INSERT INTO loottable(name) VALUES('northro_a_madman'); # :northro_a_madman_lt:
INSERT INTO loottable(name) VALUES('northro_havan_kallir'); # :northro_havan_kallir_lt:
INSERT INTO loottable(name) VALUES('northro_queen_takyaliz'); # :northro_queen_takyaliz_lt:
INSERT INTO loottable(name) VALUES('northro_translocator_ionie'); # :northro_translocator_ionie_lt:
INSERT INTO loottable(name) VALUES('northro_verrell_cogswin'); # :northro_verrell_cogswin_lt:
INSERT INTO loottable(name) VALUES('northro_an_armadillo'); # :northro_an_armadillo_lt:
INSERT INTO loottable(name) VALUES('northro_a_bat'); # :northro_a_bat_lt:
INSERT INTO loottable(name) VALUES('northro_a_brown_asp'); # :northro_a_brown_asp_lt:
INSERT INTO loottable(name) VALUES('northro_a_deathfist_pawn'); # :northro_a_deathfist_pawn_lt:
INSERT INTO loottable(name) VALUES('northro_a_decaying_skeleton'); # :northro_a_decaying_skeleton_lt:
INSERT INTO loottable(name) VALUES('northro_a_dervish_cutthroat'); # :northro_a_dervish_cutthroat_lt:
INSERT INTO loottable(name) VALUES('northro_a_desert_madman'); # :northro_a_desert_madman_lt:
INSERT INTO loottable(name) VALUES('northro_a_dune_spiderling'); # :northro_a_dune_spiderling_lt:
INSERT INTO loottable(name) VALUES('northro_a_dune_tarantula'); # :northro_a_dune_tarantula_lt:
INSERT INTO loottable(name) VALUES('northro_a_fire_beetle'); # :northro_a_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('northro_a_ghoul'); # :northro_a_ghoul_lt:
INSERT INTO loottable(name) VALUES('northro_a_giant_rattlesnake'); # :northro_a_giant_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('northro_a_gila_monster'); # :northro_a_gila_monster_lt:
INSERT INTO loottable(name) VALUES('northro_a_gila_monster_hatchling'); # :northro_a_gila_monster_hatchling_lt:
INSERT INTO loottable(name) VALUES('northro_a_guardian_tormentor'); # :northro_a_guardian_tormentor_lt:
INSERT INTO loottable(name) VALUES('northro_a_haunt'); # :northro_a_haunt_lt:
INSERT INTO loottable(name) VALUES('northro_a_jackal'); # :northro_a_jackal_lt:
INSERT INTO loottable(name) VALUES('northro_a_lamented_knight'); # :northro_a_lamented_knight_lt:
INSERT INTO loottable(name) VALUES('northro_a_large_rat'); # :northro_a_large_rat_lt:
INSERT INTO loottable(name) VALUES('northro_a_large_rattlesnake'); # :northro_a_large_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('northro_a_moss_snake'); # :northro_a_moss_snake_lt:
INSERT INTO loottable(name) VALUES('northro_a_puma'); # :northro_a_puma_lt:
INSERT INTO loottable(name) VALUES('northro_a_rattlesnake'); # :northro_a_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('northro_a_rodent'); # :northro_a_rodent_lt:
INSERT INTO loottable(name) VALUES('northro_a_sand_giant'); # :northro_a_sand_giant_lt:
INSERT INTO loottable(name) VALUES('northro_a_sand_giant_elite'); # :northro_a_sand_giant_elite_lt:
INSERT INTO loottable(name) VALUES('northro_a_sand_scarab'); # :northro_a_sand_scarab_lt:
INSERT INTO loottable(name) VALUES('northro_a_sand_scarab_hatchling'); # :northro_a_sand_scarab_hatchling_lt:
INSERT INTO loottable(name) VALUES('northro_a_shriveled_mummy'); # :northro_a_shriveled_mummy_lt:
INSERT INTO loottable(name) VALUES('northro_a_skeleton'); # :northro_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('northro_a_spirit'); # :northro_a_spirit_lt:
INSERT INTO loottable(name) VALUES('northro_a_stonesnake'); # :northro_a_stonesnake_lt:
INSERT INTO loottable(name) VALUES('northro_a_young_gila_monster'); # :northro_a_young_gila_monster_lt:
INSERT INTO loottable(name) VALUES('northro_a_young_puma'); # :northro_a_young_puma_lt:
INSERT INTO loottable(name) VALUES('northro_a_zombie'); # :northro_a_zombie_lt:
INSERT INTO loottable(name) VALUES('northro_daevyd_londayl'); # :northro_daevyd_londayl_lt:
INSERT INTO loottable(name) VALUES('northro_deathfist_pawn'); # :northro_deathfist_pawn_lt:
INSERT INTO loottable(name) VALUES('northro_dereu_ztrtn'); # :northro_dereu_ztrtn_lt:
INSERT INTO loottable(name) VALUES('northro_dizzl_nulzik'); # :northro_dizzl_nulzik_lt:
INSERT INTO loottable(name) VALUES('northro_dorn_bdynn'); # :northro_dorn_bdynn_lt:
INSERT INTO loottable(name) VALUES('northro_dry_bones_skeleton'); # :northro_dry_bones_skeleton_lt:
INSERT INTO loottable(name) VALUES('northro_efrelle_treiui'); # :northro_efrelle_treiui_lt:
INSERT INTO loottable(name) VALUES('northro_escon_quickbow'); # :northro_escon_quickbow_lt:
INSERT INTO loottable(name) VALUES('northro_guard_brendyl'); # :northro_guard_brendyl_lt:
INSERT INTO loottable(name) VALUES('northro_guard_doolin'); # :northro_guard_doolin_lt:
INSERT INTO loottable(name) VALUES('northro_guard_fintran'); # :northro_guard_fintran_lt:
INSERT INTO loottable(name) VALUES('northro_guard_sheg'); # :northro_guard_sheg_lt:
INSERT INTO loottable(name) VALUES('northro_guard_stoutman'); # :northro_guard_stoutman_lt:
INSERT INTO loottable(name) VALUES('northro_innkeep_tozie'); # :northro_innkeep_tozie_lt:
INSERT INTO loottable(name) VALUES('northro_innkeep_valon'); # :northro_innkeep_valon_lt:
INSERT INTO loottable(name) VALUES('northro_juni_sandfisher'); # :northro_juni_sandfisher_lt:
INSERT INTO loottable(name) VALUES('northro_lamriiel_mistigone'); # :northro_lamriiel_mistigone_lt:
INSERT INTO loottable(name) VALUES('northro_lydl_the_great'); # :northro_lydl_the_great_lt:
INSERT INTO loottable(name) VALUES('northro_magus_arindri'); # :northro_magus_arindri_lt:
INSERT INTO loottable(name) VALUES('northro_murissa_sandwhisper'); # :northro_murissa_sandwhisper_lt:
INSERT INTO loottable(name) VALUES('northro_odwren_werat'); # :northro_odwren_werat_lt:
INSERT INTO loottable(name) VALUES('northro_paege_stirratin'); # :northro_paege_stirratin_lt:
INSERT INTO loottable(name) VALUES('northro_peridor_sargar'); # :northro_peridor_sargar_lt:
INSERT INTO loottable(name) VALUES('northro_puntar_sandfisher'); # :northro_puntar_sandfisher_lt:
INSERT INTO loottable(name) VALUES('northro_rahotep'); # :northro_rahotep_lt:
INSERT INTO loottable(name) VALUES('northro_rargahob_dursaar'); # :northro_rargahob_dursaar_lt:
INSERT INTO loottable(name) VALUES('northro_reidar_elsai'); # :northro_reidar_elsai_lt:
INSERT INTO loottable(name) VALUES('northro_roriella_vellestan'); # :northro_roriella_vellestan_lt:
INSERT INTO loottable(name) VALUES('northro_ruanya_windleaf'); # :northro_ruanya_windleaf_lt:
INSERT INTO loottable(name) VALUES('northro_shelie_dikop'); # :northro_shelie_dikop_lt:
INSERT INTO loottable(name) VALUES('northro_soulbinder_ragni'); # :northro_soulbinder_ragni_lt:
INSERT INTO loottable(name) VALUES('northro_spoolie_gee'); # :northro_spoolie_gee_lt:
INSERT INTO loottable(name) VALUES('northro_takvalnakor'); # :northro_takvalnakor_lt:
INSERT INTO loottable(name) VALUES('northro_tarakix_vrasyrn'); # :northro_tarakix_vrasyrn_lt:
INSERT INTO loottable(name) VALUES('northro_tira_sandfisher'); # :northro_tira_sandfisher_lt:
INSERT INTO loottable(name) VALUES('northro_wenthea_bruann'); # :northro_wenthea_bruann_lt:
