(:relic_a_blinding_spiritlight_lt:, :lightstone_ld:, 1),
(:relic_a_dry_husk_abberation_lt:, :fine_steel_ld:, 1),
(:relic_a_roving_cyclone_lt:, :fine_steel_ld:, 1),
(:relic_a_scrykin_shopper_lt:, :fine_steel_ld:, 1),
(:relic_an_unyielding_edifice_lt:, :fine_steel_ld:, 1),
(:relic_a_blinding_spiritlight_lt:, :lightstone_ld:, 1),
