UPDATE npc_types SET loottable_id = :relic_ashenback_lt: WHERE id in (370084); # #Ashenback 80
UPDATE npc_types SET loottable_id = :relic_a_crashing_wave_lt: WHERE id in (370083); # #a_crashing_wave 74
UPDATE npc_types SET loottable_id = :relic_a_mud_spirit_lt: WHERE id in (370071); # #a_mud_spirit 74
UPDATE npc_types SET loottable_id = :relic_lyban_lt: WHERE id in (370091); # #Lyban 74
UPDATE npc_types SET loottable_id = :relic_maru_the_twelfth_born_lt: WHERE id in (370034); # #Maru_the_Twelfth_Born 71
UPDATE npc_types SET loottable_id = :relic_shardrahn_lt: WHERE id in (370019); # #Shar`Drahn 80
UPDATE npc_types SET loottable_id = :relic_tsikut_lt: WHERE id in (370060); # #Tsikut 80
UPDATE npc_types SET loottable_id = :relic_xanthrin_of_deep_strata_lt: WHERE id in (370079); # #Xanthrin_of_Deep_Strata 69
UPDATE npc_types SET loottable_id = :relic_an_animated_flamespout_lt: WHERE id in (370062); # an_animated_flamespout 72
UPDATE npc_types SET loottable_id = :relic_an_aqueous_healer_lt: WHERE id in (370046); # an_aqueous_healer 72
UPDATE npc_types SET loottable_id = :relic_an_earthen_construct_lt: WHERE id in (370067); # an_earthen_construct 72
UPDATE npc_types SET loottable_id = :relic_an_earthern_mage_lt: WHERE id in (370073); # an_earthern_mage 70
UPDATE npc_types SET loottable_id = :relic_an_enthralling_gale_lt: WHERE id in (370017); # an_enthralling_gale 70
UPDATE npc_types SET loottable_id = :relic_an_everwatching_warden_lt: WHERE id in (370037); # an_everwatching_warden 71
UPDATE npc_types SET loottable_id = :relic_an_unbreakable_edifice_lt: WHERE id in (370030); # an_unbreakable_edifice 71
UPDATE npc_types SET loottable_id = :relic_an_unyielding_edifice_lt: WHERE id in (370027); # an_unyielding_edifice 70
UPDATE npc_types SET loottable_id = :relic_archmage_of_relic_lt: WHERE id in (370082); # Archmage_of_Relic 72
UPDATE npc_types SET loottable_id = :relic_arena_overseer_lt: WHERE id in (370021); # Arena_Overseer 75
UPDATE npc_types SET loottable_id = :relic_arkon_of_the_sixth_circle_lt: WHERE id in (370041); # Arkon_of_the_Sixth_Circle 68
UPDATE npc_types SET loottable_id = :relic_a_blinding_spiritlight_lt: WHERE id in (370072); # a_blinding_spiritlight 71
UPDATE npc_types SET loottable_id = :relic_a_bone_walker_lt: WHERE id in (370009); # a_bone_walker 70
UPDATE npc_types SET loottable_id = :relic_a_courtyard_air_current_lt: WHERE id in (370035); # a_courtyard_air_current 70
UPDATE npc_types SET loottable_id = :relic_a_courtyard_earth_pile_lt: WHERE id in (370039); # a_courtyard_earth_pile 72
UPDATE npc_types SET loottable_id = :relic_a_courtyard_water_spout_lt: WHERE id in (370031); # a_courtyard_water_spout 70
UPDATE npc_types SET loottable_id = :relic_a_crazed_scrykin_lt: WHERE id in (370042, 370055); # a_crazed_scrykin 68
UPDATE npc_types SET loottable_id = :relic_a_cresting_wave_lt: WHERE id in (370076); # a_cresting_wave 70
UPDATE npc_types SET loottable_id = :relic_a_dry_husk_abberation_lt: WHERE id in (370004); # a_dry_husk_abberation 70
UPDATE npc_types SET loottable_id = :relic_a_fiery_sorcerer_lt: WHERE id in (370064); # a_fiery_sorcerer 72
UPDATE npc_types SET loottable_id = :relic_a_forged_steel_healer_lt: WHERE id in (370044); # a_forged_steel_healer 71
UPDATE npc_types SET loottable_id = :relic_a_granite_monstrosity_lt: WHERE id in (370087); # a_granite_monstrosity 71
UPDATE npc_types SET loottable_id = :relic_a_gravel_spellbinder_lt: WHERE id in (370065); # a_gravel_spellbinder 71
UPDATE npc_types SET loottable_id = :relic_a_living_vortex_lt: WHERE id in (370014); # a_living_vortex 70
UPDATE npc_types SET loottable_id = :relic_a_lost_scrykin_attendant_lt: WHERE id in (370003); # a_lost_scrykin_attendant 70
UPDATE npc_types SET loottable_id = :relic_a_lost_scrykin_servant_lt: WHERE id in (370000, 370001, 370002, 370016, 370028, 370029, 370032, 370040, 370045, 370047, 370054, 370058, 370061, 370063, 370069, 370070, 370075, 370077, 370078); # a_lost_scrykin_servant 70
UPDATE npc_types SET loottable_id = :relic_a_mad_scrykin_lt: WHERE id in (370049, 370051); # a_mad_scrykin 68
UPDATE npc_types SET loottable_id = :relic_a_quivering_flesh_horror_lt: WHERE id in (370089); # a_quivering_flesh_horror 70
UPDATE npc_types SET loottable_id = :relic_a_relic_water_sprite_lt: WHERE id in (370048); # a_relic_water_sprite 70
UPDATE npc_types SET loottable_id = :relic_a_roving_cyclone_lt: WHERE id in (370068); # a_roving_cyclone 70
UPDATE npc_types SET loottable_id = :relic_a_scrykin_attendant_lt: WHERE id in (370086); # a_scrykin_attendant 71
UPDATE npc_types SET loottable_id = :relic_a_scrykin_customer_lt: WHERE id in (370043); # a_scrykin_customer 70
UPDATE npc_types SET loottable_id = :relic_a_scrykin_helper_lt: WHERE id in (370053); # a_scrykin_helper 71
UPDATE npc_types SET loottable_id = :relic_a_scrykin_servant_lt: WHERE id in (370022); # a_scrykin_servant 71
UPDATE npc_types SET loottable_id = :relic_a_scrykin_shopper_lt: WHERE id in (370025); # a_scrykin_shopper 70
UPDATE npc_types SET loottable_id = :relic_a_scrykin_traveller_lt: WHERE id in (370052); # a_scrykin_traveller 71
UPDATE npc_types SET loottable_id = :relic_a_scrykin_wanderer_lt: WHERE id in (370024); # a_scrykin_wanderer 71
UPDATE npc_types SET loottable_id = :relic_a_silent_guardian_lt: WHERE id in (370036); # a_silent_guardian 71
UPDATE npc_types SET loottable_id = :relic_a_spell_whip_lt: WHERE id in (370056); # a_spell_whip 72
UPDATE npc_types SET loottable_id = :relic_a_supply_runner_lt: WHERE id in (370018, 370050, 370092, 370093, 370094, 370095, 370096, 370097); # a_supply_runner 68
UPDATE npc_types SET loottable_id = :relic_a_tellengard_lt: WHERE id in (370033, 370038); # a_Tellengard 68
UPDATE npc_types SET loottable_id = :relic_a_torturing_flesh_brute_lt: WHERE id in (370074); # a_torturing_flesh_brute 70
UPDATE npc_types SET loottable_id = :relic_a_towering_bonestich_lt: WHERE id in (370007); # a_towering_bonestich 70
UPDATE npc_types SET loottable_id = :relic_a_twisted_flesh_fiend_lt: WHERE id in (370088); # a_twisted_flesh_fiend 70
UPDATE npc_types SET loottable_id = :relic_borso_lt: WHERE id in (370020); # Borso 71
UPDATE npc_types SET loottable_id = :relic_gkil_zon_lt: WHERE id in (370006); # Gkil_Zon 71
UPDATE npc_types SET loottable_id = :relic_goroth_lt: WHERE id in (370023); # Goroth 71
UPDATE npc_types SET loottable_id = :relic_gyruth_lt: WHERE id in (370012); # Gyruth 71
UPDATE npc_types SET loottable_id = :relic_head_servant_hithorin_lt: WHERE id in (370090); # Head_Servant_Hithorin 68
UPDATE npc_types SET loottable_id = :relic_hurlinor_of_the_fifth_circle_lt: WHERE id in (370057); # Hurlinor_of_the_Fifth_Circle 68
UPDATE npc_types SET loottable_id = :relic_kachnt_of_the_fourth_circle_lt: WHERE id in (370066); # KaChnt_of_the_Fourth_Circle 68
UPDATE npc_types SET loottable_id = :relic_krack_lt: WHERE id in (370011); # Krack 71
UPDATE npc_types SET loottable_id = :relic_myath_lt: WHERE id in (370013); # Myath 71
UPDATE npc_types SET loottable_id = :relic_ngroth_lt: WHERE id in (370015); # Ngroth 71
UPDATE npc_types SET loottable_id = :relic_rorin_lt: WHERE id in (370026); # Rorin 71
UPDATE npc_types SET loottable_id = :relic_sharlash_the_ninthborn_lt: WHERE id in (370085); # Sharlash_the_Ninthborn 71
UPDATE npc_types SET loottable_id = :relic_tenaro_the_arcane_lt: WHERE id in (370080); # Tenaro_the_Arcane 71
UPDATE npc_types SET loottable_id = :relic_thanus_the_eleventh_born_lt: WHERE id in (370081); # Thanus_the_Eleventh_Born 72
UPDATE npc_types SET loottable_id = :relic___lt: WHERE id in (370005, 370008, 370010, 370059); # _ 70
