INSERT INTO loottable(name) VALUES('skylance_arkahn'); # :skylance_arkahn_lt:
INSERT INTO loottable(name) VALUES('skylance_assistant_gareth'); # :skylance_assistant_gareth_lt:
INSERT INTO loottable(name) VALUES('skylance_assistant_venorin'); # :skylance_assistant_venorin_lt:
INSERT INTO loottable(name) VALUES('skylance_a_gazing_lurker'); # :skylance_a_gazing_lurker_lt:
INSERT INTO loottable(name) VALUES('skylance_a_gnawing_roundworm'); # :skylance_a_gnawing_roundworm_lt:
INSERT INTO loottable(name) VALUES('skylance_a_mossy_bone_golem'); # :skylance_a_mossy_bone_golem_lt:
INSERT INTO loottable(name) VALUES('skylance_a_pulsing_eggsack'); # :skylance_a_pulsing_eggsack_lt:
INSERT INTO loottable(name) VALUES('skylance_a_rotting_soul'); # :skylance_a_rotting_soul_lt:
INSERT INTO loottable(name) VALUES('skylance_a_scrykin_apprentice'); # :skylance_a_scrykin_apprentice_lt:
INSERT INTO loottable(name) VALUES('skylance_a_scrykin_historian'); # :skylance_a_scrykin_historian_lt:
INSERT INTO loottable(name) VALUES('skylance_a_scrykin_student'); # :skylance_a_scrykin_student_lt:
INSERT INTO loottable(name) VALUES('skylance_a_shelled_atrocity'); # :skylance_a_shelled_atrocity_lt:
INSERT INTO loottable(name) VALUES('skylance_creeping_swarmer'); # :skylance_creeping_swarmer_lt:
INSERT INTO loottable(name) VALUES('skylance_daosheen_the_firstborn'); # :skylance_daosheen_the_firstborn_lt:
INSERT INTO loottable(name) VALUES('skylance_firefeather'); # :skylance_firefeather_lt:
INSERT INTO loottable(name) VALUES('skylance_head_librarian_magus'); # :skylance_head_librarian_magus_lt:
INSERT INTO loottable(name) VALUES('skylance_lamprey_swarmer'); # :skylance_lamprey_swarmer_lt:
INSERT INTO loottable(name) VALUES('skylance_sentinel_of_skylance'); # :skylance_sentinel_of_skylance_lt:
INSERT INTO loottable(name) VALUES('skylance_student_joban'); # :skylance_student_joban_lt:
INSERT INTO loottable(name) VALUES('skylance__'); # :skylance___lt:
