INSERT INTO loottable(name) VALUES('southro_bratoq_jiplup'); # :southro_bratoq_jiplup_lt:
INSERT INTO loottable(name) VALUES('southro_dimbwicket_middifoodle'); # :southro_dimbwicket_middifoodle_lt:
INSERT INTO loottable(name) VALUES('southro_gilfal'); # :southro_gilfal_lt:
INSERT INTO loottable(name) VALUES('southro_gnorble_iceflinger'); # :southro_gnorble_iceflinger_lt:
INSERT INTO loottable(name) VALUES('southro_instructor_maerceci'); # :southro_instructor_maerceci_lt:
INSERT INTO loottable(name) VALUES('southro_keelee_rayin'); # :southro_keelee_rayin_lt:
INSERT INTO loottable(name) VALUES('southro_plinkletop_cogstopper'); # :southro_plinkletop_cogstopper_lt:
INSERT INTO loottable(name) VALUES('southro_saeko_lvinec'); # :southro_saeko_lvinec_lt:
INSERT INTO loottable(name) VALUES('southro_tacots_silentblade'); # :southro_tacots_silentblade_lt:
INSERT INTO loottable(name) VALUES('southro_translocator_tradil'); # :southro_translocator_tradil_lt:
INSERT INTO loottable(name) VALUES('southro_andad_filla'); # :southro_andad_filla_lt:
INSERT INTO loottable(name) VALUES('southro_anumnan_dathry'); # :southro_anumnan_dathry_lt:
INSERT INTO loottable(name) VALUES('southro_an_asp'); # :southro_an_asp_lt:
INSERT INTO loottable(name) VALUES('southro_an_orcish_flameforger'); # :southro_an_orcish_flameforger_lt:
INSERT INTO loottable(name) VALUES('southro_an_orc_centurion'); # :southro_an_orc_centurion_lt:
INSERT INTO loottable(name) VALUES('southro_an_orc_cleric'); # :southro_an_orc_cleric_lt:
INSERT INTO loottable(name) VALUES('southro_an_orc_priest'); # :southro_an_orc_priest_lt:
INSERT INTO loottable(name) VALUES('southro_an_orc_warrior'); # :southro_an_orc_warrior_lt:
INSERT INTO loottable(name) VALUES('southro_artist_passia'); # :southro_artist_passia_lt:
INSERT INTO loottable(name) VALUES('southro_a_bloody_terrorantuling'); # :southro_a_bloody_terrorantuling_lt:
INSERT INTO loottable(name) VALUES('southro_a_caiman'); # :southro_a_caiman_lt:
INSERT INTO loottable(name) VALUES('southro_a_cistern_asp'); # :southro_a_cistern_asp_lt:
INSERT INTO loottable(name) VALUES('southro_a_crocodile'); # :southro_a_crocodile_lt:
INSERT INTO loottable(name) VALUES('southro_a_crypt_mummy'); # :southro_a_crypt_mummy_lt:
INSERT INTO loottable(name) VALUES('southro_a_darkweed_snake'); # :southro_a_darkweed_snake_lt:
INSERT INTO loottable(name) VALUES('southro_a_deepwater_goblin'); # :southro_a_deepwater_goblin_lt:
INSERT INTO loottable(name) VALUES('southro_a_dervish_cutthroat'); # :southro_a_dervish_cutthroat_lt:
INSERT INTO loottable(name) VALUES('southro_a_desert_madman'); # :southro_a_desert_madman_lt:
INSERT INTO loottable(name) VALUES('southro_a_desert_tarantula'); # :southro_a_desert_tarantula_lt:
INSERT INTO loottable(name) VALUES('southro_a_dune_tarantula'); # :southro_a_dune_tarantula_lt:
INSERT INTO loottable(name) VALUES('southro_a_fire_beetle'); # :southro_a_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('southro_a_ghoul'); # :southro_a_ghoul_lt:
INSERT INTO loottable(name) VALUES('southro_a_jackal'); # :southro_a_jackal_lt:
INSERT INTO loottable(name) VALUES('southro_a_moss_snake'); # :southro_a_moss_snake_lt:
INSERT INTO loottable(name) VALUES('southro_a_puma'); # :southro_a_puma_lt:
INSERT INTO loottable(name) VALUES('southro_a_row_boat'); # :southro_a_row_boat_lt:
INSERT INTO loottable(name) VALUES('southro_a_sand_giant_elite'); # :southro_a_sand_giant_elite_lt:
INSERT INTO loottable(name) VALUES('southro_a_sand_scarab'); # :southro_a_sand_scarab_lt:
INSERT INTO loottable(name) VALUES('southro_a_shriveled_mummy'); # :southro_a_shriveled_mummy_lt:
INSERT INTO loottable(name) VALUES('southro_a_skeleton'); # :southro_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('southro_a_spectre'); # :southro_a_spectre_lt:
INSERT INTO loottable(name) VALUES('southro_a_tree_snake'); # :southro_a_tree_snake_lt:
INSERT INTO loottable(name) VALUES('southro_a_wayward_kiraikuei'); # :southro_a_wayward_kiraikuei_lt:
INSERT INTO loottable(name) VALUES('southro_a_young_ronin'); # :southro_a_young_ronin_lt:
INSERT INTO loottable(name) VALUES('southro_a_zombie'); # :southro_a_zombie_lt:
INSERT INTO loottable(name) VALUES('southro_becoreen_pathfinder'); # :southro_becoreen_pathfinder_lt:
INSERT INTO loottable(name) VALUES('southro_boadiel_sharen'); # :southro_boadiel_sharen_lt:
INSERT INTO loottable(name) VALUES('southro_bryntelanka_battlebringer'); # :southro_bryntelanka_battlebringer_lt:
INSERT INTO loottable(name) VALUES('southro_cazel'); # :southro_cazel_lt:
INSERT INTO loottable(name) VALUES('southro_dahdd_jonne'); # :southro_dahdd_jonne_lt:
INSERT INTO loottable(name) VALUES('southro_dible_hedledrap'); # :southro_dible_hedledrap_lt:
INSERT INTO loottable(name) VALUES('southro_dryssa_hammerstock'); # :southro_dryssa_hammerstock_lt:
INSERT INTO loottable(name) VALUES('southro_dry_bones_skeleton'); # :southro_dry_bones_skeleton_lt:
INSERT INTO loottable(name) VALUES('southro_eewatt_halmoore'); # :southro_eewatt_halmoore_lt:
INSERT INTO loottable(name) VALUES('southro_farwein_windrun'); # :southro_farwein_windrun_lt:
INSERT INTO loottable(name) VALUES('southro_feriern_telenthar'); # :southro_feriern_telenthar_lt:
INSERT INTO loottable(name) VALUES('southro_friggal_bribbitz'); # :southro_friggal_bribbitz_lt:
INSERT INTO loottable(name) VALUES('southro_gadallion'); # :southro_gadallion_lt:
INSERT INTO loottable(name) VALUES('southro_garcon_huntmaster'); # :southro_garcon_huntmaster_lt:
INSERT INTO loottable(name) VALUES('southro_ghoul_of_takish-hiz'); # :southro_ghoul_of_takish-hiz_lt:
INSERT INTO loottable(name) VALUES('southro_grusyll_eshaan'); # :southro_grusyll_eshaan_lt:
INSERT INTO loottable(name) VALUES('southro_haele_straedhon'); # :southro_haele_straedhon_lt:
INSERT INTO loottable(name) VALUES('southro_hurgo_felcind'); # :southro_hurgo_felcind_lt:
INSERT INTO loottable(name) VALUES('southro_innkeep_marnan'); # :southro_innkeep_marnan_lt:
INSERT INTO loottable(name) VALUES('southro_innkeep_tizzy'); # :southro_innkeep_tizzy_lt:
INSERT INTO loottable(name) VALUES('southro_isslana'); # :southro_isslana_lt:
INSERT INTO loottable(name) VALUES('southro_jeysen_voon'); # :southro_jeysen_voon_lt:
INSERT INTO loottable(name) VALUES('southro_kallei_ribblok'); # :southro_kallei_ribblok_lt:
INSERT INTO loottable(name) VALUES('southro_lcangar_goodwell'); # :southro_lcangar_goodwell_lt:
INSERT INTO loottable(name) VALUES('southro_maeggi_lohndl'); # :southro_maeggi_lohndl_lt:
INSERT INTO loottable(name) VALUES('southro_magus_jerira'); # :southro_magus_jerira_lt:
INSERT INTO loottable(name) VALUES('southro_mantrek_needlebender'); # :southro_mantrek_needlebender_lt:
INSERT INTO loottable(name) VALUES('southro_merchant_ulyssa'); # :southro_merchant_ulyssa_lt:
INSERT INTO loottable(name) VALUES('southro_mograk'); # :southro_mograk_lt:
INSERT INTO loottable(name) VALUES('southro_nura_dumont'); # :southro_nura_dumont_lt:
INSERT INTO loottable(name) VALUES('southro_orc_oracle'); # :southro_orc_oracle_lt:
INSERT INTO loottable(name) VALUES('southro_ortallius'); # :southro_ortallius_lt:
INSERT INTO loottable(name) VALUES('southro_rack_stonebelly'); # :southro_rack_stonebelly_lt:
INSERT INTO loottable(name) VALUES('southro_ranzall_netcaster'); # :southro_ranzall_netcaster_lt:
INSERT INTO loottable(name) VALUES('southro_rathmana_allin'); # :southro_rathmana_allin_lt:
INSERT INTO loottable(name) VALUES('southro_ruwakka'); # :southro_ruwakka_lt:
INSERT INTO loottable(name) VALUES('southro_sandgiant_husam'); # :southro_sandgiant_husam_lt:
INSERT INTO loottable(name) VALUES('southro_scout_miigle'); # :southro_scout_miigle_lt:
INSERT INTO loottable(name) VALUES('southro_selephra_giztral'); # :southro_selephra_giztral_lt:
INSERT INTO loottable(name) VALUES('southro_smith_tvysa'); # :southro_smith_tvysa_lt:
INSERT INTO loottable(name) VALUES('southro_soulbinder_silandra'); # :southro_soulbinder_silandra_lt:
INSERT INTO loottable(name) VALUES('southro_synthan'); # :southro_synthan_lt:
INSERT INTO loottable(name) VALUES('southro_taeri_kuqq'); # :southro_taeri_kuqq_lt:
INSERT INTO loottable(name) VALUES('southro_taldrik_stumpystout'); # :southro_taldrik_stumpystout_lt:
INSERT INTO loottable(name) VALUES('southro_tran'); # :southro_tran_lt:
INSERT INTO loottable(name) VALUES('southro_transan'); # :southro_transan_lt:
