UPDATE npc_types SET loottable_id = :theater_anastasia_the_thought_drinker_lt: WHERE id in (380046); # #Anastasia_the_Thought_Drinker 80
UPDATE npc_types SET loottable_id = :theater_gnarlibramble_lt: WHERE id in (380018); # #Gnarlibramble 80
UPDATE npc_types SET loottable_id = :theater_mad_mary-anne_lt: WHERE id in (380040); # #Mad_Mary-Anne 80
UPDATE npc_types SET loottable_id = :theater_the_skeletal_steed_lt: WHERE id in (380029); # #The_Skeletal_Steed 76
UPDATE npc_types SET loottable_id = :theater_valik_the_cruel_lt: WHERE id in (380059); # #Valik_the_Cruel 80
UPDATE npc_types SET loottable_id = :theater_vasella_fireblood_lt: WHERE id in (380038); # #Vasella_Fireblood 80
UPDATE npc_types SET loottable_id = :theater_an_ancient_sentinel_lt: WHERE id in (380036, 380037); # an_ancient_sentinel 75
UPDATE npc_types SET loottable_id = :theater_an_erratic_bat_lt: WHERE id in (380033); # an_erratic_bat 73
UPDATE npc_types SET loottable_id = :theater_a_bellowing_banshee_lt: WHERE id in (380047, 380049); # a_bellowing_banshee 75
UPDATE npc_types SET loottable_id = :theater_a_bloodbonded_archimage_lt: WHERE id in (380002, 380019); # a_bloodbonded_archimage 74
UPDATE npc_types SET loottable_id = :theater_a_bloodbonded_elementalist_lt: WHERE id in (380015); # a_bloodbonded_elementalist 73
UPDATE npc_types SET loottable_id = :theater_a_bloodbonded_firestarter_lt: WHERE id in (380012); # a_bloodbonded_firestarter 73
UPDATE npc_types SET loottable_id = :theater_a_bloodbonded_spellslinger_lt: WHERE id in (380003, 380017); # a_bloodbonded_spellslinger 74
UPDATE npc_types SET loottable_id = :theater_a_bloodstorm_dervish_lt: WHERE id in (380020, 380025); # a_bloodstorm_dervish 74
UPDATE npc_types SET loottable_id = :theater_a_carnivorous_plant_lt: WHERE id in (380010); # a_carnivorous_plant 73
UPDATE npc_types SET loottable_id = :theater_a_crimson_dervish_lt: WHERE id in (380021); # a_crimson_dervish 73
UPDATE npc_types SET loottable_id = :theater_a_cursed_willow_lt: WHERE id in (380057); # a_cursed_willow 73
UPDATE npc_types SET loottable_id = :theater_a_decaying_husk_lt: WHERE id in (380030, 380031); # a_decaying_husk 74
UPDATE npc_types SET loottable_id = :theater_a_gothic_watcher_lt: WHERE id in (380044); # a_gothic_watcher 73
UPDATE npc_types SET loottable_id = :theater_a_moaning_banshee_lt: WHERE id in (380027); # a_moaning_banshee 73
UPDATE npc_types SET loottable_id = :theater_a_nightmare_lt: WHERE id in (380004); # a_nightmare 73
UPDATE npc_types SET loottable_id = :theater_a_rapacious_plant_lt: WHERE id in (380006, 380011); # a_rapacious_plant 74
UPDATE npc_types SET loottable_id = :theater_a_rotting_husk_lt: WHERE id in (380028); # a_rotting_husk 73
UPDATE npc_types SET loottable_id = :theater_a_screaming_banshee_lt: WHERE id in (380041); # a_screaming_banshee 73
UPDATE npc_types SET loottable_id = :theater_a_screeching_bat_lt: WHERE id in (380026, 380032); # a_screeching_bat 75
UPDATE npc_types SET loottable_id = :theater_a_shaded_steed_lt: WHERE id in (380009, 380039); # a_shaded_steed 75
UPDATE npc_types SET loottable_id = :theater_a_shadowmane_feralist_lt: WHERE id in (380053); # a_shadowmane_feralist 73
UPDATE npc_types SET loottable_id = :theater_a_shadowmane_spiritseeker_lt: WHERE id in (380035); # a_shadowmane_spiritseeker 73
UPDATE npc_types SET loottable_id = :theater_a_shadowmane_spiritualist_lt: WHERE id in (380022, 380023); # a_shadowmane_spiritualist 75
UPDATE npc_types SET loottable_id = :theater_a_truefaith_coercer_lt: WHERE id in (380016); # a_Truefaith_coercer 73
UPDATE npc_types SET loottable_id = :theater_a_truefaith_deathcaster_lt: WHERE id in (380001, 380005); # a_Truefaith_deathcaster 75
UPDATE npc_types SET loottable_id = :theater_a_truefaith_deathdealer_lt: WHERE id in (380013); # a_Truefaith_deathdealer 73
UPDATE npc_types SET loottable_id = :theater_a_truefaith_enticer_lt: WHERE id in (380014, 380034); # a_Truefaith_enticer 74
UPDATE npc_types SET loottable_id = :theater_a_twisted_steed_lt: WHERE id in (380007); # a_twisted_steed 73
UPDATE npc_types SET loottable_id = :theater_a_vicious_shadowmane_lt: WHERE id in (380056, 380058); # a_vicious_shadowmane 75
UPDATE npc_types SET loottable_id = :theater_a_wailing_banshee_lt: WHERE id in (380042, 380051); # a_wailing_banshee 74
UPDATE npc_types SET loottable_id = :theater_a_wandering_steed_lt: WHERE id in (380008, 380024); # a_wandering_steed 75
UPDATE npc_types SET loottable_id = :theater_a_wretched_willow_lt: WHERE id in (380054, 380055); # a_wretched_willow 74
UPDATE npc_types SET loottable_id = :theater_eodue_the_pure_lt: WHERE id in (380000); # Eodue_the_Pure 80
UPDATE npc_types SET loottable_id = :theater_maestro_tanlor_lt: WHERE id in (380052); # Maestro_Tan`lor 80
UPDATE npc_types SET loottable_id = :theater_slumbering_audience_member_lt: WHERE id in (380043, 380045, 380048, 380050); # Slumbering_Audience_Member 72
