INSERT INTO loottable(name) VALUES('fallen_exterminator_cedrin'); # :fallen_exterminator_cedrin_lt:
INSERT INTO loottable(name) VALUES('fallen_gayle_weaven'); # :fallen_gayle_weaven_lt:
INSERT INTO loottable(name) VALUES('fallen_general_arbin_derrex'); # :fallen_general_arbin_derrex_lt:
INSERT INTO loottable(name) VALUES('fallen_ghanlin_skyphire'); # :fallen_ghanlin_skyphire_lt:
INSERT INTO loottable(name) VALUES('fallen_gorion_telldmare'); # :fallen_gorion_telldmare_lt:
INSERT INTO loottable(name) VALUES('fallen_illithi_nollith'); # :fallen_illithi_nollith_lt:
INSERT INTO loottable(name) VALUES('fallen_kordian_keshalian'); # :fallen_kordian_keshalian_lt:
INSERT INTO loottable(name) VALUES('fallen_lanken_rjarn'); # :fallen_lanken_rjarn_lt:
INSERT INTO loottable(name) VALUES('fallen_laoni_reista'); # :fallen_laoni_reista_lt:
INSERT INTO loottable(name) VALUES('fallen_markus_jaevins'); # :fallen_markus_jaevins_lt:
INSERT INTO loottable(name) VALUES('fallen_nerth_sailwind'); # :fallen_nerth_sailwind_lt:
INSERT INTO loottable(name) VALUES('fallen_sentinel_aegeo'); # :fallen_sentinel_aegeo_lt:
INSERT INTO loottable(name) VALUES('fallen_sentinel_belario'); # :fallen_sentinel_belario_lt:
INSERT INTO loottable(name) VALUES('fallen_sentinel_silvis'); # :fallen_sentinel_silvis_lt:
INSERT INTO loottable(name) VALUES('fallen_tensia_hauden'); # :fallen_tensia_hauden_lt:
INSERT INTO loottable(name) VALUES('fallen_translocator_eniela'); # :fallen_translocator_eniela_lt:
INSERT INTO loottable(name) VALUES('fallen_trevis_malfin'); # :fallen_trevis_malfin_lt:
INSERT INTO loottable(name) VALUES('fallen_weligon_steelherder'); # :fallen_weligon_steelherder_lt:
INSERT INTO loottable(name) VALUES('fallen_an_infiltrator_pyromancer'); # :fallen_an_infiltrator_pyromancer_lt:
INSERT INTO loottable(name) VALUES('fallen_an_infiltrator_sapper'); # :fallen_an_infiltrator_sapper_lt:
INSERT INTO loottable(name) VALUES('fallen_a_blind_dreamer'); # :fallen_a_blind_dreamer_lt:
INSERT INTO loottable(name) VALUES('fallen_a_bone_golem'); # :fallen_a_bone_golem_lt:
INSERT INTO loottable(name) VALUES('fallen_a_bone_golem_horror'); # :fallen_a_bone_golem_horror_lt:
INSERT INTO loottable(name) VALUES('fallen_a_bone_golem_terrorizer'); # :fallen_a_bone_golem_terrorizer_lt:
INSERT INTO loottable(name) VALUES('fallen_a_bone_golem_tormentor'); # :fallen_a_bone_golem_tormentor_lt:
INSERT INTO loottable(name) VALUES('fallen_a_book_dervish'); # :fallen_a_book_dervish_lt:
INSERT INTO loottable(name) VALUES('fallen_a_burning_book_dervish'); # :fallen_a_burning_book_dervish_lt:
INSERT INTO loottable(name) VALUES('fallen_a_burning_tome_dervish'); # :fallen_a_burning_tome_dervish_lt:
INSERT INTO loottable(name) VALUES('fallen_a_burning_tome_whirlwind'); # :fallen_a_burning_tome_whirlwind_lt:
INSERT INTO loottable(name) VALUES('fallen_a_craft_keeper_adept'); # :fallen_a_craft_keeper_adept_lt:
INSERT INTO loottable(name) VALUES('fallen_a_craft_keeper_initiate'); # :fallen_a_craft_keeper_initiate_lt:
INSERT INTO loottable(name) VALUES('fallen_a_craft_keeper_mindbender'); # :fallen_a_craft_keeper_mindbender_lt:
INSERT INTO loottable(name) VALUES('fallen_a_crimson_hand_adept'); # :fallen_a_crimson_hand_adept_lt:
INSERT INTO loottable(name) VALUES('fallen_a_crimson_hand_firecaller'); # :fallen_a_crimson_hand_firecaller_lt:
INSERT INTO loottable(name) VALUES('fallen_a_crimson_hand_initiate'); # :fallen_a_crimson_hand_initiate_lt:
INSERT INTO loottable(name) VALUES('fallen_a_cultist_captive'); # :fallen_a_cultist_captive_lt:
INSERT INTO loottable(name) VALUES('fallen_a_dead_civilian'); # :fallen_a_dead_civilian_lt:
INSERT INTO loottable(name) VALUES('fallen_a_dead_sentinel'); # :fallen_a_dead_sentinel_lt:
INSERT INTO loottable(name) VALUES('fallen_a_deepwater_knight'); # :fallen_a_deepwater_knight_lt:
INSERT INTO loottable(name) VALUES('fallen_a_deepwater_knights_adept'); # :fallen_a_deepwater_knights_adept_lt:
INSERT INTO loottable(name) VALUES('fallen_a_deepwater_knights_initiate'); # :fallen_a_deepwater_knights_initiate_lt:
INSERT INTO loottable(name) VALUES('fallen_a_deepwater_knight_superior'); # :fallen_a_deepwater_knight_superior_lt:
INSERT INTO loottable(name) VALUES('fallen_a_dock_rat'); # :fallen_a_dock_rat_lt:
INSERT INTO loottable(name) VALUES('fallen_a_fallen_deepwater_knight'); # :fallen_a_fallen_deepwater_knight_lt:
INSERT INTO loottable(name) VALUES('fallen_a_fallen_erudite_sentinel'); # :fallen_a_fallen_erudite_sentinel_lt:
INSERT INTO loottable(name) VALUES('fallen_a_fallen_skeleton_tunneler'); # :fallen_a_fallen_skeleton_tunneler_lt:
INSERT INTO loottable(name) VALUES('fallen_a_gate_caller_adept'); # :fallen_a_gate_caller_adept_lt:
INSERT INTO loottable(name) VALUES('fallen_a_gate_caller_initiate'); # :fallen_a_gate_caller_initiate_lt:
INSERT INTO loottable(name) VALUES('fallen_a_gate_caller_voidchanneler'); # :fallen_a_gate_caller_voidchanneler_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_brute'); # :fallen_a_heretic_brute_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_commander'); # :fallen_a_heretic_commander_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_deathsummoner'); # :fallen_a_heretic_deathsummoner_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_deathweaver'); # :fallen_a_heretic_deathweaver_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_death_dabbler'); # :fallen_a_heretic_death_dabbler_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_fell_blade'); # :fallen_a_heretic_fell_blade_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_fell_blademaster'); # :fallen_a_heretic_fell_blademaster_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_fell_vindicator'); # :fallen_a_heretic_fell_vindicator_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_fell_warden'); # :fallen_a_heretic_fell_warden_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_hierophant'); # :fallen_a_heretic_hierophant_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_infiltrator'); # :fallen_a_heretic_infiltrator_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_occultist_dabbler'); # :fallen_a_heretic_occultist_dabbler_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_pillager'); # :fallen_a_heretic_pillager_lt:
INSERT INTO loottable(name) VALUES('fallen_a_heretic_ravager'); # :fallen_a_heretic_ravager_lt:
INSERT INTO loottable(name) VALUES('fallen_a_rat-chewed_corpse'); # :fallen_a_rat-chewed_corpse_lt:
INSERT INTO loottable(name) VALUES('fallen_a_ravenous_dock_rat'); # :fallen_a_ravenous_dock_rat_lt:
INSERT INTO loottable(name) VALUES('fallen_a_skeleton_sentinel'); # :fallen_a_skeleton_sentinel_lt:
INSERT INTO loottable(name) VALUES('fallen_a_skeleton_sentry'); # :fallen_a_skeleton_sentry_lt:
INSERT INTO loottable(name) VALUES('fallen_a_skeleton_tunneler'); # :fallen_a_skeleton_tunneler_lt:
INSERT INTO loottable(name) VALUES('fallen_a_skeleton_warrior'); # :fallen_a_skeleton_warrior_lt:
INSERT INTO loottable(name) VALUES('fallen_a_terris_thule_apostle'); # :fallen_a_terris_thule_apostle_lt:
INSERT INTO loottable(name) VALUES('fallen_a_terris_thule_cultist'); # :fallen_a_terris_thule_cultist_lt:
INSERT INTO loottable(name) VALUES('fallen_a_tome_dervish'); # :fallen_a_tome_dervish_lt:
INSERT INTO loottable(name) VALUES('fallen_a_wounded_civilian'); # :fallen_a_wounded_civilian_lt:
INSERT INTO loottable(name) VALUES('fallen_a_wounded_knight'); # :fallen_a_wounded_knight_lt:
INSERT INTO loottable(name) VALUES('fallen_spirit_of_erud'); # :fallen_spirit_of_erud_lt:
