UPDATE npc_types SET loottable_id = :housegarden_barkley_lt: WHERE id in (703051); # #Barkley 90
UPDATE npc_types SET loottable_id = :housegarden_biunahde_lt: WHERE id in (703068); # #Biunahde 90
UPDATE npc_types SET loottable_id = :housegarden_constable_erulin_lt: WHERE id in (703062); # #Constable_Erulin 85
UPDATE npc_types SET loottable_id = :housegarden_croakem_lt: WHERE id in (703066); # #Croakem 90
UPDATE npc_types SET loottable_id = :housegarden_deirdre_lt: WHERE id in (703039); # #Deirdre 85
UPDATE npc_types SET loottable_id = :housegarden_distraught_heap_lt: WHERE id in (703069); # #Distraught_Heap 90
UPDATE npc_types SET loottable_id = :housegarden_faernoc_lt: WHERE id in (703049); # #Faernoc 90
UPDATE npc_types SET loottable_id = :housegarden_gardener_aeriht_lt: WHERE id in (703044); # #Gardener_Aeriht 85
UPDATE npc_types SET loottable_id = :housegarden_ghrechla_the_patch_warden_lt: WHERE id in (703050); # #Ghrechla_the_Patch_Warden 88
UPDATE npc_types SET loottable_id = :housegarden_giladan_the_botanist_lt: WHERE id in (703038); # #Giladan_the_Botanist 88
UPDATE npc_types SET loottable_id = :housegarden_granger_rivenbel_lt: WHERE id in (703052); # #Granger_Rivenbel 85
UPDATE npc_types SET loottable_id = :housegarden_grithlan_vraniq_lt: WHERE id in (703048); # #Grithlan_Vraniq 88
UPDATE npc_types SET loottable_id = :housegarden_groundskeeper_seamus_lt: WHERE id in (703045); # #Groundskeeper_Seamus 90
UPDATE npc_types SET loottable_id = :housegarden_ikaena_the_bonesmith_lt: WHERE id in (703061); # #Ikaena_the_Bonesmith 88
UPDATE npc_types SET loottable_id = :housegarden_lost_golem_lt: WHERE id in (703018); # #Lost_Golem 88
UPDATE npc_types SET loottable_id = :housegarden_meikona_the_keeper_lt: WHERE id in (703035); # #Meikona_the_Keeper 88
UPDATE npc_types SET loottable_id = :housegarden_paltra_harins_lt: WHERE id in (703058); # #Paltra_Harins 85
UPDATE npc_types SET loottable_id = :housegarden_patch_guardian_lt: WHERE id in (703067); # #Patch_Guardian 90
UPDATE npc_types SET loottable_id = :housegarden_plomaedis_lt: WHERE id in (703060); # #Plomaedis 87
UPDATE npc_types SET loottable_id = :housegarden_rend_lt: WHERE id in (703019); # #Rend 90
UPDATE npc_types SET loottable_id = :housegarden_spensur_lt: WHERE id in (703037); # #Spensur 90
UPDATE npc_types SET loottable_id = :housegarden_therys_the_botanist_lt: WHERE id in (703001); # #Therys_the_Botanist 90
UPDATE npc_types SET loottable_id = :housegarden_an_aggressive_snake_lt: WHERE id in (703032); # an_aggressive_snake 87
UPDATE npc_types SET loottable_id = :housegarden_an_aquadervish_lt: WHERE id in (703006, 703009); # an_aquadervish 85
UPDATE npc_types SET loottable_id = :housegarden_an_bixie_guard_lt: WHERE id in (703034); # an_bixie_guard 87
UPDATE npc_types SET loottable_id = :housegarden_an_obedient_servant_lt: WHERE id in (703005); # an_obedient_servant 87
UPDATE npc_types SET loottable_id = :housegarden_athmos_the_bard_lt: WHERE id in (703000); # Athmos_the_Bard 90
UPDATE npc_types SET loottable_id = :housegarden_a_bitter_treant_lt: WHERE id in (703002); # a_bitter_treant 87
UPDATE npc_types SET loottable_id = :housegarden_a_blind_dreamer_lt: WHERE id in (703064); # a_blind_dreamer 88
UPDATE npc_types SET loottable_id = :housegarden_a_bone_crafter_lt: WHERE id in (703054, 703055); # a_bone_crafter 87
UPDATE npc_types SET loottable_id = :housegarden_a_bone_golem_lt: WHERE id in (703053, 703059); # a_bone_golem 85
UPDATE npc_types SET loottable_id = :housegarden_a_disgruntled_aquadervish_lt: WHERE id in (703021); # a_disgruntled_aquadervish 87
UPDATE npc_types SET loottable_id = :housegarden_a_forlorn_bone_golem_lt: WHERE id in (703063); # a_forlorn_bone_golem 87
UPDATE npc_types SET loottable_id = :housegarden_a_garden_bixie_lt: WHERE id in (703030, 703033); # a_garden_bixie 87
UPDATE npc_types SET loottable_id = :housegarden_a_living_heap_lt: WHERE id in (703016, 703020); # a_living_heap 85
UPDATE npc_types SET loottable_id = :housegarden_a_mad_mulch_cube_lt: WHERE id in (703025); # a_mad_mulch_cube 87
UPDATE npc_types SET loottable_id = :housegarden_a_mangy_rotdog_lt: WHERE id in (703023); # a_mangy_rotdog 87
UPDATE npc_types SET loottable_id = :housegarden_a_mulch_cube_lt: WHERE id in (703008, 703011); # a_mulch_cube 87
UPDATE npc_types SET loottable_id = :housegarden_a_peponnite_lt: WHERE id in (703036, 703041); # a_peponnite 87
UPDATE npc_types SET loottable_id = :housegarden_a_petulant_heap_lt: WHERE id in (703031); # a_petulant_heap 87
UPDATE npc_types SET loottable_id = :housegarden_a_putrified_peponnite_lt: WHERE id in (703040); # a_putrified_peponnite 87
UPDATE npc_types SET loottable_id = :housegarden_a_rotdog_lt: WHERE id in (703015, 703028); # a_rotdog 87
UPDATE npc_types SET loottable_id = :housegarden_a_servant_of_thule_lt: WHERE id in (703003, 703010); # a_servant_of_Thule 85
UPDATE npc_types SET loottable_id = :housegarden_a_souring_treant_lt: WHERE id in (703027, 703056); # a_souring_treant 87
UPDATE npc_types SET loottable_id = :housegarden_a_thornfrog_lt: WHERE id in (703046, 703047); # a_thornfrog 87
UPDATE npc_types SET loottable_id = :housegarden_a_troublesome_snake_lt: WHERE id in (703007, 703014); # a_troublesome_snake 85
UPDATE npc_types SET loottable_id = :housegarden_a_truculent_wasp_lt: WHERE id in (703029); # a_truculent_wasp 85
UPDATE npc_types SET loottable_id = :housegarden_a_wasp_lt: WHERE id in (703004); # a_wasp 85
UPDATE npc_types SET loottable_id = :housegarden_a_wicked_thornfrog_lt: WHERE id in (703042); # a_wicked_thornfrog 87
UPDATE npc_types SET loottable_id = :housegarden_eye_of_sobewiz_lt: WHERE id in (703065); # Eye_of_Sobewiz 6
UPDATE npc_types SET loottable_id = :housegarden_first_missing_bonecrafter_lt: WHERE id in (703043); # first_missing_bonecrafter 82
UPDATE npc_types SET loottable_id = :housegarden_fourth_missing_bonecrafter_lt: WHERE id in (703057); # fourth_missing_bonecrafter 82
UPDATE npc_types SET loottable_id = :housegarden_fsp-general-noeffect_lt: WHERE id in (703022); # FSP-General-NoEffect 1
UPDATE npc_types SET loottable_id = :housegarden_garden_sentinel_lt: WHERE id in (703012, 703013, 703026); # Garden_Sentinel 84
UPDATE npc_types SET loottable_id = :housegarden_second_missing_bonecrafter_lt: WHERE id in (703017); # second_missing_bonecrafter 82
UPDATE npc_types SET loottable_id = :housegarden_third_missing_bonecrafter_lt: WHERE id in (703024); # third_missing_bonecrafter 82
