INSERT INTO loottable(name) VALUES('miragulmare_an_orange_orb'); # :miragulmare_an_orange_orb_lt:
INSERT INTO loottable(name) VALUES('miragulmare_axiyiln'); # :miragulmare_axiyiln_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_battered_chest'); # :miragulmare_a_battered_chest_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_black_orb'); # :miragulmare_a_black_orb_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_blue_orb'); # :miragulmare_a_blue_orb_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_glittering_portal'); # :miragulmare_a_glittering_portal_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_green_orb'); # :miragulmare_a_green_orb_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_maimed_erudite'); # :miragulmare_a_maimed_erudite_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_red_orb'); # :miragulmare_a_red_orb_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_yellow_orb'); # :miragulmare_a_yellow_orb_lt:
INSERT INTO loottable(name) VALUES('miragulmare_gilibus_the_unseen'); # :miragulmare_gilibus_the_unseen_lt:
INSERT INTO loottable(name) VALUES('miragulmare_hiljorin'); # :miragulmare_hiljorin_lt:
INSERT INTO loottable(name) VALUES('miragulmare_mylzital'); # :miragulmare_mylzital_lt:
INSERT INTO loottable(name) VALUES('miragulmare_soul_taster'); # :miragulmare_soul_taster_lt:
INSERT INTO loottable(name) VALUES('miragulmare_utto_the_haggard'); # :miragulmare_utto_the_haggard_lt:
INSERT INTO loottable(name) VALUES('miragulmare_xilixizan'); # :miragulmare_xilixizan_lt:
INSERT INTO loottable(name) VALUES('miragulmare_xylzital'); # :miragulmare_xylzital_lt:
INSERT INTO loottable(name) VALUES('miragulmare_yilian'); # :miragulmare_yilian_lt:
INSERT INTO loottable(name) VALUES('miragulmare_ziedan_gazel'); # :miragulmare_ziedan_gazel_lt:
INSERT INTO loottable(name) VALUES('miragulmare_an_ancient_guardian'); # :miragulmare_an_ancient_guardian_lt:
INSERT INTO loottable(name) VALUES('miragulmare_an_unseen_foe'); # :miragulmare_an_unseen_foe_lt:
INSERT INTO loottable(name) VALUES('miragulmare_an_unseen_warrior'); # :miragulmare_an_unseen_warrior_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_blackened_rune'); # :miragulmare_a_blackened_rune_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_darkbone_golem'); # :miragulmare_a_darkbone_golem_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_darkshadow_golem'); # :miragulmare_a_darkshadow_golem_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_darkshadow_mephit'); # :miragulmare_a_darkshadow_mephit_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_darkshadow_raven'); # :miragulmare_a_darkshadow_raven_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_dead_erudite'); # :miragulmare_a_dead_erudite_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_feasting_raven'); # :miragulmare_a_feasting_raven_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_forgotten_guardian'); # :miragulmare_a_forgotten_guardian_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_mournful_shade'); # :miragulmare_a_mournful_shade_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_pool_of_darkness'); # :miragulmare_a_pool_of_darkness_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_shadowed_flower'); # :miragulmare_a_shadowed_flower_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_shadowed_golem'); # :miragulmare_a_shadowed_golem_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_shadowy_lurker'); # :miragulmare_a_shadowy_lurker_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_shadow_mephit'); # :miragulmare_a_shadow_mephit_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_silent_shadow'); # :miragulmare_a_silent_shadow_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_skyshadow_raven'); # :miragulmare_a_skyshadow_raven_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_sorrowful_shade'); # :miragulmare_a_sorrowful_shade_lt:
INSERT INTO loottable(name) VALUES('miragulmare_a_stalking_shadow'); # :miragulmare_a_stalking_shadow_lt:
INSERT INTO loottable(name) VALUES('miragulmare_fsp-general-noeffect'); # :miragulmare_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('miragulmare_nightmare_emissary'); # :miragulmare_nightmare_emissary_lt:
INSERT INTO loottable(name) VALUES('miragulmare_sig'); # :miragulmare_sig_lt:
