INSERT INTO loottable(name) VALUES('neighborhood_ardak_mcmahon'); # :neighborhood_ardak_mcmahon_lt:
INSERT INTO loottable(name) VALUES('neighborhood_garik_nogflop'); # :neighborhood_garik_nogflop_lt:
INSERT INTO loottable(name) VALUES('neighborhood_gebsle_nogflop'); # :neighborhood_gebsle_nogflop_lt:
INSERT INTO loottable(name) VALUES('neighborhood_lorekeeper_arbel_neklene'); # :neighborhood_lorekeeper_arbel_neklene_lt:
INSERT INTO loottable(name) VALUES('neighborhood_albert'); # :neighborhood_albert_lt:
INSERT INTO loottable(name) VALUES('neighborhood_banker_fraener'); # :neighborhood_banker_fraener_lt:
INSERT INTO loottable(name) VALUES('neighborhood_christine'); # :neighborhood_christine_lt:
INSERT INTO loottable(name) VALUES('neighborhood_darix_dunnar'); # :neighborhood_darix_dunnar_lt:
INSERT INTO loottable(name) VALUES('neighborhood_darlenna_everhot'); # :neighborhood_darlenna_everhot_lt:
INSERT INTO loottable(name) VALUES('neighborhood_david'); # :neighborhood_david_lt:
INSERT INTO loottable(name) VALUES('neighborhood_elliere_freegaze'); # :neighborhood_elliere_freegaze_lt:
INSERT INTO loottable(name) VALUES('neighborhood_erinn_hume'); # :neighborhood_erinn_hume_lt:
INSERT INTO loottable(name) VALUES('neighborhood_guardian_worg'); # :neighborhood_guardian_worg_lt:
INSERT INTO loottable(name) VALUES('neighborhood_guardian_worg_pup'); # :neighborhood_guardian_worg_pup_lt:
INSERT INTO loottable(name) VALUES('neighborhood_haze_panther'); # :neighborhood_haze_panther_lt:
INSERT INTO loottable(name) VALUES('neighborhood_herbert'); # :neighborhood_herbert_lt:
INSERT INTO loottable(name) VALUES('neighborhood_icefall_leopard'); # :neighborhood_icefall_leopard_lt:
INSERT INTO loottable(name) VALUES('neighborhood_indy'); # :neighborhood_indy_lt:
INSERT INTO loottable(name) VALUES('neighborhood_lorreal_songsword'); # :neighborhood_lorreal_songsword_lt:
INSERT INTO loottable(name) VALUES('neighborhood_neliths_sylnis'); # :neighborhood_neliths_sylnis_lt:
INSERT INTO loottable(name) VALUES('neighborhood_ragthar'); # :neighborhood_ragthar_lt:
INSERT INTO loottable(name) VALUES('neighborhood_robert'); # :neighborhood_robert_lt:
INSERT INTO loottable(name) VALUES('neighborhood_the_punting_gnome'); # :neighborhood_the_punting_gnome_lt:
INSERT INTO loottable(name) VALUES('neighborhood_varlad_rahnta'); # :neighborhood_varlad_rahnta_lt:
