UPDATE npc_types SET loottable_id = :somnium_buck_witherspoon_lt: WHERE id in (708029); # #Buck_Witherspoon 90
UPDATE npc_types SET loottable_id = :somnium_knight_captain_elena_lt: WHERE id in (708077); # #Knight_Captain_Elena 94
UPDATE npc_types SET loottable_id = :somnium_salvonius_lt: WHERE id in (708031); # #Salvonius 86
UPDATE npc_types SET loottable_id = :somnium_salvonius_treasure_chest_lt: WHERE id in (708054); # #Salvonius_Treasure_Chest 86
UPDATE npc_types SET loottable_id = :somnium_seamus_greendream_lt: WHERE id in (708058); # #Seamus_Greendream 86
UPDATE npc_types SET loottable_id = :somnium_sergeant_ghomar_lt: WHERE id in (708019); # #Sergeant_Ghomar 86
UPDATE npc_types SET loottable_id = :somnium_the_beast_king_lt: WHERE id in (708055); # #The_Beast_King 94
UPDATE npc_types SET loottable_id = :somnium_towerguard_raena_lt: WHERE id in (708026); # #Towerguard_Raena 94
UPDATE npc_types SET loottable_id = :somnium_twereus_ulithain_lt: WHERE id in (708008); # #Twereus_Ulithain 94
UPDATE npc_types SET loottable_id = :somnium_an_elite_guardian_lt: WHERE id in (708059); # an_elite_guardian 91
UPDATE npc_types SET loottable_id = :somnium_a_dark_beast_lt: WHERE id in (708012); # a_dark_beast 91
UPDATE npc_types SET loottable_id = :somnium_a_dark_occultist_lt: WHERE id in (708017, 708032); # a_dark_occultist 90
UPDATE npc_types SET loottable_id = :somnium_a_dark_occultist_researcher_lt: WHERE id in (708030); # a_dark_occultist_researcher 90
UPDATE npc_types SET loottable_id = :somnium_a_dark_ritualist_lt: WHERE id in (708037, 708040); # a_dark_ritualist 90
UPDATE npc_types SET loottable_id = :somnium_a_dark_ritualist_expert_lt: WHERE id in (708038, 708075); # a_dark_ritualist_expert 90
UPDATE npc_types SET loottable_id = :somnium_a_deluded_prince_lt: WHERE id in (708056); # a_deluded_prince 88
UPDATE npc_types SET loottable_id = :somnium_a_deranged_beggar_lt: WHERE id in (708073, 708074); # a_deranged_beggar 90
UPDATE npc_types SET loottable_id = :somnium_a_dream_phantom_lt: WHERE id in (708015); # a_dream_phantom 89
UPDATE npc_types SET loottable_id = :somnium_a_dream_phantom_illusion_lt: WHERE id in (708027); # a_dream_phantom_illusion 89
UPDATE npc_types SET loottable_id = :somnium_a_dream_shade_lt: WHERE id in (708060); # a_dream_shade 90
UPDATE npc_types SET loottable_id = :somnium_a_dream_shade_figment_lt: WHERE id in (708064); # a_dream_shade_figment 90
UPDATE npc_types SET loottable_id = :somnium_a_fake_princess_lt: WHERE id in (708048); # a_fake_princess 88
UPDATE npc_types SET loottable_id = :somnium_a_filthy_rabid_rat_lt: WHERE id in (708070); # a_filthy_rabid_rat 89
UPDATE npc_types SET loottable_id = :somnium_a_giant_mosquito_lt: WHERE id in (708044); # a_giant_mosquito 90
UPDATE npc_types SET loottable_id = :somnium_a_giant_warrior_lt: WHERE id in (708051); # a_giant_warrior 91
UPDATE npc_types SET loottable_id = :somnium_a_giant_warrior_veteran_lt: WHERE id in (708076); # a_giant_warrior_veteran 91
UPDATE npc_types SET loottable_id = :somnium_a_goblin_raider_lt: WHERE id in (708041); # a_goblin_raider 89
UPDATE npc_types SET loottable_id = :somnium_a_goblin_raider_captain_lt: WHERE id in (708046); # a_goblin_raider_captain 89
UPDATE npc_types SET loottable_id = :somnium_a_head_servant_lt: WHERE id in (708067); # a_head_servant 91
UPDATE npc_types SET loottable_id = :somnium_a_hungry_scavanger_beetle_lt: WHERE id in (708072); # a_hungry_scavanger_beetle 89
UPDATE npc_types SET loottable_id = :somnium_a_kobold_skirmisher_lt: WHERE id in (708033); # a_kobold_skirmisher 89
UPDATE npc_types SET loottable_id = :somnium_a_leprechaun_lt: WHERE id in (708053); # a_leprechaun 90
UPDATE npc_types SET loottable_id = :somnium_a_long_hallway_lt: WHERE id in (708062); # A_long_hallway 90
UPDATE npc_types SET loottable_id = :somnium_a_lucid_beggar_lt: WHERE id in (708069); # a_lucid_beggar 88
UPDATE npc_types SET loottable_id = :somnium_a_mad_beggar_lt: WHERE id in (708043, 708050); # a_mad_beggar 90
UPDATE npc_types SET loottable_id = :somnium_a_master_guardian_lt: WHERE id in (708003); # a_master_guardian 91
UPDATE npc_types SET loottable_id = :somnium_a_personal_servant_lt: WHERE id in (708002); # a_personal_servant 91
UPDATE npc_types SET loottable_id = :somnium_a_rabid_rat_lt: WHERE id in (708047); # a_rabid_rat 89
UPDATE npc_types SET loottable_id = :somnium_a_royal_archmage_lt: WHERE id in (708009, 708013); # a_royal_archmage 90
UPDATE npc_types SET loottable_id = :somnium_a_royal_guard_lt: WHERE id in (708016, 708025); # a_royal_guard 90
UPDATE npc_types SET loottable_id = :somnium_a_royal_high_priest_lt: WHERE id in (708035, 708045); # a_royal_high_priest 90
UPDATE npc_types SET loottable_id = :somnium_a_royal_knight_lt: WHERE id in (708018, 708021); # a_royal_knight 90
UPDATE npc_types SET loottable_id = :somnium_a_royal_knight_errant_lt: WHERE id in (708020); # a_royal_knight_errant 90
UPDATE npc_types SET loottable_id = :somnium_a_royal_mage_lt: WHERE id in (708023); # a_royal_mage 90
UPDATE npc_types SET loottable_id = :somnium_a_royal_priest_lt: WHERE id in (708022, 708052); # a_royal_priest 90
UPDATE npc_types SET loottable_id = :somnium_a_scavanger_beetle_lt: WHERE id in (708036); # a_scavanger_beetle 89
UPDATE npc_types SET loottable_id = :somnium_a_shadowy_dark_beast_lt: WHERE id in (708034); # a_shadowy_dark_beast 91
UPDATE npc_types SET loottable_id = :somnium_a_strange_leprechaun_lt: WHERE id in (708049); # a_strange_leprechaun 90
UPDATE npc_types SET loottable_id = :somnium_a_tower_guardian_lt: WHERE id in (708001); # a_tower_guardian 90
UPDATE npc_types SET loottable_id = :somnium_a_tower_servant_lt: WHERE id in (708006); # a_tower_servant 90
UPDATE npc_types SET loottable_id = :somnium_a_tower_warden_lt: WHERE id in (708005); # a_tower_warden 90
UPDATE npc_types SET loottable_id = :somnium_a_tower_warden_sergeant_lt: WHERE id in (708042); # a_tower_warden_sergeant 91
UPDATE npc_types SET loottable_id = :somnium_a_whisper_in_your_ear_lt: WHERE id in (708065); # A_whisper_in_your_ear 90
UPDATE npc_types SET loottable_id = :somnium_a_wounded_kobold_lt: WHERE id in (708071); # a_wounded_kobold 88
UPDATE npc_types SET loottable_id = :somnium_cort_landerson_lt: WHERE id in (708024); # Cort_Landerson 88
UPDATE npc_types SET loottable_id = :somnium_dennen_marol_lt: WHERE id in (708057); # Dennen_Marol 88
UPDATE npc_types SET loottable_id = :somnium_eye_of_theznir_lt: WHERE id in (708078); # Eye_of_Theznir 6
UPDATE npc_types SET loottable_id = :somnium_fareth_lt: WHERE id in (708068); # Fareth 88
UPDATE npc_types SET loottable_id = :somnium_fsp-general-noeffect_lt: WHERE id in (708000, 708004, 708007, 708028, 708061); # FSP-General-NoEffect 1
UPDATE npc_types SET loottable_id = :somnium_karez_dven_lt: WHERE id in (708010); # Karez_D`Ven 88
UPDATE npc_types SET loottable_id = :somnium_kojip_lt: WHERE id in (708079); # Kojip 1
UPDATE npc_types SET loottable_id = :somnium_mara_orane_lt: WHERE id in (708063); # Mara_O`Rane 88
UPDATE npc_types SET loottable_id = :somnium_morells_commander_lt: WHERE id in (708066); # Morell`s_Commander 93
UPDATE npc_types SET loottable_id = :somnium_rommen_steelforge_lt: WHERE id in (708039); # Rommen_Steelforge 88
UPDATE npc_types SET loottable_id = :somnium_sage_jarith_lt: WHERE id in (708011); # Sage_Jarith 88
UPDATE npc_types SET loottable_id = :somnium_seager_the_locksmith_lt: WHERE id in (708014); # Seager_the_Locksmith 88
