INSERT INTO loottable(name) VALUES('thulehouse1_alboct_vinn'); # :thulehouse1_alboct_vinn_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_elben'); # :thulehouse1_elben_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_gristle'); # :thulehouse1_gristle_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_groot'); # :thulehouse1_groot_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_gumbor'); # :thulehouse1_gumbor_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_huorun'); # :thulehouse1_huorun_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_korlof'); # :thulehouse1_korlof_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_krantz'); # :thulehouse1_krantz_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_laerdin_helleh'); # :thulehouse1_laerdin_helleh_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_liss'); # :thulehouse1_liss_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_nightscale'); # :thulehouse1_nightscale_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_researcher_breoro'); # :thulehouse1_researcher_breoro_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_ruppoc_rockjumper'); # :thulehouse1_ruppoc_rockjumper_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_the_butler'); # :thulehouse1_the_butler_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_torlan'); # :thulehouse1_torlan_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_beastling_of_horror'); # :thulehouse1_a_beastling_of_horror_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_beastling_of_rage'); # :thulehouse1_a_beastling_of_rage_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_beastling_of_rot'); # :thulehouse1_a_beastling_of_rot_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_beastling_of_the_unknown'); # :thulehouse1_a_beastling_of_the_unknown_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_bone_crafter'); # :thulehouse1_a_bone_crafter_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_bone_golem'); # :thulehouse1_a_bone_golem_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_dreadful_bone_golem'); # :thulehouse1_a_dreadful_bone_golem_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_frightening_skeleton'); # :thulehouse1_a_frightening_skeleton_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_frightful_bone_golem'); # :thulehouse1_a_frightful_bone_golem_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_frightful_skeleton'); # :thulehouse1_a_frightful_skeleton_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_fright_guard'); # :thulehouse1_a_fright_guard_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_fright_spinner'); # :thulehouse1_a_fright_spinner_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_horror_guard'); # :thulehouse1_a_horror_guard_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_nightmarish_guard'); # :thulehouse1_a_nightmarish_guard_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_quaking_haunt'); # :thulehouse1_a_quaking_haunt_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_rotdog_fearfinder'); # :thulehouse1_a_rotdog_fearfinder_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_rotdog_fearsmeller'); # :thulehouse1_a_rotdog_fearsmeller_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_rotdog_fearsniffer'); # :thulehouse1_a_rotdog_fearsniffer_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_rotdog_fearstalker'); # :thulehouse1_a_rotdog_fearstalker_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_rotdog_feartracker'); # :thulehouse1_a_rotdog_feartracker_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_shivering_haunt'); # :thulehouse1_a_shivering_haunt_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_sleepeating_cube'); # :thulehouse1_a_sleepeating_cube_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_sleeper_cube'); # :thulehouse1_a_sleeper_cube_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_terror_guard'); # :thulehouse1_a_terror_guard_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_terror_spinner'); # :thulehouse1_a_terror_spinner_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_terror_statue'); # :thulehouse1_a_terror_statue_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_trapped_dreamer'); # :thulehouse1_a_trapped_dreamer_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_troublesome_snake'); # :thulehouse1_a_troublesome_snake_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_vile_bone_crafter'); # :thulehouse1_a_vile_bone_crafter_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_a_worrisome_snake'); # :thulehouse1_a_worrisome_snake_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_lifedrainaura_horror'); # :thulehouse1_lifedrainaura_horror_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_lifedrainaura_rage'); # :thulehouse1_lifedrainaura_rage_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_lifedrainaura_rot'); # :thulehouse1_lifedrainaura_rot_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_lifedrainaura_unknown'); # :thulehouse1_lifedrainaura_unknown_lt:
INSERT INTO loottable(name) VALUES('thulehouse1_thbaseclock'); # :thulehouse1_thbaseclock_lt:
