INSERT INTO loottable(name) VALUES('corathusb_a_corathus_mangler'); # :corathusb_a_corathus_mangler_lt:
INSERT INTO loottable(name) VALUES('corathusb_corathus_eviscerator'); # :corathusb_corathus_eviscerator_lt:
INSERT INTO loottable(name) VALUES('corathusb_haru,_the_corathus_beast'); # :corathusb_haru,_the_corathus_beast_lt:
INSERT INTO loottable(name) VALUES('corathusb_iguanidae_enrager'); # :corathusb_iguanidae_enrager_lt:
INSERT INTO loottable(name) VALUES('corathusb_lasiurus_aggressor'); # :corathusb_lasiurus_aggressor_lt:
INSERT INTO loottable(name) VALUES('corathusb_rattus_ravager'); # :corathusb_rattus_ravager_lt:
INSERT INTO loottable(name) VALUES('corathusb__'); # :corathusb___lt:
INSERT INTO loottable(name) VALUES('corathusb_alpha_larva'); # :corathusb_alpha_larva_lt:
INSERT INTO loottable(name) VALUES('corathusb_an_insectivorous_bat'); # :corathusb_an_insectivorous_bat_lt:
INSERT INTO loottable(name) VALUES('corathusb_an_mechtech_rat_digger'); # :corathusb_an_mechtech_rat_digger_lt:
INSERT INTO loottable(name) VALUES('corathusb_an_mechtech_rat_scavenger'); # :corathusb_an_mechtech_rat_scavenger_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_basilisk'); # :corathusb_a_basilisk_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_bloodfeasting_bat'); # :corathusb_a_bloodfeasting_bat_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_corathus_feeder'); # :corathusb_a_corathus_feeder_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_corathus_larva_ravager'); # :corathusb_a_corathus_larva_ravager_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_corathus_larva_scrounger'); # :corathusb_a_corathus_larva_scrounger_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_corathus_mine_delver'); # :corathusb_a_corathus_mine_delver_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_corathus_swarmer'); # :corathusb_a_corathus_swarmer_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_bonedrill'); # :corathusb_a_creep_reaper_bonedrill_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_demolitionist'); # :corathusb_a_creep_reaper_demolitionist_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_earthclaw'); # :corathusb_a_creep_reaper_earthclaw_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_guard'); # :corathusb_a_creep_reaper_guard_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_lookout'); # :corathusb_a_creep_reaper_lookout_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_mindbore'); # :corathusb_a_creep_reaper_mindbore_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_operator'); # :corathusb_a_creep_reaper_operator_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_repair_module'); # :corathusb_a_creep_reaper_repair_module_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_scout'); # :corathusb_a_creep_reaper_scout_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_creep_reaper_surveyor'); # :corathusb_a_creep_reaper_surveyor_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_heavy_burrow_drone'); # :corathusb_a_heavy_burrow_drone_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_heavy_lifter_drone'); # :corathusb_a_heavy_lifter_drone_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_larva_gorger'); # :corathusb_a_larva_gorger_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_mech-o-rat_fusebearer'); # :corathusb_a_mech-o-rat_fusebearer_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_mech-o-rat_tunneler'); # :corathusb_a_mech-o-rat_tunneler_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_mech-o-skitter_fusebearer'); # :corathusb_a_mech-o-skitter_fusebearer_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_mech-o-skitter_hunter'); # :corathusb_a_mech-o-skitter_hunter_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_mech-o-skitter_scraper'); # :corathusb_a_mech-o-skitter_scraper_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_mechtech_rat_digger'); # :corathusb_a_mechtech_rat_digger_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_mechtech_rat_scavenger'); # :corathusb_a_mechtech_rat_scavenger_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_roving_corathus_feeder'); # :corathusb_a_roving_corathus_feeder_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_slumbering_basilisk'); # :corathusb_a_slumbering_basilisk_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_starving_draft_basilisk'); # :corathusb_a_starving_draft_basilisk_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_starving_pack_basilisk'); # :corathusb_a_starving_pack_basilisk_lt:
INSERT INTO loottable(name) VALUES('corathusb_a_wattled_bat'); # :corathusb_a_wattled_bat_lt:
INSERT INTO loottable(name) VALUES('corathusb_creeper_clicktok'); # :corathusb_creeper_clicktok_lt:
INSERT INTO loottable(name) VALUES('corathusb_larvae_runt'); # :corathusb_larvae_runt_lt:
INSERT INTO loottable(name) VALUES('corathusb_the_hurt_machine'); # :corathusb_the_hurt_machine_lt:
