INSERT INTO loottable(name) VALUES('eastkorlacha_an_ornate_chest'); # :eastkorlacha_an_ornate_chest_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_bloodeye'); # :eastkorlacha_bloodeye_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_elder_ritualist_longshadow'); # :eastkorlacha_elder_ritualist_longshadow_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_rage_biter'); # :eastkorlacha_rage_biter_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_stone_paw'); # :eastkorlacha_stone_paw_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_the_presence_of_bloodeye'); # :eastkorlacha_the_presence_of_bloodeye_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_drachind_webmender'); # :eastkorlacha_a_drachind_webmender_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_drachnid_cursewielder'); # :eastkorlacha_a_drachnid_cursewielder_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_drachnid_defiler'); # :eastkorlacha_a_drachnid_defiler_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_drachnid_guardian'); # :eastkorlacha_a_drachnid_guardian_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_drachnid_invader'); # :eastkorlacha_a_drachnid_invader_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_drachnid_looter'); # :eastkorlacha_a_drachnid_looter_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_drachnid_mindcatcher'); # :eastkorlacha_a_drachnid_mindcatcher_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_drachnid_mundunugu'); # :eastkorlacha_a_drachnid_mundunugu_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_frenzied_ragepaw'); # :eastkorlacha_a_frenzied_ragepaw_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_padded_chest'); # :eastkorlacha_a_padded_chest_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_ragepaw_earthcaller'); # :eastkorlacha_a_ragepaw_earthcaller_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_ragepaw_hunter'); # :eastkorlacha_a_ragepaw_hunter_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_ragepaw_spiritist'); # :eastkorlacha_a_ragepaw_spiritist_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha_a_ragepaw_warrior'); # :eastkorlacha_a_ragepaw_warrior_lt:
INSERT INTO loottable(name) VALUES('eastkorlacha__'); # :eastkorlacha___lt:
