INSERT INTO loottable(name) VALUES('westkorlacha_'); # :westkorlacha__lt:
INSERT INTO loottable(name) VALUES('westkorlacha_an_enforcer_of_shyra'); # :westkorlacha_an_enforcer_of_shyra_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_a_protector_of_shyra'); # :westkorlacha_a_protector_of_shyra_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_prince_drillien'); # :westkorlacha_prince_drillien_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_shyras_shadow'); # :westkorlacha_shyras_shadow_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_tone'); # :westkorlacha_tone_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_tthree'); # :westkorlacha_tthree_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_an_elite_shadowmane_guard'); # :westkorlacha_an_elite_shadowmane_guard_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_a_drachnid_anarchist'); # :westkorlacha_a_drachnid_anarchist_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_a_drachnid_defiler'); # :westkorlacha_a_drachnid_defiler_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_a_drachnid_dreadknight'); # :westkorlacha_a_drachnid_dreadknight_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_a_drachnid_evader'); # :westkorlacha_a_drachnid_evader_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_a_drachnid_ritualist'); # :westkorlacha_a_drachnid_ritualist_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_a_follower_of_shyra'); # :westkorlacha_a_follower_of_shyra_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_a_lodge_of_the_fang_member'); # :westkorlacha_a_lodge_of_the_fang_member_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_a_royal_protector'); # :westkorlacha_a_royal_protector_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_commander_hithrav'); # :westkorlacha_commander_hithrav_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_ilsuras'); # :westkorlacha_ilsuras_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_matriarch_shyra'); # :westkorlacha_matriarch_shyra_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_overseer_renok'); # :westkorlacha_overseer_renok_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_protector_iknar'); # :westkorlacha_protector_iknar_lt:
INSERT INTO loottable(name) VALUES('westkorlacha_protector_vrek'); # :westkorlacha_protector_vrek_lt:
