INSERT INTO loottable(name) VALUES('westkorlach_assistant_savils_corpse'); # :westkorlach_assistant_savils_corpse_lt:
INSERT INTO loottable(name) VALUES('westkorlach_captain_klegor'); # :westkorlach_captain_klegor_lt:
INSERT INTO loottable(name) VALUES('westkorlach_commander_olag'); # :westkorlach_commander_olag_lt:
INSERT INTO loottable(name) VALUES('westkorlach_drillak_the_slayer'); # :westkorlach_drillak_the_slayer_lt:
INSERT INTO loottable(name) VALUES('westkorlach_general_greglon'); # :westkorlach_general_greglon_lt:
INSERT INTO loottable(name) VALUES('westkorlach_kelliad'); # :westkorlach_kelliad_lt:
INSERT INTO loottable(name) VALUES('westkorlach_krage_the_lake_champion'); # :westkorlach_krage_the_lake_champion_lt:
INSERT INTO loottable(name) VALUES('westkorlach_meldrek'); # :westkorlach_meldrek_lt:
INSERT INTO loottable(name) VALUES('westkorlach_reknid_the_tower_watcher'); # :westkorlach_reknid_the_tower_watcher_lt:
INSERT INTO loottable(name) VALUES('westkorlach_researcher_briznek'); # :westkorlach_researcher_briznek_lt:
INSERT INTO loottable(name) VALUES('westkorlach_slave_driver_skeliz'); # :westkorlach_slave_driver_skeliz_lt:
INSERT INTO loottable(name) VALUES('westkorlach_squeakers'); # :westkorlach_squeakers_lt:
INSERT INTO loottable(name) VALUES('westkorlach_stonebite'); # :westkorlach_stonebite_lt:
INSERT INTO loottable(name) VALUES('westkorlach_the_drachnid_champion'); # :westkorlach_the_drachnid_champion_lt:
INSERT INTO loottable(name) VALUES('westkorlach_the_drained_shiliskin_captain'); # :westkorlach_the_drained_shiliskin_captain_lt:
INSERT INTO loottable(name) VALUES('westkorlach_the_shadow_guardian'); # :westkorlach_the_shadow_guardian_lt:
INSERT INTO loottable(name) VALUES('westkorlach_throatripper'); # :westkorlach_throatripper_lt:
INSERT INTO loottable(name) VALUES('westkorlach_widdlethorpe_gemfinder'); # :westkorlach_widdlethorpe_gemfinder_lt:
INSERT INTO loottable(name) VALUES('westkorlach_zoriles_the_champion'); # :westkorlach_zoriles_the_champion_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_blood_feaster'); # :westkorlach_a_blood_feaster_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_coral_fan'); # :westkorlach_a_coral_fan_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_coral_fin'); # :westkorlach_a_coral_fin_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_coral_sail'); # :westkorlach_a_coral_sail_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_darkhollow_shrieker'); # :westkorlach_a_darkhollow_shrieker_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_dark_mystical_chest'); # :westkorlach_a_dark_mystical_chest_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_deep_orc'); # :westkorlach_a_deep_orc_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_deep_orc_legionnaire'); # :westkorlach_a_deep_orc_legionnaire_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_diligent_silkweaver'); # :westkorlach_a_diligent_silkweaver_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_dirty_darkhollow_rat'); # :westkorlach_a_dirty_darkhollow_rat_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drachnic_mind_bender'); # :westkorlach_a_drachnic_mind_bender_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drachnid'); # :westkorlach_a_drachnid_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drachnid_hunter'); # :westkorlach_a_drachnid_hunter_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_acolyte'); # :westkorlach_a_drained_shiliskin_acolyte_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_battle_mage'); # :westkorlach_a_drained_shiliskin_battle_mage_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_bonehealer'); # :westkorlach_a_drained_shiliskin_bonehealer_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_coercer'); # :westkorlach_a_drained_shiliskin_coercer_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_slayer'); # :westkorlach_a_drained_shiliskin_slayer_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_slicer'); # :westkorlach_a_drained_shiliskin_slicer_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_soldier'); # :westkorlach_a_drained_shiliskin_soldier_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_soul_leech'); # :westkorlach_a_drained_shiliskin_soul_leech_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_warlock'); # :westkorlach_a_drained_shiliskin_warlock_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_drained_shiliskin_war_mage'); # :westkorlach_a_drained_shiliskin_war_mage_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_female_darkhollow_redback'); # :westkorlach_a_female_darkhollow_redback_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_female_darkhollow_snapfang'); # :westkorlach_a_female_darkhollow_snapfang_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_manasheen_patch'); # :westkorlach_a_manasheen_patch_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_quickspore_stand'); # :westkorlach_a_quickspore_stand_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_retch_spore_growth'); # :westkorlach_a_retch_spore_growth_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_sap_root_colony'); # :westkorlach_a_sap_root_colony_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shadowmane_elder_naturalist'); # :westkorlach_a_shadowmane_elder_naturalist_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shadowmane_elder_nightwhisper'); # :westkorlach_a_shadowmane_elder_nightwhisper_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shadowmane_elder_pathwalker'); # :westkorlach_a_shadowmane_elder_pathwalker_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shadowmane_elder_spirit_guide'); # :westkorlach_a_shadowmane_elder_spirit_guide_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shadowmane_naturalist'); # :westkorlach_a_shadowmane_naturalist_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shadowmane_nightwhisper'); # :westkorlach_a_shadowmane_nightwhisper_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shadowmane_pathwalker'); # :westkorlach_a_shadowmane_pathwalker_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shadowmane_protector'); # :westkorlach_a_shadowmane_protector_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shadowmane_spirit_guardian'); # :westkorlach_a_shadowmane_spirit_guardian_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shiliskin_soldiers_corpse'); # :westkorlach_a_shiliskin_soldiers_corpse_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shiliskin_supply_barrel'); # :westkorlach_a_shiliskin_supply_barrel_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shiliskins_corpse'); # :westkorlach_a_shiliskins_corpse_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_shrine_to_wuria'); # :westkorlach_a_shrine_to_wuria_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_sonic_blood_thirster'); # :westkorlach_a_sonic_blood_thirster_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_sonic_night_stalker'); # :westkorlach_a_sonic_night_stalker_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_stoneroot_basilisk'); # :westkorlach_a_stoneroot_basilisk_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_stoneroot_rattler'); # :westkorlach_a_stoneroot_rattler_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_stoneroot_tailsmasher'); # :westkorlach_a_stoneroot_tailsmasher_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_waterlogged_chest'); # :westkorlach_a_waterlogged_chest_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_witheran'); # :westkorlach_a_witheran_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_witheran_feeder'); # :westkorlach_a_witheran_feeder_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_witheran_glider'); # :westkorlach_a_witheran_glider_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_witheran_gnasher'); # :westkorlach_a_witheran_gnasher_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_assassin'); # :westkorlach_a_xillsfar_assassin_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_battle_mage'); # :westkorlach_a_xillsfar_battle_mage_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_bonehealer'); # :westkorlach_a_xillsfar_bonehealer_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_chaplain'); # :westkorlach_a_xillsfar_chaplain_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_coercer'); # :westkorlach_a_xillsfar_coercer_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_fighter'); # :westkorlach_a_xillsfar_fighter_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_legion_warchest'); # :westkorlach_a_xillsfar_legion_warchest_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_prelate'); # :westkorlach_a_xillsfar_prelate_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_soldier'); # :westkorlach_a_xillsfar_soldier_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_soldiers_corpse'); # :westkorlach_a_xillsfar_soldiers_corpse_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_soul_charmer'); # :westkorlach_a_xillsfar_soul_charmer_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_spirithealer'); # :westkorlach_a_xillsfar_spirithealer_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_twinblade'); # :westkorlach_a_xillsfar_twinblade_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_twinblade_adept'); # :westkorlach_a_xillsfar_twinblade_adept_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_warlock'); # :westkorlach_a_xillsfar_warlock_lt:
INSERT INTO loottable(name) VALUES('westkorlach_a_xillsfar_war_mage'); # :westkorlach_a_xillsfar_war_mage_lt:
INSERT INTO loottable(name) VALUES('westkorlach_calisar'); # :westkorlach_calisar_lt:
INSERT INTO loottable(name) VALUES('westkorlach_cutfang'); # :westkorlach_cutfang_lt:
INSERT INTO loottable(name) VALUES('westkorlach_fihtzen'); # :westkorlach_fihtzen_lt:
INSERT INTO loottable(name) VALUES('westkorlach_grokui,_the_slumbering_basilisk'); # :westkorlach_grokui,_the_slumbering_basilisk_lt:
INSERT INTO loottable(name) VALUES('westkorlach_illusionist_zimix'); # :westkorlach_illusionist_zimix_lt:
INSERT INTO loottable(name) VALUES('westkorlach_nightmoon'); # :westkorlach_nightmoon_lt:
INSERT INTO loottable(name) VALUES('westkorlach_scout_whiteclaw'); # :westkorlach_scout_whiteclaw_lt:
INSERT INTO loottable(name) VALUES('westkorlach_shadowalker_dustspirit'); # :westkorlach_shadowalker_dustspirit_lt:
INSERT INTO loottable(name) VALUES('westkorlach_sintal'); # :westkorlach_sintal_lt:
INSERT INTO loottable(name) VALUES('westkorlach_spiritualist_ryianna'); # :westkorlach_spiritualist_ryianna_lt:
INSERT INTO loottable(name) VALUES('westkorlach_watcher_greypaw'); # :westkorlach_watcher_greypaw_lt:
INSERT INTO loottable(name) VALUES('westkorlach_watcher_shadowfang'); # :westkorlach_watcher_shadowfang_lt:
INSERT INTO loottable(name) VALUES('westkorlach__'); # :westkorlach___lt:
