INSERT INTO loottable(name) VALUES('westkorlachc_a_dark_mystical_chest'); # :westkorlachc_a_dark_mystical_chest_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_chancellor_prellius'); # :westkorlachc_chancellor_prellius_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_high_priest_trelikin'); # :westkorlachc_high_priest_trelikin_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_korlach,_the_deep_leviathan'); # :westkorlachc_korlach,_the_deep_leviathan_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_vision_of_the_witheran_beast'); # :westkorlachc_vision_of_the_witheran_beast_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_an_undershore_basilisk'); # :westkorlachc_an_undershore_basilisk_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_deep_orc'); # :westkorlachc_a_deep_orc_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_drained_deathshed_protector'); # :westkorlachc_a_drained_deathshed_protector_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_drained_deathshed_slayer'); # :westkorlachc_a_drained_deathshed_slayer_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_drained_deathshed_warlock'); # :westkorlachc_a_drained_deathshed_warlock_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_drained_shiliskin_battle_mage'); # :westkorlachc_a_drained_shiliskin_battle_mage_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_drained_shiliskin_slayer'); # :westkorlachc_a_drained_shiliskin_slayer_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_drained_shiliskin_soldier'); # :westkorlachc_a_drained_shiliskin_soldier_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_hungry_witheran'); # :westkorlachc_a_hungry_witheran_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_shiliskin_deathshed_priest'); # :westkorlachc_a_shiliskin_deathshed_priest_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_shiliskin_guardians_corpse'); # :westkorlachc_a_shiliskin_guardians_corpse_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_witheran'); # :westkorlachc_a_witheran_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_witheran_feeder'); # :westkorlachc_a_witheran_feeder_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_a_young_witheran'); # :westkorlachc_a_young_witheran_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_invis_urchin_trap'); # :westkorlachc_invis_urchin_trap_lt:
INSERT INTO loottable(name) VALUES('westkorlachc_korlach,_the_deep_leviathan'); # :westkorlachc_korlach,_the_deep_leviathan_lt:
INSERT INTO loottable(name) VALUES('westkorlachc__'); # :westkorlachc___lt:
