INSERT INTO loottable(name) VALUES ('abbit_scribbletch'); # :abbit_scribbletch_lt:
INSERT INTO loottable(name) VALUES ('agent_of_morzad'); # :agent_of_morzad_lt:
INSERT INTO loottable(name) VALUES ('andre_macdonnal'); # :andre_macdonnal_lt:
INSERT INTO loottable(name) VALUES ('a_listless_madwoman'); # :a_listless_madwoman_lt:
INSERT INTO loottable(name) VALUES ('cazic_thule'); # :cazic_thule_lt:
INSERT INTO loottable(name) VALUES ('elard_velsorn'); # :elard_velsorn_lt:
INSERT INTO loottable(name) VALUES ('galo_maric'); # :galo_maric_lt:
INSERT INTO loottable(name) VALUES ('karivei_skyflare'); # :karivei_skyflare_lt:
INSERT INTO loottable(name) VALUES ('keega'); # :keega_lt:
INSERT INTO loottable(name) VALUES ('khalis'); # :khalis_lt:
INSERT INTO loottable(name) VALUES ('lilth'); # :lilth_lt:
INSERT INTO loottable(name) VALUES ('morzad_aircaster'); # :morzad_aircaster_lt:
INSERT INTO loottable(name) VALUES ('morzad_earthcaster'); # :morzad_earthcaster_lt:
INSERT INTO loottable(name) VALUES ('morzad_firecaster'); # :morzad_firecaster_lt:
INSERT INTO loottable(name) VALUES ('morzad_watercaster'); # :morzad_watercaster_lt:
INSERT INTO loottable(name) VALUES ('profane_fiend'); # :profane_fiend_lt:
INSERT INTO loottable(name) VALUES ('rotticus'); # :rotticus_lt:
INSERT INTO loottable(name) VALUES ('an_ember_golem'); # :an_ember_golem_lt:
INSERT INTO loottable(name) VALUES ('an_iceworn_guardian'); # :an_iceworn_guardian_lt:
INSERT INTO loottable(name) VALUES ('an_icy_ooze'); # :an_icy_ooze_lt:
INSERT INTO loottable(name) VALUES ('a_bloodthirsty_beast'); # :a_bloodthirsty_beast_lt:
INSERT INTO loottable(name) VALUES ('a_blood_elemental'); # :a_blood_elemental_lt:
INSERT INTO loottable(name) VALUES ('a_cheerless_apparition'); # :a_cheerless_apparition_lt:
INSERT INTO loottable(name) VALUES ('a_drifting_fog_elemental'); # :a_drifting_fog_elemental_lt:
INSERT INTO loottable(name) VALUES ('a_dripping_blood_elemental'); # :a_dripping_blood_elemental_lt:
INSERT INTO loottable(name) VALUES ('a_filthy_rotdog'); # :a_filthy_rotdog_lt:
INSERT INTO loottable(name) VALUES ('a_flowing_fog_elemental'); # :a_flowing_fog_elemental_lt:
INSERT INTO loottable(name) VALUES ('a_flying_monkey'); # :a_flying_monkey_lt:
INSERT INTO loottable(name) VALUES ('a_frozen_ooze'); # :a_frozen_ooze_lt:
INSERT INTO loottable(name) VALUES ('a_funnelweb_leaper'); # :a_funnelweb_leaper_lt:
INSERT INTO loottable(name) VALUES ('a_funnelweb_spider'); # :a_funnelweb_spider_lt:
INSERT INTO loottable(name) VALUES ('a_ghostly_vision'); # :a_ghostly_vision_lt:
INSERT INTO loottable(name) VALUES ('a_gibbering_madman'); # :a_gibbering_madman_lt:
INSERT INTO loottable(name) VALUES ('a_hateful_fire_elemental'); # :a_hateful_fire_elemental_lt:
INSERT INTO loottable(name) VALUES ('a_heartstinger_scorpion'); # :a_heartstinger_scorpion_lt:
INSERT INTO loottable(name) VALUES ('a_horrible_centipede'); # :a_horrible_centipede_lt:
INSERT INTO loottable(name) VALUES ('a_hungry_beast'); # :a_hungry_beast_lt:
INSERT INTO loottable(name) VALUES ('a_mournful_soul'); # :a_mournful_soul_lt:
INSERT INTO loottable(name) VALUES ('a_nightmarish_beast'); # :a_nightmarish_beast_lt:
INSERT INTO loottable(name) VALUES ('a_nightmarish_centipede'); # :a_nightmarish_centipede_lt:
INSERT INTO loottable(name) VALUES ('a_nightmarish_guardian'); # :a_nightmarish_guardian_lt:
INSERT INTO loottable(name) VALUES ('a_putrid_rotdog'); # :a_putrid_rotdog_lt:
INSERT INTO loottable(name) VALUES ('a_raging_beast'); # :a_raging_beast_lt:
INSERT INTO loottable(name) VALUES ('a_slithering_serpent'); # :a_slithering_serpent_lt:
INSERT INTO loottable(name) VALUES ('a_soul_devourer'); # :a_soul_devourer_lt:
INSERT INTO loottable(name) VALUES ('a_stalagmite_terror'); # :a_stalagmite_terror_lt:
INSERT INTO loottable(name) VALUES ('a_trapped_dreamer'); # :a_trapped_dreamer_lt:
INSERT INTO loottable(name) VALUES ('noeffect'); # :noeffect_lt:
INSERT INTO loottable(name) VALUES ('morzad_agent'); # :morzad_agent_lt:
INSERT INTO loottable(name) VALUES ('smokeshroud'); # :smokeshroud_lt:
INSERT INTO loottable(name) VALUES ('thmcateleportaura'); # :thmcateleportaura_lt:
INSERT INTO loottable(name) VALUES ('icefang'); # :icefang_lt:
INSERT INTO loottable(name) VALUES ('icy_devourer'); # :icy_devourer_lt:
INSERT INTO loottable(name) VALUES ('spitecrawler'); # :spitecrawler_lt:
INSERT INTO loottable(name) VALUES ('nightfang'); # :nightfang_lt:
INSERT INTO loottable(name) VALUES ('bodabas'); # :bodabas_lt:
INSERT INTO loottable(name) VALUES ('swirling_fog_elemental'); # :swirling_fog_elemental_lt:
INSERT INTO loottable(name) VALUES ('bloodmane'); # :bloodmane_lt: