INSERT INTO loottable(name) VALUES('chapterhouse_aislinn'); # :chapterhouse_aislinn_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_aliskar_darkbane'); # :chapterhouse_aliskar_darkbane_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_apathetic_zombie'); # :chapterhouse_an_apathetic_zombie_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_emaciated_ghoul'); # :chapterhouse_an_emaciated_ghoul_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_unmotivated_zombie'); # :chapterhouse_an_unmotivated_zombie_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_unravelling_mummy'); # :chapterhouse_an_unravelling_mummy_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_coffin'); # :chapterhouse_a_coffin_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_complacent_zombie'); # :chapterhouse_a_complacent_zombie_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_crumbling_mummy'); # :chapterhouse_a_crumbling_mummy_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_deteriorating_mummy'); # :chapterhouse_a_deteriorating_mummy_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_ravenous_ghoul'); # :chapterhouse_a_ravenous_ghoul_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_starving_ghoul'); # :chapterhouse_a_starving_ghoul_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_baldrik'); # :chapterhouse_baldrik_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_bertrand_the_butcher'); # :chapterhouse_bertrand_the_butcher_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_bloodreaver_narek'); # :chapterhouse_bloodreaver_narek_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_coffinhowl'); # :chapterhouse_coffinhowl_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_elgan_tombson'); # :chapterhouse_elgan_tombson_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_falsin_bonecraft'); # :chapterhouse_falsin_bonecraft_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_gertrude_darksworn'); # :chapterhouse_gertrude_darksworn_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_gibble'); # :chapterhouse_gibble_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_grimbus'); # :chapterhouse_grimbus_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_holy_defender_ioris'); # :chapterhouse_holy_defender_ioris_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_jurso_fumblefink'); # :chapterhouse_jurso_fumblefink_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_oozles'); # :chapterhouse_oozles_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_ophelia_bonesnap'); # :chapterhouse_ophelia_bonesnap_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_orson_gravegloom'); # :chapterhouse_orson_gravegloom_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_plinki_bonebrood'); # :chapterhouse_plinki_bonebrood_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_poira_the_pale'); # :chapterhouse_poira_the_pale_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_sir_birton'); # :chapterhouse_sir_birton_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_sir_graxton_talondrake'); # :chapterhouse_sir_graxton_talondrake_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_slizis_slicetail'); # :chapterhouse_slizis_slicetail_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_wilfred_gorefinder'); # :chapterhouse_wilfred_gorefinder_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_yarin_shroudfear'); # :chapterhouse_yarin_shroudfear_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_afflicted_shade'); # :chapterhouse_an_afflicted_shade_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_ancient_mummy'); # :chapterhouse_an_ancient_mummy_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_enraged_willow_wisp'); # :chapterhouse_an_enraged_willow_wisp_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_icy_terror'); # :chapterhouse_an_icy_terror_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_necromancer_initiate'); # :chapterhouse_an_necromancer_initiate_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_unchaste_cleric_of_marr'); # :chapterhouse_an_unchaste_cleric_of_marr_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_unconscious_halfling'); # :chapterhouse_an_unconscious_halfling_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_undead_cleric_of_marr'); # :chapterhouse_an_undead_cleric_of_marr_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_undead_halfling'); # :chapterhouse_an_undead_halfling_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_an_undead_servant'); # :chapterhouse_an_undead_servant_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_bloody_disposal_crate'); # :chapterhouse_a_bloody_disposal_crate_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_brittle_mummy'); # :chapterhouse_a_brittle_mummy_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_corpse_eating_beetle'); # :chapterhouse_a_corpse_eating_beetle_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_decaying_knight'); # :chapterhouse_a_decaying_knight_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_defiled_paladin_of_marr'); # :chapterhouse_a_defiled_paladin_of_marr_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_deteriorating_disposal_crate'); # :chapterhouse_a_deteriorating_disposal_crate_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_dilapidated_disposal_crate'); # :chapterhouse_a_dilapidated_disposal_crate_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_diseased_rat'); # :chapterhouse_a_diseased_rat_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_disgraced_knight'); # :chapterhouse_a_disgraced_knight_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_disgraced_paladin_of_marr'); # :chapterhouse_a_disgraced_paladin_of_marr_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_dusty_disposal_crate'); # :chapterhouse_a_dusty_disposal_crate_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_dusty_mummy'); # :chapterhouse_a_dusty_mummy_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_failed_experiment'); # :chapterhouse_a_failed_experiment_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_fallen_knight'); # :chapterhouse_a_fallen_knight_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_filthy_disposal_crate'); # :chapterhouse_a_filthy_disposal_crate_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_filthy_rat'); # :chapterhouse_a_filthy_rat_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_flesh_eating_goo'); # :chapterhouse_a_flesh_eating_goo_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_forgotten_prisoner'); # :chapterhouse_a_forgotten_prisoner_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_forlorn_cleric_of_marr'); # :chapterhouse_a_forlorn_cleric_of_marr_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_gloomy_shade'); # :chapterhouse_a_gloomy_shade_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_gooey_goo'); # :chapterhouse_a_gooey_goo_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_gory_disposal_crate'); # :chapterhouse_a_gory_disposal_crate_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_halfling_corpse'); # :chapterhouse_a_halfling_corpse_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_hissing_basilisk'); # :chapterhouse_a_hissing_basilisk_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_hungry_ghoul'); # :chapterhouse_a_hungry_ghoul_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_loathsome_ghoul'); # :chapterhouse_a_loathsome_ghoul_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_lost_soul'); # :chapterhouse_a_lost_soul_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_lost_willow_wisp'); # :chapterhouse_a_lost_willow_wisp_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_lurking_terror'); # :chapterhouse_a_lurking_terror_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_malcontent_thrall'); # :chapterhouse_a_malcontent_thrall_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_misguided_willow_wisp'); # :chapterhouse_a_misguided_willow_wisp_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_mournful_ghost'); # :chapterhouse_a_mournful_ghost_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_necromancer_apprentice'); # :chapterhouse_a_necromancer_apprentice_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_necromancer_boneraiser'); # :chapterhouse_a_necromancer_boneraiser_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_necromancer_initiate'); # :chapterhouse_a_necromancer_initiate_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_necromancer_neophyte'); # :chapterhouse_a_necromancer_neophyte_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_plague_rat'); # :chapterhouse_a_plague_rat_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_reanimated_bodypart'); # :chapterhouse_a_reanimated_bodypart_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_reanimated_paladin'); # :chapterhouse_a_reanimated_paladin_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_revolting_ghoul'); # :chapterhouse_a_revolting_ghoul_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_rotting_paladin_of_marr'); # :chapterhouse_a_rotting_paladin_of_marr_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_scavenging_beetle'); # :chapterhouse_a_scavenging_beetle_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_shambling_zombie'); # :chapterhouse_a_shambling_zombie_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_skeletal_nurse'); # :chapterhouse_a_skeletal_nurse_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_smelly_dung_beetle'); # :chapterhouse_a_smelly_dung_beetle_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_stalag_terror'); # :chapterhouse_a_stalag_terror_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_starving_basilisk'); # :chapterhouse_a_starving_basilisk_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_stoneskin_basilisk'); # :chapterhouse_a_stoneskin_basilisk_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_timeworn_servant'); # :chapterhouse_a_timeworn_servant_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_voracious_goo'); # :chapterhouse_a_voracious_goo_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_wandering_ghost'); # :chapterhouse_a_wandering_ghost_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_a_woeful_shade'); # :chapterhouse_a_woeful_shade_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_biddlix_bonecracker'); # :chapterhouse_biddlix_bonecracker_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_fling_target'); # :chapterhouse_fling_target_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_fsp-general-noeffect'); # :chapterhouse_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_gummil_shortbottom'); # :chapterhouse_gummil_shortbottom_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_researcher_vespra'); # :chapterhouse_researcher_vespra_lt:
INSERT INTO loottable(name) VALUES('chapterhouse_wandas_corpse'); # :chapterhouse_wandas_corpse_lt:
