UPDATE npc_types SET loottable_id = :crystalshard_a_crystal_lurker_lt: WHERE id in (756090); # #A_Crystal_Lurker 101
UPDATE npc_types SET loottable_id = :crystalshard_a_dead_spider_lt: WHERE id in (756052); # #a_dead_spider 10
UPDATE npc_types SET loottable_id = :crystalshard_a_dead_tentacle_lt: WHERE id in (756055); # #a_dead_tentacle 10
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_inspector_lt: WHERE id in (756019); # #A_Ry`Gorr_Inspector 101
UPDATE npc_types SET loottable_id = :crystalshard_baffod_the_wayward_lt: WHERE id in (756022); # #Baffod_the_Wayward 100
UPDATE npc_types SET loottable_id = :crystalshard_bronigan_lt: WHERE id in (756098); # #Bronigan 70
UPDATE npc_types SET loottable_id = :crystalshard_captain_dunstan_coldheart_lt: WHERE id in (756070); # #Captain_Dunstan_Coldheart 99
UPDATE npc_types SET loottable_id = :crystalshard_cassia_gemshard_lt: WHERE id in (756042); # #Cassia_Gemshard 99
UPDATE npc_types SET loottable_id = :crystalshard_derron_coldmist_lt: WHERE id in (756079); # #Derron_Coldmist 99
UPDATE npc_types SET loottable_id = :crystalshard_dirk_coldsmith_lt: WHERE id in (756057); # #Dirk_Coldsmith 99
UPDATE npc_types SET loottable_id = :crystalshard_elsa_icegem_lt: WHERE id in (756047); # #Elsa_Icegem 99
UPDATE npc_types SET loottable_id = :crystalshard_engineer_colle_lt: WHERE id in (756048); # #Engineer_Colle 99
UPDATE npc_types SET loottable_id = :crystalshard_flint_velweaver_lt: WHERE id in (756085); # #Flint_Velweaver 99
UPDATE npc_types SET loottable_id = :crystalshard_fridjorn_lt: WHERE id in (756091); # #Fridjorn 100
UPDATE npc_types SET loottable_id = :crystalshard_fridjornbody_lt: WHERE id in (756093); # #FridjornBody 100
UPDATE npc_types SET loottable_id = :crystalshard_fuller_velweaver_lt: WHERE id in (756075); # #Fuller_Velweaver 99
UPDATE npc_types SET loottable_id = :crystalshard_gilliad_coldheart_lt: WHERE id in (756056); # #Gilliad_Coldheart 99
UPDATE npc_types SET loottable_id = :crystalshard_grabble_coldheart_lt: WHERE id in (756073); # #Grabble_Coldheart 99
UPDATE npc_types SET loottable_id = :crystalshard_graght_the_little_lt: WHERE id in (756015); # #Graght_the_Little 100
UPDATE npc_types SET loottable_id = :crystalshard_guard_evercold_lt: WHERE id in (756078); # #Guard_Evercold 99
UPDATE npc_types SET loottable_id = :crystalshard_guard_grabadin_lt: WHERE id in (756043); # #Guard_Grabadin 99
UPDATE npc_types SET loottable_id = :crystalshard_guard_hollander_lt: WHERE id in (756045); # #Guard_Hollander 99
UPDATE npc_types SET loottable_id = :crystalshard_guard_justik_lt: WHERE id in (756065); # #Guard_Justik 99
UPDATE npc_types SET loottable_id = :crystalshard_guard_kevin_lt: WHERE id in (756050); # #Guard_Kevin 99
UPDATE npc_types SET loottable_id = :crystalshard_guard_kithon_lt: WHERE id in (756067); # #Guard_Kithon 99
UPDATE npc_types SET loottable_id = :crystalshard_guard_kristen_lt: WHERE id in (756059); # #Guard_Kristen 99
UPDATE npc_types SET loottable_id = :crystalshard_guard_slacey_lt: WHERE id in (756077); # #Guard_Slacey 99
UPDATE npc_types SET loottable_id = :crystalshard_guard_solistak_lt: WHERE id in (756064); # #Guard_Solistak 99
UPDATE npc_types SET loottable_id = :crystalshard_hardat_gemshard_lt: WHERE id in (756069); # #Hardat_Gemshard 99
UPDATE npc_types SET loottable_id = :crystalshard_hidden_crystal_lt: WHERE id in (756060); # #hidden_crystal 1
UPDATE npc_types SET loottable_id = :crystalshard_historian_baenek_lt: WHERE id in (756080); # #Historian_Baenek 99
UPDATE npc_types SET loottable_id = :crystalshard_jexlplix_lt: WHERE id in (756001); # #Jexlplix 97
UPDATE npc_types SET loottable_id = :crystalshard_juytabu_lt: WHERE id in (756088); # #Juytabu 97
UPDATE npc_types SET loottable_id = :crystalshard_kagzinai_lt: WHERE id in (756020); # #Kagzinai 97
UPDATE npc_types SET loottable_id = :crystalshard_kodik_lt: WHERE id in (756095); # #Kodik 100
UPDATE npc_types SET loottable_id = :crystalshard_kramble_gemshard_lt: WHERE id in (756058); # #Kramble_Gemshard 99
UPDATE npc_types SET loottable_id = :crystalshard_lerabdi_lt: WHERE id in (756049); # #Lerabdi 97
UPDATE npc_types SET loottable_id = :crystalshard_milliace_gemshard_lt: WHERE id in (756071); # #Milliace_Gemshard 99
UPDATE npc_types SET loottable_id = :crystalshard_nadalia_coldmist_lt: WHERE id in (756039); # #Nadalia_Coldmist 99
UPDATE npc_types SET loottable_id = :crystalshard_nanokik_lt: WHERE id in (756013); # #Nanokik 100
UPDATE npc_types SET loottable_id = :crystalshard_orogol_lt: WHERE id in (756006); # #Orogol 70
UPDATE npc_types SET loottable_id = :crystalshard_praps_gemshard_lt: WHERE id in (756072); # #Praps_Gemshard 99
UPDATE npc_types SET loottable_id = :crystalshard_prospector_wersan_lt: WHERE id in (756025); # #Prospector_Wersan 101
UPDATE npc_types SET loottable_id = :crystalshard_q_controller_lt: WHERE id in (756051); # #Q_controller 1
UPDATE npc_types SET loottable_id = :crystalshard_scout_grandan_lt: WHERE id in (756061); # #Scout_Grandan 99
UPDATE npc_types SET loottable_id = :crystalshard_soren_coldheart_lt: WHERE id in (756066); # #Soren_Coldheart 99
UPDATE npc_types SET loottable_id = :crystalshard_tacy_mistheart_lt: WHERE id in (756046); # #Tacy_MistHeart 99
UPDATE npc_types SET loottable_id = :crystalshard_veldmir_velweaver_lt: WHERE id in (756054); # #Veldmir_Velweaver 99
UPDATE npc_types SET loottable_id = :crystalshard_vevina_velweaver_lt: WHERE id in (756063); # #Vevina_Velweaver 99
UPDATE npc_types SET loottable_id = :crystalshard_xalzinai_lt: WHERE id in (756102); # #Xalzinai 97
UPDATE npc_types SET loottable_id = :crystalshard_ysylfar_lt: WHERE id in (756062); # #Ysylfar 100
UPDATE npc_types SET loottable_id = :crystalshard_zarinarn_lt: WHERE id in (756105); # #Zarinarn 97
UPDATE npc_types SET loottable_id = :crystalshard_an_enslaved_turmoil_toad_lt: WHERE id in (756008); # an_enslaved_Turmoil_Toad 100
UPDATE npc_types SET loottable_id = :crystalshard_an_icy_leech_lt: WHERE id in (756083, 756101); # an_icy_leech 96
UPDATE npc_types SET loottable_id = :crystalshard_an_icy_terror_lt: WHERE id in (756097); # an_icy_terror 96
UPDATE npc_types SET loottable_id = :crystalshard_a_coldain_miner_lt: WHERE id in (756068, 756074); # a_Coldain_miner 99
UPDATE npc_types SET loottable_id = :crystalshard_a_crystal_cluster_lt: WHERE id in (756007); # a_crystal_cluster 50
UPDATE npc_types SET loottable_id = :crystalshard_a_crystal_crawler_lt: WHERE id in (756035, 756092, 756103); # a_crystal_crawler 97
UPDATE npc_types SET loottable_id = :crystalshard_a_crystal_spiderling_lt: WHERE id in (756107, 756110); # a_crystal_spiderling 97
UPDATE npc_types SET loottable_id = :crystalshard_a_crystal_webmaster_lt: WHERE id in (756099, 756108); # a_crystal_webmaster 97
UPDATE npc_types SET loottable_id = :crystalshard_a_crystal_webspinner_lt: WHERE id in (756106); # a_crystal_webspinner 96
UPDATE npc_types SET loottable_id = :crystalshard_a_demented_dwarf_lt: WHERE id in (756038, 756053); # a_demented_dwarf 96
UPDATE npc_types SET loottable_id = :crystalshard_a_geonid_lt: WHERE id in (756094, 756096, 756100, 756104); # a_geonid 100
UPDATE npc_types SET loottable_id = :crystalshard_a_hollow_terror_lt: WHERE id in (756076, 756089); # a_hollow_terror 95
UPDATE npc_types SET loottable_id = :crystalshard_a_lazy_orc_lt: WHERE id in (756017, 756018); # a_lazy_orc 97
UPDATE npc_types SET loottable_id = :crystalshard_a_pure_terror_lt: WHERE id in (756081, 756082); # a_pure_terror 97
UPDATE npc_types SET loottable_id = :crystalshard_a_regal_crawler_lt: WHERE id in (756109); # a_regal_crawler 98
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_digger_lt: WHERE id in (756021); # a_Ry`Gorr_digger 97
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_excavator_lt: WHERE id in (756016); # a_Ry`Gorr_excavator 97
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_guard_lt: WHERE id in (756037); # a_Ry`Gorr_guard 97
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_messenger_lt: WHERE id in (756014); # a_Ry`Gorr_messenger 96
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_miner_lt: WHERE id in (756000, 756002, 756009, 756026, 756030, 756041); # a_Ry`Gorr_miner 97
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_oracle_lt: WHERE id in (756010, 756012); # a_Ry`Gorr_oracle 97
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_overseer_lt: WHERE id in (756023, 756034); # a_Ry`Gorr_overseer 98
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_prospector_lt: WHERE id in (756011); # a_Ry`Gorr_prospector 97
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_shaman_lt: WHERE id in (756028); # a_Ry`Gorr_shaman 97
UPDATE npc_types SET loottable_id = :crystalshard_a_rygorr_watchman_lt: WHERE id in (756003, 756004, 756005, 756024); # a_Ry`Gorr_watchman 96
UPDATE npc_types SET loottable_id = :crystalshard_a_spinechiller_spider_lt: WHERE id in (756036, 756040, 756044); # a_spinechiller_spider 97
UPDATE npc_types SET loottable_id = :crystalshard_a_stalag_terror_lt: WHERE id in (756084, 756086, 756087); # a_stalag_terror 95
UPDATE npc_types SET loottable_id = :crystalshard_a_tentacle_terror_lt: WHERE id in (756029, 756031, 756033); # a_tentacle_terror 95
UPDATE npc_types SET loottable_id = :crystalshard_a_tentacle_tormentor_lt: WHERE id in (756032); # a_tentacle_tormentor 95
UPDATE npc_types SET loottable_id = :crystalshard_a_velium_crawler_lt: WHERE id in (756027); # a_velium_crawler 96
