INSERT INTO loottable(name) VALUES('crystalshard_a_crystal_lurker'); # :crystalshard_a_crystal_lurker_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_dead_spider'); # :crystalshard_a_dead_spider_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_dead_tentacle'); # :crystalshard_a_dead_tentacle_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_inspector'); # :crystalshard_a_rygorr_inspector_lt:
INSERT INTO loottable(name) VALUES('crystalshard_baffod_the_wayward'); # :crystalshard_baffod_the_wayward_lt:
INSERT INTO loottable(name) VALUES('crystalshard_bronigan'); # :crystalshard_bronigan_lt:
INSERT INTO loottable(name) VALUES('crystalshard_captain_dunstan_coldheart'); # :crystalshard_captain_dunstan_coldheart_lt:
INSERT INTO loottable(name) VALUES('crystalshard_cassia_gemshard'); # :crystalshard_cassia_gemshard_lt:
INSERT INTO loottable(name) VALUES('crystalshard_derron_coldmist'); # :crystalshard_derron_coldmist_lt:
INSERT INTO loottable(name) VALUES('crystalshard_dirk_coldsmith'); # :crystalshard_dirk_coldsmith_lt:
INSERT INTO loottable(name) VALUES('crystalshard_elsa_icegem'); # :crystalshard_elsa_icegem_lt:
INSERT INTO loottable(name) VALUES('crystalshard_engineer_colle'); # :crystalshard_engineer_colle_lt:
INSERT INTO loottable(name) VALUES('crystalshard_flint_velweaver'); # :crystalshard_flint_velweaver_lt:
INSERT INTO loottable(name) VALUES('crystalshard_fridjorn'); # :crystalshard_fridjorn_lt:
INSERT INTO loottable(name) VALUES('crystalshard_fridjornbody'); # :crystalshard_fridjornbody_lt:
INSERT INTO loottable(name) VALUES('crystalshard_fuller_velweaver'); # :crystalshard_fuller_velweaver_lt:
INSERT INTO loottable(name) VALUES('crystalshard_gilliad_coldheart'); # :crystalshard_gilliad_coldheart_lt:
INSERT INTO loottable(name) VALUES('crystalshard_grabble_coldheart'); # :crystalshard_grabble_coldheart_lt:
INSERT INTO loottable(name) VALUES('crystalshard_graght_the_little'); # :crystalshard_graght_the_little_lt:
INSERT INTO loottable(name) VALUES('crystalshard_guard_evercold'); # :crystalshard_guard_evercold_lt:
INSERT INTO loottable(name) VALUES('crystalshard_guard_grabadin'); # :crystalshard_guard_grabadin_lt:
INSERT INTO loottable(name) VALUES('crystalshard_guard_hollander'); # :crystalshard_guard_hollander_lt:
INSERT INTO loottable(name) VALUES('crystalshard_guard_justik'); # :crystalshard_guard_justik_lt:
INSERT INTO loottable(name) VALUES('crystalshard_guard_kevin'); # :crystalshard_guard_kevin_lt:
INSERT INTO loottable(name) VALUES('crystalshard_guard_kithon'); # :crystalshard_guard_kithon_lt:
INSERT INTO loottable(name) VALUES('crystalshard_guard_kristen'); # :crystalshard_guard_kristen_lt:
INSERT INTO loottable(name) VALUES('crystalshard_guard_slacey'); # :crystalshard_guard_slacey_lt:
INSERT INTO loottable(name) VALUES('crystalshard_guard_solistak'); # :crystalshard_guard_solistak_lt:
INSERT INTO loottable(name) VALUES('crystalshard_hardat_gemshard'); # :crystalshard_hardat_gemshard_lt:
INSERT INTO loottable(name) VALUES('crystalshard_hidden_crystal'); # :crystalshard_hidden_crystal_lt:
INSERT INTO loottable(name) VALUES('crystalshard_historian_baenek'); # :crystalshard_historian_baenek_lt:
INSERT INTO loottable(name) VALUES('crystalshard_jexlplix'); # :crystalshard_jexlplix_lt:
INSERT INTO loottable(name) VALUES('crystalshard_juytabu'); # :crystalshard_juytabu_lt:
INSERT INTO loottable(name) VALUES('crystalshard_kagzinai'); # :crystalshard_kagzinai_lt:
INSERT INTO loottable(name) VALUES('crystalshard_kodik'); # :crystalshard_kodik_lt:
INSERT INTO loottable(name) VALUES('crystalshard_kramble_gemshard'); # :crystalshard_kramble_gemshard_lt:
INSERT INTO loottable(name) VALUES('crystalshard_lerabdi'); # :crystalshard_lerabdi_lt:
INSERT INTO loottable(name) VALUES('crystalshard_milliace_gemshard'); # :crystalshard_milliace_gemshard_lt:
INSERT INTO loottable(name) VALUES('crystalshard_nadalia_coldmist'); # :crystalshard_nadalia_coldmist_lt:
INSERT INTO loottable(name) VALUES('crystalshard_nanokik'); # :crystalshard_nanokik_lt:
INSERT INTO loottable(name) VALUES('crystalshard_orogol'); # :crystalshard_orogol_lt:
INSERT INTO loottable(name) VALUES('crystalshard_praps_gemshard'); # :crystalshard_praps_gemshard_lt:
INSERT INTO loottable(name) VALUES('crystalshard_prospector_wersan'); # :crystalshard_prospector_wersan_lt:
INSERT INTO loottable(name) VALUES('crystalshard_q_controller'); # :crystalshard_q_controller_lt:
INSERT INTO loottable(name) VALUES('crystalshard_scout_grandan'); # :crystalshard_scout_grandan_lt:
INSERT INTO loottable(name) VALUES('crystalshard_soren_coldheart'); # :crystalshard_soren_coldheart_lt:
INSERT INTO loottable(name) VALUES('crystalshard_tacy_mistheart'); # :crystalshard_tacy_mistheart_lt:
INSERT INTO loottable(name) VALUES('crystalshard_veldmir_velweaver'); # :crystalshard_veldmir_velweaver_lt:
INSERT INTO loottable(name) VALUES('crystalshard_vevina_velweaver'); # :crystalshard_vevina_velweaver_lt:
INSERT INTO loottable(name) VALUES('crystalshard_xalzinai'); # :crystalshard_xalzinai_lt:
INSERT INTO loottable(name) VALUES('crystalshard_ysylfar'); # :crystalshard_ysylfar_lt:
INSERT INTO loottable(name) VALUES('crystalshard_zarinarn'); # :crystalshard_zarinarn_lt:
INSERT INTO loottable(name) VALUES('crystalshard_an_enslaved_turmoil_toad'); # :crystalshard_an_enslaved_turmoil_toad_lt:
INSERT INTO loottable(name) VALUES('crystalshard_an_icy_leech'); # :crystalshard_an_icy_leech_lt:
INSERT INTO loottable(name) VALUES('crystalshard_an_icy_terror'); # :crystalshard_an_icy_terror_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_coldain_miner'); # :crystalshard_a_coldain_miner_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_crystal_cluster'); # :crystalshard_a_crystal_cluster_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_crystal_crawler'); # :crystalshard_a_crystal_crawler_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_crystal_spiderling'); # :crystalshard_a_crystal_spiderling_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_crystal_webmaster'); # :crystalshard_a_crystal_webmaster_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_crystal_webspinner'); # :crystalshard_a_crystal_webspinner_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_demented_dwarf'); # :crystalshard_a_demented_dwarf_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_geonid'); # :crystalshard_a_geonid_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_hollow_terror'); # :crystalshard_a_hollow_terror_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_lazy_orc'); # :crystalshard_a_lazy_orc_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_pure_terror'); # :crystalshard_a_pure_terror_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_regal_crawler'); # :crystalshard_a_regal_crawler_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_digger'); # :crystalshard_a_rygorr_digger_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_excavator'); # :crystalshard_a_rygorr_excavator_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_guard'); # :crystalshard_a_rygorr_guard_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_messenger'); # :crystalshard_a_rygorr_messenger_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_miner'); # :crystalshard_a_rygorr_miner_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_oracle'); # :crystalshard_a_rygorr_oracle_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_overseer'); # :crystalshard_a_rygorr_overseer_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_prospector'); # :crystalshard_a_rygorr_prospector_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_shaman'); # :crystalshard_a_rygorr_shaman_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_rygorr_watchman'); # :crystalshard_a_rygorr_watchman_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_spinechiller_spider'); # :crystalshard_a_spinechiller_spider_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_stalag_terror'); # :crystalshard_a_stalag_terror_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_tentacle_terror'); # :crystalshard_a_tentacle_terror_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_tentacle_tormentor'); # :crystalshard_a_tentacle_tormentor_lt:
INSERT INTO loottable(name) VALUES('crystalshard_a_velium_crawler'); # :crystalshard_a_velium_crawler_lt:
