INSERT INTO loottable(name) VALUES('eastwastesshard_an_airship'); # :eastwastesshard_an_airship_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_homesick_turmoil_toad'); # :eastwastesshard_a_homesick_turmoil_toad_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_portal'); # :eastwastesshard_a_portal_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_ship_wreck'); # :eastwastesshard_a_ship_wreck_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_baffod_the_wayward'); # :eastwastesshard_baffod_the_wayward_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_blacksmith_galrim'); # :eastwastesshard_blacksmith_galrim_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_dirgen'); # :eastwastesshard_dirgen_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_drjek'); # :eastwastesshard_drjek_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_emissary_kordim'); # :eastwastesshard_emissary_kordim_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_estraidentryaura'); # :eastwastesshard_estraidentryaura_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_falmia'); # :eastwastesshard_falmia_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_galurg'); # :eastwastesshard_galurg_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_general_fryn'); # :eastwastesshard_general_fryn_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_general_horlan'); # :eastwastesshard_general_horlan_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_general_urgund'); # :eastwastesshard_general_urgund_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_gildorn_icebreath'); # :eastwastesshard_gildorn_icebreath_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_hurble'); # :eastwastesshard_hurble_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_jorga'); # :eastwastesshard_jorga_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_jornin'); # :eastwastesshard_jornin_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_kedd_the_frostbitten'); # :eastwastesshard_kedd_the_frostbitten_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_mirlil'); # :eastwastesshard_mirlil_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_nalain_gartand'); # :eastwastesshard_nalain_gartand_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_silnik'); # :eastwastesshard_silnik_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_taelanie_oakenheart'); # :eastwastesshard_taelanie_oakenheart_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_tramric_the_pessimistic'); # :eastwastesshard_tramric_the_pessimistic_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_treasure_hunter_robairn'); # :eastwastesshard_treasure_hunter_robairn_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_ulv'); # :eastwastesshard_ulv_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_welken'); # :eastwastesshard_welken_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_yalfi'); # :eastwastesshard_yalfi_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_zeixshi-kar'); # :eastwastesshard_zeixshi-kar_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_an_amygdalan_knight'); # :eastwastesshard_an_amygdalan_knight_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_an_amygdalan_warrior'); # :eastwastesshard_an_amygdalan_warrior_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_an_animated_spell_book'); # :eastwastesshard_an_animated_spell_book_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_an_elder_snow_griffin'); # :eastwastesshard_an_elder_snow_griffin_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_an_elite_bodyguard'); # :eastwastesshard_an_elite_bodyguard_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_an_empty_snow_bunny_trap'); # :eastwastesshard_an_empty_snow_bunny_trap_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_an_ulthork_hunter'); # :eastwastesshard_an_ulthork_hunter_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_an_ulthork_man_o_war'); # :eastwastesshard_an_ulthork_man_o_war_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_an_ulthork_warrior'); # :eastwastesshard_an_ulthork_warrior_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_campfire'); # :eastwastesshard_a_campfire_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_coldain_blacksmith'); # :eastwastesshard_a_coldain_blacksmith_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_coldain_cook'); # :eastwastesshard_a_coldain_cook_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_coldain_hunter'); # :eastwastesshard_a_coldain_hunter_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_coldain_lookout'); # :eastwastesshard_a_coldain_lookout_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_coldain_marauder'); # :eastwastesshard_a_coldain_marauder_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_coldain_missionary'); # :eastwastesshard_a_coldain_missionary_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_coldain_skinner'); # :eastwastesshard_a_coldain_skinner_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_coldain_warrior'); # :eastwastesshard_a_coldain_warrior_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_crate'); # :eastwastesshard_a_crate_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_crate_of_weapons'); # :eastwastesshard_a_crate_of_weapons_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_dead_adventurer'); # :eastwastesshard_a_dead_adventurer_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_dire_wolf'); # :eastwastesshard_a_dire_wolf_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_fear_shardling'); # :eastwastesshard_a_fear_shardling_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_frost_giant'); # :eastwastesshard_a_frost_giant_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_frost_giant_captain'); # :eastwastesshard_a_frost_giant_captain_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_frost_giant_savage'); # :eastwastesshard_a_frost_giant_savage_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_frost_giant_scout'); # :eastwastesshard_a_frost_giant_scout_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_manticore'); # :eastwastesshard_a_manticore_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_mindless_thrall'); # :eastwastesshard_a_mindless_thrall_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_nightmare'); # :eastwastesshard_a_nightmare_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_rygorr_centurion'); # :eastwastesshard_a_rygorr_centurion_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_rygorr_clan_lookout'); # :eastwastesshard_a_rygorr_clan_lookout_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_rygorr_clan_scout'); # :eastwastesshard_a_rygorr_clan_scout_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_rygorr_deliverer'); # :eastwastesshard_a_rygorr_deliverer_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_rygorr_legionaire'); # :eastwastesshard_a_rygorr_legionaire_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_rygorr_snow_trooper'); # :eastwastesshard_a_rygorr_snow_trooper_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_samhain'); # :eastwastesshard_a_samhain_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_savage_dire_wolf'); # :eastwastesshard_a_savage_dire_wolf_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_smuggler'); # :eastwastesshard_a_smuggler_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_snow_griffin'); # :eastwastesshard_a_snow_griffin_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_spinechiller_spider'); # :eastwastesshard_a_spinechiller_spider_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_suspicious_coldain'); # :eastwastesshard_a_suspicious_coldain_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_suspicious_frost_giant'); # :eastwastesshard_a_suspicious_frost_giant_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_suspicious_rygorr'); # :eastwastesshard_a_suspicious_rygorr_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_tundra_kodiak'); # :eastwastesshard_a_tundra_kodiak_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_tundra_mammoth'); # :eastwastesshard_a_tundra_mammoth_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_walrus'); # :eastwastesshard_a_walrus_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_wooly_mammoth'); # :eastwastesshard_a_wooly_mammoth_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_a_wooly_rhino'); # :eastwastesshard_a_wooly_rhino_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_fsp-general-noeffect'); # :eastwastesshard_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_kromrif_guardsman'); # :eastwastesshard_kromrif_guardsman_lt:
INSERT INTO loottable(name) VALUES('eastwastesshard_mystic_of_rygorr'); # :eastwastesshard_mystic_of_rygorr_lt:
