INSERT INTO loottable(name) VALUES('cityofbronze_alchemist_xortiv'); # :cityofbronze_alchemist_xortiv_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_archon_xalvir'); # :cityofbronze_archon_xalvir_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_byqian_yuarin'); # :cityofbronze_byqian_yuarin_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_caindis_belongings'); # :cityofbronze_caindis_belongings_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_cenqua_corvia'); # :cityofbronze_cenqua_corvia_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_cerskel_gorinar'); # :cityofbronze_cerskel_gorinar_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_culdylri'); # :cityofbronze_culdylri_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_deathsqueak'); # :cityofbronze_deathsqueak_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_dredkel_pianair'); # :cityofbronze_dredkel_pianair_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_dreltnurn_kairnai'); # :cityofbronze_dreltnurn_kairnai_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_drukaw_fefri'); # :cityofbronze_drukaw_fefri_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_druthur'); # :cityofbronze_druthur_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_faltar'); # :cityofbronze_faltar_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_fewust_tanialor'); # :cityofbronze_fewust_tanialor_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_gorinof_tulsoi'); # :cityofbronze_gorinof_tulsoi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_guard_kalinir'); # :cityofbronze_guard_kalinir_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_hainif_kallion'); # :cityofbronze_hainif_kallion_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_jerinos'); # :cityofbronze_jerinos_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_joral'); # :cityofbronze_joral_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_kolain_hoanri'); # :cityofbronze_kolain_hoanri_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_lell_fianru'); # :cityofbronze_lell_fianru_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_lijkas_belongings'); # :cityofbronze_lijkas_belongings_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_loaksi_siandoz'); # :cityofbronze_loaksi_siandoz_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_losrok_reinat'); # :cityofbronze_losrok_reinat_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_lygh_trianor'); # :cityofbronze_lygh_trianor_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_merchant_oarryn'); # :cityofbronze_merchant_oarryn_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_mokdani_dalianir'); # :cityofbronze_mokdani_dalianir_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_mortif_risoan'); # :cityofbronze_mortif_risoan_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_nismor_zalirna'); # :cityofbronze_nismor_zalirna_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_nulbar'); # :cityofbronze_nulbar_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_oashim'); # :cityofbronze_oashim_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_olosir'); # :cityofbronze_olosir_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_pibmos_hyaniro'); # :cityofbronze_pibmos_hyaniro_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_prisoner_iiiv_vioi'); # :cityofbronze_prisoner_iiiv_vioi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_record_keeper_buorin'); # :cityofbronze_record_keeper_buorin_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_reldari_calsitior'); # :cityofbronze_reldari_calsitior_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_rulbiks_box_of_files'); # :cityofbronze_rulbiks_box_of_files_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_sholano'); # :cityofbronze_sholano_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_snethos_kariani'); # :cityofbronze_snethos_kariani_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_snyld_faiandi'); # :cityofbronze_snyld_faiandi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_sresur_caewan'); # :cityofbronze_sresur_caewan_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_srezens_belongings'); # :cityofbronze_srezens_belongings_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_swirn_hynalori'); # :cityofbronze_swirn_hynalori_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_tasali_faedoi'); # :cityofbronze_tasali_faedoi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_theq_casliri'); # :cityofbronze_theq_casliri_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_tyzen'); # :cityofbronze_tyzen_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_uyyina'); # :cityofbronze_uyyina_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_uyyinas_belongings'); # :cityofbronze_uyyinas_belongings_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_vegsqua_bernoshi'); # :cityofbronze_vegsqua_bernoshi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_verobis_belongings'); # :cityofbronze_verobis_belongings_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_vinloi'); # :cityofbronze_vinloi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_vordinar_maori'); # :cityofbronze_vordinar_maori_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_wilstoi_farniad'); # :cityofbronze_wilstoi_farniad_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_alijara'); # :cityofbronze_alijara_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_an_apprentice_blacksmith'); # :cityofbronze_an_apprentice_blacksmith_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_an_archon'); # :cityofbronze_an_archon_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_an_enthusiastic_papyrus_maker'); # :cityofbronze_an_enthusiastic_papyrus_maker_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_an_honest_citizen'); # :cityofbronze_an_honest_citizen_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_an_imposing_archon'); # :cityofbronze_an_imposing_archon_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_an_industrious_blacksmith'); # :cityofbronze_an_industrious_blacksmith_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_an_insipid_government_official'); # :cityofbronze_an_insipid_government_official_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_an_irritated_office_worker'); # :cityofbronze_an_irritated_office_worker_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_an_office_worker'); # :cityofbronze_an_office_worker_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_bankers_chest'); # :cityofbronze_a_bankers_chest_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_blacksmith'); # :cityofbronze_a_blacksmith_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_blind_dreamer'); # :cityofbronze_a_blind_dreamer_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_bloodthirsty_carnifex'); # :cityofbronze_a_bloodthirsty_carnifex_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_bored_potter'); # :cityofbronze_a_bored_potter_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_boulder'); # :cityofbronze_a_boulder_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_bureaucrat'); # :cityofbronze_a_bureaucrat_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_busy_cook'); # :cityofbronze_a_busy_cook_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_busy_papyrus_maker'); # :cityofbronze_a_busy_papyrus_maker_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_carnifex'); # :cityofbronze_a_carnifex_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_citizen'); # :cityofbronze_a_citizen_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_cook'); # :cityofbronze_a_cook_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_cruel_carnifex'); # :cityofbronze_a_cruel_carnifex_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_detailed_record_keeper'); # :cityofbronze_a_detailed_record_keeper_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_diligent_potter'); # :cityofbronze_a_diligent_potter_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_diseased_oashim'); # :cityofbronze_a_diseased_oashim_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_domesticated_braxi'); # :cityofbronze_a_domesticated_braxi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_domesticated_selyrah'); # :cityofbronze_a_domesticated_selyrah_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_dour_bureaucrat'); # :cityofbronze_a_dour_bureaucrat_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_dull_record_keeper'); # :cityofbronze_a_dull_record_keeper_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_dutiful_guard'); # :cityofbronze_a_dutiful_guard_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_faithful_citizen'); # :cityofbronze_a_faithful_citizen_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_feral_grendlaen'); # :cityofbronze_a_feral_grendlaen_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_forlorn_prisoner'); # :cityofbronze_a_forlorn_prisoner_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_government_official'); # :cityofbronze_a_government_official_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_guard'); # :cityofbronze_a_guard_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_jug_of_cider'); # :cityofbronze_a_jug_of_cider_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_magistrate'); # :cityofbronze_a_magistrate_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_merchant'); # :cityofbronze_a_merchant_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_miserly_government_official'); # :cityofbronze_a_miserly_government_official_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_mundane_office_worker'); # :cityofbronze_a_mundane_office_worker_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_potter'); # :cityofbronze_a_potter_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_prisoner'); # :cityofbronze_a_prisoner_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_prudent_merchant'); # :cityofbronze_a_prudent_merchant_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_record_keeper'); # :cityofbronze_a_record_keeper_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_resolute_bureaucrat'); # :cityofbronze_a_resolute_bureaucrat_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_ruthless_archon'); # :cityofbronze_a_ruthless_archon_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_sentry_stone'); # :cityofbronze_a_sentry_stone_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_shrewd_merchant'); # :cityofbronze_a_shrewd_merchant_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_sleeping_citizen'); # :cityofbronze_a_sleeping_citizen_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_solemn_guard'); # :cityofbronze_a_solemn_guard_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_strangleweed'); # :cityofbronze_a_strangleweed_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_tired_cook'); # :cityofbronze_a_tired_cook_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_tired_papyrus_maker'); # :cityofbronze_a_tired_papyrus_maker_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_wild_braxi'); # :cityofbronze_a_wild_braxi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_wild_selyrah'); # :cityofbronze_a_wild_selyrah_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_a_woeful_prisoner'); # :cityofbronze_a_woeful_prisoner_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_caindi'); # :cityofbronze_caindi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_donair'); # :cityofbronze_donair_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_fsp-general-noeffect'); # :cityofbronze_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_krosek'); # :cityofbronze_krosek_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_lijka'); # :cityofbronze_lijka_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_lijkas_braxi'); # :cityofbronze_lijkas_braxi_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_plonari'); # :cityofbronze_plonari_lt:
INSERT INTO loottable(name) VALUES('cityofbronze_wanidor'); # :cityofbronze_wanidor_lt:
