INSERT INTO loottable(name) VALUES('sarithcity_aquarn_the_tidalmaster'); # :sarithcity_aquarn_the_tidalmaster_lt:
INSERT INTO loottable(name) VALUES('sarithcity_bertra_harren'); # :sarithcity_bertra_harren_lt:
INSERT INTO loottable(name) VALUES('sarithcity_captain_lonz_duran'); # :sarithcity_captain_lonz_duran_lt:
INSERT INTO loottable(name) VALUES('sarithcity_captain_ullas'); # :sarithcity_captain_ullas_lt:
INSERT INTO loottable(name) VALUES('sarithcity_cartographer_weken'); # :sarithcity_cartographer_weken_lt:
INSERT INTO loottable(name) VALUES('sarithcity_chef_rolland'); # :sarithcity_chef_rolland_lt:
INSERT INTO loottable(name) VALUES('sarithcity_commander_marrien_kavus'); # :sarithcity_commander_marrien_kavus_lt:
INSERT INTO loottable(name) VALUES('sarithcity_coraln_seagazer'); # :sarithcity_coraln_seagazer_lt:
INSERT INTO loottable(name) VALUES('sarithcity_dahrius_lato'); # :sarithcity_dahrius_lato_lt:
INSERT INTO loottable(name) VALUES('sarithcity_falthen_berros'); # :sarithcity_falthen_berros_lt:
INSERT INTO loottable(name) VALUES('sarithcity_fisherman_ludwigvon'); # :sarithcity_fisherman_ludwigvon_lt:
INSERT INTO loottable(name) VALUES('sarithcity_fisherman_tayron'); # :sarithcity_fisherman_tayron_lt:
INSERT INTO loottable(name) VALUES('sarithcity_general_serobi'); # :sarithcity_general_serobi_lt:
INSERT INTO loottable(name) VALUES('sarithcity_governor_parrin_wenst'); # :sarithcity_governor_parrin_wenst_lt:
INSERT INTO loottable(name) VALUES('sarithcity_guard_captain_naraind_reles'); # :sarithcity_guard_captain_naraind_reles_lt:
INSERT INTO loottable(name) VALUES('sarithcity_kayquon'); # :sarithcity_kayquon_lt:
INSERT INTO loottable(name) VALUES('sarithcity_keeli_syzen'); # :sarithcity_keeli_syzen_lt:
INSERT INTO loottable(name) VALUES('sarithcity_lieutenant_arulien'); # :sarithcity_lieutenant_arulien_lt:
INSERT INTO loottable(name) VALUES('sarithcity_marius_lenn'); # :sarithcity_marius_lenn_lt:
INSERT INTO loottable(name) VALUES('sarithcity_merchant_stires'); # :sarithcity_merchant_stires_lt:
INSERT INTO loottable(name) VALUES('sarithcity_prison_warden_tuley'); # :sarithcity_prison_warden_tuley_lt:
INSERT INTO loottable(name) VALUES('sarithcity_quartermaster_gilles'); # :sarithcity_quartermaster_gilles_lt:
INSERT INTO loottable(name) VALUES('sarithcity_rebel_leader_ain_kavus'); # :sarithcity_rebel_leader_ain_kavus_lt:
INSERT INTO loottable(name) VALUES('sarithcity_renarra'); # :sarithcity_renarra_lt:
INSERT INTO loottable(name) VALUES('sarithcity_reqin'); # :sarithcity_reqin_lt:
INSERT INTO loottable(name) VALUES('sarithcity_riallion_cassand'); # :sarithcity_riallion_cassand_lt:
INSERT INTO loottable(name) VALUES('sarithcity_ruthen_sarros'); # :sarithcity_ruthen_sarros_lt:
INSERT INTO loottable(name) VALUES('sarithcity_senora_kenver'); # :sarithcity_senora_kenver_lt:
INSERT INTO loottable(name) VALUES('sarithcity_sergeant_elvan'); # :sarithcity_sergeant_elvan_lt:
INSERT INTO loottable(name) VALUES('sarithcity_sergeant_karus'); # :sarithcity_sergeant_karus_lt:
INSERT INTO loottable(name) VALUES('sarithcity_sergeant_larren'); # :sarithcity_sergeant_larren_lt:
INSERT INTO loottable(name) VALUES('sarithcity_solphius_kelprunner'); # :sarithcity_solphius_kelprunner_lt:
INSERT INTO loottable(name) VALUES('sarithcity_tidalmage_karith'); # :sarithcity_tidalmage_karith_lt:
INSERT INTO loottable(name) VALUES('sarithcity_tide_priest_marinsi'); # :sarithcity_tide_priest_marinsi_lt:
INSERT INTO loottable(name) VALUES('sarithcity_tiljin_of_the_deep'); # :sarithcity_tiljin_of_the_deep_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_arms_dealer'); # :sarithcity_an_arms_dealer_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_assassin'); # :sarithcity_an_orators_army_assassin_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_battlemage'); # :sarithcity_an_orators_army_battlemage_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_beast_master'); # :sarithcity_an_orators_army_beast_master_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_beast_trainer'); # :sarithcity_an_orators_army_beast_trainer_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_bishop'); # :sarithcity_an_orators_army_bishop_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_conscript'); # :sarithcity_an_orators_army_conscript_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_dark_mage'); # :sarithcity_an_orators_army_dark_mage_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_death_knight'); # :sarithcity_an_orators_army_death_knight_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_nature_mage'); # :sarithcity_an_orators_army_nature_mage_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_primal_mage'); # :sarithcity_an_orators_army_primal_mage_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_ranger'); # :sarithcity_an_orators_army_ranger_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_scout'); # :sarithcity_an_orators_army_scout_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_soldier'); # :sarithcity_an_orators_army_soldier_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_strategist'); # :sarithcity_an_orators_army_strategist_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_orators_army_warpriest'); # :sarithcity_an_orators_army_warpriest_lt:
INSERT INTO loottable(name) VALUES('sarithcity_an_osekas_chosen_guardian'); # :sarithcity_an_osekas_chosen_guardian_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_bar_patron'); # :sarithcity_a_bar_patron_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_bar_server'); # :sarithcity_a_bar_server_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_battered_sentry_stone'); # :sarithcity_a_battered_sentry_stone_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_bedraggled_braxi'); # :sarithcity_a_bedraggled_braxi_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_braxi_mount'); # :sarithcity_a_braxi_mount_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_fisherman'); # :sarithcity_a_fisherman_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_goral_mount'); # :sarithcity_a_goral_mount_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_great_white_shark'); # :sarithcity_a_great_white_shark_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_grizzled_war_beast'); # :sarithcity_a_grizzled_war_beast_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_hammerhead_shark'); # :sarithcity_a_hammerhead_shark_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_hostage_family_member'); # :sarithcity_a_hostage_family_member_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_hostage_taker'); # :sarithcity_a_hostage_taker_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_hungry_predator'); # :sarithcity_a_hungry_predator_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_kedge_defender'); # :sarithcity_a_kedge_defender_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_kedge_oracle'); # :sarithcity_a_kedge_oracle_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_kedge_watermancer'); # :sarithcity_a_kedge_watermancer_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_king_crab'); # :sarithcity_a_king_crab_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_large_great_white_shark'); # :sarithcity_a_large_great_white_shark_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_large_sea_turtle'); # :sarithcity_a_large_sea_turtle_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_large_squid'); # :sarithcity_a_large_squid_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_rebel_skirmisher'); # :sarithcity_a_rebel_skirmisher_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_salt-water_piranha'); # :sarithcity_a_salt-water_piranha_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_citizen'); # :sarithcity_a_sarith_citizen_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_city_official'); # :sarithcity_a_sarith_city_official_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_guardsman'); # :sarithcity_a_sarith_guardsman_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_guardsman_veteran'); # :sarithcity_a_sarith_guardsman_veteran_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_prisoner'); # :sarithcity_a_sarith_prisoner_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_rebel_fighter'); # :sarithcity_a_sarith_rebel_fighter_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_rebel_prisoner'); # :sarithcity_a_sarith_rebel_prisoner_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_rebel_tidalmage'); # :sarithcity_a_sarith_rebel_tidalmage_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_rebel_tidepriest'); # :sarithcity_a_sarith_rebel_tidepriest_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_tidalmage'); # :sarithcity_a_sarith_tidalmage_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_tidalmage_master'); # :sarithcity_a_sarith_tidalmage_master_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_tidal_guardian'); # :sarithcity_a_sarith_tidal_guardian_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sarith_tide_priest'); # :sarithcity_a_sarith_tide_priest_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_sentry_stone'); # :sarithcity_a_sentry_stone_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_war_beast'); # :sarithcity_a_war_beast_lt:
INSERT INTO loottable(name) VALUES('sarithcity_a_worn_sentry_stone'); # :sarithcity_a_worn_sentry_stone_lt:
INSERT INTO loottable(name) VALUES('sarithcity_fsp-general-noeffect'); # :sarithcity_fsp-general-noeffect_lt:
