UPDATE npc_types SET loottable_id = :sepulcher_agralta_lt: WHERE id in (733112); # #Agralta 99
UPDATE npc_types SET loottable_id = :sepulcher_alchemist_vaskerin_lt: WHERE id in (733075); # #Alchemist_Vaskerin 95
UPDATE npc_types SET loottable_id = :sepulcher_captured_dragon_hatchling_lt: WHERE id in (733057); # #captured_dragon_hatchling 97
UPDATE npc_types SET loottable_id = :sepulcher_infiltrator_tesara_lt: WHERE id in (733000); # #Infiltrator_Tesara 96
UPDATE npc_types SET loottable_id = :sepulcher_planner_ulnos_lt: WHERE id in (733049); # #Planner_Ulnos 95
UPDATE npc_types SET loottable_id = :sepulcher_planner_vanseth_lt: WHERE id in (733031); # #Planner_Vanseth 96
UPDATE npc_types SET loottable_id = :sepulcher_thado_penn_lt: WHERE id in (733161); # #Thado_Penn 96
UPDATE npc_types SET loottable_id = :sepulcher_thelasa_eselren_lt: WHERE id in (733070); # #Thelasa_Eselren 96
UPDATE npc_types SET loottable_id = :sepulcher_therin_the_ancient_lt: WHERE id in (733038); # #Therin_the_Ancient 95
UPDATE npc_types SET loottable_id = :sepulcher_alra_ser_alsa_lt: WHERE id in (733166); # Alra_ser_alsa 96
UPDATE npc_types SET loottable_id = :sepulcher_an_alra_ser_alsa_lt: WHERE id in (733064, 733118); # an_Alra_ser_alsa 97
UPDATE npc_types SET loottable_id = :sepulcher_an_alsa_construct_lt: WHERE id in (733159, 733160); # an_alsa_construct 95
UPDATE npc_types SET loottable_id = :sepulcher_an_alsa_thelara_initiate_lt: WHERE id in (733066, 733071, 733109, 733114, 733117, 733122, 733124, 733145); # an_alsa_thelara_initiate 94
UPDATE npc_types SET loottable_id = :sepulcher_an_alsa_thelara_worker_lt: WHERE id in (733040, 733050); # an_alsa_thelara_worker 96
UPDATE npc_types SET loottable_id = :sepulcher_an_alsa_thel_selyrah_lt: WHERE id in (733082, 733094); # an_alsa_thel_selyrah 96
UPDATE npc_types SET loottable_id = :sepulcher_an_animated_alsa_construct_lt: WHERE id in (733156); # an_animated_alsa_construct 95
UPDATE npc_types SET loottable_id = :sepulcher_an_arable_mound_lt: WHERE id in (733021, 733026); # an_arable_mound 95
UPDATE npc_types SET loottable_id = :sepulcher_an_arbiter_ereth_of_law_lt: WHERE id in (733194); # an_arbiter_ereth_of_law 97
UPDATE npc_types SET loottable_id = :sepulcher_an_arbiter_ereth_of_order_lt: WHERE id in (733007, 733010); # an_arbiter_ereth_of_order 98
UPDATE npc_types SET loottable_id = :sepulcher_an_archon_of_alsa_thelara_lt: WHERE id in (733072, 733074); # an_archon_of_alsa_thelara 96
UPDATE npc_types SET loottable_id = :sepulcher_an_armipotent_ser_alsa_thel_lt: WHERE id in (733113, 733119); # an_armipotent_ser_alsa_thel 97
UPDATE npc_types SET loottable_id = :sepulcher_an_armored_tideshell_lt: WHERE id in (733102); # an_armored_tideshell 94
UPDATE npc_types SET loottable_id = :sepulcher_an_ascended_ser_alsa_thel_lt: WHERE id in (733120, 733128); # an_ascended_ser_alsa_thel 98
UPDATE npc_types SET loottable_id = :sepulcher_an_dense_mound_lt: WHERE id in (733046); # an_dense_mound 94
UPDATE npc_types SET loottable_id = :sepulcher_an_engorged_ser_alsa_thel_lt: WHERE id in (733123, 733130); # an_engorged_ser_alsa_thel 98
UPDATE npc_types SET loottable_id = :sepulcher_an_enraptured_ser_alsa_thel_lt: WHERE id in (733107, 733165); # an_enraptured_ser_alsa_thel 96
UPDATE npc_types SET loottable_id = :sepulcher_an_ereth_of_alra_lt: WHERE id in (733058, 733062); # an_ereth_of_Alra 96
UPDATE npc_types SET loottable_id = :sepulcher_an_ereth_of_order_lt: WHERE id in (733003, 733014, 733085); # an_ereth_of_order 95
UPDATE npc_types SET loottable_id = :sepulcher_an_fertile_mound_lt: WHERE id in (733051); # an_fertile_mound 96
UPDATE npc_types SET loottable_id = :sepulcher_an_herbivorous_prowler_lt: WHERE id in (733013, 733035); # an_herbivorous_prowler 94
UPDATE npc_types SET loottable_id = :sepulcher_an_imbued_ser_alsa_thel_lt: WHERE id in (733098, 733110); # an_imbued_ser_alsa_thel 97
UPDATE npc_types SET loottable_id = :sepulcher_an_infant_eel_lt: WHERE id in (733020, 733022); # an_infant_eel 95
UPDATE npc_types SET loottable_id = :sepulcher_an_infused_alsa_construct_lt: WHERE id in (733137, 733153); # an_infused_alsa_construct 95
UPDATE npc_types SET loottable_id = :sepulcher_an_overgrown_mound_lt: WHERE id in (733018, 733053); # an_overgrown_mound 94
UPDATE npc_types SET loottable_id = :sepulcher_a_battered_sentry_stone_lt: WHERE id in (733126); # a_battered_sentry_stone 99
UPDATE npc_types SET loottable_id = :sepulcher_a_beacon_of_light_lt: WHERE id in (733164); # a_beacon_of_light 95
UPDATE npc_types SET loottable_id = :sepulcher_a_bead_of_light_lt: WHERE id in (733155, 733158); # a_bead_of_light 94
UPDATE npc_types SET loottable_id = :sepulcher_a_bladed_ereth_of_law_lt: WHERE id in (733192); # a_bladed_ereth_of_law 96
UPDATE npc_types SET loottable_id = :sepulcher_a_bladed_ereth_of_order_lt: WHERE id in (733004, 733015); # a_bladed_ereth_of_order 97
UPDATE npc_types SET loottable_id = :sepulcher_a_bladeguide_of_alsa_thelara_lt: WHERE id in (733079, 733096); # a_bladeguide_of_alsa_thelara 96
UPDATE npc_types SET loottable_id = :sepulcher_a_blade_master_of_alsa_thelara_lt: WHERE id in (733052); # a_blade_master_of_alsa_thelara 97
UPDATE npc_types SET loottable_id = :sepulcher_a_blade_mentor_of_alsa_thelara_lt: WHERE id in (733056); # a_blade_mentor_of_alsa_thelara 96
UPDATE npc_types SET loottable_id = :sepulcher_a_blade_overseer_of_alsa_thelara_lt: WHERE id in (733076, 733140); # a_blade_overseer_of_alsa_thelara 98
UPDATE npc_types SET loottable_id = :sepulcher_a_blind_scavenger_lt: WHERE id in (733027); # a_blind_scavenger 95
UPDATE npc_types SET loottable_id = :sepulcher_a_boastful_tricrystal_lt: WHERE id in (733174, 733177); # a_boastful_tricrystal 94
UPDATE npc_types SET loottable_id = :sepulcher_a_body_of_darkness_lt: WHERE id in (733127, 733141); # a_body_of_darkness 95
UPDATE npc_types SET loottable_id = :sepulcher_a_bone_amalgamation_lt: WHERE id in (733025, 733030); # a_bone_amalgamation 95
UPDATE npc_types SET loottable_id = :sepulcher_a_bone_mass_lt: WHERE id in (733034, 733054); # a_bone_mass 94
UPDATE npc_types SET loottable_id = :sepulcher_a_brooding_selyrah_lt: WHERE id in (733097); # a_brooding_selyrah 94
UPDATE npc_types SET loottable_id = :sepulcher_a_brutalizer_of_alsa_thelara_lt: WHERE id in (733008, 733055); # a_brutalizer_of_alsa_thelara 96
UPDATE npc_types SET loottable_id = :sepulcher_a_calcified_ser_thel_lt: WHERE id in (733065, 733068); # a_calcified_ser_thel 95
UPDATE npc_types SET loottable_id = :sepulcher_a_carnifex_of_alsa_thelara_lt: WHERE id in (733005, 733006); # a_carnifex_of_alsa_thelara 95
UPDATE npc_types SET loottable_id = :sepulcher_a_carrier_of_arcanum_lt: WHERE id in (733125, 733135); # a_carrier_of_arcanum 95
UPDATE npc_types SET loottable_id = :sepulcher_a_commanding_wind_lt: WHERE id in (733178); # a_commanding_wind 95
UPDATE npc_types SET loottable_id = :sepulcher_a_crystalline_healer_lt: WHERE id in (733190); # a_crystalline_healer 96
UPDATE npc_types SET loottable_id = :sepulcher_a_deceased_thelasa_lt: WHERE id in (733024, 733061); # a_deceased_thelasa 95
UPDATE npc_types SET loottable_id = :sepulcher_a_defender_of_alsa_thel_lt: WHERE id in (733132); # a_defender_of_alsa_thel 96
UPDATE npc_types SET loottable_id = :sepulcher_a_denuded_ser_thel_lt: WHERE id in (733037); # a_denuded_ser_thel 95
UPDATE npc_types SET loottable_id = :sepulcher_a_departed_thelasa_lt: WHERE id in (733175, 733180); # a_departed_thelasa 95
UPDATE npc_types SET loottable_id = :sepulcher_a_disfigured_thelasa_ser_lt: WHERE id in (733193); # a_disfigured_thelasa_ser 96
UPDATE npc_types SET loottable_id = :sepulcher_a_disgusting_soul_lt: WHERE id in (733039); # a_disgusting_soul 95
UPDATE npc_types SET loottable_id = :sepulcher_a_fleshless_ser_thel_lt: WHERE id in (733009, 733041); # a_fleshless_ser_thel 94
UPDATE npc_types SET loottable_id = :sepulcher_a_flow_of_alsa_thel_lt: WHERE id in (733017, 733029); # a_flow_of_alsa_thel 97
UPDATE npc_types SET loottable_id = :sepulcher_a_forgotten_spirit_lt: WHERE id in (733043); # a_forgotten_spirit 95
UPDATE npc_types SET loottable_id = :sepulcher_a_gale_liege_lt: WHERE id in (733187, 733171); # a_gale_liege 95
UPDATE npc_types SET loottable_id = :sepulcher_a_gale_servant_lt: WHERE id in (733185); # a_gale_servant 95
UPDATE npc_types SET loottable_id = :sepulcher_a_gleaming_stonewalker_lt: WHERE id in (733188); # a_gleaming_stonewalker 94
UPDATE npc_types SET loottable_id = :sepulcher_a_greensward_walker_lt: WHERE id in (733042); # a_greensward_walker 94
UPDATE npc_types SET loottable_id = :sepulcher_a_guardian_of_alsa_thel_lt: WHERE id in (733131, 733134); # a_guardian_of_alsa_thel 97
UPDATE npc_types SET loottable_id = :sepulcher_a_hardened_tideshell_lt: WHERE id in (733095); # a_hardened_tideshell 94
UPDATE npc_types SET loottable_id = :sepulcher_a_loamy_pile_lt: WHERE id in (733016, 733044); # a_loamy_pile 95
UPDATE npc_types SET loottable_id = :sepulcher_a_luminous_stonewalker_lt: WHERE id in (733184, 733170); # a_luminous_stonewalker 95
UPDATE npc_types SET loottable_id = :sepulcher_a_moss_jumble_lt: WHERE id in (733028, 733033); # a_moss_jumble 94
UPDATE npc_types SET loottable_id = :sepulcher_a_mutated_thel_imbiber_lt: WHERE id in (733104, 733105); # a_mutated_thel_imbiber 96
UPDATE npc_types SET loottable_id = :sepulcher_a_nesting_goral_lt: WHERE id in (733083, 733111); # a_nesting_goral 94
UPDATE npc_types SET loottable_id = :sepulcher_a_penitent_of_beloth_lt: WHERE id in (733001, 733121); # a_penitent_of_Beloth 95
UPDATE npc_types SET loottable_id = :sepulcher_a_petrified_ser_thel_lt: WHERE id in (733060); # a_petrified_ser_thel 96
UPDATE npc_types SET loottable_id = :sepulcher_a_plated_tideshell_lt: WHERE id in (733069, 733091); # a_plated_tideshell 96
UPDATE npc_types SET loottable_id = :sepulcher_a_pool_of_alsa_thel_lt: WHERE id in (733002, 733019); # a_pool_of_alsa_thel 96
UPDATE npc_types SET loottable_id = :sepulcher_a_proud_tricrystal_lt: WHERE id in (733173, 733182); # a_proud_tricrystal 95
UPDATE npc_types SET loottable_id = :sepulcher_a_purified_soul_lt: WHERE id in (733191, 733179); # a_purified_soul 94
UPDATE npc_types SET loottable_id = :sepulcher_a_ravenous_raptor_lt: WHERE id in (733089); # a_ravenous_raptor 96
UPDATE npc_types SET loottable_id = :sepulcher_a_resplendent_soul_lt: WHERE id in (733181); # a_resplendent_soul 95
UPDATE npc_types SET loottable_id = :sepulcher_a_revenant_of_thelasa_lt: WHERE id in (733032, 733045); # a_revenant_of_thelasa 98
UPDATE npc_types SET loottable_id = :sepulcher_a_savage_raptor_lt: WHERE id in (733108); # a_savage_raptor 94
UPDATE npc_types SET loottable_id = :sepulcher_a_sea_funnel_lt: WHERE id in (733088, 733093); # a_sea_funnel 95
UPDATE npc_types SET loottable_id = :sepulcher_a_sentry_stone_lt: WHERE id in (733115); # a_sentry_stone 99
UPDATE npc_types SET loottable_id = :sepulcher_a_shouting_element_lt: WHERE id in (733169); # a_shouting_element 94
UPDATE npc_types SET loottable_id = :sepulcher_a_shroud_of_thelasa_lt: WHERE id in (733023, 733036); # a_shroud_of_thelasa 97
UPDATE npc_types SET loottable_id = :sepulcher_a_soul_of_darkness_lt: WHERE id in (733148, 733152); # a_soul_of_darkness 95
UPDATE npc_types SET loottable_id = :sepulcher_a_soul_of_nature_lt: WHERE id in (733149, 733151); # a_soul_of_nature 95
UPDATE npc_types SET loottable_id = :sepulcher_a_spirit_of_nature_lt: WHERE id in (733150); # a_spirit_of_nature 95
UPDATE npc_types SET loottable_id = :sepulcher_a_starving_raptor_lt: WHERE id in (733101, 733106); # a_starving_raptor 96
UPDATE npc_types SET loottable_id = :sepulcher_a_steel_droplet_lt: WHERE id in (733144, 733146); # a_steel_droplet 94
UPDATE npc_types SET loottable_id = :sepulcher_a_steel_hurricane_lt: WHERE id in (733138); # a_steel_hurricane 95
UPDATE npc_types SET loottable_id = :sepulcher_a_steel_mass_lt: WHERE id in (733129); # a_steel_mass 96
UPDATE npc_types SET loottable_id = :sepulcher_a_steel_tornado_lt: WHERE id in (733142, 733154); # a_steel_tornado 95
UPDATE npc_types SET loottable_id = :sepulcher_a_sublime_tricrystal_lt: WHERE id in (733183); # a_sublime_tricrystal 96
UPDATE npc_types SET loottable_id = :sepulcher_a_swirling_voice_lt: WHERE id in (733186, 733176); # a_swirling_voice 95
UPDATE npc_types SET loottable_id = :sepulcher_a_tarnished_soul_lt: WHERE id in (733063); # a_tarnished_soul 95
UPDATE npc_types SET loottable_id = :sepulcher_a_territorial_goral_lt: WHERE id in (733092, 733103); # a_territorial_goral 95
UPDATE npc_types SET loottable_id = :sepulcher_a_thelara_alsa_ril_of_alra_lt: WHERE id in (733059, 733116); # a_thelara_alsa_ril_of_Alra 98
UPDATE npc_types SET loottable_id = :sepulcher_a_thel_eel_lt: WHERE id in (733080); # a_thel_eel 95
UPDATE npc_types SET loottable_id = :sepulcher_a_tide_creeper_lt: WHERE id in (733073, 733099); # a_tide_creeper 95
UPDATE npc_types SET loottable_id = :sepulcher_a_tide_drain_lt: WHERE id in (733084); # a_tide_drain 96
UPDATE npc_types SET loottable_id = :sepulcher_a_tide_drifter_lt: WHERE id in (733100); # a_tide_drifter 95
UPDATE npc_types SET loottable_id = :sepulcher_a_torturer_of_alsa_thelara_lt: WHERE id in (733011, 733077); # a_torturer_of_alsa_thelara 97
UPDATE npc_types SET loottable_id = :sepulcher_a_transcendent_adherent_lt: WHERE id in (733086, 733157); # a_transcendent_adherent 95
UPDATE npc_types SET loottable_id = :sepulcher_a_transfigured_thel_imbiber_lt: WHERE id in (733090, 733139); # a_transfigured_thel_imbiber 97
UPDATE npc_types SET loottable_id = :sepulcher_a_vessel_of_arcanum_lt: WHERE id in (733133, 733143); # a_vessel_of_arcanum 95
UPDATE npc_types SET loottable_id = :sepulcher_a_vicious_raptor_lt: WHERE id in (733081); # a_vicious_raptor 94
UPDATE npc_types SET loottable_id = :sepulcher_a_visage_of_darkness_lt: WHERE id in (733136, 733162); # a_visage_of_darkness 95
UPDATE npc_types SET loottable_id = :sepulcher_a_vociferous_element_lt: WHERE id in (733172); # a_vociferous_element 96
UPDATE npc_types SET loottable_id = :sepulcher_a_whirlwind_of_steel_lt: WHERE id in (733147); # a_whirlwind_of_steel 95
UPDATE npc_types SET loottable_id = :sepulcher_a_wind_egg_lt: WHERE id in (733168); # a_wind_egg 1
UPDATE npc_types SET loottable_id = :sepulcher_a_wind_liege_lt: WHERE id in (733195); # a_wind_liege 96
UPDATE npc_types SET loottable_id = :sepulcher_a_wind_servant_lt: WHERE id in (733189, 733167); # a_wind_servant 94
UPDATE npc_types SET loottable_id = :sepulcher_a_wizened_thelasa_lt: WHERE id in (733047, 733067); # a_wizened_thelasa 95
UPDATE npc_types SET loottable_id = :sepulcher_a_worn_sentry_stone_lt: WHERE id in (733012); # a_worn_sentry_stone 99
UPDATE npc_types SET loottable_id = :sepulcher_a_zephyr_of_steel_lt: WHERE id in (733163); # a_zephyr_of_steel 94
UPDATE npc_types SET loottable_id = :sepulcher_fsp-general-noeffect_lt: WHERE id in (733087); # FSP-General-NoEffect 1
UPDATE npc_types SET loottable_id = :sepulcher_thel_ereth_ril_lt: WHERE id in (733048); # thel_ereth_ril 99
UPDATE npc_types SET loottable_id = :sepulcher_torturer_of_alsa_thelara_lt: WHERE id in (733078); # torturer_of_alsa_thelara 98
