INSERT INTO loottable(name) VALUES('sepulcher_agralta'); # :sepulcher_agralta_lt:
INSERT INTO loottable(name) VALUES('sepulcher_alchemist_vaskerin'); # :sepulcher_alchemist_vaskerin_lt:
INSERT INTO loottable(name) VALUES('sepulcher_captured_dragon_hatchling'); # :sepulcher_captured_dragon_hatchling_lt:
INSERT INTO loottable(name) VALUES('sepulcher_infiltrator_tesara'); # :sepulcher_infiltrator_tesara_lt:
INSERT INTO loottable(name) VALUES('sepulcher_planner_ulnos'); # :sepulcher_planner_ulnos_lt:
INSERT INTO loottable(name) VALUES('sepulcher_planner_vanseth'); # :sepulcher_planner_vanseth_lt:
INSERT INTO loottable(name) VALUES('sepulcher_thado_penn'); # :sepulcher_thado_penn_lt:
INSERT INTO loottable(name) VALUES('sepulcher_thelasa_eselren'); # :sepulcher_thelasa_eselren_lt:
INSERT INTO loottable(name) VALUES('sepulcher_therin_the_ancient'); # :sepulcher_therin_the_ancient_lt:
INSERT INTO loottable(name) VALUES('sepulcher_alra_ser_alsa'); # :sepulcher_alra_ser_alsa_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_alra_ser_alsa'); # :sepulcher_an_alra_ser_alsa_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_alsa_construct'); # :sepulcher_an_alsa_construct_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_alsa_thelara_initiate'); # :sepulcher_an_alsa_thelara_initiate_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_alsa_thelara_worker'); # :sepulcher_an_alsa_thelara_worker_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_alsa_thel_selyrah'); # :sepulcher_an_alsa_thel_selyrah_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_animated_alsa_construct'); # :sepulcher_an_animated_alsa_construct_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_arable_mound'); # :sepulcher_an_arable_mound_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_arbiter_ereth_of_law'); # :sepulcher_an_arbiter_ereth_of_law_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_arbiter_ereth_of_order'); # :sepulcher_an_arbiter_ereth_of_order_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_archon_of_alsa_thelara'); # :sepulcher_an_archon_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_armipotent_ser_alsa_thel'); # :sepulcher_an_armipotent_ser_alsa_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_armored_tideshell'); # :sepulcher_an_armored_tideshell_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_ascended_ser_alsa_thel'); # :sepulcher_an_ascended_ser_alsa_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_dense_mound'); # :sepulcher_an_dense_mound_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_engorged_ser_alsa_thel'); # :sepulcher_an_engorged_ser_alsa_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_enraptured_ser_alsa_thel'); # :sepulcher_an_enraptured_ser_alsa_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_ereth_of_alra'); # :sepulcher_an_ereth_of_alra_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_ereth_of_order'); # :sepulcher_an_ereth_of_order_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_fertile_mound'); # :sepulcher_an_fertile_mound_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_herbivorous_prowler'); # :sepulcher_an_herbivorous_prowler_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_imbued_ser_alsa_thel'); # :sepulcher_an_imbued_ser_alsa_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_infant_eel'); # :sepulcher_an_infant_eel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_infused_alsa_construct'); # :sepulcher_an_infused_alsa_construct_lt:
INSERT INTO loottable(name) VALUES('sepulcher_an_overgrown_mound'); # :sepulcher_an_overgrown_mound_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_battered_sentry_stone'); # :sepulcher_a_battered_sentry_stone_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_beacon_of_light'); # :sepulcher_a_beacon_of_light_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_bead_of_light'); # :sepulcher_a_bead_of_light_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_bladed_ereth_of_law'); # :sepulcher_a_bladed_ereth_of_law_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_bladed_ereth_of_order'); # :sepulcher_a_bladed_ereth_of_order_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_bladeguide_of_alsa_thelara'); # :sepulcher_a_bladeguide_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_blade_master_of_alsa_thelara'); # :sepulcher_a_blade_master_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_blade_mentor_of_alsa_thelara'); # :sepulcher_a_blade_mentor_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_blade_overseer_of_alsa_thelara'); # :sepulcher_a_blade_overseer_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_blind_scavenger'); # :sepulcher_a_blind_scavenger_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_boastful_tricrystal'); # :sepulcher_a_boastful_tricrystal_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_body_of_darkness'); # :sepulcher_a_body_of_darkness_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_bone_amalgamation'); # :sepulcher_a_bone_amalgamation_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_bone_mass'); # :sepulcher_a_bone_mass_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_brooding_selyrah'); # :sepulcher_a_brooding_selyrah_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_brutalizer_of_alsa_thelara'); # :sepulcher_a_brutalizer_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_calcified_ser_thel'); # :sepulcher_a_calcified_ser_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_carnifex_of_alsa_thelara'); # :sepulcher_a_carnifex_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_carrier_of_arcanum'); # :sepulcher_a_carrier_of_arcanum_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_commanding_wind'); # :sepulcher_a_commanding_wind_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_crystalline_healer'); # :sepulcher_a_crystalline_healer_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_deceased_thelasa'); # :sepulcher_a_deceased_thelasa_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_defender_of_alsa_thel'); # :sepulcher_a_defender_of_alsa_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_denuded_ser_thel'); # :sepulcher_a_denuded_ser_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_departed_thelasa'); # :sepulcher_a_departed_thelasa_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_disfigured_thelasa_ser'); # :sepulcher_a_disfigured_thelasa_ser_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_disgusting_soul'); # :sepulcher_a_disgusting_soul_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_fleshless_ser_thel'); # :sepulcher_a_fleshless_ser_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_flow_of_alsa_thel'); # :sepulcher_a_flow_of_alsa_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_forgotten_spirit'); # :sepulcher_a_forgotten_spirit_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_gale_liege'); # :sepulcher_a_gale_liege_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_gale_servant'); # :sepulcher_a_gale_servant_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_gleaming_stonewalker'); # :sepulcher_a_gleaming_stonewalker_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_greensward_walker'); # :sepulcher_a_greensward_walker_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_guardian_of_alsa_thel'); # :sepulcher_a_guardian_of_alsa_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_hardened_tideshell'); # :sepulcher_a_hardened_tideshell_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_loamy_pile'); # :sepulcher_a_loamy_pile_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_luminous_stonewalker'); # :sepulcher_a_luminous_stonewalker_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_moss_jumble'); # :sepulcher_a_moss_jumble_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_mutated_thel_imbiber'); # :sepulcher_a_mutated_thel_imbiber_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_nesting_goral'); # :sepulcher_a_nesting_goral_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_penitent_of_beloth'); # :sepulcher_a_penitent_of_beloth_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_petrified_ser_thel'); # :sepulcher_a_petrified_ser_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_plated_tideshell'); # :sepulcher_a_plated_tideshell_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_pool_of_alsa_thel'); # :sepulcher_a_pool_of_alsa_thel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_proud_tricrystal'); # :sepulcher_a_proud_tricrystal_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_purified_soul'); # :sepulcher_a_purified_soul_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_ravenous_raptor'); # :sepulcher_a_ravenous_raptor_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_resplendent_soul'); # :sepulcher_a_resplendent_soul_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_revenant_of_thelasa'); # :sepulcher_a_revenant_of_thelasa_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_savage_raptor'); # :sepulcher_a_savage_raptor_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_sea_funnel'); # :sepulcher_a_sea_funnel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_sentry_stone'); # :sepulcher_a_sentry_stone_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_shouting_element'); # :sepulcher_a_shouting_element_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_shroud_of_thelasa'); # :sepulcher_a_shroud_of_thelasa_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_soul_of_darkness'); # :sepulcher_a_soul_of_darkness_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_soul_of_nature'); # :sepulcher_a_soul_of_nature_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_spirit_of_nature'); # :sepulcher_a_spirit_of_nature_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_starving_raptor'); # :sepulcher_a_starving_raptor_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_steel_droplet'); # :sepulcher_a_steel_droplet_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_steel_hurricane'); # :sepulcher_a_steel_hurricane_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_steel_mass'); # :sepulcher_a_steel_mass_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_steel_tornado'); # :sepulcher_a_steel_tornado_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_sublime_tricrystal'); # :sepulcher_a_sublime_tricrystal_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_swirling_voice'); # :sepulcher_a_swirling_voice_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_tarnished_soul'); # :sepulcher_a_tarnished_soul_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_territorial_goral'); # :sepulcher_a_territorial_goral_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_thelara_alsa_ril_of_alra'); # :sepulcher_a_thelara_alsa_ril_of_alra_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_thel_eel'); # :sepulcher_a_thel_eel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_tide_creeper'); # :sepulcher_a_tide_creeper_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_tide_drain'); # :sepulcher_a_tide_drain_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_tide_drifter'); # :sepulcher_a_tide_drifter_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_torturer_of_alsa_thelara'); # :sepulcher_a_torturer_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_transcendent_adherent'); # :sepulcher_a_transcendent_adherent_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_transfigured_thel_imbiber'); # :sepulcher_a_transfigured_thel_imbiber_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_vessel_of_arcanum'); # :sepulcher_a_vessel_of_arcanum_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_vicious_raptor'); # :sepulcher_a_vicious_raptor_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_visage_of_darkness'); # :sepulcher_a_visage_of_darkness_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_vociferous_element'); # :sepulcher_a_vociferous_element_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_whirlwind_of_steel'); # :sepulcher_a_whirlwind_of_steel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_wind_egg'); # :sepulcher_a_wind_egg_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_wind_liege'); # :sepulcher_a_wind_liege_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_wind_servant'); # :sepulcher_a_wind_servant_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_wizened_thelasa'); # :sepulcher_a_wizened_thelasa_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_worn_sentry_stone'); # :sepulcher_a_worn_sentry_stone_lt:
INSERT INTO loottable(name) VALUES('sepulcher_a_zephyr_of_steel'); # :sepulcher_a_zephyr_of_steel_lt:
INSERT INTO loottable(name) VALUES('sepulcher_fsp-general-noeffect'); # :sepulcher_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('sepulcher_thel_ereth_ril'); # :sepulcher_thel_ereth_ril_lt:
INSERT INTO loottable(name) VALUES('sepulcher_torturer_of_alsa_thelara'); # :sepulcher_torturer_of_alsa_thelara_lt:
