UPDATE npc_types SET loottable_id = :westsepulcher_dunia_lt: WHERE id in (735036); # #Dunia 10
UPDATE npc_types SET loottable_id = :westsepulcher_jordi_lt: WHERE id in (735073); # #Jordi 10
UPDATE npc_types SET loottable_id = :westsepulcher_sentry_stone_of_illdaera_lt: WHERE id in (735043); # #Sentry_Stone_of_Illdaera 99
UPDATE npc_types SET loottable_id = :westsepulcher_sentry_stone_of_ladrys_lt: WHERE id in (735102); # #Sentry_Stone_of_Ladrys 99
UPDATE npc_types SET loottable_id = :westsepulcher_sentry_stone_of_oseka_lt: WHERE id in (735035); # #Sentry_Stone_of_Oseka 99
UPDATE npc_types SET loottable_id = :westsepulcher_sentry_stone_of_sholoth_lt: WHERE id in (735002); # #Sentry_Stone_of_Sholoth 99
UPDATE npc_types SET loottable_id = :westsepulcher_the_digger_lt: WHERE id in (735009); # #The_Digger 99
UPDATE npc_types SET loottable_id = :westsepulcher_the_relic_of_illdaera_lt: WHERE id in (735096); # #The_Relic_of_Illdaera 98
UPDATE npc_types SET loottable_id = :westsepulcher_the_relic_of_ladrys_lt: WHERE id in (735110); # #The_Relic_of_Ladrys 98
UPDATE npc_types SET loottable_id = :westsepulcher_the_relic_of_oseka_lt: WHERE id in (735099); # #The_Relic_of_Oseka 98
UPDATE npc_types SET loottable_id = :westsepulcher_the_relic_of_sholoth_lt: WHERE id in (735032); # #The_Relic_of_Sholoth 98
UPDATE npc_types SET loottable_id = :westsepulcher_an_adherent_of_ladrys_lt: WHERE id in (735114); # an_adherent_of_Ladrys 98
UPDATE npc_types SET loottable_id = :westsepulcher_an_alsa_thelara_champion_lt: WHERE id in (735074, 735089); # an_alsa_thelara_champion 96
UPDATE npc_types SET loottable_id = :westsepulcher_an_alsa_thelara_conquerer_lt: WHERE id in (735092); # an_alsa_thelara_conquerer 97
UPDATE npc_types SET loottable_id = :westsepulcher_an_alsa_thelara_legend_lt: WHERE id in (735090); # an_alsa_thelara_legend 97
UPDATE npc_types SET loottable_id = :westsepulcher_an_alsa_thelara_nonpareil_lt: WHERE id in (735082); # an_alsa_thelara_nonpareil 97
UPDATE npc_types SET loottable_id = :westsepulcher_an_alsa_thelara_wind_archer_lt: WHERE id in (735077, 735078); # an_alsa_thelara_wind_archer 96
UPDATE npc_types SET loottable_id = :westsepulcher_an_archon_of_alsa_thelara_lt: WHERE id in (735003, 735039); # an_archon_of_alsa_thelara 95
UPDATE npc_types SET loottable_id = :westsepulcher_an_armored_tideshell_lt: WHERE id in (735058, 735068); # an_armored_tideshell 94
UPDATE npc_types SET loottable_id = :westsepulcher_an_devotee_of_ladrys_lt: WHERE id in (735116); # an_devotee_of_Ladrys 98
UPDATE npc_types SET loottable_id = :westsepulcher_an_infant_eel_lt: WHERE id in (735071, 735108); # an_infant_eel 94
UPDATE npc_types SET loottable_id = :westsepulcher_an_initiate_of_ladrys_lt: WHERE id in (735117, 735119); # an_initiate_of_Ladrys 97
UPDATE npc_types SET loottable_id = :westsepulcher_an_unblemished_shard_lt: WHERE id in (735120); # an_unblemished_shard 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_beast_of_steel_lt: WHERE id in (735083, 735093); # a_beast_of_steel 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_bladeguide_of_alsa_thelara_lt: WHERE id in (735004, 735047); # a_bladeguide_of_alsa_thelara 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_blade_overseer_of_alsa_thelara_lt: WHERE id in (735045); # a_blade_overseer_of_alsa_thelara 98
UPDATE npc_types SET loottable_id = :westsepulcher_a_bone_assembly_lt: WHERE id in (735012, 735026); # a_bone_assembly 95
UPDATE npc_types SET loottable_id = :westsepulcher_a_bone_bruiser_lt: WHERE id in (735020, 735029); # a_bone_bruiser 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_cave_great_white_lt: WHERE id in (735056); # a_cave_great_white 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_cave_hammerhead_lt: WHERE id in (735042, 735046); # a_cave_hammerhead 95
UPDATE npc_types SET loottable_id = :westsepulcher_a_cleansed_soul_lt: WHERE id in (735113, 735115); # a_cleansed_soul 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_consumer_of_death_lt: WHERE id in (735008); # a_consumer_of_death 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_filth_eater_lt: WHERE id in (735011, 735013); # a_filth_eater 95
UPDATE npc_types SET loottable_id = :westsepulcher_a_forgotten_spirit_lt: WHERE id in (735000, 735001, 735022, 735025, 735034, 735040, 735054, 735061, 735084, 735088, 735103, 735104, 735107, 735109); # a_forgotten_spirit 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_fouled_warrior_lt: WHERE id in (735015, 735128); # a_fouled_warrior 98
UPDATE npc_types SET loottable_id = :westsepulcher_a_giant_of_steel_lt: WHERE id in (735081); # a_giant_of_steel 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_high_thelasa_of_ladrys_lt: WHERE id in (735123); # a_high_thelasa_of_Ladrys 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_high_thelasa_of_oseka_lt: WHERE id in (735075, 735087); # a_high_thelasa_of_Oseka 98
UPDATE npc_types SET loottable_id = :westsepulcher_a_myrmidon_of_oseka_lt: WHERE id in (735101, 735106); # a_myrmidon_of_Oseka 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_noviate_of_ladrys_lt: WHERE id in (735124); # a_noviate_of_Ladrys 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_plated_tideshell_lt: WHERE id in (735063, 735066); # a_plated_tideshell 95
UPDATE npc_types SET loottable_id = :westsepulcher_a_purged_soul_lt: WHERE id in (735118, 735121); # a_purged_soul 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_relic_lt: WHERE id in (735031); # a_relic 88
UPDATE npc_types SET loottable_id = :westsepulcher_a_risen_ser_alsa_lt: WHERE id in (735018); # a_risen_ser_alsa 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_servitor_of_the_depths_lt: WHERE id in (735010, 735016); # a_servitor_of_the_depths 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_ser_alsa_deceased_lt: WHERE id in (735017, 735028); # a_ser_alsa_deceased 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_ser_alsa_hadal_lt: WHERE id in (735048, 735055); # a_ser_alsa_hadal 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_ser_alsa_thel_hadal_lt: WHERE id in (735050, 735072); # a_ser_alsa_thel_hadal 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_shard_of_illdaera_lt: WHERE id in (735091); # a_shard_of_Illdaera 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_shard_of_purity_lt: WHERE id in (735112); # a_shard_of_purity 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_sightless_turtle_lt: WHERE id in (735044, 735065); # a_sightless_turtle 95
UPDATE npc_types SET loottable_id = :westsepulcher_a_soiled_warrior_lt: WHERE id in (735014, 735019); # a_soiled_warrior 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_splash_of_illdaera_lt: WHERE id in (735076, 735086); # a_splash_of_Illdaera 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_steel_breeze_lt: WHERE id in (735079); # a_steel_breeze 95
UPDATE npc_types SET loottable_id = :westsepulcher_a_steel_torrent_lt: WHERE id in (735094); # a_steel_torrent 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_subterranean_kraken_lt: WHERE id in (735041, 735051); # a_subterranean_kraken 95
UPDATE npc_types SET loottable_id = :westsepulcher_a_subterrestrial_kraken_lt: WHERE id in (735049); # a_subterrestrial_kraken 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_sunken_turtle_lt: WHERE id in (735053); # a_sunken_turtle 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelara_of_oseka_lt: WHERE id in (735070, 735097); # a_thelara_of_Oseka 98
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelasa_ereth_of_illdaera_lt: WHERE id in (735037); # a_thelasa_ereth_of_Illdaera 95
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelasa_ereth_of_lunanyn_lt: WHERE id in (735006); # a_thelasa_ereth_of_Lunanyn 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelasa_of_battle_lt: WHERE id in (735095); # a_thelasa_of_battle 99
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelasa_of_decay_lt: WHERE id in (735030); # a_thelasa_of_decay 99
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelasa_of_ladrys_lt: WHERE id in (735122, 735127); # a_thelasa_of_Ladrys 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelasa_of_oseka_lt: WHERE id in (735085, 735100); # a_thelasa_of_Oseka 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelasa_of_splendor_lt: WHERE id in (735111); # a_thelasa_of_splendor 99
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelasa_of_the_deep_lt: WHERE id in (735027); # a_thelasa_of_the_deep 98
UPDATE npc_types SET loottable_id = :westsepulcher_a_thelasa_of_tides_lt: WHERE id in (735098); # a_thelasa_of_tides 99
UPDATE npc_types SET loottable_id = :westsepulcher_a_tide_creeper_lt: WHERE id in (735060, 735064); # a_tide_creeper 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_tide_drifter_lt: WHERE id in (735059, 735062); # a_tide_drifter 95
UPDATE npc_types SET loottable_id = :westsepulcher_a_tide_pool_lt: WHERE id in (735069); # A_tide_pool 90
UPDATE npc_types SET loottable_id = :westsepulcher_a_warrior_of_oseka_lt: WHERE id in (735057, 735080); # a_warrior_of_Oseka 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_wizened_thelasa_lt: WHERE id in (735005, 735021); # a_wizened_thelasa 96
UPDATE npc_types SET loottable_id = :westsepulcher_a_worshipper_of_decay_lt: WHERE id in (735023); # a_worshipper_of_decay 97
UPDATE npc_types SET loottable_id = :westsepulcher_a_worshipper_of_filth_lt: WHERE id in (735024, 735033); # a_worshipper_of_filth 96
UPDATE npc_types SET loottable_id = :westsepulcher_control_thel_ereth_ril_lt: WHERE id in (735105); # control_thel_ereth_ril 88
UPDATE npc_types SET loottable_id = :westsepulcher_fsp-general-noeffect_lt: WHERE id in (735007); # FSP-General-NoEffect 1
UPDATE npc_types SET loottable_id = :westsepulcher_ser_alsa_thel_hadal_lt: WHERE id in (735052, 735067); # ser_alsa_thel_hadal 98
UPDATE npc_types SET loottable_id = :westsepulcher_thelasa_of_ladrys_lt: WHERE id in (735125, 735126); # thelasa_of_Ladrys 96
UPDATE npc_types SET loottable_id = :westsepulcher_thel_ereth_ril_lt: WHERE id in (735038); # thel_ereth_ril 99
