INSERT INTO loottable(name) VALUES('westsepulcher_dunia'); # :westsepulcher_dunia_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_jordi'); # :westsepulcher_jordi_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_sentry_stone_of_illdaera'); # :westsepulcher_sentry_stone_of_illdaera_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_sentry_stone_of_ladrys'); # :westsepulcher_sentry_stone_of_ladrys_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_sentry_stone_of_oseka'); # :westsepulcher_sentry_stone_of_oseka_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_sentry_stone_of_sholoth'); # :westsepulcher_sentry_stone_of_sholoth_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_the_digger'); # :westsepulcher_the_digger_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_the_relic_of_illdaera'); # :westsepulcher_the_relic_of_illdaera_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_the_relic_of_ladrys'); # :westsepulcher_the_relic_of_ladrys_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_the_relic_of_oseka'); # :westsepulcher_the_relic_of_oseka_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_the_relic_of_sholoth'); # :westsepulcher_the_relic_of_sholoth_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_adherent_of_ladrys'); # :westsepulcher_an_adherent_of_ladrys_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_alsa_thelara_champion'); # :westsepulcher_an_alsa_thelara_champion_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_alsa_thelara_conquerer'); # :westsepulcher_an_alsa_thelara_conquerer_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_alsa_thelara_legend'); # :westsepulcher_an_alsa_thelara_legend_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_alsa_thelara_nonpareil'); # :westsepulcher_an_alsa_thelara_nonpareil_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_alsa_thelara_wind_archer'); # :westsepulcher_an_alsa_thelara_wind_archer_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_archon_of_alsa_thelara'); # :westsepulcher_an_archon_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_armored_tideshell'); # :westsepulcher_an_armored_tideshell_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_devotee_of_ladrys'); # :westsepulcher_an_devotee_of_ladrys_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_infant_eel'); # :westsepulcher_an_infant_eel_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_initiate_of_ladrys'); # :westsepulcher_an_initiate_of_ladrys_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_an_unblemished_shard'); # :westsepulcher_an_unblemished_shard_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_beast_of_steel'); # :westsepulcher_a_beast_of_steel_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_bladeguide_of_alsa_thelara'); # :westsepulcher_a_bladeguide_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_blade_overseer_of_alsa_thelara'); # :westsepulcher_a_blade_overseer_of_alsa_thelara_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_bone_assembly'); # :westsepulcher_a_bone_assembly_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_bone_bruiser'); # :westsepulcher_a_bone_bruiser_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_cave_great_white'); # :westsepulcher_a_cave_great_white_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_cave_hammerhead'); # :westsepulcher_a_cave_hammerhead_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_cleansed_soul'); # :westsepulcher_a_cleansed_soul_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_consumer_of_death'); # :westsepulcher_a_consumer_of_death_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_filth_eater'); # :westsepulcher_a_filth_eater_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_forgotten_spirit'); # :westsepulcher_a_forgotten_spirit_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_fouled_warrior'); # :westsepulcher_a_fouled_warrior_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_giant_of_steel'); # :westsepulcher_a_giant_of_steel_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_high_thelasa_of_ladrys'); # :westsepulcher_a_high_thelasa_of_ladrys_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_high_thelasa_of_oseka'); # :westsepulcher_a_high_thelasa_of_oseka_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_myrmidon_of_oseka'); # :westsepulcher_a_myrmidon_of_oseka_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_noviate_of_ladrys'); # :westsepulcher_a_noviate_of_ladrys_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_plated_tideshell'); # :westsepulcher_a_plated_tideshell_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_purged_soul'); # :westsepulcher_a_purged_soul_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_relic'); # :westsepulcher_a_relic_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_risen_ser_alsa'); # :westsepulcher_a_risen_ser_alsa_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_servitor_of_the_depths'); # :westsepulcher_a_servitor_of_the_depths_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_ser_alsa_deceased'); # :westsepulcher_a_ser_alsa_deceased_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_ser_alsa_hadal'); # :westsepulcher_a_ser_alsa_hadal_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_ser_alsa_thel_hadal'); # :westsepulcher_a_ser_alsa_thel_hadal_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_shard_of_illdaera'); # :westsepulcher_a_shard_of_illdaera_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_shard_of_purity'); # :westsepulcher_a_shard_of_purity_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_sightless_turtle'); # :westsepulcher_a_sightless_turtle_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_soiled_warrior'); # :westsepulcher_a_soiled_warrior_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_splash_of_illdaera'); # :westsepulcher_a_splash_of_illdaera_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_steel_breeze'); # :westsepulcher_a_steel_breeze_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_steel_torrent'); # :westsepulcher_a_steel_torrent_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_subterranean_kraken'); # :westsepulcher_a_subterranean_kraken_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_subterrestrial_kraken'); # :westsepulcher_a_subterrestrial_kraken_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_sunken_turtle'); # :westsepulcher_a_sunken_turtle_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelara_of_oseka'); # :westsepulcher_a_thelara_of_oseka_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelasa_ereth_of_illdaera'); # :westsepulcher_a_thelasa_ereth_of_illdaera_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelasa_ereth_of_lunanyn'); # :westsepulcher_a_thelasa_ereth_of_lunanyn_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelasa_of_battle'); # :westsepulcher_a_thelasa_of_battle_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelasa_of_decay'); # :westsepulcher_a_thelasa_of_decay_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelasa_of_ladrys'); # :westsepulcher_a_thelasa_of_ladrys_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelasa_of_oseka'); # :westsepulcher_a_thelasa_of_oseka_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelasa_of_splendor'); # :westsepulcher_a_thelasa_of_splendor_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelasa_of_the_deep'); # :westsepulcher_a_thelasa_of_the_deep_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_thelasa_of_tides'); # :westsepulcher_a_thelasa_of_tides_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_tide_creeper'); # :westsepulcher_a_tide_creeper_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_tide_drifter'); # :westsepulcher_a_tide_drifter_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_tide_pool'); # :westsepulcher_a_tide_pool_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_warrior_of_oseka'); # :westsepulcher_a_warrior_of_oseka_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_wizened_thelasa'); # :westsepulcher_a_wizened_thelasa_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_worshipper_of_decay'); # :westsepulcher_a_worshipper_of_decay_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_a_worshipper_of_filth'); # :westsepulcher_a_worshipper_of_filth_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_control_thel_ereth_ril'); # :westsepulcher_control_thel_ereth_ril_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_fsp-general-noeffect'); # :westsepulcher_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_ser_alsa_thel_hadal'); # :westsepulcher_ser_alsa_thel_hadal_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_thelasa_of_ladrys'); # :westsepulcher_thelasa_of_ladrys_lt:
INSERT INTO loottable(name) VALUES('westsepulcher_thel_ereth_ril'); # :westsepulcher_thel_ereth_ril_lt:
