UPDATE npc_types SET loottable_id = :codecay_akkapain_adan_lt: WHERE id in (200051); # #Akkapain_Adan 68
UPDATE npc_types SET loottable_id = :codecay_bertoxxulous_lt: WHERE id in (200055); # #Bertoxxulous 75
UPDATE npc_types SET loottable_id = :codecay_bhaly_adan_lt: WHERE id in (200054); # #Bhaly_Adan 68
UPDATE npc_types SET loottable_id = :codecay_cod_trigger_lt: WHERE id in (200041); # #COD_Trigger 80
UPDATE npc_types SET loottable_id = :codecay_darwol_adan_lt: WHERE id in (200046); # #Darwol_Adan 68
UPDATE npc_types SET loottable_id = :codecay_feig_adan_lt: WHERE id in (200045); # #Feig_Adan 68
UPDATE npc_types SET loottable_id = :codecay_kavilis_adan_lt: WHERE id in (200047); # #Kavilis_Adan 68
UPDATE npc_types SET loottable_id = :codecay_mage_trap_lt: WHERE id in (200061); # #mage_trap 1
UPDATE npc_types SET loottable_id = :codecay_meedo_adan_lt: WHERE id in (200053); # #Meedo_Adan 68
UPDATE npc_types SET loottable_id = :codecay_overlord_banord_paffa_lt: WHERE id in (200000); # #Overlord_Banord_Paffa 70
UPDATE npc_types SET loottable_id = :codecay_pzo_adan_lt: WHERE id in (200022); # #Pzo_Adan 70
UPDATE npc_types SET loottable_id = :codecay_qezzin_adan_lt: WHERE id in (200052); # #Qezzin_Adan 68
UPDATE npc_types SET loottable_id = :codecay_raddi_adan_lt: WHERE id in (200049); # #Raddi_Adan 68
UPDATE npc_types SET loottable_id = :codecay_spectre_of_corruption_lt: WHERE id in (200016); # #Spectre_of_Corruption 70
UPDATE npc_types SET loottable_id = :codecay_spirit_elemental_lt: WHERE id in (200060); # #Spirit_Elemental 70
UPDATE npc_types SET loottable_id = :codecay_wavadozzik_adan_lt: WHERE id in (200048); # #Wavadozzik_Adan 68
UPDATE npc_types SET loottable_id = :codecay_xhut_adan_lt: WHERE id in (200044); # #Xhut_Adan 68
UPDATE npc_types SET loottable_id = :codecay_zandal_adan_lt: WHERE id in (200050); # #Zandal_Adan 68
UPDATE npc_types SET loottable_id = :codecay__carprin_deatharn_lt: WHERE id in (200007); # #_Carprin_Deatharn 70
UPDATE npc_types SET loottable_id = :codecay_abroan_drian_lt: WHERE id in (200038); # Abroan_Drian 70
UPDATE npc_types SET loottable_id = :codecay_an_old_fly_nest_lt: WHERE id in (200077); # an_old_fly_nest 1
UPDATE npc_types SET loottable_id = :codecay_an_overwhelming_lt: WHERE id in (200080); # An_overwhelming 1
UPDATE npc_types SET loottable_id = :codecay_assassin_kakoo_lt: WHERE id in (200072); # Assassin_Kakoo 65
UPDATE npc_types SET loottable_id = :codecay_avhi_escron_lt: WHERE id in (200035); # Avhi_Escron 70
UPDATE npc_types SET loottable_id = :codecay_a_corpse_scavenger_lt: WHERE id in (200005); # a_corpse_scavenger 46
UPDATE npc_types SET loottable_id = :codecay_a_fly_swarm_lt: WHERE id in (200078); # a_fly_swarm 1
UPDATE npc_types SET loottable_id = :codecay_a_maddening_howl_lt: WHERE id in (200081); # A_maddening_howl 1
UPDATE npc_types SET loottable_id = :codecay_a_musty_smell_lt: WHERE id in (200082); # A_musty_smell 1
UPDATE npc_types SET loottable_id = :codecay_a_scrounging_rat_lt: WHERE id in (200009); # a_scrounging_rat 46
UPDATE npc_types SET loottable_id = :codecay_a_sense_of_fear_lt: WHERE id in (200083); # A_sense_of_fear 1
UPDATE npc_types SET loottable_id = :codecay_a_swarming_fly_lt: WHERE id in (200079); # a_swarming_fly 58
UPDATE npc_types SET loottable_id = :codecay_barban_cryptwalker_lt: WHERE id in (200057); # Barban_Cryptwalker 65
UPDATE npc_types SET loottable_id = :codecay_bishop_toluwon_lt: WHERE id in (200039); # Bishop_Toluwon 70
UPDATE npc_types SET loottable_id = :codecay_breddan_rutyl_lt: WHERE id in (200037); # Breddan_Rutyl 70
UPDATE npc_types SET loottable_id = :codecay_bubonian_death_caster_lt: WHERE id in (200028); # Bubonian_Death_Caster 62
UPDATE npc_types SET loottable_id = :codecay_bubonian_great_mystic_lt: WHERE id in (200029); # Bubonian_Great_Mystic 62
UPDATE npc_types SET loottable_id = :codecay_bubonian_mystic_lt: WHERE id in (200002); # Bubonian_Mystic 60
UPDATE npc_types SET loottable_id = :codecay_bubonian_warlord_lt: WHERE id in (200026); # Bubonian_Warlord 62
UPDATE npc_types SET loottable_id = :codecay_bubonian_war_rat_lt: WHERE id in (200001); # Bubonian_War_Rat 60
UPDATE npc_types SET loottable_id = :codecay_chanting_echoes_lt: WHERE id in (200085); # Chanting_echoes 1
UPDATE npc_types SET loottable_id = :codecay_corrupted_knight_lt: WHERE id in (200010); # Corrupted_Knight 60
UPDATE npc_types SET loottable_id = :codecay_corrupted_pusling_lt: WHERE id in (200003); # Corrupted_Pusling 60
UPDATE npc_types SET loottable_id = :codecay_crazed_bubonian_berzerker_lt: WHERE id in (200006); # Crazed_Bubonian_Berzerker 62
UPDATE npc_types SET loottable_id = :codecay_deathbone_archmagus_lt: WHERE id in (200069); # Deathbone_Archmagus 61
UPDATE npc_types SET loottable_id = :codecay_deathbone_magus_lt: WHERE id in (200011); # Deathbone_Magus 60
UPDATE npc_types SET loottable_id = :codecay_death_knight_lt: WHERE id in (200008); # Death_Knight 60
UPDATE npc_types SET loottable_id = :codecay_elite_necromancer_of_decay_lt: WHERE id in (200063); # Elite Necromancer_of_Decay 65
UPDATE npc_types SET loottable_id = :codecay_elite_corrupted_knight_lt: WHERE id in (200014); # Elite_Corrupted_Knight 61
UPDATE npc_types SET loottable_id = :codecay_elite_death_knight_lt: WHERE id in (200015); # Elite_Death_Knight 61
UPDATE npc_types SET loottable_id = :codecay_elite_knight_of_decay_lt: WHERE id in (200027, 200042); # Elite_Knight_of_Decay 65
UPDATE npc_types SET loottable_id = :codecay_elite_priest_of_decay_lt: WHERE id in (200020, 200043); # Elite_Priest_of_Decay 65
UPDATE npc_types SET loottable_id = :codecay_evil_emanates_lt: WHERE id in (200084); # Evil_emanates 1
UPDATE npc_types SET loottable_id = :codecay_eviscerator_fwexar_lt: WHERE id in (200073); # Eviscerator_Fwexar 65
UPDATE npc_types SET loottable_id = :codecay_firebone_archmagus_lt: WHERE id in (200070); # Firebone_Archmagus 62
UPDATE npc_types SET loottable_id = :codecay_firebone_magus_lt: WHERE id in (200013); # Firebone_Magus 60
UPDATE npc_types SET loottable_id = :codecay_foul_pusling_lt: WHERE id in (200004); # Foul_Pusling 60
UPDATE npc_types SET loottable_id = :codecay_fran_prisoal_lt: WHERE id in (200036); # Fran_Prisoal 70
UPDATE npc_types SET loottable_id = :codecay_greater_corrupted_pusling_lt: WHERE id in (200019); # Greater_Corrupted_Pusling 61
UPDATE npc_types SET loottable_id = :codecay_greater_foul_pusling_lt: WHERE id in (200031); # Greater_Foul_Pusling 61
UPDATE npc_types SET loottable_id = :codecay_greater_pusling_lt: WHERE id in (200025); # Greater_Pusling 61
UPDATE npc_types SET loottable_id = :codecay_high_mystic_qucosp_lt: WHERE id in (200074); # High_Mystic_Qucosp 65
UPDATE npc_types SET loottable_id = :codecay_high_priest_ultor_szanvon_lt: WHERE id in (200032, 200067); # High_Priest_Ultor_Szanvon 70
UPDATE npc_types SET loottable_id = :codecay_jerill_the_enraged_lt: WHERE id in (200068); # Jerill_the_Enraged 72
UPDATE npc_types SET loottable_id = :codecay_knight_of_decay_lt: WHERE id in (200018, 200064); # Knight_of_Decay 62
UPDATE npc_types SET loottable_id = :codecay_necromancer_of_decay_lt: WHERE id in (200021, 200062); # Necromancer_of_Decay 62
UPDATE npc_types SET loottable_id = :codecay_overlord_banord_paffa_lt: WHERE id in (200059); # Overlord_Banord_Paffa 66
UPDATE npc_types SET loottable_id = :codecay_pestilence_archon_lt: WHERE id in (200030); # Pestilence_Archon 61
UPDATE npc_types SET loottable_id = :codecay_pestilence_priest_lt: WHERE id in (200012); # Pestilence_Priest 60
UPDATE npc_types SET loottable_id = :codecay_plague_lord_hetral_lt: WHERE id in (200058); # Plague_Lord_Hetral 64
UPDATE npc_types SET loottable_id = :codecay_priest_of_decay_lt: WHERE id in (200017, 200065); # Priest_of_Decay 62
UPDATE npc_types SET loottable_id = :codecay_raex_pwodill_lt: WHERE id in (200033); # Raex_Pwodill 70
UPDATE npc_types SET loottable_id = :codecay_reanimated_reaver_lt: WHERE id in (200066); # Reanimated_Reaver 61
UPDATE npc_types SET loottable_id = :codecay_summoner_of_bertoxxulous_lt: WHERE id in (200024, 200056); # Summoner_of_Bertoxxulous 1
UPDATE npc_types SET loottable_id = :codecay_tarkil_adan_lt: WHERE id in (200040); # Tarkil_Adan 55
UPDATE npc_types SET loottable_id = :codecay_the_remains_lt: WHERE id in (200086); # The_remains 1
UPDATE npc_types SET loottable_id = :codecay_vindor_mawnil_lt: WHERE id in (200034); # Vindor_Mawnil 70
UPDATE npc_types SET loottable_id = :codecay_warlord_abouu_lt: WHERE id in (200071); # Warlord_Abouu 72
UPDATE npc_types SET loottable_id = :codecay_war_chieftain_dorwikak_lt: WHERE id in (200076); # War_Chieftain_Dorwikak 65
UPDATE npc_types SET loottable_id = :codecay_witchdoctor_orxkra_lt: WHERE id in (200075); # Witchdoctor_Orxkra 65
UPDATE npc_types SET loottable_id = :codecay_you_hear_lt: WHERE id in (200087); # You_hear 1
