UPDATE npc_types SET loottable_id = :hohonorb_lord_mithaniel_marr_lt: WHERE id in (220006); # #Lord_Mithaniel_Marr 77
UPDATE npc_types SET loottable_id = :hohonorb_an_honorable_protector_lt: WHERE id in (220003, 220004); # An_Honorable_Protector 67
UPDATE npc_types SET loottable_id = :hohonorb_an_honorable_protector_of_marr_lt: WHERE id in (220007); # An_Honorable_Protector_of_Marr 64
UPDATE npc_types SET loottable_id = :hohonorb_avatar_of_ralthazor_lt: WHERE id in (220017); # Avatar_of_Ralthazor 80
UPDATE npc_types SET loottable_id = :hohonorb_a_guardian_wrulon_lt: WHERE id in (220002); # A_Guardian_Wrulon 67
UPDATE npc_types SET loottable_id = :hohonorb_a_temple_guardian_lt: WHERE id in (220000); # A_Temple_Guardian 67
UPDATE npc_types SET loottable_id = :hohonorb_a_wrulon_guard_lt: WHERE id in (220001); # A_Wrulon_Guard 61
UPDATE npc_types SET loottable_id = :hohonorb_a_wrulon_protector_lt: WHERE id in (220005); # A_Wrulon_Protector 61
UPDATE npc_types SET loottable_id = :hohonorb_bromal_rythat_lt: WHERE id in (220010); # Bromal_Rythat 69
UPDATE npc_types SET loottable_id = :hohonorb_dogan_merlok_lt: WHERE id in (220009); # Dogan_Merlok 68
UPDATE npc_types SET loottable_id = :hohonorb_druhar_gandoc_lt: WHERE id in (220008); # Druhar_Gandoc 69
UPDATE npc_types SET loottable_id = :hohonorb_edium,_guardian_of_marr_lt: WHERE id in (220014); # Edium,_Guardian_of_Marr 75
UPDATE npc_types SET loottable_id = :hohonorb_halon_of_marr_lt: WHERE id in (220013); # Halon_of_Marr 73
UPDATE npc_types SET loottable_id = :hohonorb_lmm_trigger_lt: WHERE id in (220016); # LMM_trigger 60
UPDATE npc_types SET loottable_id = :hohonorb_lord_mithaniel_marr_lt: WHERE id in (220015); # Lord_Mithaniel_Marr 77
UPDATE npc_types SET loottable_id = :hohonorb_ralthazor,_champion_of_marr_lt: WHERE id in (220012); # Ralthazor,_Champion_of_Marr 75
UPDATE npc_types SET loottable_id = :hohonorb_rhodoc_sorenby_lt: WHERE id in (220011); # Rhodoc_Sorenby 68
