UPDATE npc_types SET loottable_id = :poeartha_a_gemmed_guardian_lt: WHERE id in (218134); # #A_Gemmed_Guardian 64
UPDATE npc_types SET loottable_id = :poeartha_a_rock_monstrosity_lt: WHERE id in (218089); # #A_Rock_Monstrosity 65
UPDATE npc_types SET loottable_id = :poeartha_a_sludge_lurker_lt: WHERE id in (218095); # #A_Sludge_Lurker 72
UPDATE npc_types SET loottable_id = :poeartha_croc_trap_lt: WHERE id in (218104); # #croc_trap 40
UPDATE npc_types SET loottable_id = :poeartha_dust_trigger_lt: WHERE id in (218093); # #Dust_Trigger 80
UPDATE npc_types SET loottable_id = :poeartha_earth_trap_lt: WHERE id in (218108); # #earth_trap 40
UPDATE npc_types SET loottable_id = :poeartha_ent_trap_lt: WHERE id in (218105); # #ent_trap 40
UPDATE npc_types SET loottable_id = :poeartha_final_trigger_lt: WHERE id in (218094); # #Final_Trigger 80
UPDATE npc_types SET loottable_id = :poeartha_gem_trap_lt: WHERE id in (218111); # #gem_trap 40
UPDATE npc_types SET loottable_id = :poeartha_geonid_trap_lt: WHERE id in (218112); # #geonid_trap 40
UPDATE npc_types SET loottable_id = :poeartha_jewel_trap_lt: WHERE id in (218113); # #jewel_trap 40
UPDATE npc_types SET loottable_id = :poeartha_korascian_trap_lt: WHERE id in (218110); # #korascian_trap 40
UPDATE npc_types SET loottable_id = :poeartha_mud_trap_lt: WHERE id in (218109); # #mud_trap 40
UPDATE npc_types SET loottable_id = :poeartha_mud_trigger_lt: WHERE id in (218090); # #Mud_Trigger 80
UPDATE npc_types SET loottable_id = :poeartha_rock_trap_lt: WHERE id in (218103); # #rock_trap 40
UPDATE npc_types SET loottable_id = :poeartha_stone_trap_lt: WHERE id in (218107); # #stone_trap 40
UPDATE npc_types SET loottable_id = :poeartha_stone_trigger_lt: WHERE id in (218092); # #Stone_Trigger 80
UPDATE npc_types SET loottable_id = :poeartha_tree_trap_lt: WHERE id in (218114); # #tree_trap 40
UPDATE npc_types SET loottable_id = :poeartha_undead_trap_lt: WHERE id in (218132); # #undead_trap 40
UPDATE npc_types SET loottable_id = :poeartha_vekerchiki_trap_lt: WHERE id in (218106); # #Vekerchiki_trap 40
UPDATE npc_types SET loottable_id = :poeartha_vine_trigger_lt: WHERE id in (218091); # #Vine_Trigger 80
UPDATE npc_types SET loottable_id = :poeartha_an_ancient_vekerchiki_champion_lt: WHERE id in (218052); # An_Ancient_Vekerchiki_Champion 69
UPDATE npc_types SET loottable_id = :poeartha_an_animated_earthwalker_lt: WHERE id in (218009); # An_Animated_Earthwalker 63
UPDATE npc_types SET loottable_id = :poeartha_an_arborean_earthshaker_lt: WHERE id in (218014); # An_Arborean_Earthshaker 63
UPDATE npc_types SET loottable_id = :poeartha_an_earthcrafted_assassin_lt: WHERE id in (218024); # An_Earthcrafted_Assassin 63
UPDATE npc_types SET loottable_id = :poeartha_an_earthen_crusader_lt: WHERE id in (218027, 218035); # An_Earthen_Crusader 63
UPDATE npc_types SET loottable_id = :poeartha_an_earthen_mudslinger_lt: WHERE id in (218000); # An_Earthen_Mudslinger 63
UPDATE npc_types SET loottable_id = :poeartha_an_earthen_mudwalker_lt: WHERE id in (218013); # An_Earthen_Mudwalker 62
UPDATE npc_types SET loottable_id = :poeartha_an_earthen_stonejumper_lt: WHERE id in (218003); # An_Earthen_Stonejumper 63
UPDATE npc_types SET loottable_id = :poeartha_an_earthen_warden_lt: WHERE id in (218021); # An_Earthen_Warden 63
UPDATE npc_types SET loottable_id = :poeartha_an_earth_initate_lt: WHERE id in (218026, 218039); # An_Earth_Initate 60
UPDATE npc_types SET loottable_id = :poeartha_an_encrusted_dirt_cloud_lt: WHERE id in (218129); # An_Encrusted_Dirt_Cloud 73
UPDATE npc_types SET loottable_id = :poeartha_an_unfinished_stonewalker_lt: WHERE id in (218036); # An_Unfinished_Stonewalker 60
UPDATE npc_types SET loottable_id = :poeartha_an_unkempt_arborean_lt: WHERE id in (218011); # An_Unkempt_Arborean 63
UPDATE npc_types SET loottable_id = :poeartha_a_bloodsoaked_vegerog_lt: WHERE id in (218128); # A_Bloodsoaked_Vegerog 73
UPDATE npc_types SET loottable_id = :poeartha_a_bloodthirsty_vegerog_lt: WHERE id in (218126, 218040); # A_Bloodthirsty_Vegerog 70
UPDATE npc_types SET loottable_id = :poeartha_a_boulder_thrower_lt: WHERE id in (218033); # A_Boulder_Thrower 66
UPDATE npc_types SET loottable_id = :poeartha_a_crumbling_stone_mass_lt: WHERE id in (218031); # A_Crumbling_Stone_Mass 66
UPDATE npc_types SET loottable_id = :poeartha_a_crystalline_formation_lt: WHERE id in (218002); # A_Crystalline_Formation 64
UPDATE npc_types SET loottable_id = :poeartha_a_deadly_earth_armadillo_lt: WHERE id in (218007); # A_Deadly_Earth_Armadillo 64
UPDATE npc_types SET loottable_id = :poeartha_a_decaying_spelunker_lt: WHERE id in (218133); # A_Decaying_Spelunker 64
UPDATE npc_types SET loottable_id = :poeartha_a_dusty_warder_lt: WHERE id in (218022); # a_dusty_warder 70
UPDATE npc_types SET loottable_id = :poeartha_a_dust_devotee_lt: WHERE id in (218064); # A_Dust_Devotee 67
UPDATE npc_types SET loottable_id = :poeartha_a_dust_follower_lt: WHERE id in (218122); # A_Dust_Follower 72
UPDATE npc_types SET loottable_id = :poeartha_a_fearsome_earthcrafter_lt: WHERE id in (218008); # A_Fearsome_Earthcrafter 63
UPDATE npc_types SET loottable_id = :poeartha_a_filth_gorger_lt: WHERE id in (218130, 218042); # A_Filth_Gorger 68
UPDATE npc_types SET loottable_id = :poeartha_a_gemmed_guardian_lt: WHERE id in (218005); # A_Gemmed_Guardian 64
UPDATE npc_types SET loottable_id = :poeartha_a_gemmed_protector_lt: WHERE id in (218034); # A_Gemmed_Protector 64
UPDATE npc_types SET loottable_id = :poeartha_a_gemmed_rock_man_lt: WHERE id in (218066); # A_Gemmed_Rock_Man 60
UPDATE npc_types SET loottable_id = :poeartha_a_glass_formation_lt: WHERE id in (218088); # A_Glass_Formation 60
UPDATE npc_types SET loottable_id = :poeartha_a_korascian_hunter_lt: WHERE id in (218004); # A_Korascian_Hunter 63
UPDATE npc_types SET loottable_id = :poeartha_a_korascian_necksnapper_lt: WHERE id in (218012); # A_Korascian_Necksnapper 63
UPDATE npc_types SET loottable_id = :poeartha_a_korascian_warlord_lt: WHERE id in (218065); # A_Korascian_Warlord 69
UPDATE npc_types SET loottable_id = :poeartha_a_magical_collection_of_dust_lt: WHERE id in (218097); # A_Magical_Collection_of_Dust 60
UPDATE npc_types SET loottable_id = :poeartha_a_majestic_gemwalker_lt: WHERE id in (218001); # A_Majestic_Gemwalker 64
UPDATE npc_types SET loottable_id = :poeartha_a_mangled_vegerog_lt: WHERE id in (218023); # A_Mangled_Vegerog 63
UPDATE npc_types SET loottable_id = :poeartha_a_mass_of_living_earth_lt: WHERE id in (218010); # A_Mass_of_Living_Earth 63
UPDATE npc_types SET loottable_id = :poeartha_a_merciless_mudslinger_lt: WHERE id in (218123); # A_Merciless_Mudslinger 73
UPDATE npc_types SET loottable_id = :poeartha_a_miniature_dustrunner_lt: WHERE id in (218054); # A_Miniature_Dustrunner 46
UPDATE npc_types SET loottable_id = :poeartha_a_monsterous_earthwalker_lt: WHERE id in (218098); # A_Monsterous_Earthwalker 73
UPDATE npc_types SET loottable_id = :poeartha_a_monsterous_mudwalker_lt: WHERE id in (218050); # A_Monsterous_Mudwalker 73
UPDATE npc_types SET loottable_id = :poeartha_a_mound_of_rubble_lt: WHERE id in (218118, 218119, 218120, 218076); # A_Mound_of_Rubble 70
UPDATE npc_types SET loottable_id = :poeartha_a_muck_mudlet_lt: WHERE id in (218084); # A_Muck_Mudlet 55
UPDATE npc_types SET loottable_id = :poeartha_a_muddite_mudling_lt: WHERE id in (218037); # A_Muddite_Mudling 55
UPDATE npc_types SET loottable_id = :poeartha_a_muddite_seeker_lt: WHERE id in (218018); # A_Muddite_Seeker 66
UPDATE npc_types SET loottable_id = :poeartha_a_mudfilled_earth_golem_lt: WHERE id in (218099); # A_Mudfilled_Earth_Golem 63
UPDATE npc_types SET loottable_id = :poeartha_a_mystical_arbitor_of_earth_lt: WHERE id in (218053); # A_Mystical_Arbitor_of_Earth 74
UPDATE npc_types SET loottable_id = :poeartha_a_needlescale_basilisk_lt: WHERE id in (218006); # A_Needlescale_Basilisk 64
UPDATE npc_types SET loottable_id = :poeartha_a_needlescale_hatchling_lt: WHERE id in (218080); # A_Needlescale_Hatchling 60
UPDATE npc_types SET loottable_id = :poeartha_a_perfected_warder_of_earth_lt: WHERE id in (218096); # A_Perfected_Warder_of_Earth 73
UPDATE npc_types SET loottable_id = :poeartha_a_perfect_rock_formation_lt: WHERE id in (218083); # A_Perfect_Rock_Formation 69
UPDATE npc_types SET loottable_id = :poeartha_a_pile_of_boulders_lt: WHERE id in (218030); # A_Pile_of_Boulders 66
UPDATE npc_types SET loottable_id = :poeartha_a_planar_projection_lt: WHERE id in (218068); # A_Planar_Projection 1
UPDATE npc_types SET loottable_id = :poeartha_a_prismatic_basilisk_lt: WHERE id in (218100); # A_Prismatic_Basilisk 69
UPDATE npc_types SET loottable_id = :poeartha_a_pristine_gem_golem_lt: WHERE id in (218101); # A_Pristine_Gem_Golem 69
UPDATE npc_types SET loottable_id = :poeartha_a_rock_creation_lt: WHERE id in (218032); # A_Rock_Creation 66
UPDATE npc_types SET loottable_id = :poeartha_a_rock_monstrosity_lt: WHERE id in (218029); # A_Rock_Monstrosity 65
UPDATE npc_types SET loottable_id = :poeartha_a_rotting_arborean_lt: WHERE id in (218015); # A_Rotting_Arborean 63
UPDATE npc_types SET loottable_id = :poeartha_a_shimmering_gem_sentry_lt: WHERE id in (218087); # A_Shimmering_Gem_Sentry 69
UPDATE npc_types SET loottable_id = :poeartha_a_sludge_lurker_lt: WHERE id in (218124, 218125, 218070); # A_Sludge_Lurker 70
UPDATE npc_types SET loottable_id = :poeartha_a_small_rockmonster_lt: WHERE id in (218075); # A_Small_Rockmonster 60
UPDATE npc_types SET loottable_id = :poeartha_a_stone_abomination_lt: WHERE id in (218016, 218017); # A_Stone_Abomination 63
UPDATE npc_types SET loottable_id = :poeartha_a_stone_fortification_lt: WHERE id in (218072); # A_Stone_Fortification 59
UPDATE npc_types SET loottable_id = :poeartha_a_stone_heap_lt: WHERE id in (218079); # A_Stone_Heap 64
UPDATE npc_types SET loottable_id = :poeartha_a_tainted_rock_beast_lt: WHERE id in (218019); # A_Tainted_Rock_Beast 66
UPDATE npc_types SET loottable_id = :poeartha_a_tenacious_arborean_lt: WHERE id in (218086); # A_Tenacious_Arborean 60
UPDATE npc_types SET loottable_id = :poeartha_a_towering_rock_formation_lt: WHERE id in (218028); # A_Towering_Rock_Formation 63
UPDATE npc_types SET loottable_id = :poeartha_a_triumvirate_protector_lt: WHERE id in (218061); # A_Triumvirate_Protector 64
UPDATE npc_types SET loottable_id = :poeartha_a_vekerchiki_drone_lt: WHERE id in (218047); # A_Vekerchiki_Drone 60
UPDATE npc_types SET loottable_id = :poeartha_a_vekerchiki_warrior_lt: WHERE id in (218025); # A_Vekerchiki_Warrior 63
UPDATE npc_types SET loottable_id = :poeartha_a_war_shapen_earth_emissary_lt: WHERE id in (218020); # A_War_Shapen_Earth_Emissary 63
UPDATE npc_types SET loottable_id = :poeartha_a_young_cave_geonid_lt: WHERE id in (218046); # A_Young_Cave_Geonid 60
UPDATE npc_types SET loottable_id = :poeartha_a_young_frog_lt: WHERE id in (218048); # A_Young_Frog 60
UPDATE npc_types SET loottable_id = :poeartha_calris_bristlebranch_lt: WHERE id in (218117); # Calris_Bristlebranch 69
UPDATE npc_types SET loottable_id = :poeartha_derugoak_bloodwalker_lt: WHERE id in (218127, 218058); # Derugoak_Bloodwalker 73
UPDATE npc_types SET loottable_id = :poeartha_galsinak_earthrumble_lt: WHERE id in (218116); # Galsinak_Earthrumble 68
UPDATE npc_types SET loottable_id = :poeartha_glimmerstone_lt: WHERE id in (218074); # Glimmerstone 69
UPDATE npc_types SET loottable_id = :poeartha_peregrin_rockskull_lt: WHERE id in (218121, 218049); # Peregrin_Rockskull 73
UPDATE npc_types SET loottable_id = :poeartha_tantisala_jaggedtooth_lt: WHERE id in (218038); # Tantisala_Jaggedtooth 73
UPDATE npc_types SET loottable_id = :poeartha_the_creature_lt: WHERE id in (218059); # The_creature 1
UPDATE npc_types SET loottable_id = :poeartha_the_last_lt: WHERE id in (218085); # The_last 1
UPDATE npc_types SET loottable_id = :poeartha_the_living_earth_lt: WHERE id in (218115); # The_Living_Earth 68
UPDATE npc_types SET loottable_id = :poeartha_tribal_leader_diseranon_lt: WHERE id in (218081); # Tribal_Leader_Diseranon 69
UPDATE npc_types SET loottable_id = :poeartha_triumvirate_of_soil_lt: WHERE id in (218131, 218045); # Triumvirate_of_Soil 72
