INSERT INTO loottable(name) VALUES('poinnovation_assistant_kelrig'); # :poinnovation_assistant_kelrig_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_corroded_prototype'); # :poinnovation_a_corroded_prototype_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_greasy_clockwork'); # :poinnovation_a_greasy_clockwork_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_malfunctioning_system'); # :poinnovation_a_malfunctioning_system_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_rust_covered_model'); # :poinnovation_a_rust_covered_model_lt:
INSERT INTO loottable(name) VALUES('poinnovation_chronographer_muon'); # :poinnovation_chronographer_muon_lt:
INSERT INTO loottable(name) VALUES('poinnovation_endurance_trigger'); # :poinnovation_endurance_trigger_lt:
INSERT INTO loottable(name) VALUES('poinnovation_junk_beast'); # :poinnovation_junk_beast_lt:
INSERT INTO loottable(name) VALUES('poinnovation_loreseeker_maelin'); # :poinnovation_loreseeker_maelin_lt:
INSERT INTO loottable(name) VALUES('poinnovation_manaetic_behemoth'); # :poinnovation_manaetic_behemoth_lt:
INSERT INTO loottable(name) VALUES('poinnovation_researcher_kaeon'); # :poinnovation_researcher_kaeon_lt:
INSERT INTO loottable(name) VALUES('poinnovation_spider_spawner'); # :poinnovation_spider_spawner_lt:
INSERT INTO loottable(name) VALUES('poinnovation_xanamech_nezmirthafen'); # :poinnovation_xanamech_nezmirthafen_lt:
INSERT INTO loottable(name) VALUES('poinnovation_an_archaic_model'); # :poinnovation_an_archaic_model_lt:
INSERT INTO loottable(name) VALUES('poinnovation_an_erratic_model'); # :poinnovation_an_erratic_model_lt:
INSERT INTO loottable(name) VALUES('poinnovation_an_etheric_pool'); # :poinnovation_an_etheric_pool_lt:
INSERT INTO loottable(name) VALUES('poinnovation_an_obsolete_model'); # :poinnovation_an_obsolete_model_lt:
INSERT INTO loottable(name) VALUES('poinnovation_an_obsolete_unit'); # :poinnovation_an_obsolete_unit_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_busted_power_carrier'); # :poinnovation_a_busted_power_carrier_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_clockwork_device'); # :poinnovation_a_clockwork_device_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_clockwork_golem'); # :poinnovation_a_clockwork_golem_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_corroded_model'); # :poinnovation_a_corroded_model_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_corrupted_system'); # :poinnovation_a_corrupted_system_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_defective_clockwork'); # :poinnovation_a_defective_clockwork_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_degrading_guardian'); # :poinnovation_a_degrading_guardian_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_manaetic_contraption'); # :poinnovation_a_manaetic_contraption_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_manaetic_device'); # :poinnovation_a_manaetic_device_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_manaetic_gadget'); # :poinnovation_a_manaetic_gadget_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_metallic_slime'); # :poinnovation_a_metallic_slime_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_rusted_model'); # :poinnovation_a_rusted_model_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_scrap_collector'); # :poinnovation_a_scrap_collector_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_scrounging_clockwork'); # :poinnovation_a_scrounging_clockwork_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_tin_soldier'); # :poinnovation_a_tin_soldier_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_tin_soldier_guard'); # :poinnovation_a_tin_soldier_guard_lt:
INSERT INTO loottable(name) VALUES('poinnovation_a_weathered_clockwork'); # :poinnovation_a_weathered_clockwork_lt:
INSERT INTO loottable(name) VALUES('poinnovation_giwin_mirakon'); # :poinnovation_giwin_mirakon_lt:
INSERT INTO loottable(name) VALUES('poinnovation_grooble'); # :poinnovation_grooble_lt:
INSERT INTO loottable(name) VALUES('poinnovation_manaetic_behemoth'); # :poinnovation_manaetic_behemoth_lt:
INSERT INTO loottable(name) VALUES('poinnovation_manaetic_prototype_ix'); # :poinnovation_manaetic_prototype_ix_lt:
INSERT INTO loottable(name) VALUES('poinnovation_manaetic_prototype_x'); # :poinnovation_manaetic_prototype_x_lt:
INSERT INTO loottable(name) VALUES('poinnovation_manaetic_prototype_xi'); # :poinnovation_manaetic_prototype_xi_lt:
INSERT INTO loottable(name) VALUES('poinnovation_nitram_anizok'); # :poinnovation_nitram_anizok_lt:
INSERT INTO loottable(name) VALUES('poinnovation_rusty_tail'); # :poinnovation_rusty_tail_lt:
INSERT INTO loottable(name) VALUES('poinnovation_sephin_mirakon'); # :poinnovation_sephin_mirakon_lt:
INSERT INTO loottable(name) VALUES('poinnovation_spider_controller'); # :poinnovation_spider_controller_lt:
INSERT INTO loottable(name) VALUES('poinnovation_xanamech_nezmirthafen'); # :poinnovation_xanamech_nezmirthafen_lt:
