INSERT INTO loottable(name) VALUES('postorms_'); # :postorms__lt:
INSERT INTO loottable(name) VALUES('postorms_'); # :postorms__lt:
INSERT INTO loottable(name) VALUES('postorms_an_earthen_spirit'); # :postorms_an_earthen_spirit_lt:
INSERT INTO loottable(name) VALUES('postorms_a_diaku_raider'); # :postorms_a_diaku_raider_lt:
INSERT INTO loottable(name) VALUES('postorms_a_kokavor_advisor'); # :postorms_a_kokavor_advisor_lt:
INSERT INTO loottable(name) VALUES('postorms_a_kokavor_bark_spirit'); # :postorms_a_kokavor_bark_spirit_lt:
INSERT INTO loottable(name) VALUES('postorms_a_noxious_scorponnis'); # :postorms_a_noxious_scorponnis_lt:
INSERT INTO loottable(name) VALUES('postorms_a_roving_cactore'); # :postorms_a_roving_cactore_lt:
INSERT INTO loottable(name) VALUES('postorms_a_roving_scorpioco'); # :postorms_a_roving_scorpioco_lt:
INSERT INTO loottable(name) VALUES('postorms_a_spined_cactoric'); # :postorms_a_spined_cactoric_lt:
INSERT INTO loottable(name) VALUES('postorms_a_tempest_toad'); # :postorms_a_tempest_toad_lt:
INSERT INTO loottable(name) VALUES('postorms_a_vacillating_loktole'); # :postorms_a_vacillating_loktole_lt:
INSERT INTO loottable(name) VALUES('postorms_a_woodspirit_vineguard'); # :postorms_a_woodspirit_vineguard_lt:
INSERT INTO loottable(name) VALUES('postorms_darkened_chanting_woodspirit'); # :postorms_darkened_chanting_woodspirit_lt:
INSERT INTO loottable(name) VALUES('postorms_death_trigger'); # :postorms_death_trigger_lt:
INSERT INTO loottable(name) VALUES('postorms_gurebk_lord_of_krendic'); # :postorms_gurebk_lord_of_krendic_lt:
INSERT INTO loottable(name) VALUES('postorms_jeplak_lord_of_srerendi'); # :postorms_jeplak_lord_of_srerendi_lt:
INSERT INTO loottable(name) VALUES('postorms_neffiken_lord_of_kelekvor'); # :postorms_neffiken_lord_of_kelekvor_lt:
INSERT INTO loottable(name) VALUES('postorms_ancient_trigger'); # :postorms_ancient_trigger_lt:
INSERT INTO loottable(name) VALUES('postorms_an_abandoned_wanderer'); # :postorms_an_abandoned_wanderer_lt:
INSERT INTO loottable(name) VALUES('postorms_an_aimless_adventurer'); # :postorms_an_aimless_adventurer_lt:
INSERT INTO loottable(name) VALUES('postorms_an_armantis_wayfarer'); # :postorms_an_armantis_wayfarer_lt:
INSERT INTO loottable(name) VALUES('postorms_an_her_megir'); # :postorms_an_her_megir_lt:
INSERT INTO loottable(name) VALUES('postorms_an_irmin_fannsk'); # :postorms_an_irmin_fannsk_lt:
INSERT INTO loottable(name) VALUES('postorms_an_irmin_her_megir'); # :postorms_an_irmin_her_megir_lt:
INSERT INTO loottable(name) VALUES('postorms_askr_the_lost'); # :postorms_askr_the_lost_lt:
INSERT INTO loottable(name) VALUES('postorms_a_beleaguered_ent'); # :postorms_a_beleaguered_ent_lt:
INSERT INTO loottable(name) VALUES('postorms_a_confused_castaway'); # :postorms_a_confused_castaway_lt:
INSERT INTO loottable(name) VALUES('postorms_a_fannsk'); # :postorms_a_fannsk_lt:
INSERT INTO loottable(name) VALUES('postorms_a_fish'); # :postorms_a_fish_lt:
INSERT INTO loottable(name) VALUES('postorms_a_floral_amalgam'); # :postorms_a_floral_amalgam_lt:
INSERT INTO loottable(name) VALUES('postorms_a_forgotten_traveler'); # :postorms_a_forgotten_traveler_lt:
INSERT INTO loottable(name) VALUES('postorms_a_forlorn_ent'); # :postorms_a_forlorn_ent_lt:
INSERT INTO loottable(name) VALUES('postorms_a_grezlan_cub'); # :postorms_a_grezlan_cub_lt:
INSERT INTO loottable(name) VALUES('postorms_a_hleyta_menn'); # :postorms_a_hleyta_menn_lt:
INSERT INTO loottable(name) VALUES('postorms_a_hleytis_maor'); # :postorms_a_hleytis_maor_lt:
INSERT INTO loottable(name) VALUES('postorms_a_hurricane_loktole'); # :postorms_a_hurricane_loktole_lt:
INSERT INTO loottable(name) VALUES('postorms_a_hurricane_lorok'); # :postorms_a_hurricane_lorok_lt:
INSERT INTO loottable(name) VALUES('postorms_a_hurricane_nophtan'); # :postorms_a_hurricane_nophtan_lt:
INSERT INTO loottable(name) VALUES('postorms_a_jotna_fannsk'); # :postorms_a_jotna_fannsk_lt:
INSERT INTO loottable(name) VALUES('postorms_a_jotna_her_megir'); # :postorms_a_jotna_her_megir_lt:
INSERT INTO loottable(name) VALUES('postorms_a_kelekvor_moss_snake'); # :postorms_a_kelekvor_moss_snake_lt:
INSERT INTO loottable(name) VALUES('postorms_a_kokavor_chieftain'); # :postorms_a_kokavor_chieftain_lt:
INSERT INTO loottable(name) VALUES('postorms_a_kokavor_elder'); # :postorms_a_kokavor_elder_lt:
INSERT INTO loottable(name) VALUES('postorms_a_kokavor_krovian'); # :postorms_a_kokavor_krovian_lt:
INSERT INTO loottable(name) VALUES('postorms_a_kokavor_senvar'); # :postorms_a_kokavor_senvar_lt:
INSERT INTO loottable(name) VALUES('postorms_a_krendic_slitherer'); # :postorms_a_krendic_slitherer_lt:
INSERT INTO loottable(name) VALUES('postorms_a_lost_soul'); # :postorms_a_lost_soul_lt:
INSERT INTO loottable(name) VALUES('postorms_a_maligned_ent'); # :postorms_a_maligned_ent_lt:
INSERT INTO loottable(name) VALUES('postorms_a_mangled_traveller'); # :postorms_a_mangled_traveller_lt:
INSERT INTO loottable(name) VALUES('postorms_a_manipulated_ent'); # :postorms_a_manipulated_ent_lt:
INSERT INTO loottable(name) VALUES('postorms_a_nomadic_scorpion'); # :postorms_a_nomadic_scorpion_lt:
INSERT INTO loottable(name) VALUES('postorms_a_noxious_scorponnis'); # :postorms_a_noxious_scorponnis_lt:
INSERT INTO loottable(name) VALUES('postorms_a_restrained_ent'); # :postorms_a_restrained_ent_lt:
INSERT INTO loottable(name) VALUES('postorms_a_rock_storm'); # :postorms_a_rock_storm_lt:
INSERT INTO loottable(name) VALUES('postorms_a_rootless_cactoren'); # :postorms_a_rootless_cactoren_lt:
INSERT INTO loottable(name) VALUES('postorms_a_roving_cactore'); # :postorms_a_roving_cactore_lt:
INSERT INTO loottable(name) VALUES('postorms_a_roving_scorpioco'); # :postorms_a_roving_scorpioco_lt:
INSERT INTO loottable(name) VALUES('postorms_a_royal_scorpion'); # :postorms_a_royal_scorpion_lt:
INSERT INTO loottable(name) VALUES('postorms_a_scorned_tronendi'); # :postorms_a_scorned_tronendi_lt:
INSERT INTO loottable(name) VALUES('postorms_a_sheklak_armanento'); # :postorms_a_sheklak_armanento_lt:
INSERT INTO loottable(name) VALUES('postorms_a_spined_cactoric'); # :postorms_a_spined_cactoric_lt:
INSERT INTO loottable(name) VALUES('postorms_a_srerendi_slitherer'); # :postorms_a_srerendi_slitherer_lt:
INSERT INTO loottable(name) VALUES('postorms_a_srerento_armantis'); # :postorms_a_srerento_armantis_lt:
INSERT INTO loottable(name) VALUES('postorms_a_storm_battered_traveler'); # :postorms_a_storm_battered_traveler_lt:
INSERT INTO loottable(name) VALUES('postorms_a_storm_drenched_nophtan'); # :postorms_a_storm_drenched_nophtan_lt:
INSERT INTO loottable(name) VALUES('postorms_a_storm_gruezok'); # :postorms_a_storm_gruezok_lt:
INSERT INTO loottable(name) VALUES('postorms_a_storm_worn_armantis'); # :postorms_a_storm_worn_armantis_lt:
INSERT INTO loottable(name) VALUES('postorms_a_swordfish'); # :postorms_a_swordfish_lt:
INSERT INTO loottable(name) VALUES('postorms_a_tempest_toad'); # :postorms_a_tempest_toad_lt:
INSERT INTO loottable(name) VALUES('postorms_a_tempest_torn_traveler'); # :postorms_a_tempest_torn_traveler_lt:
INSERT INTO loottable(name) VALUES('postorms_a_tumultuous_storm'); # :postorms_a_tumultuous_storm_lt:
INSERT INTO loottable(name) VALUES('postorms_a_typhoon_amphan'); # :postorms_a_typhoon_amphan_lt:
INSERT INTO loottable(name) VALUES('postorms_a_typhoon_floraling'); # :postorms_a_typhoon_floraling_lt:
INSERT INTO loottable(name) VALUES('postorms_a_typhoon_lorok'); # :postorms_a_typhoon_lorok_lt:
INSERT INTO loottable(name) VALUES('postorms_a_vacillating_loktole'); # :postorms_a_vacillating_loktole_lt:
INSERT INTO loottable(name) VALUES('postorms_a_violent_sand_storm'); # :postorms_a_violent_sand_storm_lt:
INSERT INTO loottable(name) VALUES('postorms_a_wandering_grezlan'); # :postorms_a_wandering_grezlan_lt:
INSERT INTO loottable(name) VALUES('postorms_a_wanton_tronera'); # :postorms_a_wanton_tronera_lt:
INSERT INTO loottable(name) VALUES('postorms_a_waterlogged_floran'); # :postorms_a_waterlogged_floran_lt:
INSERT INTO loottable(name) VALUES('postorms_a_whirling_rock_storm'); # :postorms_a_whirling_rock_storm_lt:
INSERT INTO loottable(name) VALUES('postorms_bearuth_the_stoic'); # :postorms_bearuth_the_stoic_lt:
INSERT INTO loottable(name) VALUES('postorms_bittrik_the_unkempt'); # :postorms_bittrik_the_unkempt_lt:
INSERT INTO loottable(name) VALUES('postorms_corrupt_volaas'); # :postorms_corrupt_volaas_lt:
INSERT INTO loottable(name) VALUES('postorms_dolshak_the_ornery'); # :postorms_dolshak_the_ornery_lt:
INSERT INTO loottable(name) VALUES('postorms_drornok_tok_volok'); # :postorms_drornok_tok_volok_lt:
INSERT INTO loottable(name) VALUES('postorms_drornok_trigger'); # :postorms_drornok_trigger_lt:
INSERT INTO loottable(name) VALUES('postorms_falto,_lord_of_thunder'); # :postorms_falto,_lord_of_thunder_lt:
INSERT INTO loottable(name) VALUES('postorms_faruek_the_bold'); # :postorms_faruek_the_bold_lt:
INSERT INTO loottable(name) VALUES('postorms_grok'); # :postorms_grok_lt:
INSERT INTO loottable(name) VALUES('postorms_gurebk_lord_of_krendic'); # :postorms_gurebk_lord_of_krendic_lt:
INSERT INTO loottable(name) VALUES('postorms_jeplak_lord_of_srerendi'); # :postorms_jeplak_lord_of_srerendi_lt:
INSERT INTO loottable(name) VALUES('postorms_krelk_the_drifter'); # :postorms_krelk_the_drifter_lt:
INSERT INTO loottable(name) VALUES('postorms_laruken_the_rigid'); # :postorms_laruken_the_rigid_lt:
INSERT INTO loottable(name) VALUES('postorms_neffiken_lord_of_kelekvor'); # :postorms_neffiken_lord_of_kelekvor_lt:
INSERT INTO loottable(name) VALUES('postorms_olidan'); # :postorms_olidan_lt:
INSERT INTO loottable(name) VALUES('postorms_paruek_the_strong'); # :postorms_paruek_the_strong_lt:
INSERT INTO loottable(name) VALUES('postorms_pendubk_the_turbulent'); # :postorms_pendubk_the_turbulent_lt:
INSERT INTO loottable(name) VALUES('postorms_relv_the_mysterious'); # :postorms_relv_the_mysterious_lt:
INSERT INTO loottable(name) VALUES('postorms_solnebk_the_unruly'); # :postorms_solnebk_the_unruly_lt:
INSERT INTO loottable(name) VALUES('postorms_spawner'); # :postorms_spawner_lt:
INSERT INTO loottable(name) VALUES('postorms_ston_spawner'); # :postorms_ston_spawner_lt:
INSERT INTO loottable(name) VALUES('postorms_stonruak,_ancient_of_trees'); # :postorms_stonruak,_ancient_of_trees_lt:
INSERT INTO loottable(name) VALUES('postorms_swirling_monsoon_elemental'); # :postorms_swirling_monsoon_elemental_lt:
INSERT INTO loottable(name) VALUES('postorms_wembly_the_forlorn'); # :postorms_wembly_the_forlorn_lt:
INSERT INTO loottable(name) VALUES('postorms_zertuken_the_unyielding'); # :postorms_zertuken_the_unyielding_lt:
INSERT INTO loottable(name) VALUES('postorms__'); # :postorms___lt:
