UPDATE npc_types SET loottable_id = :potimeb_a_flame_mephit_lt: WHERE id in (223088); # #a_flame_mephit 64
UPDATE npc_types SET loottable_id = :potimeb_a_servitor_of_peace_lt: WHERE id in (223101); # #A_Servitor_of_Peace 1
UPDATE npc_types SET loottable_id = :potimeb_bertoxxulous_lt: WHERE id in (223142); # #Bertoxxulous 75
UPDATE npc_types SET loottable_id = :potimeb_cazic_thule_lt: WHERE id in (223166); # #Cazic_Thule 75
UPDATE npc_types SET loottable_id = :potimeb_innoruuk_lt: WHERE id in (223167); # #Innoruuk 75
UPDATE npc_types SET loottable_id = :potimeb_rallos_zek_lt: WHERE id in (223168); # #Rallos_Zek 75
UPDATE npc_types SET loottable_id = :potimeb_vallon_zek_lt: WHERE id in (223164); # #Vallon_Zek 71
UPDATE npc_types SET loottable_id = :potimeb_amygdalan_knight_lt: WHERE id in (223199); # Amygdalan_knight 66
UPDATE npc_types SET loottable_id = :potimeb_anar_of_water_lt: WHERE id in (223104); # Anar_of_Water 68
UPDATE npc_types SET loottable_id = :potimeb_an_abhorrent_lt: WHERE id in (223198); # an_abhorrent 66
UPDATE npc_types SET loottable_id = :potimeb_an_air_phoenix_noble_lt: WHERE id in (223087, 223226); # An_Air_Phoenix_Noble 64
UPDATE npc_types SET loottable_id = :potimeb_an_air_phoenix_noble__lt: WHERE id in (223187, 223188); # An_Air_Phoenix_Noble_ 64
UPDATE npc_types SET loottable_id = :potimeb_an_arcane_cube_formation_lt: WHERE id in (223045); # An_Arcane_Cube_Formation 69
UPDATE npc_types SET loottable_id = :potimeb_an_earthen_overseer_lt: WHERE id in (223108); # An_Earthen_Overseer 75
UPDATE npc_types SET loottable_id = :potimeb_an_elemental_stonefist_lt: WHERE id in (223102, 223133); # An_Elemental_Stonefist 64
UPDATE npc_types SET loottable_id = :potimeb_an_inferno_mephit_lt: WHERE id in (223233, 223234, 223235, 223236, 223095); # an_inferno_mephit 65
UPDATE npc_types SET loottable_id = :potimeb_an_inferno_mephit__lt: WHERE id in (223163); # an_inferno_mephit_ 65
UPDATE npc_types SET loottable_id = :potimeb_an_undead_guardian_lt: WHERE id in (223105, 223116, 223121, 223122, 223149); # an_undead_guardian 65
UPDATE npc_types SET loottable_id = :potimeb_an_undead_guardian__lt: WHERE id in (223107, 223138); # an_undead_guardian_ 65
UPDATE npc_types SET loottable_id = :potimeb_an_undead_protector_lt: WHERE id in (223103, 223150); # an_undead_protector 69
UPDATE npc_types SET loottable_id = :potimeb_an_unholy_rock_fiend_lt: WHERE id in (223110, 223125); # An_Unholy_Rock_Fiend 60
UPDATE npc_types SET loottable_id = :potimeb_archon_of_the_plaguebringer_lt: WHERE id in (223027); # Archon_of_the_Plaguebringer 69
UPDATE npc_types SET loottable_id = :potimeb_assassin_of_hate_lt: WHERE id in (223052); # Assassin_of_Hate 67
UPDATE npc_types SET loottable_id = :potimeb_avatar_of_the_elements_lt: WHERE id in (223073); # Avatar_of_the_Elements 72
UPDATE npc_types SET loottable_id = :potimeb_a_crustacean_champion_lt: WHERE id in (223132, 223136); # A_Crustacean_Champion 60
UPDATE npc_types SET loottable_id = :potimeb_a_dark_guardian_of_the_warlord_lt: WHERE id in (223006, 223034); # A_Dark_Guardian_of_the_Warlord 69
UPDATE npc_types SET loottable_id = :potimeb_a_deadly_warboar_lt: WHERE id in (223022, 223032); # A_Deadly_Warboar 71
UPDATE npc_types SET loottable_id = :potimeb_a_deceiver_of_zek_lt: WHERE id in (223004, 223036); # a_deceiver_of_zek 69
UPDATE npc_types SET loottable_id = :potimeb_a_deepwater_assassin_lt: WHERE id in (223126, 223141); # A_Deepwater_Assassin 60
UPDATE npc_types SET loottable_id = :potimeb_a_deepwater_triloun_lt: WHERE id in (223100, 223115); # a_deepwater_triloun 65
UPDATE npc_types SET loottable_id = :potimeb_a_ferocious_cube_formation_lt: WHERE id in (223042); # A_Ferocious_Cube_Formation 67
UPDATE npc_types SET loottable_id = :potimeb_a_ferocious_cube_phantasmist_lt: WHERE id in (223043, 223044); # A_Ferocious_Cube_Phantasmist 67
UPDATE npc_types SET loottable_id = :potimeb_a_ferocious_warboar_lt: WHERE id in (223008, 223155); # A_Ferocious_Warboar 71
UPDATE npc_types SET loottable_id = :potimeb_a_ferocious_war_boar_lt: WHERE id in (223117, 223143); # A_Ferocious_War_Boar 60
UPDATE npc_types SET loottable_id = :potimeb_a_fierce_war_boar_lt: WHERE id in (223139); # A_Fierce_War_Boar 64
UPDATE npc_types SET loottable_id = :potimeb_a_firebone_caster_lt: WHERE id in (223195); # A_Firebone_Caster 66
UPDATE npc_types SET loottable_id = :potimeb_a_fire_etched_doombringer_lt: WHERE id in (223114, 223137); # A_Fire_Etched_Doombringer 60
UPDATE npc_types SET loottable_id = :potimeb_a_flame_mephit_lt: WHERE id in (223089); # a_flame_mephit 64
UPDATE npc_types SET loottable_id = :potimeb_a_flame_mephit__lt: WHERE id in (223094); # a_flame_mephit_ 65
UPDATE npc_types SET loottable_id = :potimeb_a_gutripping_war_beast_lt: WHERE id in (223135); # A_Gutripping_War_Beast 60
UPDATE npc_types SET loottable_id = :potimeb_a_hatebringer_of_innoruuk_lt: WHERE id in (223232); # A_hatebringer_of_Innoruuk 70
UPDATE npc_types SET loottable_id = :potimeb_a_hobgoblin_servant_lt: WHERE id in (223061, 223062); # A_Hobgoblin_Servant 69
UPDATE npc_types SET loottable_id = :potimeb_a_minion_of_the_warlord_lt: WHERE id in (223048); # A_Minion_of_the_Warlord 70
UPDATE npc_types SET loottable_id = :potimeb_a_mouth_of_dementia_lt: WHERE id in (223084); # A_Mouth_of_Dementia 64
UPDATE npc_types SET loottable_id = :potimeb_a_mouth_of_insanity_lt: WHERE id in (223083); # A_Mouth_of_Insanity 64
UPDATE npc_types SET loottable_id = :potimeb_a_needletusk_warboar_lt: WHERE id in (223010, 223047); # A_Needletusk_Warboar 71
UPDATE npc_types SET loottable_id = :potimeb_a_nightmare_knight_of_terris_lt: WHERE id in (223082); # A_Nightmare_Knight_of_Terris 64
UPDATE npc_types SET loottable_id = :potimeb_a_phantasm_of_terris_lt: WHERE id in (223080); # A_Phantasm_of_Terris 64
UPDATE npc_types SET loottable_id = :potimeb_a_pig_of_war_lt: WHERE id in (223005); # A_Pig_of_War 67
UPDATE npc_types SET loottable_id = :potimeb_a_pile_of_living_rubble_lt: WHERE id in (223106); # a_pile_of_living_rubble 65
UPDATE npc_types SET loottable_id = :potimeb_a_rock_shaped_assassin_lt: WHERE id in (223147); # a_rock_shaped_assassin 64
UPDATE npc_types SET loottable_id = :potimeb_a_smoldering_elemental_lt: WHERE id in (223109, 223124); # A_Smoldering_Elemental 60
UPDATE npc_types SET loottable_id = :potimeb_a_summoned_boar_lt: WHERE id in (223003); # a_summoned_boar 64
UPDATE npc_types SET loottable_id = :potimeb_a_summoned_boar__lt: WHERE id in (223230); # a_summoned_boar_ 64
UPDATE npc_types SET loottable_id = :potimeb_a_summoned_guardian_lt: WHERE id in (223131); # a_summoned_guardian 66
UPDATE npc_types SET loottable_id = :potimeb_a_summoned_guardian_of_terris_lt: WHERE id in (223079); # A_Summoned_Guardian_of_Terris 64
UPDATE npc_types SET loottable_id = :potimeb_a_summoned_knight_of_terris_lt: WHERE id in (223081); # A_Summoned_Knight_of_Terris 64
UPDATE npc_types SET loottable_id = :potimeb_a_summoned_minion_lt: WHERE id in (223002); # a_summoned_minion 64
UPDATE npc_types SET loottable_id = :potimeb_a_summoned_minion__lt: WHERE id in (223229); # a_summoned_minion_ 64
UPDATE npc_types SET loottable_id = :potimeb_a_time_vortex_lt: WHERE id in (223112); # a_time_vortex 68
UPDATE npc_types SET loottable_id = :potimeb_a_tormentor_lt: WHERE id in (223085); # A_Tormentor 64
UPDATE npc_types SET loottable_id = :potimeb_a_triloun_gatherer_lt: WHERE id in (223092, 223093); # a_triloun_gatherer 64
UPDATE npc_types SET loottable_id = :potimeb_a_twisted_tormentor_lt: WHERE id in (223086); # A_Twisted_Tormentor 64
UPDATE npc_types SET loottable_id = :potimeb_a_warboar_of_suffering_lt: WHERE id in (223049); # A_warboar_of_suffering 70
UPDATE npc_types SET loottable_id = :potimeb_a_warlord_of_zek_lt: WHERE id in (223033); # A_Warlord_of_Zek 68
UPDATE npc_types SET loottable_id = :potimeb_a_war_shapen_emissary_lt: WHERE id in (223140); # A_War_Shapen_Emissary 60
UPDATE npc_types SET loottable_id = :potimeb_a_watercrafted_hunter_lt: WHERE id in (223148, 223153); # A_Watercrafted_Hunter 65
UPDATE npc_types SET loottable_id = :potimeb_a_windshapen_warlord_of_air_lt: WHERE id in (223144); # A_Windshapen_Warlord_of_Air 75
UPDATE npc_types SET loottable_id = :potimeb_a_zek_bloodtusk_lt: WHERE id in (223035); # A_Zek_Bloodtusk 68
UPDATE npc_types SET loottable_id = :potimeb_battlemaster_of_the_faceless_lt: WHERE id in (223039); # Battlemaster_of_the_Faceless 68
UPDATE npc_types SET loottable_id = :potimeb_bertoxxulous_lt: WHERE id in (223098); # Bertoxxulous 1
UPDATE npc_types SET loottable_id = :potimeb_cazic_thule_lt: WHERE id in (223165); # Cazic_Thule 1
UPDATE npc_types SET loottable_id = :potimeb_champion_of_korascian_lt: WHERE id in (223099, 223123); # Champion_of_Korascian 66
UPDATE npc_types SET loottable_id = :potimeb_champion_of_torment_lt: WHERE id in (223019, 223065); # Champion_of_Torment 71
UPDATE npc_types SET loottable_id = :potimeb_champion_of_war_lt: WHERE id in (223007); # Champion_of_War 67
UPDATE npc_types SET loottable_id = :potimeb_cleric_of_innoruuk_lt: WHERE id in (223197); # Cleric_of_Innoruuk 66
UPDATE npc_types SET loottable_id = :potimeb_cutthroat_of_saryrn_lt: WHERE id in (223068); # Cutthroat_of_Saryrn 68
UPDATE npc_types SET loottable_id = :potimeb_dark_knight_of_saryrn_lt: WHERE id in (223069); # Dark_Knight_of_Saryrn 70
UPDATE npc_types SET loottable_id = :potimeb_dark_knight_of_terris_lt: WHERE id in (223020, 223058); # Dark_Knight_of_Terris 71
UPDATE npc_types SET loottable_id = :potimeb_dark_priest_of_innoruuk_lt: WHERE id in (223055, 223056); # Dark_Priest_of_Innoruuk 68
UPDATE npc_types SET loottable_id = :potimeb_deathbringer_blackheart_lt: WHERE id in (223009, 223156); # Deathbringer_Blackheart 71
UPDATE npc_types SET loottable_id = :potimeb_deathbringer_rianit_lt: WHERE id in (223011, 223046); # Deathbringer_Rianit 71
UPDATE npc_types SET loottable_id = :potimeb_deathbringer_skullsmash_lt: WHERE id in (223023, 223031); # Deathbringer_Skullsmash 71
UPDATE npc_types SET loottable_id = :potimeb_dersool_falgiersnaol_lt: WHERE id in (223015, 223050); # Dersool_Fal`Giersnaol 71
UPDATE npc_types SET loottable_id = :potimeb_doombringer_of_saryrn_lt: WHERE id in (223072); # Doombringer_of_Saryrn 69
UPDATE npc_types SET loottable_id = :potimeb_dreamwarp_lt: WHERE id in (223018, 223066); # Dreamwarp 71
UPDATE npc_types SET loottable_id = :potimeb_druzzil_ro_lt: WHERE id in (223213); # Druzzil_Ro 99
UPDATE npc_types SET loottable_id = :potimeb_earthen_overseer_lt: WHERE id in (223134); # Earthen_Overseer 67
UPDATE npc_types SET loottable_id = :potimeb_footman_of_the_plaguebringer_lt: WHERE id in (223028); # Footman_of_the_Plaguebringer 68
UPDATE npc_types SET loottable_id = :potimeb_guardian_knight_of_pestilence_lt: WHERE id in (223196); # Guardian_Knight_of_Pestilence 66
UPDATE npc_types SET loottable_id = :potimeb_guardian_of_the_crypt_lt: WHERE id in (223194); # Guardian_of_the_Crypt 66
UPDATE npc_types SET loottable_id = :potimeb_guardian_of_the_dark_prince_lt: WHERE id in (223231); # guardian_of_the_dark_prince 70
UPDATE npc_types SET loottable_id = :potimeb_gutripping_war_beast_lt: WHERE id in (223146); # Gutripping_War_Beast 67
UPDATE npc_types SET loottable_id = :potimeb_herlsoakian_lt: WHERE id in (223013, 223037); # Herlsoakian 71
UPDATE npc_types SET loottable_id = :potimeb_incantator_of_the_plaguebringer_lt: WHERE id in (223026); # Incantator_of_the_Plaguebringer 67
UPDATE npc_types SET loottable_id = :potimeb_innoruuk_lt: WHERE id in (223000); # Innoruuk 1
UPDATE npc_types SET loottable_id = :potimeb_kazrok_of_fire_lt: WHERE id in (223090); # Kazrok_of_Fire 66
UPDATE npc_types SET loottable_id = :potimeb_knight_of_nightmare_lt: WHERE id in (223063, 223064); # Knight_of_Nightmare 68
UPDATE npc_types SET loottable_id = :potimeb_kraksmaal_firdethsin_lt: WHERE id in (223017, 223024); # Kraksmaal_Fir`Dethsin 71
UPDATE npc_types SET loottable_id = :potimeb_lumber_event_guy_lt: WHERE id in (223113); # Lumber_Event_Guy 60
UPDATE npc_types SET loottable_id = :potimeb_neimon_of_air_lt: WHERE id in (223120); # Neimon_of_Air 68
UPDATE npc_types SET loottable_id = :potimeb_nightwalker_of_hate_lt: WHERE id in (223053, 223054); # Nightwalker_of_Hate 69
UPDATE npc_types SET loottable_id = :potimeb_phase_one_air_lt: WHERE id in (223170); # phase_one_air 80
UPDATE npc_types SET loottable_id = :potimeb_phase_one_earth_lt: WHERE id in (223169); # phase_one_earth 80
UPDATE npc_types SET loottable_id = :potimeb_phase_one_fire_lt: WHERE id in (223173); # phase_one_fire 80
UPDATE npc_types SET loottable_id = :potimeb_phase_one_undead_lt: WHERE id in (223171); # phase_one_undead 80
UPDATE npc_types SET loottable_id = :potimeb_phase_one_water_lt: WHERE id in (223172); # phase_one_water 80
UPDATE npc_types SET loottable_id = :potimeb_phoboplasm_lt: WHERE id in (223200); # phoboplasm 71
UPDATE npc_types SET loottable_id = :potimeb_quarm_lt: WHERE id in (223201); # Quarm 80
UPDATE npc_types SET loottable_id = :potimeb_rallos_zek_lt: WHERE id in (223001); # Rallos_Zek 1
UPDATE npc_types SET loottable_id = :potimeb_ralthos_enrok_lt: WHERE id in (223127); # Ralthos_Enrok 69
UPDATE npc_types SET loottable_id = :potimeb_revenant_of_the_plaguebringer_lt: WHERE id in (223029, 223030); # Revenant_of_the_Plaguebringer 68
UPDATE npc_types SET loottable_id = :potimeb_reverse_lumber_event_guy_lt: WHERE id in (223151); # Reverse_Lumber_Event_Guy 60
UPDATE npc_types SET loottable_id = :potimeb_rythor_of_the_undead_lt: WHERE id in (223129, 223152); # Rythor_of_the_Undead 68
UPDATE npc_types SET loottable_id = :potimeb_saryrn_lt: WHERE id in (223076); # Saryrn 71
UPDATE npc_types SET loottable_id = :potimeb_servitor_of_xegony_lt: WHERE id in (223111); # Servitor_of_Xegony 66
UPDATE npc_types SET loottable_id = :potimeb_servitor_of_xegony__lt: WHERE id in (223216); # Servitor_of_Xegony_ 66
UPDATE npc_types SET loottable_id = :potimeb_shadow_of_anar_lt: WHERE id in (223091); # Shadow_of_Anar 68
UPDATE npc_types SET loottable_id = :potimeb_sinrunal_gorgedreal_lt: WHERE id in (223012, 223038); # Sinrunal_Gorgedreal 71
UPDATE npc_types SET loottable_id = :potimeb_supernatural_guardian_lt: WHERE id in (223074); # Supernatural_Guardian 72
UPDATE npc_types SET loottable_id = :potimeb_tallon_zek_lt: WHERE id in (223077); # Tallon_Zek 71
UPDATE npc_types SET loottable_id = :potimeb_templar_of_saryrn_lt: WHERE id in (223071); # Templar_of_Saryrn 69
UPDATE npc_types SET loottable_id = :potimeb_terlok_of_earth_lt: WHERE id in (223119); # Terlok_of_Earth 68
UPDATE npc_types SET loottable_id = :potimeb_terris_thule_lt: WHERE id in (223075); # Terris_Thule 71
UPDATE npc_types SET loottable_id = :potimeb_thaumathurgist_of_saryrn_lt: WHERE id in (223070); # Thaumathurgist_of_Saryrn 67
UPDATE npc_types SET loottable_id = :potimeb_undead_pawn_of_terris_lt: WHERE id in (223059, 223060); # Undead_Pawn_of_Terris 67
UPDATE npc_types SET loottable_id = :potimeb_undead_squad_leader_lt: WHERE id in (223021, 223057); # Undead_Squad_Leader 71
UPDATE npc_types SET loottable_id = :potimeb_vallon_zek_lt: WHERE id in (223078); # Vallon_Zek 71
UPDATE npc_types SET loottable_id = :potimeb_vanquisher_of_the_faceless_lt: WHERE id in (223040, 223041); # Vanquisher_of_the_Faceless 68
UPDATE npc_types SET loottable_id = :potimeb_warbeast_of_saryrn_lt: WHERE id in (223067); # Warbeast_of_Saryrn 68
UPDATE npc_types SET loottable_id = :potimeb_war_shapen_emissary_lt: WHERE id in (223096); # War_Shapen_Emissary 67
UPDATE npc_types SET loottable_id = :potimeb_windshapen_warlord_of_air_lt: WHERE id in (223118); # Windshapen_Warlord_of_Air 67
UPDATE npc_types SET loottable_id = :potimeb_xeroan_xigeruonask_lt: WHERE id in (223016, 223025); # Xeroan_Xi`Geruonask 71
UPDATE npc_types SET loottable_id = :potimeb_xerskel_gerodnsal_lt: WHERE id in (223014, 223051); # Xerskel_Gerodnsal 71
UPDATE npc_types SET loottable_id = :potimeb_zebuxoruk_lt: WHERE id in (223212); # Zebuxoruk 99
UPDATE npc_types SET loottable_id = :potimeb_zone_emoter_lt: WHERE id in (223227); # zone_emoter 80
UPDATE npc_types SET loottable_id = :potimeb_zone_status_lt: WHERE id in (223097); # zone_status 80
UPDATE npc_types SET loottable_id = :potimeb___lt: WHERE id in (223214, 223228); # _ 75
