INSERT INTO loottable(name) VALUES('potorment_a_bruised_woman'); # :potorment_a_bruised_woman_lt:
INSERT INTO loottable(name) VALUES('potorment_a_pain_devourer'); # :potorment_a_pain_devourer_lt:
INSERT INTO loottable(name) VALUES('potorment_a_sorrow_seeker'); # :potorment_a_sorrow_seeker_lt:
INSERT INTO loottable(name) VALUES('potorment_a_twisted_crawler'); # :potorment_a_twisted_crawler_lt:
INSERT INTO loottable(name) VALUES('potorment_baraguj_szuul'); # :potorment_baraguj_szuul_lt:
INSERT INTO loottable(name) VALUES('potorment_metala_von_korach'); # :potorment_metala_von_korach_lt:
INSERT INTO loottable(name) VALUES('potorment_sorrowsong'); # :potorment_sorrowsong_lt:
INSERT INTO loottable(name) VALUES('potorment_the_avatar_of_agony'); # :potorment_the_avatar_of_agony_lt:
INSERT INTO loottable(name) VALUES('potorment_the_avatar_of_anguish'); # :potorment_the_avatar_of_anguish_lt:
INSERT INTO loottable(name) VALUES('potorment_the_avatar_of_pain'); # :potorment_the_avatar_of_pain_lt:
INSERT INTO loottable(name) VALUES('potorment_the_avatar_of_suffering'); # :potorment_the_avatar_of_suffering_lt:
INSERT INTO loottable(name) VALUES('potorment_tylis_newleaf'); # :potorment_tylis_newleaf_lt:
INSERT INTO loottable(name) VALUES('potorment_an_acidic_mist'); # :potorment_an_acidic_mist_lt:
INSERT INTO loottable(name) VALUES('potorment_an_acolyte_of_pain'); # :potorment_an_acolyte_of_pain_lt:
INSERT INTO loottable(name) VALUES('potorment_an_unimaginable_horror'); # :potorment_an_unimaginable_horror_lt:
INSERT INTO loottable(name) VALUES('potorment_an_unseen_entity'); # :potorment_an_unseen_entity_lt:
INSERT INTO loottable(name) VALUES('potorment_a_blood_raven'); # :potorment_a_blood_raven_lt:
INSERT INTO loottable(name) VALUES('potorment_a_blood_raven_hatchling'); # :potorment_a_blood_raven_hatchling_lt:
INSERT INTO loottable(name) VALUES('potorment_a_blood_soaked_guard'); # :potorment_a_blood_soaked_guard_lt:
INSERT INTO loottable(name) VALUES('potorment_a_blurry_image'); # :potorment_a_blurry_image_lt:
INSERT INTO loottable(name) VALUES('potorment_a_boruk_hunter'); # :potorment_a_boruk_hunter_lt:
INSERT INTO loottable(name) VALUES('potorment_a_boruk_lacerator'); # :potorment_a_boruk_lacerator_lt:
INSERT INTO loottable(name) VALUES('potorment_a_boruk_minion'); # :potorment_a_boruk_minion_lt:
INSERT INTO loottable(name) VALUES('potorment_a_boruk_painharvester'); # :potorment_a_boruk_painharvester_lt:
INSERT INTO loottable(name) VALUES('potorment_a_boruk_ravager'); # :potorment_a_boruk_ravager_lt:
INSERT INTO loottable(name) VALUES('potorment_a_boruk_skin_harvester'); # :potorment_a_boruk_skin_harvester_lt:
INSERT INTO loottable(name) VALUES('potorment_a_boruk_tormentor'); # :potorment_a_boruk_tormentor_lt:
INSERT INTO loottable(name) VALUES('potorment_a_boruk_torturer'); # :potorment_a_boruk_torturer_lt:
INSERT INTO loottable(name) VALUES('potorment_a_cloudy_image'); # :potorment_a_cloudy_image_lt:
INSERT INTO loottable(name) VALUES('potorment_a_construct_breeder'); # :potorment_a_construct_breeder_lt:
INSERT INTO loottable(name) VALUES('potorment_a_construct_harvester'); # :potorment_a_construct_harvester_lt:
INSERT INTO loottable(name) VALUES('potorment_a_construct_of_agony'); # :potorment_a_construct_of_agony_lt:
INSERT INTO loottable(name) VALUES('potorment_a_construct_of_anguish'); # :potorment_a_construct_of_anguish_lt:
INSERT INTO loottable(name) VALUES('potorment_a_construct_of_malevolence'); # :potorment_a_construct_of_malevolence_lt:
INSERT INTO loottable(name) VALUES('potorment_a_construct_of_pain'); # :potorment_a_construct_of_pain_lt:
INSERT INTO loottable(name) VALUES('potorment_a_construct_of_suffering'); # :potorment_a_construct_of_suffering_lt:
INSERT INTO loottable(name) VALUES('potorment_a_construct_seedling'); # :potorment_a_construct_seedling_lt:
INSERT INTO loottable(name) VALUES('potorment_a_faint_rattle'); # :potorment_a_faint_rattle_lt:
INSERT INTO loottable(name) VALUES('potorment_a_flayed_horror'); # :potorment_a_flayed_horror_lt:
INSERT INTO loottable(name) VALUES('potorment_a_glistening_blood_raven'); # :potorment_a_glistening_blood_raven_lt:
INSERT INTO loottable(name) VALUES('potorment_a_horrifying_vision'); # :potorment_a_horrifying_vision_lt:
INSERT INTO loottable(name) VALUES('potorment_a_kaniz_flayer'); # :potorment_a_kaniz_flayer_lt:
INSERT INTO loottable(name) VALUES('potorment_a_kaniz_hide_collector'); # :potorment_a_kaniz_hide_collector_lt:
INSERT INTO loottable(name) VALUES('potorment_a_kaniz_hopedefiler'); # :potorment_a_kaniz_hopedefiler_lt:
INSERT INTO loottable(name) VALUES('potorment_a_kaniz_hunter'); # :potorment_a_kaniz_hunter_lt:
INSERT INTO loottable(name) VALUES('potorment_a_kaniz_minion'); # :potorment_a_kaniz_minion_lt:
INSERT INTO loottable(name) VALUES('potorment_a_kaniz_ravager'); # :potorment_a_kaniz_ravager_lt:
INSERT INTO loottable(name) VALUES('potorment_a_kaniz_tormentor'); # :potorment_a_kaniz_tormentor_lt:
INSERT INTO loottable(name) VALUES('potorment_a_kaniz_torturer'); # :potorment_a_kaniz_torturer_lt:
INSERT INTO loottable(name) VALUES('potorment_a_minion_of_maareq'); # :potorment_a_minion_of_maareq_lt:
INSERT INTO loottable(name) VALUES('potorment_a_parylyx_hatchling'); # :potorment_a_parylyx_hatchling_lt:
INSERT INTO loottable(name) VALUES('potorment_a_parylyx_hookcaster'); # :potorment_a_parylyx_hookcaster_lt:
INSERT INTO loottable(name) VALUES('potorment_a_parylyx_limb_binder'); # :potorment_a_parylyx_limb_binder_lt:
INSERT INTO loottable(name) VALUES('potorment_a_parylyx_painweaver'); # :potorment_a_parylyx_painweaver_lt:
INSERT INTO loottable(name) VALUES('potorment_a_servant_of_saryrn'); # :potorment_a_servant_of_saryrn_lt:
INSERT INTO loottable(name) VALUES('potorment_a_skinless_creature'); # :potorment_a_skinless_creature_lt:
INSERT INTO loottable(name) VALUES('potorment_a_small_blood_raven'); # :potorment_a_small_blood_raven_lt:
INSERT INTO loottable(name) VALUES('potorment_a_summoned_servant'); # :potorment_a_summoned_servant_lt:
INSERT INTO loottable(name) VALUES('potorment_a_tormented_soul'); # :potorment_a_tormented_soul_lt:
INSERT INTO loottable(name) VALUES('potorment_a_twisted_crawler'); # :potorment_a_twisted_crawler_lt:
INSERT INTO loottable(name) VALUES('potorment_a_twisted_spirit'); # :potorment_a_twisted_spirit_lt:
INSERT INTO loottable(name) VALUES('potorment_a_warm'); # :potorment_a_warm_lt:
INSERT INTO loottable(name) VALUES('potorment_baraguj_szuul'); # :potorment_baraguj_szuul_lt:
INSERT INTO loottable(name) VALUES('potorment_dirge_malicia'); # :potorment_dirge_malicia_lt:
INSERT INTO loottable(name) VALUES('potorment_its_a_trap'); # :potorment_its_a_trap_lt:
INSERT INTO loottable(name) VALUES('potorment_kaniz_painbringer'); # :potorment_kaniz_painbringer_lt:
INSERT INTO loottable(name) VALUES('potorment_maareq_the_prophet'); # :potorment_maareq_the_prophet_lt:
INSERT INTO loottable(name) VALUES('potorment_mouth_trigger'); # :potorment_mouth_trigger_lt:
INSERT INTO loottable(name) VALUES('potorment_rotting_small_raven'); # :potorment_rotting_small_raven_lt:
INSERT INTO loottable(name) VALUES('potorment_salczek_the_fleshgrinder'); # :potorment_salczek_the_fleshgrinder_lt:
INSERT INTO loottable(name) VALUES('potorment_saryrn'); # :potorment_saryrn_lt:
INSERT INTO loottable(name) VALUES('potorment_something_dark'); # :potorment_something_dark_lt:
INSERT INTO loottable(name) VALUES('potorment_sorrowsong'); # :potorment_sorrowsong_lt:
INSERT INTO loottable(name) VALUES('potorment_tagrusch_the_abomination'); # :potorment_tagrusch_the_abomination_lt:
INSERT INTO loottable(name) VALUES('potorment_the_acolyte_of_affliction'); # :potorment_the_acolyte_of_affliction_lt:
INSERT INTO loottable(name) VALUES('potorment_the_keeper_of_sorrows'); # :potorment_the_keeper_of_sorrows_lt:
INSERT INTO loottable(name) VALUES('potorment_the_mouths_of_misery'); # :potorment_the_mouths_of_misery_lt:
INSERT INTO loottable(name) VALUES('potorment_the_shadows'); # :potorment_the_shadows_lt:
INSERT INTO loottable(name) VALUES('potorment_tylis_newleaf'); # :potorment_tylis_newleaf_lt:
INSERT INTO loottable(name) VALUES('potorment_tylis_newleaf_'); # :potorment_tylis_newleaf__lt:
