INSERT INTO loottable(name) VALUES('chardokb_a_rabid_chokidai_biter'); # :chardokb_a_rabid_chokidai_biter_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_rabid_chokidai_bleeder'); # :chardokb_a_rabid_chokidai_bleeder_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_rabid_chokidai_ripper'); # :chardokb_a_rabid_chokidai_ripper_lt:
INSERT INTO loottable(name) VALUES('chardokb_korucust'); # :chardokb_korucust_lt:
INSERT INTO loottable(name) VALUES('chardokb_an_iksar_skeleton'); # :chardokb_an_iksar_skeleton_lt:
INSERT INTO loottable(name) VALUES('chardokb_as_you'); # :chardokb_as_you_lt:
INSERT INTO loottable(name) VALUES('chardokb_as_you_enter'); # :chardokb_as_you_enter_lt:
INSERT INTO loottable(name) VALUES('chardokb_as_you_look'); # :chardokb_as_you_look_lt:
INSERT INTO loottable(name) VALUES('chardokb_as_you_pass'); # :chardokb_as_you_pass_lt:
INSERT INTO loottable(name) VALUES('chardokb_as_you_push'); # :chardokb_as_you_push_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_domesticated_chokidai'); # :chardokb_a_domesticated_chokidai_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_ferocious_chokidai'); # :chardokb_a_ferocious_chokidai_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_ghostly_sacrifice'); # :chardokb_a_ghostly_sacrifice_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_ghostly_servant'); # :chardokb_a_ghostly_servant_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_leprous_chokidai'); # :chardokb_a_leprous_chokidai_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_massive_construct'); # :chardokb_a_massive_construct_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_reanimated_sarnak'); # :chardokb_a_reanimated_sarnak_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_resurrected_sarnak'); # :chardokb_a_resurrected_sarnak_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_revived_sarnak'); # :chardokb_a_revived_sarnak_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_royal_sanctuary_guard'); # :chardokb_a_royal_sanctuary_guard_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_sarnak_construct'); # :chardokb_a_sarnak_construct_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_sarnak_ghost'); # :chardokb_a_sarnak_ghost_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_sarnak_haunt'); # :chardokb_a_sarnak_haunt_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_sarnak_resurrectionist'); # :chardokb_a_sarnak_resurrectionist_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_savage_chokidai'); # :chardokb_a_savage_chokidai_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_shaidin_overseer'); # :chardokb_a_shaidin_overseer_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_shaidin_royal_guard'); # :chardokb_a_shaidin_royal_guard_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_shaidin_scythemaster'); # :chardokb_a_shaidin_scythemaster_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_spectral_betrayer'); # :chardokb_a_spectral_betrayer_lt:
INSERT INTO loottable(name) VALUES('chardokb_a_vicious_chokidai'); # :chardokb_a_vicious_chokidai_lt:
INSERT INTO loottable(name) VALUES('chardokb_baelin_xirrixoan'); # :chardokb_baelin_xirrixoan_lt:
INSERT INTO loottable(name) VALUES('chardokb_brodisek_ashkansek'); # :chardokb_brodisek_ashkansek_lt:
INSERT INTO loottable(name) VALUES('chardokb_hooks'); # :chardokb_hooks_lt:
INSERT INTO loottable(name) VALUES('chardokb_krizznot_bonewalker'); # :chardokb_krizznot_bonewalker_lt:
INSERT INTO loottable(name) VALUES('chardokb_many'); # :chardokb_many_lt:
INSERT INTO loottable(name) VALUES('chardokb_palardiag_daxkunoksan'); # :chardokb_palardiag_daxkunoksan_lt:
INSERT INTO loottable(name) VALUES('chardokb_sarnak_armorer'); # :chardokb_sarnak_armorer_lt:
INSERT INTO loottable(name) VALUES('chardokb_sarnak_champion'); # :chardokb_sarnak_champion_lt:
INSERT INTO loottable(name) VALUES('chardokb_sarnak_weaponsmith'); # :chardokb_sarnak_weaponsmith_lt:
INSERT INTO loottable(name) VALUES('chardokb_silzok_foizarth'); # :chardokb_silzok_foizarth_lt:
INSERT INTO loottable(name) VALUES('chardokb_silzoks_golem'); # :chardokb_silzoks_golem_lt:
INSERT INTO loottable(name) VALUES('chardokb_valinion_vizdaron'); # :chardokb_valinion_vizdaron_lt:
INSERT INTO loottable(name) VALUES('chardokb_your_feet'); # :chardokb_your_feet_lt:
INSERT INTO loottable(name) VALUES('chardokb_you_come'); # :chardokb_you_come_lt:
INSERT INTO loottable(name) VALUES('chardokb_you_struggle'); # :chardokb_you_struggle_lt:
INSERT INTO loottable(name) VALUES('chardokb__'); # :chardokb___lt:
