INSERT INTO loottable(name) VALUES('nadox_an_exhausted_bloodtusk'); # :nadox_an_exhausted_bloodtusk_lt:
INSERT INTO loottable(name) VALUES('nadox_an_undead_weaponsmith'); # :nadox_an_undead_weaponsmith_lt:
INSERT INTO loottable(name) VALUES('nadox_a_blackhand_guardian'); # :nadox_a_blackhand_guardian_lt:
INSERT INTO loottable(name) VALUES('nadox_a_blackhand_lieutenant'); # :nadox_a_blackhand_lieutenant_lt:
INSERT INTO loottable(name) VALUES('nadox_a_blackhand_veteran'); # :nadox_a_blackhand_veteran_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_peer'); # :nadox_a_broken_skull_peer_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_prophet'); # :nadox_a_broken_skull_prophet_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_vassal'); # :nadox_a_broken_skull_vassal_lt:
INSERT INTO loottable(name) VALUES('nadox_a_cloister_sentinel'); # :nadox_a_cloister_sentinel_lt:
INSERT INTO loottable(name) VALUES('nadox_a_decaying_fisherman'); # :nadox_a_decaying_fisherman_lt:
INSERT INTO loottable(name) VALUES('nadox_a_furious_blackhand'); # :nadox_a_furious_blackhand_lt:
INSERT INTO loottable(name) VALUES('nadox_a_lava_etched_doombringer'); # :nadox_a_lava_etched_doombringer_lt:
INSERT INTO loottable(name) VALUES('nadox_a_trench_master'); # :nadox_a_trench_master_lt:
INSERT INTO loottable(name) VALUES('nadox_bloodspear_the_fallen'); # :nadox_bloodspear_the_fallen_lt:
INSERT INTO loottable(name) VALUES('nadox_bloodspear_the_wretched'); # :nadox_bloodspear_the_wretched_lt:
INSERT INTO loottable(name) VALUES('nadox_captain_aivilo'); # :nadox_captain_aivilo_lt:
INSERT INTO loottable(name) VALUES('nadox_captain_krakskull'); # :nadox_captain_krakskull_lt:
INSERT INTO loottable(name) VALUES('nadox_crew_chief_hanriesaf'); # :nadox_crew_chief_hanriesaf_lt:
INSERT INTO loottable(name) VALUES('nadox_dulein_gedasai'); # :nadox_dulein_gedasai_lt:
INSERT INTO loottable(name) VALUES('nadox_elder_shaman_elgruk'); # :nadox_elder_shaman_elgruk_lt:
INSERT INTO loottable(name) VALUES('nadox_first_mate_bresanev'); # :nadox_first_mate_bresanev_lt:
INSERT INTO loottable(name) VALUES('nadox_foreman_kraksanar'); # :nadox_foreman_kraksanar_lt:
INSERT INTO loottable(name) VALUES('nadox_garodizan_razorfin'); # :nadox_garodizan_razorfin_lt:
INSERT INTO loottable(name) VALUES('nadox_grand_spiritist_lokfan'); # :nadox_grand_spiritist_lokfan_lt:
INSERT INTO loottable(name) VALUES('nadox_high_priest_bloodspear'); # :nadox_high_priest_bloodspear_lt:
INSERT INTO loottable(name) VALUES('nadox_high_priest_grumsalot'); # :nadox_high_priest_grumsalot_lt:
INSERT INTO loottable(name) VALUES('nadox_innoruuk'); # :nadox_innoruuk_lt:
INSERT INTO loottable(name) VALUES('nadox_karsonizzak_bloodblade'); # :nadox_karsonizzak_bloodblade_lt:
INSERT INTO loottable(name) VALUES('nadox_kdansol_borgir'); # :nadox_kdansol_borgir_lt:
INSERT INTO loottable(name) VALUES('nadox_kraska_mreth'); # :nadox_kraska_mreth_lt:
INSERT INTO loottable(name) VALUES('nadox_mine_cart'); # :nadox_mine_cart_lt:
INSERT INTO loottable(name) VALUES('nadox_spiritcharmer_hargortaz'); # :nadox_spiritcharmer_hargortaz_lt:
INSERT INTO loottable(name) VALUES('nadox_spiritseeker_nadox'); # :nadox_spiritseeker_nadox_lt:
INSERT INTO loottable(name) VALUES('nadox_tarsos_fis_zaaksen'); # :nadox_tarsos_fis_zaaksen_lt:
INSERT INTO loottable(name) VALUES('nadox_the_luggald_broodmother'); # :nadox_the_luggald_broodmother_lt:
INSERT INTO loottable(name) VALUES('nadox_an_abhorrent_element'); # :nadox_an_abhorrent_element_lt:
INSERT INTO loottable(name) VALUES('nadox_an_animated_mercenary'); # :nadox_an_animated_mercenary_lt:
INSERT INTO loottable(name) VALUES('nadox_an_exhausted_miner'); # :nadox_an_exhausted_miner_lt:
INSERT INTO loottable(name) VALUES('nadox_an_exhausted_prophet'); # :nadox_an_exhausted_prophet_lt:
INSERT INTO loottable(name) VALUES('nadox_an_incubator_operator'); # :nadox_an_incubator_operator_lt:
INSERT INTO loottable(name) VALUES('nadox_an_unrestful_acolyte'); # :nadox_an_unrestful_acolyte_lt:
INSERT INTO loottable(name) VALUES('nadox_a_blackblood_prophet'); # :nadox_a_blackblood_prophet_lt:
INSERT INTO loottable(name) VALUES('nadox_a_blackhand_guardian'); # :nadox_a_blackhand_guardian_lt:
INSERT INTO loottable(name) VALUES('nadox_a_bloodtusk_beast'); # :nadox_a_bloodtusk_beast_lt:
INSERT INTO loottable(name) VALUES('nadox_a_bloodtusk_boar'); # :nadox_a_bloodtusk_boar_lt:
INSERT INTO loottable(name) VALUES('nadox_a_bloodtusk_swine'); # :nadox_a_bloodtusk_swine_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_acolyte'); # :nadox_a_broken_skull_acolyte_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_adherent'); # :nadox_a_broken_skull_adherent_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_advocate'); # :nadox_a_broken_skull_advocate_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_anchorite'); # :nadox_a_broken_skull_anchorite_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_cenobite'); # :nadox_a_broken_skull_cenobite_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_initiate'); # :nadox_a_broken_skull_initiate_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_proselyte'); # :nadox_a_broken_skull_proselyte_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_seeker'); # :nadox_a_broken_skull_seeker_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_seer'); # :nadox_a_broken_skull_seer_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_spiritist'); # :nadox_a_broken_skull_spiritist_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_sycophant'); # :nadox_a_broken_skull_sycophant_lt:
INSERT INTO loottable(name) VALUES('nadox_a_broken_skull_theurgist'); # :nadox_a_broken_skull_theurgist_lt:
INSERT INTO loottable(name) VALUES('nadox_a_burdened_bloodtusk'); # :nadox_a_burdened_bloodtusk_lt:
INSERT INTO loottable(name) VALUES('nadox_a_cathedral_protector'); # :nadox_a_cathedral_protector_lt:
INSERT INTO loottable(name) VALUES('nadox_a_chosen_of_innoruuk'); # :nadox_a_chosen_of_innoruuk_lt:
INSERT INTO loottable(name) VALUES('nadox_a_conscript_of_innoruuk'); # :nadox_a_conscript_of_innoruuk_lt:
INSERT INTO loottable(name) VALUES('nadox_a_drenched_crewman'); # :nadox_a_drenched_crewman_lt:
INSERT INTO loottable(name) VALUES('nadox_a_furious_blackhand'); # :nadox_a_furious_blackhand_lt:
INSERT INTO loottable(name) VALUES('nadox_a_luggald_abomination'); # :nadox_a_luggald_abomination_lt:
INSERT INTO loottable(name) VALUES('nadox_a_luggald_ambassador'); # :nadox_a_luggald_ambassador_lt:
INSERT INTO loottable(name) VALUES('nadox_a_luggald_apprentice'); # :nadox_a_luggald_apprentice_lt:
INSERT INTO loottable(name) VALUES('nadox_a_luggald_archseeker'); # :nadox_a_luggald_archseeker_lt:
INSERT INTO loottable(name) VALUES('nadox_a_luggald_chosen'); # :nadox_a_luggald_chosen_lt:
INSERT INTO loottable(name) VALUES('nadox_a_luggald_guardian'); # :nadox_a_luggald_guardian_lt:
INSERT INTO loottable(name) VALUES('nadox_a_luggald_high_priest'); # :nadox_a_luggald_high_priest_lt:
INSERT INTO loottable(name) VALUES('nadox_a_luggald_initiate'); # :nadox_a_luggald_initiate_lt:
INSERT INTO loottable(name) VALUES('nadox_a_luggald_overseer'); # :nadox_a_luggald_overseer_lt:
INSERT INTO loottable(name) VALUES('nadox_a_resting_acolyte'); # :nadox_a_resting_acolyte_lt:
INSERT INTO loottable(name) VALUES('nadox_a_rotting_seafarer'); # :nadox_a_rotting_seafarer_lt:
INSERT INTO loottable(name) VALUES('nadox_a_sanctuary_sentinel'); # :nadox_a_sanctuary_sentinel_lt:
INSERT INTO loottable(name) VALUES('nadox_a_sanctum_sentinel'); # :nadox_a_sanctum_sentinel_lt:
INSERT INTO loottable(name) VALUES('nadox_a_scorned_element'); # :nadox_a_scorned_element_lt:
INSERT INTO loottable(name) VALUES('nadox_a_shady_merchant'); # :nadox_a_shady_merchant_lt:
INSERT INTO loottable(name) VALUES('nadox_a_shady_smuggler'); # :nadox_a_shady_smuggler_lt:
INSERT INTO loottable(name) VALUES('nadox_a_shrine_bruiser'); # :nadox_a_shrine_bruiser_lt:
INSERT INTO loottable(name) VALUES('nadox_a_soaked_crewman'); # :nadox_a_soaked_crewman_lt:
INSERT INTO loottable(name) VALUES('nadox_a_sodden_crewman'); # :nadox_a_sodden_crewman_lt:
INSERT INTO loottable(name) VALUES('nadox_a_soot_covered_miner'); # :nadox_a_soot_covered_miner_lt:
INSERT INTO loottable(name) VALUES('nadox_a_treasure_sorter'); # :nadox_a_treasure_sorter_lt:
INSERT INTO loottable(name) VALUES('nadox_a_troll_dredge'); # :nadox_a_troll_dredge_lt:
INSERT INTO loottable(name) VALUES('nadox_a_troll_excavator'); # :nadox_a_troll_excavator_lt:
INSERT INTO loottable(name) VALUES('nadox_a_troll_quarrier'); # :nadox_a_troll_quarrier_lt:
INSERT INTO loottable(name) VALUES('nadox_a_troll_tunneler'); # :nadox_a_troll_tunneler_lt:
INSERT INTO loottable(name) VALUES('nadox_a_vehement_blackhand'); # :nadox_a_vehement_blackhand_lt:
INSERT INTO loottable(name) VALUES('nadox_a_war_torn_spirit'); # :nadox_a_war_torn_spirit_lt:
INSERT INTO loottable(name) VALUES('nadox_a_waterlogged_crewman'); # :nadox_a_waterlogged_crewman_lt:
INSERT INTO loottable(name) VALUES('nadox_a_waterlogged_stockman'); # :nadox_a_waterlogged_stockman_lt:
INSERT INTO loottable(name) VALUES('nadox_a_water_torn_crewman'); # :nadox_a_water_torn_crewman_lt:
INSERT INTO loottable(name) VALUES('nadox_a_wretched_servant'); # :nadox_a_wretched_servant_lt:
INSERT INTO loottable(name) VALUES('nadox_defender_of_the_broodmother'); # :nadox_defender_of_the_broodmother_lt:
INSERT INTO loottable(name) VALUES('nadox_high_priest_bloodspear'); # :nadox_high_priest_bloodspear_lt:
INSERT INTO loottable(name) VALUES('nadox_karsonizzak_bloodblade'); # :nadox_karsonizzak_bloodblade_lt:
INSERT INTO loottable(name) VALUES('nadox_the_luggald_broodmother'); # :nadox_the_luggald_broodmother_lt:
INSERT INTO loottable(name) VALUES('nadox__'); # :nadox___lt:
