INSERT INTO loottable(name) VALUES('soldungc_culthor_spells'); # :soldungc_culthor_spells_lt:
INSERT INTO loottable(name) VALUES('soldungc_culthor_the_gatekeeper'); # :soldungc_culthor_the_gatekeeper_lt:
INSERT INTO loottable(name) VALUES('soldungc_elemental_reset'); # :soldungc_elemental_reset_lt:
INSERT INTO loottable(name) VALUES('soldungc_fireback_counter'); # :soldungc_fireback_counter_lt:
INSERT INTO loottable(name) VALUES('soldungc_fireback_queen'); # :soldungc_fireback_queen_lt:
INSERT INTO loottable(name) VALUES('soldungc_fireback_trigger'); # :soldungc_fireback_trigger_lt:
INSERT INTO loottable(name) VALUES('soldungc_ghaib_zilal'); # :soldungc_ghaib_zilal_lt:
INSERT INTO loottable(name) VALUES('soldungc_gigantic_ashwalker'); # :soldungc_gigantic_ashwalker_lt:
INSERT INTO loottable(name) VALUES('soldungc_gwaddry_aethadoc'); # :soldungc_gwaddry_aethadoc_lt:
INSERT INTO loottable(name) VALUES('soldungc_hunter_gitog'); # :soldungc_hunter_gitog_lt:
INSERT INTO loottable(name) VALUES('soldungc_kiliki'); # :soldungc_kiliki_lt:
INSERT INTO loottable(name) VALUES('soldungc_lava_champion'); # :soldungc_lava_champion_lt:
INSERT INTO loottable(name) VALUES('soldungc_lava_construct'); # :soldungc_lava_construct_lt:
INSERT INTO loottable(name) VALUES('soldungc_lava_vindicator'); # :soldungc_lava_vindicator_lt:
INSERT INTO loottable(name) VALUES('soldungc_pulsating_pool_of_magma'); # :soldungc_pulsating_pool_of_magma_lt:
INSERT INTO loottable(name) VALUES('soldungc_servant_of_flame'); # :soldungc_servant_of_flame_lt:
INSERT INTO loottable(name) VALUES('soldungc_smoldering_tentacle_terror'); # :soldungc_smoldering_tentacle_terror_lt:
INSERT INTO loottable(name) VALUES('soldungc_typhoeus'); # :soldungc_typhoeus_lt:
INSERT INTO loottable(name) VALUES('soldungc_xaon_bulzekel'); # :soldungc_xaon_bulzekel_lt:
INSERT INTO loottable(name) VALUES('soldungc_an_inflamed_champion'); # :soldungc_an_inflamed_champion_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_blistering_horror'); # :soldungc_a_blistering_horror_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_brain_scorched_goblin'); # :soldungc_a_brain_scorched_goblin_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_burning_mire'); # :soldungc_a_burning_mire_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_cavernous_crawler'); # :soldungc_a_cavernous_crawler_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_chest'); # :soldungc_a_chest_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_cinder_scavenger'); # :soldungc_a_cinder_scavenger_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_conflagarant_terror'); # :soldungc_a_conflagarant_terror_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_fiendish_guardian'); # :soldungc_a_fiendish_guardian_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_fireback_spiderling'); # :soldungc_a_fireback_spiderling_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_fireback_widow'); # :soldungc_a_fireback_widow_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_fireborn_master'); # :soldungc_a_fireborn_master_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_fireborn_outcast'); # :soldungc_a_fireborn_outcast_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_fireborn_wanderer'); # :soldungc_a_fireborn_wanderer_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_firevenom_crawler'); # :soldungc_a_firevenom_crawler_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_fire_giant_magus'); # :soldungc_a_fire_giant_magus_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_fire_giant_soothsayer'); # :soldungc_a_fire_giant_soothsayer_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_fire_giant_warlord'); # :soldungc_a_fire_giant_warlord_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_furious_magma_guardian'); # :soldungc_a_furious_magma_guardian_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_lavabite_spider'); # :soldungc_a_lavabite_spider_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_lava_beetle'); # :soldungc_a_lava_beetle_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_magma_ooze'); # :soldungc_a_magma_ooze_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_pool_of_living_lava'); # :soldungc_a_pool_of_living_lava_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_smoldering_abomination'); # :soldungc_a_smoldering_abomination_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_taklasinai_berserker'); # :soldungc_a_taklasinai_berserker_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_taklasinai_crusader'); # :soldungc_a_taklasinai_crusader_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_taklasinai_flamedancer'); # :soldungc_a_taklasinai_flamedancer_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_taklasinai_flamespitter'); # :soldungc_a_taklasinai_flamespitter_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_taklasinai_marauder'); # :soldungc_a_taklasinai_marauder_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_vrodak_bloodclaw'); # :soldungc_a_vrodak_bloodclaw_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_vrodak_firewalker'); # :soldungc_a_vrodak_firewalker_lt:
INSERT INTO loottable(name) VALUES('soldungc_a_vrodak_mystic'); # :soldungc_a_vrodak_mystic_lt:
INSERT INTO loottable(name) VALUES('soldungc_erpar_flamegar'); # :soldungc_erpar_flamegar_lt:
INSERT INTO loottable(name) VALUES('soldungc_fireback_queen'); # :soldungc_fireback_queen_lt:
INSERT INTO loottable(name) VALUES('soldungc_imp_defender'); # :soldungc_imp_defender_lt:
INSERT INTO loottable(name) VALUES('soldungc_imp_guardian'); # :soldungc_imp_guardian_lt:
INSERT INTO loottable(name) VALUES('soldungc_imp_vanquisher'); # :soldungc_imp_vanquisher_lt:
INSERT INTO loottable(name) VALUES('soldungc_kushara_perecran'); # :soldungc_kushara_perecran_lt:
INSERT INTO loottable(name) VALUES('soldungc_lava_champion'); # :soldungc_lava_champion_lt:
INSERT INTO loottable(name) VALUES('soldungc_lava_construct'); # :soldungc_lava_construct_lt:
INSERT INTO loottable(name) VALUES('soldungc_lava_vindicator'); # :soldungc_lava_vindicator_lt:
INSERT INTO loottable(name) VALUES('soldungc_protector_of_fire'); # :soldungc_protector_of_fire_lt:
INSERT INTO loottable(name) VALUES('soldungc_pure_flame_elemental'); # :soldungc_pure_flame_elemental_lt:
INSERT INTO loottable(name) VALUES('soldungc_spiritmaster_heili'); # :soldungc_spiritmaster_heili_lt:
INSERT INTO loottable(name) VALUES('soldungc_the_firewatcher'); # :soldungc_the_firewatcher_lt:
INSERT INTO loottable(name) VALUES('soldungc_tybog_adalmond'); # :soldungc_tybog_adalmond_lt:
INSERT INTO loottable(name) VALUES('soldungc__'); # :soldungc___lt:
