INSERT INTO loottable(name) VALUES('crystallos_squire_torrentus'); # :crystallos_squire_torrentus_lt:
INSERT INTO loottable(name) VALUES('crystallos_an_air_drake'); # :crystallos_an_air_drake_lt:
INSERT INTO loottable(name) VALUES('crystallos_an_earth_drake'); # :crystallos_an_earth_drake_lt:
INSERT INTO loottable(name) VALUES('crystallos_an_elder_earth_drake'); # :crystallos_an_elder_earth_drake_lt:
INSERT INTO loottable(name) VALUES('crystallos_an_elder_fire_drake'); # :crystallos_an_elder_fire_drake_lt:
INSERT INTO loottable(name) VALUES('crystallos_an_elder_fire_wyvern'); # :crystallos_an_elder_fire_wyvern_lt:
INSERT INTO loottable(name) VALUES('crystallos_an_elder_ice_wyvern'); # :crystallos_an_elder_ice_wyvern_lt:
INSERT INTO loottable(name) VALUES('crystallos_an_ice_drake'); # :crystallos_an_ice_drake_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_captive_elemental'); # :crystallos_a_captive_elemental_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_contained_elemental'); # :crystallos_a_contained_elemental_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_fire_drake'); # :crystallos_a_fire_drake_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_prismatic_champion'); # :crystallos_a_prismatic_champion_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_prismatic_evoker'); # :crystallos_a_prismatic_evoker_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_prismatic_lifebringer'); # :crystallos_a_prismatic_lifebringer_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_prismatic_overlord'); # :crystallos_a_prismatic_overlord_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_prismatic_wyvern'); # :crystallos_a_prismatic_wyvern_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_servant_of_the_ancients'); # :crystallos_a_servant_of_the_ancients_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_trapped_elemental'); # :crystallos_a_trapped_elemental_lt:
INSERT INTO loottable(name) VALUES('crystallos_a_watchful_sentry'); # :crystallos_a_watchful_sentry_lt:
