INSERT INTO loottable(name) VALUES('mansion_fire_bath'); # :mansion_fire_bath_lt:
INSERT INTO loottable(name) VALUES('mansion_steamwork_trainer'); # :mansion_steamwork_trainer_lt:
INSERT INTO loottable(name) VALUES('mansion_water_washer'); # :mansion_water_washer_lt:
INSERT INTO loottable(name) VALUES('mansion_an_enhanced_steamsuit'); # :mansion_an_enhanced_steamsuit_lt:
INSERT INTO loottable(name) VALUES('mansion_an_envoy'); # :mansion_an_envoy_lt:
INSERT INTO loottable(name) VALUES('mansion_an_honored_guest'); # :mansion_an_honored_guest_lt:
INSERT INTO loottable(name) VALUES('mansion_an_influential_consultant'); # :mansion_an_influential_consultant_lt:
INSERT INTO loottable(name) VALUES('mansion_an_inquisitor'); # :mansion_an_inquisitor_lt:
INSERT INTO loottable(name) VALUES('mansion_an_off_duty_dedicant'); # :mansion_an_off_duty_dedicant_lt:
INSERT INTO loottable(name) VALUES('mansion_an_off_duty_mender'); # :mansion_an_off_duty_mender_lt:
INSERT INTO loottable(name) VALUES('mansion_an_off_duty_trooper'); # :mansion_an_off_duty_trooper_lt:
INSERT INTO loottable(name) VALUES('mansion_a_biodisposal_entity'); # :mansion_a_biodisposal_entity_lt:
INSERT INTO loottable(name) VALUES('mansion_a_biodisposal_mass'); # :mansion_a_biodisposal_mass_lt:
INSERT INTO loottable(name) VALUES('mansion_a_blood-blackened_steamwork'); # :mansion_a_blood-blackened_steamwork_lt:
INSERT INTO loottable(name) VALUES('mansion_a_bloodmoon_representative'); # :mansion_a_bloodmoon_representative_lt:
INSERT INTO loottable(name) VALUES('mansion_a_chief_mechanic'); # :mansion_a_chief_mechanic_lt:
INSERT INTO loottable(name) VALUES('mansion_a_consecrant'); # :mansion_a_consecrant_lt:
INSERT INTO loottable(name) VALUES('mansion_a_cook'); # :mansion_a_cook_lt:
INSERT INTO loottable(name) VALUES('mansion_a_crew_chief'); # :mansion_a_crew_chief_lt:
INSERT INTO loottable(name) VALUES('mansion_a_dedicant'); # :mansion_a_dedicant_lt:
INSERT INTO loottable(name) VALUES('mansion_a_firebringer'); # :mansion_a_firebringer_lt:
INSERT INTO loottable(name) VALUES('mansion_a_flamemaster'); # :mansion_a_flamemaster_lt:
INSERT INTO loottable(name) VALUES('mansion_a_fresh_zombie'); # :mansion_a_fresh_zombie_lt:
INSERT INTO loottable(name) VALUES('mansion_a_game_piece'); # :mansion_a_game_piece_lt:
INSERT INTO loottable(name) VALUES('mansion_a_gremlin'); # :mansion_a_gremlin_lt:
INSERT INTO loottable(name) VALUES('mansion_a_harvesters_gravestone'); # :mansion_a_harvesters_gravestone_lt:
INSERT INTO loottable(name) VALUES('mansion_a_jagged_steamwork'); # :mansion_a_jagged_steamwork_lt:
INSERT INTO loottable(name) VALUES('mansion_a_long-term_visitor'); # :mansion_a_long-term_visitor_lt:
INSERT INTO loottable(name) VALUES('mansion_a_maid'); # :mansion_a_maid_lt:
INSERT INTO loottable(name) VALUES('mansion_a_master_slaver'); # :mansion_a_master_slaver_lt:
INSERT INTO loottable(name) VALUES('mansion_a_maze_attendant'); # :mansion_a_maze_attendant_lt:
INSERT INTO loottable(name) VALUES('mansion_a_mechanic'); # :mansion_a_mechanic_lt:
INSERT INTO loottable(name) VALUES('mansion_a_mender'); # :mansion_a_mender_lt:
INSERT INTO loottable(name) VALUES('mansion_a_mercenary'); # :mansion_a_mercenary_lt:
INSERT INTO loottable(name) VALUES('mansion_a_putrid_skeleton'); # :mansion_a_putrid_skeleton_lt:
INSERT INTO loottable(name) VALUES('mansion_a_reaver'); # :mansion_a_reaver_lt:
INSERT INTO loottable(name) VALUES('mansion_a_roboboar'); # :mansion_a_roboboar_lt:
INSERT INTO loottable(name) VALUES('mansion_a_saboteur'); # :mansion_a_saboteur_lt:
INSERT INTO loottable(name) VALUES('mansion_a_servant'); # :mansion_a_servant_lt:
INSERT INTO loottable(name) VALUES('mansion_a_shock_reaver'); # :mansion_a_shock_reaver_lt:
INSERT INTO loottable(name) VALUES('mansion_a_shock_striker'); # :mansion_a_shock_striker_lt:
INSERT INTO loottable(name) VALUES('mansion_a_shock_trooper'); # :mansion_a_shock_trooper_lt:
INSERT INTO loottable(name) VALUES('mansion_a_slave'); # :mansion_a_slave_lt:
INSERT INTO loottable(name) VALUES('mansion_a_slaver'); # :mansion_a_slaver_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steambinder'); # :mansion_a_steambinder_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamboiler'); # :mansion_a_steamboiler_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamsuit'); # :mansion_a_steamsuit_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_dancer'); # :mansion_a_steamwork_dancer_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_maid'); # :mansion_a_steamwork_maid_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_mechanic'); # :mansion_a_steamwork_mechanic_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_mender'); # :mansion_a_steamwork_mender_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_reaver'); # :mansion_a_steamwork_reaver_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_servant'); # :mansion_a_steamwork_servant_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_shockmender'); # :mansion_a_steamwork_shockmender_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_shock_reaver'); # :mansion_a_steamwork_shock_reaver_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_shock_striker'); # :mansion_a_steamwork_shock_striker_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_shock_trooper'); # :mansion_a_steamwork_shock_trooper_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_striker'); # :mansion_a_steamwork_striker_lt:
INSERT INTO loottable(name) VALUES('mansion_a_steamwork_trooper'); # :mansion_a_steamwork_trooper_lt:
INSERT INTO loottable(name) VALUES('mansion_a_striker'); # :mansion_a_striker_lt:
INSERT INTO loottable(name) VALUES('mansion_a_tinytop'); # :mansion_a_tinytop_lt:
INSERT INTO loottable(name) VALUES('mansion_a_tormented_steamwork'); # :mansion_a_tormented_steamwork_lt:
INSERT INTO loottable(name) VALUES('mansion_a_torturer'); # :mansion_a_torturer_lt:
INSERT INTO loottable(name) VALUES('mansion_a_trickster'); # :mansion_a_trickster_lt:
INSERT INTO loottable(name) VALUES('mansion_a_trooper'); # :mansion_a_trooper_lt:
INSERT INTO loottable(name) VALUES('mansion_a_troubleshooter'); # :mansion_a_troubleshooter_lt:
INSERT INTO loottable(name) VALUES('mansion_a_twisted_steamwork'); # :mansion_a_twisted_steamwork_lt:
INSERT INTO loottable(name) VALUES('mansion_a_valve_inspector'); # :mansion_a_valve_inspector_lt:
INSERT INTO loottable(name) VALUES('mansion_a_weakling'); # :mansion_a_weakling_lt:
INSERT INTO loottable(name) VALUES('mansion_a_workshop_tinkerer'); # :mansion_a_workshop_tinkerer_lt:
INSERT INTO loottable(name) VALUES('mansion_brindas_assistants_assistant'); # :mansion_brindas_assistants_assistant_lt:
INSERT INTO loottable(name) VALUES('mansion_elevator_music'); # :mansion_elevator_music_lt:
INSERT INTO loottable(name) VALUES('mansion_m.e.g.'); # :mansion_m.e.g._lt:
INSERT INTO loottable(name) VALUES('mansion_statue'); # :mansion_statue_lt:
INSERT INTO loottable(name) VALUES('mansion__'); # :mansion___lt:
