INSERT INTO loottable(name) VALUES('mechanotus_bablage,_master_lifter'); # :mechanotus_bablage,_master_lifter_lt:
INSERT INTO loottable(name) VALUES('mechanotus_chief_machinist_bildarol'); # :mechanotus_chief_machinist_bildarol_lt:
INSERT INTO loottable(name) VALUES('mechanotus_eldervine_the_twisted'); # :mechanotus_eldervine_the_twisted_lt:
INSERT INTO loottable(name) VALUES('mechanotus_gurtrude_the_spymaster'); # :mechanotus_gurtrude_the_spymaster_lt:
INSERT INTO loottable(name) VALUES('mechanotus_lamperious_cogwittle'); # :mechanotus_lamperious_cogwittle_lt:
INSERT INTO loottable(name) VALUES('mechanotus_octa_the_collector'); # :mechanotus_octa_the_collector_lt:
INSERT INTO loottable(name) VALUES('mechanotus_part_sorter_model_xv'); # :mechanotus_part_sorter_model_xv_lt:
INSERT INTO loottable(name) VALUES('mechanotus_sparks_diggleknob'); # :mechanotus_sparks_diggleknob_lt:
INSERT INTO loottable(name) VALUES('mechanotus_tabazin_gearflinger'); # :mechanotus_tabazin_gearflinger_lt:
INSERT INTO loottable(name) VALUES('mechanotus_the_gearmarshal'); # :mechanotus_the_gearmarshal_lt:
INSERT INTO loottable(name) VALUES('mechanotus_tinmyn_cogsloose'); # :mechanotus_tinmyn_cogsloose_lt:
INSERT INTO loottable(name) VALUES('mechanotus_an_enhanced_steamsuit'); # :mechanotus_an_enhanced_steamsuit_lt:
INSERT INTO loottable(name) VALUES('mechanotus_an_inconspicuous_mechanic'); # :mechanotus_an_inconspicuous_mechanic_lt:
INSERT INTO loottable(name) VALUES('mechanotus_an_inquisitor'); # :mechanotus_an_inquisitor_lt:
INSERT INTO loottable(name) VALUES('mechanotus_assistant_fredrik'); # :mechanotus_assistant_fredrik_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_chief_mechanic'); # :mechanotus_a_chief_mechanic_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_cog_marauder'); # :mechanotus_a_cog_marauder_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_consecrant'); # :mechanotus_a_consecrant_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_damaged_crate'); # :mechanotus_a_damaged_crate_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_dedicant'); # :mechanotus_a_dedicant_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_firebringer'); # :mechanotus_a_firebringer_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_flamemaster'); # :mechanotus_a_flamemaster_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_gardener'); # :mechanotus_a_gardener_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_gremlin'); # :mechanotus_a_gremlin_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_hungry_roboboar'); # :mechanotus_a_hungry_roboboar_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_junk_sorter'); # :mechanotus_a_junk_sorter_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_loathsome_oil_ooze'); # :mechanotus_a_loathsome_oil_ooze_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_master_slaver'); # :mechanotus_a_master_slaver_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_mechanic'); # :mechanotus_a_mechanic_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_mender'); # :mechanotus_a_mender_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_minotaur_trooper'); # :mechanotus_a_minotaur_trooper_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_murky_oil_ooze'); # :mechanotus_a_murky_oil_ooze_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_reaver'); # :mechanotus_a_reaver_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_rebel_brownie_emissary'); # :mechanotus_a_rebel_brownie_emissary_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_recycler'); # :mechanotus_a_recycler_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_recycler_flogger'); # :mechanotus_a_recycler_flogger_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_roboboar'); # :mechanotus_a_roboboar_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_shock_reaver'); # :mechanotus_a_shock_reaver_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_shock_striker'); # :mechanotus_a_shock_striker_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_shock_trooper'); # :mechanotus_a_shock_trooper_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_siege_specialist'); # :mechanotus_a_siege_specialist_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_singed_crate'); # :mechanotus_a_singed_crate_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_slaver'); # :mechanotus_a_slaver_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_spare_part_collector'); # :mechanotus_a_spare_part_collector_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steambinder'); # :mechanotus_a_steambinder_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamboiler'); # :mechanotus_a_steamboiler_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_mechanic'); # :mechanotus_a_steamwork_mechanic_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_mender'); # :mechanotus_a_steamwork_mender_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_parts_delivery_unit'); # :mechanotus_a_steamwork_parts_delivery_unit_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_reaver'); # :mechanotus_a_steamwork_reaver_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_shockmender'); # :mechanotus_a_steamwork_shockmender_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_shock_reaver'); # :mechanotus_a_steamwork_shock_reaver_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_shock_soldier'); # :mechanotus_a_steamwork_shock_soldier_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_shock_striker'); # :mechanotus_a_steamwork_shock_striker_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_shock_trooper'); # :mechanotus_a_steamwork_shock_trooper_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_soldier'); # :mechanotus_a_steamwork_soldier_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_spy_mk-vi'); # :mechanotus_a_steamwork_spy_mk-vi_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_striker'); # :mechanotus_a_steamwork_striker_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steamwork_trooper'); # :mechanotus_a_steamwork_trooper_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_steel-bound_crate'); # :mechanotus_a_steel-bound_crate_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_sticky_oil_ooze'); # :mechanotus_a_sticky_oil_ooze_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_striker'); # :mechanotus_a_striker_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_torturer'); # :mechanotus_a_torturer_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_trooper'); # :mechanotus_a_trooper_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_troubleshooter'); # :mechanotus_a_troubleshooter_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_weed_eater'); # :mechanotus_a_weed_eater_lt:
INSERT INTO loottable(name) VALUES('mechanotus_a_wretched_oil_ooze'); # :mechanotus_a_wretched_oil_ooze_lt:
INSERT INTO loottable(name) VALUES('mechanotus_clockwork_warmarshal'); # :mechanotus_clockwork_warmarshal_lt:
INSERT INTO loottable(name) VALUES('mechanotus_engineer_brinik'); # :mechanotus_engineer_brinik_lt:
INSERT INTO loottable(name) VALUES('mechanotus_engineer_springfap'); # :mechanotus_engineer_springfap_lt:
INSERT INTO loottable(name) VALUES('mechanotus_frostfellmeccontroller'); # :mechanotus_frostfellmeccontroller_lt:
INSERT INTO loottable(name) VALUES('mechanotus_inizen_nogglezop'); # :mechanotus_inizen_nogglezop_lt:
INSERT INTO loottable(name) VALUES('mechanotus_launch_engineer'); # :mechanotus_launch_engineer_lt:
INSERT INTO loottable(name) VALUES('mechanotus_plink_squichbolt'); # :mechanotus_plink_squichbolt_lt:
INSERT INTO loottable(name) VALUES('mechanotus_pyrotechnician_flizcog'); # :mechanotus_pyrotechnician_flizcog_lt:
INSERT INTO loottable(name) VALUES('mechanotus_researcher_stripcog'); # :mechanotus_researcher_stripcog_lt:
INSERT INTO loottable(name) VALUES('mechanotus_siege_inspector_huttle'); # :mechanotus_siege_inspector_huttle_lt:
INSERT INTO loottable(name) VALUES('mechanotus_tavik_gearpaq'); # :mechanotus_tavik_gearpaq_lt:
INSERT INTO loottable(name) VALUES('mechanotus_veltar_spawner'); # :mechanotus_veltar_spawner_lt:
INSERT INTO loottable(name) VALUES('mechanotus__'); # :mechanotus___lt:
