INSERT INTO loottable(name) VALUES('shipworkshop_a_teleportation_accident'); # :shipworkshop_a_teleportation_accident_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_chief_administrator_grigano'); # :shipworkshop_chief_administrator_grigano_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_head_administrator_grigano'); # :shipworkshop_head_administrator_grigano_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_head_scientist_lotrip'); # :shipworkshop_head_scientist_lotrip_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_head_scientist_twiner'); # :shipworkshop_head_scientist_twiner_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_head_scientist_wripple'); # :shipworkshop_head_scientist_wripple_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_malfunctioning_steamwork_borri'); # :shipworkshop_malfunctioning_steamwork_borri_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_an_administrative_assistant'); # :shipworkshop_an_administrative_assistant_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_an_evaluation_specialist'); # :shipworkshop_an_evaluation_specialist_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_an_injured_spy'); # :shipworkshop_an_injured_spy_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_an_unstable_beast'); # :shipworkshop_an_unstable_beast_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_brownie_ductcleaner'); # :shipworkshop_a_brownie_ductcleaner_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_brownie_ductworker'); # :shipworkshop_a_brownie_ductworker_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_brownie_medic'); # :shipworkshop_a_brownie_medic_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_consecrant'); # :shipworkshop_a_consecrant_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_disabled_steamwork'); # :shipworkshop_a_disabled_steamwork_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_gnome_dreadguard'); # :shipworkshop_a_gnome_dreadguard_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_gnome_mage'); # :shipworkshop_a_gnome_mage_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_gnome_medic'); # :shipworkshop_a_gnome_medic_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_gnome_necromancer'); # :shipworkshop_a_gnome_necromancer_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_gnome_sneak'); # :shipworkshop_a_gnome_sneak_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_gnome_trooper'); # :shipworkshop_a_gnome_trooper_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_laboratory_runner'); # :shipworkshop_a_laboratory_runner_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_lab_assistant'); # :shipworkshop_a_lab_assistant_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_lab_protector'); # :shipworkshop_a_lab_protector_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_lab_technician'); # :shipworkshop_a_lab_technician_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_lab_worker'); # :shipworkshop_a_lab_worker_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_minotaur_berserker'); # :shipworkshop_a_minotaur_berserker_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_minotaur_juggernaut'); # :shipworkshop_a_minotaur_juggernaut_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_minotaur_shocktrooper'); # :shipworkshop_a_minotaur_shocktrooper_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_minotaur_trooper'); # :shipworkshop_a_minotaur_trooper_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_shock_reaver'); # :shipworkshop_a_shock_reaver_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_shock_striker'); # :shipworkshop_a_shock_striker_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_shock_trooper'); # :shipworkshop_a_shock_trooper_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamboiler'); # :shipworkshop_a_steamboiler_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_reaver'); # :shipworkshop_a_steamwork_reaver_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_repairer'); # :shipworkshop_a_steamwork_repairer_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_shockreaver'); # :shipworkshop_a_steamwork_shockreaver_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_shockstriker'); # :shipworkshop_a_steamwork_shockstriker_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_shocktrooper'); # :shipworkshop_a_steamwork_shocktrooper_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_spy_mk-i'); # :shipworkshop_a_steamwork_spy_mk-i_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_spy_mk-ii'); # :shipworkshop_a_steamwork_spy_mk-ii_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_spy_mk-iii'); # :shipworkshop_a_steamwork_spy_mk-iii_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_striker'); # :shipworkshop_a_steamwork_striker_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_tinker'); # :shipworkshop_a_steamwork_tinker_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_steamwork_trooper'); # :shipworkshop_a_steamwork_trooper_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_technicians_assistant'); # :shipworkshop_a_technicians_assistant_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_test_subject'); # :shipworkshop_a_test_subject_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_troubleshooter'); # :shipworkshop_a_troubleshooter_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_workshop_pyrotechnician'); # :shipworkshop_a_workshop_pyrotechnician_lt:
INSERT INTO loottable(name) VALUES('shipworkshop_a_workshop_repairer'); # :shipworkshop_a_workshop_repairer_lt:
