INSERT INTO loottable(name) VALUES('steamfontmts_a_kobold_missionary'); # :steamfontmts_a_kobold_missionary_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_biddliss_sperandu'); # :steamfontmts_biddliss_sperandu_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_findleznax_grimblewimbus'); # :steamfontmts_findleznax_grimblewimbus_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_mip_sprocket'); # :steamfontmts_mip_sprocket_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_renux_herkanor'); # :steamfontmts_renux_herkanor_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_smith_numden'); # :steamfontmts_smith_numden_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_an_earth_elemental'); # :steamfontmts_an_earth_elemental_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_an_ebon_drakeling'); # :steamfontmts_an_ebon_drakeling_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_an_infected_rat'); # :steamfontmts_an_infected_rat_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_brittle_skeleton'); # :steamfontmts_a_brittle_skeleton_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_clockwork_bowyer'); # :steamfontmts_a_clockwork_bowyer_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_clockwork_fletcher'); # :steamfontmts_a_clockwork_fletcher_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_decaying_gnome_skeleton'); # :steamfontmts_a_decaying_gnome_skeleton_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_decomposing_body'); # :steamfontmts_a_decomposing_body_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_faded_banner'); # :steamfontmts_a_faded_banner_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_female_rat'); # :steamfontmts_a_female_rat_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_giant_diseased_rat'); # :steamfontmts_a_giant_diseased_rat_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_giant_rat'); # :steamfontmts_a_giant_rat_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_giant_yellow_recluse'); # :steamfontmts_a_giant_yellow_recluse_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_gnome_skeleton'); # :steamfontmts_a_gnome_skeleton_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_gnome_slave'); # :steamfontmts_a_gnome_slave_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_grikbar_kobold'); # :steamfontmts_a_grikbar_kobold_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_grikbar_shaman'); # :steamfontmts_a_grikbar_shaman_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_harpy'); # :steamfontmts_a_harpy_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_kobold_runt'); # :steamfontmts_a_kobold_runt_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_kobold_scout'); # :steamfontmts_a_kobold_scout_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_krag_chick'); # :steamfontmts_a_krag_chick_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_krag_warrior'); # :steamfontmts_a_krag_warrior_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_large_plague_rat'); # :steamfontmts_a_large_plague_rat_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_large_rat'); # :steamfontmts_a_large_rat_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_large_yellow_recluse'); # :steamfontmts_a_large_yellow_recluse_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_lesser_ebon_drake'); # :steamfontmts_a_lesser_ebon_drake_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_minotaur_brawler'); # :steamfontmts_a_minotaur_brawler_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_minotaur_slaver'); # :steamfontmts_a_minotaur_slaver_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_mountain_brownie'); # :steamfontmts_a_mountain_brownie_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_mountain_lion'); # :steamfontmts_a_mountain_lion_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_rebel_clockwork'); # :steamfontmts_a_rebel_clockwork_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_runaway_clockwork'); # :steamfontmts_a_runaway_clockwork_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_skeleton'); # :steamfontmts_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_small_coyote'); # :steamfontmts_a_small_coyote_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_small_mountain_lion'); # :steamfontmts_a_small_mountain_lion_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_spiderling'); # :steamfontmts_a_spiderling_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_steam_elemental'); # :steamfontmts_a_steam_elemental_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_young_ebon_drake'); # :steamfontmts_a_young_ebon_drake_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_a_young_plague_rat'); # :steamfontmts_a_young_plague_rat_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_berinsan'); # :steamfontmts_berinsan_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_bigilam_wantilans'); # :steamfontmts_bigilam_wantilans_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_bom_knotwood'); # :steamfontmts_bom_knotwood_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_brona_frugrin'); # :steamfontmts_brona_frugrin_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_brynn_tinkerton'); # :steamfontmts_brynn_tinkerton_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_byrola_bendil'); # :steamfontmts_byrola_bendil_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_cargo_clockwork'); # :steamfontmts_cargo_clockwork_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_charlotte'); # :steamfontmts_charlotte_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_crisyn'); # :steamfontmts_crisyn_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_crusader_swiftmoon'); # :steamfontmts_crusader_swiftmoon_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_diloperia'); # :steamfontmts_diloperia_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_dimlore_stormhammer'); # :steamfontmts_dimlore_stormhammer_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_dirolensab'); # :steamfontmts_dirolensab_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_diseased_female_rat'); # :steamfontmts_diseased_female_rat_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_donlix_bonkle'); # :steamfontmts_donlix_bonkle_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_ennixy_frennor'); # :steamfontmts_ennixy_frennor_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_faeeron'); # :steamfontmts_faeeron_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_fearonoliop'); # :steamfontmts_fearonoliop_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_finkel_rardobaen'); # :steamfontmts_finkel_rardobaen_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_fodin_frugrin'); # :steamfontmts_fodin_frugrin_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_forpar_fizfla'); # :steamfontmts_forpar_fizfla_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_frebin_tinderhue'); # :steamfontmts_frebin_tinderhue_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_freed_fimplefur'); # :steamfontmts_freed_fimplefur_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_frugo_prigdish'); # :steamfontmts_frugo_prigdish_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_galorin'); # :steamfontmts_galorin_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_gana_geargrinder'); # :steamfontmts_gana_geargrinder_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_genda_minyte'); # :steamfontmts_genda_minyte_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_glen_garginburr'); # :steamfontmts_glen_garginburr_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_godbin_strumharp'); # :steamfontmts_godbin_strumharp_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_gorehorn'); # :steamfontmts_gorehorn_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_greeble_blacktoe'); # :steamfontmts_greeble_blacktoe_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_grenga_cogsworth'); # :steamfontmts_grenga_cogsworth_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_halorniop'); # :steamfontmts_halorniop_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_hector_the_highway_bandit'); # :steamfontmts_hector_the_highway_bandit_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_inactive_clockwork'); # :steamfontmts_inactive_clockwork_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_jerald_the_highway_bandit'); # :steamfontmts_jerald_the_highway_bandit_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_jibble_blexnik'); # :steamfontmts_jibble_blexnik_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_jin_fidentine'); # :steamfontmts_jin_fidentine_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_jogl_doobraugh'); # :steamfontmts_jogl_doobraugh_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_legyn_sarawyn'); # :steamfontmts_legyn_sarawyn_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_lodrand_dindlenod'); # :steamfontmts_lodrand_dindlenod_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_meldrath_the_malignant'); # :steamfontmts_meldrath_the_malignant_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_metallurgist_mirakzin'); # :steamfontmts_metallurgist_mirakzin_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_minotaur_guard'); # :steamfontmts_minotaur_guard_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_minotaur_hero'); # :steamfontmts_minotaur_hero_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_minotaur_lord'); # :steamfontmts_minotaur_lord_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_nilit_druzlit'); # :steamfontmts_nilit_druzlit_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_oren_furdenbline'); # :steamfontmts_oren_furdenbline_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_phiz_frugrin'); # :steamfontmts_phiz_frugrin_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_renaldo_the_highway_bandit'); # :steamfontmts_renaldo_the_highway_bandit_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_rogue_cleaner'); # :steamfontmts_rogue_cleaner_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_rogue_clockwork'); # :steamfontmts_rogue_clockwork_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_runaway_clockwork'); # :steamfontmts_runaway_clockwork_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_stell_borrengo'); # :steamfontmts_stell_borrengo_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_thetherthag_wakintrob'); # :steamfontmts_thetherthag_wakintrob_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_tindo_frugrin'); # :steamfontmts_tindo_frugrin_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_torodrane_frompwaddle'); # :steamfontmts_torodrane_frompwaddle_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_vyntok_bonkle'); # :steamfontmts_vyntok_bonkle_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_watchman_dreeb'); # :steamfontmts_watchman_dreeb_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_watchman_grep'); # :steamfontmts_watchman_grep_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_watchman_mylz'); # :steamfontmts_watchman_mylz_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_watchman_prenn'); # :steamfontmts_watchman_prenn_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_watchman_prynn'); # :steamfontmts_watchman_prynn_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_winex_kloktik'); # :steamfontmts_winex_kloktik_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_yama_twerik'); # :steamfontmts_yama_twerik_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_yendar_starpyre'); # :steamfontmts_yendar_starpyre_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_yulcabis'); # :steamfontmts_yulcabis_lt:
INSERT INTO loottable(name) VALUES('steamfontmts_zondo_hyzill'); # :steamfontmts_zondo_hyzill_lt:
