INSERT INTO loottable(name) VALUES('brellsrest_'); # :brellsrest__lt:
INSERT INTO loottable(name) VALUES('brellsrest_algera_chindlebolt'); # :brellsrest_algera_chindlebolt_lt:
INSERT INTO loottable(name) VALUES('brellsrest_berrina_saltidnarik'); # :brellsrest_berrina_saltidnarik_lt:
INSERT INTO loottable(name) VALUES('brellsrest_dorrvix'); # :brellsrest_dorrvix_lt:
INSERT INTO loottable(name) VALUES('brellsrest_dwekvard_gravelpick'); # :brellsrest_dwekvard_gravelpick_lt:
INSERT INTO loottable(name) VALUES('brellsrest_eldinn_sturdyboot'); # :brellsrest_eldinn_sturdyboot_lt:
INSERT INTO loottable(name) VALUES('brellsrest_elmina_sturdyboot'); # :brellsrest_elmina_sturdyboot_lt:
INSERT INTO loottable(name) VALUES('brellsrest_firnel_missynstip'); # :brellsrest_firnel_missynstip_lt:
INSERT INTO loottable(name) VALUES('brellsrest_graztuk'); # :brellsrest_graztuk_lt:
INSERT INTO loottable(name) VALUES('brellsrest_holdegar_bairdun'); # :brellsrest_holdegar_bairdun_lt:
INSERT INTO loottable(name) VALUES('brellsrest_marie_fay'); # :brellsrest_marie_fay_lt:
INSERT INTO loottable(name) VALUES('brellsrest_nogol_bandras'); # :brellsrest_nogol_bandras_lt:
INSERT INTO loottable(name) VALUES('brellsrest_parrmug'); # :brellsrest_parrmug_lt:
INSERT INTO loottable(name) VALUES('brellsrest_the_gatekeeper'); # :brellsrest_the_gatekeeper_lt:
INSERT INTO loottable(name) VALUES('brellsrest_useful_automated_vendor'); # :brellsrest_useful_automated_vendor_lt:
INSERT INTO loottable(name) VALUES('brellsrest_an_underfish'); # :brellsrest_an_underfish_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_burynai_burrower'); # :brellsrest_a_burynai_burrower_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_burynai_cenobite'); # :brellsrest_a_burynai_cenobite_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_burynai_curate'); # :brellsrest_a_burynai_curate_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_burynai_explorer'); # :brellsrest_a_burynai_explorer_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_burynai_rockshaper'); # :brellsrest_a_burynai_rockshaper_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_burynai_sapper'); # :brellsrest_a_burynai_sapper_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_dwarven_combatant'); # :brellsrest_a_dwarven_combatant_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_gnoll_assassin'); # :brellsrest_a_gnoll_assassin_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_gnoll_brawler'); # :brellsrest_a_gnoll_brawler_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_gnoll_charger'); # :brellsrest_a_gnoll_charger_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_gnoll_combatant'); # :brellsrest_a_gnoll_combatant_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_gnoll_flamepaw'); # :brellsrest_a_gnoll_flamepaw_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_gnoll_guardian'); # :brellsrest_a_gnoll_guardian_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_gnoll_shaman'); # :brellsrest_a_gnoll_shaman_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_gnoll_soothsayer'); # :brellsrest_a_gnoll_soothsayer_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_gnome_combatant'); # :brellsrest_a_gnome_combatant_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_kobold_champion'); # :brellsrest_a_kobold_champion_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_kobold_combatant'); # :brellsrest_a_kobold_combatant_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_kobold_defender'); # :brellsrest_a_kobold_defender_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_kobold_guardian'); # :brellsrest_a_kobold_guardian_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_kobold_hunter'); # :brellsrest_a_kobold_hunter_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_kobold_shaman'); # :brellsrest_a_kobold_shaman_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_kobold_spiritcaller'); # :brellsrest_a_kobold_spiritcaller_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_kobold_warder'); # :brellsrest_a_kobold_warder_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_lavakin'); # :brellsrest_a_lavakin_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_nestling'); # :brellsrest_a_nestling_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_spinebloom'); # :brellsrest_a_spinebloom_lt:
INSERT INTO loottable(name) VALUES('brellsrest_a_steam_elemental'); # :brellsrest_a_steam_elemental_lt:
INSERT INTO loottable(name) VALUES('brellsrest_bartel'); # :brellsrest_bartel_lt:
INSERT INTO loottable(name) VALUES('brellsrest_eggsniffer'); # :brellsrest_eggsniffer_lt:
INSERT INTO loottable(name) VALUES('brellsrest_fangskull'); # :brellsrest_fangskull_lt:
INSERT INTO loottable(name) VALUES('brellsrest_gilbot_the_golden'); # :brellsrest_gilbot_the_golden_lt:
INSERT INTO loottable(name) VALUES('brellsrest_gilbot_the_magnificent'); # :brellsrest_gilbot_the_magnificent_lt:
INSERT INTO loottable(name) VALUES('brellsrest_nogit'); # :brellsrest_nogit_lt:
INSERT INTO loottable(name) VALUES('brellsrest_ripskin'); # :brellsrest_ripskin_lt:
