INSERT INTO loottable(name) VALUES('convorteum_apexus_enforcer'); # :convorteum_apexus_enforcer_lt:
INSERT INTO loottable(name) VALUES('convorteum_argnus'); # :convorteum_argnus_lt:
INSERT INTO loottable(name) VALUES('convorteum_belsa'); # :convorteum_belsa_lt:
INSERT INTO loottable(name) VALUES('convorteum_bergolos'); # :convorteum_bergolos_lt:
INSERT INTO loottable(name) VALUES('convorteum_delth'); # :convorteum_delth_lt:
INSERT INTO loottable(name) VALUES('convorteum_donald_darkbrow'); # :convorteum_donald_darkbrow_lt:
INSERT INTO loottable(name) VALUES('convorteum_elder_viklov'); # :convorteum_elder_viklov_lt:
INSERT INTO loottable(name) VALUES('convorteum_etrigore'); # :convorteum_etrigore_lt:
INSERT INTO loottable(name) VALUES('convorteum_grif_iceblock'); # :convorteum_grif_iceblock_lt:
INSERT INTO loottable(name) VALUES('convorteum_griggles'); # :convorteum_griggles_lt:
INSERT INTO loottable(name) VALUES('convorteum_grodnis'); # :convorteum_grodnis_lt:
INSERT INTO loottable(name) VALUES('convorteum_hibblio'); # :convorteum_hibblio_lt:
INSERT INTO loottable(name) VALUES('convorteum_hilbert_sonori'); # :convorteum_hilbert_sonori_lt:
INSERT INTO loottable(name) VALUES('convorteum_krog_the_bounty_hunter'); # :convorteum_krog_the_bounty_hunter_lt:
INSERT INTO loottable(name) VALUES('convorteum_norri_stubblestone'); # :convorteum_norri_stubblestone_lt:
INSERT INTO loottable(name) VALUES('convorteum_silbibio'); # :convorteum_silbibio_lt:
INSERT INTO loottable(name) VALUES('convorteum_stonemason_broav'); # :convorteum_stonemason_broav_lt:
INSERT INTO loottable(name) VALUES('convorteum_summoner_netikos'); # :convorteum_summoner_netikos_lt:
INSERT INTO loottable(name) VALUES('convorteum_the_scavenger_subjugator'); # :convorteum_the_scavenger_subjugator_lt:
INSERT INTO loottable(name) VALUES('convorteum_tippletop_whizzlebang'); # :convorteum_tippletop_whizzlebang_lt:
INSERT INTO loottable(name) VALUES('convorteum_tolvias_the_keeper'); # :convorteum_tolvias_the_keeper_lt:
INSERT INTO loottable(name) VALUES('convorteum_warret_darklight'); # :convorteum_warret_darklight_lt:
INSERT INTO loottable(name) VALUES('convorteum_welmina'); # :convorteum_welmina_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_advisor'); # :convorteum_an_advisor_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_apexus_brute'); # :convorteum_an_apexus_brute_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_apexus_guard'); # :convorteum_an_apexus_guard_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_apexus_scholar'); # :convorteum_an_apexus_scholar_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_elementalist'); # :convorteum_an_autarchian_elementalist_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_harrier'); # :convorteum_an_autarchian_harrier_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_healer'); # :convorteum_an_autarchian_healer_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_pilgrim'); # :convorteum_an_autarchian_pilgrim_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_ravager'); # :convorteum_an_autarchian_ravager_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_rioter'); # :convorteum_an_autarchian_rioter_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_scavenger'); # :convorteum_an_autarchian_scavenger_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_scrapper'); # :convorteum_an_autarchian_scrapper_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_skirmisher'); # :convorteum_an_autarchian_skirmisher_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_soldier'); # :convorteum_an_autarchian_soldier_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_autarchian_trooper'); # :convorteum_an_autarchian_trooper_lt:
INSERT INTO loottable(name) VALUES('convorteum_an_immature_greken'); # :convorteum_an_immature_greken_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_bellikos_conniver'); # :convorteum_a_bellikos_conniver_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_bellikos_curator'); # :convorteum_a_bellikos_curator_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_bellikos_deceiver'); # :convorteum_a_bellikos_deceiver_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_bellikos_harbinger'); # :convorteum_a_bellikos_harbinger_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_bellikos_reviler'); # :convorteum_a_bellikos_reviler_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_bellikos_sermonizer'); # :convorteum_a_bellikos_sermonizer_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_clockwork_magma_meter_mcmxcix'); # :convorteum_a_clockwork_magma_meter_mcmxcix_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_failed_creation'); # :convorteum_a_failed_creation_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_firebug'); # :convorteum_a_firebug_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_fire_elemental'); # :convorteum_a_fire_elemental_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_greken_hatchling'); # :convorteum_a_greken_hatchling_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_lava_beetle'); # :convorteum_a_lava_beetle_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_lava_brute'); # :convorteum_a_lava_brute_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_lava_mephit_defector'); # :convorteum_a_lava_mephit_defector_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_lava_mephit_traitor'); # :convorteum_a_lava_mephit_traitor_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_lithographer'); # :convorteum_a_lithographer_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_prison_guard'); # :convorteum_a_prison_guard_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_record_keeper'); # :convorteum_a_record_keeper_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_telmiran_summoner'); # :convorteum_a_telmiran_summoner_lt:
INSERT INTO loottable(name) VALUES('convorteum_a_telmiran_worker'); # :convorteum_a_telmiran_worker_lt:
INSERT INTO loottable(name) VALUES('convorteum_conpatrolcontroller'); # :convorteum_conpatrolcontroller_lt:
INSERT INTO loottable(name) VALUES('convorteum_fsp-buff-exquisite-manargn'); # :convorteum_fsp-buff-exquisite-manargn_lt:
INSERT INTO loottable(name) VALUES('convorteum_fsp-general-noeffect'); # :convorteum_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('convorteum_smokescreen'); # :convorteum_smokescreen_lt:
