INSERT INTO loottable(name) VALUES('coolingchamber_foreman_gronkin'); # :coolingchamber_foreman_gronkin_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_lower_foreman'); # :coolingchamber_lower_foreman_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_middle_foreman'); # :coolingchamber_middle_foreman_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_taelin_the_fearless'); # :coolingchamber_taelin_the_fearless_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_talbot_roaringhead'); # :coolingchamber_talbot_roaringhead_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_tasnise_underbelly'); # :coolingchamber_tasnise_underbelly_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_thelga_muntik'); # :coolingchamber_thelga_muntik_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_upper_foreman'); # :coolingchamber_upper_foreman_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_valcamph_shadowfrost'); # :coolingchamber_valcamph_shadowfrost_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_baleful_banshee'); # :coolingchamber_a_baleful_banshee_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_barrel'); # :coolingchamber_a_barrel_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_chattering_skeleton'); # :coolingchamber_a_chattering_skeleton_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_clattering_skeleton'); # :coolingchamber_a_clattering_skeleton_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_cooling_chamber_attendant'); # :coolingchamber_a_cooling_chamber_attendant_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_cooling_chamber_engineer'); # :coolingchamber_a_cooling_chamber_engineer_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_cooling_chamber_worker'); # :coolingchamber_a_cooling_chamber_worker_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_creeping_ghoul'); # :coolingchamber_a_creeping_ghoul_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_cursed_elf'); # :coolingchamber_a_cursed_elf_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_cursed_human'); # :coolingchamber_a_cursed_human_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_drifting_specter'); # :coolingchamber_a_drifting_specter_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_forlorn_banshee'); # :coolingchamber_a_forlorn_banshee_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_frightful_banshee'); # :coolingchamber_a_frightful_banshee_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_haunting_specter'); # :coolingchamber_a_haunting_specter_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_hulking_zombie'); # :coolingchamber_a_hulking_zombie_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_leering_ghoul'); # :coolingchamber_a_leering_ghoul_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_magical_ward'); # :coolingchamber_a_magical_ward_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_rock_absorbing_goo'); # :coolingchamber_a_rock_absorbing_goo_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_rock_consumed_goo'); # :coolingchamber_a_rock_consumed_goo_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_rock_consuming_goo'); # :coolingchamber_a_rock_consuming_goo_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_rock_crunching_goo'); # :coolingchamber_a_rock_crunching_goo_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_rock_destroyed_goo'); # :coolingchamber_a_rock_destroyed_goo_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_rock_destroying_goo'); # :coolingchamber_a_rock_destroying_goo_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_rock_devouring_goo'); # :coolingchamber_a_rock_devouring_goo_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_rock_dissolving_goo'); # :coolingchamber_a_rock_dissolving_goo_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_shuffling_zombie'); # :coolingchamber_a_shuffling_zombie_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_traitorous_alchemist'); # :coolingchamber_a_traitorous_alchemist_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_traitorous_laborer'); # :coolingchamber_a_traitorous_laborer_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_traitorous_worker'); # :coolingchamber_a_traitorous_worker_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_a_wailing_banshee'); # :coolingchamber_a_wailing_banshee_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_rodrick_cleanheart'); # :coolingchamber_rodrick_cleanheart_lt:
INSERT INTO loottable(name) VALUES('coolingchamber_thorbin_the_elder'); # :coolingchamber_thorbin_the_elder_lt:
