UPDATE npc_types SET loottable_id = :lichencreep__lt: WHERE id in (487063); #  88
UPDATE npc_types SET loottable_id = :lichencreep_akini,_xanathans_warder_lt: WHERE id in (487044); # #Akini,_Xanathan`s_Warder 80
UPDATE npc_types SET loottable_id = :lichencreep_ash_golem_lt: WHERE id in (487050); # #Ash_Golem 88
UPDATE npc_types SET loottable_id = :lichencreep_balbor_lt: WHERE id in (487062); # #Balbor 83
UPDATE npc_types SET loottable_id = :lichencreep_excavator_borga_lt: WHERE id in (487054); # #Excavator_Borga 83
UPDATE npc_types SET loottable_id = :lichencreep_explorer_durgan_lt: WHERE id in (487056); # #Explorer_Durgan 83
UPDATE npc_types SET loottable_id = :lichencreep_figles_steeltread_lt: WHERE id in (487051); # #Figles_Steeltread 85
UPDATE npc_types SET loottable_id = :lichencreep_gweddon_tinkertasker_lt: WHERE id in (487046); # #Gweddon_Tinkertasker 85
UPDATE npc_types SET loottable_id = :lichencreep_inventor_biddlebokk_lt: WHERE id in (487053); # #Inventor_Biddlebokk 83
UPDATE npc_types SET loottable_id = :lichencreep_invismanaprilfoolslic_lt: WHERE id in (487052); # #InvisManAprilFoolsLIC 88
UPDATE npc_types SET loottable_id = :lichencreep_lava_mephit_outcast_lt: WHERE id in (487001); # #Lava_Mephit_Outcast 83
UPDATE npc_types SET loottable_id = :lichencreep_mephit_shaman_lt: WHERE id in (487041); # #Mephit_Shaman 86
UPDATE npc_types SET loottable_id = :lichencreep_rinna_tinwhistle_lt: WHERE id in (487002); # #Rinna_Tinwhistle 85
UPDATE npc_types SET loottable_id = :lichencreep_sessiloid_calcifier_lt: WHERE id in (487008); # #Sessiloid_Calcifier 88
UPDATE npc_types SET loottable_id = :lichencreep_sessy_lt: WHERE id in (487005); # #Sessy 83
UPDATE npc_types SET loottable_id = :lichencreep_shiani_lt: WHERE id in (487006); # #Shiani 83
UPDATE npc_types SET loottable_id = :lichencreep_shrum_lt: WHERE id in (487017); # #Shrum 83
UPDATE npc_types SET loottable_id = :lichencreep_sienna_flamestalker_lt: WHERE id in (487019); # #Sienna_Flamestalker 83
UPDATE npc_types SET loottable_id = :lichencreep_splak_lt: WHERE id in (487058); # #Splak 83
UPDATE npc_types SET loottable_id = :lichencreep_splari_lt: WHERE id in (487057); # #Splari 83
UPDATE npc_types SET loottable_id = :lichencreep_xanathan_foxheart_lt: WHERE id in (487043); # #Xanathan_Foxheart 83
UPDATE npc_types SET loottable_id = :lichencreep_zuzz_lt: WHERE id in (487022); # #Zuzz 83
UPDATE npc_types SET loottable_id = :lichencreep_an_autarchian_dwarf_lt: WHERE id in (487016, 487018, 487023, 487026, 487031, 487035, 487036, 487039, 487045, 487059); # an_autarchian_dwarf 83
UPDATE npc_types SET loottable_id = :lichencreep_an_autarchian_gnome_lt: WHERE id in (487012, 487021, 487025, 487027, 487028, 487030, 487032, 487033, 487034, 487038); # an_autarchian_gnome 84
UPDATE npc_types SET loottable_id = :lichencreep_a_cliknar_gatherer_lt: WHERE id in (487040); # a_cliknar_gatherer 85
UPDATE npc_types SET loottable_id = :lichencreep_a_cliknar_scout_lt: WHERE id in (487047); # a_cliknar_scout 85
UPDATE npc_types SET loottable_id = :lichencreep_a_deranged_mephit_lt: WHERE id in (487003); # a_deranged_mephit 85
UPDATE npc_types SET loottable_id = :lichencreep_a_frightened_sporali_lt: WHERE id in (487013); # a_frightened_sporali 85
UPDATE npc_types SET loottable_id = :lichencreep_a_hungry_sessiloid_lt: WHERE id in (487004); # a_hungry_sessiloid 85
UPDATE npc_types SET loottable_id = :lichencreep_a_lavaborn_golem_lt: WHERE id in (487024, 487029, 487037); # a_lavaborn_golem 84
UPDATE npc_types SET loottable_id = :lichencreep_a_lava_golem_lt: WHERE id in (487015); # a_lava_golem 85
UPDATE npc_types SET loottable_id = :lichencreep_a_lava_mephit_guard_lt: WHERE id in (487007); # a_lava_mephit_guard 85
UPDATE npc_types SET loottable_id = :lichencreep_a_lava_mephit_miner_lt: WHERE id in (487048); # a_lava_mephit_miner 85
UPDATE npc_types SET loottable_id = :lichencreep_a_lava_mephit_ore_carrier_lt: WHERE id in (487049, 487060, 487061); # a_lava_mephit_ore_carrier 85
UPDATE npc_types SET loottable_id = :lichencreep_a_lava_mephit_worker_lt: WHERE id in (487011); # a_lava_mephit_worker 85
UPDATE npc_types SET loottable_id = :lichencreep_a_lost_sporali_lt: WHERE id in (487020); # a_lost_sporali 85
UPDATE npc_types SET loottable_id = :lichencreep_a_magma_golem_lt: WHERE id in (487014); # a_magma_golem 85
UPDATE npc_types SET loottable_id = :lichencreep_a_rock_golem_guardian_lt: WHERE id in (487010); # a_rock_golem_guardian 85
UPDATE npc_types SET loottable_id = :lichencreep_a_rock_golem_smasher_lt: WHERE id in (487042); # a_rock_golem_smasher 85
UPDATE npc_types SET loottable_id = :lichencreep_a_rock_pile_lt: WHERE id in (487009); # a_rock_pile 75
UPDATE npc_types SET loottable_id = :lichencreep_skuportalguninvisman_lt: WHERE id in (487000, 487055); # SKUPortalGunInvisMan 75
