INSERT INTO loottable(name) VALUES('airplane_master_of_elements'); # :airplane_master_of_elements_lt:
INSERT INTO loottable(name) VALUES('airplane_sister_of_the_spire'); # :airplane_sister_of_the_spire_lt:
INSERT INTO loottable(name) VALUES('airplane_the_gale_caller'); # :airplane_the_gale_caller_lt:
INSERT INTO loottable(name) VALUES('airplane_abec_ianor'); # :airplane_abec_ianor_lt:
INSERT INTO loottable(name) VALUES('airplane_alan_harten'); # :airplane_alan_harten_lt:
INSERT INTO loottable(name) VALUES('airplane_an_avenging_gazer'); # :airplane_an_avenging_gazer_lt:
INSERT INTO loottable(name) VALUES('airplane_an_azarack'); # :airplane_an_azarack_lt:
INSERT INTO loottable(name) VALUES('airplane_an_essence_carrier'); # :airplane_an_essence_carrier_lt:
INSERT INTO loottable(name) VALUES('airplane_an_essence_harvester'); # :airplane_an_essence_harvester_lt:
INSERT INTO loottable(name) VALUES('airplane_an_essence_tamer'); # :airplane_an_essence_tamer_lt:
INSERT INTO loottable(name) VALUES('airplane_an_undine_spirit'); # :airplane_an_undine_spirit_lt:
INSERT INTO loottable(name) VALUES('airplane_a_blade_storm'); # :airplane_a_blade_storm_lt:
INSERT INTO loottable(name) VALUES('airplane_a_crystaline_cloud'); # :airplane_a_crystaline_cloud_lt:
INSERT INTO loottable(name) VALUES('airplane_a_fatestealer_drake'); # :airplane_a_fatestealer_drake_lt:
INSERT INTO loottable(name) VALUES('airplane_a_gorgalask'); # :airplane_a_gorgalask_lt:
INSERT INTO loottable(name) VALUES('airplane_a_greater_sphinx'); # :airplane_a_greater_sphinx_lt:
INSERT INTO loottable(name) VALUES('airplane_a_gust_of_wind'); # :airplane_a_gust_of_wind_lt:
INSERT INTO loottable(name) VALUES('airplane_a_heartsbane_drake'); # :airplane_a_heartsbane_drake_lt:
INSERT INTO loottable(name) VALUES('airplane_a_presence'); # :airplane_a_presence_lt:
INSERT INTO loottable(name) VALUES('airplane_a_shimmering_meteor'); # :airplane_a_shimmering_meteor_lt:
INSERT INTO loottable(name) VALUES('airplane_a_soul_carrier'); # :airplane_a_soul_carrier_lt:
INSERT INTO loottable(name) VALUES('airplane_a_soul_harvester'); # :airplane_a_soul_harvester_lt:
INSERT INTO loottable(name) VALUES('airplane_a_soul_tamer'); # :airplane_a_soul_tamer_lt:
INSERT INTO loottable(name) VALUES('airplane_a_spiroc_arbiter'); # :airplane_a_spiroc_arbiter_lt:
INSERT INTO loottable(name) VALUES('airplane_a_spiroc_banisher'); # :airplane_a_spiroc_banisher_lt:
INSERT INTO loottable(name) VALUES('airplane_a_spiroc_caller'); # :airplane_a_spiroc_caller_lt:
INSERT INTO loottable(name) VALUES('airplane_a_spiroc_expulser'); # :airplane_a_spiroc_expulser_lt:
INSERT INTO loottable(name) VALUES('airplane_a_spiroc_revolter'); # :airplane_a_spiroc_revolter_lt:
INSERT INTO loottable(name) VALUES('airplane_a_spiroc_vanquisher'); # :airplane_a_spiroc_vanquisher_lt:
INSERT INTO loottable(name) VALUES('airplane_a_spiroc_walker'); # :airplane_a_spiroc_walker_lt:
INSERT INTO loottable(name) VALUES('airplane_a_sprited_harpie'); # :airplane_a_sprited_harpie_lt:
INSERT INTO loottable(name) VALUES('airplane_a_thunder_spirit'); # :airplane_a_thunder_spirit_lt:
INSERT INTO loottable(name) VALUES('airplane_a_thunder_spirit_princess'); # :airplane_a_thunder_spirit_princess_lt:
INSERT INTO loottable(name) VALUES('airplane_a_watchful_guard'); # :airplane_a_watchful_guard_lt:
INSERT INTO loottable(name) VALUES('airplane_a_windrider_drake'); # :airplane_a_windrider_drake_lt:
INSERT INTO loottable(name) VALUES('airplane_bazzt_zzzt'); # :airplane_bazzt_zzzt_lt:
INSERT INTO loottable(name) VALUES('airplane_bazzzazzt'); # :airplane_bazzzazzt_lt:
INSERT INTO loottable(name) VALUES('airplane_bizazzzt'); # :airplane_bizazzzt_lt:
INSERT INTO loottable(name) VALUES('airplane_bzzazzt'); # :airplane_bzzazzt_lt:
INSERT INTO loottable(name) VALUES('airplane_bzzzt'); # :airplane_bzzzt_lt:
INSERT INTO loottable(name) VALUES('airplane_cilin_spellsinger'); # :airplane_cilin_spellsinger_lt:
INSERT INTO loottable(name) VALUES('airplane_clarisa_spiritsong'); # :airplane_clarisa_spiritsong_lt:
INSERT INTO loottable(name) VALUES('airplane_dason_goldblade'); # :airplane_dason_goldblade_lt:
INSERT INTO loottable(name) VALUES('airplane_denise_songweaver'); # :airplane_denise_songweaver_lt:
INSERT INTO loottable(name) VALUES('airplane_deric_lennox'); # :airplane_deric_lennox_lt:
INSERT INTO loottable(name) VALUES('airplane_dirkog_steelhand'); # :airplane_dirkog_steelhand_lt:
INSERT INTO loottable(name) VALUES('airplane_drakis_bloodcaster'); # :airplane_drakis_bloodcaster_lt:
INSERT INTO loottable(name) VALUES('airplane_dugaas_helpyre'); # :airplane_dugaas_helpyre_lt:
INSERT INTO loottable(name) VALUES('airplane_enchanter_jolas'); # :airplane_enchanter_jolas_lt:
INSERT INTO loottable(name) VALUES('airplane_enderbite'); # :airplane_enderbite_lt:
INSERT INTO loottable(name) VALUES('airplane_eternal_spirit'); # :airplane_eternal_spirit_lt:
INSERT INTO loottable(name) VALUES('airplane_eye_of_veeshan'); # :airplane_eye_of_veeshan_lt:
INSERT INTO loottable(name) VALUES('airplane_falorn'); # :airplane_falorn_lt:
INSERT INTO loottable(name) VALUES('airplane_fenalla_moonshadow'); # :airplane_fenalla_moonshadow_lt:
INSERT INTO loottable(name) VALUES('airplane_frederic_calermin'); # :airplane_frederic_calermin_lt:
INSERT INTO loottable(name) VALUES('airplane_gina_mcstargan'); # :airplane_gina_mcstargan_lt:
INSERT INTO loottable(name) VALUES('airplane_gkzzallk'); # :airplane_gkzzallk_lt:
INSERT INTO loottable(name) VALUES('airplane_gordon_treecaller'); # :airplane_gordon_treecaller_lt:
INSERT INTO loottable(name) VALUES('airplane_gorgalosk'); # :airplane_gorgalosk_lt:
INSERT INTO loottable(name) VALUES('airplane_gragrot'); # :airplane_gragrot_lt:
INSERT INTO loottable(name) VALUES('airplane_gregori_lightbringer'); # :airplane_gregori_lightbringer_lt:
INSERT INTO loottable(name) VALUES('airplane_gwan'); # :airplane_gwan_lt:
INSERT INTO loottable(name) VALUES('airplane_heart_harpie'); # :airplane_heart_harpie_lt:
INSERT INTO loottable(name) VALUES('airplane_holwin'); # :airplane_holwin_lt:
INSERT INTO loottable(name) VALUES('airplane_inte_akera'); # :airplane_inte_akera_lt:
INSERT INTO loottable(name) VALUES('airplane_josin_faithbringer'); # :airplane_josin_faithbringer_lt:
INSERT INTO loottable(name) VALUES('airplane_jzil_gsix'); # :airplane_jzil_gsix_lt:
INSERT INTO loottable(name) VALUES('airplane_keeper_of_souls'); # :airplane_keeper_of_souls_lt:
INSERT INTO loottable(name) VALUES('airplane_kendrick'); # :airplane_kendrick_lt:
INSERT INTO loottable(name) VALUES('airplane_key_master'); # :airplane_key_master_lt:
INSERT INTO loottable(name) VALUES('airplane_kihun_solstin'); # :airplane_kihun_solstin_lt:
INSERT INTO loottable(name) VALUES('airplane_lelulean'); # :airplane_lelulean_lt:
INSERT INTO loottable(name) VALUES('airplane_magus_frinon'); # :airplane_magus_frinon_lt:
INSERT INTO loottable(name) VALUES('airplane_medicine_man_veetra'); # :airplane_medicine_man_veetra_lt:
INSERT INTO loottable(name) VALUES('airplane_neasin_leornic'); # :airplane_neasin_leornic_lt:
INSERT INTO loottable(name) VALUES('airplane_noble_dojorn'); # :airplane_noble_dojorn_lt:
INSERT INTO loottable(name) VALUES('airplane_ogog'); # :airplane_ogog_lt:
INSERT INTO loottable(name) VALUES('airplane_ooga'); # :airplane_ooga_lt:
INSERT INTO loottable(name) VALUES('airplane_overseer_of_air'); # :airplane_overseer_of_air_lt:
INSERT INTO loottable(name) VALUES('airplane_protector_of_sky'); # :airplane_protector_of_sky_lt:
INSERT INTO loottable(name) VALUES('airplane_ranger_spirit'); # :airplane_ranger_spirit_lt:
INSERT INTO loottable(name) VALUES('airplane_rayne'); # :airplane_rayne_lt:
INSERT INTO loottable(name) VALUES('airplane_relinin_skyrunner'); # :airplane_relinin_skyrunner_lt:
INSERT INTO loottable(name) VALUES('airplane_roanis_elindar'); # :airplane_roanis_elindar_lt:
INSERT INTO loottable(name) VALUES('airplane_sarkis_ebonblade'); # :airplane_sarkis_ebonblade_lt:
INSERT INTO loottable(name) VALUES('airplane_sirran_the_lunatic'); # :airplane_sirran_the_lunatic_lt:
INSERT INTO loottable(name) VALUES('airplane_strandar_pinemist'); # :airplane_strandar_pinemist_lt:
INSERT INTO loottable(name) VALUES('airplane_thalik_silenthand'); # :airplane_thalik_silenthand_lt:
INSERT INTO loottable(name) VALUES('airplane_the_hand_of_veeshan'); # :airplane_the_hand_of_veeshan_lt:
INSERT INTO loottable(name) VALUES('airplane_the_spiroc_guardian'); # :airplane_the_spiroc_guardian_lt:
INSERT INTO loottable(name) VALUES('airplane_the_spiroc_lord'); # :airplane_the_spiroc_lord_lt:
INSERT INTO loottable(name) VALUES('airplane_the_storm_mistress'); # :airplane_the_storm_mistress_lt:
INSERT INTO loottable(name) VALUES('airplane_ton_po'); # :airplane_ton_po_lt:
INSERT INTO loottable(name) VALUES('airplane_torgon_blademaster'); # :airplane_torgon_blademaster_lt:
INSERT INTO loottable(name) VALUES('airplane_tynicon_dlin'); # :airplane_tynicon_dlin_lt:
INSERT INTO loottable(name) VALUES('airplane_will_treewalker'); # :airplane_will_treewalker_lt:
INSERT INTO loottable(name) VALUES('airplane_wizard_schrock'); # :airplane_wizard_schrock_lt:
INSERT INTO loottable(name) VALUES('airplane_wu_the_enlightened'); # :airplane_wu_the_enlightened_lt:
INSERT INTO loottable(name) VALUES('airplane_zoner'); # :airplane_zoner_lt:
