UPDATE npc_types SET loottable_id = :akanon_a_brown_bear_lt: WHERE id in (55083); # a_brown_bear 4
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_alchemist_lt: WHERE id in (55098); # a_clockwork_alchemist 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_armorer_lt: WHERE id in (55107, 55108, 55141); # a_clockwork_armorer 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_baker_lt: WHERE id in (55140); # a_clockwork_baker 35
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_banker_lt: WHERE id in (55113, 55220); # a_clockwork_banker 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_barkeep_lt: WHERE id in (55105); # a_clockwork_barkeep 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_bowyer_lt: WHERE id in (55102); # a_clockwork_bowyer 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_brewmaster_lt: WHERE id in (55147); # a_clockwork_brewmaster 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_cobbler_lt: WHERE id in (55106); # a_clockwork_cobbler 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_grocer_lt: WHERE id in (55101); # a_clockwork_grocer 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_jeweler_lt: WHERE id in (55099, 55100); # a_clockwork_jeweler 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_merchant_lt: WHERE id in (55301, 55302, 55319, 55326, 55327, 55328, 55329, 55080, 55097, 55142); # a_clockwork_merchant 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_miner_lt: WHERE id in (55149); # a_clockwork_miner 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_potter_lt: WHERE id in (55143); # a_clockwork_potter 35
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_priest_lt: WHERE id in (55115); # a_clockwork_priest 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_receptionist_lt: WHERE id in (55087); # a_clockwork_receptionist 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_rogue_lt: WHERE id in (55114); # a_clockwork_rogue 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_sketcher_lt: WHERE id in (55148); # a_clockwork_sketcher 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_tailor_lt: WHERE id in (55111, 55112, 55144); # a_clockwork_tailor 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_tanner_lt: WHERE id in (55109, 55110); # a_clockwork_tanner 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_torturer_lt: WHERE id in (55089); # a_clockwork_torturer 40
UPDATE npc_types SET loottable_id = :akanon_a_clockwork_weaponsmith_lt: WHERE id in (55103, 55104); # a_clockwork_weaponsmith 40
UPDATE npc_types SET loottable_id = :akanon_a_decaying_gnome_skeleton_lt: WHERE id in (55007); # a_decaying_gnome_skeleton 1
UPDATE npc_types SET loottable_id = :akanon_a_defective_cleaner_lt: WHERE id in (55005); # a_defective_cleaner 1
UPDATE npc_types SET loottable_id = :akanon_a_frostfell_goblin_lt: WHERE id in (55336); # a_Frostfell_Goblin 1
UPDATE npc_types SET loottable_id = :akanon_a_lesser_minotaur_lt: WHERE id in (55081); # a_lesser_minotaur 9
UPDATE npc_types SET loottable_id = :akanon_a_mechanic_lt: WHERE id in (55091, 55092, 55093, 55094, 55095, 55096, 55218, 55219, 55008); # a_mechanic 23
UPDATE npc_types SET loottable_id = :akanon_a_rock_snake_lt: WHERE id in (55011); # a_rock_snake 1
UPDATE npc_types SET loottable_id = :akanon_a_rock_spider_lt: WHERE id in (55012); # a_rock_spider 2
UPDATE npc_types SET loottable_id = :akanon_a_tiger_lt: WHERE id in (55082); # a_tiger 8
UPDATE npc_types SET loottable_id = :akanon_baxok_curhunter_lt: WHERE id in (55136); # Baxok_Curhunter 61
UPDATE npc_types SET loottable_id = :akanon_cleaner_x_lt: WHERE id in (55161); # Cleaner_X 6
UPDATE npc_types SET loottable_id = :akanon_clockwork_cleaner_lt: WHERE id in (55183, 55036); # clockwork_cleaner 9
UPDATE npc_types SET loottable_id = :akanon_clockwork_iiiz_lt: WHERE id in (55084, 55215); # Clockwork_IIIZ 32
UPDATE npc_types SET loottable_id = :akanon_clockwork_iiz_lt: WHERE id in (55086); # Clockwork_IIZ 32
UPDATE npc_types SET loottable_id = :akanon_clockwork_ivb_lt: WHERE id in (55052, 55197); # Clockwork_IVB 31
UPDATE npc_types SET loottable_id = :akanon_clockwork_iz_lt: WHERE id in (55085, 55216); # Clockwork_IZ 28
UPDATE npc_types SET loottable_id = :akanon_clockwork_merchant_lt: WHERE id in (55303, 55304, 55305, 55306, 55307, 55308, 55309, 55310, 55311, 55312, 55313, 55314, 55315, 55316, 55317, 55318, 55320, 55321, 55322, 55323, 55324, 55325, 55330, 55331, 55332, 55333, 55079, 55013, 55014); # Clockwork_Merchant 40
UPDATE npc_types SET loottable_id = :akanon_clockwork_mx_lt: WHERE id in (55057); # Clockwork_MX 44
UPDATE npc_types SET loottable_id = :akanon_clockwork_scrubber_lt: WHERE id in (55001, 55010, 55035); # clockwork_scrubber 6
UPDATE npc_types SET loottable_id = :akanon_clockwork_smithxiii_lt: WHERE id in (55021); # Clockwork_SmithXIII 40
UPDATE npc_types SET loottable_id = :akanon_clockwork_sweeper_lt: WHERE id in (55009); # clockwork_sweeper 15
UPDATE npc_types SET loottable_id = :akanon_clockwork_viix_lt: WHERE id in (55017); # Clockwork_VIIX 55
UPDATE npc_types SET loottable_id = :akanon_clockwork_xe_lt: WHERE id in (55076); # Clockwork_XE 30
UPDATE npc_types SET loottable_id = :akanon_clockwork_xib_lt: WHERE id in (55067); # Clockwork_XIB 31
UPDATE npc_types SET loottable_id = :akanon_clockwork_xie_lt: WHERE id in (55073, 55210); # Clockwork_XIE 28
UPDATE npc_types SET loottable_id = :akanon_clockwork_xiib_lt: WHERE id in (55066, 55206); # Clockwork_XIIB 28
UPDATE npc_types SET loottable_id = :akanon_clockwork_xiic_lt: WHERE id in (55051, 55196); # Clockwork_XIIC 38
UPDATE npc_types SET loottable_id = :akanon_clockwork_xiie_lt: WHERE id in (55171, 55002); # Clockwork_XIIE 28
UPDATE npc_types SET loottable_id = :akanon_clockwork_xiiib_lt: WHERE id in (55043); # Clockwork_XIIIB 32
UPDATE npc_types SET loottable_id = :akanon_clockwork_xive_lt: WHERE id in (55071); # Clockwork_XIVE 29
UPDATE npc_types SET loottable_id = :akanon_clockwork_xixa_lt: WHERE id in (55166, 55172, 55004); # Clockwork_XIXA 21
UPDATE npc_types SET loottable_id = :akanon_clockwork_xva_lt: WHERE id in (55065, 55205); # Clockwork_XVA 22
UPDATE npc_types SET loottable_id = :akanon_clockwork_xvd_lt: WHERE id in (55075, 55212); # Clockwork_XVD 33
UPDATE npc_types SET loottable_id = :akanon_clockwork_xve_lt: WHERE id in (55077); # Clockwork_XVE 30
UPDATE npc_types SET loottable_id = :akanon_clockwork_xvib_lt: WHERE id in (55063, 55203); # Clockwork_XVIB 28
UPDATE npc_types SET loottable_id = :akanon_clockwork_xvid_lt: WHERE id in (55072, 55209); # Clockwork_XVID 37
UPDATE npc_types SET loottable_id = :akanon_clockwork_xvie_lt: WHERE id in (55047, 55192); # Clockwork_XVIE 31
UPDATE npc_types SET loottable_id = :akanon_clockwork_xviia_lt: WHERE id in (55039); # Clockwork_XVIIA 18
UPDATE npc_types SET loottable_id = :akanon_clockwork_xviib_lt: WHERE id in (55064, 55204); # Clockwork_XVIIB 31
UPDATE npc_types SET loottable_id = :akanon_clockwork_xviic_lt: WHERE id in (55165, 55170, 55222, 55003); # Clockwork_XVIIC 39
UPDATE npc_types SET loottable_id = :akanon_clockwork_xviiib_lt: WHERE id in (55046); # Clockwork_XVIIIB 32
UPDATE npc_types SET loottable_id = :akanon_clockwork_xviiie_lt: WHERE id in (55041); # Clockwork_XVIIIE 29
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxa_lt: WHERE id in (55045, 55191); # Clockwork_XXA 22
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxb_lt: WHERE id in (55054, 55199); # Clockwork_XXB 32
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxd_lt: WHERE id in (55078, 55213); # Clockwork_XXD 37
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxe_lt: WHERE id in (55070, 55208); # Clockwork_XXE 31
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxia_lt: WHERE id in (55062, 55202); # Clockwork_XXIA 9
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxib_lt: WHERE id in (55055); # Clockwork_XXIB 29
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxid_lt: WHERE id in (55074, 55211); # Clockwork_XXID 35
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxiib_lt: WHERE id in (55186, 55038); # Clockwork_XXIIB 31
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxiiia_lt: WHERE id in (55044, 55190); # Clockwork_XXIIIA 12
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxivd_lt: WHERE id in (55040); # Clockwork_XXIVD 35
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxixb_lt: WHERE id in (55050, 55195); # Clockwork_XXIXB 28
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxva_lt: WHERE id in (55060, 55200); # Clockwork_XXVA 21
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxvd_lt: WHERE id in (55053, 55198); # Clockwork_XXVD 34
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxvic_lt: WHERE id in (55061, 55201); # Clockwork_XXVIC 39
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxviib_lt: WHERE id in (55048, 55193); # Clockwork_XXVIIB 31
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxviic_lt: WHERE id in (55185, 55037); # Clockwork_XXVIIC 39
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxviiib_lt: WHERE id in (55049, 55194); # Clockwork_XXVIIIB 29
UPDATE npc_types SET loottable_id = :akanon_clockwork_xxxd_lt: WHERE id in (55068, 55207); # Clockwork_XXXD 35
UPDATE npc_types SET loottable_id = :akanon_derthix_gibblix_lt: WHERE id in (55020); # Derthix_Gibblix 61
UPDATE npc_types SET loottable_id = :akanon_dewis_caneal_lt: WHERE id in (55125); # Dewis_Caneal 61
UPDATE npc_types SET loottable_id = :akanon_digetha_chogaller_lt: WHERE id in (55138); # Digetha_Chogaller 61
UPDATE npc_types SET loottable_id = :akanon_drekon_vebnebber_lt: WHERE id in (55116); # Drekon_Vebnebber 20
UPDATE npc_types SET loottable_id = :akanon_drigaz_grumblegrowl_lt: WHERE id in (55157); # Drigaz_Grumblegrowl 34
UPDATE npc_types SET loottable_id = :akanon_duster_v_lt: WHERE id in (55163); # Duster_V 6
UPDATE npc_types SET loottable_id = :akanon_duster_x_lt: WHERE id in (55334); # Duster_X 8
UPDATE npc_types SET loottable_id = :akanon_eonis_mournunder_lt: WHERE id in (55126); # Eonis_Mournunder 61
UPDATE npc_types SET loottable_id = :akanon_evah_xokez_lt: WHERE id in (55124); # Evah_Xokez 61
UPDATE npc_types SET loottable_id = :akanon_exterminator_viii_lt: WHERE id in (55175, 55016); # Exterminator_VIII 33
UPDATE npc_types SET loottable_id = :akanon_fireworks_engineer_fabdabus_lt: WHERE id in (55338); # Fireworks_Engineer_Fabdabus 1
UPDATE npc_types SET loottable_id = :akanon_flapti_bizttrin_lt: WHERE id in (55156); # Flapti_Bizttrin 65
UPDATE npc_types SET loottable_id = :akanon_garret_zethkog_lt: WHERE id in (55145); # Garret_Zethkog 61
UPDATE npc_types SET loottable_id = :akanon_gilipus_lt: WHERE id in (55159); # Gilipus 20
UPDATE npc_types SET loottable_id = :akanon_glerbella_gibblix_lt: WHERE id in (55022); # Glerbella_Gibblix 35
UPDATE npc_types SET loottable_id = :akanon_golsodix_biroboddle_lt: WHERE id in (55153); # Golsodix_Biroboddle 61
UPDATE npc_types SET loottable_id = :akanon_guide_i_lt: WHERE id in (55179, 55031); # Guide_I 31
UPDATE npc_types SET loottable_id = :akanon_guide_ii_lt: WHERE id in (55181, 55033); # Guide_II 32
UPDATE npc_types SET loottable_id = :akanon_guide_iii_lt: WHERE id in (55180, 55032); # Guide_III 28
UPDATE npc_types SET loottable_id = :akanon_guide_iv_lt: WHERE id in (55177, 55029); # Guide_IV 31
UPDATE npc_types SET loottable_id = :akanon_guide_v_lt: WHERE id in (55178, 55030); # Guide_V 28
UPDATE npc_types SET loottable_id = :akanon_guide_vi_lt: WHERE id in (55176, 55028); # Guide_VI 31
UPDATE npc_types SET loottable_id = :akanon_hargar_the_velium_chef_lt: WHERE id in (55337); # Hargar_the_Velium_Chef 1
UPDATE npc_types SET loottable_id = :akanon_iony_gredlong_lt: WHERE id in (55139); # Iony_Gredlong 61
UPDATE npc_types SET loottable_id = :akanon_jarah_reskan_lt: WHERE id in (55135); # Jarah_Reskan 61
UPDATE npc_types SET loottable_id = :akanon_juline_urncaller_lt: WHERE id in (55132); # Juline_Urncaller 61
UPDATE npc_types SET loottable_id = :akanon_kaxon_frennor_lt: WHERE id in (55122); # Kaxon_Frennor 61
UPDATE npc_types SET loottable_id = :akanon_kimble_nogflop_lt: WHERE id in (55137); # Kimble_Nogflop 40
UPDATE npc_types SET loottable_id = :akanon_king_ak-anon_lt: WHERE id in (55088); # King_Ak-Anon 60
UPDATE npc_types SET loottable_id = :akanon_kozyn_gigglephizz_lt: WHERE id in (55164, 55223); # Kozyn_Gigglephizz 34
UPDATE npc_types SET loottable_id = :akanon_larkon_theardor_lt: WHERE id in (55056); # Larkon_Theardor 61
UPDATE npc_types SET loottable_id = :akanon_lewis_reldnok_lt: WHERE id in (55146); # Lewis_Reldnok 61
UPDATE npc_types SET loottable_id = :akanon_lobal_postugger_lt: WHERE id in (55127); # Lobal_Postugger 61
UPDATE npc_types SET loottable_id = :akanon_lyra_lyrestringer_lt: WHERE id in (55155); # Lyra_Lyrestringer 25
UPDATE npc_types SET loottable_id = :akanon_manik_compolten_lt: WHERE id in (55118); # Manik_Compolten 61
UPDATE npc_types SET loottable_id = :akanon_mimtia_zethkog_lt: WHERE id in (55024); # Mimtia_Zethkog 35
UPDATE npc_types SET loottable_id = :akanon_morlan_tanlonikan_lt: WHERE id in (55340); # Morlan_Tanlonikan 70
UPDATE npc_types SET loottable_id = :akanon_narron_jenork_lt: WHERE id in (55117); # Narron_Jenork 61
UPDATE npc_types SET loottable_id = :akanon_naygog_mitope_lt: WHERE id in (55120); # Naygog_Mitope 61
UPDATE npc_types SET loottable_id = :akanon_nonnie_texaker_lt: WHERE id in (55131); # Nonnie_Texaker 61
UPDATE npc_types SET loottable_id = :akanon_obsolete_model_lt: WHERE id in (55160, 55162, 55168, 55174, 55225, 55034); # obsolete_model 3
UPDATE npc_types SET loottable_id = :akanon_priest_of_discord_lt: WHERE id in (55158); # Priest_of_Discord 50
UPDATE npc_types SET loottable_id = :akanon_rebbie_romblerum_lt: WHERE id in (55023); # Rebbie_Romblerum 35
UPDATE npc_types SET loottable_id = :akanon_red_v_lt: WHERE id in (55167, 55224); # Red_V 5
UPDATE npc_types SET loottable_id = :akanon_reuben_reldnok_lt: WHERE id in (55339); # Reuben_Reldnok 70
UPDATE npc_types SET loottable_id = :akanon_rilgor_plegnog_lt: WHERE id in (55121); # Rilgor_Plegnog 61
UPDATE npc_types SET loottable_id = :akanon_rylin_coil_lt: WHERE id in (55027); # Rylin_Coil 30
UPDATE npc_types SET loottable_id = :akanon_sanfyrd_featherhead_lt: WHERE id in (55090); # Sanfyrd_Featherhead 25
UPDATE npc_types SET loottable_id = :akanon_santug_claugg_lt: WHERE id in (55335); # Santug_Claugg 70
UPDATE npc_types SET loottable_id = :akanon_scrubber_iv_lt: WHERE id in (55169, 55221, 55000); # Scrubber_IV 9
UPDATE npc_types SET loottable_id = :akanon_silox_azrix_lt: WHERE id in (55006); # Silox_Azrix 60
UPDATE npc_types SET loottable_id = :akanon_soulbinder_toglonoit_lt: WHERE id in (55152); # Soulbinder_Toglonoit 65
UPDATE npc_types SET loottable_id = :akanon_tamno_shifa_lt: WHERE id in (55019); # Tamno_Shifa 65
UPDATE npc_types SET loottable_id = :akanon_tergon_brenclog_lt: WHERE id in (55133); # Tergon_Brenclog 61
UPDATE npc_types SET loottable_id = :akanon_tesil_gludien_lt: WHERE id in (55154); # Tesil_Gludien 40
UPDATE npc_types SET loottable_id = :akanon_tilkzog_mournunder_lt: WHERE id in (55026); # Tilkzog_Mournunder 35
UPDATE npc_types SET loottable_id = :akanon_tobon_starpyre_lt: WHERE id in (55130); # Tobon_Starpyre 61
UPDATE npc_types SET loottable_id = :akanon_useah_harnbock_lt: WHERE id in (55129); # Useah_Harnbock 61
UPDATE npc_types SET loottable_id = :akanon_vaenor_husga_lt: WHERE id in (55123); # Vaenor_Husga 61
UPDATE npc_types SET loottable_id = :akanon_velena_corgtec_lt: WHERE id in (55119); # Velena_Corgtec 61
UPDATE npc_types SET loottable_id = :akanon_watchman_dool_lt: WHERE id in (55042); # Watchman_Dool 35
UPDATE npc_types SET loottable_id = :akanon_watchman_hodl_lt: WHERE id in (55059); # Watchman_Hodl 35
UPDATE npc_types SET loottable_id = :akanon_watchman_lyl_lt: WHERE id in (55069); # Watchman_Lyl 35
UPDATE npc_types SET loottable_id = :akanon_watchman_qiz_lt: WHERE id in (55058); # Watchman_Qiz 35
UPDATE npc_types SET loottable_id = :akanon_welno_tanlonikan_lt: WHERE id in (55128); # Welno_Tanlonikan 70
UPDATE npc_types SET loottable_id = :akanon_windlebeck_tobokog_lt: WHERE id in (55025); # Windlebeck_Tobokog 35
UPDATE npc_types SET loottable_id = :akanon_wuggan_azusphere_lt: WHERE id in (55134); # Wuggan_Azusphere 61
UPDATE npc_types SET loottable_id = :akanon_xalirilan_zarinokosalio_lt: WHERE id in (55015); # Xalirilan_Zarinokosalio 61
UPDATE npc_types SET loottable_id = :akanon_zapho_the_ancient_lt: WHERE id in (55151); # Zapho_the_Ancient 61
UPDATE npc_types SET loottable_id = :akanon_zenrel_ottonoggin_lt: WHERE id in (55150); # Zenrel_Ottonoggin 25
UPDATE npc_types SET loottable_id = :akanon_zigg_flin_lt: WHERE id in (55018); # Zigg_Flin 25
