(:beholder_a_goblin_alchemist_lt:, :cloth_small_ld:, 1),
(:beholder_a_goblin_alchemist_lt:, :rusty_ld:, 5),
(:beholder_a_goblin_lookout_lt:, :cloth_small_ld:, 1),
(:beholder_a_goblin_lookout_lt:, :rusty_ld:, 5),
(:beholder_a_goblin_sentry_lt:, :cloth_small_ld:, 1),
(:beholder_a_goblin_sentry_lt:, :rusty_ld:, 5),
