INSERT INTO loottable(name) VALUES('butcher_signus_boran'); # :butcher_signus_boran_lt:
INSERT INTO loottable(name) VALUES('butcher_kanthuk_ogrebane'); # :butcher_kanthuk_ogrebane_lt:
INSERT INTO loottable(name) VALUES('butcher_maidens_voyage'); # :butcher_maidens_voyage_lt:
INSERT INTO loottable(name) VALUES('butcher_translocator_fithop'); # :butcher_translocator_fithop_lt:
INSERT INTO loottable(name) VALUES('butcher_translocator_gethia'); # :butcher_translocator_gethia_lt:
INSERT INTO loottable(name) VALUES('butcher__'); # :butcher___lt:
INSERT INTO loottable(name) VALUES('butcher_alga_bruntbuckler'); # :butcher_alga_bruntbuckler_lt:
INSERT INTO loottable(name) VALUES('butcher_alun_bilgum'); # :butcher_alun_bilgum_lt:
INSERT INTO loottable(name) VALUES('butcher_an_aqua_goblin'); # :butcher_an_aqua_goblin_lt:
INSERT INTO loottable(name) VALUES('butcher_an_aqua_goblin_wizard'); # :butcher_an_aqua_goblin_wizard_lt:
INSERT INTO loottable(name) VALUES('butcher_an_enraged_goblin'); # :butcher_an_enraged_goblin_lt:
INSERT INTO loottable(name) VALUES('butcher_an_orc_oracle'); # :butcher_an_orc_oracle_lt:
INSERT INTO loottable(name) VALUES('butcher_an_orc_scoutsman'); # :butcher_an_orc_scoutsman_lt:
INSERT INTO loottable(name) VALUES('butcher_an_undead_bishop'); # :butcher_an_undead_bishop_lt:
INSERT INTO loottable(name) VALUES('butcher_an_undead_king'); # :butcher_an_undead_king_lt:
INSERT INTO loottable(name) VALUES('butcher_an_undead_pawn'); # :butcher_an_undead_pawn_lt:
INSERT INTO loottable(name) VALUES('butcher_an_undead_rook'); # :butcher_an_undead_rook_lt:
INSERT INTO loottable(name) VALUES('butcher_aqua_goblin_marauder'); # :butcher_aqua_goblin_marauder_lt:
INSERT INTO loottable(name) VALUES('butcher_atwin_keladryn'); # :butcher_atwin_keladryn_lt:
INSERT INTO loottable(name) VALUES('butcher_ayen_rundlor'); # :butcher_ayen_rundlor_lt:
INSERT INTO loottable(name) VALUES('butcher_a_bat'); # :butcher_a_bat_lt:
INSERT INTO loottable(name) VALUES('butcher_a_crazed_goblin'); # :butcher_a_crazed_goblin_lt:
INSERT INTO loottable(name) VALUES('butcher_a_decaying_dwarf_skeleton'); # :butcher_a_decaying_dwarf_skeleton_lt:
INSERT INTO loottable(name) VALUES('butcher_a_dismal_rage_initiate'); # :butcher_a_dismal_rage_initiate_lt:
INSERT INTO loottable(name) VALUES('butcher_a_dwarf_skeleton'); # :butcher_a_dwarf_skeleton_lt:
INSERT INTO loottable(name) VALUES('butcher_a_dwarven_bandit'); # :butcher_a_dwarven_bandit_lt:
INSERT INTO loottable(name) VALUES('butcher_a_giant_bat'); # :butcher_a_giant_bat_lt:
INSERT INTO loottable(name) VALUES('butcher_a_giant_scarab'); # :butcher_a_giant_scarab_lt:
INSERT INTO loottable(name) VALUES('butcher_a_goblin'); # :butcher_a_goblin_lt:
INSERT INTO loottable(name) VALUES('butcher_a_goblin_grunt'); # :butcher_a_goblin_grunt_lt:
INSERT INTO loottable(name) VALUES('butcher_a_goblin_shaman'); # :butcher_a_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('butcher_a_goblin_warrior'); # :butcher_a_goblin_warrior_lt:
INSERT INTO loottable(name) VALUES('butcher_a_goblin_whelp'); # :butcher_a_goblin_whelp_lt:
INSERT INTO loottable(name) VALUES('butcher_a_goblin_wizard'); # :butcher_a_goblin_wizard_lt:
INSERT INTO loottable(name) VALUES('butcher_a_greedy_beggar'); # :butcher_a_greedy_beggar_lt:
INSERT INTO loottable(name) VALUES('butcher_a_krag_chick'); # :butcher_a_krag_chick_lt:
INSERT INTO loottable(name) VALUES('butcher_a_krag_elder'); # :butcher_a_krag_elder_lt:
INSERT INTO loottable(name) VALUES('butcher_a_large_skunk'); # :butcher_a_large_skunk_lt:
INSERT INTO loottable(name) VALUES('butcher_a_large_snake'); # :butcher_a_large_snake_lt:
INSERT INTO loottable(name) VALUES('butcher_a_large_spider'); # :butcher_a_large_spider_lt:
INSERT INTO loottable(name) VALUES('butcher_a_lesser_spirit'); # :butcher_a_lesser_spirit_lt:
INSERT INTO loottable(name) VALUES('butcher_a_lowland_basilisk'); # :butcher_a_lowland_basilisk_lt:
INSERT INTO loottable(name) VALUES('butcher_a_rock_spiderling'); # :butcher_a_rock_spiderling_lt:
INSERT INTO loottable(name) VALUES('butcher_a_snake'); # :butcher_a_snake_lt:
INSERT INTO loottable(name) VALUES('butcher_a_towering_brute'); # :butcher_a_towering_brute_lt:
INSERT INTO loottable(name) VALUES('butcher_a_tunarian_scout'); # :butcher_a_tunarian_scout_lt:
INSERT INTO loottable(name) VALUES('butcher_a_wandering_greenblood'); # :butcher_a_wandering_greenblood_lt:
INSERT INTO loottable(name) VALUES('butcher_a_worker_scarab'); # :butcher_a_worker_scarab_lt:
INSERT INTO loottable(name) VALUES('butcher_balen_kalgunn'); # :butcher_balen_kalgunn_lt:
INSERT INTO loottable(name) VALUES('butcher_baradiella_skymoor'); # :butcher_baradiella_skymoor_lt:
INSERT INTO loottable(name) VALUES('butcher_barma_dunfire'); # :butcher_barma_dunfire_lt:
INSERT INTO loottable(name) VALUES('butcher_biski_teezlen'); # :butcher_biski_teezlen_lt:
INSERT INTO loottable(name) VALUES('butcher_blyle_bundin'); # :butcher_blyle_bundin_lt:
INSERT INTO loottable(name) VALUES('butcher_captains_skiff'); # :butcher_captains_skiff_lt:
INSERT INTO loottable(name) VALUES('butcher_corflunk'); # :butcher_corflunk_lt:
INSERT INTO loottable(name) VALUES('butcher_crytil_dunfire'); # :butcher_crytil_dunfire_lt:
INSERT INTO loottable(name) VALUES('butcher_dalbar_tarbrind'); # :butcher_dalbar_tarbrind_lt:
INSERT INTO loottable(name) VALUES('butcher_dandalek_swillslammer'); # :butcher_dandalek_swillslammer_lt:
INSERT INTO loottable(name) VALUES('butcher_dapper_blackhammer'); # :butcher_dapper_blackhammer_lt:
INSERT INTO loottable(name) VALUES('butcher_darm_dundam'); # :butcher_darm_dundam_lt:
INSERT INTO loottable(name) VALUES('butcher_deldryn_splendyr'); # :butcher_deldryn_splendyr_lt:
INSERT INTO loottable(name) VALUES('butcher_delin_ironblend'); # :butcher_delin_ironblend_lt:
INSERT INTO loottable(name) VALUES('butcher_den_ironblend'); # :butcher_den_ironblend_lt:
INSERT INTO loottable(name) VALUES('butcher_doran_glosglen'); # :butcher_doran_glosglen_lt:
INSERT INTO loottable(name) VALUES('butcher_droongar_kann'); # :butcher_droongar_kann_lt:
INSERT INTO loottable(name) VALUES('butcher_dru_razbind'); # :butcher_dru_razbind_lt:
INSERT INTO loottable(name) VALUES('butcher_durkis_battlemore'); # :butcher_durkis_battlemore_lt:
INSERT INTO loottable(name) VALUES('butcher_ellona'); # :butcher_ellona_lt:
INSERT INTO loottable(name) VALUES('butcher_emeraldman'); # :butcher_emeraldman_lt:
INSERT INTO loottable(name) VALUES('butcher_felen_razdal'); # :butcher_felen_razdal_lt:
INSERT INTO loottable(name) VALUES('butcher_feriella_vorana'); # :butcher_feriella_vorana_lt:
INSERT INTO loottable(name) VALUES('butcher_fugan_mumfur'); # :butcher_fugan_mumfur_lt:
INSERT INTO loottable(name) VALUES('butcher_gaellane_ivyweaver'); # :butcher_gaellane_ivyweaver_lt:
INSERT INTO loottable(name) VALUES('butcher_gamin_griststone'); # :butcher_gamin_griststone_lt:
INSERT INTO loottable(name) VALUES('butcher_ganbar_dundam'); # :butcher_ganbar_dundam_lt:
INSERT INTO loottable(name) VALUES('butcher_gand_truelink'); # :butcher_gand_truelink_lt:
INSERT INTO loottable(name) VALUES('butcher_gann_dunbull'); # :butcher_gann_dunbull_lt:
INSERT INTO loottable(name) VALUES('butcher_gan_ironsworthy'); # :butcher_gan_ironsworthy_lt:
INSERT INTO loottable(name) VALUES('butcher_gibi_bilgum'); # :butcher_gibi_bilgum_lt:
INSERT INTO loottable(name) VALUES('butcher_glisse_bluesea'); # :butcher_glisse_bluesea_lt:
INSERT INTO loottable(name) VALUES('butcher_glopruk_tigglum'); # :butcher_glopruk_tigglum_lt:
INSERT INTO loottable(name) VALUES('butcher_glorin_binfurr'); # :butcher_glorin_binfurr_lt:
INSERT INTO loottable(name) VALUES('butcher_glubbsink'); # :butcher_glubbsink_lt:
INSERT INTO loottable(name) VALUES('butcher_glynda_smeltpot'); # :butcher_glynda_smeltpot_lt:
INSERT INTO loottable(name) VALUES('butcher_glynn_smeltpot'); # :butcher_glynn_smeltpot_lt:
INSERT INTO loottable(name) VALUES('butcher_gridbar_galund'); # :butcher_gridbar_galund_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_armandin'); # :butcher_guard_armandin_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_belg'); # :butcher_guard_belg_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_burr'); # :butcher_guard_burr_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_clendin'); # :butcher_guard_clendin_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_dunil'); # :butcher_guard_dunil_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_dunn'); # :butcher_guard_dunn_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_gabel'); # :butcher_guard_gabel_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_gonin'); # :butcher_guard_gonin_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_grae'); # :butcher_guard_grae_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_haendar'); # :butcher_guard_haendar_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_haldin'); # :butcher_guard_haldin_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_hartt'); # :butcher_guard_hartt_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_kizzburr'); # :butcher_guard_kizzburr_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_kyte'); # :butcher_guard_kyte_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_mandin'); # :butcher_guard_mandin_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_norin'); # :butcher_guard_norin_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_rundul'); # :butcher_guard_rundul_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_rylin'); # :butcher_guard_rylin_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_sornn'); # :butcher_guard_sornn_lt:
INSERT INTO loottable(name) VALUES('butcher_guard_srinn'); # :butcher_guard_srinn_lt:
INSERT INTO loottable(name) VALUES('butcher_gundl'); # :butcher_gundl_lt:
INSERT INTO loottable(name) VALUES('butcher_happ_findlefinn'); # :butcher_happ_findlefinn_lt:
INSERT INTO loottable(name) VALUES('butcher_harbormaster_ironbeard'); # :butcher_harbormaster_ironbeard_lt:
INSERT INTO loottable(name) VALUES('butcher_iglan_thranon'); # :butcher_iglan_thranon_lt:
INSERT INTO loottable(name) VALUES('butcher_inudul_dumirgun'); # :butcher_inudul_dumirgun_lt:
INSERT INTO loottable(name) VALUES('butcher_izbal_brightblaze'); # :butcher_izbal_brightblaze_lt:
INSERT INTO loottable(name) VALUES('butcher_jelqtan_oretnai'); # :butcher_jelqtan_oretnai_lt:
INSERT INTO loottable(name) VALUES('butcher_jilsuia_lluarea'); # :butcher_jilsuia_lluarea_lt:
INSERT INTO loottable(name) VALUES('butcher_kaila_rucksack'); # :butcher_kaila_rucksack_lt:
INSERT INTO loottable(name) VALUES('butcher_kancompan'); # :butcher_kancompan_lt:
INSERT INTO loottable(name) VALUES('butcher_kandin_firepot'); # :butcher_kandin_firepot_lt:
INSERT INTO loottable(name) VALUES('butcher_kanthuk_ogrebane_'); # :butcher_kanthuk_ogrebane__lt:
INSERT INTO loottable(name) VALUES('butcher_keldyn_dunfire'); # :butcher_keldyn_dunfire_lt:
INSERT INTO loottable(name) VALUES('butcher_kroggl'); # :butcher_kroggl_lt:
INSERT INTO loottable(name) VALUES('butcher_lann_dabldrin'); # :butcher_lann_dabldrin_lt:
INSERT INTO loottable(name) VALUES('butcher_lieutenant_gattek'); # :butcher_lieutenant_gattek_lt:
INSERT INTO loottable(name) VALUES('butcher_magnus_boran'); # :butcher_magnus_boran_lt:
INSERT INTO loottable(name) VALUES('butcher_magus_tira'); # :butcher_magus_tira_lt:
INSERT INTO loottable(name) VALUES('butcher_margyl_darklin'); # :butcher_margyl_darklin_lt:
INSERT INTO loottable(name) VALUES('butcher_mimzit_furnov'); # :butcher_mimzit_furnov_lt:
INSERT INTO loottable(name) VALUES('butcher_nalda_griststone'); # :butcher_nalda_griststone_lt:
INSERT INTO loottable(name) VALUES('butcher_nyzil_bloodforge'); # :butcher_nyzil_bloodforge_lt:
INSERT INTO loottable(name) VALUES('butcher_orc_centurion'); # :butcher_orc_centurion_lt:
INSERT INTO loottable(name) VALUES('butcher_orc_pawn'); # :butcher_orc_pawn_lt:
INSERT INTO loottable(name) VALUES('butcher_orc_runner'); # :butcher_orc_runner_lt:
INSERT INTO loottable(name) VALUES('butcher_parn_gylwyn'); # :butcher_parn_gylwyn_lt:
INSERT INTO loottable(name) VALUES('butcher_peg_leg'); # :butcher_peg_leg_lt:
INSERT INTO loottable(name) VALUES('butcher_qued'); # :butcher_qued_lt:
INSERT INTO loottable(name) VALUES('butcher_renell_bekea'); # :butcher_renell_bekea_lt:
INSERT INTO loottable(name) VALUES('butcher_rokaon_sternheart'); # :butcher_rokaon_sternheart_lt:
INSERT INTO loottable(name) VALUES('butcher_sigmas_boran'); # :butcher_sigmas_boran_lt:
INSERT INTO loottable(name) VALUES('butcher_signus_boran'); # :butcher_signus_boran_lt:
INSERT INTO loottable(name) VALUES('butcher_siltria_marwind'); # :butcher_siltria_marwind_lt:
INSERT INTO loottable(name) VALUES('butcher_sirensbane'); # :butcher_sirensbane_lt:
INSERT INTO loottable(name) VALUES('butcher_soulbinder_tania'); # :butcher_soulbinder_tania_lt:
INSERT INTO loottable(name) VALUES('butcher_stormbreaker'); # :butcher_stormbreaker_lt:
INSERT INTO loottable(name) VALUES('butcher_stump_rundl'); # :butcher_stump_rundl_lt:
INSERT INTO loottable(name) VALUES('butcher_tagnis_ginfarr'); # :butcher_tagnis_ginfarr_lt:
INSERT INTO loottable(name) VALUES('butcher_thar_kelgand'); # :butcher_thar_kelgand_lt:
INSERT INTO loottable(name) VALUES('butcher_the_fabled_corflunk'); # :butcher_the_fabled_corflunk_lt:
INSERT INTO loottable(name) VALUES('butcher_the_fabled_zarchoomi'); # :butcher_the_fabled_zarchoomi_lt:
INSERT INTO loottable(name) VALUES('butcher_tok_skan'); # :butcher_tok_skan_lt:
INSERT INTO loottable(name) VALUES('butcher_urazun_thranon'); # :butcher_urazun_thranon_lt:
INSERT INTO loottable(name) VALUES('butcher_vedico_windwisper'); # :butcher_vedico_windwisper_lt:
INSERT INTO loottable(name) VALUES('butcher_vual_stoutest'); # :butcher_vual_stoutest_lt:
INSERT INTO loottable(name) VALUES('butcher_walnan'); # :butcher_walnan_lt:
INSERT INTO loottable(name) VALUES('butcher_xyzelauna_tuvalzir'); # :butcher_xyzelauna_tuvalzir_lt:
INSERT INTO loottable(name) VALUES('butcher_zarchoomi'); # :butcher_zarchoomi_lt:
