UPDATE npc_types SET loottable_id = :butcher_signus_boran_lt: WHERE id in (68266); # ##Signus_Boran 70
UPDATE npc_types SET loottable_id = :butcher_kanthuk_ogrebane_lt: WHERE id in (68066); # #Kanthuk_Ogrebane 23
UPDATE npc_types SET loottable_id = :butcher_maidens_voyage_lt: WHERE id in (68260); # #Maidens_Voyage 50
UPDATE npc_types SET loottable_id = :butcher_translocator_fithop_lt: WHERE id in (68135); # #Translocator_Fithop 1
UPDATE npc_types SET loottable_id = :butcher_translocator_gethia_lt: WHERE id in (68134); # #Translocator_Gethia 1
UPDATE npc_types SET loottable_id = :butcher___lt: WHERE id in (68262); # #_# 60
UPDATE npc_types SET loottable_id = :butcher_alga_bruntbuckler_lt: WHERE id in (68053); # Alga_Bruntbuckler 41
UPDATE npc_types SET loottable_id = :butcher_alun_bilgum_lt: WHERE id in (68091); # Alun_Bilgum 35
UPDATE npc_types SET loottable_id = :butcher_an_aqua_goblin_lt: WHERE id in (68140, 68142, 68186); # an_aqua_goblin 7
UPDATE npc_types SET loottable_id = :butcher_an_aqua_goblin_wizard_lt: WHERE id in (68189); # an_aqua_goblin_wizard 17
UPDATE npc_types SET loottable_id = :butcher_an_enraged_goblin_lt: WHERE id in (68163, 68203, 68086); # an_enraged_goblin 13
UPDATE npc_types SET loottable_id = :butcher_an_orc_oracle_lt: WHERE id in (68168, 68055); # an_orc_oracle 13
UPDATE npc_types SET loottable_id = :butcher_an_orc_scoutsman_lt: WHERE id in (68169, 68200, 68056); # an_orc_scoutsman 12
UPDATE npc_types SET loottable_id = :butcher_an_undead_bishop_lt: WHERE id in (68199, 68210); # an_undead_bishop 10
UPDATE npc_types SET loottable_id = :butcher_an_undead_king_lt: WHERE id in (68241, 68250); # an_undead_king 15
UPDATE npc_types SET loottable_id = :butcher_an_undead_pawn_lt: WHERE id in (68158, 68030, 68036); # an_undead_pawn 10
UPDATE npc_types SET loottable_id = :butcher_an_undead_rook_lt: WHERE id in (68151); # an_undead_rook 9
UPDATE npc_types SET loottable_id = :butcher_aqua_goblin_marauder_lt: WHERE id in (68059, 68060, 68061); # aqua_goblin_marauder 7
UPDATE npc_types SET loottable_id = :butcher_atwin_keladryn_lt: WHERE id in (68076); # Atwin_Keladryn 35
UPDATE npc_types SET loottable_id = :butcher_ayen_rundlor_lt: WHERE id in (68114); # Ayen_Rundlor 38
UPDATE npc_types SET loottable_id = :butcher_a_bat_lt: WHERE id in (68008); # a_bat 1
UPDATE npc_types SET loottable_id = :butcher_a_crazed_goblin_lt: WHERE id in (68162, 68164, 68193); # a_crazed_goblin 26
UPDATE npc_types SET loottable_id = :butcher_a_decaying_dwarf_skeleton_lt: WHERE id in (68002); # a_decaying_dwarf_skeleton 1
UPDATE npc_types SET loottable_id = :butcher_a_dismal_rage_initiate_lt: WHERE id in (68172, 68051, 68052); # a_dismal_rage_initiate 5
UPDATE npc_types SET loottable_id = :butcher_a_dwarf_skeleton_lt: WHERE id in (68016, 68034, 68041); # a_dwarf_skeleton 7
UPDATE npc_types SET loottable_id = :butcher_a_dwarven_bandit_lt: WHERE id in (68235); # a_dwarven_bandit 4
UPDATE npc_types SET loottable_id = :butcher_a_giant_bat_lt: WHERE id in (68252); # a_giant_bat 7
UPDATE npc_types SET loottable_id = :butcher_a_giant_scarab_lt: WHERE id in (68148, 68026, 68043); # a_giant_scarab 8
UPDATE npc_types SET loottable_id = :butcher_a_goblin_lt: WHERE id in (68139, 68144, 68145, 68167, 68194, 68013, 68015, 68019, 68020, 68022, 68023); # a_goblin 4
UPDATE npc_types SET loottable_id = :butcher_a_goblin_grunt_lt: WHERE id in (68021, 68063); # a_goblin_grunt 3
UPDATE npc_types SET loottable_id = :butcher_a_goblin_shaman_lt: WHERE id in (68152, 68192, 68195); # a_goblin_shaman 10
UPDATE npc_types SET loottable_id = :butcher_a_goblin_warrior_lt: WHERE id in (68141, 68143, 68196); # a_goblin_warrior 6
UPDATE npc_types SET loottable_id = :butcher_a_goblin_whelp_lt: WHERE id in (68001); # a_goblin_whelp 1
UPDATE npc_types SET loottable_id = :butcher_a_goblin_wizard_lt: WHERE id in (68156, 68224); # a_goblin_wizard 11
UPDATE npc_types SET loottable_id = :butcher_a_greedy_beggar_lt: WHERE id in (68006); # a_greedy_beggar 1
UPDATE npc_types SET loottable_id = :butcher_a_krag_chick_lt: WHERE id in (68011, 68024, 68044); # a_Krag_chick 4
UPDATE npc_types SET loottable_id = :butcher_a_krag_elder_lt: WHERE id in (68155); # a_Krag_elder 9
UPDATE npc_types SET loottable_id = :butcher_a_large_skunk_lt: WHERE id in (68010); # a_large_skunk 2
UPDATE npc_types SET loottable_id = :butcher_a_large_snake_lt: WHERE id in (68000, 68042, 68046); # a_large_snake 3
UPDATE npc_types SET loottable_id = :butcher_a_large_spider_lt: WHERE id in (68138, 68009, 68057); # a_large_spider 3
UPDATE npc_types SET loottable_id = :butcher_a_lesser_spirit_lt: WHERE id in (68251); # a_lesser_spirit 1
UPDATE npc_types SET loottable_id = :butcher_a_lowland_basilisk_lt: WHERE id in (68014); # a_lowland_basilisk 7
UPDATE npc_types SET loottable_id = :butcher_a_rock_spiderling_lt: WHERE id in (68007); # a_rock_spiderling 2
UPDATE npc_types SET loottable_id = :butcher_a_snake_lt: WHERE id in (68005); # a_snake 1
UPDATE npc_types SET loottable_id = :butcher_a_towering_brute_lt: WHERE id in (68157, 68198, 68050, 68064, 68065); # a_towering_brute 12
UPDATE npc_types SET loottable_id = :butcher_a_tunarian_scout_lt: WHERE id in (68122); # a_Tunarian_scout 40
UPDATE npc_types SET loottable_id = :butcher_a_wandering_greenblood_lt: WHERE id in (68147, 68183, 68003, 68018); # a_wandering_greenblood 10
UPDATE npc_types SET loottable_id = :butcher_a_worker_scarab_lt: WHERE id in (68004); # a_worker_scarab 2
UPDATE npc_types SET loottable_id = :butcher_balen_kalgunn_lt: WHERE id in (68072); # Balen_Kalgunn 35
UPDATE npc_types SET loottable_id = :butcher_baradiella_skymoor_lt: WHERE id in (68232); # Baradiella_Skymoor 50
UPDATE npc_types SET loottable_id = :butcher_barma_dunfire_lt: WHERE id in (68166, 68215, 68040); # Barma_Dunfire 10
UPDATE npc_types SET loottable_id = :butcher_biski_teezlen_lt: WHERE id in (68129); # Biski_Teezlen 65
UPDATE npc_types SET loottable_id = :butcher_blyle_bundin_lt: WHERE id in (68226); # Blyle_Bundin 7
UPDATE npc_types SET loottable_id = :butcher_captains_skiff_lt: WHERE id in (68150); # Captains_Skiff 50
UPDATE npc_types SET loottable_id = :butcher_corflunk_lt: WHERE id in (68146); # Corflunk 7
UPDATE npc_types SET loottable_id = :butcher_crytil_dunfire_lt: WHERE id in (68160, 68212, 68027); # Crytil_Dunfire 10
UPDATE npc_types SET loottable_id = :butcher_dalbar_tarbrind_lt: WHERE id in (68084); # Dalbar_Tarbrind 35
UPDATE npc_types SET loottable_id = :butcher_dandalek_swillslammer_lt: WHERE id in (68112); # Dandalek_Swillslammer 40
UPDATE npc_types SET loottable_id = :butcher_dapper_blackhammer_lt: WHERE id in (68089); # Dapper_Blackhammer 45
UPDATE npc_types SET loottable_id = :butcher_darm_dundam_lt: WHERE id in (68104); # Darm_Dundam 35
UPDATE npc_types SET loottable_id = :butcher_deldryn_splendyr_lt: WHERE id in (68073); # Deldryn_Splendyr 25
UPDATE npc_types SET loottable_id = :butcher_delin_ironblend_lt: WHERE id in (68049); # Delin_Ironblend 35
UPDATE npc_types SET loottable_id = :butcher_den_ironblend_lt: WHERE id in (68083); # Den_Ironblend 35
UPDATE npc_types SET loottable_id = :butcher_doran_glosglen_lt: WHERE id in (68070); # Doran_Glosglen 35
UPDATE npc_types SET loottable_id = :butcher_droongar_kann_lt: WHERE id in (68244); # Droongar_Kann 50
UPDATE npc_types SET loottable_id = :butcher_dru_razbind_lt: WHERE id in (68098); # Dru_Razbind 35
UPDATE npc_types SET loottable_id = :butcher_durkis_battlemore_lt: WHERE id in (68113); # Durkis_Battlemore 50
UPDATE npc_types SET loottable_id = :butcher_ellona_lt: WHERE id in (68111); # Ellona 45
UPDATE npc_types SET loottable_id = :butcher_emeraldman_lt: WHERE id in (68237); # Emeraldman 1
UPDATE npc_types SET loottable_id = :butcher_felen_razdal_lt: WHERE id in (68116); # Felen_Razdal 40
UPDATE npc_types SET loottable_id = :butcher_feriella_vorana_lt: WHERE id in (68248); # Feriella_Vorana 50
UPDATE npc_types SET loottable_id = :butcher_fugan_mumfur_lt: WHERE id in (68108); # Fugan_Mumfur 32
UPDATE npc_types SET loottable_id = :butcher_gaellane_ivyweaver_lt: WHERE id in (68125); # Gaellane_Ivyweaver 65
UPDATE npc_types SET loottable_id = :butcher_gamin_griststone_lt: WHERE id in (68097); # Gamin_Griststone 39
UPDATE npc_types SET loottable_id = :butcher_ganbar_dundam_lt: WHERE id in (68105); # Ganbar_Dundam 35
UPDATE npc_types SET loottable_id = :butcher_gand_truelink_lt: WHERE id in (68099); # Gand_Truelink 42
UPDATE npc_types SET loottable_id = :butcher_gann_dunbull_lt: WHERE id in (68071); # Gann_Dunbull 35
UPDATE npc_types SET loottable_id = :butcher_gan_ironsworthy_lt: WHERE id in (68227); # Gan_Ironsworthy 50
UPDATE npc_types SET loottable_id = :butcher_gibi_bilgum_lt: WHERE id in (68090); # Gibi_Bilgum 35
UPDATE npc_types SET loottable_id = :butcher_glisse_bluesea_lt: WHERE id in (68236); # Glisse_Bluesea 99
UPDATE npc_types SET loottable_id = :butcher_glopruk_tigglum_lt: WHERE id in (68127); # Glopruk_Tigglum 65
UPDATE npc_types SET loottable_id = :butcher_glorin_binfurr_lt: WHERE id in (68054); # Glorin_Binfurr 35
UPDATE npc_types SET loottable_id = :butcher_glubbsink_lt: WHERE id in (68137); # Glubbsink 15
UPDATE npc_types SET loottable_id = :butcher_glynda_smeltpot_lt: WHERE id in (68165, 68213, 68035); # Glynda_Smeltpot 9
UPDATE npc_types SET loottable_id = :butcher_glynn_smeltpot_lt: WHERE id in (68214, 68037); # Glynn_Smeltpot 11
UPDATE npc_types SET loottable_id = :butcher_gridbar_galund_lt: WHERE id in (68234); # Gridbar_Galund 60
UPDATE npc_types SET loottable_id = :butcher_guard_armandin_lt: WHERE id in (68117); # Guard_Armandin 50
UPDATE npc_types SET loottable_id = :butcher_guard_belg_lt: WHERE id in (68028); # Guard_Belg 40
UPDATE npc_types SET loottable_id = :butcher_guard_burr_lt: WHERE id in (68120); # Guard_Burr 50
UPDATE npc_types SET loottable_id = :butcher_guard_clendin_lt: WHERE id in (68107); # Guard_Clendin 45
UPDATE npc_types SET loottable_id = :butcher_guard_dunil_lt: WHERE id in (68074); # Guard_Dunil 45
UPDATE npc_types SET loottable_id = :butcher_guard_dunn_lt: WHERE id in (68088); # Guard_Dunn 45
UPDATE npc_types SET loottable_id = :butcher_guard_gabel_lt: WHERE id in (68110); # Guard_Gabel 40
UPDATE npc_types SET loottable_id = :butcher_guard_gonin_lt: WHERE id in (68217, 68081); # Guard_Gonin 24
UPDATE npc_types SET loottable_id = :butcher_guard_grae_lt: WHERE id in (68118); # Guard_Grae 50
UPDATE npc_types SET loottable_id = :butcher_guard_haendar_lt: WHERE id in (68119); # Guard_Haendar 50
UPDATE npc_types SET loottable_id = :butcher_guard_haldin_lt: WHERE id in (68031); # Guard_Haldin 40
UPDATE npc_types SET loottable_id = :butcher_guard_hartt_lt: WHERE id in (68069); # Guard_Hartt 40
UPDATE npc_types SET loottable_id = :butcher_guard_kizzburr_lt: WHERE id in (68025); # Guard_Kizzburr 25
UPDATE npc_types SET loottable_id = :butcher_guard_kyte_lt: WHERE id in (68209, 68080); # Guard_Kyte 26
UPDATE npc_types SET loottable_id = :butcher_guard_mandin_lt: WHERE id in (68264); # Guard_Mandin 45
UPDATE npc_types SET loottable_id = :butcher_guard_norin_lt: WHERE id in (68067); # Guard_Norin 40
UPDATE npc_types SET loottable_id = :butcher_guard_rundul_lt: WHERE id in (68101); # Guard_Rundul 45
UPDATE npc_types SET loottable_id = :butcher_guard_rylin_lt: WHERE id in (68182, 68077); # Guard_Rylin 37
UPDATE npc_types SET loottable_id = :butcher_guard_sornn_lt: WHERE id in (68068); # Guard_Sornn 40
UPDATE npc_types SET loottable_id = :butcher_guard_srinn_lt: WHERE id in (68047); # Guard_Srinn 40
UPDATE npc_types SET loottable_id = :butcher_gundl_lt: WHERE id in (68100, 68177, 68204); # Gundl 9
UPDATE npc_types SET loottable_id = :butcher_happ_findlefinn_lt: WHERE id in (68079); # Happ_Findlefinn 35
UPDATE npc_types SET loottable_id = :butcher_harbormaster_ironbeard_lt: WHERE id in (68233); # Harbormaster_Ironbeard 99
UPDATE npc_types SET loottable_id = :butcher_iglan_thranon_lt: WHERE id in (68095); # Iglan_Thranon 32
UPDATE npc_types SET loottable_id = :butcher_inudul_dumirgun_lt: WHERE id in (68093); # Inudul_Dumirgun 40
UPDATE npc_types SET loottable_id = :butcher_izbal_brightblaze_lt: WHERE id in (68058); # Izbal_Brightblaze 41
UPDATE npc_types SET loottable_id = :butcher_jelqtan_oretnai_lt: WHERE id in (68128); # Jelqtan_Oretnai 65
UPDATE npc_types SET loottable_id = :butcher_jilsuia_lluarea_lt: WHERE id in (68124); # Jilsuia_Lluarea 65
UPDATE npc_types SET loottable_id = :butcher_kaila_rucksack_lt: WHERE id in (68230); # Kaila_Rucksack 41
UPDATE npc_types SET loottable_id = :butcher_kancompan_lt: WHERE id in (68245); # Kancompan 1
UPDATE npc_types SET loottable_id = :butcher_kandin_firepot_lt: WHERE id in (68109); # Kandin_Firepot 54
UPDATE npc_types SET loottable_id = :butcher_kanthuk_ogrebane__lt: WHERE id in (68239); # Kanthuk_Ogrebane_ 23
UPDATE npc_types SET loottable_id = :butcher_keldyn_dunfire_lt: WHERE id in (68191, 68012); # Keldyn_Dunfire 7
UPDATE npc_types SET loottable_id = :butcher_kroggl_lt: WHERE id in (68126); # Kroggl 65
UPDATE npc_types SET loottable_id = :butcher_lann_dabldrin_lt: WHERE id in (68085); # Lann_Dabldrin 35
UPDATE npc_types SET loottable_id = :butcher_lieutenant_gattek_lt: WHERE id in (68247); # Lieutenant_Gattek 50
UPDATE npc_types SET loottable_id = :butcher_magnus_boran_lt: WHERE id in (68102); # Magnus_Boran 35
UPDATE npc_types SET loottable_id = :butcher_magus_tira_lt: WHERE id in (68133); # Magus_Tira 60
UPDATE npc_types SET loottable_id = :butcher_margyl_darklin_lt: WHERE id in (68202, 68033); # Margyl_Darklin 9
UPDATE npc_types SET loottable_id = :butcher_mimzit_furnov_lt: WHERE id in (68121); # Mimzit_Furnov 60
UPDATE npc_types SET loottable_id = :butcher_nalda_griststone_lt: WHERE id in (68096); # Nalda_Griststone 38
UPDATE npc_types SET loottable_id = :butcher_nyzil_bloodforge_lt: WHERE id in (68103); # Nyzil_Bloodforge 45
UPDATE npc_types SET loottable_id = :butcher_orc_centurion_lt: WHERE id in (68190); # orc_centurion 3
UPDATE npc_types SET loottable_id = :butcher_orc_pawn_lt: WHERE id in (68263); # orc_pawn 1
UPDATE npc_types SET loottable_id = :butcher_orc_runner_lt: WHERE id in (68223); # orc_runner 7
UPDATE npc_types SET loottable_id = :butcher_parn_gylwyn_lt: WHERE id in (68106); # Parn_Gylwyn 40
UPDATE npc_types SET loottable_id = :butcher_peg_leg_lt: WHERE id in (68161, 68201, 68032); # Peg_Leg 13
UPDATE npc_types SET loottable_id = :butcher_qued_lt: WHERE id in (68159, 68216, 68062); # Qued 10
UPDATE npc_types SET loottable_id = :butcher_renell_bekea_lt: WHERE id in (68132); # Renell_Bekea 65
UPDATE npc_types SET loottable_id = :butcher_rokaon_sternheart_lt: WHERE id in (68123); # Rokaon_Sternheart 65
UPDATE npc_types SET loottable_id = :butcher_sigmas_boran_lt: WHERE id in (68242); # Sigmas_Boran 35
UPDATE npc_types SET loottable_id = :butcher_signus_boran_lt: WHERE id in (68048); # Signus_Boran 35
UPDATE npc_types SET loottable_id = :butcher_siltria_marwind_lt: WHERE id in (68075); # Siltria_Marwind 25
UPDATE npc_types SET loottable_id = :butcher_sirensbane_lt: WHERE id in (68228); # SirensBane 50
UPDATE npc_types SET loottable_id = :butcher_soulbinder_tania_lt: WHERE id in (68136); # Soulbinder_Tania 65
UPDATE npc_types SET loottable_id = :butcher_stormbreaker_lt: WHERE id in (68188); # Stormbreaker 50
UPDATE npc_types SET loottable_id = :butcher_stump_rundl_lt: WHERE id in (68170, 68211, 68029); # Stump_Rundl 12
UPDATE npc_types SET loottable_id = :butcher_tagnis_ginfarr_lt: WHERE id in (68082); # Tagnis_Ginfarr 35
UPDATE npc_types SET loottable_id = :butcher_thar_kelgand_lt: WHERE id in (68078); # Thar_Kelgand 35
UPDATE npc_types SET loottable_id = :butcher_the_fabled_corflunk_lt: WHERE id in (68249); # The_Fabled_Corflunk 15
UPDATE npc_types SET loottable_id = :butcher_the_fabled_zarchoomi_lt: WHERE id in (68246); # The_Fabled_Zarchoomi 15
UPDATE npc_types SET loottable_id = :butcher_tok_skan_lt: WHERE id in (68231); # Tok_Skan 50
UPDATE npc_types SET loottable_id = :butcher_urazun_thranon_lt: WHERE id in (68094); # Urazun_Thranon 41
UPDATE npc_types SET loottable_id = :butcher_vedico_windwisper_lt: WHERE id in (68115); # Vedico_Windwisper 45
UPDATE npc_types SET loottable_id = :butcher_vual_stoutest_lt: WHERE id in (68131); # Vual_Stoutest 65
UPDATE npc_types SET loottable_id = :butcher_walnan_lt: WHERE id in (68087); # Walnan 47
UPDATE npc_types SET loottable_id = :butcher_xyzelauna_tuvalzir_lt: WHERE id in (68130); # Xyzelauna_Tu`Valzir 65
UPDATE npc_types SET loottable_id = :butcher_zarchoomi_lt: WHERE id in (68185); # Zarchoomi 10
