INSERT INTO loottable(name) VALUES('cauldron_an_undertow_skeleton'); # :cauldron_an_undertow_skeleton_lt:
INSERT INTO loottable(name) VALUES('cauldron_aqua_goblin_mariner'); # :cauldron_aqua_goblin_mariner_lt:
INSERT INTO loottable(name) VALUES('cauldron_aqua_goblin_shaman'); # :cauldron_aqua_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('cauldron_a_cauldron_rat'); # :cauldron_a_cauldron_rat_lt:
INSERT INTO loottable(name) VALUES('cauldron_bilge_farfathom'); # :cauldron_bilge_farfathom_lt:
INSERT INTO loottable(name) VALUES('cauldron_captain_klunga'); # :cauldron_captain_klunga_lt:
INSERT INTO loottable(name) VALUES('cauldron_llara'); # :cauldron_llara_lt:
INSERT INTO loottable(name) VALUES('cauldron_the_fabled_bilge_farfathom'); # :cauldron_the_fabled_bilge_farfathom_lt:
INSERT INTO loottable(name) VALUES('cauldron_an_aqua_goblin_mariner'); # :cauldron_an_aqua_goblin_mariner_lt:
INSERT INTO loottable(name) VALUES('cauldron_an_exiled_legionnaire'); # :cauldron_an_exiled_legionnaire_lt:
INSERT INTO loottable(name) VALUES('cauldron_an_orc_scout'); # :cauldron_an_orc_scout_lt:
INSERT INTO loottable(name) VALUES('cauldron_an_undertow_skeleton'); # :cauldron_an_undertow_skeleton_lt:
INSERT INTO loottable(name) VALUES('cauldron_aqua_goblin_bosun'); # :cauldron_aqua_goblin_bosun_lt:
INSERT INTO loottable(name) VALUES('cauldron_aqua_goblin_mariner'); # :cauldron_aqua_goblin_mariner_lt:
INSERT INTO loottable(name) VALUES('cauldron_aqua_goblin_shaman'); # :cauldron_aqua_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('cauldron_aqua_goblin_tidal_lord'); # :cauldron_aqua_goblin_tidal_lord_lt:
INSERT INTO loottable(name) VALUES('cauldron_a_boat'); # :cauldron_a_boat_lt:
INSERT INTO loottable(name) VALUES('cauldron_a_cauldron_rat'); # :cauldron_a_cauldron_rat_lt:
INSERT INTO loottable(name) VALUES('cauldron_a_sandbar_serpent'); # :cauldron_a_sandbar_serpent_lt:
INSERT INTO loottable(name) VALUES('cauldron_a_scalded_rat'); # :cauldron_a_scalded_rat_lt:
INSERT INTO loottable(name) VALUES('cauldron_a_shoal_serpent'); # :cauldron_a_shoal_serpent_lt:
INSERT INTO loottable(name) VALUES('cauldron_barnacle_bones'); # :cauldron_barnacle_bones_lt:
INSERT INTO loottable(name) VALUES('cauldron_conium_darkblade'); # :cauldron_conium_darkblade_lt:
INSERT INTO loottable(name) VALUES('cauldron_dwigus_lowater'); # :cauldron_dwigus_lowater_lt:
INSERT INTO loottable(name) VALUES('cauldron_elmion_hendrys'); # :cauldron_elmion_hendrys_lt:
INSERT INTO loottable(name) VALUES('cauldron_flotsam'); # :cauldron_flotsam_lt:
INSERT INTO loottable(name) VALUES('cauldron_ghilanbiddle_nylwadil'); # :cauldron_ghilanbiddle_nylwadil_lt:
INSERT INTO loottable(name) VALUES('cauldron_grimpl_rustedcog'); # :cauldron_grimpl_rustedcog_lt:
INSERT INTO loottable(name) VALUES('cauldron_gundalthur_izuran'); # :cauldron_gundalthur_izuran_lt:
INSERT INTO loottable(name) VALUES('cauldron_henai_silentwalker'); # :cauldron_henai_silentwalker_lt:
INSERT INTO loottable(name) VALUES('cauldron_jagged_fang'); # :cauldron_jagged_fang_lt:
INSERT INTO loottable(name) VALUES('cauldron_jetsam'); # :cauldron_jetsam_lt:
INSERT INTO loottable(name) VALUES('cauldron_jinalis_andir'); # :cauldron_jinalis_andir_lt:
INSERT INTO loottable(name) VALUES('cauldron_llaracom'); # :cauldron_llaracom_lt:
INSERT INTO loottable(name) VALUES('cauldron_llara_'); # :cauldron_llara__lt:
INSERT INTO loottable(name) VALUES('cauldron_nyrien_lyrdarniel'); # :cauldron_nyrien_lyrdarniel_lt:
INSERT INTO loottable(name) VALUES('cauldron_praklion_of_the_cauldron'); # :cauldron_praklion_of_the_cauldron_lt:
INSERT INTO loottable(name) VALUES('cauldron_sigan_ilbirkun'); # :cauldron_sigan_ilbirkun_lt:
INSERT INTO loottable(name) VALUES('cauldron_squallslither'); # :cauldron_squallslither_lt:
INSERT INTO loottable(name) VALUES('cauldron_symperbell_moor'); # :cauldron_symperbell_moor_lt:
INSERT INTO loottable(name) VALUES('cauldron_the_fabled_barnacle_bones'); # :cauldron_the_fabled_barnacle_bones_lt:
INSERT INTO loottable(name) VALUES('cauldron_treanik_ireblade'); # :cauldron_treanik_ireblade_lt:
