INSERT INTO loottable(name) VALUES('cazicthule_amygdalan_knight'); # :cazicthule_amygdalan_knight_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_acidic_mass'); # :cazicthule_an_acidic_mass_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_enraged_amygdalan'); # :cazicthule_an_enraged_amygdalan_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_enraged_disciple'); # :cazicthule_an_enraged_disciple_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_enraged_jungle_raptor'); # :cazicthule_an_enraged_jungle_raptor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_enraged_tiger_raptor'); # :cazicthule_an_enraged_tiger_raptor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_ooze_covered_ritualist'); # :cazicthule_an_ooze_covered_ritualist_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_unstable_rift'); # :cazicthule_an_unstable_rift_lt:
INSERT INTO loottable(name) VALUES('cazicthule_avatar_of_dread'); # :cazicthule_avatar_of_dread_lt:
INSERT INTO loottable(name) VALUES('cazicthule_avatar_of_fear'); # :cazicthule_avatar_of_fear_lt:
INSERT INTO loottable(name) VALUES('cazicthule_avatar_of_fright'); # :cazicthule_avatar_of_fright_lt:
INSERT INTO loottable(name) VALUES('cazicthule_avatar_of_terror'); # :cazicthule_avatar_of_terror_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_blood_fin_piranha'); # :cazicthule_a_blood_fin_piranha_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_boiling_ooze'); # :cazicthule_a_boiling_ooze_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_bubbling_ooze'); # :cazicthule_a_bubbling_ooze_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_crystaline_mass'); # :cazicthule_a_crystaline_mass_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_disciple_of_thule'); # :cazicthule_a_disciple_of_thule_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_diseased_mosquito'); # :cazicthule_a_diseased_mosquito_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_frenzied_shiverback'); # :cazicthule_a_frenzied_shiverback_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_gelatinous_mass'); # :cazicthule_a_gelatinous_mass_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_gorgon'); # :cazicthule_a_gorgon_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_gyrating_mass'); # :cazicthule_a_gyrating_mass_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_poisonstrand_hunter'); # :cazicthule_a_poisonstrand_hunter_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_quivering_mass'); # :cazicthule_a_quivering_mass_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_razor_fin_piranha'); # :cazicthule_a_razor_fin_piranha_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_rotting_horror'); # :cazicthule_a_rotting_horror_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_rotting_shiverback'); # :cazicthule_a_rotting_shiverback_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_shiverback'); # :cazicthule_a_shiverback_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_silverflank_shiverback'); # :cazicthule_a_silverflank_shiverback_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_spinechill_spider'); # :cazicthule_a_spinechill_spider_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_swirling_black_mass'); # :cazicthule_a_swirling_black_mass_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_swirling_green_mass'); # :cazicthule_a_swirling_green_mass_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_swirling_ooze'); # :cazicthule_a_swirling_ooze_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_swirling_red_mass'); # :cazicthule_a_swirling_red_mass_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_aggressor'); # :cazicthule_a_tae_ew_aggressor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_bloodfiend'); # :cazicthule_a_tae_ew_bloodfiend_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_convert'); # :cazicthule_a_tae_ew_convert_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_hunter'); # :cazicthule_a_tae_ew_hunter_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_justicar'); # :cazicthule_a_tae_ew_justicar_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_trapper'); # :cazicthule_a_tae_ew_trapper_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_warlord'); # :cazicthule_a_tae_ew_warlord_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_warmaster'); # :cazicthule_a_tae_ew_warmaster_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_adept'); # :cazicthule_a_thul_tae_ew_adept_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_crusader'); # :cazicthule_a_thul_tae_ew_crusader_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_despoiler'); # :cazicthule_a_thul_tae_ew_despoiler_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_high_priest'); # :cazicthule_a_thul_tae_ew_high_priest_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_ritualist'); # :cazicthule_a_thul_tae_ew_ritualist_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_spirtcaller'); # :cazicthule_a_thul_tae_ew_spirtcaller_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_torturer'); # :cazicthule_a_thul_tae_ew_torturer_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_tracker'); # :cazicthule_a_thul_tae_ew_tracker_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_toxic_jungle_hunter'); # :cazicthule_a_toxic_jungle_hunter_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dreadfang'); # :cazicthule_dreadfang_lt:
INSERT INTO loottable(name) VALUES('cazicthule_gimlik_cogboggle'); # :cazicthule_gimlik_cogboggle_lt:
INSERT INTO loottable(name) VALUES('cazicthule_guard_khataruss'); # :cazicthule_guard_khataruss_lt:
INSERT INTO loottable(name) VALUES('cazicthule_guard_scithiss'); # :cazicthule_guard_scithiss_lt:
INSERT INTO loottable(name) VALUES('cazicthule_guard_thrasciss'); # :cazicthule_guard_thrasciss_lt:
INSERT INTO loottable(name) VALUES('cazicthule_ikpug_giblod'); # :cazicthule_ikpug_giblod_lt:
INSERT INTO loottable(name) VALUES('cazicthule_soul_siphon'); # :cazicthule_soul_siphon_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_amygdalan_protector'); # :cazicthule_an_amygdalan_protector_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_enraged_shiverback'); # :cazicthule_an_enraged_shiverback_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_enraged_tae_ew_fanatic'); # :cazicthule_an_enraged_tae_ew_fanatic_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_envenomed_hunter'); # :cazicthule_an_envenomed_hunter_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_ooze'); # :cazicthule_an_ooze_lt:
INSERT INTO loottable(name) VALUES('cazicthule_an_unseen_force'); # :cazicthule_an_unseen_force_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_barbed_scale_piranha'); # :cazicthule_a_barbed_scale_piranha_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_blood_claw_raptor'); # :cazicthule_a_blood_claw_raptor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_diamond_scale_piranha'); # :cazicthule_a_diamond_scale_piranha_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_fierce_jungle_raptor'); # :cazicthule_a_fierce_jungle_raptor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_fierce_tiger_raptor'); # :cazicthule_a_fierce_tiger_raptor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_frenzied_jungle_raptor'); # :cazicthule_a_frenzied_jungle_raptor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_frenzied_tiger_raptor'); # :cazicthule_a_frenzied_tiger_raptor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_graystriped_mosquito'); # :cazicthule_a_graystriped_mosquito_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_greenblood_piranha'); # :cazicthule_a_greenblood_piranha_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_horror_construct'); # :cazicthule_a_horror_construct_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_jungle_hunter'); # :cazicthule_a_jungle_hunter_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_jungle_raptor'); # :cazicthule_a_jungle_raptor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_jungle_stalker'); # :cazicthule_a_jungle_stalker_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_large_greenblood_piranha'); # :cazicthule_a_large_greenblood_piranha_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_large_hunter'); # :cazicthule_a_large_hunter_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_lifestealer_mosquito'); # :cazicthule_a_lifestealer_mosquito_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_living_void'); # :cazicthule_a_living_void_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_noxious_jungle_spider'); # :cazicthule_a_noxious_jungle_spider_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_pool_of_black_ooze'); # :cazicthule_a_pool_of_black_ooze_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_pool_of_slime'); # :cazicthule_a_pool_of_slime_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_razor_tooth_piranha'); # :cazicthule_a_razor_tooth_piranha_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_rotting_gorilla'); # :cazicthule_a_rotting_gorilla_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_shiverback'); # :cazicthule_a_shiverback_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_sickly_mosquito'); # :cazicthule_a_sickly_mosquito_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_swirling_ooze'); # :cazicthule_a_swirling_ooze_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_bloodcaller'); # :cazicthule_a_tae_ew_bloodcaller_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_defender'); # :cazicthule_a_tae_ew_defender_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_disciple'); # :cazicthule_a_tae_ew_disciple_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_fanatic'); # :cazicthule_a_tae_ew_fanatic_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_judicator'); # :cazicthule_a_tae_ew_judicator_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_justicar'); # :cazicthule_a_tae_ew_justicar_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_lifedrinker'); # :cazicthule_a_tae_ew_lifedrinker_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_lifestealer'); # :cazicthule_a_tae_ew_lifestealer_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_prophet'); # :cazicthule_a_tae_ew_prophet_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_proselyte'); # :cazicthule_a_tae_ew_proselyte_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_protector'); # :cazicthule_a_tae_ew_protector_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_spear_fisher'); # :cazicthule_a_tae_ew_spear_fisher_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_spiritcaller'); # :cazicthule_a_tae_ew_spiritcaller_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_warder'); # :cazicthule_a_tae_ew_warder_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_warrior'); # :cazicthule_a_tae_ew_warrior_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tae_ew_zealot'); # :cazicthule_a_tae_ew_zealot_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tentacle_terror'); # :cazicthule_a_tentacle_terror_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thulian_high_ritualist'); # :cazicthule_a_thulian_high_ritualist_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_bloodcaller'); # :cazicthule_a_thul_tae_ew_bloodcaller_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_defender'); # :cazicthule_a_thul_tae_ew_defender_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_fanatic'); # :cazicthule_a_thul_tae_ew_fanatic_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_hunter'); # :cazicthule_a_thul_tae_ew_hunter_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_judicator'); # :cazicthule_a_thul_tae_ew_judicator_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_justicar'); # :cazicthule_a_thul_tae_ew_justicar_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_lifestealer'); # :cazicthule_a_thul_tae_ew_lifestealer_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_protector'); # :cazicthule_a_thul_tae_ew_protector_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_warder'); # :cazicthule_a_thul_tae_ew_warder_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_thul_tae_ew_zealot'); # :cazicthule_a_thul_tae_ew_zealot_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_tiger_raptor'); # :cazicthule_a_tiger_raptor_lt:
INSERT INTO loottable(name) VALUES('cazicthule_a_virulent_mosquito'); # :cazicthule_a_virulent_mosquito_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dismay'); # :cazicthule_dismay_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgeight'); # :cazicthule_dlgeight_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgeighteen'); # :cazicthule_dlgeighteen_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgeleven'); # :cazicthule_dlgeleven_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgfifteen'); # :cazicthule_dlgfifteen_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgfive'); # :cazicthule_dlgfive_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgfour'); # :cazicthule_dlgfour_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgfourteen'); # :cazicthule_dlgfourteen_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgnine'); # :cazicthule_dlgnine_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgnineteen'); # :cazicthule_dlgnineteen_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgone'); # :cazicthule_dlgone_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgseven'); # :cazicthule_dlgseven_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgseventeen'); # :cazicthule_dlgseventeen_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgsix'); # :cazicthule_dlgsix_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgsixteen'); # :cazicthule_dlgsixteen_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgten'); # :cazicthule_dlgten_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgthirteen'); # :cazicthule_dlgthirteen_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgthree'); # :cazicthule_dlgthree_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgtwelve'); # :cazicthule_dlgtwelve_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgtwo'); # :cazicthule_dlgtwo_lt:
INSERT INTO loottable(name) VALUES('cazicthule_dlgzero'); # :cazicthule_dlgzero_lt:
INSERT INTO loottable(name) VALUES('cazicthule_eartahiaone'); # :cazicthule_eartahiaone_lt:
INSERT INTO loottable(name) VALUES('cazicthule_eartahiathree'); # :cazicthule_eartahiathree_lt:
INSERT INTO loottable(name) VALUES('cazicthule_eartahiatwo'); # :cazicthule_eartahiatwo_lt:
INSERT INTO loottable(name) VALUES('cazicthule_frightchaser'); # :cazicthule_frightchaser_lt:
INSERT INTO loottable(name) VALUES('cazicthule_gimlik_cogboggle'); # :cazicthule_gimlik_cogboggle_lt:
INSERT INTO loottable(name) VALUES('cazicthule_gimlik_cogboggle_'); # :cazicthule_gimlik_cogboggle__lt:
INSERT INTO loottable(name) VALUES('cazicthule_interpreterone'); # :cazicthule_interpreterone_lt:
INSERT INTO loottable(name) VALUES('cazicthule_interpreterrare'); # :cazicthule_interpreterrare_lt:
INSERT INTO loottable(name) VALUES('cazicthule_interpreterthree'); # :cazicthule_interpreterthree_lt:
INSERT INTO loottable(name) VALUES('cazicthule_interpretertwo'); # :cazicthule_interpretertwo_lt:
INSERT INTO loottable(name) VALUES('cazicthule_interpreterzero'); # :cazicthule_interpreterzero_lt:
INSERT INTO loottable(name) VALUES('cazicthule_mazeman'); # :cazicthule_mazeman_lt:
INSERT INTO loottable(name) VALUES('cazicthule_radiant'); # :cazicthule_radiant_lt:
INSERT INTO loottable(name) VALUES('cazicthule_raidstopper'); # :cazicthule_raidstopper_lt:
INSERT INTO loottable(name) VALUES('cazicthule_silverfang'); # :cazicthule_silverfang_lt:
INSERT INTO loottable(name) VALUES('cazicthule_tahia_felwah'); # :cazicthule_tahia_felwah_lt:
INSERT INTO loottable(name) VALUES('cazicthule_terrorclaw'); # :cazicthule_terrorclaw_lt:
INSERT INTO loottable(name) VALUES('cazicthule_toxiferious'); # :cazicthule_toxiferious_lt:
INSERT INTO loottable(name) VALUES('cazicthule_trap_def'); # :cazicthule_trap_def_lt:
INSERT INTO loottable(name) VALUES('cazicthule_trap_disc'); # :cazicthule_trap_disc_lt:
INSERT INTO loottable(name) VALUES('cazicthule_trap_pros'); # :cazicthule_trap_pros_lt:
INSERT INTO loottable(name) VALUES('cazicthule_trap_war'); # :cazicthule_trap_war_lt:
INSERT INTO loottable(name) VALUES('cazicthule__________'); # :cazicthule___________lt:
