INSERT INTO loottable(name) VALUES('commons_an_asp'); # :commons_an_asp_lt:
INSERT INTO loottable(name) VALUES('commons_an_orc_centurion'); # :commons_an_orc_centurion_lt:
INSERT INTO loottable(name) VALUES('commons_an_orc_legionnaire'); # :commons_an_orc_legionnaire_lt:
INSERT INTO loottable(name) VALUES('commons_avatar_of_elements'); # :commons_avatar_of_elements_lt:
INSERT INTO loottable(name) VALUES('commons_a_black_bear'); # :commons_a_black_bear_lt:
INSERT INTO loottable(name) VALUES('commons_a_broken_claw_bandit'); # :commons_a_broken_claw_bandit_lt:
INSERT INTO loottable(name) VALUES('commons_a_darkweed_snake'); # :commons_a_darkweed_snake_lt:
INSERT INTO loottable(name) VALUES('commons_a_dervish_cutthroat'); # :commons_a_dervish_cutthroat_lt:
INSERT INTO loottable(name) VALUES('commons_a_dervish_thug'); # :commons_a_dervish_thug_lt:
INSERT INTO loottable(name) VALUES('commons_a_ghoul'); # :commons_a_ghoul_lt:
INSERT INTO loottable(name) VALUES('commons_a_giant_spider'); # :commons_a_giant_spider_lt:
INSERT INTO loottable(name) VALUES('commons_a_hill_giant'); # :commons_a_hill_giant_lt:
INSERT INTO loottable(name) VALUES('commons_a_large_piranha'); # :commons_a_large_piranha_lt:
INSERT INTO loottable(name) VALUES('commons_a_large_rattlesnake'); # :commons_a_large_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('commons_a_legendary_hill_giant'); # :commons_a_legendary_hill_giant_lt:
INSERT INTO loottable(name) VALUES('commons_a_nightfall_giant'); # :commons_a_nightfall_giant_lt:
INSERT INTO loottable(name) VALUES('commons_a_plains_cat'); # :commons_a_plains_cat_lt:
INSERT INTO loottable(name) VALUES('commons_a_puma'); # :commons_a_puma_lt:
INSERT INTO loottable(name) VALUES('commons_a_rattlesnake'); # :commons_a_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('commons_a_risen_hero'); # :commons_a_risen_hero_lt:
INSERT INTO loottable(name) VALUES('commons_a_shadowed_man'); # :commons_a_shadowed_man_lt:
INSERT INTO loottable(name) VALUES('commons_a_skeleton'); # :commons_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('commons_a_tortured_revenant'); # :commons_a_tortured_revenant_lt:
INSERT INTO loottable(name) VALUES('commons_a_werewolf'); # :commons_a_werewolf_lt:
INSERT INTO loottable(name) VALUES('commons_a_willowisp'); # :commons_a_willowisp_lt:
INSERT INTO loottable(name) VALUES('commons_a_young_kodiak'); # :commons_a_young_kodiak_lt:
INSERT INTO loottable(name) VALUES('commons_bealya_tanilsuia'); # :commons_bealya_tanilsuia_lt:
INSERT INTO loottable(name) VALUES('commons_brizzenoth_scyth'); # :commons_brizzenoth_scyth_lt:
INSERT INTO loottable(name) VALUES('commons_ceel_moonwhisper'); # :commons_ceel_moonwhisper_lt:
INSERT INTO loottable(name) VALUES('commons_cei_sunjumper'); # :commons_cei_sunjumper_lt:
INSERT INTO loottable(name) VALUES('commons_dragoon_zytl'); # :commons_dragoon_zytl_lt:
INSERT INTO loottable(name) VALUES('commons_duggin_scumber'); # :commons_duggin_scumber_lt:
INSERT INTO loottable(name) VALUES('commons_frost'); # :commons_frost_lt:
INSERT INTO loottable(name) VALUES('commons_greater_werewolf'); # :commons_greater_werewolf_lt:
INSERT INTO loottable(name) VALUES('commons_ground'); # :commons_ground_lt:
INSERT INTO loottable(name) VALUES('commons_guard_colin'); # :commons_guard_colin_lt:
INSERT INTO loottable(name) VALUES('commons_guard_valon'); # :commons_guard_valon_lt:
INSERT INTO loottable(name) VALUES('commons_innkeep_olissa'); # :commons_innkeep_olissa_lt:
INSERT INTO loottable(name) VALUES('commons_innkeep_redthorn'); # :commons_innkeep_redthorn_lt:
INSERT INTO loottable(name) VALUES('commons_innkeep_roster'); # :commons_innkeep_roster_lt:
INSERT INTO loottable(name) VALUES('commons_innkeep_seke'); # :commons_innkeep_seke_lt:
INSERT INTO loottable(name) VALUES('commons_jahsohn_aksot'); # :commons_jahsohn_aksot_lt:
INSERT INTO loottable(name) VALUES('commons_kizdean_gix'); # :commons_kizdean_gix_lt:
INSERT INTO loottable(name) VALUES('commons_lesser_werewolf'); # :commons_lesser_werewolf_lt:
INSERT INTO loottable(name) VALUES('commons_magma'); # :commons_magma_lt:
INSERT INTO loottable(name) VALUES('commons_maula_fishcatcher'); # :commons_maula_fishcatcher_lt:
INSERT INTO loottable(name) VALUES('commons_modren_fishcatcher'); # :commons_modren_fishcatcher_lt:
INSERT INTO loottable(name) VALUES('commons_mojax_hikspin'); # :commons_mojax_hikspin_lt:
INSERT INTO loottable(name) VALUES('commons_nalla'); # :commons_nalla_lt:
INSERT INTO loottable(name) VALUES('commons_nightfall_giant'); # :commons_nightfall_giant_lt:
INSERT INTO loottable(name) VALUES('commons_noresa_sparkle'); # :commons_noresa_sparkle_lt:
INSERT INTO loottable(name) VALUES('commons_one_of_zanivars_bandits'); # :commons_one_of_zanivars_bandits_lt:
INSERT INTO loottable(name) VALUES('commons_opal_woodchopper'); # :commons_opal_woodchopper_lt:
INSERT INTO loottable(name) VALUES('commons_orc_apprentice'); # :commons_orc_apprentice_lt:
INSERT INTO loottable(name) VALUES('commons_orc_centurion'); # :commons_orc_centurion_lt:
INSERT INTO loottable(name) VALUES('commons_orc_legionnaire'); # :commons_orc_legionnaire_lt:
INSERT INTO loottable(name) VALUES('commons_orc_oracle'); # :commons_orc_oracle_lt:
INSERT INTO loottable(name) VALUES('commons_orc_pawn'); # :commons_orc_pawn_lt:
INSERT INTO loottable(name) VALUES('commons_orc_weaponsmith'); # :commons_orc_weaponsmith_lt:
INSERT INTO loottable(name) VALUES('commons_parus_the_strong'); # :commons_parus_the_strong_lt:
INSERT INTO loottable(name) VALUES('commons_peron_threadspinner'); # :commons_peron_threadspinner_lt:
INSERT INTO loottable(name) VALUES('commons_ranon_strongarm'); # :commons_ranon_strongarm_lt:
INSERT INTO loottable(name) VALUES('commons_ranvigoz_tonsmith'); # :commons_ranvigoz_tonsmith_lt:
INSERT INTO loottable(name) VALUES('commons_ruby_boxcrafter'); # :commons_ruby_boxcrafter_lt:
INSERT INTO loottable(name) VALUES('commons_sasha_the_seer'); # :commons_sasha_the_seer_lt:
INSERT INTO loottable(name) VALUES('commons_shadow_treebright'); # :commons_shadow_treebright_lt:
INSERT INTO loottable(name) VALUES('commons_sil_silverstar'); # :commons_sil_silverstar_lt:
INSERT INTO loottable(name) VALUES('commons_simon_aldicott'); # :commons_simon_aldicott_lt:
INSERT INTO loottable(name) VALUES('commons_skipynn_stoneheart'); # :commons_skipynn_stoneheart_lt:
INSERT INTO loottable(name) VALUES('commons_slea_pinewhisper'); # :commons_slea_pinewhisper_lt:
INSERT INTO loottable(name) VALUES('commons_sorsha_hobbitfriend'); # :commons_sorsha_hobbitfriend_lt:
INSERT INTO loottable(name) VALUES('commons_spider'); # :commons_spider_lt:
INSERT INTO loottable(name) VALUES('commons_static'); # :commons_static_lt:
INSERT INTO loottable(name) VALUES('commons_timtok_tonsmith'); # :commons_timtok_tonsmith_lt:
INSERT INTO loottable(name) VALUES('commons_wallin_slyfoot'); # :commons_wallin_slyfoot_lt:
INSERT INTO loottable(name) VALUES('commons__'); # :commons___lt:
INSERT INTO loottable(name) VALUES('commons__watcher'); # :commons__watcher_lt:
