
(:erudsxing_a_frantic_kerran_lt:, :bronze_weapon_exotic_ld:, 1),
(:erudsxing_a_kerra_snake_lt:, :snake_egg_ld:, 1),
(:erudsxing_a_kerra_snake_lt:, :snake_meat_ld:, 1),
(:erudsxing_a_kerra_snake_lt:, :snake_scales_ld:, 49),
(:erudsxing_a_killer_shark_lt:, :fresh_fish_ld:, 1),
(:erudsxing_a_killer_shark_lt:, :shark_meat_ld:, 1),
(:erudsxing_a_lizardman_warrior_lt:, :cloth_small_ld:, 1),
(:erudsxing_a_lizardman_warrior_lt:, :rusty_ld:, 5),
(:erudsxing_a_plague_shark_lt:, :shark_meat_ld:, 1),
(:erudsxing_a_seahorse_lt:, :fresh_fish_ld:, 1),
(:erudsxing_a_shark_lt:, :fresh_fish_ld:, 1),
(:erudsxing_a_shark_lt:, :shark_meat_ld:, 1),
(:erudsxing_a_zombie_guardian_lt:, :cloth_small_ld:, 1),
(:erudsxing_a_zombie_guardian_lt:, :rusty_ld:, 5),
(:erudsxing_a_zombie_sailor_lt:, :cloth_small_ld:, 1),
(:erudsxing_a_zombie_sailor_lt:, :rusty_ld:, 5),
(:erudsxing_captain_vekeros_lt:, :rawhide_medium_ld:, 1),
(:erudsxing_hojo_lt:, :fresh_fish_ld:, 1),
(:erudsxing_jarra_lt:, :fresh_fish_ld:, 1),
(:erudsxing_kala_lt:, :fresh_fish_ld:, 1),
(:erudsxing_milla_lt:, :fresh_fish_ld:, 1),
(:erudsxing_monala_lt:, :fresh_fish_ld:, 1),
(:erudsxing_nifta_lt:, :fresh_fish_ld:, 1),
(:erudsxing_nomala_lt:, :fresh_fish_ld:, 1),(:erudsxing_a_willowisp_lt:, :lightstone_ld:, 1),
(:erudsxing_a_willowisp_lt:, :lightstone_ld:, 1),
