INSERT INTO loottable(name) VALUES('erudnext_jordin_sretin'); # :erudnext_jordin_sretin_lt:
INSERT INTO loottable(name) VALUES('erudnext_senina_jolik'); # :erudnext_senina_jolik_lt:
INSERT INTO loottable(name) VALUES('erudnext_translocator_eniela'); # :erudnext_translocator_eniela_lt:
INSERT INTO loottable(name) VALUES('erudnext_alimaja_shanthun'); # :erudnext_alimaja_shanthun_lt:
INSERT INTO loottable(name) VALUES('erudnext_altrusan_belstince'); # :erudnext_altrusan_belstince_lt:
INSERT INTO loottable(name) VALUES('erudnext_alysa_eltern'); # :erudnext_alysa_eltern_lt:
INSERT INTO loottable(name) VALUES('erudnext_ayth_niphiria'); # :erudnext_ayth_niphiria_lt:
INSERT INTO loottable(name) VALUES('erudnext_a_fish'); # :erudnext_a_fish_lt:
INSERT INTO loottable(name) VALUES('erudnext_a_frostfell_goblin'); # :erudnext_a_frostfell_goblin_lt:
INSERT INTO loottable(name) VALUES('erudnext_a_giant_piranha'); # :erudnext_a_giant_piranha_lt:
INSERT INTO loottable(name) VALUES('erudnext_a_sand_shark'); # :erudnext_a_sand_shark_lt:
INSERT INTO loottable(name) VALUES('erudnext_a_shark'); # :erudnext_a_shark_lt:
INSERT INTO loottable(name) VALUES('erudnext_a_young_shark'); # :erudnext_a_young_shark_lt:
INSERT INTO loottable(name) VALUES('erudnext_bazma_brinstar'); # :erudnext_bazma_brinstar_lt:
INSERT INTO loottable(name) VALUES('erudnext_beth_breadmaker'); # :erudnext_beth_breadmaker_lt:
INSERT INTO loottable(name) VALUES('erudnext_borge_finleather'); # :erudnext_borge_finleather_lt:
INSERT INTO loottable(name) VALUES('erudnext_breya_nostulia'); # :erudnext_breya_nostulia_lt:
INSERT INTO loottable(name) VALUES('erudnext_brianna_falsruinay'); # :erudnext_brianna_falsruinay_lt:
INSERT INTO loottable(name) VALUES('erudnext_camin'); # :erudnext_camin_lt:
INSERT INTO loottable(name) VALUES('erudnext_chembla_ellent'); # :erudnext_chembla_ellent_lt:
INSERT INTO loottable(name) VALUES('erudnext_cipse_tospyr'); # :erudnext_cipse_tospyr_lt:
INSERT INTO loottable(name) VALUES('erudnext_collier'); # :erudnext_collier_lt:
INSERT INTO loottable(name) VALUES('erudnext_demicla_tanner'); # :erudnext_demicla_tanner_lt:
INSERT INTO loottable(name) VALUES('erudnext_depnar_bulrious'); # :erudnext_depnar_bulrious_lt:
INSERT INTO loottable(name) VALUES('erudnext_dleria_mausrel'); # :erudnext_dleria_mausrel_lt:
INSERT INTO loottable(name) VALUES('erudnext_dunore_steelfinger'); # :erudnext_dunore_steelfinger_lt:
INSERT INTO loottable(name) VALUES('erudnext_fhania_aserdon'); # :erudnext_fhania_aserdon_lt:
INSERT INTO loottable(name) VALUES('erudnext_fireworks_engineer_fabdabus'); # :erudnext_fireworks_engineer_fabdabus_lt:
INSERT INTO loottable(name) VALUES('erudnext_galbasi_weaver'); # :erudnext_galbasi_weaver_lt:
INSERT INTO loottable(name) VALUES('erudnext_gans_paust'); # :erudnext_gans_paust_lt:
INSERT INTO loottable(name) VALUES('erudnext_gayle_weaven'); # :erudnext_gayle_weaven_lt:
INSERT INTO loottable(name) VALUES('erudnext_genna_lostin'); # :erudnext_genna_lostin_lt:
INSERT INTO loottable(name) VALUES('erudnext_geoard_bluehawk'); # :erudnext_geoard_bluehawk_lt:
INSERT INTO loottable(name) VALUES('erudnext_ghemna_nyjuss'); # :erudnext_ghemna_nyjuss_lt:
INSERT INTO loottable(name) VALUES('erudnext_grendin_maze'); # :erudnext_grendin_maze_lt:
INSERT INTO loottable(name) VALUES('erudnext_hargar_the_velium_chef'); # :erudnext_hargar_the_velium_chef_lt:
INSERT INTO loottable(name) VALUES('erudnext_helia_bluehawk'); # :erudnext_helia_bluehawk_lt:
INSERT INTO loottable(name) VALUES('erudnext_ienala_eceiaiu'); # :erudnext_ienala_eceiaiu_lt:
INSERT INTO loottable(name) VALUES('erudnext_ignacia_rellasp'); # :erudnext_ignacia_rellasp_lt:
INSERT INTO loottable(name) VALUES('erudnext_illithi_nollith'); # :erudnext_illithi_nollith_lt:
INSERT INTO loottable(name) VALUES('erudnext_issibla_belstince'); # :erudnext_issibla_belstince_lt:
INSERT INTO loottable(name) VALUES('erudnext_jagen_kindlor'); # :erudnext_jagen_kindlor_lt:
INSERT INTO loottable(name) VALUES('erudnext_jras_solsier'); # :erudnext_jras_solsier_lt:
INSERT INTO loottable(name) VALUES('erudnext_junice_weslent'); # :erudnext_junice_weslent_lt:
INSERT INTO loottable(name) VALUES('erudnext_kathar_varselli'); # :erudnext_kathar_varselli_lt:
INSERT INTO loottable(name) VALUES('erudnext_kisrin_breezeshadow'); # :erudnext_kisrin_breezeshadow_lt:
INSERT INTO loottable(name) VALUES('erudnext_kordian_keshalian'); # :erudnext_kordian_keshalian_lt:
INSERT INTO loottable(name) VALUES('erudnext_laoni_reista'); # :erudnext_laoni_reista_lt:
INSERT INTO loottable(name) VALUES('erudnext_lenya_wisk'); # :erudnext_lenya_wisk_lt:
INSERT INTO loottable(name) VALUES('erudnext_leraena_shelyrak'); # :erudnext_leraena_shelyrak_lt:
INSERT INTO loottable(name) VALUES('erudnext_lissa_respelti'); # :erudnext_lissa_respelti_lt:
INSERT INTO loottable(name) VALUES('erudnext_lumi_stergnon'); # :erudnext_lumi_stergnon_lt:
INSERT INTO loottable(name) VALUES('erudnext_luren_renthalis'); # :erudnext_luren_renthalis_lt:
INSERT INTO loottable(name) VALUES('erudnext_megan_tiglin'); # :erudnext_megan_tiglin_lt:
INSERT INTO loottable(name) VALUES('erudnext_mertitt_phentilly'); # :erudnext_mertitt_phentilly_lt:
INSERT INTO loottable(name) VALUES('erudnext_mikeana_tolstaub'); # :erudnext_mikeana_tolstaub_lt:
INSERT INTO loottable(name) VALUES('erudnext_monita_weaver'); # :erudnext_monita_weaver_lt:
INSERT INTO loottable(name) VALUES('erudnext_nerth_sailwind'); # :erudnext_nerth_sailwind_lt:
INSERT INTO loottable(name) VALUES('erudnext_nolusia_finharn'); # :erudnext_nolusia_finharn_lt:
INSERT INTO loottable(name) VALUES('erudnext_orwin_flintmaker'); # :erudnext_orwin_flintmaker_lt:
INSERT INTO loottable(name) VALUES('erudnext_palus_weaponsmith'); # :erudnext_palus_weaponsmith_lt:
INSERT INTO loottable(name) VALUES('erudnext_phloatin_highbrow'); # :erudnext_phloatin_highbrow_lt:
INSERT INTO loottable(name) VALUES('erudnext_priest_of_discord'); # :erudnext_priest_of_discord_lt:
INSERT INTO loottable(name) VALUES('erudnext_qualtis_weslent'); # :erudnext_qualtis_weslent_lt:
INSERT INTO loottable(name) VALUES('erudnext_raine_beteria'); # :erudnext_raine_beteria_lt:
INSERT INTO loottable(name) VALUES('erudnext_rarnan_lapice'); # :erudnext_rarnan_lapice_lt:
INSERT INTO loottable(name) VALUES('erudnext_reihan_wilhemson'); # :erudnext_reihan_wilhemson_lt:
INSERT INTO loottable(name) VALUES('erudnext_reklon_gnallen'); # :erudnext_reklon_gnallen_lt:
INSERT INTO loottable(name) VALUES('erudnext_reko_saltamer'); # :erudnext_reko_saltamer_lt:
INSERT INTO loottable(name) VALUES('erudnext_rem_knarjon'); # :erudnext_rem_knarjon_lt:
INSERT INTO loottable(name) VALUES('erudnext_sabrina'); # :erudnext_sabrina_lt:
INSERT INTO loottable(name) VALUES('erudnext_santug_claugg'); # :erudnext_santug_claugg_lt:
INSERT INTO loottable(name) VALUES('erudnext_sea_king'); # :erudnext_sea_king_lt:
INSERT INTO loottable(name) VALUES('erudnext_selint_chency'); # :erudnext_selint_chency_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_adrial'); # :erudnext_sentinel_adrial_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_aegeo'); # :erudnext_sentinel_aegeo_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_belario'); # :erudnext_sentinel_belario_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_cymbelin'); # :erudnext_sentinel_cymbelin_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_demitri'); # :erudnext_sentinel_demitri_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_gressio'); # :erudnext_sentinel_gressio_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_malvol'); # :erudnext_sentinel_malvol_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_mercutil'); # :erudnext_sentinel_mercutil_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_phylos'); # :erudnext_sentinel_phylos_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_polix'); # :erudnext_sentinel_polix_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_silvis'); # :erudnext_sentinel_silvis_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_tybal'); # :erudnext_sentinel_tybal_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_ursulo'); # :erudnext_sentinel_ursulo_lt:
INSERT INTO loottable(name) VALUES('erudnext_sentinel_venci'); # :erudnext_sentinel_venci_lt:
INSERT INTO loottable(name) VALUES('erudnext_shinan_orefinder'); # :erudnext_shinan_orefinder_lt:
INSERT INTO loottable(name) VALUES('erudnext_silos_dumont'); # :erudnext_silos_dumont_lt:
INSERT INTO loottable(name) VALUES('erudnext_sinnkin_highbrow'); # :erudnext_sinnkin_highbrow_lt:
INSERT INTO loottable(name) VALUES('erudnext_sornita_eltern'); # :erudnext_sornita_eltern_lt:
INSERT INTO loottable(name) VALUES('erudnext_soulbinder_altira_mamar'); # :erudnext_soulbinder_altira_mamar_lt:
INSERT INTO loottable(name) VALUES('erudnext_stella_breezemoon'); # :erudnext_stella_breezemoon_lt:
INSERT INTO loottable(name) VALUES('erudnext_stofo_olan'); # :erudnext_stofo_olan_lt:
INSERT INTO loottable(name) VALUES('erudnext_stolace_printell'); # :erudnext_stolace_printell_lt:
INSERT INTO loottable(name) VALUES('erudnext_syra_printell'); # :erudnext_syra_printell_lt:
INSERT INTO loottable(name) VALUES('erudnext_taler_bilge'); # :erudnext_taler_bilge_lt:
INSERT INTO loottable(name) VALUES('erudnext_teria_finleather'); # :erudnext_teria_finleather_lt:
INSERT INTO loottable(name) VALUES('erudnext_tiam_khonsir'); # :erudnext_tiam_khonsir_lt:
INSERT INTO loottable(name) VALUES('erudnext_ticar_lorestring'); # :erudnext_ticar_lorestring_lt:
INSERT INTO loottable(name) VALUES('erudnext_tollari_mistell'); # :erudnext_tollari_mistell_lt:
INSERT INTO loottable(name) VALUES('erudnext_tol_nicelot'); # :erudnext_tol_nicelot_lt:
INSERT INTO loottable(name) VALUES('erudnext_tomekeeper_danl'); # :erudnext_tomekeeper_danl_lt:
INSERT INTO loottable(name) VALUES('erudnext_valani_gadriek'); # :erudnext_valani_gadriek_lt:
INSERT INTO loottable(name) VALUES('erudnext_vynon_estaliun'); # :erudnext_vynon_estaliun_lt:
INSERT INTO loottable(name) VALUES('erudnext_weligon_steelherder'); # :erudnext_weligon_steelherder_lt:
INSERT INTO loottable(name) VALUES('erudnext_weltria_ostriss'); # :erudnext_weltria_ostriss_lt:
INSERT INTO loottable(name) VALUES('erudnext_zip_fendil'); # :erudnext_zip_fendil_lt:
INSERT INTO loottable(name) VALUES('erudnext_zure_bavuior'); # :erudnext_zure_bavuior_lt:
