UPDATE npc_types SET loottable_id = :erudsxing_translocator_jempar_lt: WHERE id in (98045); # #Translocator_Jempar 1
UPDATE npc_types SET loottable_id = :erudsxing_abe_the_abandoned_lt: WHERE id in (98050); # Abe_the_Abandoned 20
UPDATE npc_types SET loottable_id = :erudsxing_a_fish_lt: WHERE id in (98014); # a_fish 1
UPDATE npc_types SET loottable_id = :erudsxing_a_frantic_kerran_lt: WHERE id in (98022); # a_frantic_kerran 19
UPDATE npc_types SET loottable_id = :erudsxing_a_greater_spirit_lt: WHERE id in (98052); # a_greater_spirit 1
UPDATE npc_types SET loottable_id = :erudsxing_a_kerra_snake_lt: WHERE id in (98011, 98017); # a_kerra_snake 8
UPDATE npc_types SET loottable_id = :erudsxing_a_kerra_spider_lt: WHERE id in (98010, 98018); # a_kerra_spider 12
UPDATE npc_types SET loottable_id = :erudsxing_a_killer_shark_lt: WHERE id in (98001, 98029, 98030); # a_killer_shark 40
UPDATE npc_types SET loottable_id = :erudsxing_a_plague_shark_lt: WHERE id in (98028); # a_plague_shark 33
UPDATE npc_types SET loottable_id = :erudsxing_a_seahorse_lt: WHERE id in (98031, 98032); # a_seahorse 7
UPDATE npc_types SET loottable_id = :erudsxing_a_shark_lt: WHERE id in (98005, 98006, 98007, 98015, 98021); # a_shark 17
UPDATE npc_types SET loottable_id = :erudsxing_a_vampire_bat_lt: WHERE id in (98019, 98020, 98033); # a_vampire_bat 9
UPDATE npc_types SET loottable_id = :erudsxing_a_willowisp_lt: WHERE id in (98002, 98003, 98042); # a_willowisp 10
UPDATE npc_types SET loottable_id = :erudsxing_a_zombie_guardian_lt: WHERE id in (98043); # a_zombie_guardian 26
UPDATE npc_types SET loottable_id = :erudsxing_a_zombie_sailor_lt: WHERE id in (98000, 98012, 98013); # a_zombie_sailor 10
UPDATE npc_types SET loottable_id = :erudsxing_captain_vekeros_lt: WHERE id in (98027); # Captain_Vekeros 11
UPDATE npc_types SET loottable_id = :erudsxing_dillon_the_drowned_lt: WHERE id in (98051); # Dillon_the_Drowned 20
UPDATE npc_types SET loottable_id = :erudsxing_froham_the_forgotten_lt: WHERE id in (98047); # Froham_the_Forgotten 20
UPDATE npc_types SET loottable_id = :erudsxing_golden_maiden_lt: WHERE id in (98054); # Golden_Maiden 50
UPDATE npc_types SET loottable_id = :erudsxing_hojo_lt: WHERE id in (98034); # Hojo 13
UPDATE npc_types SET loottable_id = :erudsxing_jarra_lt: WHERE id in (98040); # Jarra 14
UPDATE npc_types SET loottable_id = :erudsxing_kala_lt: WHERE id in (98039); # Kala 13
UPDATE npc_types SET loottable_id = :erudsxing_kerra_isle_beetle_lt: WHERE id in (98016); # Kerra_Isle_beetle 2
UPDATE npc_types SET loottable_id = :erudsxing_milla_lt: WHERE id in (98035); # Milla 17
UPDATE npc_types SET loottable_id = :erudsxing_monala_lt: WHERE id in (98036); # Monala 17
UPDATE npc_types SET loottable_id = :erudsxing_nifta_lt: WHERE id in (98037); # Nifta 13
UPDATE npc_types SET loottable_id = :erudsxing_nomala_lt: WHERE id in (98004); # Nomala 4
UPDATE npc_types SET loottable_id = :erudsxing_ooglyn_lt: WHERE id in (98009); # Ooglyn 45
UPDATE npc_types SET loottable_id = :erudsxing_renna_lt: WHERE id in (98038); # Renna 16
UPDATE npc_types SET loottable_id = :erudsxing_sea_king_lt: WHERE id in (98053); # Sea_King 50
UPDATE npc_types SET loottable_id = :erudsxing_srafen_the_soaked_lt: WHERE id in (98046); # Srafen_the_Soaked 20
UPDATE npc_types SET loottable_id = :erudsxing_tolo_lt: WHERE id in (98041); # Tolo 16
UPDATE npc_types SET loottable_id = :erudsxing_undead_erudite_sailor_lt: WHERE id in (98024); # undead_erudite_sailor 35
UPDATE npc_types SET loottable_id = :erudsxing_undead_troll_sailor_lt: WHERE id in (98023); # undead_troll_sailor 35
UPDATE npc_types SET loottable_id = :erudsxing_yelesom_paust_lt: WHERE id in (98044); # Yelesom_Paust 20
UPDATE npc_types SET loottable_id = :erudsxing_yun_assistant_maldok_lt: WHERE id in (98008); # Yun_Assistant_Maldok 20
UPDATE npc_types SET loottable_id = :erudsxing_zombie_sailor_lt: WHERE id in (98025, 98026); # Zombie_Sailor 10
UPDATE npc_types SET loottable_id = :erudsxing_zoner_template_copy_lt: WHERE id in (98055); # zoner_template_copy 60
