INSERT INTO loottable(name) VALUES('fearplane_the_tempest_reaver'); # :fearplane_the_tempest_reaver_lt:
INSERT INTO loottable(name) VALUES('fearplane_amygdalan_knight'); # :fearplane_amygdalan_knight_lt:
INSERT INTO loottable(name) VALUES('fearplane_amygdalan_warrior'); # :fearplane_amygdalan_warrior_lt:
INSERT INTO loottable(name) VALUES('fearplane_an_enraged_golem'); # :fearplane_an_enraged_golem_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_boogeyman'); # :fearplane_a_boogeyman_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_broken_golem'); # :fearplane_a_broken_golem_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_decrepit_warder'); # :fearplane_a_decrepit_warder_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_dracoliche'); # :fearplane_a_dracoliche_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_fetid_fiend'); # :fearplane_a_fetid_fiend_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_frightfinger'); # :fearplane_a_frightfinger_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_glare_lord'); # :fearplane_a_glare_lord_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_gorgon'); # :fearplane_a_gorgon_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_nightmare'); # :fearplane_a_nightmare_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_phantasm'); # :fearplane_a_phantasm_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_samhain'); # :fearplane_a_samhain_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_scareling'); # :fearplane_a_scareling_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_shiverback'); # :fearplane_a_shiverback_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_spinechiller_spider'); # :fearplane_a_spinechiller_spider_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_tentacle_tormentor'); # :fearplane_a_tentacle_tormentor_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_turmoil_toad'); # :fearplane_a_turmoil_toad_lt:
INSERT INTO loottable(name) VALUES('fearplane_a_worry_wraith'); # :fearplane_a_worry_wraith_lt:
INSERT INTO loottable(name) VALUES('fearplane_cazic_thule'); # :fearplane_cazic_thule_lt:
INSERT INTO loottable(name) VALUES('fearplane_dread'); # :fearplane_dread_lt:
INSERT INTO loottable(name) VALUES('fearplane_enraged_imp'); # :fearplane_enraged_imp_lt:
INSERT INTO loottable(name) VALUES('fearplane_essence_of_rage'); # :fearplane_essence_of_rage_lt:
INSERT INTO loottable(name) VALUES('fearplane_fright'); # :fearplane_fright_lt:
INSERT INTO loottable(name) VALUES('fearplane_iksar_broodling'); # :fearplane_iksar_broodling_lt:
INSERT INTO loottable(name) VALUES('fearplane_irak_altil'); # :fearplane_irak_altil_lt:
INSERT INTO loottable(name) VALUES('fearplane_ireblind_imp'); # :fearplane_ireblind_imp_lt:
INSERT INTO loottable(name) VALUES('fearplane_phoboplasm'); # :fearplane_phoboplasm_lt:
INSERT INTO loottable(name) VALUES('fearplane_terror'); # :fearplane_terror_lt:
INSERT INTO loottable(name) VALUES('fearplane_wraith_of_a_shissar'); # :fearplane_wraith_of_a_shissar_lt:
INSERT INTO loottable(name) VALUES('fearplane_wraith_of_a_shissir'); # :fearplane_wraith_of_a_shissir_lt:
