INSERT INTO loottable(name) VALUES('feerrott__thugat_the_champion'); # :feerrott__thugat_the_champion_lt:
INSERT INTO loottable(name) VALUES('feerrott_druid_epic_trap'); # :feerrott_druid_epic_trap_lt:
INSERT INTO loottable(name) VALUES('feerrott_emissary_shinsere'); # :feerrott_emissary_shinsere_lt:
INSERT INTO loottable(name) VALUES('feerrott_roror'); # :feerrott_roror_lt:
INSERT INTO loottable(name) VALUES('feerrott_swamp_terror'); # :feerrott_swamp_terror_lt:
INSERT INTO loottable(name) VALUES('feerrott_annaelia_wylassi'); # :feerrott_annaelia_wylassi_lt:
INSERT INTO loottable(name) VALUES('feerrott_an_alligator'); # :feerrott_an_alligator_lt:
INSERT INTO loottable(name) VALUES('feerrott_an_infected_rat'); # :feerrott_an_infected_rat_lt:
INSERT INTO loottable(name) VALUES('feerrott_aqaar_aluram'); # :feerrott_aqaar_aluram_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_bat'); # :feerrott_a_bat_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_black_wolf'); # :feerrott_a_black_wolf_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_decaying_skeleton'); # :feerrott_a_decaying_skeleton_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_dry_bones_skeleton'); # :feerrott_a_dry_bones_skeleton_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_froglok_tad'); # :feerrott_a_froglok_tad_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_giant_bat'); # :feerrott_a_giant_bat_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_gorilla'); # :feerrott_a_gorilla_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_green_snake'); # :feerrott_a_green_snake_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_hatchling'); # :feerrott_a_hatchling_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_hulking_gorilla'); # :feerrott_a_hulking_gorilla_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_jungle_spider'); # :feerrott_a_jungle_spider_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_jungle_spiderling'); # :feerrott_a_jungle_spiderling_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_large_gorilla'); # :feerrott_a_large_gorilla_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_large_piranha'); # :feerrott_a_large_piranha_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_lesser_scarab'); # :feerrott_a_lesser_scarab_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_lizardman_broodling'); # :feerrott_a_lizardman_broodling_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_lizardman_forager'); # :feerrott_a_lizardman_forager_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_lizardman_mystic'); # :feerrott_a_lizardman_mystic_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_lizardman_scout'); # :feerrott_a_lizardman_scout_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_lizardman_warrior'); # :feerrott_a_lizardman_warrior_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_lizardman_watcher'); # :feerrott_a_lizardman_watcher_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_marsh_bear'); # :feerrott_a_marsh_bear_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_marsh_bear_cub'); # :feerrott_a_marsh_bear_cub_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_minor_scarab'); # :feerrott_a_minor_scarab_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_shadow_wolf'); # :feerrott_a_shadow_wolf_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_sharp'); # :feerrott_a_sharp_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_silvered_tae_ew_observer'); # :feerrott_a_silvered_tae_ew_observer_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_silverflank_guardian'); # :feerrott_a_silverflank_guardian_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_skeletal_commander'); # :feerrott_a_skeletal_commander_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_skeletal_conscript'); # :feerrott_a_skeletal_conscript_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_skeletal_footsoldier'); # :feerrott_a_skeletal_footsoldier_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_skeletal_lieutenant'); # :feerrott_a_skeletal_lieutenant_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_skeletal_trooper'); # :feerrott_a_skeletal_trooper_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_skeleton'); # :feerrott_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_snake'); # :feerrott_a_snake_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_spectre'); # :feerrott_a_spectre_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_swamp_alligator'); # :feerrott_a_swamp_alligator_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_crusader'); # :feerrott_a_tae_ew_crusader_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_defender'); # :feerrott_a_tae_ew_defender_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_disciple'); # :feerrott_a_tae_ew_disciple_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_fanatic'); # :feerrott_a_tae_ew_fanatic_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_herald'); # :feerrott_a_tae_ew_herald_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_judicator'); # :feerrott_a_tae_ew_judicator_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_justicar'); # :feerrott_a_tae_ew_justicar_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_page'); # :feerrott_a_tae_ew_page_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_probationer'); # :feerrott_a_tae_ew_probationer_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_protector'); # :feerrott_a_tae_ew_protector_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_sentinel'); # :feerrott_a_tae_ew_sentinel_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_spiritualist'); # :feerrott_a_tae_ew_spiritualist_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_warder'); # :feerrott_a_tae_ew_warder_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tae_ew_zealot'); # :feerrott_a_tae_ew_zealot_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_tree_snake'); # :feerrott_a_tree_snake_lt:
INSERT INTO loottable(name) VALUES('feerrott_a_zombie'); # :feerrott_a_zombie_lt:
INSERT INTO loottable(name) VALUES('feerrott_bouncer_flerb'); # :feerrott_bouncer_flerb_lt:
INSERT INTO loottable(name) VALUES('feerrott_bouncer_fug'); # :feerrott_bouncer_fug_lt:
INSERT INTO loottable(name) VALUES('feerrott_bouncer_hurd'); # :feerrott_bouncer_hurd_lt:
INSERT INTO loottable(name) VALUES('feerrott_bouncer_prud'); # :feerrott_bouncer_prud_lt:
INSERT INTO loottable(name) VALUES('feerrott_bup'); # :feerrott_bup_lt:
INSERT INTO loottable(name) VALUES('feerrott_corrupted_spirit'); # :feerrott_corrupted_spirit_lt:
INSERT INTO loottable(name) VALUES('feerrott_cyndreela'); # :feerrott_cyndreela_lt:
INSERT INTO loottable(name) VALUES('feerrott_dark_assassin'); # :feerrott_dark_assassin_lt:
INSERT INTO loottable(name) VALUES('feerrott_drizda_tunesinger'); # :feerrott_drizda_tunesinger_lt:
INSERT INTO loottable(name) VALUES('feerrott_duga'); # :feerrott_duga_lt:
INSERT INTO loottable(name) VALUES('feerrott_eleann_morkul'); # :feerrott_eleann_morkul_lt:
INSERT INTO loottable(name) VALUES('feerrott_fugla'); # :feerrott_fugla_lt:
INSERT INTO loottable(name) VALUES('feerrott_grak'); # :feerrott_grak_lt:
INSERT INTO loottable(name) VALUES('feerrott_greenblood_zombie'); # :feerrott_greenblood_zombie_lt:
INSERT INTO loottable(name) VALUES('feerrott_grinak'); # :feerrott_grinak_lt:
INSERT INTO loottable(name) VALUES('feerrott_innkeep_gub'); # :feerrott_innkeep_gub_lt:
INSERT INTO loottable(name) VALUES('feerrott_innkeep_morpa'); # :feerrott_innkeep_morpa_lt:
INSERT INTO loottable(name) VALUES('feerrott_kogg'); # :feerrott_kogg_lt:
INSERT INTO loottable(name) VALUES('feerrott_mugu'); # :feerrott_mugu_lt:
INSERT INTO loottable(name) VALUES('feerrott_murg'); # :feerrott_murg_lt:
INSERT INTO loottable(name) VALUES('feerrott_murga'); # :feerrott_murga_lt:
INSERT INTO loottable(name) VALUES('feerrott_oknoggin_stonesmacker'); # :feerrott_oknoggin_stonesmacker_lt:
INSERT INTO loottable(name) VALUES('feerrott_radiant'); # :feerrott_radiant_lt:
INSERT INTO loottable(name) VALUES('feerrott_scout_ahlikal'); # :feerrott_scout_ahlikal_lt:
INSERT INTO loottable(name) VALUES('feerrott_spanner_scrapsnatcher'); # :feerrott_spanner_scrapsnatcher_lt:
INSERT INTO loottable(name) VALUES('feerrott_tae_ew_archon'); # :feerrott_tae_ew_archon_lt:
INSERT INTO loottable(name) VALUES('feerrott_tae_ew_diviner'); # :feerrott_tae_ew_diviner_lt:
INSERT INTO loottable(name) VALUES('feerrott_tae_ew_templar'); # :feerrott_tae_ew_templar_lt:
INSERT INTO loottable(name) VALUES('feerrott_the_spirit_of_decay'); # :feerrott_the_spirit_of_decay_lt:
INSERT INTO loottable(name) VALUES('feerrott_thul_tae_ew_cenobite'); # :feerrott_thul_tae_ew_cenobite_lt:
