INSERT INTO loottable(name) VALUES('feerrott2_ashrin_tvahn'); # :feerrott2_ashrin_tvahn_lt:
INSERT INTO loottable(name) VALUES('feerrott2_bouncer_flerb'); # :feerrott2_bouncer_flerb_lt:
INSERT INTO loottable(name) VALUES('feerrott2_bouncer_fug'); # :feerrott2_bouncer_fug_lt:
INSERT INTO loottable(name) VALUES('feerrott2_bouncer_prud'); # :feerrott2_bouncer_prud_lt:
INSERT INTO loottable(name) VALUES('feerrott2_cyndreela'); # :feerrott2_cyndreela_lt:
INSERT INTO loottable(name) VALUES('feerrott2_dark_alchemist_illian'); # :feerrott2_dark_alchemist_illian_lt:
INSERT INTO loottable(name) VALUES('feerrott2_dorran_flightfoot'); # :feerrott2_dorran_flightfoot_lt:
INSERT INTO loottable(name) VALUES('feerrott2_dyla'); # :feerrott2_dyla_lt:
INSERT INTO loottable(name) VALUES('feerrott2_feril_brandigar'); # :feerrott2_feril_brandigar_lt:
INSERT INTO loottable(name) VALUES('feerrott2_ferils_campfire'); # :feerrott2_ferils_campfire_lt:
INSERT INTO loottable(name) VALUES('feerrott2_festerback'); # :feerrott2_festerback_lt:
INSERT INTO loottable(name) VALUES('feerrott2_gananorn'); # :feerrott2_gananorn_lt:
INSERT INTO loottable(name) VALUES('feerrott2_ginale_vaultseeker'); # :feerrott2_ginale_vaultseeker_lt:
INSERT INTO loottable(name) VALUES('feerrott2_gonop'); # :feerrott2_gonop_lt:
INSERT INTO loottable(name) VALUES('feerrott2_graylenn_reskan'); # :feerrott2_graylenn_reskan_lt:
INSERT INTO loottable(name) VALUES('feerrott2_kaelynn_stearns'); # :feerrott2_kaelynn_stearns_lt:
INSERT INTO loottable(name) VALUES('feerrott2_kavri_flightfoot'); # :feerrott2_kavri_flightfoot_lt:
INSERT INTO loottable(name) VALUES('feerrott2_kyluc'); # :feerrott2_kyluc_lt:
INSERT INTO loottable(name) VALUES('feerrott2_lerg'); # :feerrott2_lerg_lt:
INSERT INTO loottable(name) VALUES('feerrott2_orloh'); # :feerrott2_orloh_lt:
INSERT INTO loottable(name) VALUES('feerrott2_rathen_darkforest'); # :feerrott2_rathen_darkforest_lt:
INSERT INTO loottable(name) VALUES('feerrott2_rotharran_radhelm'); # :feerrott2_rotharran_radhelm_lt:
INSERT INTO loottable(name) VALUES('feerrott2_rupkerr'); # :feerrott2_rupkerr_lt:
INSERT INTO loottable(name) VALUES('feerrott2_sentinel_quilaztli'); # :feerrott2_sentinel_quilaztli_lt:
INSERT INTO loottable(name) VALUES('feerrott2_shalma'); # :feerrott2_shalma_lt:
INSERT INTO loottable(name) VALUES('feerrott2_trepek_gruplin'); # :feerrott2_trepek_gruplin_lt:
INSERT INTO loottable(name) VALUES('feerrott2_william_the_tall'); # :feerrott2_william_the_tall_lt:
INSERT INTO loottable(name) VALUES('feerrott2_zande_vorich'); # :feerrott2_zande_vorich_lt:
INSERT INTO loottable(name) VALUES('feerrott2_an_aggitated_spirit'); # :feerrott2_an_aggitated_spirit_lt:
INSERT INTO loottable(name) VALUES('feerrott2_an_angry_gorilla_patriarch'); # :feerrott2_an_angry_gorilla_patriarch_lt:
INSERT INTO loottable(name) VALUES('feerrott2_an_empowered_fallen_explorer'); # :feerrott2_an_empowered_fallen_explorer_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_blighted_gorilla'); # :feerrott2_a_blighted_gorilla_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_bloodbathed_skeleton'); # :feerrott2_a_bloodbathed_skeleton_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_bloodbone_lich'); # :feerrott2_a_bloodbone_lich_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_bloodbone_skeleton'); # :feerrott2_a_bloodbone_skeleton_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_bloodied_skeleton'); # :feerrott2_a_bloodied_skeleton_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_bloody_tae_ew_ritualist'); # :feerrott2_a_bloody_tae_ew_ritualist_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_corrupt_orbweaver'); # :feerrott2_a_corrupt_orbweaver_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_deadly_viper'); # :feerrott2_a_deadly_viper_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_decaying_gorilla'); # :feerrott2_a_decaying_gorilla_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_deceased_traveler'); # :feerrott2_a_deceased_traveler_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_dedicated_tae_ew'); # :feerrott2_a_dedicated_tae_ew_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_drowned_explorer'); # :feerrott2_a_drowned_explorer_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_drybone_skeleton'); # :feerrott2_a_drybone_skeleton_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_fallen_traveler'); # :feerrott2_a_fallen_traveler_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_flesh_feeder'); # :feerrott2_a_flesh_feeder_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_frenzied_feeder'); # :feerrott2_a_frenzied_feeder_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_frenzied_tae_ew'); # :feerrott2_a_frenzied_tae_ew_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_frightful_spirit'); # :feerrott2_a_frightful_spirit_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_froglok_corpse'); # :feerrott2_a_froglok_corpse_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_gorilla_matron'); # :feerrott2_a_gorilla_matron_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_gorilla_patriarch'); # :feerrott2_a_gorilla_patriarch_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_jungle_crawler'); # :feerrott2_a_jungle_crawler_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lingering_revenant'); # :feerrott2_a_lingering_revenant_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lingering_spirit'); # :feerrott2_a_lingering_spirit_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lizardman_brute'); # :feerrott2_a_lizardman_brute_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lizardman_corpse'); # :feerrott2_a_lizardman_corpse_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lizardman_mystic'); # :feerrott2_a_lizardman_mystic_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lizardman_patroller'); # :feerrott2_a_lizardman_patroller_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lizardman_scrapper'); # :feerrott2_a_lizardman_scrapper_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lizardman_thug'); # :feerrott2_a_lizardman_thug_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lizardman_visionary'); # :feerrott2_a_lizardman_visionary_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_lizardman_watcher'); # :feerrott2_a_lizardman_watcher_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_ravenous_rotdog'); # :feerrott2_a_ravenous_rotdog_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_restless_spirit'); # :feerrott2_a_restless_spirit_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_rotdog_scavenger'); # :feerrott2_a_rotdog_scavenger_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_sinuous_adder'); # :feerrott2_a_sinuous_adder_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_slithering_adder'); # :feerrott2_a_slithering_adder_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_stalking_crawler'); # :feerrott2_a_stalking_crawler_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_aggressor'); # :feerrott2_a_tae_ew_aggressor_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_devotee'); # :feerrott2_a_tae_ew_devotee_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_disciple'); # :feerrott2_a_tae_ew_disciple_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_drudge'); # :feerrott2_a_tae_ew_drudge_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_enforcer'); # :feerrott2_a_tae_ew_enforcer_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_exalter'); # :feerrott2_a_tae_ew_exalter_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_invoker'); # :feerrott2_a_tae_ew_invoker_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_ritualist'); # :feerrott2_a_tae_ew_ritualist_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_scavenger'); # :feerrott2_a_tae_ew_scavenger_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tae_ew_worshiper'); # :feerrott2_a_tae_ew_worshiper_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tainted_orbweaver'); # :feerrott2_a_tainted_orbweaver_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tanglefang_hunter'); # :feerrott2_a_tanglefang_hunter_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tanglefang_huntress'); # :feerrott2_a_tanglefang_huntress_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tanglefang_prowler'); # :feerrott2_a_tanglefang_prowler_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_tanglefang_stalker'); # :feerrott2_a_tanglefang_stalker_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_toxic_orbweaver'); # :feerrott2_a_toxic_orbweaver_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_venomous_viper'); # :feerrott2_a_venomous_viper_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_waterlogged_explorer'); # :feerrott2_a_waterlogged_explorer_lt:
INSERT INTO loottable(name) VALUES('feerrott2_a_young_gorilla'); # :feerrott2_a_young_gorilla_lt:
INSERT INTO loottable(name) VALUES('feerrott2_bup'); # :feerrott2_bup_lt:
INSERT INTO loottable(name) VALUES('feerrott2_campfire'); # :feerrott2_campfire_lt:
INSERT INTO loottable(name) VALUES('feerrott2_delvers_campfire'); # :feerrott2_delvers_campfire_lt:
INSERT INTO loottable(name) VALUES('feerrott2_duga'); # :feerrott2_duga_lt:
INSERT INTO loottable(name) VALUES('feerrott2_eye_of_dragonrose'); # :feerrott2_eye_of_dragonrose_lt:
INSERT INTO loottable(name) VALUES('feerrott2_fsp-general-noeffect'); # :feerrott2_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('feerrott2_fugla'); # :feerrott2_fugla_lt:
INSERT INTO loottable(name) VALUES('feerrott2_gbn-general-noeffect'); # :feerrott2_gbn-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('feerrott2_grak'); # :feerrott2_grak_lt:
INSERT INTO loottable(name) VALUES('feerrott2_innkeep_gub'); # :feerrott2_innkeep_gub_lt:
INSERT INTO loottable(name) VALUES('feerrott2_innkeep_morpa'); # :feerrott2_innkeep_morpa_lt:
INSERT INTO loottable(name) VALUES('feerrott2_kogg'); # :feerrott2_kogg_lt:
INSERT INTO loottable(name) VALUES('feerrott2_mugu'); # :feerrott2_mugu_lt:
INSERT INTO loottable(name) VALUES('feerrott2_murg'); # :feerrott2_murg_lt:
INSERT INTO loottable(name) VALUES('feerrott2_murga'); # :feerrott2_murga_lt:
