INSERT INTO loottable(name) VALUES('felwitheb_alicia_starshimmer'); # :felwitheb_alicia_starshimmer_lt:
INSERT INTO loottable(name) VALUES('felwitheb_berill_gladeleaper'); # :felwitheb_berill_gladeleaper_lt:
INSERT INTO loottable(name) VALUES('felwitheb_celent_newmist'); # :felwitheb_celent_newmist_lt:
INSERT INTO loottable(name) VALUES('felwitheb_elishia_leafrunner'); # :felwitheb_elishia_leafrunner_lt:
INSERT INTO loottable(name) VALUES('felwitheb_elle_leafdancer'); # :felwitheb_elle_leafdancer_lt:
INSERT INTO loottable(name) VALUES('felwitheb_est_treewalker'); # :felwitheb_est_treewalker_lt:
INSERT INTO loottable(name) VALUES('felwitheb_farios_elianos'); # :felwitheb_farios_elianos_lt:
INSERT INTO loottable(name) VALUES('felwitheb_griff_candleflame'); # :felwitheb_griff_candleflame_lt:
INSERT INTO loottable(name) VALUES('felwitheb_guard_golyn'); # :felwitheb_guard_golyn_lt:
INSERT INTO loottable(name) VALUES('felwitheb_guard_mystan'); # :felwitheb_guard_mystan_lt:
INSERT INTO loottable(name) VALUES('felwitheb_guard_plage'); # :felwitheb_guard_plage_lt:
INSERT INTO loottable(name) VALUES('felwitheb_guard_psape'); # :felwitheb_guard_psape_lt:
INSERT INTO loottable(name) VALUES('felwitheb_guard_spioko'); # :felwitheb_guard_spioko_lt:
INSERT INTO loottable(name) VALUES('felwitheb_guard_tistan'); # :felwitheb_guard_tistan_lt:
INSERT INTO loottable(name) VALUES('felwitheb_guard_tynthal'); # :felwitheb_guard_tynthal_lt:
INSERT INTO loottable(name) VALUES('felwitheb_joren_nobleheart'); # :felwitheb_joren_nobleheart_lt:
INSERT INTO loottable(name) VALUES('felwitheb_kinool_goldsinger'); # :felwitheb_kinool_goldsinger_lt:
INSERT INTO loottable(name) VALUES('felwitheb_merchant_earlyn'); # :felwitheb_merchant_earlyn_lt:
INSERT INTO loottable(name) VALUES('felwitheb_merchant_jewyln'); # :felwitheb_merchant_jewyln_lt:
INSERT INTO loottable(name) VALUES('felwitheb_merchant_lyssia'); # :felwitheb_merchant_lyssia_lt:
INSERT INTO loottable(name) VALUES('felwitheb_merchant_moonthread'); # :felwitheb_merchant_moonthread_lt:
INSERT INTO loottable(name) VALUES('felwitheb_merchant_tyslin'); # :felwitheb_merchant_tyslin_lt:
INSERT INTO loottable(name) VALUES('felwitheb_merchant_yisasan'); # :felwitheb_merchant_yisasan_lt:
INSERT INTO loottable(name) VALUES('felwitheb_nestess_branchtop'); # :felwitheb_nestess_branchtop_lt:
INSERT INTO loottable(name) VALUES('felwitheb_niola_impholder'); # :felwitheb_niola_impholder_lt:
INSERT INTO loottable(name) VALUES('felwitheb_osisa_goldenspear'); # :felwitheb_osisa_goldenspear_lt:
INSERT INTO loottable(name) VALUES('felwitheb_porra'); # :felwitheb_porra_lt:
INSERT INTO loottable(name) VALUES('felwitheb_quiss_stormseeker'); # :felwitheb_quiss_stormseeker_lt:
INSERT INTO loottable(name) VALUES('felwitheb_reff_truewood'); # :felwitheb_reff_truewood_lt:
INSERT INTO loottable(name) VALUES('felwitheb_seren_the_swift'); # :felwitheb_seren_the_swift_lt:
INSERT INTO loottable(name) VALUES('felwitheb_serri_moonwatcher'); # :felwitheb_serri_moonwatcher_lt:
INSERT INTO loottable(name) VALUES('felwitheb_srell_tumblebrook'); # :felwitheb_srell_tumblebrook_lt:
INSERT INTO loottable(name) VALUES('felwitheb_stormy'); # :felwitheb_stormy_lt:
INSERT INTO loottable(name) VALUES('felwitheb_tarker_blazetoss'); # :felwitheb_tarker_blazetoss_lt:
INSERT INTO loottable(name) VALUES('felwitheb_thwinose_vilgarn'); # :felwitheb_thwinose_vilgarn_lt:
INSERT INTO loottable(name) VALUES('felwitheb_vellera_wintergreen'); # :felwitheb_vellera_wintergreen_lt:
INSERT INTO loottable(name) VALUES('felwitheb_xista_finder'); # :felwitheb_xista_finder_lt:
INSERT INTO loottable(name) VALUES('felwitheb_yuin_starchaser'); # :felwitheb_yuin_starchaser_lt:
