INSERT INTO loottable(name) VALUES('grobb_artisan_zermak'); # :grobb_artisan_zermak_lt:
INSERT INTO loottable(name) VALUES('grobb_a_domesticated_bleeder'); # :grobb_a_domesticated_bleeder_lt:
INSERT INTO loottable(name) VALUES('grobb_a_froglok_prisoner'); # :grobb_a_froglok_prisoner_lt:
INSERT INTO loottable(name) VALUES('grobb_a_frostfell_goblin'); # :grobb_a_frostfell_goblin_lt:
INSERT INTO loottable(name) VALUES('grobb_a_greater_zombie'); # :grobb_a_greater_zombie_lt:
INSERT INTO loottable(name) VALUES('grobb_a_jungle_hatchling'); # :grobb_a_jungle_hatchling_lt:
INSERT INTO loottable(name) VALUES('grobb_a_prisoner'); # :grobb_a_prisoner_lt:
INSERT INTO loottable(name) VALUES('grobb_a_sharptooth_caribe'); # :grobb_a_sharptooth_caribe_lt:
INSERT INTO loottable(name) VALUES('grobb_a_skeleton'); # :grobb_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('grobb_bahagg'); # :grobb_bahagg_lt:
INSERT INTO loottable(name) VALUES('grobb_barsk'); # :grobb_barsk_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_avisk'); # :grobb_basher_avisk_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_banzuk'); # :grobb_basher_banzuk_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_bibeka'); # :grobb_basher_bibeka_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_bugak'); # :grobb_basher_bugak_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_gamuk'); # :grobb_basher_gamuk_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_glaum'); # :grobb_basher_glaum_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_gobzin'); # :grobb_basher_gobzin_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_gubaku'); # :grobb_basher_gubaku_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_kankuk'); # :grobb_basher_kankuk_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_kigak'); # :grobb_basher_kigak_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_kumek'); # :grobb_basher_kumek_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_nagkuma'); # :grobb_basher_nagkuma_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_nanrum'); # :grobb_basher_nanrum_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_rakguk'); # :grobb_basher_rakguk_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_razbaz'); # :grobb_basher_razbaz_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_roruma'); # :grobb_basher_roruma_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_scintok'); # :grobb_basher_scintok_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_stizik'); # :grobb_basher_stizik_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_sutok'); # :grobb_basher_sutok_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_thintan'); # :grobb_basher_thintan_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_uvgin'); # :grobb_basher_uvgin_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_wisthak'); # :grobb_basher_wisthak_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_zabaak'); # :grobb_basher_zabaak_lt:
INSERT INTO loottable(name) VALUES('grobb_basher_zazluk'); # :grobb_basher_zazluk_lt:
INSERT INTO loottable(name) VALUES('grobb_beztopi'); # :grobb_beztopi_lt:
INSERT INTO loottable(name) VALUES('grobb_bimuk'); # :grobb_bimuk_lt:
INSERT INTO loottable(name) VALUES('grobb_blergagg'); # :grobb_blergagg_lt:
INSERT INTO loottable(name) VALUES('grobb_blergrab'); # :grobb_blergrab_lt:
INSERT INTO loottable(name) VALUES('grobb_blorgok_gkapbron'); # :grobb_blorgok_gkapbron_lt:
INSERT INTO loottable(name) VALUES('grobb_bregna'); # :grobb_bregna_lt:
INSERT INTO loottable(name) VALUES('grobb_bukton'); # :grobb_bukton_lt:
INSERT INTO loottable(name) VALUES('grobb_carver_cagrek'); # :grobb_carver_cagrek_lt:
INSERT INTO loottable(name) VALUES('grobb_chamt'); # :grobb_chamt_lt:
INSERT INTO loottable(name) VALUES('grobb_chopper_brenga'); # :grobb_chopper_brenga_lt:
INSERT INTO loottable(name) VALUES('grobb_corrupted_shaman'); # :grobb_corrupted_shaman_lt:
INSERT INTO loottable(name) VALUES('grobb_cralk'); # :grobb_cralk_lt:
INSERT INTO loottable(name) VALUES('grobb_crilt'); # :grobb_crilt_lt:
INSERT INTO loottable(name) VALUES('grobb_daboo_dogak'); # :grobb_daboo_dogak_lt:
INSERT INTO loottable(name) VALUES('grobb_fireworks_engineer_fabdabus'); # :grobb_fireworks_engineer_fabdabus_lt:
INSERT INTO loottable(name) VALUES('grobb_gardunk'); # :grobb_gardunk_lt:
INSERT INTO loottable(name) VALUES('grobb_gargh'); # :grobb_gargh_lt:
INSERT INTO loottable(name) VALUES('grobb_garklog'); # :grobb_garklog_lt:
INSERT INTO loottable(name) VALUES('grobb_gartonka'); # :grobb_gartonka_lt:
INSERT INTO loottable(name) VALUES('grobb_gemcrafter_tessu'); # :grobb_gemcrafter_tessu_lt:
INSERT INTO loottable(name) VALUES('grobb_glubtak'); # :grobb_glubtak_lt:
INSERT INTO loottable(name) VALUES('grobb_gluku'); # :grobb_gluku_lt:
INSERT INTO loottable(name) VALUES('grobb_goldush'); # :grobb_goldush_lt:
INSERT INTO loottable(name) VALUES('grobb_grabah'); # :grobb_grabah_lt:
INSERT INTO loottable(name) VALUES('grobb_graktak'); # :grobb_graktak_lt:
INSERT INTO loottable(name) VALUES('grobb_gralok'); # :grobb_gralok_lt:
INSERT INTO loottable(name) VALUES('grobb_grigdor'); # :grobb_grigdor_lt:
INSERT INTO loottable(name) VALUES('grobb_hargar_the_velium_chef'); # :grobb_hargar_the_velium_chef_lt:
INSERT INTO loottable(name) VALUES('grobb_hartok'); # :grobb_hartok_lt:
INSERT INTO loottable(name) VALUES('grobb_hergor'); # :grobb_hergor_lt:
INSERT INTO loottable(name) VALUES('grobb_hoart'); # :grobb_hoart_lt:
INSERT INTO loottable(name) VALUES('grobb_hukulk'); # :grobb_hukulk_lt:
INSERT INTO loottable(name) VALUES('grobb_iskopa'); # :grobb_iskopa_lt:
INSERT INTO loottable(name) VALUES('grobb_jarlok'); # :grobb_jarlok_lt:
INSERT INTO loottable(name) VALUES('grobb_jokca'); # :grobb_jokca_lt:
INSERT INTO loottable(name) VALUES('grobb_kagbkek'); # :grobb_kagbkek_lt:
INSERT INTO loottable(name) VALUES('grobb_kaglari'); # :grobb_kaglari_lt:
INSERT INTO loottable(name) VALUES('grobb_korff'); # :grobb_korff_lt:
INSERT INTO loottable(name) VALUES('grobb_kragia'); # :grobb_kragia_lt:
INSERT INTO loottable(name) VALUES('grobb_kramf'); # :grobb_kramf_lt:
INSERT INTO loottable(name) VALUES('grobb_kugaran'); # :grobb_kugaran_lt:
INSERT INTO loottable(name) VALUES('grobb_lord_bergurgle'); # :grobb_lord_bergurgle_lt:
INSERT INTO loottable(name) VALUES('grobb_luruk_dridor'); # :grobb_luruk_dridor_lt:
INSERT INTO loottable(name) VALUES('grobb_mulg'); # :grobb_mulg_lt:
INSERT INTO loottable(name) VALUES('grobb_natasha_whitewater'); # :grobb_natasha_whitewater_lt:
INSERT INTO loottable(name) VALUES('grobb_okun'); # :grobb_okun_lt:
INSERT INTO loottable(name) VALUES('grobb_ootok'); # :grobb_ootok_lt:
INSERT INTO loottable(name) VALUES('grobb_prashnak'); # :grobb_prashnak_lt:
INSERT INTO loottable(name) VALUES('grobb_priest_of_discord'); # :grobb_priest_of_discord_lt:
INSERT INTO loottable(name) VALUES('grobb_ranjor'); # :grobb_ranjor_lt:
INSERT INTO loottable(name) VALUES('grobb_rasrok_the_blotched'); # :grobb_rasrok_the_blotched_lt:
INSERT INTO loottable(name) VALUES('grobb_raztara'); # :grobb_raztara_lt:
INSERT INTO loottable(name) VALUES('grobb_rezslog'); # :grobb_rezslog_lt:
INSERT INTO loottable(name) VALUES('grobb_rohga'); # :grobb_rohga_lt:
INSERT INTO loottable(name) VALUES('grobb_sanfik'); # :grobb_sanfik_lt:
INSERT INTO loottable(name) VALUES('grobb_santug_claugg'); # :grobb_santug_claugg_lt:
INSERT INTO loottable(name) VALUES('grobb_savarixsa_zexus'); # :grobb_savarixsa_zexus_lt:
INSERT INTO loottable(name) VALUES('grobb_soulbinder_snog'); # :grobb_soulbinder_snog_lt:
INSERT INTO loottable(name) VALUES('grobb_spinkit'); # :grobb_spinkit_lt:
INSERT INTO loottable(name) VALUES('grobb_tainted_aquagoblin'); # :grobb_tainted_aquagoblin_lt:
INSERT INTO loottable(name) VALUES('grobb_tangiz'); # :grobb_tangiz_lt:
INSERT INTO loottable(name) VALUES('grobb_tokun'); # :grobb_tokun_lt:
INSERT INTO loottable(name) VALUES('grobb_tracab'); # :grobb_tracab_lt:
INSERT INTO loottable(name) VALUES('grobb_treskar'); # :grobb_treskar_lt:
INSERT INTO loottable(name) VALUES('grobb_trusk'); # :grobb_trusk_lt:
INSERT INTO loottable(name) VALUES('grobb_ungia'); # :grobb_ungia_lt:
INSERT INTO loottable(name) VALUES('grobb_urako'); # :grobb_urako_lt:
INSERT INTO loottable(name) VALUES('grobb_uzak'); # :grobb_uzak_lt:
INSERT INTO loottable(name) VALUES('grobb_vergad'); # :grobb_vergad_lt:
INSERT INTO loottable(name) VALUES('grobb_vynugga'); # :grobb_vynugga_lt:
INSERT INTO loottable(name) VALUES('grobb_webclaw_murkwave'); # :grobb_webclaw_murkwave_lt:
INSERT INTO loottable(name) VALUES('grobb_wista'); # :grobb_wista_lt:
INSERT INTO loottable(name) VALUES('grobb_zatok'); # :grobb_zatok_lt:
INSERT INTO loottable(name) VALUES('grobb_zazhar'); # :grobb_zazhar_lt:
INSERT INTO loottable(name) VALUES('grobb_zignal_luk'); # :grobb_zignal_luk_lt:
INSERT INTO loottable(name) VALUES('grobb_zumzal'); # :grobb_zumzal_lt:
