INSERT INTO loottable(name) VALUES('hateplane_ashenbone_broodmaster'); # :hateplane_ashenbone_broodmaster_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_very_unpleasant_hand'); # :hateplane_a_very_unpleasant_hand_lt:
INSERT INTO loottable(name) VALUES('hateplane_coercer_tvala'); # :hateplane_coercer_tvala_lt:
INSERT INTO loottable(name) VALUES('hateplane_the_deathrot_knight'); # :hateplane_the_deathrot_knight_lt:
INSERT INTO loottable(name) VALUES('hateplane_an_abhorrent'); # :hateplane_an_abhorrent_lt:
INSERT INTO loottable(name) VALUES('hateplane_an_agent_of_innoruuk'); # :hateplane_an_agent_of_innoruuk_lt:
INSERT INTO loottable(name) VALUES('hateplane_an_ashenbone_drake'); # :hateplane_an_ashenbone_drake_lt:
INSERT INTO loottable(name) VALUES('hateplane_an_elite_dragoon'); # :hateplane_an_elite_dragoon_lt:
INSERT INTO loottable(name) VALUES('hateplane_an_evangelist_of_hate'); # :hateplane_an_evangelist_of_hate_lt:
INSERT INTO loottable(name) VALUES('hateplane_an_evil_little_imp'); # :hateplane_an_evil_little_imp_lt:
INSERT INTO loottable(name) VALUES('hateplane_an_ire_ghast'); # :hateplane_an_ire_ghast_lt:
INSERT INTO loottable(name) VALUES('hateplane_avatar_of_abhorrence'); # :hateplane_avatar_of_abhorrence_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_barsher_captain'); # :hateplane_a_barsher_captain_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_basher_captain'); # :hateplane_a_basher_captain_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_blood'); # :hateplane_a_blood_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_champion_of_innoruuk'); # :hateplane_a_champion_of_innoruuk_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_craknek_emissary'); # :hateplane_a_craknek_emissary_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_disciple_of_innoruuk'); # :hateplane_a_disciple_of_innoruuk_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_dismal_rager'); # :hateplane_a_dismal_rager_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_forsaken_revenant'); # :hateplane_a_forsaken_revenant_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_greenblood_emissary'); # :hateplane_a_greenblood_emissary_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_greenmist_diplomat'); # :hateplane_a_greenmist_diplomat_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_haunted_chest'); # :hateplane_a_haunted_chest_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_heretic_of_odus'); # :hateplane_a_heretic_of_odus_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_kiraikuei'); # :hateplane_a_kiraikuei_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_knight_of_innoruuk'); # :hateplane_a_knight_of_innoruuk_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_kotiz_ambassador'); # :hateplane_a_kotiz_ambassador_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_loathling_lich'); # :hateplane_a_loathling_lich_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_minister_of_bertoxxulous'); # :hateplane_a_minister_of_bertoxxulous_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_nightkeep_warder'); # :hateplane_a_nightkeep_warder_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_revultant_rat'); # :hateplane_a_revultant_rat_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_sage_of_innoruuk'); # :hateplane_a_sage_of_innoruuk_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_scorn_banshee'); # :hateplane_a_scorn_banshee_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_seeker_of_the_dark_truth'); # :hateplane_a_seeker_of_the_dark_truth_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_spite_golem'); # :hateplane_a_spite_golem_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_steel_warrior'); # :hateplane_a_steel_warrior_lt:
INSERT INTO loottable(name) VALUES('hateplane_a_wise'); # :hateplane_a_wise_lt:
INSERT INTO loottable(name) VALUES('hateplane_cleric_of_innoruuk'); # :hateplane_cleric_of_innoruuk_lt:
INSERT INTO loottable(name) VALUES('hateplane_corrupter_of_life'); # :hateplane_corrupter_of_life_lt:
INSERT INTO loottable(name) VALUES('hateplane_filled'); # :hateplane_filled_lt:
INSERT INTO loottable(name) VALUES('hateplane_grandmaster_rtal'); # :hateplane_grandmaster_rtal_lt:
INSERT INTO loottable(name) VALUES('hateplane_hand_of_the_maestro'); # :hateplane_hand_of_the_maestro_lt:
INSERT INTO loottable(name) VALUES('hateplane_high_priest_mkari'); # :hateplane_high_priest_mkari_lt:
INSERT INTO loottable(name) VALUES('hateplane_innoruuk'); # :hateplane_innoruuk_lt:
INSERT INTO loottable(name) VALUES('hateplane_innoruuks_advisor'); # :hateplane_innoruuks_advisor_lt:
INSERT INTO loottable(name) VALUES('hateplane_innoruuks_chosen'); # :hateplane_innoruuks_chosen_lt:
INSERT INTO loottable(name) VALUES('hateplane_little_eggs_of_evil'); # :hateplane_little_eggs_of_evil_lt:
INSERT INTO loottable(name) VALUES('hateplane_lord_of_loathing'); # :hateplane_lord_of_loathing_lt:
INSERT INTO loottable(name) VALUES('hateplane_maestro_of_rancor'); # :hateplane_maestro_of_rancor_lt:
INSERT INTO loottable(name) VALUES('hateplane_magi_ptasa'); # :hateplane_magi_ptasa_lt:
INSERT INTO loottable(name) VALUES('hateplane_master_of_spite'); # :hateplane_master_of_spite_lt:
INSERT INTO loottable(name) VALUES('hateplane_mistress_of_scorn'); # :hateplane_mistress_of_scorn_lt:
INSERT INTO loottable(name) VALUES('hateplane_showeq_users_are_lame'); # :hateplane_showeq_users_are_lame_lt:
INSERT INTO loottable(name) VALUES('hateplane_suddenly'); # :hateplane_suddenly_lt:
INSERT INTO loottable(name) VALUES('hateplane_the_stench'); # :hateplane_the_stench_lt:
INSERT INTO loottable(name) VALUES('hateplane_you_really'); # :hateplane_you_really_lt:
INSERT INTO loottable(name) VALUES('hateplane_you_would'); # :hateplane_you_would_lt:
