UPDATE npc_types SET loottable_id = :highkeep_a_noble_lt: WHERE id in (6189); # #a_noble 39
UPDATE npc_types SET loottable_id = :highkeep_aeris_greymalkyn_lt: WHERE id in (6063); # Aeris_Greymalkyn 37
UPDATE npc_types SET loottable_id = :highkeep_assistant_kiolna_lt: WHERE id in (6057); # Assistant_Kiolna 25
UPDATE npc_types SET loottable_id = :highkeep_a_clerk_lt: WHERE id in (6075); # a_clerk 45
UPDATE npc_types SET loottable_id = :highkeep_a_crazed_goblin_lt: WHERE id in (6097, 6116); # a_crazed_goblin 23
UPDATE npc_types SET loottable_id = :highkeep_a_dealer_lt: WHERE id in (6076); # a_dealer 45
UPDATE npc_types SET loottable_id = :highkeep_a_goblin_lt: WHERE id in (6087); # a_goblin 25
UPDATE npc_types SET loottable_id = :highkeep_a_goblin_thief_lt: WHERE id in (6144, 6150, 6176, 6040); # a_goblin_thief 24
UPDATE npc_types SET loottable_id = :highkeep_a_guard_lt: WHERE id in (6175, 6014, 6015, 6016, 6017); # a_guard 23
UPDATE npc_types SET loottable_id = :highkeep_a_kitchen_drudge_lt: WHERE id in (6173, 6174, 6071, 6072, 6073, 6136, 6137); # a_kitchen_drudge 11
UPDATE npc_types SET loottable_id = :highkeep_a_lady_in_waiting_lt: WHERE id in (6169, 6069, 6070, 6133); # a_lady_in_waiting 11
UPDATE npc_types SET loottable_id = :highkeep_a_maid_lt: WHERE id in (6168, 6124); # a_maid 8
UPDATE npc_types SET loottable_id = :highkeep_a_noble_lt: WHERE id in (6146, 6086, 6089, 6094, 6096, 6142, 6143); # a_noble 41
UPDATE npc_types SET loottable_id = :highkeep_a_pickclaw_cabalist_lt: WHERE id in (6147, 6088, 6138); # a_pickclaw_cabalist 23
UPDATE npc_types SET loottable_id = :highkeep_a_pickclaw_guard_lt: WHERE id in (6156, 6098, 6139); # a_Pickclaw_guard 26
UPDATE npc_types SET loottable_id = :highkeep_a_pickclaw_lookout_lt: WHERE id in (6080, 6091, 6095); # a_pickclaw_lookout 23
UPDATE npc_types SET loottable_id = :highkeep_a_pickclaw_raider_lt: WHERE id in (6119, 6120); # a_pickclaw_raider 31
UPDATE npc_types SET loottable_id = :highkeep_a_pickclaw_seer_lt: WHERE id in (6038, 6039); # a_Pickclaw_seer 29
UPDATE npc_types SET loottable_id = :highkeep_a_pickclaw_spiritist_lt: WHERE id in (6179, 6093); # a_pickclaw_spiritist 21
UPDATE npc_types SET loottable_id = :highkeep_a_pickclaw_visionary_lt: WHERE id in (6149); # a_pickclaw_visionary 26
UPDATE npc_types SET loottable_id = :highkeep_a_pickclaw_warrior_lt: WHERE id in (6037, 6041); # a_Pickclaw_warrior 30
UPDATE npc_types SET loottable_id = :highkeep_a_prisoner_lt: WHERE id in (6043, 6045, 6053, 6054, 6126); # a_prisoner 10
UPDATE npc_types SET loottable_id = :highkeep_baker_jena_lt: WHERE id in (6049); # Baker_Jena 40
UPDATE npc_types SET loottable_id = :highkeep_bank_clerk_jaylin_lt: WHERE id in (6059); # Bank_Clerk_Jaylin 25
UPDATE npc_types SET loottable_id = :highkeep_captain_bosec_lt: WHERE id in (6034); # Captain_Bosec 34
UPDATE npc_types SET loottable_id = :highkeep_captain_boshinko_lt: WHERE id in (6042); # Captain_Boshinko 40
UPDATE npc_types SET loottable_id = :highkeep_carson_mccabe_lt: WHERE id in (6181); # Carson_McCabe 40
UPDATE npc_types SET loottable_id = :highkeep_dealer_maeline_lt: WHERE id in (6183); # Dealer_Maeline 45
UPDATE npc_types SET loottable_id = :highkeep_dealer_shonta_lt: WHERE id in (6064); # Dealer_Shonta 20
UPDATE npc_types SET loottable_id = :highkeep_dulcyna_blackhand_lt: WHERE id in (6180); # Dulcyna_Blackhand 45
UPDATE npc_types SET loottable_id = :highkeep_dyrna_nlith_lt: WHERE id in (6047, 6134); # Dyrna_Nlith 41
UPDATE npc_types SET loottable_id = :highkeep_fenn_kaedrick_lt: WHERE id in (6184); # Fenn_Kaedrick 1
UPDATE npc_types SET loottable_id = :highkeep_flayer_hopkins_lt: WHERE id in (6048); # Flayer_Hopkins 25
UPDATE npc_types SET loottable_id = :highkeep_grahm_embersmith_lt: WHERE id in (6052); # Grahm_Embersmith 40
UPDATE npc_types SET loottable_id = :highkeep_grex_lt: WHERE id in (6187); # Grex 11
UPDATE npc_types SET loottable_id = :highkeep_guard_anleal_lt: WHERE id in (6163, 6011, 6130); # Guard_Anleal 32
UPDATE npc_types SET loottable_id = :highkeep_guard_antilles_lt: WHERE id in (6162, 6024, 6100); # Guard_Antilles 30
UPDATE npc_types SET loottable_id = :highkeep_guard_bach_lt: WHERE id in (6081, 6114); # Guard_Bach 23
UPDATE npc_types SET loottable_id = :highkeep_guard_bicker_lt: WHERE id in (6188); # Guard_Bicker 27
UPDATE npc_types SET loottable_id = :highkeep_guard_blayle_lt: WHERE id in (6002); # Guard_Blayle 20
UPDATE npc_types SET loottable_id = :highkeep_guard_bolton_lt: WHERE id in (6155, 6033, 6118); # Guard_Bolton 25
UPDATE npc_types SET loottable_id = :highkeep_guard_bonner_lt: WHERE id in (6025, 6101); # Guard_Bonner 26
UPDATE npc_types SET loottable_id = :highkeep_guard_chin_lt: WHERE id in (6031); # Guard_Chin 32
UPDATE npc_types SET loottable_id = :highkeep_guard_chopin_lt: WHERE id in (6164, 6090, 6125); # Guard_Chopin 24
UPDATE npc_types SET loottable_id = :highkeep_guard_clyzen_lt: WHERE id in (6161, 6026, 6102); # Guard_Clyzen 27
UPDATE npc_types SET loottable_id = :highkeep_guard_diff_lt: WHERE id in (6145, 6085); # Guard_Diff 23
UPDATE npc_types SET loottable_id = :highkeep_guard_dister_lt: WHERE id in (6165, 6122); # Guard_Dister 22
UPDATE npc_types SET loottable_id = :highkeep_guard_drugan_lt: WHERE id in (6009, 6112); # Guard_Drugan 24
UPDATE npc_types SET loottable_id = :highkeep_guard_duras_lt: WHERE id in (6151, 6006, 6110); # Guard_Duras 29
UPDATE npc_types SET loottable_id = :highkeep_guard_dwight_lt: WHERE id in (6160, 6012); # Guard_Dwight 29
UPDATE npc_types SET loottable_id = :highkeep_guard_folton_lt: WHERE id in (6003, 6105); # Guard_Folton 21
UPDATE npc_types SET loottable_id = :highkeep_guard_gechop_lt: WHERE id in (6023); # Guard_Gechop 27
UPDATE npc_types SET loottable_id = :highkeep_guard_golgon_lt: WHERE id in (6001, 6107); # Guard_Golgon 23
UPDATE npc_types SET loottable_id = :highkeep_guard_handy_lt: WHERE id in (6171, 6032); # Guard_Handy 31
UPDATE npc_types SET loottable_id = :highkeep_guard_heltch_lt: WHERE id in (6000, 6106); # Guard_Heltch 25
UPDATE npc_types SET loottable_id = :highkeep_guard_jaxon_lt: WHERE id in (6022, 6099); # Guard_Jaxon 26
UPDATE npc_types SET loottable_id = :highkeep_guard_kheb_lt: WHERE id in (6170, 6018); # Guard_Kheb 29
UPDATE npc_types SET loottable_id = :highkeep_guard_kovan_lt: WHERE id in (6035, 6123); # Guard_Kovan 27
UPDATE npc_types SET loottable_id = :highkeep_guard_lancel_lt: WHERE id in (6154, 6007); # Guard_Lancel 24
UPDATE npc_types SET loottable_id = :highkeep_guard_lorton_lt: WHERE id in (6113); # Guard_Lorton 29
UPDATE npc_types SET loottable_id = :highkeep_guard_mytin_lt: WHERE id in (6159, 6021, 6115); # Guard_Mytin 29
UPDATE npc_types SET loottable_id = :highkeep_guard_onto_lt: WHERE id in (6030, 6127); # Guard_Onto 25
UPDATE npc_types SET loottable_id = :highkeep_guard_qanyl_lt: WHERE id in (6166, 6020, 6128); # Guard_Qanyl 26
UPDATE npc_types SET loottable_id = :highkeep_guard_queztin_lt: WHERE id in (6148, 6027, 6103); # Guard_Queztin 27
UPDATE npc_types SET loottable_id = :highkeep_guard_rance_lt: WHERE id in (6152, 6005, 6109); # Guard_Rance 30
UPDATE npc_types SET loottable_id = :highkeep_guard_ruan_lt: WHERE id in (6004, 6129); # Guard_Ruan 25
UPDATE npc_types SET loottable_id = :highkeep_guard_sintra_lt: WHERE id in (6019, 6121); # Guard_Sintra 31
UPDATE npc_types SET loottable_id = :highkeep_guard_sydl_lt: WHERE id in (6158, 6013, 6131); # Guard_Sydl 28
UPDATE npc_types SET loottable_id = :highkeep_guard_wextr_lt: WHERE id in (6177, 6083, 6108); # Guard_Wextr 26
UPDATE npc_types SET loottable_id = :highkeep_guard_xantar_lt: WHERE id in (6178, 6079, 6117); # Guard_Xantar 23
UPDATE npc_types SET loottable_id = :highkeep_guard_yeltin_lt: WHERE id in (6084, 6104); # Guard_Yeltin 25
UPDATE npc_types SET loottable_id = :highkeep_isabella_cellus_lt: WHERE id in (6167, 6082, 6092); # Isabella_Cellus 39
UPDATE npc_types SET loottable_id = :highkeep_jail_clerk_maryl_lt: WHERE id in (6058); # Jail_Clerk_Maryl 40
UPDATE npc_types SET loottable_id = :highkeep_justin_ryhmes_lt: WHERE id in (6062); # Justin_Ryhmes 45
UPDATE npc_types SET loottable_id = :highkeep_krystalle_corsair_lt: WHERE id in (6055); # Krystalle_Corsair 30
UPDATE npc_types SET loottable_id = :highkeep_lady_mccabe_lt: WHERE id in (6067); # Lady_McCabe 37
UPDATE npc_types SET loottable_id = :highkeep_lartin_lt: WHERE id in (6186); # Lartin 11
UPDATE npc_types SET loottable_id = :highkeep_lislia_goldtune_lt: WHERE id in (6036); # Lislia_Goldtune 25
UPDATE npc_types SET loottable_id = :highkeep_lozani_lt: WHERE id in (6029); # Lozani 30
UPDATE npc_types SET loottable_id = :highkeep_lucky_the_beggar_lt: WHERE id in (6157, 6010); # Lucky_the_Beggar 6
UPDATE npc_types SET loottable_id = :highkeep_merchant_dominik_lt: WHERE id in (6050); # Merchant_Dominik 40
UPDATE npc_types SET loottable_id = :highkeep_merchant_edina_lt: WHERE id in (6065); # Merchant_Edina 40
UPDATE npc_types SET loottable_id = :highkeep_miner_harton_lt: WHERE id in (6060); # Miner_Harton 45
UPDATE npc_types SET loottable_id = :highkeep_mistress_anna_lt: WHERE id in (6068); # Mistress_Anna 35
UPDATE npc_types SET loottable_id = :highkeep_osargen_lt: WHERE id in (6051); # Osargen 22
UPDATE npc_types SET loottable_id = :highkeep_princess_lenia_lt: WHERE id in (6172, 6046, 6135); # Princess_Lenia 21
UPDATE npc_types SET loottable_id = :highkeep_purchin_oddsbot_lt: WHERE id in (6074); # Purchin_Oddsbot 35
UPDATE npc_types SET loottable_id = :highkeep_ran_flamespinner_lt: WHERE id in (6066); # Ran_Flamespinner 61
UPDATE npc_types SET loottable_id = :highkeep_rodrick_marslett_lt: WHERE id in (6056); # Rodrick_Marslett 13
UPDATE npc_types SET loottable_id = :highkeep_starr_dreamspinner_lt: WHERE id in (6140); # Starr_DreamSpinner 40
UPDATE npc_types SET loottable_id = :highkeep_storm_dragonchaser_lt: WHERE id in (6141); # Storm_Dragonchaser 40
UPDATE npc_types SET loottable_id = :highkeep_tarn_visilin_lt: WHERE id in (6061); # Tarn_Visilin 45
UPDATE npc_types SET loottable_id = :highkeep_tearon_bleanix_lt: WHERE id in (6078); # Tearon_Bleanix 30
UPDATE npc_types SET loottable_id = :highkeep_treasurer_lynn_lt: WHERE id in (6077); # Treasurer_Lynn 30
UPDATE npc_types SET loottable_id = :highkeep_tsaria_jnarus_lt: WHERE id in (6182); # Tsaria_Jnarus 43
UPDATE npc_types SET loottable_id = :highkeep_tyrana_slil_lt: WHERE id in (6044, 6132); # Tyrana_Slil 30
UPDATE npc_types SET loottable_id = :highkeep_xentil_herkanon_lt: WHERE id in (6185); # Xentil_Herkanon 12
