INSERT INTO loottable(name) VALUES('highkeep_a_noble'); # :highkeep_a_noble_lt:
INSERT INTO loottable(name) VALUES('highkeep_aeris_greymalkyn'); # :highkeep_aeris_greymalkyn_lt:
INSERT INTO loottable(name) VALUES('highkeep_assistant_kiolna'); # :highkeep_assistant_kiolna_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_clerk'); # :highkeep_a_clerk_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_crazed_goblin'); # :highkeep_a_crazed_goblin_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_dealer'); # :highkeep_a_dealer_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_goblin'); # :highkeep_a_goblin_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_goblin_thief'); # :highkeep_a_goblin_thief_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_guard'); # :highkeep_a_guard_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_kitchen_drudge'); # :highkeep_a_kitchen_drudge_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_lady_in_waiting'); # :highkeep_a_lady_in_waiting_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_maid'); # :highkeep_a_maid_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_noble'); # :highkeep_a_noble_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_pickclaw_cabalist'); # :highkeep_a_pickclaw_cabalist_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_pickclaw_guard'); # :highkeep_a_pickclaw_guard_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_pickclaw_lookout'); # :highkeep_a_pickclaw_lookout_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_pickclaw_raider'); # :highkeep_a_pickclaw_raider_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_pickclaw_seer'); # :highkeep_a_pickclaw_seer_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_pickclaw_spiritist'); # :highkeep_a_pickclaw_spiritist_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_pickclaw_visionary'); # :highkeep_a_pickclaw_visionary_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_pickclaw_warrior'); # :highkeep_a_pickclaw_warrior_lt:
INSERT INTO loottable(name) VALUES('highkeep_a_prisoner'); # :highkeep_a_prisoner_lt:
INSERT INTO loottable(name) VALUES('highkeep_baker_jena'); # :highkeep_baker_jena_lt:
INSERT INTO loottable(name) VALUES('highkeep_bank_clerk_jaylin'); # :highkeep_bank_clerk_jaylin_lt:
INSERT INTO loottable(name) VALUES('highkeep_captain_bosec'); # :highkeep_captain_bosec_lt:
INSERT INTO loottable(name) VALUES('highkeep_captain_boshinko'); # :highkeep_captain_boshinko_lt:
INSERT INTO loottable(name) VALUES('highkeep_carson_mccabe'); # :highkeep_carson_mccabe_lt:
INSERT INTO loottable(name) VALUES('highkeep_dealer_maeline'); # :highkeep_dealer_maeline_lt:
INSERT INTO loottable(name) VALUES('highkeep_dealer_shonta'); # :highkeep_dealer_shonta_lt:
INSERT INTO loottable(name) VALUES('highkeep_dulcyna_blackhand'); # :highkeep_dulcyna_blackhand_lt:
INSERT INTO loottable(name) VALUES('highkeep_dyrna_nlith'); # :highkeep_dyrna_nlith_lt:
INSERT INTO loottable(name) VALUES('highkeep_fenn_kaedrick'); # :highkeep_fenn_kaedrick_lt:
INSERT INTO loottable(name) VALUES('highkeep_flayer_hopkins'); # :highkeep_flayer_hopkins_lt:
INSERT INTO loottable(name) VALUES('highkeep_grahm_embersmith'); # :highkeep_grahm_embersmith_lt:
INSERT INTO loottable(name) VALUES('highkeep_grex'); # :highkeep_grex_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_anleal'); # :highkeep_guard_anleal_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_antilles'); # :highkeep_guard_antilles_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_bach'); # :highkeep_guard_bach_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_bicker'); # :highkeep_guard_bicker_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_blayle'); # :highkeep_guard_blayle_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_bolton'); # :highkeep_guard_bolton_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_bonner'); # :highkeep_guard_bonner_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_chin'); # :highkeep_guard_chin_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_chopin'); # :highkeep_guard_chopin_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_clyzen'); # :highkeep_guard_clyzen_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_diff'); # :highkeep_guard_diff_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_dister'); # :highkeep_guard_dister_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_drugan'); # :highkeep_guard_drugan_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_duras'); # :highkeep_guard_duras_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_dwight'); # :highkeep_guard_dwight_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_folton'); # :highkeep_guard_folton_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_gechop'); # :highkeep_guard_gechop_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_golgon'); # :highkeep_guard_golgon_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_handy'); # :highkeep_guard_handy_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_heltch'); # :highkeep_guard_heltch_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_jaxon'); # :highkeep_guard_jaxon_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_kheb'); # :highkeep_guard_kheb_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_kovan'); # :highkeep_guard_kovan_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_lancel'); # :highkeep_guard_lancel_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_lorton'); # :highkeep_guard_lorton_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_mytin'); # :highkeep_guard_mytin_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_onto'); # :highkeep_guard_onto_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_qanyl'); # :highkeep_guard_qanyl_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_queztin'); # :highkeep_guard_queztin_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_rance'); # :highkeep_guard_rance_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_ruan'); # :highkeep_guard_ruan_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_sintra'); # :highkeep_guard_sintra_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_sydl'); # :highkeep_guard_sydl_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_wextr'); # :highkeep_guard_wextr_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_xantar'); # :highkeep_guard_xantar_lt:
INSERT INTO loottable(name) VALUES('highkeep_guard_yeltin'); # :highkeep_guard_yeltin_lt:
INSERT INTO loottable(name) VALUES('highkeep_isabella_cellus'); # :highkeep_isabella_cellus_lt:
INSERT INTO loottable(name) VALUES('highkeep_jail_clerk_maryl'); # :highkeep_jail_clerk_maryl_lt:
INSERT INTO loottable(name) VALUES('highkeep_justin_ryhmes'); # :highkeep_justin_ryhmes_lt:
INSERT INTO loottable(name) VALUES('highkeep_krystalle_corsair'); # :highkeep_krystalle_corsair_lt:
INSERT INTO loottable(name) VALUES('highkeep_lady_mccabe'); # :highkeep_lady_mccabe_lt:
INSERT INTO loottable(name) VALUES('highkeep_lartin'); # :highkeep_lartin_lt:
INSERT INTO loottable(name) VALUES('highkeep_lislia_goldtune'); # :highkeep_lislia_goldtune_lt:
INSERT INTO loottable(name) VALUES('highkeep_lozani'); # :highkeep_lozani_lt:
INSERT INTO loottable(name) VALUES('highkeep_lucky_the_beggar'); # :highkeep_lucky_the_beggar_lt:
INSERT INTO loottable(name) VALUES('highkeep_merchant_dominik'); # :highkeep_merchant_dominik_lt:
INSERT INTO loottable(name) VALUES('highkeep_merchant_edina'); # :highkeep_merchant_edina_lt:
INSERT INTO loottable(name) VALUES('highkeep_miner_harton'); # :highkeep_miner_harton_lt:
INSERT INTO loottable(name) VALUES('highkeep_mistress_anna'); # :highkeep_mistress_anna_lt:
INSERT INTO loottable(name) VALUES('highkeep_osargen'); # :highkeep_osargen_lt:
INSERT INTO loottable(name) VALUES('highkeep_princess_lenia'); # :highkeep_princess_lenia_lt:
INSERT INTO loottable(name) VALUES('highkeep_purchin_oddsbot'); # :highkeep_purchin_oddsbot_lt:
INSERT INTO loottable(name) VALUES('highkeep_ran_flamespinner'); # :highkeep_ran_flamespinner_lt:
INSERT INTO loottable(name) VALUES('highkeep_rodrick_marslett'); # :highkeep_rodrick_marslett_lt:
INSERT INTO loottable(name) VALUES('highkeep_starr_dreamspinner'); # :highkeep_starr_dreamspinner_lt:
INSERT INTO loottable(name) VALUES('highkeep_storm_dragonchaser'); # :highkeep_storm_dragonchaser_lt:
INSERT INTO loottable(name) VALUES('highkeep_tarn_visilin'); # :highkeep_tarn_visilin_lt:
INSERT INTO loottable(name) VALUES('highkeep_tearon_bleanix'); # :highkeep_tearon_bleanix_lt:
INSERT INTO loottable(name) VALUES('highkeep_treasurer_lynn'); # :highkeep_treasurer_lynn_lt:
INSERT INTO loottable(name) VALUES('highkeep_tsaria_jnarus'); # :highkeep_tsaria_jnarus_lt:
INSERT INTO loottable(name) VALUES('highkeep_tyrana_slil'); # :highkeep_tyrana_slil_lt:
INSERT INTO loottable(name) VALUES('highkeep_xentil_herkanon'); # :highkeep_xentil_herkanon_lt:
