INSERT INTO loottable(name) VALUES('hole_an_ancient_construct'); # :hole_an_ancient_construct_lt:
INSERT INTO loottable(name) VALUES('hole_an_ancient_gargoyle'); # :hole_an_ancient_gargoyle_lt:
INSERT INTO loottable(name) VALUES('hole_an_animated_construct'); # :hole_an_animated_construct_lt:
INSERT INTO loottable(name) VALUES('hole_an_animated_construct_'); # :hole_an_animated_construct__lt:
INSERT INTO loottable(name) VALUES('hole_an_old_construct'); # :hole_an_old_construct_lt:
INSERT INTO loottable(name) VALUES('hole_an_old_gargoyle'); # :hole_an_old_gargoyle_lt:
INSERT INTO loottable(name) VALUES('hole_a_dormant_watcher'); # :hole_a_dormant_watcher_lt:
INSERT INTO loottable(name) VALUES('hole_a_ratman_guard'); # :hole_a_ratman_guard_lt:
INSERT INTO loottable(name) VALUES('hole_a_ratman_inhabitant'); # :hole_a_ratman_inhabitant_lt:
INSERT INTO loottable(name) VALUES('hole_a_temple_researcher'); # :hole_a_temple_researcher_lt:
INSERT INTO loottable(name) VALUES('hole_echo_of_nortlav'); # :hole_echo_of_nortlav_lt:
INSERT INTO loottable(name) VALUES('hole_ghost_of_glohnor'); # :hole_ghost_of_glohnor_lt:
INSERT INTO loottable(name) VALUES('hole_guardian_of_the_seal'); # :hole_guardian_of_the_seal_lt:
INSERT INTO loottable(name) VALUES('hole_high_scale_kirn'); # :hole_high_scale_kirn_lt:
INSERT INTO loottable(name) VALUES('hole_high_scale_kirn_'); # :hole_high_scale_kirn__lt:
INSERT INTO loottable(name) VALUES('hole_ikurenm_the_sly'); # :hole_ikurenm_the_sly_lt:
INSERT INTO loottable(name) VALUES('hole_pellillo_cogswin'); # :hole_pellillo_cogswin_lt:
INSERT INTO loottable(name) VALUES('hole_tzitzi_the_crazed'); # :hole_tzitzi_the_crazed_lt:
INSERT INTO loottable(name) VALUES('hole_an_elemental_capturer'); # :hole_an_elemental_capturer_lt:
INSERT INTO loottable(name) VALUES('hole_an_elemental_channeler'); # :hole_an_elemental_channeler_lt:
INSERT INTO loottable(name) VALUES('hole_an_elemental_crusader'); # :hole_an_elemental_crusader_lt:
INSERT INTO loottable(name) VALUES('hole_an_elemental_deceiver'); # :hole_an_elemental_deceiver_lt:
INSERT INTO loottable(name) VALUES('hole_an_elemental_harvester'); # :hole_an_elemental_harvester_lt:
INSERT INTO loottable(name) VALUES('hole_an_elemental_monstrosity'); # :hole_an_elemental_monstrosity_lt:
INSERT INTO loottable(name) VALUES('hole_an_elemental_visier'); # :hole_an_elemental_visier_lt:
INSERT INTO loottable(name) VALUES('hole_an_elemental_warrior'); # :hole_an_elemental_warrior_lt:
INSERT INTO loottable(name) VALUES('hole_an_elemental_wizard'); # :hole_an_elemental_wizard_lt:
INSERT INTO loottable(name) VALUES('hole_a_broken_construct'); # :hole_a_broken_construct_lt:
INSERT INTO loottable(name) VALUES('hole_a_broken_gargoyle'); # :hole_a_broken_gargoyle_lt:
INSERT INTO loottable(name) VALUES('hole_a_chest'); # :hole_a_chest_lt:
INSERT INTO loottable(name) VALUES('hole_a_citybound_spirit'); # :hole_a_citybound_spirit_lt:
INSERT INTO loottable(name) VALUES('hole_a_crumbling_gargoyle'); # :hole_a_crumbling_gargoyle_lt:
INSERT INTO loottable(name) VALUES('hole_a_destroyed_construct'); # :hole_a_destroyed_construct_lt:
INSERT INTO loottable(name) VALUES('hole_a_destroyed_gargoyle'); # :hole_a_destroyed_gargoyle_lt:
INSERT INTO loottable(name) VALUES('hole_a_fallen_adventurer'); # :hole_a_fallen_adventurer_lt:
INSERT INTO loottable(name) VALUES('hole_a_fallen_erudite'); # :hole_a_fallen_erudite_lt:
INSERT INTO loottable(name) VALUES('hole_a_fallen_heretic'); # :hole_a_fallen_heretic_lt:
INSERT INTO loottable(name) VALUES('hole_a_flighty_fiend'); # :hole_a_flighty_fiend_lt:
INSERT INTO loottable(name) VALUES('hole_a_massive_construct'); # :hole_a_massive_construct_lt:
INSERT INTO loottable(name) VALUES('hole_a_ratman_inhabitant'); # :hole_a_ratman_inhabitant_lt:
INSERT INTO loottable(name) VALUES('hole_a_ratman_warrior'); # :hole_a_ratman_warrior_lt:
INSERT INTO loottable(name) VALUES('hole_a_rock_golem'); # :hole_a_rock_golem_lt:
INSERT INTO loottable(name) VALUES('hole_a_ruined_construct'); # :hole_a_ruined_construct_lt:
INSERT INTO loottable(name) VALUES('hole_a_ruined_gargoyle'); # :hole_a_ruined_gargoyle_lt:
INSERT INTO loottable(name) VALUES('hole_a_spirit_of_the_old_city'); # :hole_a_spirit_of_the_old_city_lt:
INSERT INTO loottable(name) VALUES('hole_a_spirit_of_the_ruins'); # :hole_a_spirit_of_the_ruins_lt:
INSERT INTO loottable(name) VALUES('hole_a_stone_ward'); # :hole_a_stone_ward_lt:
INSERT INTO loottable(name) VALUES('hole_a_templebound_spirit'); # :hole_a_templebound_spirit_lt:
INSERT INTO loottable(name) VALUES('hole_a_wanderer'); # :hole_a_wanderer_lt:
INSERT INTO loottable(name) VALUES('hole_bejeweled_elemental'); # :hole_bejeweled_elemental_lt:
INSERT INTO loottable(name) VALUES('hole_caradon'); # :hole_caradon_lt:
INSERT INTO loottable(name) VALUES('hole_commander_yarik'); # :hole_commander_yarik_lt:
INSERT INTO loottable(name) VALUES('hole_dartain_the_lost'); # :hole_dartain_the_lost_lt:
INSERT INTO loottable(name) VALUES('hole_gibartik'); # :hole_gibartik_lt:
INSERT INTO loottable(name) VALUES('hole_initiate_sirlis'); # :hole_initiate_sirlis_lt:
INSERT INTO loottable(name) VALUES('hole_irslak_the_wretched'); # :hole_irslak_the_wretched_lt:
INSERT INTO loottable(name) VALUES('hole_jaeil_the_insane'); # :hole_jaeil_the_insane_lt:
INSERT INTO loottable(name) VALUES('hole_jaeil_the_wretched'); # :hole_jaeil_the_wretched_lt:
INSERT INTO loottable(name) VALUES('hole_julei_direaxe'); # :hole_julei_direaxe_lt:
INSERT INTO loottable(name) VALUES('hole_keeper_of_the_tombs'); # :hole_keeper_of_the_tombs_lt:
INSERT INTO loottable(name) VALUES('hole_kejar_the_mighty'); # :hole_kejar_the_mighty_lt:
INSERT INTO loottable(name) VALUES('hole_kyrenna'); # :hole_kyrenna_lt:
INSERT INTO loottable(name) VALUES('hole_lost_spirit'); # :hole_lost_spirit_lt:
INSERT INTO loottable(name) VALUES('hole_master_yael'); # :hole_master_yael_lt:
INSERT INTO loottable(name) VALUES('hole_muck_covered_elemental'); # :hole_muck_covered_elemental_lt:
INSERT INTO loottable(name) VALUES('hole_mummy_of_glohnor'); # :hole_mummy_of_glohnor_lt:
INSERT INTO loottable(name) VALUES('hole_niltoth_the_unholy'); # :hole_niltoth_the_unholy_lt:
INSERT INTO loottable(name) VALUES('hole_nortlav_the_scalekeeper'); # :hole_nortlav_the_scalekeeper_lt:
INSERT INTO loottable(name) VALUES('hole_polzin_mrid'); # :hole_polzin_mrid_lt:
INSERT INTO loottable(name) VALUES('hole_protector_of_the_ruins'); # :hole_protector_of_the_ruins_lt:
INSERT INTO loottable(name) VALUES('hole_retseth_tretse'); # :hole_retseth_tretse_lt:
INSERT INTO loottable(name) VALUES('hole_rocksoul'); # :hole_rocksoul_lt:
INSERT INTO loottable(name) VALUES('hole_schnozz_the_flighty'); # :hole_schnozz_the_flighty_lt:
INSERT INTO loottable(name) VALUES('hole_slizik_the_mighty'); # :hole_slizik_the_mighty_lt:
INSERT INTO loottable(name) VALUES('hole_stonegrinder_minion'); # :hole_stonegrinder_minion_lt:
INSERT INTO loottable(name) VALUES('hole_stonesoul_the_unmoving'); # :hole_stonesoul_the_unmoving_lt:
INSERT INTO loottable(name) VALUES('hole_stone_collector'); # :hole_stone_collector_lt:
INSERT INTO loottable(name) VALUES('hole_the_banners'); # :hole_the_banners_lt:
INSERT INTO loottable(name) VALUES('hole_the_ghost_of_kindle'); # :hole_the_ghost_of_kindle_lt:
INSERT INTO loottable(name) VALUES('hole_the_home'); # :hole_the_home_lt:
INSERT INTO loottable(name) VALUES('hole_the_summoned'); # :hole_the_summoned_lt:
INSERT INTO loottable(name) VALUES('hole_ulrik_the_devout'); # :hole_ulrik_the_devout_lt:
INSERT INTO loottable(name) VALUES('hole_urwenae_the_cold'); # :hole_urwenae_the_cold_lt:
INSERT INTO loottable(name) VALUES('hole__'); # :hole___lt:
