INSERT INTO loottable(name) VALUES('jaggedpine_annous_pineshadow'); # :jaggedpine_annous_pineshadow_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_forest_dragon'); # :jaggedpine_a_forest_dragon_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_banker_mardalson'); # :jaggedpine_banker_mardalson_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_barducks_darkpaw'); # :jaggedpine_barducks_darkpaw_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_bossgnollspawn'); # :jaggedpine_bossgnollspawn_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_call_of_the_wild'); # :jaggedpine_call_of_the_wild_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_cathleen_goodroot'); # :jaggedpine_cathleen_goodroot_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_cheyloh_greenwood'); # :jaggedpine_cheyloh_greenwood_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_cyribelle_comes'); # :jaggedpine_cyribelle_comes_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_cyribelle_the_wild'); # :jaggedpine_cyribelle_the_wild_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_derick_goodroot'); # :jaggedpine_derick_goodroot_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_diedra_twothorns'); # :jaggedpine_diedra_twothorns_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_dismal_darkpaw_mystic'); # :jaggedpine_dismal_darkpaw_mystic_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_donna_twothorns'); # :jaggedpine_donna_twothorns_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_elishia_blackguard'); # :jaggedpine_elishia_blackguard_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_farkus_grime'); # :jaggedpine_farkus_grime_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_firwyn'); # :jaggedpine_firwyn_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_fiveinc'); # :jaggedpine_fiveinc_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_fourinc'); # :jaggedpine_fourinc_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_goldentalon'); # :jaggedpine_goldentalon_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_guard_bossamir'); # :jaggedpine_guard_bossamir_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_guard_finewine'); # :jaggedpine_guard_finewine_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_jeremy_leafrunner'); # :jaggedpine_jeremy_leafrunner_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_kaithys_galestrider'); # :jaggedpine_kaithys_galestrider_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_lady_deira'); # :jaggedpine_lady_deira_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_lameriae_the_alluring'); # :jaggedpine_lameriae_the_alluring_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_matriarch_handmaid'); # :jaggedpine_matriarch_handmaid_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_morgan_wetstone'); # :jaggedpine_morgan_wetstone_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_myraephe_the_pure'); # :jaggedpine_myraephe_the_pure_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_nerdala_darkcloud'); # :jaggedpine_nerdala_darkcloud_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_nolan_greenwood'); # :jaggedpine_nolan_greenwood_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_oneinc'); # :jaggedpine_oneinc_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_pergan_darkcloud'); # :jaggedpine_pergan_darkcloud_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_persgnollspawn'); # :jaggedpine_persgnollspawn_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_queen_nhyalia'); # :jaggedpine_queen_nhyalia_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_ralleford_twothorns'); # :jaggedpine_ralleford_twothorns_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_randel_stormwind'); # :jaggedpine_randel_stormwind_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_rashara_wrualla'); # :jaggedpine_rashara_wrualla_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_reynold_blackguard'); # :jaggedpine_reynold_blackguard_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_selia_wetstone'); # :jaggedpine_selia_wetstone_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_sergeant_caelin'); # :jaggedpine_sergeant_caelin_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_setup'); # :jaggedpine_setup_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_shayna_thunderhand'); # :jaggedpine_shayna_thunderhand_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_spawnman'); # :jaggedpine_spawnman_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_tallien_brightflash'); # :jaggedpine_tallien_brightflash_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_threeinc'); # :jaggedpine_threeinc_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_timer'); # :jaggedpine_timer_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_twoinc'); # :jaggedpine_twoinc_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_vaurien_sticklebush'); # :jaggedpine_vaurien_sticklebush_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_yranik_blackguard'); # :jaggedpine_yranik_blackguard_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_zed_sticklebush'); # :jaggedpine_zed_sticklebush_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_zeroinc'); # :jaggedpine_zeroinc_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_anchorite_of_brell_serilis'); # :jaggedpine_anchorite_of_brell_serilis_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_black_panther'); # :jaggedpine_a_black_panther_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_black_pinewolf'); # :jaggedpine_a_black_pinewolf_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_cave_basilisk'); # :jaggedpine_a_cave_basilisk_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_cave_basilisk_genitor'); # :jaggedpine_a_cave_basilisk_genitor_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_darkpaw_corruptor'); # :jaggedpine_a_darkpaw_corruptor_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_darkpaw_curate'); # :jaggedpine_a_darkpaw_curate_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_darkpaw_defiler'); # :jaggedpine_a_darkpaw_defiler_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_darkpaw_gnoll'); # :jaggedpine_a_darkpaw_gnoll_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_darkpaw_healer'); # :jaggedpine_a_darkpaw_healer_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_darkpaw_mystic'); # :jaggedpine_a_darkpaw_mystic_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_darkpaw_oracle'); # :jaggedpine_a_darkpaw_oracle_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_darkpaw_warrior'); # :jaggedpine_a_darkpaw_warrior_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_dire_kodiak'); # :jaggedpine_a_dire_kodiak_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_docile_bear'); # :jaggedpine_a_docile_bear_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_dryad'); # :jaggedpine_a_dryad_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_giant_anaconda'); # :jaggedpine_a_giant_anaconda_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_gnoll'); # :jaggedpine_a_gnoll_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_gnoll_assassin'); # :jaggedpine_a_gnoll_assassin_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_greenwood_bear'); # :jaggedpine_a_greenwood_bear_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_greenwood_grizzly'); # :jaggedpine_a_greenwood_grizzly_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_grey_pinewolf'); # :jaggedpine_a_grey_pinewolf_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_poacher'); # :jaggedpine_a_poacher_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_potameid_bewilder'); # :jaggedpine_a_potameid_bewilder_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_potameid_guardian'); # :jaggedpine_a_potameid_guardian_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_potameid_maiden'); # :jaggedpine_a_potameid_maiden_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_potameid_matriarch'); # :jaggedpine_a_potameid_matriarch_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_potameid_protector'); # :jaggedpine_a_potameid_protector_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_potameid_temptress'); # :jaggedpine_a_potameid_temptress_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_potameid_wildling'); # :jaggedpine_a_potameid_wildling_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_river_turtle'); # :jaggedpine_a_river_turtle_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_timber_griffawn'); # :jaggedpine_a_timber_griffawn_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_timber_griffon'); # :jaggedpine_a_timber_griffon_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_treant'); # :jaggedpine_a_treant_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_water_protector'); # :jaggedpine_a_water_protector_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_water_spirit'); # :jaggedpine_a_water_spirit_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_a_willowisp'); # :jaggedpine_a_willowisp_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_banker_rarrgar'); # :jaggedpine_banker_rarrgar_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_chef_brargus'); # :jaggedpine_chef_brargus_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_deathnotify'); # :jaggedpine_deathnotify_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_dunarl'); # :jaggedpine_dunarl_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_ervonis_leaflow'); # :jaggedpine_ervonis_leaflow_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_karka'); # :jaggedpine_karka_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_lady_fianya'); # :jaggedpine_lady_fianya_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_oracle_jaarl'); # :jaggedpine_oracle_jaarl_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_quartermaster_grarucks'); # :jaggedpine_quartermaster_grarucks_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_raidmisc'); # :jaggedpine_raidmisc_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_red_dogwood_treant'); # :jaggedpine_red_dogwood_treant_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_snarla_the_fang'); # :jaggedpine_snarla_the_fang_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_the_flame'); # :jaggedpine_the_flame_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_the_wind'); # :jaggedpine_the_wind_lt:
INSERT INTO loottable(name) VALUES('jaggedpine_waldo_pinemyer'); # :jaggedpine_waldo_pinemyer_lt:
