UPDATE npc_types SET loottable_id = :kaladimb_aanina_rockfinder_lt: WHERE id in (67043); # Aanina_Rockfinder 41
UPDATE npc_types SET loottable_id = :kaladimb_atheki_norkhitter_lt: WHERE id in (67076, 67040); # Atheki_Norkhitter 9
UPDATE npc_types SET loottable_id = :kaladimb_axa_stormshield_lt: WHERE id in (67063); # Axa_Stormshield 39
UPDATE npc_types SET loottable_id = :kaladimb_a_rodent_lt: WHERE id in (67001); # a_rodent 1
UPDATE npc_types SET loottable_id = :kaladimb_baleki_nightseer_lt: WHERE id in (67086); # Baleki_Nightseer 38
UPDATE npc_types SET loottable_id = :kaladimb_banaf_norkhitter_lt: WHERE id in (67042); # Banaf_Norkhitter 39
UPDATE npc_types SET loottable_id = :kaladimb_bloarn_norkhitter_lt: WHERE id in (67039); # Bloarn_Norkhitter 50
UPDATE npc_types SET loottable_id = :kaladimb_bndainy_everhot_lt: WHERE id in (67045); # Bndainy_Everhot 39
UPDATE npc_types SET loottable_id = :kaladimb_brenthalion_aleslammer_lt: WHERE id in (67004); # Brenthalion_Aleslammer 61
UPDATE npc_types SET loottable_id = :kaladimb_bumle_reminjar_lt: WHERE id in (67026); # Bumle_Reminjar 61
UPDATE npc_types SET loottable_id = :kaladimb_busey_nehart_lt: WHERE id in (67020); # Busey_Nehart 34
UPDATE npc_types SET loottable_id = :kaladimb_cleaner_vii_lt: WHERE id in (67088); # Cleaner_VII 4
UPDATE npc_types SET loottable_id = :kaladimb_crovsar_dirkbringer_lt: WHERE id in (67003); # Crovsar_Dirkbringer 61
UPDATE npc_types SET loottable_id = :kaladimb_darthur_nightseer_lt: WHERE id in (67054); # Darthur_Nightseer 42
UPDATE npc_types SET loottable_id = :kaladimb_datur_nightseer_lt: WHERE id in (67029); # Datur_Nightseer 61
UPDATE npc_types SET loottable_id = :kaladimb_diggins_lt: WHERE id in (67017); # Diggins 61
UPDATE npc_types SET loottable_id = :kaladimb_dindaek_everhot_lt: WHERE id in (67081); # Dindaek_Everhot 38
UPDATE npc_types SET loottable_id = :kaladimb_donnel_ratsbome_lt: WHERE id in (67085, 67052); # Donnel_Ratsbome 40
UPDATE npc_types SET loottable_id = :kaladimb_doramafi_ratsbone_lt: WHERE id in (67084); # Doramafi_Ratsbone 38
UPDATE npc_types SET loottable_id = :kaladimb_dorlita_splitshield_lt: WHERE id in (67066); # Dorlita_Splitshield 41
UPDATE npc_types SET loottable_id = :kaladimb_dravel_axethrasher_lt: WHERE id in (67087); # Dravel_Axethrasher 65
UPDATE npc_types SET loottable_id = :kaladimb_dunony_chestire_lt: WHERE id in (67027); # Dunony_Chestire 61
UPDATE npc_types SET loottable_id = :kaladimb_duppa_pickstone_lt: WHERE id in (67012); # Duppa_Pickstone 39
UPDATE npc_types SET loottable_id = :kaladimb_exterminator_vin_lt: WHERE id in (67006); # Exterminator_Vin 45
UPDATE npc_types SET loottable_id = :kaladimb_fettar_steelwield_lt: WHERE id in (67064); # Fettar_Steelwield 42
UPDATE npc_types SET loottable_id = :kaladimb_founy_jestands_lt: WHERE id in (67000); # Founy_Jestands 45
UPDATE npc_types SET loottable_id = :kaladimb_giant_rat_lt: WHERE id in (67093, 67094, 67002, 67061); # Giant_Rat 2
UPDATE npc_types SET loottable_id = :kaladimb_goriba_thurgorson_lt: WHERE id in (67059); # Goriba_Thurgorson 61
UPDATE npc_types SET loottable_id = :kaladimb_gralpa_axeheft_lt: WHERE id in (67068); # Gralpa_Axeheft 38
UPDATE npc_types SET loottable_id = :kaladimb_guard_ainamar_lt: WHERE id in (67034); # Guard_Ainamar 39
UPDATE npc_types SET loottable_id = :kaladimb_guard_dalammer_lt: WHERE id in (67072, 67035); # Guard_Dalammer 38
UPDATE npc_types SET loottable_id = :kaladimb_guard_dalthur_lt: WHERE id in (67038); # Guard_Dalthur 38
UPDATE npc_types SET loottable_id = :kaladimb_guard_doradek_lt: WHERE id in (67074, 67037); # Guard_Doradek 40
UPDATE npc_types SET loottable_id = :kaladimb_guard_kaldolar_lt: WHERE id in (67036); # Guard_Kaldolar 41
UPDATE npc_types SET loottable_id = :kaladimb_gunlok_jure_lt: WHERE id in (67028); # Gunlok_Jure 61
UPDATE npc_types SET loottable_id = :kaladimb_haldorak_foamymugs_lt: WHERE id in (67005); # Haldorak_Foamymugs 61
UPDATE npc_types SET loottable_id = :kaladimb_halthar_mowestone_lt: WHERE id in (67091); # Halthar_Mowestone 65
UPDATE npc_types SET loottable_id = :kaladimb_harnoff_splitrock_lt: WHERE id in (67057); # Harnoff_Splitrock 1
UPDATE npc_types SET loottable_id = :kaladimb_infected_rat_lt: WHERE id in (67092, 67062); # Infected_Rat 2
UPDATE npc_types SET loottable_id = :kaladimb_jark_lt: WHERE id in (67056); # Jark 50
UPDATE npc_types SET loottable_id = :kaladimb_jeet_lt: WHERE id in (67018); # Jeet 61
UPDATE npc_types SET loottable_id = :kaladimb_kadek_norkhitter_lt: WHERE id in (67083); # Kadek_Norkhitter 39
UPDATE npc_types SET loottable_id = :kaladimb_kafia_ratsbone_lt: WHERE id in (67053); # Kafia_Ratsbone 42
UPDATE npc_types SET loottable_id = :kaladimb_kalamin_norkhitter_lt: WHERE id in (67077, 67041); # Kalamin_Norkhitter 9
UPDATE npc_types SET loottable_id = :kaladimb_kinlo_strongarm_lt: WHERE id in (67030); # Kinlo_Strongarm 50
UPDATE npc_types SET loottable_id = :kaladimb_krako_stonesplitter_lt: WHERE id in (67069); # Krako_Stonesplitter 41
UPDATE npc_types SET loottable_id = :kaladimb_marsha_stonepenner_lt: WHERE id in (67058); # Marsha_Stonepenner 25
UPDATE npc_types SET loottable_id = :kaladimb_mater_lt: WHERE id in (67019); # Mater 61
UPDATE npc_types SET loottable_id = :kaladimb_murlond_everhot_lt: WHERE id in (67079); # Murlond_Everhot 41
UPDATE npc_types SET loottable_id = :kaladimb_myre_lt: WHERE id in (67016); # Myre 30
UPDATE npc_types SET loottable_id = :kaladimb_nella_stonebraids_lt: WHERE id in (67090); # Nella_Stonebraids 55
UPDATE npc_types SET loottable_id = :kaladimb_nultal_malfoot_lt: WHERE id in (67023); # Nultal_Malfoot 61
UPDATE npc_types SET loottable_id = :kaladimb_phell_gronback_lt: WHERE id in (67021); # Phell_Gronback 61
UPDATE npc_types SET loottable_id = :kaladimb_poriss_splitrock_lt: WHERE id in (67065); # Poriss_Splitrock 40
UPDATE npc_types SET loottable_id = :kaladimb_priestess_ghalea_lt: WHERE id in (67024); # Priestess_Ghalea 61
UPDATE npc_types SET loottable_id = :kaladimb_ragunk_everhot_lt: WHERE id in (67032); # Ragunk_Everhot 41
UPDATE npc_types SET loottable_id = :kaladimb_resron_silvern_lt: WHERE id in (67022); # Resron_Silvern 61
UPDATE npc_types SET loottable_id = :kaladimb_serenk_greybloom_lt: WHERE id in (67044); # Serenk_Greybloom 39
UPDATE npc_types SET loottable_id = :kaladimb_storn_trueblade_lt: WHERE id in (67008); # Storn_Trueblade 39
UPDATE npc_types SET loottable_id = :kaladimb_tabber_varhund_lt: WHERE id in (67060); # Tabber_Varhund 40
UPDATE npc_types SET loottable_id = :kaladimb_tempia_lauley_lt: WHERE id in (67025); # Tempia_Lauley 38
UPDATE npc_types SET loottable_id = :kaladimb_tissin_greybloom_lt: WHERE id in (67031, 67070); # Tissin_Greybloom 40
UPDATE npc_types SET loottable_id = :kaladimb_tortuk_everhot_lt: WHERE id in (67080, 67047); # Tortuk_Everhot 38
UPDATE npc_types SET loottable_id = :kaladimb_trantor_everhot_lt: WHERE id in (67033); # Trantor_Everhot 35
UPDATE npc_types SET loottable_id = :kaladimb_usbak_the_old_lt: WHERE id in (67089); # Usbak_the_Old 55
UPDATE npc_types SET loottable_id = :kaladimb_zeffan_holdsman_lt: WHERE id in (67067); # Zeffan_Holdsman 42
