UPDATE npc_types SET loottable_id = :kerraridge_allix_lt: WHERE id in (74073); # Allix 13
UPDATE npc_types SET loottable_id = :kerraridge_alrik_pasdar_lt: WHERE id in (74113); # Alrik_Pasdar 21
UPDATE npc_types SET loottable_id = :kerraridge_a_banished_kerran_lt: WHERE id in (74040); # a_banished_kerran 20
UPDATE npc_types SET loottable_id = :kerraridge_a_catfisher_lt: WHERE id in (74081, 74112); # a_catfisher 2
UPDATE npc_types SET loottable_id = :kerraridge_a_gorilla_guard_lt: WHERE id in (74042, 74090); # a_gorilla_guard 18
UPDATE npc_types SET loottable_id = :kerraridge_a_gorilla_protector_lt: WHERE id in (74051, 74091); # a_gorilla_protector 17
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_ademzada_lt: WHERE id in (74035, 74109); # a_kerran_ademzada 17
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_ademzada_shaman_lt: WHERE id in (74034, 74108); # a_Kerran_ademzada_shaman 17
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_ademzadaamir_lt: WHERE id in (74046, 74096, 74098); # a_kerran_ademzada`amir 20
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_ahmad_shaman_lt: WHERE id in (74044, 74099); # a_kerran_ahmad_shaman 19
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_amira_guardian_lt: WHERE id in (74053, 74054, 74094); # a_kerran_amira_guardian 19
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_amira_priestess_lt: WHERE id in (74052, 74092); # a_kerran_amira_priestess 23
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_amira_protector_lt: WHERE id in (74093); # a_kerran_amira_protector 20
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_awrat_lt: WHERE id in (74000, 74008, 74009); # a_kerran_awrat 12
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_ghazi_lt: WHERE id in (74017, 74078, 74100, 74104); # a_kerran_ghazi 17
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_ghazi_shaman_lt: WHERE id in (74011, 74012, 74095); # a_kerran_ghazi_shaman 18
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_ghaziamir_lt: WHERE id in (74045, 74047, 74097); # a_kerran_ghazi`amir 20
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_ghulam_lt: WHERE id in (74002, 74062, 74064, 74084); # a_kerran_ghulam 17
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_gorilla_lt: WHERE id in (74018, 74019, 74043); # a_kerran_gorilla 17
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_gorilla_shaman_lt: WHERE id in (74020, 74110); # a_kerran_gorilla_shaman 18
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_ispusar_lt: WHERE id in (74001, 74063, 74111); # a_kerran_ispusar 15
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_mamluk_lt: WHERE id in (74006, 74007, 74010); # a_kerran_mamluk 11
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_mujahed_lt: WHERE id in (74015, 74016, 74026); # a_kerran_mujahed 20
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_pasdar_lt: WHERE id in (74049, 74059, 74087, 74102, 74103); # a_kerran_pasdar 17
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_pazdar_lt: WHERE id in (74021, 74048, 74050, 74101); # a_kerran_pazdar 19
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_pazdar_shaman_lt: WHERE id in (74013, 74037, 74038, 74105, 74106); # a_kerran_pazdar_shaman 18
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_pazhal_lt: WHERE id in (74039, 74061); # a_kerran_pazhal 18
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_puzhal_lt: WHERE id in (74075); # a_Kerran_puzhal 16
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_sharr_apprentice_lt: WHERE id in (74117); # a_kerran_sha`rr_apprentice 22
UPDATE npc_types SET loottable_id = :kerraridge_a_kerran_amir_lt: WHERE id in (74025, 74027); # a_kerran_`amir 20
UPDATE npc_types SET loottable_id = :kerraridge_a_kerra_lion_lt: WHERE id in (74031, 74085, 74086); # a_kerra_lion 20
UPDATE npc_types SET loottable_id = :kerraridge_a_kerra_puma_lt: WHERE id in (74065, 74067, 74071); # a_kerra_puma 15
UPDATE npc_types SET loottable_id = :kerraridge_a_kobold_prisoner_lt: WHERE id in (74077, 74079, 74080); # a_kobold_prisoner 5
UPDATE npc_types SET loottable_id = :kerraridge_a_patrolling_tiger_lt: WHERE id in (74036); # a_patrolling_tiger 17
UPDATE npc_types SET loottable_id = :kerraridge_a_tiger_lt: WHERE id in (74060); # a_tiger 17
UPDATE npc_types SET loottable_id = :kerraridge_a_venomous_spikefish_lt: WHERE id in (74083); # a_venomous_spikefish 13
UPDATE npc_types SET loottable_id = :kerraridge_a_wild_tiger_lt: WHERE id in (74056, 74088); # a_wild_tiger 15
UPDATE npc_types SET loottable_id = :kerraridge_dozing_ghulam_lt: WHERE id in (74082); # dozing_ghulam 17
UPDATE npc_types SET loottable_id = :kerraridge_drunken_ghulam_lt: WHERE id in (74066); # drunken_ghulam 17
UPDATE npc_types SET loottable_id = :kerraridge_erfer_longclaw_lt: WHERE id in (74024); # Erfer_Longclaw 18
UPDATE npc_types SET loottable_id = :kerraridge_errrak_thickshank_lt: WHERE id in (74055); # Errrak_Thickshank 17
UPDATE npc_types SET loottable_id = :kerraridge_falthrik_lothoro_lt: WHERE id in (74030); # Falthrik_Lothoro 20
UPDATE npc_types SET loottable_id = :kerraridge_fang_tooth_lt: WHERE id in (74120); # fang_tooth 15
UPDATE npc_types SET loottable_id = :kerraridge_feren_lt: WHERE id in (74028); # Feren 14
UPDATE npc_types SET loottable_id = :kerraridge_feskr_drinkmaker_lt: WHERE id in (74058); # Feskr_Drinkmaker 15
UPDATE npc_types SET loottable_id = :kerraridge_graalf_sharpclaw_lt: WHERE id in (74057); # Graalf_Sharpclaw 14
UPDATE npc_types SET loottable_id = :kerraridge_hamed_grarr_lt: WHERE id in (74114); # Hamed_Grarr 21
UPDATE npc_types SET loottable_id = :kerraridge_iffrir_soulcaller_lt: WHERE id in (74023); # Iffrir_Soulcaller 18
UPDATE npc_types SET loottable_id = :kerraridge_jo_jo_lt: WHERE id in (74107); # Jo_Jo 18
UPDATE npc_types SET loottable_id = :kerraridge_kerran_tiger_spahi_lt: WHERE id in (74033); # kerran_tiger_spahi 22
UPDATE npc_types SET loottable_id = :kerraridge_kerran_tseq_lt: WHERE id in (74003, 74004); # kerran_tseq 12
UPDATE npc_types SET loottable_id = :kerraridge_khonza_mitty_of_kerra_lt: WHERE id in (74116); # Khonza_Mitty_of_Kerra 23
UPDATE npc_types SET loottable_id = :kerraridge_kirran_mirrah_lt: WHERE id in (74119); # Kirran_Mirrah 14
UPDATE npc_types SET loottable_id = :kerraridge_lord_gongo_lt: WHERE id in (74115); # Lord_Gongo 20
UPDATE npc_types SET loottable_id = :kerraridge_marl_kastane_lt: WHERE id in (74089); # Marl_Kastane 60
UPDATE npc_types SET loottable_id = :kerraridge_maugarim_lt: WHERE id in (74041); # Maugarim 25
UPDATE npc_types SET loottable_id = :kerraridge_melixis_lt: WHERE id in (74076); # Melixis 20
UPDATE npc_types SET loottable_id = :kerraridge_raarrk_lt: WHERE id in (74070); # Raarrk 35
UPDATE npc_types SET loottable_id = :kerraridge_razortooth_lt: WHERE id in (74118); # Razortooth 25
UPDATE npc_types SET loottable_id = :kerraridge_roary_fishpouncer_lt: WHERE id in (74069); # Roary_Fishpouncer 13
UPDATE npc_types SET loottable_id = :kerraridge_shazda_asad_lt: WHERE id in (74032); # Shazda_Asad 23
UPDATE npc_types SET loottable_id = :kerraridge_spikefish_lt: WHERE id in (74029); # Spikefish 13
UPDATE npc_types SET loottable_id = :kerraridge_thalith_mamluk_lt: WHERE id in (74074); # Thalith_Mamluk 14
UPDATE npc_types SET loottable_id = :kerraridge_the_kerran_sharr_lt: WHERE id in (74014); # The_Kerran_Sha`rr 22
UPDATE npc_types SET loottable_id = :kerraridge_urkath_greyface_lt: WHERE id in (74022); # Urkath_Greyface 18
UPDATE npc_types SET loottable_id = :kerraridge_wharf_rat_lt: WHERE id in (74068, 74072); # wharf_rat 11
UPDATE npc_types SET loottable_id = :kerraridge_wislen_mamluk_lt: WHERE id in (74005); # Wislen_Mamluk 14
