INSERT INTO loottable(name) VALUES('lakerathe_ancient_megalodon'); # :lakerathe_ancient_megalodon_lt:
INSERT INTO loottable(name) VALUES('lakerathe_egonis'); # :lakerathe_egonis_lt:
INSERT INTO loottable(name) VALUES('lakerathe_gnoll_scavenger'); # :lakerathe_gnoll_scavenger_lt:
INSERT INTO loottable(name) VALUES('lakerathe_guja_master_therik'); # :lakerathe_guja_master_therik_lt:
INSERT INTO loottable(name) VALUES('lakerathe_kimm_mcshannel'); # :lakerathe_kimm_mcshannel_lt:
INSERT INTO loottable(name) VALUES('lakerathe_man-eating_freshwater_shark'); # :lakerathe_man-eating_freshwater_shark_lt:
INSERT INTO loottable(name) VALUES('lakerathe_natasha_whitewater'); # :lakerathe_natasha_whitewater_lt:
INSERT INTO loottable(name) VALUES('lakerathe_ronaiar_skullmoore'); # :lakerathe_ronaiar_skullmoore_lt:
INSERT INTO loottable(name) VALUES('lakerathe_tainted_aquagoblin'); # :lakerathe_tainted_aquagoblin_lt:
INSERT INTO loottable(name) VALUES('lakerathe_the_fabled_webclaw_murkwave'); # :lakerathe_the_fabled_webclaw_murkwave_lt:
INSERT INTO loottable(name) VALUES('lakerathe_triathalon_bike'); # :lakerathe_triathalon_bike_lt:
INSERT INTO loottable(name) VALUES('lakerathe_triathalon_swim_goggles'); # :lakerathe_triathalon_swim_goggles_lt:
INSERT INTO loottable(name) VALUES('lakerathe_worboli'); # :lakerathe_worboli_lt:
INSERT INTO loottable(name) VALUES('lakerathe_2_'); # :lakerathe_2__lt:
INSERT INTO loottable(name) VALUES('lakerathe_abrod'); # :lakerathe_abrod_lt:
INSERT INTO loottable(name) VALUES('lakerathe_aija'); # :lakerathe_aija_lt:
INSERT INTO loottable(name) VALUES('lakerathe_an_algae_snake'); # :lakerathe_an_algae_snake_lt:
INSERT INTO loottable(name) VALUES('lakerathe_an_alligator'); # :lakerathe_an_alligator_lt:
INSERT INTO loottable(name) VALUES('lakerathe_an_aqua_goblin'); # :lakerathe_an_aqua_goblin_lt:
INSERT INTO loottable(name) VALUES('lakerathe_an_aqua_goblin_shaman'); # :lakerathe_an_aqua_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('lakerathe_an_aviak'); # :lakerathe_an_aviak_lt:
INSERT INTO loottable(name) VALUES('lakerathe_an_aviak_guard'); # :lakerathe_an_aviak_guard_lt:
INSERT INTO loottable(name) VALUES('lakerathe_an_exhumed_gnoll'); # :lakerathe_an_exhumed_gnoll_lt:
INSERT INTO loottable(name) VALUES('lakerathe_an_orc_warrior'); # :lakerathe_an_orc_warrior_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_bandit'); # :lakerathe_a_bandit_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_boat'); # :lakerathe_a_boat_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_bone_golem'); # :lakerathe_a_bone_golem_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_brigand'); # :lakerathe_a_brigand_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_crocodile'); # :lakerathe_a_crocodile_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_deepwater_goblin'); # :lakerathe_a_deepwater_goblin_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_failed_apprentice'); # :lakerathe_a_failed_apprentice_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_fallen_student'); # :lakerathe_a_fallen_student_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_fish'); # :lakerathe_a_fish_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_freshwater_shark'); # :lakerathe_a_freshwater_shark_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_froglok'); # :lakerathe_a_froglok_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_gnoll'); # :lakerathe_a_gnoll_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_gnoll_embalmer'); # :lakerathe_a_gnoll_embalmer_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_gnoll_guard'); # :lakerathe_a_gnoll_guard_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_gnoll_high_shaman'); # :lakerathe_a_gnoll_high_shaman_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_gnoll_shaman'); # :lakerathe_a_gnoll_shaman_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_goblin_net_master'); # :lakerathe_a_goblin_net_master_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_greater_zombie'); # :lakerathe_a_greater_zombie_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_royal_fish'); # :lakerathe_a_royal_fish_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_skeleton'); # :lakerathe_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_spirit_of_flame'); # :lakerathe_a_spirit_of_flame_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_stone_skeleton'); # :lakerathe_a_stone_skeleton_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_tortured_soul'); # :lakerathe_a_tortured_soul_lt:
INSERT INTO loottable(name) VALUES('lakerathe_a_water_snake'); # :lakerathe_a_water_snake_lt:
INSERT INTO loottable(name) VALUES('lakerathe_brundar'); # :lakerathe_brundar_lt:
INSERT INTO loottable(name) VALUES('lakerathe_corrupted_aquagoblin'); # :lakerathe_corrupted_aquagoblin_lt:
INSERT INTO loottable(name) VALUES('lakerathe_corrupted_shaman'); # :lakerathe_corrupted_shaman_lt:
INSERT INTO loottable(name) VALUES('lakerathe_cyanelle'); # :lakerathe_cyanelle_lt:
INSERT INTO loottable(name) VALUES('lakerathe_deep'); # :lakerathe_deep_lt:
INSERT INTO loottable(name) VALUES('lakerathe_deillia'); # :lakerathe_deillia_lt:
INSERT INTO loottable(name) VALUES('lakerathe_derg'); # :lakerathe_derg_lt:
INSERT INTO loottable(name) VALUES('lakerathe_dreana'); # :lakerathe_dreana_lt:
INSERT INTO loottable(name) VALUES('lakerathe_dunndrylla'); # :lakerathe_dunndrylla_lt:
INSERT INTO loottable(name) VALUES('lakerathe_eldreth'); # :lakerathe_eldreth_lt:
INSERT INTO loottable(name) VALUES('lakerathe_emkel_kabae'); # :lakerathe_emkel_kabae_lt:
INSERT INTO loottable(name) VALUES('lakerathe_give_me_your_token'); # :lakerathe_give_me_your_token_lt:
INSERT INTO loottable(name) VALUES('lakerathe_grinda'); # :lakerathe_grinda_lt:
INSERT INTO loottable(name) VALUES('lakerathe_groethar'); # :lakerathe_groethar_lt:
INSERT INTO loottable(name) VALUES('lakerathe_grud'); # :lakerathe_grud_lt:
INSERT INTO loottable(name) VALUES('lakerathe_guard_rianna'); # :lakerathe_guard_rianna_lt:
INSERT INTO loottable(name) VALUES('lakerathe_guard_treal'); # :lakerathe_guard_treal_lt:
INSERT INTO loottable(name) VALUES('lakerathe_gunhedra'); # :lakerathe_gunhedra_lt:
INSERT INTO loottable(name) VALUES('lakerathe_hruthgar'); # :lakerathe_hruthgar_lt:
INSERT INTO loottable(name) VALUES('lakerathe_hulga'); # :lakerathe_hulga_lt:
INSERT INTO loottable(name) VALUES('lakerathe_jonah_brucker'); # :lakerathe_jonah_brucker_lt:
INSERT INTO loottable(name) VALUES('lakerathe_jorna'); # :lakerathe_jorna_lt:
INSERT INTO loottable(name) VALUES('lakerathe_kanthurn'); # :lakerathe_kanthurn_lt:
INSERT INTO loottable(name) VALUES('lakerathe_kazen_fecae'); # :lakerathe_kazen_fecae_lt:
INSERT INTO loottable(name) VALUES('lakerathe_kyralynn'); # :lakerathe_kyralynn_lt:
INSERT INTO loottable(name) VALUES('lakerathe_lenklo'); # :lakerathe_lenklo_lt:
INSERT INTO loottable(name) VALUES('lakerathe_lord_bergurgle'); # :lakerathe_lord_bergurgle_lt:
INSERT INTO loottable(name) VALUES('lakerathe_lorud'); # :lakerathe_lorud_lt:
INSERT INTO loottable(name) VALUES('lakerathe_misty_tekcihta'); # :lakerathe_misty_tekcihta_lt:
INSERT INTO loottable(name) VALUES('lakerathe_princess_lenya_thex'); # :lakerathe_princess_lenya_thex_lt:
INSERT INTO loottable(name) VALUES('lakerathe_punga'); # :lakerathe_punga_lt:
INSERT INTO loottable(name) VALUES('lakerathe_rondel'); # :lakerathe_rondel_lt:
INSERT INTO loottable(name) VALUES('lakerathe_rykas'); # :lakerathe_rykas_lt:
INSERT INTO loottable(name) VALUES('lakerathe_shmendrik_lavawalker'); # :lakerathe_shmendrik_lavawalker_lt:
INSERT INTO loottable(name) VALUES('lakerathe_srynda'); # :lakerathe_srynda_lt:
INSERT INTO loottable(name) VALUES('lakerathe_tabitha'); # :lakerathe_tabitha_lt:
INSERT INTO loottable(name) VALUES('lakerathe_taia_lyfol'); # :lakerathe_taia_lyfol_lt:
INSERT INTO loottable(name) VALUES('lakerathe_tainted_aquagoblin'); # :lakerathe_tainted_aquagoblin_lt:
INSERT INTO loottable(name) VALUES('lakerathe_the_lake_lurker'); # :lakerathe_the_lake_lurker_lt:
INSERT INTO loottable(name) VALUES('lakerathe_tralinda'); # :lakerathe_tralinda_lt:
INSERT INTO loottable(name) VALUES('lakerathe_trug'); # :lakerathe_trug_lt:
INSERT INTO loottable(name) VALUES('lakerathe_turga'); # :lakerathe_turga_lt:
INSERT INTO loottable(name) VALUES('lakerathe_turgan'); # :lakerathe_turgan_lt:
INSERT INTO loottable(name) VALUES('lakerathe_vrynn'); # :lakerathe_vrynn_lt:
INSERT INTO loottable(name) VALUES('lakerathe_webclaw_murkwave'); # :lakerathe_webclaw_murkwave_lt:
