INSERT INTO loottable(name) VALUES('lfaydark_a_wayfarer'); # :lfaydark_a_wayfarer_lt:
INSERT INTO loottable(name) VALUES('lfaydark_kahliz_the_mist_runner'); # :lfaydark_kahliz_the_mist_runner_lt:
INSERT INTO loottable(name) VALUES('lfaydark_taskmaster_mirot'); # :lfaydark_taskmaster_mirot_lt:
INSERT INTO loottable(name) VALUES('lfaydark_the_spirit_of_malevolence'); # :lfaydark_the_spirit_of_malevolence_lt:
INSERT INTO loottable(name) VALUES('lfaydark_anelia_thrywiel'); # :lfaydark_anelia_thrywiel_lt:
INSERT INTO loottable(name) VALUES('lfaydark_an_emperor_fae_drake'); # :lfaydark_an_emperor_fae_drake_lt:
INSERT INTO loottable(name) VALUES('lfaydark_averna_eisley'); # :lfaydark_averna_eisley_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_bandit'); # :lfaydark_a_bandit_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_brownie'); # :lfaydark_a_brownie_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_brownie_farmer'); # :lfaydark_a_brownie_farmer_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_brownie_guard'); # :lfaydark_a_brownie_guard_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_brownie_merchant'); # :lfaydark_a_brownie_merchant_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_brownie_noble'); # :lfaydark_a_brownie_noble_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_brownie_outcast'); # :lfaydark_a_brownie_outcast_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_faerie'); # :lfaydark_a_faerie_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_faerie_courtier'); # :lfaydark_a_faerie_courtier_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_faerie_guard'); # :lfaydark_a_faerie_guard_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_faerie_maiden'); # :lfaydark_a_faerie_maiden_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_fae_drake'); # :lfaydark_a_fae_drake_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_fae_drake_hatchling'); # :lfaydark_a_fae_drake_hatchling_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_fairy_guard'); # :lfaydark_a_fairy_guard_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_giant_spider'); # :lfaydark_a_giant_spider_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_mist_wolf'); # :lfaydark_a_mist_wolf_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_monarch_fae_drake'); # :lfaydark_a_monarch_fae_drake_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_mummy'); # :lfaydark_a_mummy_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_pixie_jongleur'); # :lfaydark_a_pixie_jongleur_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_pixie_prankster'); # :lfaydark_a_pixie_prankster_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_pixie_trickster'); # :lfaydark_a_pixie_trickster_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_rancorous_ghast'); # :lfaydark_a_rancorous_ghast_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_shadowed_man'); # :lfaydark_a_shadowed_man_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_skeleton'); # :lfaydark_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_spiderling'); # :lfaydark_a_spiderling_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_wasp_sentinel'); # :lfaydark_a_wasp_sentinel_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_wasp_soldier'); # :lfaydark_a_wasp_soldier_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_wayfarer'); # :lfaydark_a_wayfarer_lt:
INSERT INTO loottable(name) VALUES('lfaydark_a_werewolf'); # :lfaydark_a_werewolf_lt:
INSERT INTO loottable(name) VALUES('lfaydark_bin_fiddlekins'); # :lfaydark_bin_fiddlekins_lt:
INSERT INTO loottable(name) VALUES('lfaydark_bracken_underbrush'); # :lfaydark_bracken_underbrush_lt:
INSERT INTO loottable(name) VALUES('lfaydark_brownie_scout'); # :lfaydark_brownie_scout_lt:
INSERT INTO loottable(name) VALUES('lfaydark_bryn_fynndel'); # :lfaydark_bryn_fynndel_lt:
INSERT INTO loottable(name) VALUES('lfaydark_cognoggin'); # :lfaydark_cognoggin_lt:
INSERT INTO loottable(name) VALUES('lfaydark_corrupted_brownie'); # :lfaydark_corrupted_brownie_lt:
INSERT INTO loottable(name) VALUES('lfaydark_crookstinger'); # :lfaydark_crookstinger_lt:
INSERT INTO loottable(name) VALUES('lfaydark_cylas_delbrin'); # :lfaydark_cylas_delbrin_lt:
INSERT INTO loottable(name) VALUES('lfaydark_dragoon_szorn'); # :lfaydark_dragoon_szorn_lt:
INSERT INTO loottable(name) VALUES('lfaydark_elwinn_prelliaen'); # :lfaydark_elwinn_prelliaen_lt:
INSERT INTO loottable(name) VALUES('lfaydark_equestrielle_the_corrupted'); # :lfaydark_equestrielle_the_corrupted_lt:
INSERT INTO loottable(name) VALUES('lfaydark_faril_elvebryn'); # :lfaydark_faril_elvebryn_lt:
INSERT INTO loottable(name) VALUES('lfaydark_galwyn_geldin'); # :lfaydark_galwyn_geldin_lt:
INSERT INTO loottable(name) VALUES('lfaydark_gearheart'); # :lfaydark_gearheart_lt:
INSERT INTO loottable(name) VALUES('lfaydark_ghoul_boss'); # :lfaydark_ghoul_boss_lt:
INSERT INTO loottable(name) VALUES('lfaydark_glidara_myllar'); # :lfaydark_glidara_myllar_lt:
INSERT INTO loottable(name) VALUES('lfaydark_glyndur_tindel'); # :lfaydark_glyndur_tindel_lt:
INSERT INTO loottable(name) VALUES('lfaydark_grynnaf_einoom'); # :lfaydark_grynnaf_einoom_lt:
INSERT INTO loottable(name) VALUES('lfaydark_gundel_elorion'); # :lfaydark_gundel_elorion_lt:
INSERT INTO loottable(name) VALUES('lfaydark_happ_dremblenod'); # :lfaydark_happ_dremblenod_lt:
INSERT INTO loottable(name) VALUES('lfaydark_ivie_bramblefoot'); # :lfaydark_ivie_bramblefoot_lt:
INSERT INTO loottable(name) VALUES('lfaydark_jayla_nybright'); # :lfaydark_jayla_nybright_lt:
INSERT INTO loottable(name) VALUES('lfaydark_kalayia_woodwhisper'); # :lfaydark_kalayia_woodwhisper_lt:
INSERT INTO loottable(name) VALUES('lfaydark_kayla_nybright'); # :lfaydark_kayla_nybright_lt:
INSERT INTO loottable(name) VALUES('lfaydark_larik_zvole'); # :lfaydark_larik_zvole_lt:
INSERT INTO loottable(name) VALUES('lfaydark_mina_glimmerwing'); # :lfaydark_mina_glimmerwing_lt:
INSERT INTO loottable(name) VALUES('lfaydark_mywyn_tinendel'); # :lfaydark_mywyn_tinendel_lt:
INSERT INTO loottable(name) VALUES('lfaydark_old_dimshimmer'); # :lfaydark_old_dimshimmer_lt:
INSERT INTO loottable(name) VALUES('lfaydark_orc_centurion'); # :lfaydark_orc_centurion_lt:
INSERT INTO loottable(name) VALUES('lfaydark_orc_chief'); # :lfaydark_orc_chief_lt:
INSERT INTO loottable(name) VALUES('lfaydark_orc_legionnaire'); # :lfaydark_orc_legionnaire_lt:
INSERT INTO loottable(name) VALUES('lfaydark_orc_oracle'); # :lfaydark_orc_oracle_lt:
INSERT INTO loottable(name) VALUES('lfaydark_pained_unicorn'); # :lfaydark_pained_unicorn_lt:
INSERT INTO loottable(name) VALUES('lfaydark_priestess_llandra'); # :lfaydark_priestess_llandra_lt:
INSERT INTO loottable(name) VALUES('lfaydark_princess_joleena'); # :lfaydark_princess_joleena_lt:
INSERT INTO loottable(name) VALUES('lfaydark_queen_nasheeji'); # :lfaydark_queen_nasheeji_lt:
INSERT INTO loottable(name) VALUES('lfaydark_reanimated_minion'); # :lfaydark_reanimated_minion_lt:
INSERT INTO loottable(name) VALUES('lfaydark_saben_tucross'); # :lfaydark_saben_tucross_lt:
INSERT INTO loottable(name) VALUES('lfaydark_sarawyn_amorfin'); # :lfaydark_sarawyn_amorfin_lt:
INSERT INTO loottable(name) VALUES('lfaydark_scout_leader_plavo'); # :lfaydark_scout_leader_plavo_lt:
INSERT INTO loottable(name) VALUES('lfaydark_scout_rahjiq'); # :lfaydark_scout_rahjiq_lt:
INSERT INTO loottable(name) VALUES('lfaydark_shadowman_leader'); # :lfaydark_shadowman_leader_lt:
INSERT INTO loottable(name) VALUES('lfaydark_shayla_nybright'); # :lfaydark_shayla_nybright_lt:
INSERT INTO loottable(name) VALUES('lfaydark_tainted_brownie'); # :lfaydark_tainted_brownie_lt:
INSERT INTO loottable(name) VALUES('lfaydark_taskmaster_mirot'); # :lfaydark_taskmaster_mirot_lt:
INSERT INTO loottable(name) VALUES('lfaydark_tayla_nybright'); # :lfaydark_tayla_nybright_lt:
INSERT INTO loottable(name) VALUES('lfaydark_teirdal_elite'); # :lfaydark_teirdal_elite_lt:
INSERT INTO loottable(name) VALUES('lfaydark_teirdal_prophet'); # :lfaydark_teirdal_prophet_lt:
INSERT INTO loottable(name) VALUES('lfaydark_the_mist'); # :lfaydark_the_mist_lt:
INSERT INTO loottable(name) VALUES('lfaydark_thistle_underbrush'); # :lfaydark_thistle_underbrush_lt:
INSERT INTO loottable(name) VALUES('lfaydark_trudo_frugrin'); # :lfaydark_trudo_frugrin_lt:
INSERT INTO loottable(name) VALUES('lfaydark_vynn_thrildur'); # :lfaydark_vynn_thrildur_lt:
INSERT INTO loottable(name) VALUES('lfaydark_whimsy_larktwitter'); # :lfaydark_whimsy_larktwitter_lt:
INSERT INTO loottable(name) VALUES('lfaydark__2__'); # :lfaydark__2___lt:
INSERT INTO loottable(name) VALUES('lfaydark__watcher'); # :lfaydark__watcher_lt:
