INSERT INTO loottable(name) VALUES('mistythicket_a_faithful_farmer'); # :mistythicket_a_faithful_farmer_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_tired_farmer'); # :mistythicket_a_tired_farmer_lt:
INSERT INTO loottable(name) VALUES('mistythicket_old_gourdhead'); # :mistythicket_old_gourdhead_lt:
INSERT INTO loottable(name) VALUES('mistythicket_an_orc_lumberjack'); # :mistythicket_an_orc_lumberjack_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_bat'); # :mistythicket_a_bat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_bixie'); # :mistythicket_a_bixie_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_bixie_drone'); # :mistythicket_a_bixie_drone_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_bixie_queen'); # :mistythicket_a_bixie_queen_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_black_bear'); # :mistythicket_a_black_bear_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_black_wolf'); # :mistythicket_a_black_wolf_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_decaying_skeleton'); # :mistythicket_a_decaying_skeleton_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_diseased_rat'); # :mistythicket_a_diseased_rat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_fire_beetle'); # :mistythicket_a_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_giant_bat'); # :mistythicket_a_giant_bat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_giant_fruit_bat'); # :mistythicket_a_giant_fruit_bat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_giant_scarab'); # :mistythicket_a_giant_scarab_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_giant_thicket_rat'); # :mistythicket_a_giant_thicket_rat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_giant_wood_spider'); # :mistythicket_a_giant_wood_spider_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_giant_yellowjacket'); # :mistythicket_a_giant_yellowjacket_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_goblin_alchemist'); # :mistythicket_a_goblin_alchemist_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_goblin_shaman'); # :mistythicket_a_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_goblin_warrior'); # :mistythicket_a_goblin_warrior_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_goblin_worker'); # :mistythicket_a_goblin_worker_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_halfling_skeleton'); # :mistythicket_a_halfling_skeleton_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_halfling_zombie'); # :mistythicket_a_halfling_zombie_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_klaknak_drone'); # :mistythicket_a_klaknak_drone_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_klaknak_warrior'); # :mistythicket_a_klaknak_warrior_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_large_bat'); # :mistythicket_a_large_bat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_large_fruit_bat'); # :mistythicket_a_large_fruit_bat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_large_rat'); # :mistythicket_a_large_rat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_large_thicket_rat'); # :mistythicket_a_large_thicket_rat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_large_wood_spider'); # :mistythicket_a_large_wood_spider_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_large_yellowjacket'); # :mistythicket_a_large_yellowjacket_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_lesser_mummy'); # :mistythicket_a_lesser_mummy_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_mangy_rat'); # :mistythicket_a_mangy_rat_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_moss_snake'); # :mistythicket_a_moss_snake_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_shadowed_assassin'); # :mistythicket_a_shadowed_assassin_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_shadow_wolf'); # :mistythicket_a_shadow_wolf_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_skeleton'); # :mistythicket_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_spiderling'); # :mistythicket_a_spiderling_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_thorn_drakeling'); # :mistythicket_a_thorn_drakeling_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_tree_snake'); # :mistythicket_a_tree_snake_lt:
INSERT INTO loottable(name) VALUES('mistythicket_a_young_kodiak'); # :mistythicket_a_young_kodiak_lt:
INSERT INTO loottable(name) VALUES('mistythicket_bidils_the_quickhand'); # :mistythicket_bidils_the_quickhand_lt:
INSERT INTO loottable(name) VALUES('mistythicket_bim_buskin'); # :mistythicket_bim_buskin_lt:
INSERT INTO loottable(name) VALUES('mistythicket_blixkin_entopop'); # :mistythicket_blixkin_entopop_lt:
INSERT INTO loottable(name) VALUES('mistythicket_brock_brawlbottom'); # :mistythicket_brock_brawlbottom_lt:
INSERT INTO loottable(name) VALUES('mistythicket_bronin_higginsbot'); # :mistythicket_bronin_higginsbot_lt:
INSERT INTO loottable(name) VALUES('mistythicket_cozy'); # :mistythicket_cozy_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_asler'); # :mistythicket_deputy_asler_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_budo'); # :mistythicket_deputy_budo_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_drebo'); # :mistythicket_deputy_drebo_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_eigon'); # :mistythicket_deputy_eigon_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_felp'); # :mistythicket_deputy_felp_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_keld'); # :mistythicket_deputy_keld_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_looh'); # :mistythicket_deputy_looh_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_poolt'); # :mistythicket_deputy_poolt_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_tagil'); # :mistythicket_deputy_tagil_lt:
INSERT INTO loottable(name) VALUES('mistythicket_deputy_vastin'); # :mistythicket_deputy_vastin_lt:
INSERT INTO loottable(name) VALUES('mistythicket_ella_foodcrafter'); # :mistythicket_ella_foodcrafter_lt:
INSERT INTO loottable(name) VALUES('mistythicket_ember'); # :mistythicket_ember_lt:
INSERT INTO loottable(name) VALUES('mistythicket_epicurean_halfling'); # :mistythicket_epicurean_halfling_lt:
INSERT INTO loottable(name) VALUES('mistythicket_faano_windmaker'); # :mistythicket_faano_windmaker_lt:
INSERT INTO loottable(name) VALUES('mistythicket_fajio_knejo'); # :mistythicket_fajio_knejo_lt:
INSERT INTO loottable(name) VALUES('mistythicket_felawen_kellthoo'); # :mistythicket_felawen_kellthoo_lt:
INSERT INTO loottable(name) VALUES('mistythicket_ferrigon_hepplebottom'); # :mistythicket_ferrigon_hepplebottom_lt:
INSERT INTO loottable(name) VALUES('mistythicket_gunrich'); # :mistythicket_gunrich_lt:
INSERT INTO loottable(name) VALUES('mistythicket_hanga_wiskin'); # :mistythicket_hanga_wiskin_lt:
INSERT INTO loottable(name) VALUES('mistythicket_joogl_honeybugger'); # :mistythicket_joogl_honeybugger_lt:
INSERT INTO loottable(name) VALUES('mistythicket_lil_honeybugger'); # :mistythicket_lil_honeybugger_lt:
INSERT INTO loottable(name) VALUES('mistythicket_mooto'); # :mistythicket_mooto_lt:
INSERT INTO loottable(name) VALUES('mistythicket_orc_apprentice'); # :mistythicket_orc_apprentice_lt:
INSERT INTO loottable(name) VALUES('mistythicket_orc_centurion'); # :mistythicket_orc_centurion_lt:
INSERT INTO loottable(name) VALUES('mistythicket_orc_legionnaire'); # :mistythicket_orc_legionnaire_lt:
INSERT INTO loottable(name) VALUES('mistythicket_orc_oracle'); # :mistythicket_orc_oracle_lt:
INSERT INTO loottable(name) VALUES('mistythicket_orc_pawn'); # :mistythicket_orc_pawn_lt:
INSERT INTO loottable(name) VALUES('mistythicket_princess_klaknak'); # :mistythicket_princess_klaknak_lt:
INSERT INTO loottable(name) VALUES('mistythicket_prince_klaknak'); # :mistythicket_prince_klaknak_lt:
INSERT INTO loottable(name) VALUES('mistythicket_queen_klaknak'); # :mistythicket_queen_klaknak_lt:
INSERT INTO loottable(name) VALUES('mistythicket_relia_wastein'); # :mistythicket_relia_wastein_lt:
INSERT INTO loottable(name) VALUES('mistythicket_roha_jumthief'); # :mistythicket_roha_jumthief_lt:
INSERT INTO loottable(name) VALUES('mistythicket_rufus'); # :mistythicket_rufus_lt:
INSERT INTO loottable(name) VALUES('mistythicket_rusbek_the_inhospitable'); # :mistythicket_rusbek_the_inhospitable_lt:
INSERT INTO loottable(name) VALUES('mistythicket_simeena_sukan'); # :mistythicket_simeena_sukan_lt:
INSERT INTO loottable(name) VALUES('mistythicket_slaythe'); # :mistythicket_slaythe_lt:
INSERT INTO loottable(name) VALUES('mistythicket_sonsa_fromp'); # :mistythicket_sonsa_fromp_lt:
INSERT INTO loottable(name) VALUES('mistythicket_swish_appletop'); # :mistythicket_swish_appletop_lt:
INSERT INTO loottable(name) VALUES('mistythicket_tain_whistleburrow'); # :mistythicket_tain_whistleburrow_lt:
INSERT INTO loottable(name) VALUES('mistythicket_the_fabled_mooto'); # :mistythicket_the_fabled_mooto_lt:
INSERT INTO loottable(name) VALUES('mistythicket_tipa_lighten'); # :mistythicket_tipa_lighten_lt:
INSERT INTO loottable(name) VALUES('mistythicket_topper_drodo'); # :mistythicket_topper_drodo_lt:
