UPDATE npc_types SET loottable_id = :misty_a_faithful_farmer_lt: WHERE id in (33159); # #a_faithful_farmer 12
UPDATE npc_types SET loottable_id = :misty_a_ghoulish_guardian_lt: WHERE id in (33169); # #A_Ghoulish_Guardian 71
UPDATE npc_types SET loottable_id = :misty_a_ravenous_werewolf_lt: WHERE id in (33170); # #A_Ravenous_Werewolf 71
UPDATE npc_types SET loottable_id = :misty_a_scarecrow_lt: WHERE id in (33168); # #A_Scarecrow 71
UPDATE npc_types SET loottable_id = :misty_a_tired_farmer_lt: WHERE id in (33150); # #a_tired_farmer 12
UPDATE npc_types SET loottable_id = :misty_a_vicious_spider_lt: WHERE id in (33167); # #a_vicious_spider 70
UPDATE npc_types SET loottable_id = :misty_old_gourdhead_lt: WHERE id in (33080); # #Old_Gourdhead 1
UPDATE npc_types SET loottable_id = :misty_orc_corpse_lt: WHERE id in (33166, 33171); # #orc_corpse 10
UPDATE npc_types SET loottable_id = :misty_an_orc_lumberjack_lt: WHERE id in (33156); # an_orc_lumberjack 10
UPDATE npc_types SET loottable_id = :misty_a_bat_lt: WHERE id in (33028); # a_bat 1
UPDATE npc_types SET loottable_id = :misty_a_bixie_lt: WHERE id in (33099, 33002); # a_bixie 1
UPDATE npc_types SET loottable_id = :misty_a_bixie_drone_lt: WHERE id in (33019); # a_bixie_drone 2
UPDATE npc_types SET loottable_id = :misty_a_bixie_queen_lt: WHERE id in (33149); # a_bixie_queen 4
UPDATE npc_types SET loottable_id = :misty_a_black_bear_lt: WHERE id in (33101, 33000); # a_black_bear 5
UPDATE npc_types SET loottable_id = :misty_a_black_wolf_lt: WHERE id in (33031); # a_black_wolf 1
UPDATE npc_types SET loottable_id = :misty_a_decaying_skeleton_lt: WHERE id in (33106); # a_decaying_skeleton 1
UPDATE npc_types SET loottable_id = :misty_a_diseased_rat_lt: WHERE id in (33044, 33052, 33054); # a_diseased_rat 3
UPDATE npc_types SET loottable_id = :misty_a_fire_beetle_lt: WHERE id in (33024, 33015); # a_fire_beetle 2
UPDATE npc_types SET loottable_id = :misty_a_giant_bat_lt: WHERE id in (33098, 33001, 33006); # a_giant_bat 7
UPDATE npc_types SET loottable_id = :misty_a_giant_fruit_bat_lt: WHERE id in (33020); # a_giant_fruit_bat 9
UPDATE npc_types SET loottable_id = :misty_a_giant_scarab_lt: WHERE id in (33035, 33096); # a_giant_scarab 11
UPDATE npc_types SET loottable_id = :misty_a_giant_thicket_rat_lt: WHERE id in (33027, 33039, 33055); # a_giant_thicket_rat 9
UPDATE npc_types SET loottable_id = :misty_a_giant_wood_spider_lt: WHERE id in (33152, 33153); # a_giant_wood_spider 7
UPDATE npc_types SET loottable_id = :misty_a_giant_yellowjacket_lt: WHERE id in (33158); # a_giant_yellowjacket 9
UPDATE npc_types SET loottable_id = :misty_a_goblin_alchemist_lt: WHERE id in (33154); # a_goblin_alchemist 16
UPDATE npc_types SET loottable_id = :misty_a_goblin_shaman_lt: WHERE id in (33155); # a_goblin_shaman 11
UPDATE npc_types SET loottable_id = :misty_a_goblin_warrior_lt: WHERE id in (33043, 33121, 33012, 33013, 33016); # a_goblin_warrior 7
UPDATE npc_types SET loottable_id = :misty_a_goblin_worker_lt: WHERE id in (33100); # a_goblin_worker 1
UPDATE npc_types SET loottable_id = :misty_a_halfling_skeleton_lt: WHERE id in (33051, 33053, 33056); # a_halfling_skeleton 5
UPDATE npc_types SET loottable_id = :misty_a_halfling_zombie_lt: WHERE id in (33147); # a_halfling_zombie 8
UPDATE npc_types SET loottable_id = :misty_a_klaknak_warrior_lt: WHERE id in (33045); # a_Klaknak_warrior 2
UPDATE npc_types SET loottable_id = :misty_a_large_bat_lt: WHERE id in (33047, 33048, 33057, 33007); # a_large_bat 4
UPDATE npc_types SET loottable_id = :misty_a_large_fruit_bat_lt: WHERE id in (33025, 33026); # a_large_fruit_bat 4
UPDATE npc_types SET loottable_id = :misty_a_large_rat_lt: WHERE id in (33005); # a_large_rat 1
UPDATE npc_types SET loottable_id = :misty_a_large_thicket_rat_lt: WHERE id in (33030, 33042, 33058); # a_large_thicket_rat 3
UPDATE npc_types SET loottable_id = :misty_a_large_wood_spider_lt: WHERE id in (33040, 33049); # a_large_wood_spider 3
UPDATE npc_types SET loottable_id = :misty_a_large_yellowjacket_lt: WHERE id in (33050); # a_large_yellowjacket 4
UPDATE npc_types SET loottable_id = :misty_a_lesser_mummy_lt: WHERE id in (33008); # a_lesser_mummy 12
UPDATE npc_types SET loottable_id = :misty_a_mangy_rat_lt: WHERE id in (33160); # a_mangy_rat 1
UPDATE npc_types SET loottable_id = :misty_a_moss_snake_lt: WHERE id in (33017); # a_moss_snake 1
UPDATE npc_types SET loottable_id = :misty_a_shadowed_assassin_lt: WHERE id in (33059, 33060, 33061, 33062, 33063, 33102, 33103, 33110, 33133); # a_shadowed_assassin 7
UPDATE npc_types SET loottable_id = :misty_a_shadow_wolf_lt: WHERE id in (33032, 33046, 33003); # a_shadow_wolf 3
UPDATE npc_types SET loottable_id = :misty_a_skeleton_lt: WHERE id in (33116, 33009); # a_skeleton 5
UPDATE npc_types SET loottable_id = :misty_a_spiderling_lt: WHERE id in (33029, 33004, 33021); # a_spiderling 3
UPDATE npc_types SET loottable_id = :misty_a_thorn_drakeling_lt: WHERE id in (33097, 33018); # a_thorn_drakeling 5
UPDATE npc_types SET loottable_id = :misty_a_tree_snake_lt: WHERE id in (33041, 33010, 33011); # a_tree_snake 6
UPDATE npc_types SET loottable_id = :misty_a_young_kodiak_lt: WHERE id in (33014); # a_young_kodiak 10
UPDATE npc_types SET loottable_id = :misty_bidils_the_quickhand_lt: WHERE id in (33076); # Bidils_the_Quickhand 61
UPDATE npc_types SET loottable_id = :misty_bim_buskin_lt: WHERE id in (33089); # Bim_Buskin 30
UPDATE npc_types SET loottable_id = :misty_blixkin_entopop_lt: WHERE id in (33066); # Blixkin_Entopop 27
UPDATE npc_types SET loottable_id = :misty_brock_brawlbottom_lt: WHERE id in (33078, 33128); # Brock_Brawlbottom 13
UPDATE npc_types SET loottable_id = :misty_bronin_higginsbot_lt: WHERE id in (33079); # Bronin_Higginsbot 10
UPDATE npc_types SET loottable_id = :misty_cozy_lt: WHERE id in (33075, 33118); # Cozy 8
UPDATE npc_types SET loottable_id = :misty_crysta_tagglefoot_lt: WHERE id in (33164, 33165); # Crysta_Tagglefoot 60
UPDATE npc_types SET loottable_id = :misty_deputy?_lt: WHERE id in (33161); # Deputy? 73
UPDATE npc_types SET loottable_id = :misty_deputy??_lt: WHERE id in (33162); # Deputy?? 73
UPDATE npc_types SET loottable_id = :misty_deputy???_lt: WHERE id in (33163); # Deputy??? 73
UPDATE npc_types SET loottable_id = :misty_deputy_budo_lt: WHERE id in (33068); # Deputy_Budo 39
UPDATE npc_types SET loottable_id = :misty_deputy_drebo_lt: WHERE id in (33069); # Deputy_Drebo 29
UPDATE npc_types SET loottable_id = :misty_deputy_eigon_lt: WHERE id in (33070); # Deputy_Eigon 30
UPDATE npc_types SET loottable_id = :misty_deputy_felp_lt: WHERE id in (33072); # Deputy_Felp 25
UPDATE npc_types SET loottable_id = :misty_deputy_keld_lt: WHERE id in (33073); # Deputy_Keld 25
UPDATE npc_types SET loottable_id = :misty_deputy_looh_lt: WHERE id in (33067); # Deputy_Looh 27
UPDATE npc_types SET loottable_id = :misty_deputy_poolt_lt: WHERE id in (33151); # Deputy_Poolt 20
UPDATE npc_types SET loottable_id = :misty_deputy_tagil_lt: WHERE id in (33090); # Deputy_Tagil 50
UPDATE npc_types SET loottable_id = :misty_deputy_vastin_lt: WHERE id in (33091); # Deputy_Vastin 50
UPDATE npc_types SET loottable_id = :misty_ella_foodcrafter_lt: WHERE id in (33077); # Ella_Foodcrafter 50
UPDATE npc_types SET loottable_id = :misty_ember_lt: WHERE id in (33065); # Ember 1
UPDATE npc_types SET loottable_id = :misty_epicurean_halfling_lt: WHERE id in (33094); # epicurean_halfling 15
UPDATE npc_types SET loottable_id = :misty_faano_windmaker_lt: WHERE id in (33083); # Faano_Windmaker 15
UPDATE npc_types SET loottable_id = :misty_fajio_knejo_lt: WHERE id in (33092); # Fajio_Knejo 55
UPDATE npc_types SET loottable_id = :misty_felawen_kellthoo_lt: WHERE id in (33148); # Felawen_Kellthoo 50
UPDATE npc_types SET loottable_id = :misty_ferrigon_hepplebottom_lt: WHERE id in (33138); # Ferrigon_Hepplebottom 50
UPDATE npc_types SET loottable_id = :misty_gunrich_lt: WHERE id in (33135); # Gunrich 5
UPDATE npc_types SET loottable_id = :misty_hanga_wiskin_lt: WHERE id in (33085); # Hanga_Wiskin 30
UPDATE npc_types SET loottable_id = :misty_joogl_honeybugger_lt: WHERE id in (33084, 33127, 33134); # Joogl_Honeybugger 11
UPDATE npc_types SET loottable_id = :misty_lil_honeybugger_lt: WHERE id in (33081, 33129); # Lil_Honeybugger 1
UPDATE npc_types SET loottable_id = :misty_mooto_lt: WHERE id in (33104); # Mooto 10
UPDATE npc_types SET loottable_id = :misty_orc_apprentice_lt: WHERE id in (33033, 33038, 33113); # orc_apprentice 3
UPDATE npc_types SET loottable_id = :misty_orc_centurion_lt: WHERE id in (33034, 33036, 33037); # orc_centurion 10
UPDATE npc_types SET loottable_id = :misty_orc_legionnaire_lt: WHERE id in (33123); # orc_legionnaire 12
UPDATE npc_types SET loottable_id = :misty_orc_oracle_lt: WHERE id in (33064, 33108, 33124); # orc_oracle 8
UPDATE npc_types SET loottable_id = :misty_princess_klaknak_lt: WHERE id in (33141); # Princess_Klaknak 2
UPDATE npc_types SET loottable_id = :misty_prince_klaknak_lt: WHERE id in (33143); # Prince_Klaknak 2
UPDATE npc_types SET loottable_id = :misty_queen_klaknak_lt: WHERE id in (33136); # Queen_Klaknak 9
UPDATE npc_types SET loottable_id = :misty_relia_wastein_lt: WHERE id in (33082); # Relia_Wastein 15
UPDATE npc_types SET loottable_id = :misty_roha_jumthief_lt: WHERE id in (33095); # Roha_Jumthief 65
UPDATE npc_types SET loottable_id = :misty_rufus_lt: WHERE id in (33074, 33119); # Rufus 7
UPDATE npc_types SET loottable_id = :misty_rusbek_the_inhospitable_lt: WHERE id in (33093); # Rusbek_the_Inhospitable 11
UPDATE npc_types SET loottable_id = :misty_simeena_sukan_lt: WHERE id in (33140); # Simeena_Sukan 50
UPDATE npc_types SET loottable_id = :misty_slaythe_lt: WHERE id in (33146); # Slaythe 20
UPDATE npc_types SET loottable_id = :misty_sonsa_fromp_lt: WHERE id in (33088); # Sonsa_Fromp 25
UPDATE npc_types SET loottable_id = :misty_swish_appletop_lt: WHERE id in (33145); # Swish_Appletop 50
UPDATE npc_types SET loottable_id = :misty_tain_whistleburrow_lt: WHERE id in (33137); # Tain_Whistleburrow 50
UPDATE npc_types SET loottable_id = :misty_the_fabled_mooto_lt: WHERE id in (33157); # The_Fabled_Mooto 11
UPDATE npc_types SET loottable_id = :misty_tipa_lighten_lt: WHERE id in (33087); # Tipa_Lighten 30
UPDATE npc_types SET loottable_id = :misty_topper_drodo_lt: WHERE id in (33086); # Topper_Drodo 30
