INSERT INTO loottable(name) VALUES('misty_a_faithful_farmer'); # :misty_a_faithful_farmer_lt:
INSERT INTO loottable(name) VALUES('misty_a_ghoulish_guardian'); # :misty_a_ghoulish_guardian_lt:
INSERT INTO loottable(name) VALUES('misty_a_ravenous_werewolf'); # :misty_a_ravenous_werewolf_lt:
INSERT INTO loottable(name) VALUES('misty_a_scarecrow'); # :misty_a_scarecrow_lt:
INSERT INTO loottable(name) VALUES('misty_a_tired_farmer'); # :misty_a_tired_farmer_lt:
INSERT INTO loottable(name) VALUES('misty_a_vicious_spider'); # :misty_a_vicious_spider_lt:
INSERT INTO loottable(name) VALUES('misty_old_gourdhead'); # :misty_old_gourdhead_lt:
INSERT INTO loottable(name) VALUES('misty_orc_corpse'); # :misty_orc_corpse_lt:
INSERT INTO loottable(name) VALUES('misty_an_orc_lumberjack'); # :misty_an_orc_lumberjack_lt:
INSERT INTO loottable(name) VALUES('misty_a_bat'); # :misty_a_bat_lt:
INSERT INTO loottable(name) VALUES('misty_a_bixie'); # :misty_a_bixie_lt:
INSERT INTO loottable(name) VALUES('misty_a_bixie_drone'); # :misty_a_bixie_drone_lt:
INSERT INTO loottable(name) VALUES('misty_a_bixie_queen'); # :misty_a_bixie_queen_lt:
INSERT INTO loottable(name) VALUES('misty_a_black_bear'); # :misty_a_black_bear_lt:
INSERT INTO loottable(name) VALUES('misty_a_black_wolf'); # :misty_a_black_wolf_lt:
INSERT INTO loottable(name) VALUES('misty_a_decaying_skeleton'); # :misty_a_decaying_skeleton_lt:
INSERT INTO loottable(name) VALUES('misty_a_diseased_rat'); # :misty_a_diseased_rat_lt:
INSERT INTO loottable(name) VALUES('misty_a_fire_beetle'); # :misty_a_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('misty_a_giant_bat'); # :misty_a_giant_bat_lt:
INSERT INTO loottable(name) VALUES('misty_a_giant_fruit_bat'); # :misty_a_giant_fruit_bat_lt:
INSERT INTO loottable(name) VALUES('misty_a_giant_scarab'); # :misty_a_giant_scarab_lt:
INSERT INTO loottable(name) VALUES('misty_a_giant_thicket_rat'); # :misty_a_giant_thicket_rat_lt:
INSERT INTO loottable(name) VALUES('misty_a_giant_wood_spider'); # :misty_a_giant_wood_spider_lt:
INSERT INTO loottable(name) VALUES('misty_a_giant_yellowjacket'); # :misty_a_giant_yellowjacket_lt:
INSERT INTO loottable(name) VALUES('misty_a_goblin_alchemist'); # :misty_a_goblin_alchemist_lt:
INSERT INTO loottable(name) VALUES('misty_a_goblin_shaman'); # :misty_a_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('misty_a_goblin_warrior'); # :misty_a_goblin_warrior_lt:
INSERT INTO loottable(name) VALUES('misty_a_goblin_worker'); # :misty_a_goblin_worker_lt:
INSERT INTO loottable(name) VALUES('misty_a_halfling_skeleton'); # :misty_a_halfling_skeleton_lt:
INSERT INTO loottable(name) VALUES('misty_a_halfling_zombie'); # :misty_a_halfling_zombie_lt:
INSERT INTO loottable(name) VALUES('misty_a_klaknak_warrior'); # :misty_a_klaknak_warrior_lt:
INSERT INTO loottable(name) VALUES('misty_a_large_bat'); # :misty_a_large_bat_lt:
INSERT INTO loottable(name) VALUES('misty_a_large_fruit_bat'); # :misty_a_large_fruit_bat_lt:
INSERT INTO loottable(name) VALUES('misty_a_large_rat'); # :misty_a_large_rat_lt:
INSERT INTO loottable(name) VALUES('misty_a_large_thicket_rat'); # :misty_a_large_thicket_rat_lt:
INSERT INTO loottable(name) VALUES('misty_a_large_wood_spider'); # :misty_a_large_wood_spider_lt:
INSERT INTO loottable(name) VALUES('misty_a_large_yellowjacket'); # :misty_a_large_yellowjacket_lt:
INSERT INTO loottable(name) VALUES('misty_a_lesser_mummy'); # :misty_a_lesser_mummy_lt:
INSERT INTO loottable(name) VALUES('misty_a_mangy_rat'); # :misty_a_mangy_rat_lt:
INSERT INTO loottable(name) VALUES('misty_a_moss_snake'); # :misty_a_moss_snake_lt:
INSERT INTO loottable(name) VALUES('misty_a_shadowed_assassin'); # :misty_a_shadowed_assassin_lt:
INSERT INTO loottable(name) VALUES('misty_a_shadow_wolf'); # :misty_a_shadow_wolf_lt:
INSERT INTO loottable(name) VALUES('misty_a_skeleton'); # :misty_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('misty_a_spiderling'); # :misty_a_spiderling_lt:
INSERT INTO loottable(name) VALUES('misty_a_thorn_drakeling'); # :misty_a_thorn_drakeling_lt:
INSERT INTO loottable(name) VALUES('misty_a_tree_snake'); # :misty_a_tree_snake_lt:
INSERT INTO loottable(name) VALUES('misty_a_young_kodiak'); # :misty_a_young_kodiak_lt:
INSERT INTO loottable(name) VALUES('misty_bidils_the_quickhand'); # :misty_bidils_the_quickhand_lt:
INSERT INTO loottable(name) VALUES('misty_bim_buskin'); # :misty_bim_buskin_lt:
INSERT INTO loottable(name) VALUES('misty_blixkin_entopop'); # :misty_blixkin_entopop_lt:
INSERT INTO loottable(name) VALUES('misty_brock_brawlbottom'); # :misty_brock_brawlbottom_lt:
INSERT INTO loottable(name) VALUES('misty_bronin_higginsbot'); # :misty_bronin_higginsbot_lt:
INSERT INTO loottable(name) VALUES('misty_cozy'); # :misty_cozy_lt:
INSERT INTO loottable(name) VALUES('misty_crysta_tagglefoot'); # :misty_crysta_tagglefoot_lt:
INSERT INTO loottable(name) VALUES('misty_deputy?'); # :misty_deputy?_lt:
INSERT INTO loottable(name) VALUES('misty_deputy??'); # :misty_deputy??_lt:
INSERT INTO loottable(name) VALUES('misty_deputy???'); # :misty_deputy???_lt:
INSERT INTO loottable(name) VALUES('misty_deputy_budo'); # :misty_deputy_budo_lt:
INSERT INTO loottable(name) VALUES('misty_deputy_drebo'); # :misty_deputy_drebo_lt:
INSERT INTO loottable(name) VALUES('misty_deputy_eigon'); # :misty_deputy_eigon_lt:
INSERT INTO loottable(name) VALUES('misty_deputy_felp'); # :misty_deputy_felp_lt:
INSERT INTO loottable(name) VALUES('misty_deputy_keld'); # :misty_deputy_keld_lt:
INSERT INTO loottable(name) VALUES('misty_deputy_looh'); # :misty_deputy_looh_lt:
INSERT INTO loottable(name) VALUES('misty_deputy_poolt'); # :misty_deputy_poolt_lt:
INSERT INTO loottable(name) VALUES('misty_deputy_tagil'); # :misty_deputy_tagil_lt:
INSERT INTO loottable(name) VALUES('misty_deputy_vastin'); # :misty_deputy_vastin_lt:
INSERT INTO loottable(name) VALUES('misty_ella_foodcrafter'); # :misty_ella_foodcrafter_lt:
INSERT INTO loottable(name) VALUES('misty_ember'); # :misty_ember_lt:
INSERT INTO loottable(name) VALUES('misty_epicurean_halfling'); # :misty_epicurean_halfling_lt:
INSERT INTO loottable(name) VALUES('misty_faano_windmaker'); # :misty_faano_windmaker_lt:
INSERT INTO loottable(name) VALUES('misty_fajio_knejo'); # :misty_fajio_knejo_lt:
INSERT INTO loottable(name) VALUES('misty_felawen_kellthoo'); # :misty_felawen_kellthoo_lt:
INSERT INTO loottable(name) VALUES('misty_ferrigon_hepplebottom'); # :misty_ferrigon_hepplebottom_lt:
INSERT INTO loottable(name) VALUES('misty_gunrich'); # :misty_gunrich_lt:
INSERT INTO loottable(name) VALUES('misty_hanga_wiskin'); # :misty_hanga_wiskin_lt:
INSERT INTO loottable(name) VALUES('misty_joogl_honeybugger'); # :misty_joogl_honeybugger_lt:
INSERT INTO loottable(name) VALUES('misty_lil_honeybugger'); # :misty_lil_honeybugger_lt:
INSERT INTO loottable(name) VALUES('misty_mooto'); # :misty_mooto_lt:
INSERT INTO loottable(name) VALUES('misty_orc_apprentice'); # :misty_orc_apprentice_lt:
INSERT INTO loottable(name) VALUES('misty_orc_centurion'); # :misty_orc_centurion_lt:
INSERT INTO loottable(name) VALUES('misty_orc_legionnaire'); # :misty_orc_legionnaire_lt:
INSERT INTO loottable(name) VALUES('misty_orc_oracle'); # :misty_orc_oracle_lt:
INSERT INTO loottable(name) VALUES('misty_princess_klaknak'); # :misty_princess_klaknak_lt:
INSERT INTO loottable(name) VALUES('misty_prince_klaknak'); # :misty_prince_klaknak_lt:
INSERT INTO loottable(name) VALUES('misty_queen_klaknak'); # :misty_queen_klaknak_lt:
INSERT INTO loottable(name) VALUES('misty_relia_wastein'); # :misty_relia_wastein_lt:
INSERT INTO loottable(name) VALUES('misty_roha_jumthief'); # :misty_roha_jumthief_lt:
INSERT INTO loottable(name) VALUES('misty_rufus'); # :misty_rufus_lt:
INSERT INTO loottable(name) VALUES('misty_rusbek_the_inhospitable'); # :misty_rusbek_the_inhospitable_lt:
INSERT INTO loottable(name) VALUES('misty_simeena_sukan'); # :misty_simeena_sukan_lt:
INSERT INTO loottable(name) VALUES('misty_slaythe'); # :misty_slaythe_lt:
INSERT INTO loottable(name) VALUES('misty_sonsa_fromp'); # :misty_sonsa_fromp_lt:
INSERT INTO loottable(name) VALUES('misty_swish_appletop'); # :misty_swish_appletop_lt:
INSERT INTO loottable(name) VALUES('misty_tain_whistleburrow'); # :misty_tain_whistleburrow_lt:
INSERT INTO loottable(name) VALUES('misty_the_fabled_mooto'); # :misty_the_fabled_mooto_lt:
INSERT INTO loottable(name) VALUES('misty_tipa_lighten'); # :misty_tipa_lighten_lt:
INSERT INTO loottable(name) VALUES('misty_topper_drodo'); # :misty_topper_drodo_lt:
