UPDATE npc_types SET loottable_id = :nektulos_checkpoint_ten_lt: WHERE id in (25437); # #checkpoint_ten 99
UPDATE npc_types SET loottable_id = :nektulos_coldwind_blackfoot_lt: WHERE id in (25414); # #Coldwind_Blackfoot 72
UPDATE npc_types SET loottable_id = :nektulos_first_fragment_of_igok_lt: WHERE id in (25057); # #First_Fragment_of_Igok 5
UPDATE npc_types SET loottable_id = :nektulos_an_araneidae_spiderling_lt: WHERE id in (25310); # an_araneidae_spiderling 1
UPDATE npc_types SET loottable_id = :nektulos_an_arcane_elementalist_lt: WHERE id in (25362); # An_Arcane_Elementalist 6
UPDATE npc_types SET loottable_id = :nektulos_an_arcane_incantator_lt: WHERE id in (25369); # An_Arcane_Incantator 2
UPDATE npc_types SET loottable_id = :nektulos_an_arcane_shapeshifter_lt: WHERE id in (25372); # An_Arcane_Shapeshifter 8
UPDATE npc_types SET loottable_id = :nektulos_an_ash_drakeling_lt: WHERE id in (25312); # an_ash_drakeling 3
UPDATE npc_types SET loottable_id = :nektulos_an_invis_placeholder_lt: WHERE id in (25361); # an_invis_placeholder 1
UPDATE npc_types SET loottable_id = :nektulos_an_undead_annalkeeper_lt: WHERE id in (25124); # An_Undead_Annalkeeper 10
UPDATE npc_types SET loottable_id = :nektulos_an_undead_steward_lt: WHERE id in (25023); # An_Undead_Steward 10
UPDATE npc_types SET loottable_id = :nektulos_a_basilisk_hatchling_lt: WHERE id in (25326); # a_basilisk_hatchling 8
UPDATE npc_types SET loottable_id = :nektulos_a_black_bear_lt: WHERE id in (25327); # a_black_bear 3
UPDATE npc_types SET loottable_id = :nektulos_a_black_mamba_lt: WHERE id in (25333); # a_black_mamba 7
UPDATE npc_types SET loottable_id = :nektulos_a_black_wolf_lt: WHERE id in (25311); # a_black_wolf 1
UPDATE npc_types SET loottable_id = :nektulos_a_calcified_skeleton_lt: WHERE id in (25358); # a_calcified_skeleton 5
UPDATE npc_types SET loottable_id = :nektulos_a_crushbone_thaumaturge_lt: WHERE id in (25408); # a_Crushbone_thaumaturge 15
UPDATE npc_types SET loottable_id = :nektulos_a_darkwater_piranha_lt: WHERE id in (25102); # a_darkwater_piranha 14
UPDATE npc_types SET loottable_id = :nektulos_a_dark_spirit_of_nektulos_lt: WHERE id in (25429); # a_dark_spirit_of_Nektulos 50
UPDATE npc_types SET loottable_id = :nektulos_a_deathfist_legionnaire_lt: WHERE id in (25368, 25379, 25010, 25038, 25062); # a_Deathfist_legionnaire 7
UPDATE npc_types SET loottable_id = :nektulos_a_deathfist_scout_lt: WHERE id in (25116, 25396, 25013); # a_deathfist_scout 4
UPDATE npc_types SET loottable_id = :nektulos_a_deathfist_templar_lt: WHERE id in (25387, 25039, 25061); # a_deathfist_templar 8
UPDATE npc_types SET loottable_id = :nektulos_a_decaying_councilman_lt: WHERE id in (25346); # a_decaying_councilman 9
UPDATE npc_types SET loottable_id = :nektulos_a_decaying_initiate_lt: WHERE id in (25354); # a_decaying_initiate 7
UPDATE npc_types SET loottable_id = :nektulos_a_decaying_skeleton_lt: WHERE id in (25322); # a_decaying_skeleton 1
UPDATE npc_types SET loottable_id = :nektulos_a_deep_forest_spider_lt: WHERE id in (25407); # a_Deep_Forest_Spider 13
UPDATE npc_types SET loottable_id = :nektulos_a_garter_snake_lt: WHERE id in (25316); # a_garter_snake 1
UPDATE npc_types SET loottable_id = :nektulos_a_giant_widow_lt: WHERE id in (25424); # a_giant_widow 14
UPDATE npc_types SET loottable_id = :nektulos_a_greater_skeleton_lt: WHERE id in (25355); # a_greater_skeleton 7
UPDATE npc_types SET loottable_id = :nektulos_a_greater_wisp_lt: WHERE id in (25413); # a_greater_wisp 11
UPDATE npc_types SET loottable_id = :nektulos_a_halfling_skeleton_lt: WHERE id in (25044, 25058); # a_halfling_skeleton 4
UPDATE npc_types SET loottable_id = :nektulos_a_large_araneidae_lt: WHERE id in (25329); # a_large_araneidae 2
UPDATE npc_types SET loottable_id = :nektulos_a_large_forest_crawler_lt: WHERE id in (25416); # a_Large_Forest_Crawler 10
UPDATE npc_types SET loottable_id = :nektulos_a_large_piranha_lt: WHERE id in (25397); # a_large_piranha 10
UPDATE npc_types SET loottable_id = :nektulos_a_lesser_mummy_lt: WHERE id in (25048); # a_lesser_mummy 10
UPDATE npc_types SET loottable_id = :nektulos_a_moss_snake_lt: WHERE id in (25314); # a_moss_snake 1
UPDATE npc_types SET loottable_id = :nektulos_a_nektulos_widow_lt: WHERE id in (25417); # a_Nektulos_widow 11
UPDATE npc_types SET loottable_id = :nektulos_a_pyre_beetle_lt: WHERE id in (25315); # a_pyre_beetle 2
UPDATE npc_types SET loottable_id = :nektulos_a_rotting_citizen_lt: WHERE id in (25353); # a_rotting_citizen 7
UPDATE npc_types SET loottable_id = :nektulos_a_rotting_initiate_lt: WHERE id in (25323); # a_rotting_initiate 7
UPDATE npc_types SET loottable_id = :nektulos_a_shadowed_man_lt: WHERE id in (25428, 25430, 25431); # a_shadowed_man 24
UPDATE npc_types SET loottable_id = :nektulos_a_shadow_wolf_lt: WHERE id in (25339); # a_shadow_wolf 3
UPDATE npc_types SET loottable_id = :nektulos_a_skeleton_lt: WHERE id in (25325); # a_skeleton 4
UPDATE npc_types SET loottable_id = :nektulos_a_spider_cocoon_cluster_lt: WHERE id in (25410); # a_spider_cocoon_cluster 3
UPDATE npc_types SET loottable_id = :nektulos_a_tree_snake_lt: WHERE id in (25328); # a_tree_snake 4
UPDATE npc_types SET loottable_id = :nektulos_a_willowisp_lt: WHERE id in (25342); # a_willowisp 9
UPDATE npc_types SET loottable_id = :nektulos_a_young_kodiak_lt: WHERE id in (25120, 25122); # a_young_kodiak 9
UPDATE npc_types SET loottable_id = :nektulos_a_zombie_lt: WHERE id in (25432); # a_zombie 8
UPDATE npc_types SET loottable_id = :nektulos_bink_lt: WHERE id in (25138); # Bink 6
UPDATE npc_types SET loottable_id = :nektulos_blugurg_lt: WHERE id in (25098); # Blugurg 40
UPDATE npc_types SET loottable_id = :nektulos_brizzawn_villifar_lt: WHERE id in (25107); # Brizzawn_Villifar 50
UPDATE npc_types SET loottable_id = :nektulos_captain_nfarre_lt: WHERE id in (25026); # Captain_N`Farre 50
UPDATE npc_types SET loottable_id = :nektulos_corporal_dabth_lt: WHERE id in (25123); # Corporal_D`Abth 21
UPDATE npc_types SET loottable_id = :nektulos_corporal_xhorn_lt: WHERE id in (25125); # Corporal_X`Horn 22
UPDATE npc_types SET loottable_id = :nektulos_disciple_of_rodcet_lt: WHERE id in (25374); # Disciple_of_Rodcet 4
UPDATE npc_types SET loottable_id = :nektulos_droogo_gron_lt: WHERE id in (25104); # Droogo_Gron 50
UPDATE npc_types SET loottable_id = :nektulos_farand_sliver_lt: WHERE id in (25106); # Farand_Sliver 50
UPDATE npc_types SET loottable_id = :nektulos_foley_lt: WHERE id in (25140); # Foley 7
UPDATE npc_types SET loottable_id = :nektulos_forley_lt: WHERE id in (25421); # Forley 7
UPDATE npc_types SET loottable_id = :nektulos_glob_lt: WHERE id in (25110); # Glob 60
UPDATE npc_types SET loottable_id = :nektulos_gollee_lt: WHERE id in (25089); # Gollee 7
UPDATE npc_types SET loottable_id = :nektulos_grom_shives_lt: WHERE id in (25436); # Grom_Shives 50
UPDATE npc_types SET loottable_id = :nektulos_guard_ebrona_lt: WHERE id in (25401); # Guard_E`Brona 17
UPDATE npc_types SET loottable_id = :nektulos_guard_etru_lt: WHERE id in (25142); # Guard_E`tru 50
UPDATE npc_types SET loottable_id = :nektulos_guard_gvarr_lt: WHERE id in (25050); # Guard_Gvarr 16
UPDATE npc_types SET loottable_id = :nektulos_guard_nlan_lt: WHERE id in (25406); # Guard_N`Lan 15
UPDATE npc_types SET loottable_id = :nektulos_guard_tquetal_lt: WHERE id in (25117, 25055); # Guard_T`Quetal 15
UPDATE npc_types SET loottable_id = :nektulos_guard_vlex_lt: WHERE id in (25119, 25036); # Guard_V`Lex 16
UPDATE npc_types SET loottable_id = :nektulos_guard_xonnu_lt: WHERE id in (25405); # Guard_X`Onnu 15
UPDATE npc_types SET loottable_id = :nektulos_guard_zden_lt: WHERE id in (25349); # Guard_Z`Den 13
UPDATE npc_types SET loottable_id = :nektulos_hamer_lt: WHERE id in (25423); # Hamer 7
UPDATE npc_types SET loottable_id = :nektulos_hetha_vsyph_lt: WHERE id in (25112); # Hetha_V`Syph 15
UPDATE npc_types SET loottable_id = :nektulos_high_chief_deroslan_lt: WHERE id in (25144); # High_Chief_Deroslan 12
UPDATE npc_types SET loottable_id = :nektulos_high_chief_ferilsars_lt: WHERE id in (25145); # High_Chief_Ferilsars 13
UPDATE npc_types SET loottable_id = :nektulos_high_chief_wasolors_lt: WHERE id in (25146); # High_Chief_Wasolors 12
UPDATE npc_types SET loottable_id = :nektulos_himmel_lt: WHERE id in (25079); # Himmel 7
UPDATE npc_types SET loottable_id = :nektulos_initiate_abber_lt: WHERE id in (25395); # Initiate_Abber 5
UPDATE npc_types SET loottable_id = :nektulos_initiate_guanin_lt: WHERE id in (25389, 25439); # Initiate_Guanin 8
UPDATE npc_types SET loottable_id = :nektulos_initiate_hart_lt: WHERE id in (25096, 25384); # Initiate_Hart 5
UPDATE npc_types SET loottable_id = :nektulos_initiate_of_rodcet_lt: WHERE id in (25375); # Initiate_of_Rodcet 3
UPDATE npc_types SET loottable_id = :nektulos_initiate_pool_lt: WHERE id in (25135, 25391); # Initiate_Pool 7
UPDATE npc_types SET loottable_id = :nektulos_initiate_rambel_lt: WHERE id in (25095, 25394); # Initiate_Rambel 5
UPDATE npc_types SET loottable_id = :nektulos_initiate_umbra_lt: WHERE id in (25088, 25136, 25393); # Initiate_Umbra 9
UPDATE npc_types SET loottable_id = :nektulos_jossle_lt: WHERE id in (25139, 25080); # Jossle 6
UPDATE npc_types SET loottable_id = :nektulos_kamidra_voragone_lt: WHERE id in (25105); # Kamidra_Voragone 50
UPDATE npc_types SET loottable_id = :nektulos_kinliat_bloodwalker_lt: WHERE id in (25111); # Kinliat_Bloodwalker 40
UPDATE npc_types SET loottable_id = :nektulos_kirak_vil_lt: WHERE id in (25301); # Kirak_Vil 56
UPDATE npc_types SET loottable_id = :nektulos_klimmer_lt: WHERE id in (25090, 25137); # Klimmer 11
UPDATE npc_types SET loottable_id = :nektulos_leatherfoot_captain_lt: WHERE id in (25352, 25099); # Leatherfoot_Captain 10
UPDATE npc_types SET loottable_id = :nektulos_leatherfoot_corporal_lt: WHERE id in (25084, 25085, 25343); # Leatherfoot_Corporal 3
UPDATE npc_types SET loottable_id = :nektulos_leatherfoot_deputy_lt: WHERE id in (25390, 25143); # Leatherfoot_Deputy 30
UPDATE npc_types SET loottable_id = :nektulos_leatherfoot_medic_lt: WHERE id in (25087); # Leatherfoot_medic 20
UPDATE npc_types SET loottable_id = :nektulos_leatherfoot_scout_lt: WHERE id in (25077, 25082, 25083, 25341); # Leatherfoot_Scout 1
UPDATE npc_types SET loottable_id = :nektulos_leatherfoot_sergeant_lt: WHERE id in (25351, 25128, 25081); # Leatherfoot_Sergeant 8
UPDATE npc_types SET loottable_id = :nektulos_master_whoopal_lt: WHERE id in (25130, 25392); # Master_Whoopal 13
UPDATE npc_types SET loottable_id = :nektulos_missionary_of_rodcet_lt: WHERE id in (25371); # Missionary_of_Rodcet 8
UPDATE npc_types SET loottable_id = :nektulos_neophyte_edel_lt: WHERE id in (25141); # Neophyte_Edel 4
UPDATE npc_types SET loottable_id = :nektulos_neophyte_halle_lt: WHERE id in (25114); # Neophyte_Halle 4
UPDATE npc_types SET loottable_id = :nektulos_neophyte_hazel_lt: WHERE id in (25094); # Neophyte_Hazel 4
UPDATE npc_types SET loottable_id = :nektulos_nkamba_fleshblade_lt: WHERE id in (25103); # Nkamba_Fleshblade 50
UPDATE npc_types SET loottable_id = :nektulos_orc_runner_lt: WHERE id in (25438); # orc_runner 7
UPDATE npc_types SET loottable_id = :nektulos_quester_dunden_lt: WHERE id in (25065); # Quester_Dunden 9
UPDATE npc_types SET loottable_id = :nektulos_quester_hannil_lt: WHERE id in (25086); # Quester_Hannil 10
UPDATE npc_types SET loottable_id = :nektulos_quester_hannin_lt: WHERE id in (25092); # Quester_Hannin 9
UPDATE npc_types SET loottable_id = :nektulos_rollis_lt: WHERE id in (25131); # Rollis 8
UPDATE npc_types SET loottable_id = :nektulos_sergeant_corm_lt: WHERE id in (25115); # Sergeant_C`Orm 50
UPDATE npc_types SET loottable_id = :nektulos_sergeant_jnarus_lt: WHERE id in (25019); # Sergeant_J`Narus 24
UPDATE npc_types SET loottable_id = :nektulos_slarin_kvekn_lt: WHERE id in (25101); # Slarin_K`Vekn 15
UPDATE npc_types SET loottable_id = :nektulos_snitch_lt: WHERE id in (25091); # Snitch 9
UPDATE npc_types SET loottable_id = :nektulos_the_ashen_ground_lt: WHERE id in (25363); # The_ashen_ground 1
UPDATE npc_types SET loottable_id = :nektulos_travis_two_tone_lt: WHERE id in (25063); # Travis_Two_Tone 25
UPDATE npc_types SET loottable_id = :nektulos_venenzi_oberzendi_lt: WHERE id in (25113); # Venenzi_Oberzendi 50
UPDATE npc_types SET loottable_id = :nektulos_vol_tvke_lt: WHERE id in (25109); # Vol_T`Vke 60
UPDATE npc_types SET loottable_id = :nektulos___lt: WHERE id in (25435); # _ 99
