INSERT INTO loottable(name) VALUES('oggok_bordag'); # :oggok_bordag_lt:
INSERT INTO loottable(name) VALUES('oggok_ambassador_kryn'); # :oggok_ambassador_kryn_lt:
INSERT INTO loottable(name) VALUES('oggok_angrog'); # :oggok_angrog_lt:
INSERT INTO loottable(name) VALUES('oggok_an_armadillo'); # :oggok_an_armadillo_lt:
INSERT INTO loottable(name) VALUES('oggok_a_frostfell_goblin'); # :oggok_a_frostfell_goblin_lt:
INSERT INTO loottable(name) VALUES('oggok_a_young_armadillo'); # :oggok_a_young_armadillo_lt:
INSERT INTO loottable(name) VALUES('oggok_baddi_waca'); # :oggok_baddi_waca_lt:
INSERT INTO loottable(name) VALUES('oggok_bakrishal'); # :oggok_bakrishal_lt:
INSERT INTO loottable(name) VALUES('oggok_barsk'); # :oggok_barsk_lt:
INSERT INTO loottable(name) VALUES('oggok_betabstgmspawner'); # :oggok_betabstgmspawner_lt:
INSERT INTO loottable(name) VALUES('oggok_blergerda'); # :oggok_blergerda_lt:
INSERT INTO loottable(name) VALUES('oggok_bonlarg'); # :oggok_bonlarg_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_bak'); # :oggok_bouncer_bak_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_druk'); # :oggok_bouncer_druk_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_gronk'); # :oggok_bouncer_gronk_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_haraan'); # :oggok_bouncer_haraan_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_krik'); # :oggok_bouncer_krik_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_mrang'); # :oggok_bouncer_mrang_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_praag'); # :oggok_bouncer_praag_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_raan'); # :oggok_bouncer_raan_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_scaar'); # :oggok_bouncer_scaar_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_skon'); # :oggok_bouncer_skon_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_skuk'); # :oggok_bouncer_skuk_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_tazak'); # :oggok_bouncer_tazak_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_thrang'); # :oggok_bouncer_thrang_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_wrok'); # :oggok_bouncer_wrok_lt:
INSERT INTO loottable(name) VALUES('oggok_bouncer_xak'); # :oggok_bouncer_xak_lt:
INSERT INTO loottable(name) VALUES('oggok_bozlum_blossom'); # :oggok_bozlum_blossom_lt:
INSERT INTO loottable(name) VALUES('oggok_bozlum_blossom_pet'); # :oggok_bozlum_blossom_pet_lt:
INSERT INTO loottable(name) VALUES('oggok_brana'); # :oggok_brana_lt:
INSERT INTO loottable(name) VALUES('oggok_brogdog'); # :oggok_brogdog_lt:
INSERT INTO loottable(name) VALUES('oggok_brokk_boxtripper'); # :oggok_brokk_boxtripper_lt:
INSERT INTO loottable(name) VALUES('oggok_bubbgrib'); # :oggok_bubbgrib_lt:
INSERT INTO loottable(name) VALUES('oggok_chamt'); # :oggok_chamt_lt:
INSERT INTO loottable(name) VALUES('oggok_chef_dooga'); # :oggok_chef_dooga_lt:
INSERT INTO loottable(name) VALUES('oggok_cikoona'); # :oggok_cikoona_lt:
INSERT INTO loottable(name) VALUES('oggok_clurg'); # :oggok_clurg_lt:
INSERT INTO loottable(name) VALUES('oggok_cralk'); # :oggok_cralk_lt:
INSERT INTO loottable(name) VALUES('oggok_crilt'); # :oggok_crilt_lt:
INSERT INTO loottable(name) VALUES('oggok_crunga'); # :oggok_crunga_lt:
INSERT INTO loottable(name) VALUES('oggok_duuga_tearstopper'); # :oggok_duuga_tearstopper_lt:
INSERT INTO loottable(name) VALUES('oggok_emissary_glib'); # :oggok_emissary_glib_lt:
INSERT INTO loottable(name) VALUES('oggok_erung'); # :oggok_erung_lt:
INSERT INTO loottable(name) VALUES('oggok_exterminator_glurg'); # :oggok_exterminator_glurg_lt:
INSERT INTO loottable(name) VALUES('oggok_fireworks_engineer_fabdabus'); # :oggok_fireworks_engineer_fabdabus_lt:
INSERT INTO loottable(name) VALUES('oggok_fuga'); # :oggok_fuga_lt:
INSERT INTO loottable(name) VALUES('oggok_garakbar'); # :oggok_garakbar_lt:
INSERT INTO loottable(name) VALUES('oggok_goobast'); # :oggok_goobast_lt:
INSERT INTO loottable(name) VALUES('oggok_gralbug'); # :oggok_gralbug_lt:
INSERT INTO loottable(name) VALUES('oggok_grapok'); # :oggok_grapok_lt:
INSERT INTO loottable(name) VALUES('oggok_gretamog'); # :oggok_gretamog_lt:
INSERT INTO loottable(name) VALUES('oggok_grevak'); # :oggok_grevak_lt:
INSERT INTO loottable(name) VALUES('oggok_gronk'); # :oggok_gronk_lt:
INSERT INTO loottable(name) VALUES('oggok_grop'); # :oggok_grop_lt:
INSERT INTO loottable(name) VALUES('oggok_guntrik'); # :oggok_guntrik_lt:
INSERT INTO loottable(name) VALUES('oggok_hargar_the_velium_chef'); # :oggok_hargar_the_velium_chef_lt:
INSERT INTO loottable(name) VALUES('oggok_helgara_dirtcarver'); # :oggok_helgara_dirtcarver_lt:
INSERT INTO loottable(name) VALUES('oggok_hoart'); # :oggok_hoart_lt:
INSERT INTO loottable(name) VALUES('oggok_horgus'); # :oggok_horgus_lt:
INSERT INTO loottable(name) VALUES('oggok_hrak'); # :oggok_hrak_lt:
INSERT INTO loottable(name) VALUES('oggok_iksob_darkchaser'); # :oggok_iksob_darkchaser_lt:
INSERT INTO loottable(name) VALUES('oggok_jargo'); # :oggok_jargo_lt:
INSERT INTO loottable(name) VALUES('oggok_juk_hidebeater'); # :oggok_juk_hidebeater_lt:
INSERT INTO loottable(name) VALUES('oggok_kerplooe_dirtcarver'); # :oggok_kerplooe_dirtcarver_lt:
INSERT INTO loottable(name) VALUES('oggok_kizrak_the_tyrant'); # :oggok_kizrak_the_tyrant_lt:
INSERT INTO loottable(name) VALUES('oggok_klob_pulp'); # :oggok_klob_pulp_lt:
INSERT INTO loottable(name) VALUES('oggok_kogna'); # :oggok_kogna_lt:
INSERT INTO loottable(name) VALUES('oggok_korff'); # :oggok_korff_lt:
INSERT INTO loottable(name) VALUES('oggok_korgarg_swillchugger'); # :oggok_korgarg_swillchugger_lt:
INSERT INTO loottable(name) VALUES('oggok_kramf'); # :oggok_kramf_lt:
INSERT INTO loottable(name) VALUES('oggok_kulver'); # :oggok_kulver_lt:
INSERT INTO loottable(name) VALUES('oggok_lopuka'); # :oggok_lopuka_lt:
INSERT INTO loottable(name) VALUES('oggok_lork'); # :oggok_lork_lt:
INSERT INTO loottable(name) VALUES('oggok_marda'); # :oggok_marda_lt:
INSERT INTO loottable(name) VALUES('oggok_mooglan'); # :oggok_mooglan_lt:
INSERT INTO loottable(name) VALUES('oggok_murak'); # :oggok_murak_lt:
INSERT INTO loottable(name) VALUES('oggok_ogomok'); # :oggok_ogomok_lt:
INSERT INTO loottable(name) VALUES('oggok_pordopa'); # :oggok_pordopa_lt:
INSERT INTO loottable(name) VALUES('oggok_praak'); # :oggok_praak_lt:
INSERT INTO loottable(name) VALUES('oggok_priest_of_discord'); # :oggok_priest_of_discord_lt:
INSERT INTO loottable(name) VALUES('oggok_puglala'); # :oggok_puglala_lt:
INSERT INTO loottable(name) VALUES('oggok_puwdap'); # :oggok_puwdap_lt:
INSERT INTO loottable(name) VALUES('oggok_rognok'); # :oggok_rognok_lt:
INSERT INTO loottable(name) VALUES('oggok_rora_dirtstamp'); # :oggok_rora_dirtstamp_lt:
INSERT INTO loottable(name) VALUES('oggok_ruksa'); # :oggok_ruksa_lt:
INSERT INTO loottable(name) VALUES('oggok_santug_claugg'); # :oggok_santug_claugg_lt:
INSERT INTO loottable(name) VALUES('oggok_sheerie_oglarum'); # :oggok_sheerie_oglarum_lt:
INSERT INTO loottable(name) VALUES('oggok_sinsaal'); # :oggok_sinsaal_lt:
INSERT INTO loottable(name) VALUES('oggok_snarg_bonesmacker'); # :oggok_snarg_bonesmacker_lt:
INSERT INTO loottable(name) VALUES('oggok_soonog'); # :oggok_soonog_lt:
INSERT INTO loottable(name) VALUES('oggok_soulbinder_trurg'); # :oggok_soulbinder_trurg_lt:
INSERT INTO loottable(name) VALUES('oggok_squeea'); # :oggok_squeea_lt:
INSERT INTO loottable(name) VALUES('oggok_tokun'); # :oggok_tokun_lt:
INSERT INTO loottable(name) VALUES('oggok_trusk'); # :oggok_trusk_lt:
INSERT INTO loottable(name) VALUES('oggok_ungral_silverstomp'); # :oggok_ungral_silverstomp_lt:
INSERT INTO loottable(name) VALUES('oggok_uoola'); # :oggok_uoola_lt:
INSERT INTO loottable(name) VALUES('oggok_varrok_neckchopper'); # :oggok_varrok_neckchopper_lt:
INSERT INTO loottable(name) VALUES('oggok_zarg_knightbane'); # :oggok_zarg_knightbane_lt:
INSERT INTO loottable(name) VALUES('oggok_zulort'); # :oggok_zulort_lt:
