# INSERT INTO loottable_entries(probability, loottable_id, lootdrop_id, drop_limit, mindrop) VALUES (100, :todo_lt:, :todo_ld:, 1, 1);
(1, :oggok_bouncer_skuk_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_mrang_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_gronk_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_thrang_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_haraan_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_praag_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_wrok_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_scaar_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_xak_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_skon_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_druk_lt:, :fine_steel_ld:),
(1, :oggok_exterminator_glurg_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_bak_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_tazak_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_raan_lt:, :fine_steel_ld:),
(1, :oggok_bouncer_krik_lt:, :fine_steel_ld:),
