UPDATE npc_types SET loottable_id = :oot_a_corrupted_koalindl_lt: WHERE id in (69141); # #A_Corrupted_Koalindl 60
UPDATE npc_types SET loottable_id = :oot_kaiaren_lt: WHERE id in (69152); # #Kaiaren 75
UPDATE npc_types SET loottable_id = :oot_marrey_mcgrannel_lt: WHERE id in (69137); # #Marrey_McGrannel 65
UPDATE npc_types SET loottable_id = :oot_translocator_narrik_lt: WHERE id in (69088); # #Translocator_Narrik 1
UPDATE npc_types SET loottable_id = :oot_allizewsaur_lt: WHERE id in (69018); # Allizewsaur 50
UPDATE npc_types SET loottable_id = :oot_antinime_lt: WHERE id in (69026); # Antinime 23
UPDATE npc_types SET loottable_id = :oot_an_alluring_siren_lt: WHERE id in (69011, 69016); # an_alluring_siren 13
UPDATE npc_types SET loottable_id = :oot_an_ancient_cyclops_lt: WHERE id in (69150); # an_ancient_cyclops 41
UPDATE npc_types SET loottable_id = :oot_an_aqua_goblin_lt: WHERE id in (69001, 69003, 69009, 69012, 69035); # an_aqua_goblin 9
UPDATE npc_types SET loottable_id = :oot_an_aviak_quetzel_lt: WHERE id in (69057, 69071, 69112); # an_aviak_quetzel 22
UPDATE npc_types SET loottable_id = :oot_an_aviak_starling_lt: WHERE id in (69055, 69056, 69072); # an_aviak_starling 11
UPDATE npc_types SET loottable_id = :oot_an_aviak_tanager_lt: WHERE id in (69076, 69113); # an_aviak_tanager 17
UPDATE npc_types SET loottable_id = :oot_an_aviak_turaco_lt: WHERE id in (69037, 69070); # an_aviak_turaco 13
UPDATE npc_types SET loottable_id = :oot_an_island_goblin_headhunte_lt: WHERE id in (69145); # an_island_goblin_headhunte 23
UPDATE npc_types SET loottable_id = :oot_an_island_goblin_headhunter_lt: WHERE id in (69027); # an_island_goblin_headhunter 23
UPDATE npc_types SET loottable_id = :oot_an_isle_goblin_lt: WHERE id in (69029, 69036, 69046, 69052, 69058, 69108); # an_isle_goblin 16
UPDATE npc_types SET loottable_id = :oot_an_isle_goblin_headhunter_lt: WHERE id in (69045); # an_isle_goblin_headhunter 22
UPDATE npc_types SET loottable_id = :oot_an_isle_goblin_shaman_lt: WHERE id in (69028, 69038, 69059); # an_isle_goblin_shaman 11
UPDATE npc_types SET loottable_id = :oot_an_isle_goblin_warrior_lt: WHERE id in (69103, 69104, 69114); # an_isle_goblin_warrior 22
UPDATE npc_types SET loottable_id = :oot_an_isle_goblin_wizard_lt: WHERE id in (69047, 69117); # an_isle_goblin_wizard 16
UPDATE npc_types SET loottable_id = :oot_aqua_goblin_sacrifice_lt: WHERE id in (69095); # aqua_goblin_sacrifice 9
UPDATE npc_types SET loottable_id = :oot_ascania_halvbin_lt: WHERE id in (69015); # Ascania_Halvbin 24
UPDATE npc_types SET loottable_id = :oot_assistant_jeyular_lt: WHERE id in (69087); # Assistant_Jeyular 25
UPDATE npc_types SET loottable_id = :oot_a_boat_lt: WHERE id in (69063); # a_boat 50
UPDATE npc_types SET loottable_id = :oot_a_buccaneer_lt: WHERE id in (69007, 69097); # a_buccaneer 27
UPDATE npc_types SET loottable_id = :oot_a_cyclops_lt: WHERE id in (69126, 69128, 69006); # a_cyclops 42
UPDATE npc_types SET loottable_id = :oot_a_flighty_catfish_lt: WHERE id in (69151); # a_flighty_catfish 20
UPDATE npc_types SET loottable_id = :oot_a_gargoyle_lt: WHERE id in (69123); # a_gargoyle 19
UPDATE npc_types SET loottable_id = :oot_a_goblin_headmaster_lt: WHERE id in (69102, 69107); # a_goblin_headmaster 25
UPDATE npc_types SET loottable_id = :oot_a_greater_skeleton_lt: WHERE id in (69031, 69032, 69033); # a_greater_skeleton 13
UPDATE npc_types SET loottable_id = :oot_a_lesser_spirit_lt: WHERE id in (69149); # a_lesser_spirit 1
UPDATE npc_types SET loottable_id = :oot_a_pirate_lt: WHERE id in (69147); # a_pirate 22
UPDATE npc_types SET loottable_id = :oot_a_reef_shark_lt: WHERE id in (69054, 69065, 69066); # a_reef_shark 4
UPDATE npc_types SET loottable_id = :oot_a_seafury_cyclops_lt: WHERE id in (69000, 69004, 69013, 69089, 69091); # a_seafury_cyclops 40
UPDATE npc_types SET loottable_id = :oot_a_shark_lt: WHERE id in (69021, 69067, 69068, 69069); # a_shark 13
UPDATE npc_types SET loottable_id = :oot_a_spectre_lt: WHERE id in (69039, 69040, 69041, 69099, 69115); # a_spectre 37
UPDATE npc_types SET loottable_id = :oot_boog_mudtoe_lt: WHERE id in (69090); # Boog_Mudtoe 18
UPDATE npc_types SET loottable_id = :oot_brawn_lt: WHERE id in (69120); # Brawn 22
UPDATE npc_types SET loottable_id = :oot_breecyll_skene__lt: WHERE id in (69133); # Breecyll_Skene_ 50
UPDATE npc_types SET loottable_id = :oot_capt_surestout_lt: WHERE id in (69130, 69023, 69100); # Capt_Surestout 18
UPDATE npc_types SET loottable_id = :oot_cleonae_kalen_lt: WHERE id in (69075, 69110); # Cleonae_Kalen 26
UPDATE npc_types SET loottable_id = :oot_corrupted_seafury_cyclops_lt: WHERE id in (69142); # corrupted_seafury_cyclops 52
UPDATE npc_types SET loottable_id = :oot_craven_jonsbrow_lt: WHERE id in (69077); # Craven_Jonsbrow 25
UPDATE npc_types SET loottable_id = :oot_dayle_jornin_lt: WHERE id in (69124); # Dayle_Jornin 14
UPDATE npc_types SET loottable_id = :oot_denken_strongpick_lt: WHERE id in (69061); # Denken_Strongpick 55
UPDATE npc_types SET loottable_id = :oot_dixl_drool_lt: WHERE id in (69024); # Dixl_Drool 20
UPDATE npc_types SET loottable_id = :oot_donoven_blurr_lt: WHERE id in (69081); # Donoven_Blurr 25
UPDATE npc_types SET loottable_id = :oot_doran_vargnus_lt: WHERE id in (69074); # Doran_Vargnus 45
UPDATE npc_types SET loottable_id = :oot_dragoon_artellin_lt: WHERE id in (69119); # Dragoon_Artellin 21
UPDATE npc_types SET loottable_id = :oot_dragoon_darl_lt: WHERE id in (69118); # Dragoon_Darl 20
UPDATE npc_types SET loottable_id = :oot_dunvan_mercwinn_lt: WHERE id in (69085); # Dunvan_Mercwinn 25
UPDATE npc_types SET loottable_id = :oot_elesseryl_terussar_lt: WHERE id in (69073); # Elesseryl_Terussar 40
UPDATE npc_types SET loottable_id = :oot_elona_tunbrin_lt: WHERE id in (69025); # Elona_Tunbrin 24
UPDATE npc_types SET loottable_id = :oot_endan_halson_lt: WHERE id in (69082); # Endan_Halson 14
UPDATE npc_types SET loottable_id = :oot_euboea_delewyn_lt: WHERE id in (69022); # Euboea_Delewyn 25
UPDATE npc_types SET loottable_id = :oot_fendlemend_figlefop_lt: WHERE id in (69062); # Fendlemend_Figlefop 55
UPDATE npc_types SET loottable_id = :oot_gellmana_sunara_lt: WHERE id in (69136); # Gellmana_Sunara 50
UPDATE npc_types SET loottable_id = :oot_glendl_vargnus_lt: WHERE id in (69019); # Glendl_Vargnus 25
UPDATE npc_types SET loottable_id = :oot_goob_mudtoe_lt: WHERE id in (69125); # Goob_Mudtoe 22
UPDATE npc_types SET loottable_id = :oot_gornit_lt: WHERE id in (69127, 69129, 69094); # Gornit 36
UPDATE npc_types SET loottable_id = :oot_guardian_of_karnon_lt: WHERE id in (69048, 69106); # Guardian_of_K`Arnon 41
UPDATE npc_types SET loottable_id = :oot_gubblegrot_smashfist_lt: WHERE id in (69140); # Gubblegrot_Smashfist 66
UPDATE npc_types SET loottable_id = :oot_gull_skytalon_lt: WHERE id in (69034); # Gull_Skytalon 35
UPDATE npc_types SET loottable_id = :oot_hugan_tunbrin_lt: WHERE id in (69020); # Hugan_Tunbrin 25
UPDATE npc_types SET loottable_id = :oot_isle_goblin_chieftan_lt: WHERE id in (69148); # isle_goblin_chieftan 25
UPDATE npc_types SET loottable_id = :oot_larisa_gelrith_lt: WHERE id in (69014); # Larisa_Gelrith 25
UPDATE npc_types SET loottable_id = :oot_lorna_shearsin_lt: WHERE id in (69083); # Lorna_Shearsin 25
UPDATE npc_types SET loottable_id = :oot_moad_delangan_lt: WHERE id in (69139); # Moad_Delangan 50
UPDATE npc_types SET loottable_id = :oot_naya_driftwood_lt: WHERE id in (69109); # Naya_Driftwood 15
UPDATE npc_types SET loottable_id = :oot_nerbilik_lt: WHERE id in (69064); # Nerbilik 20
UPDATE npc_types SET loottable_id = :oot_nyuae_the_cruel_lt: WHERE id in (69005); # Nyuae_the_Cruel 42
UPDATE npc_types SET loottable_id = :oot_oracle_of_karnon_lt: WHERE id in (69044); # Oracle_of_K`Arnon 36
UPDATE npc_types SET loottable_id = :oot_paeonia_purnn_lt: WHERE id in (69030); # Paeonia_Purnn 25
UPDATE npc_types SET loottable_id = :oot_phocaea_hapspenn_lt: WHERE id in (69053); # Phocaea_Hapspenn 25
UPDATE npc_types SET loottable_id = :oot_quag_maelstrom_lt: WHERE id in (69093); # Quag_Maelstrom 45
UPDATE npc_types SET loottable_id = :oot_ran_aldorne_lt: WHERE id in (69079); # Ran_Aldorne 25
UPDATE npc_types SET loottable_id = :oot_raotin_teawel_lt: WHERE id in (69086); # Raotin_Teawel 15
UPDATE npc_types SET loottable_id = :oot_saldra_trailfinder_lt: WHERE id in (69138); # Saldra_Trailfinder 50
UPDATE npc_types SET loottable_id = :oot_sanian_shearsin_lt: WHERE id in (69084); # Sanian_Shearsin 25
UPDATE npc_types SET loottable_id = :oot_secaldru_zandar_lt: WHERE id in (69146); # Secaldru_Zandar 50
UPDATE npc_types SET loottable_id = :oot_sentry_xyrin_lt: WHERE id in (69132); # Sentry_Xyrin 19
UPDATE npc_types SET loottable_id = :oot_seplawishinl_bladeblight_lt: WHERE id in (69060); # Seplawishinl_Bladeblight 60
UPDATE npc_types SET loottable_id = :oot_sirensbane_lt: WHERE id in (69134); # SirensBane 50
UPDATE npc_types SET loottable_id = :oot_sister_of_erollisi_lt: WHERE id in (69043, 69049, 69050, 69051); # Sister_of_Erollisi 7
UPDATE npc_types SET loottable_id = :oot_soarin_brightfeather_lt: WHERE id in (69153); # Soarin_Brightfeather 30
UPDATE npc_types SET loottable_id = :oot_styria_fearnon_lt: WHERE id in (69008); # Styria_Fearnon 61
UPDATE npc_types SET loottable_id = :oot_tagea_prendyn_lt: WHERE id in (69144); # Tagea_Prendyn 99
UPDATE npc_types SET loottable_id = :oot_tainted_seafury_cyclops_lt: WHERE id in (69096); # tainted_seafury_cyclops 46
UPDATE npc_types SET loottable_id = :oot_tegea_prendyn_lt: WHERE id in (69017); # Tegea_Prendyn 25
UPDATE npc_types SET loottable_id = :oot_the_fabled_allizewsaur_lt: WHERE id in (69135); # The_Fabled_Allizewsaur 70
UPDATE npc_types SET loottable_id = :oot_toko_binlittle_lt: WHERE id in (69121, 69042, 69101); # Toko_Binlittle 15
UPDATE npc_types SET loottable_id = :oot_valaryn_elben_lt: WHERE id in (69080); # Valaryn_Elben 25
UPDATE npc_types SET loottable_id = :oot_wiltin_windwalker_lt: WHERE id in (69143); # Wiltin_Windwalker 32
UPDATE npc_types SET loottable_id = :oot_zachariah_reigh_lt: WHERE id in (69078); # Zachariah_Reigh 25
UPDATE npc_types SET loottable_id = :oot_zyle_bensmill_lt: WHERE id in (69002, 69092); # Zyle_Bensmill 14
