INSERT INTO loottable(name) VALUES('paw_air_elemental_breeze_master'); # :paw_air_elemental_breeze_master_lt:
INSERT INTO loottable(name) VALUES('paw_a_gnoll_prisoner'); # :paw_a_gnoll_prisoner_lt:
INSERT INTO loottable(name) VALUES('paw_a_tidal_monstrosity'); # :paw_a_tidal_monstrosity_lt:
INSERT INTO loottable(name) VALUES('paw_blazemaster_arnab'); # :paw_blazemaster_arnab_lt:
INSERT INTO loottable(name) VALUES('paw_earthmaster_grundag'); # :paw_earthmaster_grundag_lt:
INSERT INTO loottable(name) VALUES('paw_fire_elemental_brigand'); # :paw_fire_elemental_brigand_lt:
INSERT INTO loottable(name) VALUES('paw_gillamina_garstobidokis'); # :paw_gillamina_garstobidokis_lt:
INSERT INTO loottable(name) VALUES('paw_overlord_flargor'); # :paw_overlord_flargor_lt:
INSERT INTO loottable(name) VALUES('paw_retharg'); # :paw_retharg_lt:
INSERT INTO loottable(name) VALUES('paw_rockbeast_kloorg'); # :paw_rockbeast_kloorg_lt:
INSERT INTO loottable(name) VALUES('paw_scorch'); # :paw_scorch_lt:
INSERT INTO loottable(name) VALUES('paw_sertiki_the_master_of_tides'); # :paw_sertiki_the_master_of_tides_lt:
INSERT INTO loottable(name) VALUES('paw_stormrider_hilooa'); # :paw_stormrider_hilooa_lt:
INSERT INTO loottable(name) VALUES('paw_tidemaster_aquinius'); # :paw_tidemaster_aquinius_lt:
INSERT INTO loottable(name) VALUES('paw_vrek_hillsmasher'); # :paw_vrek_hillsmasher_lt:
INSERT INTO loottable(name) VALUES('paw_water_elemental_officer'); # :paw_water_elemental_officer_lt:
INSERT INTO loottable(name) VALUES('paw_water_elemental_overseer'); # :paw_water_elemental_overseer_lt:
INSERT INTO loottable(name) VALUES('paw_windlord_brizoris'); # :paw_windlord_brizoris_lt:
INSERT INTO loottable(name) VALUES('paw_windspirit_glorn'); # :paw_windspirit_glorn_lt:
INSERT INTO loottable(name) VALUES('paw_an_air_elemental_breeze_lord'); # :paw_an_air_elemental_breeze_lord_lt:
INSERT INTO loottable(name) VALUES('paw_an_air_elemental_infiltrator'); # :paw_an_air_elemental_infiltrator_lt:
INSERT INTO loottable(name) VALUES('paw_an_earth_elemental_intruder'); # :paw_an_earth_elemental_intruder_lt:
INSERT INTO loottable(name) VALUES('paw_an_earth_elemental_rockshaper'); # :paw_an_earth_elemental_rockshaper_lt:
INSERT INTO loottable(name) VALUES('paw_an_imprisoned_gnoll'); # :paw_an_imprisoned_gnoll_lt:
INSERT INTO loottable(name) VALUES('paw_a_dead_gnoll'); # :paw_a_dead_gnoll_lt:
INSERT INTO loottable(name) VALUES('paw_a_fire_elemental_blazemaster'); # :paw_a_fire_elemental_blazemaster_lt:
INSERT INTO loottable(name) VALUES('paw_a_fire_elemental_raider'); # :paw_a_fire_elemental_raider_lt:
INSERT INTO loottable(name) VALUES('paw_a_gnoll_prisoner'); # :paw_a_gnoll_prisoner_lt:
INSERT INTO loottable(name) VALUES('paw_a_water_elemental_invader'); # :paw_a_water_elemental_invader_lt:
INSERT INTO loottable(name) VALUES('paw_a_water_elemental_wavecrasher'); # :paw_a_water_elemental_wavecrasher_lt:
INSERT INTO loottable(name) VALUES('paw_a_water_mephit'); # :paw_a_water_mephit_lt:
