INSERT INTO loottable(name) VALUES('qcat_azi_pop'); # :qcat_azi_pop_lt:
INSERT INTO loottable(name) VALUES('qcat_a_sepsis_rat'); # :qcat_a_sepsis_rat_lt:
INSERT INTO loottable(name) VALUES('qcat_a_zombie'); # :qcat_a_zombie_lt:
INSERT INTO loottable(name) VALUES('qcat_coord_inv'); # :qcat_coord_inv_lt:
INSERT INTO loottable(name) VALUES('qcat_nec_pop'); # :qcat_nec_pop_lt:
INSERT INTO loottable(name) VALUES('qcat_rat_popa'); # :qcat_rat_popa_lt:
INSERT INTO loottable(name) VALUES('qcat_rat_popb'); # :qcat_rat_popb_lt:
INSERT INTO loottable(name) VALUES('qcat_sepsis_rat'); # :qcat_sepsis_rat_lt:
INSERT INTO loottable(name) VALUES('qcat_zom_pop'); # :qcat_zom_pop_lt:
INSERT INTO loottable(name) VALUES('qcat_an_exhausted_guard'); # :qcat_an_exhausted_guard_lt:
INSERT INTO loottable(name) VALUES('qcat_an_injured_brigand'); # :qcat_an_injured_brigand_lt:
INSERT INTO loottable(name) VALUES('qcat_an_injured_rat'); # :qcat_an_injured_rat_lt:
INSERT INTO loottable(name) VALUES('qcat_an_investigator'); # :qcat_an_investigator_lt:
INSERT INTO loottable(name) VALUES('qcat_argyn_shieldstan'); # :qcat_argyn_shieldstan_lt:
INSERT INTO loottable(name) VALUES('qcat_azibelle_spavin'); # :qcat_azibelle_spavin_lt:
INSERT INTO loottable(name) VALUES('qcat_a_beggar'); # :qcat_a_beggar_lt:
INSERT INTO loottable(name) VALUES('qcat_a_courier'); # :qcat_a_courier_lt:
INSERT INTO loottable(name) VALUES('qcat_a_fire_beetle'); # :qcat_a_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('qcat_a_fish'); # :qcat_a_fish_lt:
INSERT INTO loottable(name) VALUES('qcat_a_froglok'); # :qcat_a_froglok_lt:
INSERT INTO loottable(name) VALUES('qcat_a_gelatinous_cube'); # :qcat_a_gelatinous_cube_lt:
INSERT INTO loottable(name) VALUES('qcat_a_giant_sewer_rat'); # :qcat_a_giant_sewer_rat_lt:
INSERT INTO loottable(name) VALUES('qcat_a_green_snake'); # :qcat_a_green_snake_lt:
INSERT INTO loottable(name) VALUES('qcat_a_large_piranha'); # :qcat_a_large_piranha_lt:
INSERT INTO loottable(name) VALUES('qcat_a_large_rat'); # :qcat_a_large_rat_lt:
INSERT INTO loottable(name) VALUES('qcat_a_large_snake'); # :qcat_a_large_snake_lt:
INSERT INTO loottable(name) VALUES('qcat_a_large_spider'); # :qcat_a_large_spider_lt:
INSERT INTO loottable(name) VALUES('qcat_a_mercenary'); # :qcat_a_mercenary_lt:
INSERT INTO loottable(name) VALUES('qcat_a_mossy_skeleton'); # :qcat_a_mossy_skeleton_lt:
INSERT INTO loottable(name) VALUES('qcat_a_necromancer'); # :qcat_a_necromancer_lt:
INSERT INTO loottable(name) VALUES('qcat_a_nesting_rat'); # :qcat_a_nesting_rat_lt:
INSERT INTO loottable(name) VALUES('qcat_a_piranha'); # :qcat_a_piranha_lt:
INSERT INTO loottable(name) VALUES('qcat_a_ring_leader'); # :qcat_a_ring_leader_lt:
INSERT INTO loottable(name) VALUES('qcat_a_rotting_sentry'); # :qcat_a_rotting_sentry_lt:
INSERT INTO loottable(name) VALUES('qcat_a_sewer_rat'); # :qcat_a_sewer_rat_lt:
INSERT INTO loottable(name) VALUES('qcat_a_sewer_sentinel'); # :qcat_a_sewer_sentinel_lt:
INSERT INTO loottable(name) VALUES('qcat_a_shady_mercenary'); # :qcat_a_shady_mercenary_lt:
INSERT INTO loottable(name) VALUES('qcat_a_shark'); # :qcat_a_shark_lt:
INSERT INTO loottable(name) VALUES('qcat_a_skeleton'); # :qcat_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('qcat_a_sludge_spiderling'); # :qcat_a_sludge_spiderling_lt:
INSERT INTO loottable(name) VALUES('qcat_a_small_alligator'); # :qcat_a_small_alligator_lt:
INSERT INTO loottable(name) VALUES('qcat_a_smuggler'); # :qcat_a_smuggler_lt:
INSERT INTO loottable(name) VALUES('qcat_a_spectre'); # :qcat_a_spectre_lt:
INSERT INTO loottable(name) VALUES('qcat_a_thug'); # :qcat_a_thug_lt:
INSERT INTO loottable(name) VALUES('qcat_a_thug_leader'); # :qcat_a_thug_leader_lt:
INSERT INTO loottable(name) VALUES('qcat_bait_masterson'); # :qcat_bait_masterson_lt:
INSERT INTO loottable(name) VALUES('qcat_banker_javen'); # :qcat_banker_javen_lt:
INSERT INTO loottable(name) VALUES('qcat_beggar_wyllin'); # :qcat_beggar_wyllin_lt:
INSERT INTO loottable(name) VALUES('qcat_bruax_grengar'); # :qcat_bruax_grengar_lt:
INSERT INTO loottable(name) VALUES('qcat_chan_whinstone'); # :qcat_chan_whinstone_lt:
INSERT INTO loottable(name) VALUES('qcat_chou_whinstone'); # :qcat_chou_whinstone_lt:
INSERT INTO loottable(name) VALUES('qcat_commander_kane'); # :qcat_commander_kane_lt:
INSERT INTO loottable(name) VALUES('qcat_corrupt_guard_helminth'); # :qcat_corrupt_guard_helminth_lt:
INSERT INTO loottable(name) VALUES('qcat_cuburt'); # :qcat_cuburt_lt:
INSERT INTO loottable(name) VALUES('qcat_dallisen_xalladyr'); # :qcat_dallisen_xalladyr_lt:
INSERT INTO loottable(name) VALUES('qcat_dollin_nusmag'); # :qcat_dollin_nusmag_lt:
INSERT INTO loottable(name) VALUES('qcat_dranot_harbin'); # :qcat_dranot_harbin_lt:
INSERT INTO loottable(name) VALUES('qcat_felia_milltorn'); # :qcat_felia_milltorn_lt:
INSERT INTO loottable(name) VALUES('qcat_fellweni_the_kraven'); # :qcat_fellweni_the_kraven_lt:
INSERT INTO loottable(name) VALUES('qcat_garuc_anehm'); # :qcat_garuc_anehm_lt:
INSERT INTO loottable(name) VALUES('qcat_gehnon_dejartes'); # :qcat_gehnon_dejartes_lt:
INSERT INTO loottable(name) VALUES('qcat_gelatinous_cube'); # :qcat_gelatinous_cube_lt:
INSERT INTO loottable(name) VALUES('qcat_guard_helminth'); # :qcat_guard_helminth_lt:
INSERT INTO loottable(name) VALUES('qcat_gyrna_porrin'); # :qcat_gyrna_porrin_lt:
INSERT INTO loottable(name) VALUES('qcat_illie_roln'); # :qcat_illie_roln_lt:
INSERT INTO loottable(name) VALUES('qcat_jexun_elsorg'); # :qcat_jexun_elsorg_lt:
INSERT INTO loottable(name) VALUES('qcat_kron_redstepp'); # :qcat_kron_redstepp_lt:
INSERT INTO loottable(name) VALUES('qcat_krytn_redstepp'); # :qcat_krytn_redstepp_lt:
INSERT INTO loottable(name) VALUES('qcat_kubder_restona'); # :qcat_kubder_restona_lt:
INSERT INTO loottable(name) VALUES('qcat_kurne_rextula'); # :qcat_kurne_rextula_lt:
INSERT INTO loottable(name) VALUES('qcat_lahn_whinstone'); # :qcat_lahn_whinstone_lt:
INSERT INTO loottable(name) VALUES('qcat_leon_ereek'); # :qcat_leon_ereek_lt:
INSERT INTO loottable(name) VALUES('qcat_likka_sowtsui'); # :qcat_likka_sowtsui_lt:
INSERT INTO loottable(name) VALUES('qcat_lyris_moonbane'); # :qcat_lyris_moonbane_lt:
INSERT INTO loottable(name) VALUES('qcat_malka_rale'); # :qcat_malka_rale_lt:
INSERT INTO loottable(name) VALUES('qcat_marn_darkson'); # :qcat_marn_darkson_lt:
INSERT INTO loottable(name) VALUES('qcat_monsarna'); # :qcat_monsarna_lt:
INSERT INTO loottable(name) VALUES('qcat_morn_darkson'); # :qcat_morn_darkson_lt:
INSERT INTO loottable(name) VALUES('qcat_naes_ereek'); # :qcat_naes_ereek_lt:
INSERT INTO loottable(name) VALUES('qcat_neab'); # :qcat_neab_lt:
INSERT INTO loottable(name) VALUES('qcat_nomaria_doseniar'); # :qcat_nomaria_doseniar_lt:
INSERT INTO loottable(name) VALUES('qcat_nulima_opalis'); # :qcat_nulima_opalis_lt:
INSERT INTO loottable(name) VALUES('qcat_omorb'); # :qcat_omorb_lt:
INSERT INTO loottable(name) VALUES('qcat_pakeg_aspet'); # :qcat_pakeg_aspet_lt:
INSERT INTO loottable(name) VALUES('qcat_perkon_malok'); # :qcat_perkon_malok_lt:
INSERT INTO loottable(name) VALUES('qcat_phes_gestolk'); # :qcat_phes_gestolk_lt:
INSERT INTO loottable(name) VALUES('qcat_ranthor_bekesna'); # :qcat_ranthor_bekesna_lt:
INSERT INTO loottable(name) VALUES('qcat_reania_jukle'); # :qcat_reania_jukle_lt:
INSERT INTO loottable(name) VALUES('qcat_riggin_vix'); # :qcat_riggin_vix_lt:
INSERT INTO loottable(name) VALUES('qcat_rihtur_fullome'); # :qcat_rihtur_fullome_lt:
INSERT INTO loottable(name) VALUES('qcat_rocthar_bekesna'); # :qcat_rocthar_bekesna_lt:
INSERT INTO loottable(name) VALUES('qcat_ronn_castekin'); # :qcat_ronn_castekin_lt:
INSERT INTO loottable(name) VALUES('qcat_senst_ereek'); # :qcat_senst_ereek_lt:
INSERT INTO loottable(name) VALUES('qcat_sragg_bloodheart'); # :qcat_sragg_bloodheart_lt:
INSERT INTO loottable(name) VALUES('qcat_tessia_sowtsui'); # :qcat_tessia_sowtsui_lt:
INSERT INTO loottable(name) VALUES('qcat_teydar'); # :qcat_teydar_lt:
INSERT INTO loottable(name) VALUES('qcat_thumpy'); # :qcat_thumpy_lt:
INSERT INTO loottable(name) VALUES('qcat_timvu'); # :qcat_timvu_lt:
INSERT INTO loottable(name) VALUES('qcat_torin_krentar'); # :qcat_torin_krentar_lt:
INSERT INTO loottable(name) VALUES('qcat_trenon_callust'); # :qcat_trenon_callust_lt:
INSERT INTO loottable(name) VALUES('qcat_unmuz_tukore'); # :qcat_unmuz_tukore_lt:
INSERT INTO loottable(name) VALUES('qcat_vach_piral'); # :qcat_vach_piral_lt:
INSERT INTO loottable(name) VALUES('qcat_van_shatblack'); # :qcat_van_shatblack_lt:
INSERT INTO loottable(name) VALUES('qcat_vidurlyn_aeminee'); # :qcat_vidurlyn_aeminee_lt:
INSERT INTO loottable(name) VALUES('qcat_vin_moltor'); # :qcat_vin_moltor_lt:
INSERT INTO loottable(name) VALUES('qcat_vun_shatblack'); # :qcat_vun_shatblack_lt:
INSERT INTO loottable(name) VALUES('qcat_wellis_pestule'); # :qcat_wellis_pestule_lt:
INSERT INTO loottable(name) VALUES('qcat_xeture_demiagar'); # :qcat_xeture_demiagar_lt:
INSERT INTO loottable(name) VALUES('qcat_zaen_kalystir'); # :qcat_zaen_kalystir_lt:
