UPDATE npc_types SET loottable_id = :qcat_azi_pop_lt: WHERE id in (45109); # #Azi_pop 50
UPDATE npc_types SET loottable_id = :qcat_a_sepsis_rat_lt: WHERE id in (45104); # #a_sepsis_rat 33
UPDATE npc_types SET loottable_id = :qcat_a_zombie_lt: WHERE id in (45126); # #a_zombie 8
UPDATE npc_types SET loottable_id = :qcat_coord_inv_lt: WHERE id in (45099); # #Coord_Inv 50
UPDATE npc_types SET loottable_id = :qcat_nec_pop_lt: WHERE id in (45107); # #Nec_pop 50
UPDATE npc_types SET loottable_id = :qcat_rat_popa_lt: WHERE id in (45110); # #Rat_popa 50
UPDATE npc_types SET loottable_id = :qcat_rat_popb_lt: WHERE id in (45108); # #Rat_popb 50
UPDATE npc_types SET loottable_id = :qcat_sepsis_rat_lt: WHERE id in (45113); # #sepsis_rat 32
UPDATE npc_types SET loottable_id = :qcat_zom_pop_lt: WHERE id in (45122); # #Zom_pop 50
UPDATE npc_types SET loottable_id = :qcat_an_exhausted_guard_lt: WHERE id in (45046); # an_exhausted_guard 4
UPDATE npc_types SET loottable_id = :qcat_an_injured_brigand_lt: WHERE id in (45038); # an_injured_brigand 6
UPDATE npc_types SET loottable_id = :qcat_an_injured_rat_lt: WHERE id in (45123); # an_injured_rat 2
UPDATE npc_types SET loottable_id = :qcat_an_investigator_lt: WHERE id in (45093); # an_investigator 1
UPDATE npc_types SET loottable_id = :qcat_argyn_shieldstan_lt: WHERE id in (45015); # Argyn_Shieldstan 30
UPDATE npc_types SET loottable_id = :qcat_azibelle_spavin_lt: WHERE id in (45119); # Azibelle_Spavin 45
UPDATE npc_types SET loottable_id = :qcat_a_beggar_lt: WHERE id in (45021); # a_beggar 5
UPDATE npc_types SET loottable_id = :qcat_a_courier_lt: WHERE id in (45005); # a_courier 6
UPDATE npc_types SET loottable_id = :qcat_a_fire_beetle_lt: WHERE id in (45025); # a_fire_beetle 2
UPDATE npc_types SET loottable_id = :qcat_a_fish_lt: WHERE id in (45000, 45014, 45023); # a_fish 1
UPDATE npc_types SET loottable_id = :qcat_a_froglok_lt: WHERE id in (45032, 45034, 45035); # a_froglok 4
UPDATE npc_types SET loottable_id = :qcat_a_gelatinous_cube_lt: WHERE id in (45007, 45020); # a_gelatinous_cube 5
UPDATE npc_types SET loottable_id = :qcat_a_giant_sewer_rat_lt: WHERE id in (45008, 45026, 45031); # a_giant_sewer_rat 5
UPDATE npc_types SET loottable_id = :qcat_a_green_snake_lt: WHERE id in (45033); # a_green_snake 1
UPDATE npc_types SET loottable_id = :qcat_a_large_piranha_lt: WHERE id in (45022); # a_large_piranha 4
UPDATE npc_types SET loottable_id = :qcat_a_large_rat_lt: WHERE id in (45028); # a_large_rat 1
UPDATE npc_types SET loottable_id = :qcat_a_large_snake_lt: WHERE id in (45043, 45047); # a_large_snake 3
UPDATE npc_types SET loottable_id = :qcat_a_large_spider_lt: WHERE id in (45001, 45016, 45040); # a_large_spider 4
UPDATE npc_types SET loottable_id = :qcat_a_mercenary_lt: WHERE id in (45029, 45030); # a_mercenary 3
UPDATE npc_types SET loottable_id = :qcat_a_mossy_skeleton_lt: WHERE id in (45018); # a_mossy_skeleton 1
UPDATE npc_types SET loottable_id = :qcat_a_necromancer_lt: WHERE id in (45106); # a_necromancer 34
UPDATE npc_types SET loottable_id = :qcat_a_nesting_rat_lt: WHERE id in (45121); # a_nesting_rat 5
UPDATE npc_types SET loottable_id = :qcat_a_piranha_lt: WHERE id in (45092); # a_piranha 2
UPDATE npc_types SET loottable_id = :qcat_a_ring_leader_lt: WHERE id in (45101); # a_ring_leader 12
UPDATE npc_types SET loottable_id = :qcat_a_rotting_sentry_lt: WHERE id in (45118); # a_rotting_sentry 32
UPDATE npc_types SET loottable_id = :qcat_a_sewer_rat_lt: WHERE id in (45002, 45006, 45039, 45042); # a_sewer_rat 3
UPDATE npc_types SET loottable_id = :qcat_a_sewer_sentinel_lt: WHERE id in (45053); # a_sewer_sentinel 8
UPDATE npc_types SET loottable_id = :qcat_a_shady_mercenary_lt: WHERE id in (45125); # A_Shady_Mercenary 7
UPDATE npc_types SET loottable_id = :qcat_a_shark_lt: WHERE id in (45041); # a_shark 17
UPDATE npc_types SET loottable_id = :qcat_a_skeleton_lt: WHERE id in (45060, 45004); # a_skeleton 6
UPDATE npc_types SET loottable_id = :qcat_a_sludge_spiderling_lt: WHERE id in (45017, 45027, 45045); # a_sludge_spiderling 1
UPDATE npc_types SET loottable_id = :qcat_a_small_alligator_lt: WHERE id in (45019); # a_small_alligator 1
UPDATE npc_types SET loottable_id = :qcat_a_smuggler_lt: WHERE id in (45009, 45010, 45024); # a_smuggler 11
UPDATE npc_types SET loottable_id = :qcat_a_spectre_lt: WHERE id in (45011, 45012, 45013); # a_spectre 37
UPDATE npc_types SET loottable_id = :qcat_a_thug_lt: WHERE id in (45036, 45037); # a_thug 6
UPDATE npc_types SET loottable_id = :qcat_a_thug_leader_lt: WHERE id in (45096); # a_thug_leader 7
UPDATE npc_types SET loottable_id = :qcat_bait_masterson_lt: WHERE id in (45094); # Bait_Masterson 25
UPDATE npc_types SET loottable_id = :qcat_banker_javen_lt: WHERE id in (45054); # Banker_Javen 40
UPDATE npc_types SET loottable_id = :qcat_beggar_wyllin_lt: WHERE id in (45115); # Beggar_Wyllin 5
UPDATE npc_types SET loottable_id = :qcat_bruax_grengar_lt: WHERE id in (45064); # Bruax_Grengar 61
UPDATE npc_types SET loottable_id = :qcat_chan_whinstone_lt: WHERE id in (45102); # Chan_Whinstone 30
UPDATE npc_types SET loottable_id = :qcat_chou_whinstone_lt: WHERE id in (45071); # Chou_Whinstone 30
UPDATE npc_types SET loottable_id = :qcat_commander_kane_lt: WHERE id in (45114); # Commander_Kane 61
UPDATE npc_types SET loottable_id = :qcat_corrupt_guard_helminth_lt: WHERE id in (45130); # Corrupt_Guard_Helminth 50
UPDATE npc_types SET loottable_id = :qcat_cuburt_lt: WHERE id in (45116); # Cuburt 4
UPDATE npc_types SET loottable_id = :qcat_dallisen_xalladyr_lt: WHERE id in (45049); # Dallisen_Xalladyr 45
UPDATE npc_types SET loottable_id = :qcat_dollin_nusmag_lt: WHERE id in (45127, 45128); # Dollin_Nusmag 65
UPDATE npc_types SET loottable_id = :qcat_dranot_harbin_lt: WHERE id in (45061); # Dranot_Harbin 30
UPDATE npc_types SET loottable_id = :qcat_felia_milltorn_lt: WHERE id in (45063); # Felia_Milltorn 30
UPDATE npc_types SET loottable_id = :qcat_fellweni_the_kraven_lt: WHERE id in (45048); # Fellweni_the_Kraven 45
UPDATE npc_types SET loottable_id = :qcat_garuc_anehm_lt: WHERE id in (45069); # Garuc_Anehm 61
UPDATE npc_types SET loottable_id = :qcat_gehnon_dejartes_lt: WHERE id in (45079); # Gehnon_Dejartes 40
UPDATE npc_types SET loottable_id = :qcat_gelatinous_cube_lt: WHERE id in (45105); # Gelatinous_Cube 14
UPDATE npc_types SET loottable_id = :qcat_guard_helminth_lt: WHERE id in (45131); # Guard_Helminth 35
UPDATE npc_types SET loottable_id = :qcat_gyrna_porrin_lt: WHERE id in (45051); # Gyrna_Porrin 45
UPDATE npc_types SET loottable_id = :qcat_illie_roln_lt: WHERE id in (45076); # Illie_Roln 35
UPDATE npc_types SET loottable_id = :qcat_jexun_elsorg_lt: WHERE id in (45078); # Jexun_Elsorg 38
UPDATE npc_types SET loottable_id = :qcat_kron_redstepp_lt: WHERE id in (45097); # Kron_Redstepp 30
UPDATE npc_types SET loottable_id = :qcat_krytn_redstepp_lt: WHERE id in (45072); # Krytn_Redstepp 30
UPDATE npc_types SET loottable_id = :qcat_kubder_restona_lt: WHERE id in (45062); # Kubder_Restona 30
UPDATE npc_types SET loottable_id = :qcat_kurne_rextula_lt: WHERE id in (45066); # Kurne_Rextula 61
UPDATE npc_types SET loottable_id = :qcat_lahn_whinstone_lt: WHERE id in (45003); # Lahn_Whinstone 30
UPDATE npc_types SET loottable_id = :qcat_leon_ereek_lt: WHERE id in (45058); # Leon_Ereek 50
UPDATE npc_types SET loottable_id = :qcat_likka_sowtsui_lt: WHERE id in (45059); # Likka_Sowtsui 50
UPDATE npc_types SET loottable_id = :qcat_lyris_moonbane_lt: WHERE id in (45090); # Lyris_Moonbane 61
UPDATE npc_types SET loottable_id = :qcat_malka_rale_lt: WHERE id in (45095); # Malka_Rale 48
UPDATE npc_types SET loottable_id = :qcat_marn_darkson_lt: WHERE id in (45073); # Marn_Darkson 30
UPDATE npc_types SET loottable_id = :qcat_monsarna_lt: WHERE id in (45120); # Mon`Sarna 5
UPDATE npc_types SET loottable_id = :qcat_morn_darkson_lt: WHERE id in (45100); # Morn_Darkson 30
UPDATE npc_types SET loottable_id = :qcat_naes_ereek_lt: WHERE id in (45056); # Naes_Ereek 50
UPDATE npc_types SET loottable_id = :qcat_neab_lt: WHERE id in (45084); # Neab 10
UPDATE npc_types SET loottable_id = :qcat_nomaria_doseniar_lt: WHERE id in (45086); # Nomaria_Doseniar 61
UPDATE npc_types SET loottable_id = :qcat_nulima_opalis_lt: WHERE id in (45065); # Nulima_Opalis 61
UPDATE npc_types SET loottable_id = :qcat_omorb_lt: WHERE id in (45117); # Omorb 20
UPDATE npc_types SET loottable_id = :qcat_pakeg_aspet_lt: WHERE id in (45077); # Pakeg_Aspet 41
UPDATE npc_types SET loottable_id = :qcat_perkon_malok_lt: WHERE id in (45083); # Perkon_Malok 61
UPDATE npc_types SET loottable_id = :qcat_phes_gestolk_lt: WHERE id in (45088); # Phes_Gestolk 61
UPDATE npc_types SET loottable_id = :qcat_ranthor_bekesna_lt: WHERE id in (45129); # Ranthor_Bekesna 70
UPDATE npc_types SET loottable_id = :qcat_reania_jukle_lt: WHERE id in (45082); # Reania_Jukle 61
UPDATE npc_types SET loottable_id = :qcat_riggin_vix_lt: WHERE id in (45085); # Riggin_Vix 17
UPDATE npc_types SET loottable_id = :qcat_rihtur_fullome_lt: WHERE id in (45087); # Rihtur_Fullome 61
UPDATE npc_types SET loottable_id = :qcat_rocthar_bekesna_lt: WHERE id in (45080); # Rocthar_Bekesna 61
UPDATE npc_types SET loottable_id = :qcat_ronn_castekin_lt: WHERE id in (45124); # Ronn_Castekin 2
UPDATE npc_types SET loottable_id = :qcat_senst_ereek_lt: WHERE id in (45055); # Senst_Ereek 50
UPDATE npc_types SET loottable_id = :qcat_sragg_bloodheart_lt: WHERE id in (45091); # Sragg_Bloodheart 61
UPDATE npc_types SET loottable_id = :qcat_tessia_sowtsui_lt: WHERE id in (45057); # Tessia_Sowtsui 50
UPDATE npc_types SET loottable_id = :qcat_teydar_lt: WHERE id in (45044); # Teydar 60
UPDATE npc_types SET loottable_id = :qcat_thumpy_lt: WHERE id in (45103); # Thumpy 10
UPDATE npc_types SET loottable_id = :qcat_timvu_lt: WHERE id in (45112); # Timvu 35
UPDATE npc_types SET loottable_id = :qcat_torin_krentar_lt: WHERE id in (45074); # Torin_Krentar 35
UPDATE npc_types SET loottable_id = :qcat_trenon_callust_lt: WHERE id in (45081); # Trenon_Callust 61
UPDATE npc_types SET loottable_id = :qcat_unmuz_tukore_lt: WHERE id in (45067); # Unmuz_Tukore 61
UPDATE npc_types SET loottable_id = :qcat_vach_piral_lt: WHERE id in (45052); # Vach_Piral 65
UPDATE npc_types SET loottable_id = :qcat_van_shatblack_lt: WHERE id in (45098); # Van_Shatblack 30
UPDATE npc_types SET loottable_id = :qcat_vidurlyn_aeminee_lt: WHERE id in (45050); # Vidurlyn_Aeminee 45
UPDATE npc_types SET loottable_id = :qcat_vin_moltor_lt: WHERE id in (45111); # Vin_Moltor 24
UPDATE npc_types SET loottable_id = :qcat_vun_shatblack_lt: WHERE id in (45070); # Vun_Shatblack 30
UPDATE npc_types SET loottable_id = :qcat_wellis_pestule_lt: WHERE id in (45075); # Wellis_Pestule 35
UPDATE npc_types SET loottable_id = :qcat_xeture_demiagar_lt: WHERE id in (45089); # Xeture_Demiagar 61
UPDATE npc_types SET loottable_id = :qcat_zaen_kalystir_lt: WHERE id in (45068); # Zaen_Kalystir 61
