UPDATE npc_types SET loottable_id = :qeytoqrg_apprentice_of_saxuus_lt: WHERE id in (4170); # #Apprentice_of_Saxuus 30
UPDATE npc_types SET loottable_id = :qeytoqrg_jpeapprenticecounter_lt: WHERE id in (4173); # #JPEApprenticeCounter 1
UPDATE npc_types SET loottable_id = :qeytoqrg_the_fabled_pyzjn_lt: WHERE id in (4199); # #The_Fabled_Pyzjn 27
UPDATE npc_types SET loottable_id = :qeytoqrg_utility_listener_lt: WHERE id in (4182); # #Utility_Listener 1
UPDATE npc_types SET loottable_id = :qeytoqrg_amid_the_lt: WHERE id in (4174); # Amid_the 1
UPDATE npc_types SET loottable_id = :qeytoqrg_axe_broadsmith_lt: WHERE id in (4038); # Axe_Broadsmith 20
UPDATE npc_types SET loottable_id = :qeytoqrg_a_boat_lt: WHERE id in (4058); # a_boat 1
UPDATE npc_types SET loottable_id = :qeytoqrg_a_brown_bear_lt: WHERE id in (4005, 4027); # a_brown_bear 3
UPDATE npc_types SET loottable_id = :qeytoqrg_a_decaying_skeleton_lt: WHERE id in (4010); # a_decaying_skeleton 1
UPDATE npc_types SET loottable_id = :qeytoqrg_a_dread_corpse_lt: WHERE id in (4139, 4045, 4047); # a_dread_corpse 9
UPDATE npc_types SET loottable_id = :qeytoqrg_a_fire_beetle_lt: WHERE id in (4026); # a_fire_beetle 2
UPDATE npc_types SET loottable_id = :qeytoqrg_a_giant_field_rat_lt: WHERE id in (4080); # a_giant_field_rat 5
UPDATE npc_types SET loottable_id = :qeytoqrg_a_giant_king_snake_lt: WHERE id in (4044); # a_giant_king_snake 7
UPDATE npc_types SET loottable_id = :qeytoqrg_a_giant_myotis_bat_lt: WHERE id in (4039, 4042); # a_giant_myotis_bat 8
UPDATE npc_types SET loottable_id = :qeytoqrg_a_giant_rat_lt: WHERE id in (4036); # a_giant_rat 4
UPDATE npc_types SET loottable_id = :qeytoqrg_a_giant_whiskered_bat_lt: WHERE id in (4002); # a_giant_whiskered_bat 7
UPDATE npc_types SET loottable_id = :qeytoqrg_a_gnoll_lt: WHERE id in (4096, 4006, 4033); # a_gnoll 5
UPDATE npc_types SET loottable_id = :qeytoqrg_a_gnoll_hunter_lt: WHERE id in (4191); # a_gnoll_hunter 5
UPDATE npc_types SET loottable_id = :qeytoqrg_a_gnoll_pup_lt: WHERE id in (4079); # a_gnoll_pup 1
UPDATE npc_types SET loottable_id = :qeytoqrg_a_gnoll_scout_lt: WHERE id in (4015, 4021); # a_gnoll_scout 3
UPDATE npc_types SET loottable_id = :qeytoqrg_a_gnoll_watcher_lt: WHERE id in (4152, 4028, 4029); # a_gnoll_watcher 4
UPDATE npc_types SET loottable_id = :qeytoqrg_a_gray_wolf_lt: WHERE id in (4000, 4016, 4034); # a_gray_wolf 3
UPDATE npc_types SET loottable_id = :qeytoqrg_a_grizzly_bear_lt: WHERE id in (4030); # a_grizzly_bear 11
UPDATE npc_types SET loottable_id = :qeytoqrg_a_king_snake_lt: WHERE id in (4017); # a_king_snake 1
UPDATE npc_types SET loottable_id = :qeytoqrg_a_large_field_rat_lt: WHERE id in (4007, 4013, 4024); # a_large_field_rat 1
UPDATE npc_types SET loottable_id = :qeytoqrg_a_large_king_snake_lt: WHERE id in (4018, 4023); # a_large_king_snake 4
UPDATE npc_types SET loottable_id = :qeytoqrg_a_large_myotis_bat_lt: WHERE id in (4143, 4074, 4075); # a_large_myotis_bat 5
UPDATE npc_types SET loottable_id = :qeytoqrg_a_large_whiskered_bat_lt: WHERE id in (4011, 4012, 4043, 4050, 4051); # a_large_whiskered_bat 6
UPDATE npc_types SET loottable_id = :qeytoqrg_a_mangy_rat_lt: WHERE id in (4078); # a_mangy_rat 1
UPDATE npc_types SET loottable_id = :qeytoqrg_a_putrid_skeleton_lt: WHERE id in (4137, 4148); # a_putrid_skeleton 6
UPDATE npc_types SET loottable_id = :qeytoqrg_a_rabid_grizzly_lt: WHERE id in (4136); # a_rabid_grizzly 8
UPDATE npc_types SET loottable_id = :qeytoqrg_a_rabid_wolf_lt: WHERE id in (4019, 4040); # a_rabid_wolf 3
UPDATE npc_types SET loottable_id = :qeytoqrg_a_restless_skeleton_lt: WHERE id in (4150, 4022); # a_restless_skeleton 2
UPDATE npc_types SET loottable_id = :qeytoqrg_a_row_boat_lt: WHERE id in (4059); # a_row_boat 50
UPDATE npc_types SET loottable_id = :qeytoqrg_a_shrieking_lt: WHERE id in (4163); # A_shrieking 1
UPDATE npc_types SET loottable_id = :qeytoqrg_a_skeletal_commander_lt: WHERE id in (4108, 4109); # a_skeletal_commander 38
UPDATE npc_types SET loottable_id = :qeytoqrg_a_skeletal_conscript_lt: WHERE id in (4129); # a_skeletal_conscript 12
UPDATE npc_types SET loottable_id = :qeytoqrg_a_skeletal_footsoldier_lt: WHERE id in (4101, 4120, 4122, 4125); # a_skeletal_footsoldier 22
UPDATE npc_types SET loottable_id = :qeytoqrg_a_skeletal_lieutenant_lt: WHERE id in (4116, 4119); # a_skeletal_lieutenant 34
UPDATE npc_types SET loottable_id = :qeytoqrg_a_skeletal_trooper_lt: WHERE id in (4110, 4112, 4114, 4115, 4128, 4145, 4146, 4091, 4092, 4094); # a_skeletal_trooper 29
UPDATE npc_types SET loottable_id = :qeytoqrg_a_strange_skeleton_lt: WHERE id in (4192); # a_strange_skeleton 6
UPDATE npc_types SET loottable_id = :qeytoqrg_a_whiskered_bat_lt: WHERE id in (4009, 4014, 4025); # a_whiskered_bat 3
UPDATE npc_types SET loottable_id = :qeytoqrg_a_willowisp_lt: WHERE id in (4154, 4035, 4041); # a_willowisp 9
UPDATE npc_types SET loottable_id = :qeytoqrg_baobob_miller_lt: WHERE id in (4055); # Baobob_Miller 25
UPDATE npc_types SET loottable_id = :qeytoqrg_barn_bloodstone_lt: WHERE id in (4203); # Barn_Bloodstone 20
UPDATE npc_types SET loottable_id = :qeytoqrg_buzzlin_bornahm_lt: WHERE id in (4149); # Buzzlin_Bornahm 24
UPDATE npc_types SET loottable_id = :qeytoqrg_cethernee_vellestan_lt: WHERE id in (4201); # Cethernee_Vellestan 50
UPDATE npc_types SET loottable_id = :qeytoqrg_chanda_miller_lt: WHERE id in (4052); # Chanda_Miller 25
UPDATE npc_types SET loottable_id = :qeytoqrg_crumpy_irontoe_lt: WHERE id in (4164); # Crumpy_Irontoe 13
UPDATE npc_types SET loottable_id = :qeytoqrg_erudite_traveler_lt: WHERE id in (4056); # erudite_traveler 20
UPDATE npc_types SET loottable_id = :qeytoqrg_for_a_brief_lt: WHERE id in (4168); # For_a_brief 1
UPDATE npc_types SET loottable_id = :qeytoqrg_from_afar_lt: WHERE id in (4185); # From_afar 1
UPDATE npc_types SET loottable_id = :qeytoqrg_gnasher_furgutt_lt: WHERE id in (4181); # Gnasher_Furgutt 10
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_beris_lt: WHERE id in (4053); # Guard_Beris 15
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_bixby_lt: WHERE id in (4063); # Guard_Bixby 22
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_cheslin_lt: WHERE id in (4004, 4076, 4081); # Guard_Cheslin 4
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_chrighton_lt: WHERE id in (4180); # Guard_Chrighton 40
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_kellot_lt: WHERE id in (4067); # Guard_Kellot 20
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_leopold_lt: WHERE id in (4061); # Guard_Leopold 38
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_miles_lt: WHERE id in (4141); # Guard_Miles 38
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_monroe_lt: WHERE id in (4068); # Guard_Monroe 27
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_nash_lt: WHERE id in (4066); # Guard_Nash 40
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_philbin_lt: WHERE id in (4062); # Guard_Philbin 25
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_sironan_lt: WHERE id in (4049); # Guard_Sironan 14
UPDATE npc_types SET loottable_id = :qeytoqrg_guard_yalroen_lt: WHERE id in (4048); # Guard_Yalroen 12
UPDATE npc_types SET loottable_id = :qeytoqrg_hadden_lt: WHERE id in (4189); # Hadden 28
UPDATE npc_types SET loottable_id = :qeytoqrg_hefax_tinmar_lt: WHERE id in (4142); # Hefax_Tinmar 20
UPDATE npc_types SET loottable_id = :qeytoqrg_holly_windstalker_lt: WHERE id in (4057); # Holly_Windstalker 27
UPDATE npc_types SET loottable_id = :qeytoqrg_jaynen,_master_armsman_lt: WHERE id in (4161); # Jaynen,_Master_Armsman 60
UPDATE npc_types SET loottable_id = :qeytoqrg_jpegnollspawner_lt: WHERE id in (4156); # JPEGnollSpawner 1
UPDATE npc_types SET loottable_id = :qeytoqrg_jpeinvisgnollshoutspawn_lt: WHERE id in (4178); # JPEInvisGnollShoutSpawn 1
UPDATE npc_types SET loottable_id = :qeytoqrg_jpeinvisgnollspawn_lt: WHERE id in (4167); # JPEInvisGnollSpawn 1
UPDATE npc_types SET loottable_id = :qeytoqrg_jpeinvisgnollspawna_lt: WHERE id in (4159); # JPEInvisGnollSpawna 1
UPDATE npc_types SET loottable_id = :qeytoqrg_jpeinvisjaynen_lt: WHERE id in (4187); # JPEInvisJaynen 1
UPDATE npc_types SET loottable_id = :qeytoqrg_jpeinviskantorn_lt: WHERE id in (4183); # JPEInvisKantorn 1
UPDATE npc_types SET loottable_id = :qeytoqrg_jpeinvisrngspawn_lt: WHERE id in (4166); # JPEInvisRngSpawn 1
UPDATE npc_types SET loottable_id = :qeytoqrg_jpetimer_lt: WHERE id in (4175); # JPETimer 1
UPDATE npc_types SET loottable_id = :qeytoqrg_just_outside_lt: WHERE id in (4162); # Just_outside 1
UPDATE npc_types SET loottable_id = :qeytoqrg_kantorn,_master_armsman_lt: WHERE id in (4188); # Kantorn,_Master_Armsman 60
UPDATE npc_types SET loottable_id = :qeytoqrg_konem_matse_lt: WHERE id in (4072); # Konem_Matse 28
UPDATE npc_types SET loottable_id = :qeytoqrg_lamangao_fallstine_lt: WHERE id in (4202); # Lamangao_Fallstine 50
UPDATE npc_types SET loottable_id = :qeytoqrg_marton_sayer_lt: WHERE id in (4065); # Marton_Sayer 30
UPDATE npc_types SET loottable_id = :qeytoqrg_mira_sayer_lt: WHERE id in (4064); # Mira_Sayer 30
UPDATE npc_types SET loottable_id = :qeytoqrg_misty_storyswapper_lt: WHERE id in (4193); # Misty_Storyswapper 15
UPDATE npc_types SET loottable_id = :qeytoqrg_mogan_delfin_lt: WHERE id in (4069); # Mogan_Delfin 25
UPDATE npc_types SET loottable_id = :qeytoqrg_neclo_rheslar_lt: WHERE id in (4032); # Neclo_Rheslar 16
UPDATE npc_types SET loottable_id = :qeytoqrg_niclaus_ressinn_lt: WHERE id in (4060); # Niclaus_Ressinn 33
UPDATE npc_types SET loottable_id = :qeytoqrg_pemawen_vorana_lt: WHERE id in (4200); # Pemawen_Vorana 50
UPDATE npc_types SET loottable_id = :qeytoqrg_pyzjn_lt: WHERE id in (4147); # Pyzjn 13
UPDATE npc_types SET loottable_id = :qeytoqrg_rephas_lt: WHERE id in (4037); # Rephas 28
UPDATE npc_types SET loottable_id = :qeytoqrg_rilca_leafrunner_lt: WHERE id in (4054); # Rilca_Leafrunner 35
UPDATE npc_types SET loottable_id = :qeytoqrg_sarri_modav_lt: WHERE id in (4070); # Sarri_Modav 65
UPDATE npc_types SET loottable_id = :qeytoqrg_scruffy_lt: WHERE id in (4155); # Scruffy 1
UPDATE npc_types SET loottable_id = :qeytoqrg_sir_edwin_motte_lt: WHERE id in (4077); # Sir_Edwin_Motte 33
UPDATE npc_types SET loottable_id = :qeytoqrg_talym_shoontar_lt: WHERE id in (4157); # Talym_Shoontar 15
UPDATE npc_types SET loottable_id = :qeytoqrg_tol_nicelot_lt: WHERE id in (4205); # Tol_Nicelot 20
UPDATE npc_types SET loottable_id = :qeytoqrg_tovax_vmar_lt: WHERE id in (4020); # Tovax_Vmar 10
UPDATE npc_types SET loottable_id = :qeytoqrg_ubzial_iyeaql_lt: WHERE id in (4071); # Ubzial_Iyeaql 65
UPDATE npc_types SET loottable_id = :qeytoqrg_varsoon_lt: WHERE id in (4171); # Varsoon 25
UPDATE npc_types SET loottable_id = :qeytoqrg_varsoon_the_undying_lt: WHERE id in (4190); # Varsoon_the_Undying 30
UPDATE npc_types SET loottable_id = :qeytoqrg_waradern_skymoor_lt: WHERE id in (4204); # Waradern_Skymoor 50
UPDATE npc_types SET loottable_id = :qeytoqrg_wyle_bimlin_lt: WHERE id in (4073); # Wyle_Bimlin 20
UPDATE npc_types SET loottable_id = :qeytoqrg_yollis_jenkins_lt: WHERE id in (4046); # Yollis_Jenkins 12
