INSERT INTO loottable(name) VALUES('qrg_arrivae_valleren'); # :qrg_arrivae_valleren_lt:
INSERT INTO loottable(name) VALUES('qrg_a_bear_cub'); # :qrg_a_bear_cub_lt:
INSERT INTO loottable(name) VALUES('qrg_a_bloodsaber_defiler'); # :qrg_a_bloodsaber_defiler_lt:
INSERT INTO loottable(name) VALUES('qrg_a_brown_bear'); # :qrg_a_brown_bear_lt:
INSERT INTO loottable(name) VALUES('qrg_a_fish'); # :qrg_a_fish_lt:
INSERT INTO loottable(name) VALUES('qrg_a_grizzly_bear'); # :qrg_a_grizzly_bear_lt:
INSERT INTO loottable(name) VALUES('qrg_a_piranha'); # :qrg_a_piranha_lt:
INSERT INTO loottable(name) VALUES('qrg_a_poacher'); # :qrg_a_poacher_lt:
INSERT INTO loottable(name) VALUES('qrg_a_skulking_gnoll'); # :qrg_a_skulking_gnoll_lt:
INSERT INTO loottable(name) VALUES('qrg_bren_treeclimber'); # :qrg_bren_treeclimber_lt:
INSERT INTO loottable(name) VALUES('qrg_bukem_breewood'); # :qrg_bukem_breewood_lt:
INSERT INTO loottable(name) VALUES('qrg_corun_finisc'); # :qrg_corun_finisc_lt:
INSERT INTO loottable(name) VALUES('qrg_dannos_safecoin'); # :qrg_dannos_safecoin_lt:
INSERT INTO loottable(name) VALUES('qrg_donka_leafkeeper'); # :qrg_donka_leafkeeper_lt:
INSERT INTO loottable(name) VALUES('qrg_durvinna_barkkis'); # :qrg_durvinna_barkkis_lt:
INSERT INTO loottable(name) VALUES('qrg_errin_pinewhisper'); # :qrg_errin_pinewhisper_lt:
INSERT INTO loottable(name) VALUES('qrg_frannie'); # :qrg_frannie_lt:
INSERT INTO loottable(name) VALUES('qrg_frenway_marthank'); # :qrg_frenway_marthank_lt:
INSERT INTO loottable(name) VALUES('qrg_gemcrafter_anuk'); # :qrg_gemcrafter_anuk_lt:
INSERT INTO loottable(name) VALUES('qrg_gerael_woodone'); # :qrg_gerael_woodone_lt:
INSERT INTO loottable(name) VALUES('qrg_gillarian_naelev'); # :qrg_gillarian_naelev_lt:
INSERT INTO loottable(name) VALUES('qrg_gnoll_poacher'); # :qrg_gnoll_poacher_lt:
INSERT INTO loottable(name) VALUES('qrg_grathin_nilm'); # :qrg_grathin_nilm_lt:
INSERT INTO loottable(name) VALUES('qrg_guaril_leafkeeper'); # :qrg_guaril_leafkeeper_lt:
INSERT INTO loottable(name) VALUES('qrg_gurrin_nitestorm'); # :qrg_gurrin_nitestorm_lt:
INSERT INTO loottable(name) VALUES('qrg_hager_sureshot'); # :qrg_hager_sureshot_lt:
INSERT INTO loottable(name) VALUES('qrg_jarse_kedison'); # :qrg_jarse_kedison_lt:
INSERT INTO loottable(name) VALUES('qrg_jhaya_wyndrunner'); # :qrg_jhaya_wyndrunner_lt:
INSERT INTO loottable(name) VALUES('qrg_jpetimer'); # :qrg_jpetimer_lt:
INSERT INTO loottable(name) VALUES('qrg_krystal_aspen'); # :qrg_krystal_aspen_lt:
INSERT INTO loottable(name) VALUES('qrg_larsk_juton'); # :qrg_larsk_juton_lt:
INSERT INTO loottable(name) VALUES('qrg_lerian_wyndrunner'); # :qrg_lerian_wyndrunner_lt:
INSERT INTO loottable(name) VALUES('qrg_livam_tlant'); # :qrg_livam_tlant_lt:
INSERT INTO loottable(name) VALUES('qrg_mammoth'); # :qrg_mammoth_lt:
INSERT INTO loottable(name) VALUES('qrg_merdan_fleetfoot'); # :qrg_merdan_fleetfoot_lt:
INSERT INTO loottable(name) VALUES('qrg_merona_castekin'); # :qrg_merona_castekin_lt:
INSERT INTO loottable(name) VALUES('qrg_mikkai_nomak'); # :qrg_mikkai_nomak_lt:
INSERT INTO loottable(name) VALUES('qrg_narwkend_falgon'); # :qrg_narwkend_falgon_lt:
INSERT INTO loottable(name) VALUES('qrg_niera_farbreeze'); # :qrg_niera_farbreeze_lt:
INSERT INTO loottable(name) VALUES('qrg_poacher'); # :qrg_poacher_lt:
INSERT INTO loottable(name) VALUES('qrg_qaelin_hailstorm'); # :qrg_qaelin_hailstorm_lt:
INSERT INTO loottable(name) VALUES('qrg_qomber_roblen'); # :qrg_qomber_roblen_lt:
INSERT INTO loottable(name) VALUES('qrg_raken'); # :qrg_raken_lt:
INSERT INTO loottable(name) VALUES('qrg_ran_walker'); # :qrg_ran_walker_lt:
INSERT INTO loottable(name) VALUES('qrg_sallah'); # :qrg_sallah_lt:
INSERT INTO loottable(name) VALUES('qrg_salmekia_treherth'); # :qrg_salmekia_treherth_lt:
INSERT INTO loottable(name) VALUES('qrg_sequea_erthinon'); # :qrg_sequea_erthinon_lt:
INSERT INTO loottable(name) VALUES('qrg_sivina_lutewhisper'); # :qrg_sivina_lutewhisper_lt:
INSERT INTO loottable(name) VALUES('qrg_talym_shoontar'); # :qrg_talym_shoontar_lt:
INSERT INTO loottable(name) VALUES('qrg_teanara'); # :qrg_teanara_lt:
INSERT INTO loottable(name) VALUES('qrg_the_trees'); # :qrg_the_trees_lt:
INSERT INTO loottable(name) VALUES('qrg_tonsia'); # :qrg_tonsia_lt:
INSERT INTO loottable(name) VALUES('qrg_tralo_songsword'); # :qrg_tralo_songsword_lt:
INSERT INTO loottable(name) VALUES('qrg_vesteri_nomanoi'); # :qrg_vesteri_nomanoi_lt:
INSERT INTO loottable(name) VALUES('qrg_you_hear'); # :qrg_you_hear_lt:
