INSERT INTO loottable(name) VALUES('rathemtn_a_pile_of_froglok_remains'); # :rathemtn_a_pile_of_froglok_remains_lt:
INSERT INTO loottable(name) VALUES('rathemtn_bloodneedle'); # :rathemtn_bloodneedle_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_master_griblok'); # :rathemtn_dar_master_griblok_lt:
INSERT INTO loottable(name) VALUES('rathemtn_daynight'); # :rathemtn_daynight_lt:
INSERT INTO loottable(name) VALUES('rathemtn_fipok_glubble'); # :rathemtn_fipok_glubble_lt:
INSERT INTO loottable(name) VALUES('rathemtn_jin_master_sergug'); # :rathemtn_jin_master_sergug_lt:
INSERT INTO loottable(name) VALUES('rathemtn_kor_master_gloorg'); # :rathemtn_kor_master_gloorg_lt:
INSERT INTO loottable(name) VALUES('rathemtn_leatherhide'); # :rathemtn_leatherhide_lt:
INSERT INTO loottable(name) VALUES('rathemtn_sethena'); # :rathemtn_sethena_lt:
INSERT INTO loottable(name) VALUES('rathemtn_shin_master_grubbus'); # :rathemtn_shin_master_grubbus_lt:
INSERT INTO loottable(name) VALUES('rathemtn_yun_master_arglug'); # :rathemtn_yun_master_arglug_lt:
INSERT INTO loottable(name) VALUES('rathemtn_abigail'); # :rathemtn_abigail_lt:
INSERT INTO loottable(name) VALUES('rathemtn_albain_tinderbrand'); # :rathemtn_albain_tinderbrand_lt:
INSERT INTO loottable(name) VALUES('rathemtn_animal_trainer_visop'); # :rathemtn_animal_trainer_visop_lt:
INSERT INTO loottable(name) VALUES('rathemtn_ankhefenmut'); # :rathemtn_ankhefenmut_lt:
INSERT INTO loottable(name) VALUES('rathemtn_ankhesenaten'); # :rathemtn_ankhesenaten_lt:
INSERT INTO loottable(name) VALUES('rathemtn_ankhetperure'); # :rathemtn_ankhetperure_lt:
INSERT INTO loottable(name) VALUES('rathemtn_ankhnesmerira'); # :rathemtn_ankhnesmerira_lt:
INSERT INTO loottable(name) VALUES('rathemtn_anlut_heavenfall'); # :rathemtn_anlut_heavenfall_lt:
INSERT INTO loottable(name) VALUES('rathemtn_an_adult_bleeder'); # :rathemtn_an_adult_bleeder_lt:
INSERT INTO loottable(name) VALUES('rathemtn_an_ebon_drake'); # :rathemtn_an_ebon_drake_lt:
INSERT INTO loottable(name) VALUES('rathemtn_an_obsidian_drake'); # :rathemtn_an_obsidian_drake_lt:
INSERT INTO loottable(name) VALUES('rathemtn_an_onyx_drake'); # :rathemtn_an_onyx_drake_lt:
INSERT INTO loottable(name) VALUES('rathemtn_an_orc_priest'); # :rathemtn_an_orc_priest_lt:
INSERT INTO loottable(name) VALUES('rathemtn_an_orc_warrior'); # :rathemtn_an_orc_warrior_lt:
INSERT INTO loottable(name) VALUES('rathemtn_an_undead_servant'); # :rathemtn_an_undead_servant_lt:
INSERT INTO loottable(name) VALUES('rathemtn_an_unkempt_fanatic'); # :rathemtn_an_unkempt_fanatic_lt:
INSERT INTO loottable(name) VALUES('rathemtn_assistant_faldok'); # :rathemtn_assistant_faldok_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_bandit'); # :rathemtn_a_bandit_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_barbed_bone_skeleton'); # :rathemtn_a_barbed_bone_skeleton_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_basalt_drake'); # :rathemtn_a_basalt_drake_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_basilisk'); # :rathemtn_a_basilisk_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_black_bear'); # :rathemtn_a_black_bear_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_bleeder_pupa'); # :rathemtn_a_bleeder_pupa_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_brigand'); # :rathemtn_a_brigand_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_brown_bear'); # :rathemtn_a_brown_bear_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_burly_kobold'); # :rathemtn_a_burly_kobold_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_crab_spiderling'); # :rathemtn_a_crab_spiderling_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_cyclops'); # :rathemtn_a_cyclops_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_decaying_skeleton'); # :rathemtn_a_decaying_skeleton_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_domesticated_bleeder'); # :rathemtn_a_domesticated_bleeder_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_domesticated_hatchling'); # :rathemtn_a_domesticated_hatchling_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_drake'); # :rathemtn_a_drake_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_feral_bleeder'); # :rathemtn_a_feral_bleeder_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_fire_beetle'); # :rathemtn_a_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_froglok_exile'); # :rathemtn_a_froglok_exile_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_froglok_guardsman'); # :rathemtn_a_froglok_guardsman_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_froglok_traitor'); # :rathemtn_a_froglok_traitor_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_frostfell_goblin'); # :rathemtn_a_frostfell_goblin_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_fungus_man_tracker'); # :rathemtn_a_fungus_man_tracker_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_fungus_spore'); # :rathemtn_a_fungus_spore_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_fungus_sporeling'); # :rathemtn_a_fungus_sporeling_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_giant_moccasin'); # :rathemtn_a_giant_moccasin_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_giant_skeleton'); # :rathemtn_a_giant_skeleton_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_grizzly_bear'); # :rathemtn_a_grizzly_bear_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_hill_giant'); # :rathemtn_a_hill_giant_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_kobold'); # :rathemtn_a_kobold_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_kodiak_bear'); # :rathemtn_a_kodiak_bear_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_larval_bleeder'); # :rathemtn_a_larval_bleeder_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_lesser_spirit'); # :rathemtn_a_lesser_spirit_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_lizardman_healer'); # :rathemtn_a_lizardman_healer_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_lizardman_mystic'); # :rathemtn_a_lizardman_mystic_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_lizardman_robber'); # :rathemtn_a_lizardman_robber_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_lizardman_warrior'); # :rathemtn_a_lizardman_warrior_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_minion_of_ytyrs'); # :rathemtn_a_minion_of_ytyrs_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_monstrous_zombie'); # :rathemtn_a_monstrous_zombie_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_skeletal_monk'); # :rathemtn_a_skeletal_monk_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_skeleton'); # :rathemtn_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_teirdal_priest'); # :rathemtn_a_teirdal_priest_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_teirdal_spellbinder'); # :rathemtn_a_teirdal_spellbinder_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_tough_skinned_larvae'); # :rathemtn_a_tough_skinned_larvae_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_troll_greenblood'); # :rathemtn_a_troll_greenblood_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_troll_invader'); # :rathemtn_a_troll_invader_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_troll_marauder'); # :rathemtn_a_troll_marauder_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_water_moccasin'); # :rathemtn_a_water_moccasin_lt:
INSERT INTO loottable(name) VALUES('rathemtn_a_zombie'); # :rathemtn_a_zombie_lt:
INSERT INTO loottable(name) VALUES('rathemtn_bibsy_gakdoo'); # :rathemtn_bibsy_gakdoo_lt:
INSERT INTO loottable(name) VALUES('rathemtn_bindlegrob'); # :rathemtn_bindlegrob_lt:
INSERT INTO loottable(name) VALUES('rathemtn_blackwing'); # :rathemtn_blackwing_lt:
INSERT INTO loottable(name) VALUES('rathemtn_blinde_the_cutpurse'); # :rathemtn_blinde_the_cutpurse_lt:
INSERT INTO loottable(name) VALUES('rathemtn_bok_master_thragnog'); # :rathemtn_bok_master_thragnog_lt:
INSERT INTO loottable(name) VALUES('rathemtn_brill'); # :rathemtn_brill_lt:
INSERT INTO loottable(name) VALUES('rathemtn_broog_bloodbeard'); # :rathemtn_broog_bloodbeard_lt:
INSERT INTO loottable(name) VALUES('rathemtn_brother_zephyl'); # :rathemtn_brother_zephyl_lt:
INSERT INTO loottable(name) VALUES('rathemtn_bunk_odon'); # :rathemtn_bunk_odon_lt:
INSERT INTO loottable(name) VALUES('rathemtn_cathendra_bo'); # :rathemtn_cathendra_bo_lt:
INSERT INTO loottable(name) VALUES('rathemtn_chalex_the_redeemed'); # :rathemtn_chalex_the_redeemed_lt:
INSERT INTO loottable(name) VALUES('rathemtn_chandra_kali'); # :rathemtn_chandra_kali_lt:
INSERT INTO loottable(name) VALUES('rathemtn_chizzlik'); # :rathemtn_chizzlik_lt:
INSERT INTO loottable(name) VALUES('rathemtn_colgon_dursaar'); # :rathemtn_colgon_dursaar_lt:
INSERT INTO loottable(name) VALUES('rathemtn_corrupted_hill_giant'); # :rathemtn_corrupted_hill_giant_lt:
INSERT INTO loottable(name) VALUES('rathemtn_cynthia'); # :rathemtn_cynthia_lt:
INSERT INTO loottable(name) VALUES('rathemtn_darfumpel_zirubbel'); # :rathemtn_darfumpel_zirubbel_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_banker_zlopps'); # :rathemtn_dar_banker_zlopps_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_collector_reokar'); # :rathemtn_dar_collector_reokar_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_forager_lumun'); # :rathemtn_dar_forager_lumun_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_guard_broktl'); # :rathemtn_dar_guard_broktl_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_guard_fnabble'); # :rathemtn_dar_guard_fnabble_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_guard_gflabbiel'); # :rathemtn_dar_guard_gflabbiel_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_guard_lraktol'); # :rathemtn_dar_guard_lraktol_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_guard_mroktla'); # :rathemtn_dar_guard_mroktla_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_guard_zraktl'); # :rathemtn_dar_guard_zraktl_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dar_strategist_guib'); # :rathemtn_dar_strategist_guib_lt:
INSERT INTO loottable(name) VALUES('rathemtn_david'); # :rathemtn_david_lt:
INSERT INTO loottable(name) VALUES('rathemtn_delila'); # :rathemtn_delila_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dellweena_bruann'); # :rathemtn_dellweena_bruann_lt:
INSERT INTO loottable(name) VALUES('rathemtn_drayen_blackguard'); # :rathemtn_drayen_blackguard_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dry_bone_skeleton'); # :rathemtn_dry_bone_skeleton_lt:
INSERT INTO loottable(name) VALUES('rathemtn_dven_tulvnek'); # :rathemtn_dven_tulvnek_lt:
INSERT INTO loottable(name) VALUES('rathemtn_elisabeth'); # :rathemtn_elisabeth_lt:
INSERT INTO loottable(name) VALUES('rathemtn_exterminator_galub'); # :rathemtn_exterminator_galub_lt:
INSERT INTO loottable(name) VALUES('rathemtn_fandl_arathin'); # :rathemtn_fandl_arathin_lt:
INSERT INTO loottable(name) VALUES('rathemtn_findlegrob'); # :rathemtn_findlegrob_lt:
INSERT INTO loottable(name) VALUES('rathemtn_fipnoc_birribit'); # :rathemtn_fipnoc_birribit_lt:
INSERT INTO loottable(name) VALUES('rathemtn_fireworks_engineer_fabdabus'); # :rathemtn_fireworks_engineer_fabdabus_lt:
INSERT INTO loottable(name) VALUES('rathemtn_gaz_commander_faltip'); # :rathemtn_gaz_commander_faltip_lt:
INSERT INTO loottable(name) VALUES('rathemtn_gaz_master_shargnol'); # :rathemtn_gaz_master_shargnol_lt:
INSERT INTO loottable(name) VALUES('rathemtn_gikkl_duguug'); # :rathemtn_gikkl_duguug_lt:
INSERT INTO loottable(name) VALUES('rathemtn_glaron_the_wicked'); # :rathemtn_glaron_the_wicked_lt:
INSERT INTO loottable(name) VALUES('rathemtn_goaad_mistigone'); # :rathemtn_goaad_mistigone_lt:
INSERT INTO loottable(name) VALUES('rathemtn_grazhak_the_berzerker'); # :rathemtn_grazhak_the_berzerker_lt:
INSERT INTO loottable(name) VALUES('rathemtn_guard_carnita'); # :rathemtn_guard_carnita_lt:
INSERT INTO loottable(name) VALUES('rathemtn_guard_dykalin'); # :rathemtn_guard_dykalin_lt:
INSERT INTO loottable(name) VALUES('rathemtn_guard_fernaldo'); # :rathemtn_guard_fernaldo_lt:
INSERT INTO loottable(name) VALUES('rathemtn_guard_gruilka'); # :rathemtn_guard_gruilka_lt:
INSERT INTO loottable(name) VALUES('rathemtn_guard_shiznak'); # :rathemtn_guard_shiznak_lt:
INSERT INTO loottable(name) VALUES('rathemtn_guzzla'); # :rathemtn_guzzla_lt:
INSERT INTO loottable(name) VALUES('rathemtn_gwynn_marthank'); # :rathemtn_gwynn_marthank_lt:
INSERT INTO loottable(name) VALUES('rathemtn_hargar_the_velium_chef'); # :rathemtn_hargar_the_velium_chef_lt:
INSERT INTO loottable(name) VALUES('rathemtn_hasten_bootstrutter'); # :rathemtn_hasten_bootstrutter_lt:
INSERT INTO loottable(name) VALUES('rathemtn_high_seer_flogk'); # :rathemtn_high_seer_flogk_lt:
INSERT INTO loottable(name) VALUES('rathemtn_hogus_durmas'); # :rathemtn_hogus_durmas_lt:
INSERT INTO loottable(name) VALUES('rathemtn_ice_bone_skeleton'); # :rathemtn_ice_bone_skeleton_lt:
INSERT INTO loottable(name) VALUES('rathemtn_initiate_xabbis'); # :rathemtn_initiate_xabbis_lt:
INSERT INTO loottable(name) VALUES('rathemtn_innkeep_serge'); # :rathemtn_innkeep_serge_lt:
INSERT INTO loottable(name) VALUES('rathemtn_innkeep_troy'); # :rathemtn_innkeep_troy_lt:
INSERT INTO loottable(name) VALUES('rathemtn_jars_legola'); # :rathemtn_jars_legola_lt:
INSERT INTO loottable(name) VALUES('rathemtn_jyle_windstorm'); # :rathemtn_jyle_windstorm_lt:
INSERT INTO loottable(name) VALUES('rathemtn_karam_dragonforge'); # :rathemtn_karam_dragonforge_lt:
INSERT INTO loottable(name) VALUES('rathemtn_kathryn'); # :rathemtn_kathryn_lt:
INSERT INTO loottable(name) VALUES('rathemtn_kazzel_dleryt'); # :rathemtn_kazzel_dleryt_lt:
INSERT INTO loottable(name) VALUES('rathemtn_kedryll_tindle'); # :rathemtn_kedryll_tindle_lt:
INSERT INTO loottable(name) VALUES('rathemtn_kindra_farseer'); # :rathemtn_kindra_farseer_lt:
INSERT INTO loottable(name) VALUES('rathemtn_kor_master_ralg'); # :rathemtn_kor_master_ralg_lt:
INSERT INTO loottable(name) VALUES('rathemtn_kor_protector_durlonz'); # :rathemtn_kor_protector_durlonz_lt:
INSERT INTO loottable(name) VALUES('rathemtn_kor_trainer_galdok'); # :rathemtn_kor_trainer_galdok_lt:
INSERT INTO loottable(name) VALUES('rathemtn_lianna_ferasa'); # :rathemtn_lianna_ferasa_lt:
INSERT INTO loottable(name) VALUES('rathemtn_loancal_joonan'); # :rathemtn_loancal_joonan_lt:
INSERT INTO loottable(name) VALUES('rathemtn_lokta_elder_dibbig'); # :rathemtn_lokta_elder_dibbig_lt:
INSERT INTO loottable(name) VALUES('rathemtn_lokta_elder_froops'); # :rathemtn_lokta_elder_froops_lt:
INSERT INTO loottable(name) VALUES('rathemtn_lokta_elder_ginnid'); # :rathemtn_lokta_elder_ginnid_lt:
INSERT INTO loottable(name) VALUES('rathemtn_lokta_elder_gritib'); # :rathemtn_lokta_elder_gritib_lt:
INSERT INTO loottable(name) VALUES('rathemtn_lokta_elder_nywlek'); # :rathemtn_lokta_elder_nywlek_lt:
INSERT INTO loottable(name) VALUES('rathemtn_lokta_elder_sigig'); # :rathemtn_lokta_elder_sigig_lt:
INSERT INTO loottable(name) VALUES('rathemtn_lysandra'); # :rathemtn_lysandra_lt:
INSERT INTO loottable(name) VALUES('rathemtn_maldyn_the_unkempt'); # :rathemtn_maldyn_the_unkempt_lt:
INSERT INTO loottable(name) VALUES('rathemtn_marianna'); # :rathemtn_marianna_lt:
INSERT INTO loottable(name) VALUES('rathemtn_master_scribe_uklo'); # :rathemtn_master_scribe_uklo_lt:
INSERT INTO loottable(name) VALUES('rathemtn_meelana'); # :rathemtn_meelana_lt:
INSERT INTO loottable(name) VALUES('rathemtn_memory_of_chalex'); # :rathemtn_memory_of_chalex_lt:
INSERT INTO loottable(name) VALUES('rathemtn_meridith_tindle'); # :rathemtn_meridith_tindle_lt:
INSERT INTO loottable(name) VALUES('rathemtn_mortificator_syythrak'); # :rathemtn_mortificator_syythrak_lt:
INSERT INTO loottable(name) VALUES('rathemtn_nancine'); # :rathemtn_nancine_lt:
INSERT INTO loottable(name) VALUES('rathemtn_nemeen_pekasr'); # :rathemtn_nemeen_pekasr_lt:
INSERT INTO loottable(name) VALUES('rathemtn_nicholas'); # :rathemtn_nicholas_lt:
INSERT INTO loottable(name) VALUES('rathemtn_nola_thistleborn'); # :rathemtn_nola_thistleborn_lt:
INSERT INTO loottable(name) VALUES('rathemtn_oculys_ogrefiend'); # :rathemtn_oculys_ogrefiend_lt:
INSERT INTO loottable(name) VALUES('rathemtn_peltin_funter'); # :rathemtn_peltin_funter_lt:
INSERT INTO loottable(name) VALUES('rathemtn_petrifin'); # :rathemtn_petrifin_lt:
INSERT INTO loottable(name) VALUES('rathemtn_philicia_drinn'); # :rathemtn_philicia_drinn_lt:
INSERT INTO loottable(name) VALUES('rathemtn_priest_of_discord'); # :rathemtn_priest_of_discord_lt:
INSERT INTO loottable(name) VALUES('rathemtn_quartermaster_grik'); # :rathemtn_quartermaster_grik_lt:
INSERT INTO loottable(name) VALUES('rathemtn_quid_rilstone'); # :rathemtn_quid_rilstone_lt:
INSERT INTO loottable(name) VALUES('rathemtn_rambling_sphinx_spiritservant'); # :rathemtn_rambling_sphinx_spiritservant_lt:
INSERT INTO loottable(name) VALUES('rathemtn_raving_sphinx_spiritservant'); # :rathemtn_raving_sphinx_spiritservant_lt:
INSERT INTO loottable(name) VALUES('rathemtn_rell_ostodl'); # :rathemtn_rell_ostodl_lt:
INSERT INTO loottable(name) VALUES('rathemtn_rharzar'); # :rathemtn_rharzar_lt:
INSERT INTO loottable(name) VALUES('rathemtn_roshmael'); # :rathemtn_roshmael_lt:
INSERT INTO loottable(name) VALUES('rathemtn_santug_claugg'); # :rathemtn_santug_claugg_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_biddlegorb'); # :rathemtn_scribe_biddlegorb_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_figglebog'); # :rathemtn_scribe_figglebog_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_flogglebig'); # :rathemtn_scribe_flogglebig_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_florgg'); # :rathemtn_scribe_florgg_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_garp'); # :rathemtn_scribe_garp_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_gokk'); # :rathemtn_scribe_gokk_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_gralke'); # :rathemtn_scribe_gralke_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_noglleg'); # :rathemtn_scribe_noglleg_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_rikik'); # :rathemtn_scribe_rikik_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_vordangl'); # :rathemtn_scribe_vordangl_lt:
INSERT INTO loottable(name) VALUES('rathemtn_scribe_yoss'); # :rathemtn_scribe_yoss_lt:
INSERT INTO loottable(name) VALUES('rathemtn_sentry_joanna'); # :rathemtn_sentry_joanna_lt:
INSERT INTO loottable(name) VALUES('rathemtn_sergeant_herptol'); # :rathemtn_sergeant_herptol_lt:
INSERT INTO loottable(name) VALUES('rathemtn_shardwing'); # :rathemtn_shardwing_lt:
INSERT INTO loottable(name) VALUES('rathemtn_sheldon'); # :rathemtn_sheldon_lt:
INSERT INTO loottable(name) VALUES('rathemtn_sindlegrob'); # :rathemtn_sindlegrob_lt:
INSERT INTO loottable(name) VALUES('rathemtn_sir_edwin_motte'); # :rathemtn_sir_edwin_motte_lt:
INSERT INTO loottable(name) VALUES('rathemtn_solvedi_aldeberan'); # :rathemtn_solvedi_aldeberan_lt:
INSERT INTO loottable(name) VALUES('rathemtn_srekta_froreki'); # :rathemtn_srekta_froreki_lt:
INSERT INTO loottable(name) VALUES('rathemtn_sugal_the_fist'); # :rathemtn_sugal_the_fist_lt:
INSERT INTO loottable(name) VALUES('rathemtn_susanna'); # :rathemtn_susanna_lt:
INSERT INTO loottable(name) VALUES('rathemtn_sven_drinn'); # :rathemtn_sven_drinn_lt:
INSERT INTO loottable(name) VALUES('rathemtn_sylp_tyanathin'); # :rathemtn_sylp_tyanathin_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tabien_the_goodly'); # :rathemtn_tabien_the_goodly_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tainted_hill_giant'); # :rathemtn_tainted_hill_giant_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tal_godin'); # :rathemtn_tal_godin_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tann_cellus'); # :rathemtn_tann_cellus_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tarikh_korula'); # :rathemtn_tarikh_korula_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tarskuk'); # :rathemtn_tarskuk_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tholia_fastbond'); # :rathemtn_tholia_fastbond_lt:
INSERT INTO loottable(name) VALUES('rathemtn_thomas'); # :rathemtn_thomas_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tibrinn_ember'); # :rathemtn_tibrinn_ember_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tomas'); # :rathemtn_tomas_lt:
INSERT INTO loottable(name) VALUES('rathemtn_troll_captain_krignok'); # :rathemtn_troll_captain_krignok_lt:
INSERT INTO loottable(name) VALUES('rathemtn_tugog_grigol'); # :rathemtn_tugog_grigol_lt:
INSERT INTO loottable(name) VALUES('rathemtn_ukla'); # :rathemtn_ukla_lt:
INSERT INTO loottable(name) VALUES('rathemtn_undead_troll_marauder'); # :rathemtn_undead_troll_marauder_lt:
INSERT INTO loottable(name) VALUES('rathemtn_unkempt_preserver'); # :rathemtn_unkempt_preserver_lt:
INSERT INTO loottable(name) VALUES('rathemtn_viira_bali'); # :rathemtn_viira_bali_lt:
INSERT INTO loottable(name) VALUES('rathemtn_warrior_spirit_chalex'); # :rathemtn_warrior_spirit_chalex_lt:
INSERT INTO loottable(name) VALUES('rathemtn_xenyari_lisariel'); # :rathemtn_xenyari_lisariel_lt:
INSERT INTO loottable(name) VALUES('rathemtn_yilbit_gerbigo'); # :rathemtn_yilbit_gerbigo_lt:
INSERT INTO loottable(name) VALUES('rathemtn_ytyrs_reborn'); # :rathemtn_ytyrs_reborn_lt:
INSERT INTO loottable(name) VALUES('rathemtn_ytyrs_the_reborn'); # :rathemtn_ytyrs_the_reborn_lt:
INSERT INTO loottable(name) VALUES('rathemtn_yun_protector_kaewhis'); # :rathemtn_yun_protector_kaewhis_lt:
INSERT INTO loottable(name) VALUES('rathemtn_yun_trainer_kintok'); # :rathemtn_yun_trainer_kintok_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zazamaharet'); # :rathemtn_zazamaharet_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zazamenhu'); # :rathemtn_zazamenhu_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zazamoukh'); # :rathemtn_zazamoukh_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zazaphenebti'); # :rathemtn_zazaphenebti_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zepin_winsle'); # :rathemtn_zepin_winsle_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zokta_elder_fogug'); # :rathemtn_zokta_elder_fogug_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zokta_elder_gubbigo'); # :rathemtn_zokta_elder_gubbigo_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zokta_elder_reebig'); # :rathemtn_zokta_elder_reebig_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zokta_elder_riobbin'); # :rathemtn_zokta_elder_riobbin_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zokta_noble_bribbiz'); # :rathemtn_zokta_noble_bribbiz_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zokta_noble_groobl'); # :rathemtn_zokta_noble_groobl_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_caropni'); # :rathemtn_zok_caropni_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_crikk'); # :rathemtn_zok_crikk_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_dendrung'); # :rathemtn_zok_dendrung_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_drup'); # :rathemtn_zok_drup_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_folis'); # :rathemtn_zok_folis_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_froob'); # :rathemtn_zok_froob_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_giibles'); # :rathemtn_zok_giibles_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_giisip'); # :rathemtn_zok_giisip_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_gimar'); # :rathemtn_zok_gimar_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_glag'); # :rathemtn_zok_glag_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_gleeup'); # :rathemtn_zok_gleeup_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_gluchh'); # :rathemtn_zok_gluchh_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_gorble'); # :rathemtn_zok_gorble_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_gribbl'); # :rathemtn_zok_gribbl_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_grop'); # :rathemtn_zok_grop_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_huoo'); # :rathemtn_zok_huoo_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_kilikko'); # :rathemtn_zok_kilikko_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_kuluree'); # :rathemtn_zok_kuluree_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_lillis'); # :rathemtn_zok_lillis_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_lubump'); # :rathemtn_zok_lubump_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_malka'); # :rathemtn_zok_malka_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_moic'); # :rathemtn_zok_moic_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_pirk'); # :rathemtn_zok_pirk_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_prolo'); # :rathemtn_zok_prolo_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_ruppeta'); # :rathemtn_zok_ruppeta_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_rurpp'); # :rathemtn_zok_rurpp_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_seleka'); # :rathemtn_zok_seleka_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_sevrana'); # :rathemtn_zok_sevrana_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_sliips'); # :rathemtn_zok_sliips_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_tabruu'); # :rathemtn_zok_tabruu_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_virek'); # :rathemtn_zok_virek_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_vroog'); # :rathemtn_zok_vroog_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zok_zribb'); # :rathemtn_zok_zribb_lt:
INSERT INTO loottable(name) VALUES('rathemtn_zol_master_malgorn'); # :rathemtn_zol_master_malgorn_lt:
INSERT INTO loottable(name) VALUES('rathemtn__'); # :rathemtn___lt:
