INSERT INTO loottable(name) VALUES('runnyeye_a_herald_of_mischief'); # :runnyeye_a_herald_of_mischief_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_crusader'); # :runnyeye_a_pickclaw_crusader_lt:
INSERT INTO loottable(name) VALUES('runnyeye_battlelord_paluk'); # :runnyeye_battlelord_paluk_lt:
INSERT INTO loottable(name) VALUES('runnyeye_battlewizard_unak'); # :runnyeye_battlewizard_unak_lt:
INSERT INTO loottable(name) VALUES('runnyeye_lord_pickclaw'); # :runnyeye_lord_pickclaw_lt:
INSERT INTO loottable(name) VALUES('runnyeye_the_sporali_moldmaster'); # :runnyeye_the_sporali_moldmaster_lt:
INSERT INTO loottable(name) VALUES('runnyeye_an_evil_eye_prisoner'); # :runnyeye_an_evil_eye_prisoner_lt:
INSERT INTO loottable(name) VALUES('runnyeye_an_ooze_crawler'); # :runnyeye_an_ooze_crawler_lt:
INSERT INTO loottable(name) VALUES('runnyeye_an_unbelievable'); # :runnyeye_an_unbelievable_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_goblin_banker'); # :runnyeye_a_goblin_banker_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_goblin_bartender'); # :runnyeye_a_goblin_bartender_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_goblin_merchant'); # :runnyeye_a_goblin_merchant_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_goblin_neophyte'); # :runnyeye_a_goblin_neophyte_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_goblin_peon'); # :runnyeye_a_goblin_peon_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_goblin_runt'); # :runnyeye_a_goblin_runt_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_goblin_scavenger'); # :runnyeye_a_goblin_scavenger_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_goblin_trainee'); # :runnyeye_a_goblin_trainee_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_layer'); # :runnyeye_a_layer_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_mimic'); # :runnyeye_a_mimic_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_ambushbaiter'); # :runnyeye_a_pickclaw_ambushbaiter_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_arroweater'); # :runnyeye_a_pickclaw_arroweater_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_bladestopper'); # :runnyeye_a_pickclaw_bladestopper_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_bonemender'); # :runnyeye_a_pickclaw_bonemender_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_destroyer'); # :runnyeye_a_pickclaw_destroyer_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_fleshburner'); # :runnyeye_a_pickclaw_fleshburner_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_foechopper'); # :runnyeye_a_pickclaw_foechopper_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_foeseeker'); # :runnyeye_a_pickclaw_foeseeker_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_foeslicer'); # :runnyeye_a_pickclaw_foeslicer_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_mindripper'); # :runnyeye_a_pickclaw_mindripper_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_slayspell'); # :runnyeye_a_pickclaw_slayspell_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_thoughtshaper'); # :runnyeye_a_pickclaw_thoughtshaper_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_veteran'); # :runnyeye_a_pickclaw_veteran_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pickclaw_zekspeaker'); # :runnyeye_a_pickclaw_zekspeaker_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_pile_of_mold'); # :runnyeye_a_pile_of_mold_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_runnyeye_conscript'); # :runnyeye_a_runnyeye_conscript_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_runnyeye_trustee'); # :runnyeye_a_runnyeye_trustee_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_sharp_rock'); # :runnyeye_a_sharp_rock_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_slime_elemental'); # :runnyeye_a_slime_elemental_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_slime_mold'); # :runnyeye_a_slime_mold_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_sludge_guppy'); # :runnyeye_a_sludge_guppy_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_sporali_defender'); # :runnyeye_a_sporali_defender_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_sporali_gatherer'); # :runnyeye_a_sporali_gatherer_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_sporali_miner'); # :runnyeye_a_sporali_miner_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_sporali_scavenger'); # :runnyeye_a_sporali_scavenger_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_sporali_worker'); # :runnyeye_a_sporali_worker_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_sporeling'); # :runnyeye_a_sporeling_lt:
INSERT INTO loottable(name) VALUES('runnyeye_a_sporelit'); # :runnyeye_a_sporelit_lt:
INSERT INTO loottable(name) VALUES('runnyeye_goblin_janitor'); # :runnyeye_goblin_janitor_lt:
INSERT INTO loottable(name) VALUES('runnyeye_if_the'); # :runnyeye_if_the_lt:
INSERT INTO loottable(name) VALUES('runnyeye_perhaps'); # :runnyeye_perhaps_lt:
INSERT INTO loottable(name) VALUES('runnyeye_progressing'); # :runnyeye_progressing_lt:
INSERT INTO loottable(name) VALUES('runnyeye_sludge_dankmire'); # :runnyeye_sludge_dankmire_lt:
INSERT INTO loottable(name) VALUES('runnyeye_the_constant'); # :runnyeye_the_constant_lt:
INSERT INTO loottable(name) VALUES('runnyeye_thoughts'); # :runnyeye_thoughts_lt:
INSERT INTO loottable(name) VALUES('runnyeye_you_are'); # :runnyeye_you_are_lt:
INSERT INTO loottable(name) VALUES('runnyeye_you_feel'); # :runnyeye_you_feel_lt:
