INSERT INTO loottable(name) VALUES('soldunga_safetynet'); # :soldunga_safetynet_lt:
INSERT INTO loottable(name) VALUES('soldunga_the_fabled_cwg_model_exg'); # :soldunga_the_fabled_cwg_model_exg_lt:
INSERT INTO loottable(name) VALUES('soldunga_the_fabled_gabbie_mardoddle'); # :soldunga_the_fabled_gabbie_mardoddle_lt:
INSERT INTO loottable(name) VALUES('soldunga_blazing_elemental'); # :soldunga_blazing_elemental_lt:
INSERT INTO loottable(name) VALUES('soldunga_captain_bipnubble'); # :soldunga_captain_bipnubble_lt:
INSERT INTO loottable(name) VALUES('soldunga_cinder_goblin'); # :soldunga_cinder_goblin_lt:
INSERT INTO loottable(name) VALUES('soldunga_cinder_goblin_shaman'); # :soldunga_cinder_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('soldunga_cinder_goblin_wizard'); # :soldunga_cinder_goblin_wizard_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_ca'); # :soldunga_cwg_model_ca_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_cb'); # :soldunga_cwg_model_cb_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_cc'); # :soldunga_cwg_model_cc_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_cx'); # :soldunga_cwg_model_cx_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_exg'); # :soldunga_cwg_model_exg_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_ma'); # :soldunga_cwg_model_ma_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_mb'); # :soldunga_cwg_model_mb_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_mc'); # :soldunga_cwg_model_mc_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_xa'); # :soldunga_cwg_model_xa_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_xb'); # :soldunga_cwg_model_xb_lt:
INSERT INTO loottable(name) VALUES('soldunga_cwg_model_xc'); # :soldunga_cwg_model_xc_lt:
INSERT INTO loottable(name) VALUES('soldunga_cws_model_sx'); # :soldunga_cws_model_sx_lt:
INSERT INTO loottable(name) VALUES('soldunga_fire_goblin'); # :soldunga_fire_goblin_lt:
INSERT INTO loottable(name) VALUES('soldunga_fire_goblin_bartender'); # :soldunga_fire_goblin_bartender_lt:
INSERT INTO loottable(name) VALUES('soldunga_fire_goblin_shaman'); # :soldunga_fire_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('soldunga_fire_goblin_wizard'); # :soldunga_fire_goblin_wizard_lt:
INSERT INTO loottable(name) VALUES('soldunga_flame_goblin'); # :soldunga_flame_goblin_lt:
INSERT INTO loottable(name) VALUES('soldunga_flame_goblin_foreman'); # :soldunga_flame_goblin_foreman_lt:
INSERT INTO loottable(name) VALUES('soldunga_flame_goblin_shaman'); # :soldunga_flame_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('soldunga_flame_goblin_wizard'); # :soldunga_flame_goblin_wizard_lt:
INSERT INTO loottable(name) VALUES('soldunga_gabbie_mardoddle'); # :soldunga_gabbie_mardoddle_lt:
INSERT INTO loottable(name) VALUES('soldunga_gnomish_conjurer'); # :soldunga_gnomish_conjurer_lt:
INSERT INTO loottable(name) VALUES('soldunga_gnomish_curator'); # :soldunga_gnomish_curator_lt:
INSERT INTO loottable(name) VALUES('soldunga_gnomish_miner'); # :soldunga_gnomish_miner_lt:
INSERT INTO loottable(name) VALUES('soldunga_goblin_drunkard'); # :soldunga_goblin_drunkard_lt:
INSERT INTO loottable(name) VALUES('soldunga_goblin_high_shaman'); # :soldunga_goblin_high_shaman_lt:
INSERT INTO loottable(name) VALUES('soldunga_goblin_merchant'); # :soldunga_goblin_merchant_lt:
INSERT INTO loottable(name) VALUES('soldunga_inferno_goblin'); # :soldunga_inferno_goblin_lt:
INSERT INTO loottable(name) VALUES('soldunga_inferno_goblin_captain'); # :soldunga_inferno_goblin_captain_lt:
INSERT INTO loottable(name) VALUES('soldunga_inferno_goblin_shaman'); # :soldunga_inferno_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('soldunga_inferno_goblin_torturer'); # :soldunga_inferno_goblin_torturer_lt:
INSERT INTO loottable(name) VALUES('soldunga_inferno_goblin_wizard'); # :soldunga_inferno_goblin_wizard_lt:
INSERT INTO loottable(name) VALUES('soldunga_kindle'); # :soldunga_kindle_lt:
INSERT INTO loottable(name) VALUES('soldunga_kobold_predator'); # :soldunga_kobold_predator_lt:
INSERT INTO loottable(name) VALUES('soldunga_large_fire_goblin'); # :soldunga_large_fire_goblin_lt:
INSERT INTO loottable(name) VALUES('soldunga_lava_elemental'); # :soldunga_lava_elemental_lt:
INSERT INTO loottable(name) VALUES('soldunga_lord_gimblox'); # :soldunga_lord_gimblox_lt:
INSERT INTO loottable(name) VALUES('soldunga_lynada_the_exiled'); # :soldunga_lynada_the_exiled_lt:
INSERT INTO loottable(name) VALUES('soldunga_marfen_binkdirple'); # :soldunga_marfen_binkdirple_lt:
INSERT INTO loottable(name) VALUES('soldunga_reckless_efreeti'); # :soldunga_reckless_efreeti_lt:
INSERT INTO loottable(name) VALUES('soldunga_singe'); # :soldunga_singe_lt:
INSERT INTO loottable(name) VALUES('soldunga_solusek_champion'); # :soldunga_solusek_champion_lt:
INSERT INTO loottable(name) VALUES('soldunga_solusek_goblin'); # :soldunga_solusek_goblin_lt:
INSERT INTO loottable(name) VALUES('soldunga_solusek_goblin_king'); # :soldunga_solusek_goblin_king_lt:
INSERT INTO loottable(name) VALUES('soldunga_solusek_mage'); # :soldunga_solusek_mage_lt:
INSERT INTO loottable(name) VALUES('soldunga_solusek_priest'); # :soldunga_solusek_priest_lt:
INSERT INTO loottable(name) VALUES('soldunga_young_goblin'); # :soldunga_young_goblin_lt:
INSERT INTO loottable(name) VALUES('soldunga_young_goblin_shaman'); # :soldunga_young_goblin_shaman_lt:
INSERT INTO loottable(name) VALUES('soldunga_young_goblin_wizard'); # :soldunga_young_goblin_wizard_lt:
