
(:soldungb_a_greater_kobold_lt:, :cloth_small_ld:, 1),
(:soldungb_a_greater_kobold_lt:, :fine_steel_ld:, 1),
(:soldungb_a_greater_kobold_lt:, :rusty_ld:, 5),
(:soldungb_efreeti_lord_djarn_lt:, :fine_steel_ld:, 1),
(:soldungb_fire_giant_wizard_lt:, :fine_steel_ld:, 1),
(:soldungb_greater_kobold_lt:, :bronze_armor_ld:, 1),
(:soldungb_greater_kobold_lt:, :fine_steel_ld:, 1),
(:soldungb_greater_kobold_shaman_lt:, :cloth_small_ld:, 1),
(:soldungb_greater_kobold_shaman_lt:, :fine_steel_ld:, 1),
(:soldungb_greater_kobold_shaman_lt:, :rusty_ld:, 5),
(:soldungb_guano_harvester_lt:, :cloth_small_ld:, 1),
(:soldungb_guano_harvester_lt:, :rusty_ld:),(1, :soldungb_fire_giant_warrior_lt:, :fine_steel_ld:, 5),
(:soldungb_imp_protector_lt:, :fine_steel_ld:, 1),
(:soldungb_king_tranix_lt:, :fine_steel_ld:, 1),
(:soldungb_kobold_champion_lt:, :bronze_armor_ld:, 1),
(:soldungb_kobold_champion_lt:, :fine_steel_ld:, 1),
(:soldungb_kobold_priest_lt:, :bronze_armor_ld:, 1),
(:soldungb_kobold_priest_lt:, :fine_steel_ld:, 1),
(:soldungb_magus_rokyl_lt:, :fine_steel_ld:, 1),
(:soldungb_solusek_kobold_king_lt:, :bronze_armor_ld:, 1),
(:soldungb_solusek_kobold_king_lt:, :fine_steel_ld:, 1),
(:soldungb_solusek_kobold_lt:, :bronze_armor_ld:, 1),
(:soldungb_solusek_kobold_lt:, :fine_steel_ld:, 1),
(:soldungb_solusek_kobold_shaman_lt:, :cloth_small_ld:, 1),
(:soldungb_solusek_kobold_shaman_lt:, :fine_steel_ld:, 1),
(:soldungb_solusek_kobold_shaman_lt:, :rusty_ld:, 5),
(:soldungb_warlord_skarlon_lt:, :fine_steel_ld:, 1),(:soldungb_a_greater_kobold_lt:, :buckler_ld:, 1),
(:soldungb_solusek_kobold_shaman_lt:, :buckler_ld:, 1),
(:soldungb_kobold_noble_lt:, :buckler_ld:, 1),
(:soldungb_greater_kobold_shaman_lt:, :wooden_shield_ld:, 1),
(:soldungb_solusek_kobold_shaman_lt:, :wooden_shield_ld:, 1),
(:soldungb_a_greater_kobold_lt:, :wooden_shield_ld:, 1),
(:soldungb_solusek_kobold_shaman_lt:, :small_buckler_ld:, 1),
(:soldungb_greater_kobold_shaman_lt:, :small_buckler_ld:, 1),
(:soldungb_solusek_kobold_shaman_lt:, :small_wooden_shield_ld:, 1),
(:soldungb_a_greater_kobold_lt:, :small_wooden_shield_ld:, 1),
(:soldungb_greater_kobold_shaman_lt:, :small_wooden_shield_ld:, 1),
