INSERT INTO loottable(name) VALUES('sro_bratoq_jiplup'); # :sro_bratoq_jiplup_lt:
INSERT INTO loottable(name) VALUES('sro_gargantula'); # :sro_gargantula_lt:
INSERT INTO loottable(name) VALUES('sro_gilfal'); # :sro_gilfal_lt:
INSERT INTO loottable(name) VALUES('sro_grass'); # :sro_grass_lt:
INSERT INTO loottable(name) VALUES('sro_instructor_maerceci'); # :sro_instructor_maerceci_lt:
INSERT INTO loottable(name) VALUES('sro_moldrak_drin'); # :sro_moldrak_drin_lt:
INSERT INTO loottable(name) VALUES('sro_remal_the_black'); # :sro_remal_the_black_lt:
INSERT INTO loottable(name) VALUES('sro_saeko_lvinec'); # :sro_saeko_lvinec_lt:
INSERT INTO loottable(name) VALUES('sro_andad_filla'); # :sro_andad_filla_lt:
INSERT INTO loottable(name) VALUES('sro_anumnan_dathry'); # :sro_anumnan_dathry_lt:
INSERT INTO loottable(name) VALUES('sro_an_ancient_cyclops'); # :sro_an_ancient_cyclops_lt:
INSERT INTO loottable(name) VALUES('sro_an_asp'); # :sro_an_asp_lt:
INSERT INTO loottable(name) VALUES('sro_an_orc'); # :sro_an_orc_lt:
INSERT INTO loottable(name) VALUES('sro_an_orc_centurion'); # :sro_an_orc_centurion_lt:
INSERT INTO loottable(name) VALUES('sro_an_orc_cleric'); # :sro_an_orc_cleric_lt:
INSERT INTO loottable(name) VALUES('sro_an_orc_warrior'); # :sro_an_orc_warrior_lt:
INSERT INTO loottable(name) VALUES('sro_artist_passia'); # :sro_artist_passia_lt:
INSERT INTO loottable(name) VALUES('sro_a_cistern_asp'); # :sro_a_cistern_asp_lt:
INSERT INTO loottable(name) VALUES('sro_a_coyote'); # :sro_a_coyote_lt:
INSERT INTO loottable(name) VALUES('sro_a_crypt_mummy'); # :sro_a_crypt_mummy_lt:
INSERT INTO loottable(name) VALUES('sro_a_darkweed_snake'); # :sro_a_darkweed_snake_lt:
INSERT INTO loottable(name) VALUES('sro_a_dervish_cutthroat'); # :sro_a_dervish_cutthroat_lt:
INSERT INTO loottable(name) VALUES('sro_a_dervish_thug'); # :sro_a_dervish_thug_lt:
INSERT INTO loottable(name) VALUES('sro_a_desert_madman'); # :sro_a_desert_madman_lt:
INSERT INTO loottable(name) VALUES('sro_a_desert_tarantula'); # :sro_a_desert_tarantula_lt:
INSERT INTO loottable(name) VALUES('sro_a_drybone_skeleton'); # :sro_a_drybone_skeleton_lt:
INSERT INTO loottable(name) VALUES('sro_a_dune_tarantula'); # :sro_a_dune_tarantula_lt:
INSERT INTO loottable(name) VALUES('sro_a_fire_beetle'); # :sro_a_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('sro_a_ghoul'); # :sro_a_ghoul_lt:
INSERT INTO loottable(name) VALUES('sro_a_giant_rattlesnake'); # :sro_a_giant_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('sro_a_jackal'); # :sro_a_jackal_lt:
INSERT INTO loottable(name) VALUES('sro_a_madman'); # :sro_a_madman_lt:
INSERT INTO loottable(name) VALUES('sro_a_moss_snake'); # :sro_a_moss_snake_lt:
INSERT INTO loottable(name) VALUES('sro_a_mummy'); # :sro_a_mummy_lt:
INSERT INTO loottable(name) VALUES('sro_a_puma'); # :sro_a_puma_lt:
INSERT INTO loottable(name) VALUES('sro_a_rattlesnake'); # :sro_a_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('sro_a_sand_giant'); # :sro_a_sand_giant_lt:
INSERT INTO loottable(name) VALUES('sro_a_sand_giant_elite'); # :sro_a_sand_giant_elite_lt:
INSERT INTO loottable(name) VALUES('sro_a_sand_scarab'); # :sro_a_sand_scarab_lt:
INSERT INTO loottable(name) VALUES('sro_a_shriveled_mummy'); # :sro_a_shriveled_mummy_lt:
INSERT INTO loottable(name) VALUES('sro_a_skeleton'); # :sro_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('sro_a_terrorantuling'); # :sro_a_terrorantuling_lt:
INSERT INTO loottable(name) VALUES('sro_a_tree_snake'); # :sro_a_tree_snake_lt:
INSERT INTO loottable(name) VALUES('sro_a_zombie'); # :sro_a_zombie_lt:
INSERT INTO loottable(name) VALUES('sro_becoreen_pathfinder'); # :sro_becoreen_pathfinder_lt:
INSERT INTO loottable(name) VALUES('sro_bryntelanka_battlebringer'); # :sro_bryntelanka_battlebringer_lt:
INSERT INTO loottable(name) VALUES('sro_crypt_mummy'); # :sro_crypt_mummy_lt:
INSERT INTO loottable(name) VALUES('sro_dahdd_jonne'); # :sro_dahdd_jonne_lt:
INSERT INTO loottable(name) VALUES('sro_dible_hedledrap'); # :sro_dible_hedledrap_lt:
INSERT INTO loottable(name) VALUES('sro_dry_bones_skeleton'); # :sro_dry_bones_skeleton_lt:
INSERT INTO loottable(name) VALUES('sro_erg_bluntbruiser'); # :sro_erg_bluntbruiser_lt:
INSERT INTO loottable(name) VALUES('sro_farwein_windrun'); # :sro_farwein_windrun_lt:
INSERT INTO loottable(name) VALUES('sro_feriern_telenthar'); # :sro_feriern_telenthar_lt:
INSERT INTO loottable(name) VALUES('sro_frenzied_gargling'); # :sro_frenzied_gargling_lt:
INSERT INTO loottable(name) VALUES('sro_friggal_bribbitz'); # :sro_friggal_bribbitz_lt:
INSERT INTO loottable(name) VALUES('sro_garcon_huntmaster'); # :sro_garcon_huntmaster_lt:
INSERT INTO loottable(name) VALUES('sro_gargling'); # :sro_gargling_lt:
INSERT INTO loottable(name) VALUES('sro_gargling_runt'); # :sro_gargling_runt_lt:
INSERT INTO loottable(name) VALUES('sro_ghoul_of_takish-hiz'); # :sro_ghoul_of_takish-hiz_lt:
INSERT INTO loottable(name) VALUES('sro_haele_straedhon'); # :sro_haele_straedhon_lt:
INSERT INTO loottable(name) VALUES('sro_kallei_ribblok'); # :sro_kallei_ribblok_lt:
INSERT INTO loottable(name) VALUES('sro_lcangar_goodwell'); # :sro_lcangar_goodwell_lt:
INSERT INTO loottable(name) VALUES('sro_maeggi_lohndl'); # :sro_maeggi_lohndl_lt:
INSERT INTO loottable(name) VALUES('sro_magus_jerira'); # :sro_magus_jerira_lt:
INSERT INTO loottable(name) VALUES('sro_merchant_ulyssa'); # :sro_merchant_ulyssa_lt:
INSERT INTO loottable(name) VALUES('sro_obretl'); # :sro_obretl_lt:
INSERT INTO loottable(name) VALUES('sro_orc_oracle'); # :sro_orc_oracle_lt:
INSERT INTO loottable(name) VALUES('sro_ortallius'); # :sro_ortallius_lt:
INSERT INTO loottable(name) VALUES('sro_rabid_gargling'); # :sro_rabid_gargling_lt:
INSERT INTO loottable(name) VALUES('sro_rathmana_allin'); # :sro_rathmana_allin_lt:
INSERT INTO loottable(name) VALUES('sro_razortooth'); # :sro_razortooth_lt:
INSERT INTO loottable(name) VALUES('sro_ruwakka'); # :sro_ruwakka_lt:
INSERT INTO loottable(name) VALUES('sro_sandgiant_husam'); # :sro_sandgiant_husam_lt:
INSERT INTO loottable(name) VALUES('sro_scout_miigle'); # :sro_scout_miigle_lt:
INSERT INTO loottable(name) VALUES('sro_scrounge'); # :sro_scrounge_lt:
INSERT INTO loottable(name) VALUES('sro_selephra_giztral'); # :sro_selephra_giztral_lt:
INSERT INTO loottable(name) VALUES('sro_smith_tvysa'); # :sro_smith_tvysa_lt:
INSERT INTO loottable(name) VALUES('sro_soulbinder_silandra'); # :sro_soulbinder_silandra_lt:
INSERT INTO loottable(name) VALUES('sro_taeri_kuqq'); # :sro_taeri_kuqq_lt:
INSERT INTO loottable(name) VALUES('sro_terrorantula'); # :sro_terrorantula_lt:
INSERT INTO loottable(name) VALUES('sro_the_fabled_ancient_cyclops'); # :sro_the_fabled_ancient_cyclops_lt:
