UPDATE npc_types SET loottable_id = :tox_aglthin_dasmore_lt: WHERE id in (38038); # #Aglthin_Dasmore 8
UPDATE npc_types SET loottable_id = :tox_fleshless_servant_lt: WHERE id in (38173); # #Fleshless_Servant 60
UPDATE npc_types SET loottable_id = :tox_phaeril_nightshire_lt: WHERE id in (38081); # #Phaeril_Nightshire 25
UPDATE npc_types SET loottable_id = :tox_veisha_fathomwalker_lt: WHERE id in (38021); # #Veisha_Fathomwalker 25
UPDATE npc_types SET loottable_id = :tox_wall_echo_lt: WHERE id in (38179); # #wall_echo 1
UPDATE npc_types SET loottable_id = :tox_abandoned_heretic_pet_lt: WHERE id in (38018, 38037, 38139); # abandoned_heretic_pet 8
UPDATE npc_types SET loottable_id = :tox_an_erudin_emissary_lt: WHERE id in (38147, 38049, 38056); # an_Erudin_Emissary 21
UPDATE npc_types SET loottable_id = :tox_an_infected_rat_lt: WHERE id in (38014); # an_infected_rat 2
UPDATE npc_types SET loottable_id = :tox_assistant_tos_lt: WHERE id in (38077); # Assistant_T`os 50
UPDATE npc_types SET loottable_id = :tox_a_boat_lt: WHERE id in (38068); # a_boat 50
UPDATE npc_types SET loottable_id = :tox_a_briar_snake_lt: WHERE id in (38022, 38048, 38054); # a_briar_snake 3
UPDATE npc_types SET loottable_id = :tox_a_decaying_skeleton_lt: WHERE id in (38009, 38013); # a_decaying_skeleton 2
UPDATE npc_types SET loottable_id = :tox_a_fading_spectre_lt: WHERE id in (38025); # a_fading_spectre 10
UPDATE npc_types SET loottable_id = :tox_a_fire_beetle_lt: WHERE id in (38003); # a_fire_beetle 2
UPDATE npc_types SET loottable_id = :tox_a_fish_lt: WHERE id in (38052, 38055); # a_fish 1
UPDATE npc_types SET loottable_id = :tox_a_giant_briar_snake_lt: WHERE id in (38039, 38136); # a_giant_briar_snake 7
UPDATE npc_types SET loottable_id = :tox_a_giant_thistle_snake_lt: WHERE id in (38033, 38041); # a_giant_thistle_snake 9
UPDATE npc_types SET loottable_id = :tox_a_giant_widow_lt: WHERE id in (38029); # a_giant_widow 10
UPDATE npc_types SET loottable_id = :tox_a_kobold_caster_lt: WHERE id in (38172); # a_kobold_caster 9
UPDATE npc_types SET loottable_id = :tox_a_kobold_runt_lt: WHERE id in (38004); # a_kobold_runt 1
UPDATE npc_types SET loottable_id = :tox_a_kobold_scout_lt: WHERE id in (38035); # a_kobold_scout 2
UPDATE npc_types SET loottable_id = :tox_a_kobold_sentry_lt: WHERE id in (38001, 38002, 38012); # a_kobold_sentry 3
UPDATE npc_types SET loottable_id = :tox_a_kobold_shaman_lt: WHERE id in (38145); # a_kobold_shaman 5
UPDATE npc_types SET loottable_id = :tox_a_kobold_watcher_lt: WHERE id in (38008); # a_kobold_watcher 3
UPDATE npc_types SET loottable_id = :tox_a_large_briar_snake_lt: WHERE id in (38034, 38045, 38050); # a_large_briar_snake 7
UPDATE npc_types SET loottable_id = :tox_a_large_fire_beetle_lt: WHERE id in (38028, 38040); # a_large_fire_beetle 6
UPDATE npc_types SET loottable_id = :tox_a_large_skunk_lt: WHERE id in (38148); # a_large_skunk 2
UPDATE npc_types SET loottable_id = :tox_a_large_thistle_snake_lt: WHERE id in (38032, 38042, 38046); # a_large_thistle_snake 6
UPDATE npc_types SET loottable_id = :tox_a_large_widow_lt: WHERE id in (38026, 38027); # a_large_widow 5
UPDATE npc_types SET loottable_id = :tox_a_large_wood_spider_lt: WHERE id in (38030, 38031, 38044); # a_large_wood_spider 5
UPDATE npc_types SET loottable_id = :tox_a_moss_snake_lt: WHERE id in (38007); # a_moss_snake 1
UPDATE npc_types SET loottable_id = :tox_a_mystic_voice_lt: WHERE id in (38163); # A_Mystic_Voice 50
UPDATE npc_types SET loottable_id = :tox_a_pie_flinger_lt: WHERE id in (38175); # a_pie_flinger 1
UPDATE npc_types SET loottable_id = :tox_a_pie_hurler_lt: WHERE id in (38176); # a_pie_hurler 1
UPDATE npc_types SET loottable_id = :tox_a_pie_thrower_lt: WHERE id in (38177); # a_pie_thrower 1
UPDATE npc_types SET loottable_id = :tox_a_piranha_lt: WHERE id in (38057); # a_piranha 2
UPDATE npc_types SET loottable_id = :tox_a_pixie_lt: WHERE id in (38060, 38080); # a_pixie 16
UPDATE npc_types SET loottable_id = :tox_a_skeletal_commander_lt: WHERE id in (38084, 38085, 38087); # a_skeletal_commander 39
UPDATE npc_types SET loottable_id = :tox_a_skeletal_conscript_lt: WHERE id in (38108, 38130); # a_skeletal_conscript 9
UPDATE npc_types SET loottable_id = :tox_a_skeletal_footsoldier_lt: WHERE id in (38106, 38109, 38110, 38112, 38113, 38114, 38116, 38120, 38121, 38124); # a_skeletal_footsoldier 22
UPDATE npc_types SET loottable_id = :tox_a_skeletal_lieutenant_lt: WHERE id in (38088, 38089); # a_skeletal_lieutenant 35
UPDATE npc_types SET loottable_id = :tox_a_skeletal_trooper_lt: WHERE id in (38090, 38094, 38097, 38098, 38100, 38101, 38102, 38104, 38119, 38122, 38125); # a_skeletal_trooper 32
UPDATE npc_types SET loottable_id = :tox_a_skeleton_lt: WHERE id in (38016, 38017, 38020); # a_skeleton 9
UPDATE npc_types SET loottable_id = :tox_a_skunk_lt: WHERE id in (38006); # a_skunk 2
UPDATE npc_types SET loottable_id = :tox_a_spiderling_lt: WHERE id in (38010, 38011); # a_spiderling 2
UPDATE npc_types SET loottable_id = :tox_a_thistle_snake_lt: WHERE id in (38000); # a_thistle_snake 1
UPDATE npc_types SET loottable_id = :tox_a_toxxulia_mushroom_lt: WHERE id in (38174); # a_toxxulia_mushroom 1
UPDATE npc_types SET loottable_id = :tox_a_widow_hatchling_lt: WHERE id in (38015); # a_widow_hatchling 2
UPDATE npc_types SET loottable_id = :tox_cyria_lorewhisper_lt: WHERE id in (38069); # Cyria_Lorewhisper 45
UPDATE npc_types SET loottable_id = :tox_dovon_traical_lt: WHERE id in (38078); # Dovon_Traical 65
UPDATE npc_types SET loottable_id = :tox_elial_brook_lt: WHERE id in (38061); # Elial_Brook 7
UPDATE npc_types SET loottable_id = :tox_emil_parsini_lt: WHERE id in (38074); # Emil_Parsini 25
UPDATE npc_types SET loottable_id = :tox_fittorin_bladespur_lt: WHERE id in (38059); # Fittorin_Bladespur 32
UPDATE npc_types SET loottable_id = :tox_fittorn_bladespur_lt: WHERE id in (38151); # Fittorn_Bladespur 32
UPDATE npc_types SET loottable_id = :tox_friedalla_dawncrest__lt: WHERE id in (38167); # Friedalla_Dawncrest_ 50
UPDATE npc_types SET loottable_id = :tox_fuzz_selppa_lt: WHERE id in (38171); # Fuzz_Selppa 50
UPDATE npc_types SET loottable_id = :tox_ilanics_skeleton_lt: WHERE id in (38150, 38157); # Ilanics_skeleton 5
UPDATE npc_types SET loottable_id = :tox_ilisiv_gantrau_lt: WHERE id in (38079); # Ilisiv_Gantrau 65
UPDATE npc_types SET loottable_id = :tox_islan_hetston_lt: WHERE id in (38073); # Islan_Hetston 24
UPDATE npc_types SET loottable_id = :tox_jalen_goldsinger_lt: WHERE id in (38066); # Jalen_Goldsinger 40
UPDATE npc_types SET loottable_id = :tox_kellkoan_rishta_lt: WHERE id in (38159); # Kellkoan_Rishta 50
UPDATE npc_types SET loottable_id = :tox_knarthenne_skurl_lt: WHERE id in (38058); # Knarthenne_Skurl 50
UPDATE npc_types SET loottable_id = :tox_lanivon_baxer_lt: WHERE id in (38064); # Lanivon_Baxer 50
UPDATE npc_types SET loottable_id = :tox_marta_stalwart_lt: WHERE id in (38178); # Marta_Stalwart 45
UPDATE npc_types SET loottable_id = :tox_martyn_firechaser_lt: WHERE id in (38063); # Martyn_Firechaser 45
UPDATE npc_types SET loottable_id = :tox_nexus_scion_lt: WHERE id in (38065); # Nexus_Scion 66
UPDATE npc_types SET loottable_id = :tox_odus_spires_lt: WHERE id in (38051); # Odus_Spires 50
UPDATE npc_types SET loottable_id = :tox_poacher_dell_lt: WHERE id in (38133); # Poacher_Dell 4
UPDATE npc_types SET loottable_id = :tox_poacher_hill_lt: WHERE id in (38158); # Poacher_Hill 4
UPDATE npc_types SET loottable_id = :tox_poacher_shelli_lt: WHERE id in (38043); # Poacher_Shelli 3
UPDATE npc_types SET loottable_id = :tox_poacher_topi_lt: WHERE id in (38162); # Poacher_Topi 3
UPDATE npc_types SET loottable_id = :tox_poacher_unil_lt: WHERE id in (38156); # Poacher_Unil 2
UPDATE npc_types SET loottable_id = :tox_poacher_willa_lt: WHERE id in (38168); # Poacher_Willa 5
UPDATE npc_types SET loottable_id = :tox_quana_rainsparkle_lt: WHERE id in (38070); # Quana_Rainsparkle 45
UPDATE npc_types SET loottable_id = :tox_reeking_skunk_lt: WHERE id in (38047); # Reeking_Skunk 45
UPDATE npc_types SET loottable_id = :tox_ricandrow_starbourne_lt: WHERE id in (38170); # Ricandrow_Starbourne 50
UPDATE npc_types SET loottable_id = :tox_rungupp_lt: WHERE id in (38023, 38134); # Rungupp 3
UPDATE npc_types SET loottable_id = :tox_sanidella_syllvic_lt: WHERE id in (38166); # Sanidella_Syllvic 50
UPDATE npc_types SET loottable_id = :tox_sentinel_creot_lt: WHERE id in (38053); # Sentinel_Creot 30
UPDATE npc_types SET loottable_id = :tox_sentinel_drom_lt: WHERE id in (38076); # Sentinel_Drom 50
UPDATE npc_types SET loottable_id = :tox_sentinel_flavius_lt: WHERE id in (38075); # Sentinel_Flavius 50
UPDATE npc_types SET loottable_id = :tox_shintar_vinlail_lt: WHERE id in (38067); # Shintar_Vinlail 4
UPDATE npc_types SET loottable_id = :tox_stylla_parsini_lt: WHERE id in (38024); # Stylla_Parsini 45
UPDATE npc_types SET loottable_id = :tox_telanku_trailrunner_lt: WHERE id in (38164); # Telanku_Trailrunner 50
UPDATE npc_types SET loottable_id = :tox_terago_omath_lt: WHERE id in (38062); # Terago_Omath 12
UPDATE npc_types SET loottable_id = :tox_the_norrath_spires_lt: WHERE id in (38149); # The_Norrath_Spires 50
UPDATE npc_types SET loottable_id = :tox_tran_lilspin_lt: WHERE id in (38036); # Tran_Lilspin 26
UPDATE npc_types SET loottable_id = :tox_win_karnam_lt: WHERE id in (38072); # Win_Karnam 45
UPDATE npc_types SET loottable_id = :tox_xylania_rainsparkle_lt: WHERE id in (38071); # Xylania_Rainsparkle 28
