INSERT INTO loottable(name) VALUES('tutorialb_arias'); # :tutorialb_arias_lt:
INSERT INTO loottable(name) VALUES('tutorialb_brokenclaw'); # :tutorialb_brokenclaw_lt:
INSERT INTO loottable(name) VALUES('tutorialb_krenshin'); # :tutorialb_krenshin_lt:
INSERT INTO loottable(name) VALUES('tutorialb_overlord_gnikan'); # :tutorialb_overlord_gnikan_lt:
INSERT INTO loottable(name) VALUES('tutorialb_pox'); # :tutorialb_pox_lt:
INSERT INTO loottable(name) VALUES('tutorialb_queen_gloomfang'); # :tutorialb_queen_gloomfang_lt:
INSERT INTO loottable(name) VALUES('tutorialb_ratasaurus'); # :tutorialb_ratasaurus_lt:
INSERT INTO loottable(name) VALUES('tutorialb_rookfynn'); # :tutorialb_rookfynn_lt:
INSERT INTO loottable(name) VALUES('tutorialb_rufus'); # :tutorialb_rufus_lt:
INSERT INTO loottable(name) VALUES('tutorialb_selandoor'); # :tutorialb_selandoor_lt:
INSERT INTO loottable(name) VALUES('tutorialb_slavemaster_ruga'); # :tutorialb_slavemaster_ruga_lt:
INSERT INTO loottable(name) VALUES('tutorialb_sliver'); # :tutorialb_sliver_lt:
INSERT INTO loottable(name) VALUES('tutorialb_spider_tamer_gugan'); # :tutorialb_spider_tamer_gugan_lt:
INSERT INTO loottable(name) VALUES('tutorialb_venomfang'); # :tutorialb_venomfang_lt:
INSERT INTO loottable(name) VALUES('tutorialb_absor'); # :tutorialb_absor_lt:
INSERT INTO loottable(name) VALUES('tutorialb_ajax'); # :tutorialb_ajax_lt:
INSERT INTO loottable(name) VALUES('tutorialb_an_exhausted_goblin'); # :tutorialb_an_exhausted_goblin_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_cave_bat'); # :tutorialb_a_cave_bat_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_cave_rat'); # :tutorialb_a_cave_rat_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_dark_elf_slave'); # :tutorialb_a_dark_elf_slave_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_diseased_rat'); # :tutorialb_a_diseased_rat_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_dwarven_slave'); # :tutorialb_a_dwarven_slave_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_garroted_kobold'); # :tutorialb_a_garroted_kobold_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloomfang_lurker'); # :tutorialb_a_gloomfang_lurker_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloomingdeep_captain'); # :tutorialb_a_gloomingdeep_captain_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloomingdeep_grunt'); # :tutorialb_a_gloomingdeep_grunt_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloomingdeep_plaguebearer'); # :tutorialb_a_gloomingdeep_plaguebearer_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloomingdeep_shaman'); # :tutorialb_a_gloomingdeep_shaman_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloomingdeep_slave_warden'); # :tutorialb_a_gloomingdeep_slave_warden_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloomingdeep_spiritweaver'); # :tutorialb_a_gloomingdeep_spiritweaver_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloomingdeep_taskmaster'); # :tutorialb_a_gloomingdeep_taskmaster_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloomingdeep_warrior'); # :tutorialb_a_gloomingdeep_warrior_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloom_spider'); # :tutorialb_a_gloom_spider_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_gloom_spiderling'); # :tutorialb_a_gloom_spiderling_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_goblin_slave'); # :tutorialb_a_goblin_slave_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_human_slave'); # :tutorialb_a_human_slave_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_kobold_barrel'); # :tutorialb_a_kobold_barrel_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_locksmiths_footlocker'); # :tutorialb_a_locksmiths_footlocker_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_pile_of_bones'); # :tutorialb_a_pile_of_bones_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_pile_of_digested_remains'); # :tutorialb_a_pile_of_digested_remains_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_small_rat'); # :tutorialb_a_small_rat_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_small_spider'); # :tutorialb_a_small_spider_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_spider_cocoon_cluster'); # :tutorialb_a_spider_cocoon_cluster_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_trampled_kobold'); # :tutorialb_a_trampled_kobold_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_trampled_slave'); # :tutorialb_a_trampled_slave_lt:
INSERT INTO loottable(name) VALUES('tutorialb_a_vermin_nest'); # :tutorialb_a_vermin_nest_lt:
INSERT INTO loottable(name) VALUES('tutorialb_babyface'); # :tutorialb_babyface_lt:
INSERT INTO loottable(name) VALUES('tutorialb_basher_alga'); # :tutorialb_basher_alga_lt:
INSERT INTO loottable(name) VALUES('tutorialb_belfayda'); # :tutorialb_belfayda_lt:
INSERT INTO loottable(name) VALUES('tutorialb_boqueron'); # :tutorialb_boqueron_lt:
INSERT INTO loottable(name) VALUES('tutorialb_celrak'); # :tutorialb_celrak_lt:
INSERT INTO loottable(name) VALUES('tutorialb_clockwork_war_machine'); # :tutorialb_clockwork_war_machine_lt:
INSERT INTO loottable(name) VALUES('tutorialb_damian'); # :tutorialb_damian_lt:
INSERT INTO loottable(name) VALUES('tutorialb_deltadawn'); # :tutorialb_deltadawn_lt:
INSERT INTO loottable(name) VALUES('tutorialb_dragoon_zytl'); # :tutorialb_dragoon_zytl_lt:
INSERT INTO loottable(name) VALUES('tutorialb_duarte'); # :tutorialb_duarte_lt:
INSERT INTO loottable(name) VALUES('tutorialb_dysan'); # :tutorialb_dysan_lt:
INSERT INTO loottable(name) VALUES('tutorialb_flutterwing'); # :tutorialb_flutterwing_lt:
INSERT INTO loottable(name) VALUES('tutorialb_frizznik_hailstorm'); # :tutorialb_frizznik_hailstorm_lt:
INSERT INTO loottable(name) VALUES('tutorialb_frogasly'); # :tutorialb_frogasly_lt:
INSERT INTO loottable(name) VALUES('tutorialb_gnikans_war_chest'); # :tutorialb_gnikans_war_chest_lt:
INSERT INTO loottable(name) VALUES('tutorialb_guard_hobart'); # :tutorialb_guard_hobart_lt:
INSERT INTO loottable(name) VALUES('tutorialb_guard_kaikachi'); # :tutorialb_guard_kaikachi_lt:
INSERT INTO loottable(name) VALUES('tutorialb_guard_maddoc'); # :tutorialb_guard_maddoc_lt:
INSERT INTO loottable(name) VALUES('tutorialb_guard_of_gloomingdeep'); # :tutorialb_guard_of_gloomingdeep_lt:
INSERT INTO loottable(name) VALUES('tutorialb_guard_rahtiz'); # :tutorialb_guard_rahtiz_lt:
INSERT INTO loottable(name) VALUES('tutorialb_guard_vyrinn'); # :tutorialb_guard_vyrinn_lt:
INSERT INTO loottable(name) VALUES('tutorialb_hobart_wolfkin'); # :tutorialb_hobart_wolfkin_lt:
INSERT INTO loottable(name) VALUES('tutorialb_kobold_siege_supplies'); # :tutorialb_kobold_siege_supplies_lt:
INSERT INTO loottable(name) VALUES('tutorialb_lyndroh'); # :tutorialb_lyndroh_lt:
INSERT INTO loottable(name) VALUES('tutorialb_nomaad'); # :tutorialb_nomaad_lt:
INSERT INTO loottable(name) VALUES('tutorialb_nura'); # :tutorialb_nura_lt:
INSERT INTO loottable(name) VALUES('tutorialb_poxan_'); # :tutorialb_poxan__lt:
INSERT INTO loottable(name) VALUES('tutorialb_prathun_stumblebum'); # :tutorialb_prathun_stumblebum_lt:
INSERT INTO loottable(name) VALUES('tutorialb_ranger_band'); # :tutorialb_ranger_band_lt:
INSERT INTO loottable(name) VALUES('tutorialb_rashere'); # :tutorialb_rashere_lt:
INSERT INTO loottable(name) VALUES('tutorialb_revolt_scout_kaikachi'); # :tutorialb_revolt_scout_kaikachi_lt:
INSERT INTO loottable(name) VALUES('tutorialb_revolt_scout_zajeer'); # :tutorialb_revolt_scout_zajeer_lt:
INSERT INTO loottable(name) VALUES('tutorialb_rohga'); # :tutorialb_rohga_lt:
INSERT INTO loottable(name) VALUES('tutorialb_rowyl'); # :tutorialb_rowyl_lt:
INSERT INTO loottable(name) VALUES('tutorialb_rytan'); # :tutorialb_rytan_lt:
INSERT INTO loottable(name) VALUES('tutorialb_shadow'); # :tutorialb_shadow_lt:
INSERT INTO loottable(name) VALUES('tutorialb_sticks'); # :tutorialb_sticks_lt:
INSERT INTO loottable(name) VALUES('tutorialb_the_gloomingdeep_jailor'); # :tutorialb_the_gloomingdeep_jailor_lt:
INSERT INTO loottable(name) VALUES('tutorialb_the_gloomingdeep_locksmith'); # :tutorialb_the_gloomingdeep_locksmith_lt:
INSERT INTO loottable(name) VALUES('tutorialb_tinkerer_gordish'); # :tutorialb_tinkerer_gordish_lt:
INSERT INTO loottable(name) VALUES('tutorialb_tinkerer_keridon'); # :tutorialb_tinkerer_keridon_lt:
INSERT INTO loottable(name) VALUES('tutorialb_tinkerer_oshran'); # :tutorialb_tinkerer_oshran_lt:
INSERT INTO loottable(name) VALUES('tutorialb_vahlara'); # :tutorialb_vahlara_lt:
INSERT INTO loottable(name) VALUES('tutorialb_valtron_ogrebane'); # :tutorialb_valtron_ogrebane_lt:
INSERT INTO loottable(name) VALUES('tutorialb_vyrinn_shadowmist'); # :tutorialb_vyrinn_shadowmist_lt:
INSERT INTO loottable(name) VALUES('tutorialb_wijdan'); # :tutorialb_wijdan_lt:
INSERT INTO loottable(name) VALUES('tutorialb_xenaida_akhzrial'); # :tutorialb_xenaida_akhzrial_lt:
INSERT INTO loottable(name) VALUES('tutorialb_yodaman'); # :tutorialb_yodaman_lt:
INSERT INTO loottable(name) VALUES('tutorialb__'); # :tutorialb___lt:
