INSERT INTO loottable(name) VALUES('gukb_a_cloud_of_poison'); # :gukb_a_cloud_of_poison_lt:
INSERT INTO loottable(name) VALUES('gukb_a_cursed_burrower'); # :gukb_a_cursed_burrower_lt:
INSERT INTO loottable(name) VALUES('gukb_a_festering_ooze'); # :gukb_a_festering_ooze_lt:
INSERT INTO loottable(name) VALUES('gukb_a_reanimated_shinta_knight'); # :gukb_a_reanimated_shinta_knight_lt:
INSERT INTO loottable(name) VALUES('gukb_a_rotting_box'); # :gukb_a_rotting_box_lt:
INSERT INTO loottable(name) VALUES('gukb_a_witness_of_hate_tattler'); # :gukb_a_witness_of_hate_tattler_lt:
INSERT INTO loottable(name) VALUES('gukb_flavor_text_bridge'); # :gukb_flavor_text_bridge_lt:
INSERT INTO loottable(name) VALUES('gukb_flavor_text_crypt'); # :gukb_flavor_text_crypt_lt:
INSERT INTO loottable(name) VALUES('gukb_flavor_text_junction'); # :gukb_flavor_text_junction_lt:
INSERT INTO loottable(name) VALUES('gukb_flavor_text_library'); # :gukb_flavor_text_library_lt:
INSERT INTO loottable(name) VALUES('gukb_flavor_text_root'); # :gukb_flavor_text_root_lt:
