INSERT INTO loottable(name) VALUES('guke_chest_of_the_foci'); # :guke_chest_of_the_foci_lt:
INSERT INTO loottable(name) VALUES('guke_gimdks_chest'); # :guke_gimdks_chest_lt:
INSERT INTO loottable(name) VALUES('guke_the_slimy_chest_of_the_witness'); # :guke_the_slimy_chest_of_the_witness_lt:
INSERT INTO loottable(name) VALUES('guke_an_acolyte_of_the_first'); # :guke_an_acolyte_of_the_first_lt:
INSERT INTO loottable(name) VALUES('guke_an_alluring_oculus'); # :guke_an_alluring_oculus_lt:
INSERT INTO loottable(name) VALUES('guke_an_ice_caller_of_the_first'); # :guke_an_ice_caller_of_the_first_lt:
INSERT INTO loottable(name) VALUES('guke_an_oculus_thamaturge'); # :guke_an_oculus_thamaturge_lt:
INSERT INTO loottable(name) VALUES('guke_a_blade_of_the_first'); # :guke_a_blade_of_the_first_lt:
INSERT INTO loottable(name) VALUES('guke_a_bone_pile'); # :guke_a_bone_pile_lt:
INSERT INTO loottable(name) VALUES('guke_a_caller_of_the_first'); # :guke_a_caller_of_the_first_lt:
INSERT INTO loottable(name) VALUES('guke_a_cauldron_acolyte'); # :guke_a_cauldron_acolyte_lt:
INSERT INTO loottable(name) VALUES('guke_a_cauldron_witch_doctor'); # :guke_a_cauldron_witch_doctor_lt:
INSERT INTO loottable(name) VALUES('guke_a_cursed_guktan'); # :guke_a_cursed_guktan_lt:
INSERT INTO loottable(name) VALUES('guke_a_festering_ooze_trap'); # :guke_a_festering_ooze_trap_lt:
INSERT INTO loottable(name) VALUES('guke_a_fist_of_the_first'); # :guke_a_fist_of_the_first_lt:
INSERT INTO loottable(name) VALUES('guke_a_frenzied_spirit'); # :guke_a_frenzied_spirit_lt:
INSERT INTO loottable(name) VALUES('guke_a_guardian_of_the_first'); # :guke_a_guardian_of_the_first_lt:
INSERT INTO loottable(name) VALUES('guke_a_hand_of_the_first'); # :guke_a_hand_of_the_first_lt:
INSERT INTO loottable(name) VALUES('guke_a_malicious_force'); # :guke_a_malicious_force_lt:
INSERT INTO loottable(name) VALUES('guke_a_moldy_chest'); # :guke_a_moldy_chest_lt:
INSERT INTO loottable(name) VALUES('guke_a_poison_cloud_trap'); # :guke_a_poison_cloud_trap_lt:
INSERT INTO loottable(name) VALUES('guke_a_protector_of_the_first_witness'); # :guke_a_protector_of_the_first_witness_lt:
INSERT INTO loottable(name) VALUES('guke_a_reader_of_the_first'); # :guke_a_reader_of_the_first_lt:
INSERT INTO loottable(name) VALUES('guke_a_risen_acolyte'); # :guke_a_risen_acolyte_lt:
INSERT INTO loottable(name) VALUES('guke_a_risen_champion'); # :guke_a_risen_champion_lt:
INSERT INTO loottable(name) VALUES('guke_a_risen_death_knight'); # :guke_a_risen_death_knight_lt:
INSERT INTO loottable(name) VALUES('guke_a_risen_deceiver'); # :guke_a_risen_deceiver_lt:
INSERT INTO loottable(name) VALUES('guke_a_risen_fire_caller'); # :guke_a_risen_fire_caller_lt:
INSERT INTO loottable(name) VALUES('guke_a_risen_partisan'); # :guke_a_risen_partisan_lt:
INSERT INTO loottable(name) VALUES('guke_a_risen_stalker'); # :guke_a_risen_stalker_lt:
INSERT INTO loottable(name) VALUES('guke_a_risen_witch_doctor'); # :guke_a_risen_witch_doctor_lt:
INSERT INTO loottable(name) VALUES('guke_a_rotting_barrel'); # :guke_a_rotting_barrel_lt:
INSERT INTO loottable(name) VALUES('guke_a_rotting_box'); # :guke_a_rotting_box_lt:
INSERT INTO loottable(name) VALUES('guke_a_seer_of_the_first'); # :guke_a_seer_of_the_first_lt:
INSERT INTO loottable(name) VALUES('guke_a_witnessing_oculus'); # :guke_a_witnessing_oculus_lt:
INSERT INTO loottable(name) VALUES('guke_energy_focus'); # :guke_energy_focus_lt:
INSERT INTO loottable(name) VALUES('guke_executioner_gimdk'); # :guke_executioner_gimdk_lt:
INSERT INTO loottable(name) VALUES('guke_matter_focus'); # :guke_matter_focus_lt:
INSERT INTO loottable(name) VALUES('guke_scout_granos'); # :guke_scout_granos_lt:
INSERT INTO loottable(name) VALUES('guke_scout_mainil'); # :guke_scout_mainil_lt:
INSERT INTO loottable(name) VALUES('guke_spirit_focus'); # :guke_spirit_focus_lt:
INSERT INTO loottable(name) VALUES('guke_the_first_witness'); # :guke_the_first_witness_lt:
INSERT INTO loottable(name) VALUES('guke_the_first_witness-unused'); # :guke_the_first_witness-unused_lt:
