INSERT INTO loottable(name) VALUES('mira_an_arctic_icespinner'); # :mira_an_arctic_icespinner_lt:
INSERT INTO loottable(name) VALUES('mira_a_blistering_glob_of_flesh'); # :mira_a_blistering_glob_of_flesh_lt:
INSERT INTO loottable(name) VALUES('mira_a_clattering_anomaly'); # :mira_a_clattering_anomaly_lt:
INSERT INTO loottable(name) VALUES('mira_a_confused_mutation'); # :mira_a_confused_mutation_lt:
INSERT INTO loottable(name) VALUES('mira_a_dire_magic_vortex'); # :mira_a_dire_magic_vortex_lt:
INSERT INTO loottable(name) VALUES('mira_a_frostfoot_archpriest'); # :mira_a_frostfoot_archpriest_lt:
INSERT INTO loottable(name) VALUES('mira_a_frostfoot_oracle'); # :mira_a_frostfoot_oracle_lt:
INSERT INTO loottable(name) VALUES('mira_a_frostfoot_sage'); # :mira_a_frostfoot_sage_lt:
INSERT INTO loottable(name) VALUES('mira_a_frostfoot_savager'); # :mira_a_frostfoot_savager_lt:
INSERT INTO loottable(name) VALUES('mira_a_frostfoot_scamp'); # :mira_a_frostfoot_scamp_lt:
INSERT INTO loottable(name) VALUES('mira_a_frost_covered_box'); # :mira_a_frost_covered_box_lt:
INSERT INTO loottable(name) VALUES('mira_a_frozen_table'); # :mira_a_frozen_table_lt:
INSERT INTO loottable(name) VALUES('mira_a_hatchling'); # :mira_a_hatchling_lt:
INSERT INTO loottable(name) VALUES('mira_a_lost_polar_bear'); # :mira_a_lost_polar_bear_lt:
INSERT INTO loottable(name) VALUES('mira_a_rambling_ice_brute'); # :mira_a_rambling_ice_brute_lt:
INSERT INTO loottable(name) VALUES('mira_a_skeletal_scholar'); # :mira_a_skeletal_scholar_lt:
INSERT INTO loottable(name) VALUES('mira_a_stray_wolf'); # :mira_a_stray_wolf_lt:
INSERT INTO loottable(name) VALUES('mira__'); # :mira___lt:
