INSERT INTO loottable(name) VALUES('mirg_an_echo_of_the_synarcana'); # :mirg_an_echo_of_the_synarcana_lt:
INSERT INTO loottable(name) VALUES('mirg_an_extraplanar_fiend'); # :mirg_an_extraplanar_fiend_lt:
INSERT INTO loottable(name) VALUES('mirg_a_corrosive_ooze'); # :mirg_a_corrosive_ooze_lt:
INSERT INTO loottable(name) VALUES('mirg_a_jeweled_sentinel'); # :mirg_a_jeweled_sentinel_lt:
INSERT INTO loottable(name) VALUES('mirg_flurry_of_insanity'); # :mirg_flurry_of_insanity_lt:
INSERT INTO loottable(name) VALUES('mirg_holgresh_trickster'); # :mirg_holgresh_trickster_lt:
INSERT INTO loottable(name) VALUES('mirg_kiszchen_the_mischief'); # :mirg_kiszchen_the_mischief_lt:
INSERT INTO loottable(name) VALUES('mirg_the_synarcana'); # :mirg_the_synarcana_lt:
INSERT INTO loottable(name) VALUES('mirg_venidraxxen'); # :mirg_venidraxxen_lt:
INSERT INTO loottable(name) VALUES('mirg_an_ancient_chest'); # :mirg_an_ancient_chest_lt:
INSERT INTO loottable(name) VALUES('mirg_an_ancient_skeletal_worker'); # :mirg_an_ancient_skeletal_worker_lt:
INSERT INTO loottable(name) VALUES('mirg_an_icy_skeletal_worker'); # :mirg_an_icy_skeletal_worker_lt:
INSERT INTO loottable(name) VALUES('mirg_an_icy_sphere'); # :mirg_an_icy_sphere_lt:
INSERT INTO loottable(name) VALUES('mirg_a_blistering_glob_of_flesh'); # :mirg_a_blistering_glob_of_flesh_lt:
INSERT INTO loottable(name) VALUES('mirg_a_bubbling_clod_of_flesh'); # :mirg_a_bubbling_clod_of_flesh_lt:
INSERT INTO loottable(name) VALUES('mirg_a_cacophonous_horror'); # :mirg_a_cacophonous_horror_lt:
INSERT INTO loottable(name) VALUES('mirg_a_charred_skeletal_worker'); # :mirg_a_charred_skeletal_worker_lt:
INSERT INTO loottable(name) VALUES('mirg_a_cloud_of_poison'); # :mirg_a_cloud_of_poison_lt:
INSERT INTO loottable(name) VALUES('mirg_a_confused_mutation'); # :mirg_a_confused_mutation_lt:
INSERT INTO loottable(name) VALUES('mirg_a_crystallized_guardian'); # :mirg_a_crystallized_guardian_lt:
INSERT INTO loottable(name) VALUES('mirg_a_cunning_fiend'); # :mirg_a_cunning_fiend_lt:
INSERT INTO loottable(name) VALUES('mirg_a_deluded_holgresh'); # :mirg_a_deluded_holgresh_lt:
INSERT INTO loottable(name) VALUES('mirg_a_diminutive_horror'); # :mirg_a_diminutive_horror_lt:
INSERT INTO loottable(name) VALUES('mirg_a_dire_magic_vortex'); # :mirg_a_dire_magic_vortex_lt:
INSERT INTO loottable(name) VALUES('mirg_a_fearsome_planar_specimen'); # :mirg_a_fearsome_planar_specimen_lt:
INSERT INTO loottable(name) VALUES('mirg_a_frost_covered_barrel'); # :mirg_a_frost_covered_barrel_lt:
INSERT INTO loottable(name) VALUES('mirg_a_glaring_manticore'); # :mirg_a_glaring_manticore_lt:
INSERT INTO loottable(name) VALUES('mirg_a_greater_tormentor'); # :mirg_a_greater_tormentor_lt:
INSERT INTO loottable(name) VALUES('mirg_a_greater_torment_knight'); # :mirg_a_greater_torment_knight_lt:
INSERT INTO loottable(name) VALUES('mirg_a_growling_manticore'); # :mirg_a_growling_manticore_lt:
INSERT INTO loottable(name) VALUES('mirg_a_humming_malformation'); # :mirg_a_humming_malformation_lt:
INSERT INTO loottable(name) VALUES('mirg_a_planar_tormentor'); # :mirg_a_planar_tormentor_lt:
INSERT INTO loottable(name) VALUES('mirg_a_portal'); # :mirg_a_portal_lt:
INSERT INTO loottable(name) VALUES('mirg_a_railing_holgresh'); # :mirg_a_railing_holgresh_lt:
INSERT INTO loottable(name) VALUES('mirg_a_ranting_holgresh'); # :mirg_a_ranting_holgresh_lt:
INSERT INTO loottable(name) VALUES('mirg_a_rime-bone_skeleton'); # :mirg_a_rime-bone_skeleton_lt:
INSERT INTO loottable(name) VALUES('mirg_a_scheming_fiend'); # :mirg_a_scheming_fiend_lt:
INSERT INTO loottable(name) VALUES('mirg_a_sentient_sludge'); # :mirg_a_sentient_sludge_lt:
INSERT INTO loottable(name) VALUES('mirg_a_shimmering_goo'); # :mirg_a_shimmering_goo_lt:
INSERT INTO loottable(name) VALUES('mirg_a_shimmering_skeleton'); # :mirg_a_shimmering_skeleton_lt:
INSERT INTO loottable(name) VALUES('mirg_a_singing_malformation'); # :mirg_a_singing_malformation_lt:
INSERT INTO loottable(name) VALUES('mirg_a_skeletal_apprentice'); # :mirg_a_skeletal_apprentice_lt:
INSERT INTO loottable(name) VALUES('mirg_a_skeletal_scholar'); # :mirg_a_skeletal_scholar_lt:
INSERT INTO loottable(name) VALUES('mirg_a_skeletal_worker'); # :mirg_a_skeletal_worker_lt:
INSERT INTO loottable(name) VALUES('mirg_a_snarling_manticore'); # :mirg_a_snarling_manticore_lt:
INSERT INTO loottable(name) VALUES('mirg_a_trapped_tormentor'); # :mirg_a_trapped_tormentor_lt:
INSERT INTO loottable(name) VALUES('mirg_a_vicious_magic_vortex'); # :mirg_a_vicious_magic_vortex_lt:
INSERT INTO loottable(name) VALUES('mirg_a_whirling_flurry'); # :mirg_a_whirling_flurry_lt:
INSERT INTO loottable(name) VALUES('mirg_glim'); # :mirg_glim_lt:
INSERT INTO loottable(name) VALUES('mirg_jagged_blades'); # :mirg_jagged_blades_lt:
INSERT INTO loottable(name) VALUES('mirg__'); # :mirg___lt:
