INSERT INTO loottable(name) VALUES('mirj_effusive_construct'); # :mirj_effusive_construct_lt:
INSERT INTO loottable(name) VALUES('mirj_siphoned_manticore'); # :mirj_siphoned_manticore_lt:
INSERT INTO loottable(name) VALUES('mirj_an_ancient_chest'); # :mirj_an_ancient_chest_lt:
INSERT INTO loottable(name) VALUES('mirj_a_blistering_glob_of_flesh'); # :mirj_a_blistering_glob_of_flesh_lt:
INSERT INTO loottable(name) VALUES('mirj_a_clattering_anomaly'); # :mirj_a_clattering_anomaly_lt:
INSERT INTO loottable(name) VALUES('mirj_a_confused_mutation'); # :mirj_a_confused_mutation_lt:
INSERT INTO loottable(name) VALUES('mirj_a_deluded_holgresh'); # :mirj_a_deluded_holgresh_lt:
INSERT INTO loottable(name) VALUES('mirj_a_dire_magic_vortex'); # :mirj_a_dire_magic_vortex_lt:
INSERT INTO loottable(name) VALUES('mirj_a_droning_malformation'); # :mirj_a_droning_malformation_lt:
INSERT INTO loottable(name) VALUES('mirj_a_fearsome_planar_specimen'); # :mirj_a_fearsome_planar_specimen_lt:
INSERT INTO loottable(name) VALUES('mirj_a_fidgeting_anomaly'); # :mirj_a_fidgeting_anomaly_lt:
INSERT INTO loottable(name) VALUES('mirj_a_frost_covered_barrel'); # :mirj_a_frost_covered_barrel_lt:
INSERT INTO loottable(name) VALUES('mirj_a_frustrated_fiend'); # :mirj_a_frustrated_fiend_lt:
INSERT INTO loottable(name) VALUES('mirj_a_humming_malformation'); # :mirj_a_humming_malformation_lt:
INSERT INTO loottable(name) VALUES('mirj_a_railing_holgresh'); # :mirj_a_railing_holgresh_lt:
INSERT INTO loottable(name) VALUES('mirj_a_ranting_holgresh'); # :mirj_a_ranting_holgresh_lt:
INSERT INTO loottable(name) VALUES('mirj_a_scheming_fiend'); # :mirj_a_scheming_fiend_lt:
INSERT INTO loottable(name) VALUES('mirj_a_skeletal_apprentice'); # :mirj_a_skeletal_apprentice_lt:
INSERT INTO loottable(name) VALUES('mirj_a_skeletal_scholar'); # :mirj_a_skeletal_scholar_lt:
INSERT INTO loottable(name) VALUES('mirj_a_skeletal_worker'); # :mirj_a_skeletal_worker_lt:
INSERT INTO loottable(name) VALUES('mirj_a_snarling_manticore'); # :mirj_a_snarling_manticore_lt:
INSERT INTO loottable(name) VALUES('mirj_a_trapped_tormentor'); # :mirj_a_trapped_tormentor_lt:
INSERT INTO loottable(name) VALUES('mirj_emili_the_powerful'); # :mirj_emili_the_powerful_lt:
INSERT INTO loottable(name) VALUES('mirj__'); # :mirj___lt:
