INSERT INTO loottable(name) VALUES('mmcb_scion_bone_binder'); # :mmcb_scion_bone_binder_lt:
INSERT INTO loottable(name) VALUES('mmcb_scion_harlot'); # :mmcb_scion_harlot_lt:
INSERT INTO loottable(name) VALUES('mmcb_scion_matron'); # :mmcb_scion_matron_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_bitten_victim'); # :mmcb_a_bitten_victim_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_bloodfang'); # :mmcb_a_bloodfang_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_bloodfiend'); # :mmcb_a_bloodfiend_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_bloodsucker'); # :mmcb_a_bloodsucker_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_cloud_of_poison'); # :mmcb_a_cloud_of_poison_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_dark_coffin'); # :mmcb_a_dark_coffin_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_deathcrawler'); # :mmcb_a_deathcrawler_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_dusty_barrel'); # :mmcb_a_dusty_barrel_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_dusty_box'); # :mmcb_a_dusty_box_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_festering_ooze'); # :mmcb_a_festering_ooze_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_foul_writher'); # :mmcb_a_foul_writher_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_lurker'); # :mmcb_a_lurker_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_marrow_hunter'); # :mmcb_a_marrow_hunter_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_beguiler'); # :mmcb_a_nightrage_beguiler_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_decapitator'); # :mmcb_a_nightrage_decapitator_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_diseaser'); # :mmcb_a_nightrage_diseaser_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_dreamthief'); # :mmcb_a_nightrage_dreamthief_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_fleshravager'); # :mmcb_a_nightrage_fleshravager_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_hunter'); # :mmcb_a_nightrage_hunter_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_idealist'); # :mmcb_a_nightrage_idealist_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_narcissist'); # :mmcb_a_nightrage_narcissist_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_occultist'); # :mmcb_a_nightrage_occultist_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_protector'); # :mmcb_a_nightrage_protector_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_rot-licker'); # :mmcb_a_nightrage_rot-licker_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_scrivener'); # :mmcb_a_nightrage_scrivener_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_skulker'); # :mmcb_a_nightrage_skulker_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_spiritravager'); # :mmcb_a_nightrage_spiritravager_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_nightrage_troglodyte'); # :mmcb_a_nightrage_troglodyte_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_rapacious_nightrage_skulker'); # :mmcb_a_rapacious_nightrage_skulker_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_rawbone'); # :mmcb_a_rawbone_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_sacrificing_trueborn'); # :mmcb_a_sacrificing_trueborn_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_savagefang_desecrator'); # :mmcb_a_savagefang_desecrator_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_savagefang_lightreaper'); # :mmcb_a_savagefang_lightreaper_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_savagefang_liturgist'); # :mmcb_a_savagefang_liturgist_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_savagefang_scrivener'); # :mmcb_a_savagefang_scrivener_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_savagefang_stalker'); # :mmcb_a_savagefang_stalker_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scavenger'); # :mmcb_a_scavenger_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_blood_agent'); # :mmcb_a_scion_blood_agent_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_blood_steward'); # :mmcb_a_scion_blood_steward_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_caretaker'); # :mmcb_a_scion_caretaker_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_conniver'); # :mmcb_a_scion_conniver_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_crypt_creeper'); # :mmcb_a_scion_crypt_creeper_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_cyst_maker'); # :mmcb_a_scion_cyst_maker_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_deathknave'); # :mmcb_a_scion_deathknave_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_debauchee'); # :mmcb_a_scion_debauchee_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_debaucher'); # :mmcb_a_scion_debaucher_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_essence_soother'); # :mmcb_a_scion_essence_soother_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_gorefeeder'); # :mmcb_a_scion_gorefeeder_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_nightwatcher'); # :mmcb_a_scion_nightwatcher_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_rites_chanter'); # :mmcb_a_scion_rites_chanter_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_rites_scribe'); # :mmcb_a_scion_rites_scribe_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_shadekeeper'); # :mmcb_a_scion_shadekeeper_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_shadowscout'); # :mmcb_a_scion_shadowscout_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_shadow_agent'); # :mmcb_a_scion_shadow_agent_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_soul_assaulter'); # :mmcb_a_scion_soul_assaulter_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_soul_bleeder'); # :mmcb_a_scion_soul_bleeder_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_scion_spiritknave'); # :mmcb_a_scion_spiritknave_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_shade'); # :mmcb_a_shade_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_assassin'); # :mmcb_a_trueborn_assassin_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_bloodprowler'); # :mmcb_a_trueborn_bloodprowler_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_creeper'); # :mmcb_a_trueborn_creeper_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_cryptrobber'); # :mmcb_a_trueborn_cryptrobber_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_deathknave'); # :mmcb_a_trueborn_deathknave_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_deathmarker'); # :mmcb_a_trueborn_deathmarker_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_embalmer'); # :mmcb_a_trueborn_embalmer_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_exemplar'); # :mmcb_a_trueborn_exemplar_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_flesh_reanimator'); # :mmcb_a_trueborn_flesh_reanimator_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_idealist'); # :mmcb_a_trueborn_idealist_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_narcissist'); # :mmcb_a_trueborn_narcissist_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_ritualcaller'); # :mmcb_a_trueborn_ritualcaller_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_sacrificer'); # :mmcb_a_trueborn_sacrificer_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_shadow_vanguard'); # :mmcb_a_trueborn_shadow_vanguard_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_soul_gnasher'); # :mmcb_a_trueborn_soul_gnasher_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_soul_leech'); # :mmcb_a_trueborn_soul_leech_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_soul_parasite'); # :mmcb_a_trueborn_soul_parasite_lt:
INSERT INTO loottable(name) VALUES('mmcb_a_trueborn_vanguard'); # :mmcb_a_trueborn_vanguard_lt:
INSERT INTO loottable(name) VALUES('mmcb_oredigger_bachin'); # :mmcb_oredigger_bachin_lt:
INSERT INTO loottable(name) VALUES('mmcb__bft'); # :mmcb__bft_lt:
