(:mmcd_a_dark_coffin_lt:, :spiderling_silk_ld:, 1),
(:mmcd_a_dusty_box_lt:, :spiderling_silk_ld:, 1),
(:mmcd_a_dusty_barrel_lt:, :spiderling_silk_ld:, 1),
(:mmcd_a_dark_chest_lt:, :spiderling_silk_ld:, 1),
(:mmcd_a_dark_coffin_lt:, :spider_silk_ld:, 1),
(:mmcd_a_dusty_box_lt:, :spider_silk_ld:, 1),
(:mmcd_a_dusty_barrel_lt:, :spider_silk_ld:, 1),
(:mmcd_a_dark_chest_lt:, :spider_silk_ld:, 1),
