INSERT INTO loottable(name) VALUES('mmci_crimson_cabal_heartlancer'); # :mmci_crimson_cabal_heartlancer_lt:
INSERT INTO loottable(name) VALUES('mmci_savagefang_spine_extractor'); # :mmci_savagefang_spine_extractor_lt:
INSERT INTO loottable(name) VALUES('mmci_trueborn_death_synergist'); # :mmci_trueborn_death_synergist_lt:
INSERT INTO loottable(name) VALUES('mmci_an_illusory_steward_soothsayer'); # :mmci_an_illusory_steward_soothsayer_lt:
INSERT INTO loottable(name) VALUES('mmci_a_bitten_victim'); # :mmci_a_bitten_victim_lt:
INSERT INTO loottable(name) VALUES('mmci_a_bloodbone'); # :mmci_a_bloodbone_lt:
INSERT INTO loottable(name) VALUES('mmci_a_bloodguard_deathcaller'); # :mmci_a_bloodguard_deathcaller_lt:
INSERT INTO loottable(name) VALUES('mmci_a_cloud_of_poison'); # :mmci_a_cloud_of_poison_lt:
INSERT INTO loottable(name) VALUES('mmci_a_crimson_cabal_deathprowler'); # :mmci_a_crimson_cabal_deathprowler_lt:
INSERT INTO loottable(name) VALUES('mmci_a_crimson_cabal_deceiver'); # :mmci_a_crimson_cabal_deceiver_lt:
INSERT INTO loottable(name) VALUES('mmci_a_crimson_cabal_devotee'); # :mmci_a_crimson_cabal_devotee_lt:
INSERT INTO loottable(name) VALUES('mmci_a_crimson_cabal_evangelist'); # :mmci_a_crimson_cabal_evangelist_lt:
INSERT INTO loottable(name) VALUES('mmci_a_crimson_cabal_overseer'); # :mmci_a_crimson_cabal_overseer_lt:
INSERT INTO loottable(name) VALUES('mmci_a_crimson_cabal_phantom'); # :mmci_a_crimson_cabal_phantom_lt:
INSERT INTO loottable(name) VALUES('mmci_a_crimson_cabal_subverter'); # :mmci_a_crimson_cabal_subverter_lt:
INSERT INTO loottable(name) VALUES('mmci_a_dusty_barrel'); # :mmci_a_dusty_barrel_lt:
INSERT INTO loottable(name) VALUES('mmci_a_dusty_box'); # :mmci_a_dusty_box_lt:
INSERT INTO loottable(name) VALUES('mmci_a_festering_ooze'); # :mmci_a_festering_ooze_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_coercer'); # :mmci_a_harvester_coercer_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_corpsecaller'); # :mmci_a_harvester_corpsecaller_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_cryptrobber'); # :mmci_a_harvester_cryptrobber_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_crypt_fiend'); # :mmci_a_harvester_crypt_fiend_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_crypt_pillager'); # :mmci_a_harvester_crypt_pillager_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_deathkeeper'); # :mmci_a_harvester_deathkeeper_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_deathprowler'); # :mmci_a_harvester_deathprowler_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_death_preserver'); # :mmci_a_harvester_death_preserver_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_deceiver'); # :mmci_a_harvester_deceiver_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_fleshburner'); # :mmci_a_harvester_fleshburner_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_gloombringer'); # :mmci_a_harvester_gloombringer_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_sentry'); # :mmci_a_harvester_sentry_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_soul_hunter'); # :mmci_a_harvester_soul_hunter_lt:
INSERT INTO loottable(name) VALUES('mmci_a_harvester_soul_sentry'); # :mmci_a_harvester_soul_sentry_lt:
INSERT INTO loottable(name) VALUES('mmci_a_rawbone'); # :mmci_a_rawbone_lt:
INSERT INTO loottable(name) VALUES('mmci_a_sacrificing_trueborn'); # :mmci_a_sacrificing_trueborn_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scavenger'); # :mmci_a_scavenger_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_blood_agent'); # :mmci_a_scion_blood_agent_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_crypt_creeper'); # :mmci_a_scion_crypt_creeper_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_deathknave'); # :mmci_a_scion_deathknave_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_debauchee'); # :mmci_a_scion_debauchee_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_debaucher'); # :mmci_a_scion_debaucher_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_nightwatcher'); # :mmci_a_scion_nightwatcher_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_rites_chanter'); # :mmci_a_scion_rites_chanter_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_shadekeeper'); # :mmci_a_scion_shadekeeper_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_shadowscout'); # :mmci_a_scion_shadowscout_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_shadow_agent'); # :mmci_a_scion_shadow_agent_lt:
INSERT INTO loottable(name) VALUES('mmci_a_scion_soul_bleeder'); # :mmci_a_scion_soul_bleeder_lt:
INSERT INTO loottable(name) VALUES('mmci_a_shade'); # :mmci_a_shade_lt:
INSERT INTO loottable(name) VALUES('mmci_a_steward_brooder'); # :mmci_a_steward_brooder_lt:
INSERT INTO loottable(name) VALUES('mmci_a_steward_darkguard'); # :mmci_a_steward_darkguard_lt:
INSERT INTO loottable(name) VALUES('mmci_a_steward_tormentor'); # :mmci_a_steward_tormentor_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_bloodprowler'); # :mmci_a_trueborn_bloodprowler_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_creeper'); # :mmci_a_trueborn_creeper_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_cryptrobber'); # :mmci_a_trueborn_cryptrobber_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_deathknave'); # :mmci_a_trueborn_deathknave_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_embalmer'); # :mmci_a_trueborn_embalmer_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_exemplar'); # :mmci_a_trueborn_exemplar_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_flesh_reanimator'); # :mmci_a_trueborn_flesh_reanimator_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_idealist'); # :mmci_a_trueborn_idealist_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_narcissist'); # :mmci_a_trueborn_narcissist_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_ritualcaller'); # :mmci_a_trueborn_ritualcaller_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_shadow_vanguard'); # :mmci_a_trueborn_shadow_vanguard_lt:
INSERT INTO loottable(name) VALUES('mmci_a_trueborn_vanguard'); # :mmci_a_trueborn_vanguard_lt:
INSERT INTO loottable(name) VALUES('mmci_a_warden'); # :mmci_a_warden_lt:
INSERT INTO loottable(name) VALUES('mmci__ift'); # :mmci__ift_lt:
