INSERT INTO loottable(name) VALUES('ruja_sikl_the_manslayer'); # :ruja_sikl_the_manslayer_lt:
INSERT INTO loottable(name) VALUES('ruja_slave_marauder'); # :ruja_slave_marauder_lt:
INSERT INTO loottable(name) VALUES('ruja_steelslave_infiltrator'); # :ruja_steelslave_infiltrator_lt:
INSERT INTO loottable(name) VALUES('ruja_an_orcish_chest'); # :ruja_an_orcish_chest_lt:
INSERT INTO loottable(name) VALUES('ruja_a_blade'); # :ruja_a_blade_lt:
INSERT INTO loottable(name) VALUES('ruja_a_captive_coin_chattel'); # :ruja_a_captive_coin_chattel_lt:
INSERT INTO loottable(name) VALUES('ruja_a_creaking_crate'); # :ruja_a_creaking_crate_lt:
INSERT INTO loottable(name) VALUES('ruja_a_festering_ooze'); # :ruja_a_festering_ooze_lt:
INSERT INTO loottable(name) VALUES('ruja_a_fleshfeaster'); # :ruja_a_fleshfeaster_lt:
INSERT INTO loottable(name) VALUES('ruja_a_metal_melter'); # :ruja_a_metal_melter_lt:
INSERT INTO loottable(name) VALUES('ruja_a_resilient_slave'); # :ruja_a_resilient_slave_lt:
INSERT INTO loottable(name) VALUES('ruja_a_slave_berserker'); # :ruja_a_slave_berserker_lt:
INSERT INTO loottable(name) VALUES('ruja_a_slave_slayer'); # :ruja_a_slave_slayer_lt:
INSERT INTO loottable(name) VALUES('ruja_a_steelslave_battle_medic'); # :ruja_a_steelslave_battle_medic_lt:
INSERT INTO loottable(name) VALUES('ruja_a_steelslave_legionnaire'); # :ruja_a_steelslave_legionnaire_lt:
INSERT INTO loottable(name) VALUES('ruja_a_steelslave_mender'); # :ruja_a_steelslave_mender_lt:
INSERT INTO loottable(name) VALUES('ruja_a_steelslave_mercenary'); # :ruja_a_steelslave_mercenary_lt:
INSERT INTO loottable(name) VALUES('ruja_a_steelslave_ruffian'); # :ruja_a_steelslave_ruffian_lt:
INSERT INTO loottable(name) VALUES('ruja_a_steelslave_soldier'); # :ruja_a_steelslave_soldier_lt:
INSERT INTO loottable(name) VALUES('ruja_a_steelslave_specialist'); # :ruja_a_steelslave_specialist_lt:
INSERT INTO loottable(name) VALUES('ruja_a_tortured_toiler'); # :ruja_a_tortured_toiler_lt:
INSERT INTO loottable(name) VALUES('ruja_a_wooden_barrel'); # :ruja_a_wooden_barrel_lt:
INSERT INTO loottable(name) VALUES('ruja_flavor_text'); # :ruja_flavor_text_lt:
INSERT INTO loottable(name) VALUES('ruja_jagged_blades'); # :ruja_jagged_blades_lt:
