INSERT INTO loottable(name) VALUES('rujg_researchers_box_of_supplies'); # :rujg_researchers_box_of_supplies_lt:
INSERT INTO loottable(name) VALUES('rujg_the_bloody_barrel'); # :rujg_the_bloody_barrel_lt:
INSERT INTO loottable(name) VALUES('rujg_the_splintering_barrel'); # :rujg_the_splintering_barrel_lt:
INSERT INTO loottable(name) VALUES('rujg_an_orcish_chest'); # :rujg_an_orcish_chest_lt:
INSERT INTO loottable(name) VALUES('rujg_a_barrel'); # :rujg_a_barrel_lt:
INSERT INTO loottable(name) VALUES('rujg_a_battle_harrower'); # :rujg_a_battle_harrower_lt:
INSERT INTO loottable(name) VALUES('rujg_a_blade'); # :rujg_a_blade_lt:
INSERT INTO loottable(name) VALUES('rujg_a_box'); # :rujg_a_box_lt:
INSERT INTO loottable(name) VALUES('rujg_a_captive_coin_drudge'); # :rujg_a_captive_coin_drudge_lt:
INSERT INTO loottable(name) VALUES('rujg_a_creaking_crate'); # :rujg_a_creaking_crate_lt:
INSERT INTO loottable(name) VALUES('rujg_a_festering_ooze'); # :rujg_a_festering_ooze_lt:
INSERT INTO loottable(name) VALUES('rujg_a_flesh_slasher'); # :rujg_a_flesh_slasher_lt:
INSERT INTO loottable(name) VALUES('rujg_a_limping_slave'); # :rujg_a_limping_slave_lt:
INSERT INTO loottable(name) VALUES('rujg_a_rujarkian_assassin'); # :rujg_a_rujarkian_assassin_lt:
INSERT INTO loottable(name) VALUES('rujg_a_slave_executioner'); # :rujg_a_slave_executioner_lt:
INSERT INTO loottable(name) VALUES('rujg_a_steelslave_assassin'); # :rujg_a_steelslave_assassin_lt:
INSERT INTO loottable(name) VALUES('rujg_a_steelslave_fleshstitcher'); # :rujg_a_steelslave_fleshstitcher_lt:
INSERT INTO loottable(name) VALUES('rujg_a_steelslave_legionnaire'); # :rujg_a_steelslave_legionnaire_lt:
INSERT INTO loottable(name) VALUES('rujg_a_steelslave_physician'); # :rujg_a_steelslave_physician_lt:
INSERT INTO loottable(name) VALUES('rujg_a_steelslave_practitioner'); # :rujg_a_steelslave_practitioner_lt:
INSERT INTO loottable(name) VALUES('rujg_a_tormented_sage'); # :rujg_a_tormented_sage_lt:
INSERT INTO loottable(name) VALUES('rujg_a_weapon_rack'); # :rujg_a_weapon_rack_lt:
INSERT INTO loottable(name) VALUES('rujg_crispen_koloff'); # :rujg_crispen_koloff_lt:
INSERT INTO loottable(name) VALUES('rujg_flawed_mutation'); # :rujg_flawed_mutation_lt:
INSERT INTO loottable(name) VALUES('rujg_flawed_mutation_'); # :rujg_flawed_mutation__lt:
INSERT INTO loottable(name) VALUES('rujg_flawless_experimental_battlelord'); # :rujg_flawless_experimental_battlelord_lt:
INSERT INTO loottable(name) VALUES('rujg_flawless_experimental_brute'); # :rujg_flawless_experimental_brute_lt:
INSERT INTO loottable(name) VALUES('rujg_jagged_blades'); # :rujg_jagged_blades_lt:
INSERT INTO loottable(name) VALUES('rujg_steelslave_researcher'); # :rujg_steelslave_researcher_lt:
INSERT INTO loottable(name) VALUES('rujg_steelslave_researcher_'); # :rujg_steelslave_researcher__lt:
INSERT INTO loottable(name) VALUES('rujg_steelslave_research_assistant'); # :rujg_steelslave_research_assistant_lt:
INSERT INTO loottable(name) VALUES('rujg_text1'); # :rujg_text1_lt:
INSERT INTO loottable(name) VALUES('rujg_text10'); # :rujg_text10_lt:
INSERT INTO loottable(name) VALUES('rujg_text11'); # :rujg_text11_lt:
INSERT INTO loottable(name) VALUES('rujg_text12'); # :rujg_text12_lt:
INSERT INTO loottable(name) VALUES('rujg_text13'); # :rujg_text13_lt:
INSERT INTO loottable(name) VALUES('rujg_text14'); # :rujg_text14_lt:
INSERT INTO loottable(name) VALUES('rujg_text15'); # :rujg_text15_lt:
INSERT INTO loottable(name) VALUES('rujg_text2'); # :rujg_text2_lt:
INSERT INTO loottable(name) VALUES('rujg_text3'); # :rujg_text3_lt:
INSERT INTO loottable(name) VALUES('rujg_text4'); # :rujg_text4_lt:
INSERT INTO loottable(name) VALUES('rujg_text5'); # :rujg_text5_lt:
INSERT INTO loottable(name) VALUES('rujg_text6'); # :rujg_text6_lt:
INSERT INTO loottable(name) VALUES('rujg_text7'); # :rujg_text7_lt:
INSERT INTO loottable(name) VALUES('rujg_text8'); # :rujg_text8_lt:
INSERT INTO loottable(name) VALUES('rujg_text9'); # :rujg_text9_lt:
INSERT INTO loottable(name) VALUES('rujg_violent_research_subject'); # :rujg_violent_research_subject_lt:
INSERT INTO loottable(name) VALUES('rujg_zone_status'); # :rujg_zone_status_lt:
INSERT INTO loottable(name) VALUES('rujg__'); # :rujg___lt:
INSERT INTO loottable(name) VALUES('rujg__ft'); # :rujg__ft_lt:
