INSERT INTO loottable(name) VALUES('ruji_rebellious_arcanist'); # :ruji_rebellious_arcanist_lt:
INSERT INTO loottable(name) VALUES('ruji_an_orcish_chest'); # :ruji_an_orcish_chest_lt:
INSERT INTO loottable(name) VALUES('ruji_a_battle_harrower'); # :ruji_a_battle_harrower_lt:
INSERT INTO loottable(name) VALUES('ruji_a_captive_coin_chattel'); # :ruji_a_captive_coin_chattel_lt:
INSERT INTO loottable(name) VALUES('ruji_a_captive_coin_drudge'); # :ruji_a_captive_coin_drudge_lt:
INSERT INTO loottable(name) VALUES('ruji_a_chanting_slave'); # :ruji_a_chanting_slave_lt:
INSERT INTO loottable(name) VALUES('ruji_a_creaking_crate'); # :ruji_a_creaking_crate_lt:
INSERT INTO loottable(name) VALUES('ruji_a_fleshfeaster'); # :ruji_a_fleshfeaster_lt:
INSERT INTO loottable(name) VALUES('ruji_a_flesh_ripper'); # :ruji_a_flesh_ripper_lt:
INSERT INTO loottable(name) VALUES('ruji_a_metal_melter'); # :ruji_a_metal_melter_lt:
INSERT INTO loottable(name) VALUES('ruji_a_resilient_slave'); # :ruji_a_resilient_slave_lt:
INSERT INTO loottable(name) VALUES('ruji_a_rujarkian_appeaser'); # :ruji_a_rujarkian_appeaser_lt:
INSERT INTO loottable(name) VALUES('ruji_a_slave_slayer'); # :ruji_a_slave_slayer_lt:
INSERT INTO loottable(name) VALUES('ruji_a_spiritual_drudge'); # :ruji_a_spiritual_drudge_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_assassin'); # :ruji_a_steelslave_assassin_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_bonecrusher'); # :ruji_a_steelslave_bonecrusher_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_bruiser'); # :ruji_a_steelslave_bruiser_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_legionnaire'); # :ruji_a_steelslave_legionnaire_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_mender'); # :ruji_a_steelslave_mender_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_mercenary'); # :ruji_a_steelslave_mercenary_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_ruffian'); # :ruji_a_steelslave_ruffian_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_soldier'); # :ruji_a_steelslave_soldier_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_specialist'); # :ruji_a_steelslave_specialist_lt:
INSERT INTO loottable(name) VALUES('ruji_a_steelslave_spiritcaller'); # :ruji_a_steelslave_spiritcaller_lt:
INSERT INTO loottable(name) VALUES('ruji_a_tortured_toiler'); # :ruji_a_tortured_toiler_lt:
