INSERT INTO loottable(name) VALUES('takb_amethyst_summoning'); # :takb_amethyst_summoning_lt:
INSERT INTO loottable(name) VALUES('takb_panicked_summoning'); # :takb_panicked_summoning_lt:
INSERT INTO loottable(name) VALUES('takb_an_ancient_sand_frog'); # :takb_an_ancient_sand_frog_lt:
INSERT INTO loottable(name) VALUES('takb_an_earthen_defender'); # :takb_an_earthen_defender_lt:
INSERT INTO loottable(name) VALUES('takb_an_enraged_stoneservant'); # :takb_an_enraged_stoneservant_lt:
INSERT INTO loottable(name) VALUES('takb_a_city_patroller'); # :takb_a_city_patroller_lt:
INSERT INTO loottable(name) VALUES('takb_a_flowkeeper_director'); # :takb_a_flowkeeper_director_lt:
INSERT INTO loottable(name) VALUES('takb_a_flowkeeper_engineer'); # :takb_a_flowkeeper_engineer_lt:
INSERT INTO loottable(name) VALUES('takb_a_flowkeeper_inventor'); # :takb_a_flowkeeper_inventor_lt:
INSERT INTO loottable(name) VALUES('takb_a_flustered_sandspirit'); # :takb_a_flustered_sandspirit_lt:
INSERT INTO loottable(name) VALUES('takb_a_forgotten_cave_dweller'); # :takb_a_forgotten_cave_dweller_lt:
INSERT INTO loottable(name) VALUES('takb_a_geomantic_compact_prodigy'); # :takb_a_geomantic_compact_prodigy_lt:
INSERT INTO loottable(name) VALUES('takb_a_giant_burrowing_scarab'); # :takb_a_giant_burrowing_scarab_lt:
INSERT INTO loottable(name) VALUES('takb_a_guardian_of_sand'); # :takb_a_guardian_of_sand_lt:
INSERT INTO loottable(name) VALUES('takb_a_hollow_tree'); # :takb_a_hollow_tree_lt:
INSERT INTO loottable(name) VALUES('takb_a_jeweled_guard_hero'); # :takb_a_jeweled_guard_hero_lt:
INSERT INTO loottable(name) VALUES('takb_a_menacing_tree_spirit'); # :takb_a_menacing_tree_spirit_lt:
INSERT INTO loottable(name) VALUES('takb_a_petrified_colossal_tree'); # :takb_a_petrified_colossal_tree_lt:
INSERT INTO loottable(name) VALUES('takb_a_phosphorescent_golem'); # :takb_a_phosphorescent_golem_lt:
INSERT INTO loottable(name) VALUES('takb_a_pristine_guardian'); # :takb_a_pristine_guardian_lt:
INSERT INTO loottable(name) VALUES('takb_a_royal_advisor'); # :takb_a_royal_advisor_lt:
INSERT INTO loottable(name) VALUES('takb_a_royal_confidante'); # :takb_a_royal_confidante_lt:
INSERT INTO loottable(name) VALUES('takb_a_royal_guardian'); # :takb_a_royal_guardian_lt:
INSERT INTO loottable(name) VALUES('takb_a_royal_hierophant'); # :takb_a_royal_hierophant_lt:
INSERT INTO loottable(name) VALUES('takb_a_royal_protector'); # :takb_a_royal_protector_lt:
INSERT INTO loottable(name) VALUES('takb_a_royal_sandadvisor'); # :takb_a_royal_sandadvisor_lt:
INSERT INTO loottable(name) VALUES('takb_a_summoned_greater_defender'); # :takb_a_summoned_greater_defender_lt:
INSERT INTO loottable(name) VALUES('takb_a_takish-hiz_recordkeeper'); # :takb_a_takish-hiz_recordkeeper_lt:
INSERT INTO loottable(name) VALUES('takb_a_talented_gemsetter'); # :takb_a_talented_gemsetter_lt:
INSERT INTO loottable(name) VALUES('takb_a_wooden_barrel'); # :takb_a_wooden_barrel_lt:
INSERT INTO loottable(name) VALUES('takb_flavor_text_one'); # :takb_flavor_text_one_lt:
INSERT INTO loottable(name) VALUES('takb_flavor_text_three'); # :takb_flavor_text_three_lt:
INSERT INTO loottable(name) VALUES('takb_flavor_text_two'); # :takb_flavor_text_two_lt:
