INSERT INTO loottable(name) VALUES('takc_kamoj_the_protector'); # :takc_kamoj_the_protector_lt:
INSERT INTO loottable(name) VALUES('takc_ledanne_the_rejuvenator'); # :takc_ledanne_the_rejuvenator_lt:
INSERT INTO loottable(name) VALUES('takc_quintessence_of_sand'); # :takc_quintessence_of_sand_lt:
INSERT INTO loottable(name) VALUES('takc_ritanas_ornate_chest'); # :takc_ritanas_ornate_chest_lt:
INSERT INTO loottable(name) VALUES('takc_the_earthen_chest'); # :takc_the_earthen_chest_lt:
INSERT INTO loottable(name) VALUES('takc_the_gem_encrusted_chest'); # :takc_the_gem_encrusted_chest_lt:
INSERT INTO loottable(name) VALUES('takc_thosan_the_manipulator'); # :takc_thosan_the_manipulator_lt:
INSERT INTO loottable(name) VALUES('takc_tweyne_the_sandcaller'); # :takc_tweyne_the_sandcaller_lt:
INSERT INTO loottable(name) VALUES('takc_unala_the_avenger'); # :takc_unala_the_avenger_lt:
INSERT INTO loottable(name) VALUES('takc_an_ancient_sand_frog'); # :takc_an_ancient_sand_frog_lt:
INSERT INTO loottable(name) VALUES('takc_an_angry_sappling'); # :takc_an_angry_sappling_lt:
INSERT INTO loottable(name) VALUES('takc_an_earthen_defender'); # :takc_an_earthen_defender_lt:
INSERT INTO loottable(name) VALUES('takc_an_elemental_spirit'); # :takc_an_elemental_spirit_lt:
INSERT INTO loottable(name) VALUES('takc_an_enraged_stoneservant'); # :takc_an_enraged_stoneservant_lt:
INSERT INTO loottable(name) VALUES('takc_an_intense_spiritstorm'); # :takc_an_intense_spiritstorm_lt:
INSERT INTO loottable(name) VALUES('takc_a_desert_curse'); # :takc_a_desert_curse_lt:
INSERT INTO loottable(name) VALUES('takc_a_flowkeeper_director'); # :takc_a_flowkeeper_director_lt:
INSERT INTO loottable(name) VALUES('takc_a_flowkeeper_inventor'); # :takc_a_flowkeeper_inventor_lt:
INSERT INTO loottable(name) VALUES('takc_a_forgotten_cave_dweller'); # :takc_a_forgotten_cave_dweller_lt:
INSERT INTO loottable(name) VALUES('takc_a_geomantic_compact_prodigy'); # :takc_a_geomantic_compact_prodigy_lt:
INSERT INTO loottable(name) VALUES('takc_a_giant_burrowing_scarab'); # :takc_a_giant_burrowing_scarab_lt:
INSERT INTO loottable(name) VALUES('takc_a_guardian_of_sand'); # :takc_a_guardian_of_sand_lt:
INSERT INTO loottable(name) VALUES('takc_a_guardian_of_the_compact'); # :takc_a_guardian_of_the_compact_lt:
INSERT INTO loottable(name) VALUES('takc_a_hollow_tree'); # :takc_a_hollow_tree_lt:
INSERT INTO loottable(name) VALUES('takc_a_jeweled_guard_hero'); # :takc_a_jeweled_guard_hero_lt:
INSERT INTO loottable(name) VALUES('takc_a_menacing_tree_spirit'); # :takc_a_menacing_tree_spirit_lt:
INSERT INTO loottable(name) VALUES('takc_a_petrified_observer'); # :takc_a_petrified_observer_lt:
INSERT INTO loottable(name) VALUES('takc_a_royal_confidante'); # :takc_a_royal_confidante_lt:
INSERT INTO loottable(name) VALUES('takc_a_royal_guardian'); # :takc_a_royal_guardian_lt:
INSERT INTO loottable(name) VALUES('takc_a_royal_hierophant'); # :takc_a_royal_hierophant_lt:
INSERT INTO loottable(name) VALUES('takc_a_royal_messenger'); # :takc_a_royal_messenger_lt:
INSERT INTO loottable(name) VALUES('takc_a_royal_representative'); # :takc_a_royal_representative_lt:
INSERT INTO loottable(name) VALUES('takc_a_royal_sandadvisor'); # :takc_a_royal_sandadvisor_lt:
INSERT INTO loottable(name) VALUES('takc_a_summoned_greater_defender'); # :takc_a_summoned_greater_defender_lt:
INSERT INTO loottable(name) VALUES('takc_a_trusted_flowkeeper'); # :takc_a_trusted_flowkeeper_lt:
INSERT INTO loottable(name) VALUES('takc_a_vengeful_gemwalker'); # :takc_a_vengeful_gemwalker_lt:
INSERT INTO loottable(name) VALUES('takc_golem_flavor_text'); # :takc_golem_flavor_text_lt:
INSERT INTO loottable(name) VALUES('takc_priest_flavor_text'); # :takc_priest_flavor_text_lt:
INSERT INTO loottable(name) VALUES('takc_ritana_the_convoker'); # :takc_ritana_the_convoker_lt:
INSERT INTO loottable(name) VALUES('takc_split_flavor_text'); # :takc_split_flavor_text_lt:
INSERT INTO loottable(name) VALUES('takc_trap2'); # :takc_trap2_lt:
INSERT INTO loottable(name) VALUES('takc_zone_status'); # :takc_zone_status_lt:
