INSERT INTO loottable(name) VALUES('takf_calcified_frog'); # :takf_calcified_frog_lt:
INSERT INTO loottable(name) VALUES('takf_dazed_philosopher'); # :takf_dazed_philosopher_lt:
INSERT INTO loottable(name) VALUES('takf_quartz_worker'); # :takf_quartz_worker_lt:
INSERT INTO loottable(name) VALUES('takf_young_jeweled_guard_recruit'); # :takf_young_jeweled_guard_recruit_lt:
INSERT INTO loottable(name) VALUES('takf_an_earthen_digger'); # :takf_an_earthen_digger_lt:
INSERT INTO loottable(name) VALUES('takf_an_initiate_flowkeeper'); # :takf_an_initiate_flowkeeper_lt:
INSERT INTO loottable(name) VALUES('takf_a_cloud_of_poison'); # :takf_a_cloud_of_poison_lt:
INSERT INTO loottable(name) VALUES('takf_a_concealed_observer'); # :takf_a_concealed_observer_lt:
INSERT INTO loottable(name) VALUES('takf_a_dazed_royal'); # :takf_a_dazed_royal_lt:
INSERT INTO loottable(name) VALUES('takf_a_dazzling_worker'); # :takf_a_dazzling_worker_lt:
INSERT INTO loottable(name) VALUES('takf_a_flowkeeper_acolyte'); # :takf_a_flowkeeper_acolyte_lt:
INSERT INTO loottable(name) VALUES('takf_a_geomancer_guard'); # :takf_a_geomancer_guard_lt:
INSERT INTO loottable(name) VALUES('takf_a_geomantic_compact_initiate'); # :takf_a_geomantic_compact_initiate_lt:
INSERT INTO loottable(name) VALUES('takf_a_geomantic_compact_instructor'); # :takf_a_geomantic_compact_instructor_lt:
INSERT INTO loottable(name) VALUES('takf_a_hardened_frog'); # :takf_a_hardened_frog_lt:
INSERT INTO loottable(name) VALUES('takf_a_hissing_spiritstorm'); # :takf_a_hissing_spiritstorm_lt:
INSERT INTO loottable(name) VALUES('takf_a_jeweled_guard_sentry'); # :takf_a_jeweled_guard_sentry_lt:
INSERT INTO loottable(name) VALUES('takf_a_jeweled_guard_strategist'); # :takf_a_jeweled_guard_strategist_lt:
INSERT INTO loottable(name) VALUES('takf_a_lesser_royal'); # :takf_a_lesser_royal_lt:
INSERT INTO loottable(name) VALUES('takf_a_petrified_tree'); # :takf_a_petrified_tree_lt:
INSERT INTO loottable(name) VALUES('takf_a_royal_advisor'); # :takf_a_royal_advisor_lt:
INSERT INTO loottable(name) VALUES('takf_a_royal_associate'); # :takf_a_royal_associate_lt:
INSERT INTO loottable(name) VALUES('takf_a_royal_devotee'); # :takf_a_royal_devotee_lt:
INSERT INTO loottable(name) VALUES('takf_a_royal_regulator'); # :takf_a_royal_regulator_lt:
INSERT INTO loottable(name) VALUES('takf_a_sand_collector'); # :takf_a_sand_collector_lt:
INSERT INTO loottable(name) VALUES('takf_a_sand_surveyor'); # :takf_a_sand_surveyor_lt:
INSERT INTO loottable(name) VALUES('takf_a_sand_vortex'); # :takf_a_sand_vortex_lt:
INSERT INTO loottable(name) VALUES('takf_a_sand_weaver'); # :takf_a_sand_weaver_lt:
INSERT INTO loottable(name) VALUES('takf_a_small_burrowing_scarab'); # :takf_a_small_burrowing_scarab_lt:
INSERT INTO loottable(name) VALUES('takf_a_summoned_defender'); # :takf_a_summoned_defender_lt:
INSERT INTO loottable(name) VALUES('takf_a_takish-hiz_patroller'); # :takf_a_takish-hiz_patroller_lt:
INSERT INTO loottable(name) VALUES('takf_a_wooden_barrel'); # :takf_a_wooden_barrel_lt:
INSERT INTO loottable(name) VALUES('takf_flavor_text_one'); # :takf_flavor_text_one_lt:
INSERT INTO loottable(name) VALUES('takf_flavor_text_three'); # :takf_flavor_text_three_lt:
INSERT INTO loottable(name) VALUES('takf_flavor_text_two'); # :takf_flavor_text_two_lt:
