INSERT INTO loottable(name) VALUES('discord_grgnok'); # :discord_grgnok_lt:
INSERT INTO loottable(name) VALUES('discord_herald_of_druzzil_ro'); # :discord_herald_of_druzzil_ro_lt:
INSERT INTO loottable(name) VALUES('discord_an_aneuk_mindrender'); # :discord_an_aneuk_mindrender_lt:
INSERT INTO loottable(name) VALUES('discord_an_aneuk_overfiend'); # :discord_an_aneuk_overfiend_lt:
INSERT INTO loottable(name) VALUES('discord_an_ikaav_corrupter'); # :discord_an_ikaav_corrupter_lt:
INSERT INTO loottable(name) VALUES('discord_an_ikaav_envenomer'); # :discord_an_ikaav_envenomer_lt:
INSERT INTO loottable(name) VALUES('discord_an_ixt_commander'); # :discord_an_ixt_commander_lt:
INSERT INTO loottable(name) VALUES('discord_an_ukun_bloodsniffer'); # :discord_an_ukun_bloodsniffer_lt:
INSERT INTO loottable(name) VALUES('discord_an_ukun_carnophage'); # :discord_an_ukun_carnophage_lt:
INSERT INTO loottable(name) VALUES('discord_an_ukun_thrasher'); # :discord_an_ukun_thrasher_lt:
INSERT INTO loottable(name) VALUES('discord_a_bazu_pulverizer'); # :discord_a_bazu_pulverizer_lt:
INSERT INTO loottable(name) VALUES('discord_a_bloodthirsty_feran'); # :discord_a_bloodthirsty_feran_lt:
INSERT INTO loottable(name) VALUES('discord_a_discordling_mangler'); # :discord_a_discordling_mangler_lt:
INSERT INTO loottable(name) VALUES('discord_a_discordling_ravager'); # :discord_a_discordling_ravager_lt:
INSERT INTO loottable(name) VALUES('discord_a_disheveled_human'); # :discord_a_disheveled_human_lt:
INSERT INTO loottable(name) VALUES('discord_a_gelidran_rift_slave'); # :discord_a_gelidran_rift_slave_lt:
INSERT INTO loottable(name) VALUES('discord_a_huvul_lord'); # :discord_a_huvul_lord_lt:
INSERT INTO loottable(name) VALUES('discord_a_kyv_deathstalker'); # :discord_a_kyv_deathstalker_lt:
INSERT INTO loottable(name) VALUES('discord_a_kyv_slayer'); # :discord_a_kyv_slayer_lt:
INSERT INTO loottable(name) VALUES('discord_a_lightning_warrior_galvanizer'); # :discord_a_lightning_warrior_galvanizer_lt:
INSERT INTO loottable(name) VALUES('discord_a_mastruq_fleshrender'); # :discord_a_mastruq_fleshrender_lt:
INSERT INTO loottable(name) VALUES('discord_a_mastruq_paindrinker'); # :discord_a_mastruq_paindrinker_lt:
INSERT INTO loottable(name) VALUES('discord_a_mindshear_attendant'); # :discord_a_mindshear_attendant_lt:
INSERT INTO loottable(name) VALUES('discord_a_noc_bloodthirster'); # :discord_a_noc_bloodthirster_lt:
INSERT INTO loottable(name) VALUES('discord_a_noc_ripper'); # :discord_a_noc_ripper_lt:
INSERT INTO loottable(name) VALUES('discord_a_pyrilen_rift_slave'); # :discord_a_pyrilen_rift_slave_lt:
INSERT INTO loottable(name) VALUES('discord_a_ratuk_bonecleaver'); # :discord_a_ratuk_bonecleaver_lt:
INSERT INTO loottable(name) VALUES('discord_a_ratuk_executioner'); # :discord_a_ratuk_executioner_lt:
INSERT INTO loottable(name) VALUES('discord_a_ratuk_skullsplitter'); # :discord_a_ratuk_skullsplitter_lt:
INSERT INTO loottable(name) VALUES('discord_a_vitrik_corporifer'); # :discord_a_vitrik_corporifer_lt:
INSERT INTO loottable(name) VALUES('discord_a_vitrik_portal_slaver'); # :discord_a_vitrik_portal_slaver_lt:
INSERT INTO loottable(name) VALUES('discord_telivar_spawner'); # :discord_telivar_spawner_lt:
