INSERT INTO loottable(name) VALUES('korascian_bikk'); # :korascian_bikk_lt:
INSERT INTO loottable(name) VALUES('korascian_catapult_gaakan_operator'); # :korascian_catapult_gaakan_operator_lt:
INSERT INTO loottable(name) VALUES('korascian_catapult_kefguk_operator'); # :korascian_catapult_kefguk_operator_lt:
INSERT INTO loottable(name) VALUES('korascian_catapult_morg_operator'); # :korascian_catapult_morg_operator_lt:
INSERT INTO loottable(name) VALUES('korascian_catapult_rosk_operator'); # :korascian_catapult_rosk_operator_lt:
INSERT INTO loottable(name) VALUES('korascian_catapult_tekk_operator'); # :korascian_catapult_tekk_operator_lt:
INSERT INTO loottable(name) VALUES('korascian_crystalline_imperiont'); # :korascian_crystalline_imperiont_lt:
INSERT INTO loottable(name) VALUES('korascian_crystalline_sorcidont'); # :korascian_crystalline_sorcidont_lt:
INSERT INTO loottable(name) VALUES('korascian_dalikand_darkhammer'); # :korascian_dalikand_darkhammer_lt:
INSERT INTO loottable(name) VALUES('korascian_delver_hagorn'); # :korascian_delver_hagorn_lt:
INSERT INTO loottable(name) VALUES('korascian_glerud_darkhammer'); # :korascian_glerud_darkhammer_lt:
INSERT INTO loottable(name) VALUES('korascian_kaigrun_darkhammer'); # :korascian_kaigrun_darkhammer_lt:
INSERT INTO loottable(name) VALUES('korascian_korascian_prime'); # :korascian_korascian_prime_lt:
INSERT INTO loottable(name) VALUES('korascian_krant'); # :korascian_krant_lt:
INSERT INTO loottable(name) VALUES('korascian_murdunk'); # :korascian_murdunk_lt:
INSERT INTO loottable(name) VALUES('korascian_nedsin_tabbels'); # :korascian_nedsin_tabbels_lt:
INSERT INTO loottable(name) VALUES('korascian_ordrik_darkhammer'); # :korascian_ordrik_darkhammer_lt:
INSERT INTO loottable(name) VALUES('korascian_sterik_gristmaker'); # :korascian_sterik_gristmaker_lt:
INSERT INTO loottable(name) VALUES('korascian_ulgin_darkhammer'); # :korascian_ulgin_darkhammer_lt:
INSERT INTO loottable(name) VALUES('korascian_ylatra_the_vassal'); # :korascian_ylatra_the_vassal_lt:
INSERT INTO loottable(name) VALUES('korascian_an_agent_of_discord'); # :korascian_an_agent_of_discord_lt:
INSERT INTO loottable(name) VALUES('korascian_an_earthen_warden'); # :korascian_an_earthen_warden_lt:
INSERT INTO loottable(name) VALUES('korascian_a_clay_golem'); # :korascian_a_clay_golem_lt:
INSERT INTO loottable(name) VALUES('korascian_a_crystalline_aetheront'); # :korascian_a_crystalline_aetheront_lt:
INSERT INTO loottable(name) VALUES('korascian_a_crystalline_corrupter'); # :korascian_a_crystalline_corrupter_lt:
INSERT INTO loottable(name) VALUES('korascian_a_crystalline_discharger'); # :korascian_a_crystalline_discharger_lt:
INSERT INTO loottable(name) VALUES('korascian_a_crystalline_exterminator'); # :korascian_a_crystalline_exterminator_lt:
INSERT INTO loottable(name) VALUES('korascian_a_crystalline_hulk'); # :korascian_a_crystalline_hulk_lt:
INSERT INTO loottable(name) VALUES('korascian_a_crystalline_sphere'); # :korascian_a_crystalline_sphere_lt:
INSERT INTO loottable(name) VALUES('korascian_a_crystalline_trichordont'); # :korascian_a_crystalline_trichordont_lt:
INSERT INTO loottable(name) VALUES('korascian_a_crystalline_visceront'); # :korascian_a_crystalline_visceront_lt:
INSERT INTO loottable(name) VALUES('korascian_a_darkhammer_miner'); # :korascian_a_darkhammer_miner_lt:
INSERT INTO loottable(name) VALUES('korascian_a_darkhammer_paladin'); # :korascian_a_darkhammer_paladin_lt:
INSERT INTO loottable(name) VALUES('korascian_a_darkhammer_prospector'); # :korascian_a_darkhammer_prospector_lt:
INSERT INTO loottable(name) VALUES('korascian_a_darkhammer_rowdy'); # :korascian_a_darkhammer_rowdy_lt:
INSERT INTO loottable(name) VALUES('korascian_a_darkhammer_runeholder'); # :korascian_a_darkhammer_runeholder_lt:
INSERT INTO loottable(name) VALUES('korascian_a_darkhammer_stonemaster'); # :korascian_a_darkhammer_stonemaster_lt:
INSERT INTO loottable(name) VALUES('korascian_a_darkhammer_thane'); # :korascian_a_darkhammer_thane_lt:
INSERT INTO loottable(name) VALUES('korascian_a_disciple_of_zek'); # :korascian_a_disciple_of_zek_lt:
INSERT INTO loottable(name) VALUES('korascian_a_korascian_champion'); # :korascian_a_korascian_champion_lt:
INSERT INTO loottable(name) VALUES('korascian_a_korascian_sentinel'); # :korascian_a_korascian_sentinel_lt:
INSERT INTO loottable(name) VALUES('korascian_a_korascian_thrall'); # :korascian_a_korascian_thrall_lt:
INSERT INTO loottable(name) VALUES('korascian_a_mithril_golem'); # :korascian_a_mithril_golem_lt:
INSERT INTO loottable(name) VALUES('korascian_a_moss_spider'); # :korascian_a_moss_spider_lt:
INSERT INTO loottable(name) VALUES('korascian_a_priest_of_discord'); # :korascian_a_priest_of_discord_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_archer'); # :korascian_a_rallosian_archer_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_artillery_chief'); # :korascian_a_rallosian_artillery_chief_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_boulder_thrower'); # :korascian_a_rallosian_boulder_thrower_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_catapult_loader'); # :korascian_a_rallosian_catapult_loader_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_dakkilon_warrior'); # :korascian_a_rallosian_dakkilon_warrior_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_fodderling'); # :korascian_a_rallosian_fodderling_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_guard'); # :korascian_a_rallosian_guard_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_guardsman'); # :korascian_a_rallosian_guardsman_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_invader'); # :korascian_a_rallosian_invader_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_lifetaker'); # :korascian_a_rallosian_lifetaker_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_marauder'); # :korascian_a_rallosian_marauder_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_messcook'); # :korascian_a_rallosian_messcook_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_provost'); # :korascian_a_rallosian_provost_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_salvebringer'); # :korascian_a_rallosian_salvebringer_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_scout'); # :korascian_a_rallosian_scout_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_shirker'); # :korascian_a_rallosian_shirker_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_shocktrooper'); # :korascian_a_rallosian_shocktrooper_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_soldier'); # :korascian_a_rallosian_soldier_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rallosian_warbrute'); # :korascian_a_rallosian_warbrute_lt:
INSERT INTO loottable(name) VALUES('korascian_a_rathecharmed_scarab'); # :korascian_a_rathecharmed_scarab_lt:
INSERT INTO loottable(name) VALUES('korascian_a_spinecutter_basilisk'); # :korascian_a_spinecutter_basilisk_lt:
INSERT INTO loottable(name) VALUES('korascian_a_vekerchiki_warrior'); # :korascian_a_vekerchiki_warrior_lt:
INSERT INTO loottable(name) VALUES('korascian_crystal_pit'); # :korascian_crystal_pit_lt:
INSERT INTO loottable(name) VALUES('korascian_fsp-general-noeffect'); # :korascian_fsp-general-noeffect_lt:
