INSERT INTO loottable(name) VALUES('oceangreenhills_assistant_josephine'); # :oceangreenhills_assistant_josephine_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_bracka_darkpaw'); # :oceangreenhills_bracka_darkpaw_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_captain_hiran_tillin'); # :oceangreenhills_captain_hiran_tillin_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_cirtan,_bayles_herald'); # :oceangreenhills_cirtan,_bayles_herald_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_elder_mystic_foppye'); # :oceangreenhills_elder_mystic_foppye_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_evon_sewurd'); # :oceangreenhills_evon_sewurd_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_fripp_darkpaw'); # :oceangreenhills_fripp_darkpaw_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_jessica_marsdaughter'); # :oceangreenhills_jessica_marsdaughter_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_raxtor_darkpaw'); # :oceangreenhills_raxtor_darkpaw_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_acolyte_gnoren'); # :oceangreenhills_acolyte_gnoren_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_acolyte_harene'); # :oceangreenhills_acolyte_harene_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_acolyte_hueld'); # :oceangreenhills_acolyte_hueld_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_acolyte_jelneo'); # :oceangreenhills_acolyte_jelneo_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_acolyte_jora'); # :oceangreenhills_acolyte_jora_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_acolyte_koel'); # :oceangreenhills_acolyte_koel_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_acolyte_nolea'); # :oceangreenhills_acolyte_nolea_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_acolyte_vessa'); # :oceangreenhills_acolyte_vessa_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_an_infected_bat'); # :oceangreenhills_an_infected_bat_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_an_infected_brown_bear'); # :oceangreenhills_an_infected_brown_bear_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_an_infected_fire_beetle'); # :oceangreenhills_an_infected_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_an_infected_gray_wolf'); # :oceangreenhills_an_infected_gray_wolf_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_an_infected_king_snake'); # :oceangreenhills_an_infected_king_snake_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_an_infected_large_rat'); # :oceangreenhills_an_infected_large_rat_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_an_undead_soldier'); # :oceangreenhills_an_undead_soldier_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_archon_darianna_althus'); # :oceangreenhills_archon_darianna_althus_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_blackbriar'); # :oceangreenhills_a_blackbriar_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_blackburrow_lurker'); # :oceangreenhills_a_blackburrow_lurker_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_blackburrow_reaver'); # :oceangreenhills_a_blackburrow_reaver_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_brown_bear'); # :oceangreenhills_a_brown_bear_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_carpenter'); # :oceangreenhills_a_carpenter_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_darkpaw_mystic'); # :oceangreenhills_a_darkpaw_mystic_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_darkpaw_patroller'); # :oceangreenhills_a_darkpaw_patroller_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_darkpaw_warrior'); # :oceangreenhills_a_darkpaw_warrior_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_decaying_rager'); # :oceangreenhills_a_decaying_rager_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_desiccated_treeling'); # :oceangreenhills_a_desiccated_treeling_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_diseased_bat_corpse'); # :oceangreenhills_a_diseased_bat_corpse_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_diseased_beetle_corpse'); # :oceangreenhills_a_diseased_beetle_corpse_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_diseased_brown_bear_corpse'); # :oceangreenhills_a_diseased_brown_bear_corpse_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_diseased_gray_wolf_corpse'); # :oceangreenhills_a_diseased_gray_wolf_corpse_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_diseased_rat_corpse'); # :oceangreenhills_a_diseased_rat_corpse_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_diseased_snake_corpse'); # :oceangreenhills_a_diseased_snake_corpse_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_festering_corpse'); # :oceangreenhills_a_festering_corpse_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_fire_beetle'); # :oceangreenhills_a_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_giant_snake'); # :oceangreenhills_a_giant_snake_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_gray_wolf'); # :oceangreenhills_a_gray_wolf_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_grizzly'); # :oceangreenhills_a_grizzly_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_grizzly_cub'); # :oceangreenhills_a_grizzly_cub_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_king_snake'); # :oceangreenhills_a_king_snake_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_large_rat'); # :oceangreenhills_a_large_rat_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_mason'); # :oceangreenhills_a_mason_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_pustulant_cadaver'); # :oceangreenhills_a_pustulant_cadaver_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_putrescent_corpse'); # :oceangreenhills_a_putrescent_corpse_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_putrid_skeleton'); # :oceangreenhills_a_putrid_skeleton_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_restless_shade'); # :oceangreenhills_a_restless_shade_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_rotting_corpse'); # :oceangreenhills_a_rotting_corpse_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_skeleton'); # :oceangreenhills_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_tottering_treant'); # :oceangreenhills_a_tottering_treant_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_twitching_cadaver'); # :oceangreenhills_a_twitching_cadaver_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_vengeful_harbinger'); # :oceangreenhills_a_vengeful_harbinger_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_whiskered_bat'); # :oceangreenhills_a_whiskered_bat_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_wispglow'); # :oceangreenhills_a_wispglow_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_worker'); # :oceangreenhills_a_worker_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_zombie_bombardier'); # :oceangreenhills_a_zombie_bombardier_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_a_zombie_catapult'); # :oceangreenhills_a_zombie_catapult_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_catapult_target'); # :oceangreenhills_catapult_target_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_garvin_windrunner'); # :oceangreenhills_garvin_windrunner_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_gladeshine'); # :oceangreenhills_gladeshine_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_anjon'); # :oceangreenhills_guard_anjon_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_ashon'); # :oceangreenhills_guard_ashon_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_brecht'); # :oceangreenhills_guard_brecht_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_drial'); # :oceangreenhills_guard_drial_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_emos'); # :oceangreenhills_guard_emos_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_fobler'); # :oceangreenhills_guard_fobler_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_liorn'); # :oceangreenhills_guard_liorn_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_morna'); # :oceangreenhills_guard_morna_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_ochey'); # :oceangreenhills_guard_ochey_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_radha'); # :oceangreenhills_guard_radha_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_teygh'); # :oceangreenhills_guard_teygh_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_uonty'); # :oceangreenhills_guard_uonty_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_guard_wuith'); # :oceangreenhills_guard_wuith_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_jelurc_canteoul'); # :oceangreenhills_jelurc_canteoul_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_jeneca_orlofen'); # :oceangreenhills_jeneca_orlofen_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_karco_yucille'); # :oceangreenhills_karco_yucille_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_kerrin_the_unkempt'); # :oceangreenhills_kerrin_the_unkempt_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_leria_blandrie'); # :oceangreenhills_leria_blandrie_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_lord_antonius_bayle'); # :oceangreenhills_lord_antonius_bayle_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_magus_wentior'); # :oceangreenhills_magus_wentior_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_migglethorpe_the_putremancer'); # :oceangreenhills_migglethorpe_the_putremancer_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_muvinn_vandolan'); # :oceangreenhills_muvinn_vandolan_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_nanari_keuzel'); # :oceangreenhills_nanari_keuzel_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_pestilent_aura'); # :oceangreenhills_pestilent_aura_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_senior_guard_jenkins'); # :oceangreenhills_senior_guard_jenkins_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_senior_guard_thompkins'); # :oceangreenhills_senior_guard_thompkins_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_seradi_stormcaller'); # :oceangreenhills_seradi_stormcaller_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_sergeant_bronal_cadran'); # :oceangreenhills_sergeant_bronal_cadran_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_skymane'); # :oceangreenhills_skymane_lt:
INSERT INTO loottable(name) VALUES('oceangreenhills_tabron_caulria'); # :oceangreenhills_tabron_caulria_lt:
