
(:oceangreenhills_a_grizzly_lt:, :bear_meat_ld:, 20),
(:oceangreenhills_a_grizzly_lt:, :bear_parts_ld:, 10),
(:oceangreenhills_a_grizzly_lt:, :bear_skin_ld:, 25),

(:oceangreenhills_a_grizzly_cub_lt:, :bear_meat_ld:, 20),
(:oceangreenhills_a_grizzly_cub_lt:, :bear_parts_ld:, 10),
(:oceangreenhills_a_grizzly_cub_lt:, :bear_skin_ld:, 25),

(:oceangreenhills_a_brown_bear_lt:, :bear_meat_ld:, 20),
(:oceangreenhills_a_brown_bear_lt:, :bear_parts_ld:, 10),
(:oceangreenhills_a_brown_bear_lt:, :bear_skin_ld:, 25),

(:oceangreenhills_an_infected_brown_bear_lt:, :bear_meat_ld:, 20),
(:oceangreenhills_an_infected_brown_bear_lt:, :bear_parts_ld:, 10),
(:oceangreenhills_an_infected_brown_bear_lt:, :bear_skin_ld:, 25),

(:oceangreenhills_a_vengeful_harbinger_lt:, :rusty_ld:, 1),
(:oceangreenhills_a_darkpaw_warrior_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_a_blackburrow_lurker_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_gladeshine_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_jessica_marsdaughter_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_a_darkpaw_mystic_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_a_pustulant_cadaver_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_a_blackbriar_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_kerrin_the_unkempt_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_guard_uonty_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_a_blackburrow_reaver_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_a_darkpaw_patroller_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_a_zombie_bombardier_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_evon_sewurd_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_skymane_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_guard_drial_lt:, :fine_steel_ld:, 1),
(:oceangreenhills_a_king_snake_lt:, :snake_meat_ld:, 1),
(:oceangreenhills_an_infected_king_snake_lt:, :snake_meat_ld:, 1),
(:oceangreenhills_a_giant_snake_lt:, :snake_meat_ld:, 1),
(:oceangreenhills_an_infected_large_rat_lt:, :rat_meat_ld:, 1),
(:oceangreenhills_a_large_rat_lt:, :rat_meat_ld:, 1),
(:oceangreenhills_an_infected_king_snake_lt:, :snake_fang_ld:, 1),
(:oceangreenhills_a_giant_snake_lt:, :snake_fang_ld:, 1),
(:oceangreenhills_a_king_snake_lt:, :snake_fang_ld:, 1),
(:oceangreenhills_a_king_snake_lt:, :snake_scales_ld:, 1),
(:oceangreenhills_an_infected_king_snake_lt:, :snake_scales_ld:, 1),
(:oceangreenhills_a_giant_snake_lt:, :snake_scales_ld:, 1),
(:oceangreenhills_a_putrid_skeleton_lt:, :skeleton_parts_ld:, 1),
