INSERT INTO loottable(name) VALUES('oldblackburrow_guard_ellery'); # :oldblackburrow_guard_ellery_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll'); # :oldblackburrow_an_enraged_gnoll_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_berserker'); # :oldblackburrow_an_enraged_gnoll_berserker_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_brewmaster'); # :oldblackburrow_an_enraged_gnoll_brewmaster_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_butcher'); # :oldblackburrow_an_enraged_gnoll_butcher_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_commander'); # :oldblackburrow_an_enraged_gnoll_commander_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_high_commander'); # :oldblackburrow_an_enraged_gnoll_high_commander_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_high_shaman'); # :oldblackburrow_an_enraged_gnoll_high_shaman_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_mystic'); # :oldblackburrow_an_enraged_gnoll_mystic_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_reaver'); # :oldblackburrow_an_enraged_gnoll_reaver_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_slavemaster'); # :oldblackburrow_an_enraged_gnoll_slavemaster_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_slaver'); # :oldblackburrow_an_enraged_gnoll_slaver_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_gnoll_thief'); # :oldblackburrow_an_enraged_gnoll_thief_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_scrawny_gnoll'); # :oldblackburrow_an_enraged_scrawny_gnoll_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_an_enraged_snake_handler'); # :oldblackburrow_an_enraged_snake_handler_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_bayle_guard_controller'); # :oldblackburrow_a_bayle_guard_controller_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_blackburrow_carp'); # :oldblackburrow_a_blackburrow_carp_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_blackburrow_rockfish'); # :oldblackburrow_a_blackburrow_rockfish_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_burly_gnoll'); # :oldblackburrow_a_burly_gnoll_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_burly_guard'); # :oldblackburrow_a_burly_guard_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_direfang_constrictor'); # :oldblackburrow_a_direfang_constrictor_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_direfang_serpent'); # :oldblackburrow_a_direfang_serpent_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_direfang_viper'); # :oldblackburrow_a_direfang_viper_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_gnoll_ravager'); # :oldblackburrow_a_gnoll_ravager_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_gnoll_shaman'); # :oldblackburrow_a_gnoll_shaman_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_large_direfang_serpent'); # :oldblackburrow_a_large_direfang_serpent_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_wrext_mal_bloodreaper'); # :oldblackburrow_a_wrext_mal_bloodreaper_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_wrext_mal_painbringer'); # :oldblackburrow_a_wrext_mal_painbringer_lt:
INSERT INTO loottable(name) VALUES('oldblackburrow_a_wrext_mal_shaman'); # :oldblackburrow_a_wrext_mal_shaman_lt:
