UPDATE npc_types SET loottable_id = :oldbloodfield_acolyte_maarnek_lt: WHERE id in (472005); # #Acolyte_Maarnek 87
UPDATE npc_types SET loottable_id = :oldbloodfield_alsor_the_reticent_lt: WHERE id in (472021); # #Alsor_the_Reticent 86
UPDATE npc_types SET loottable_id = :oldbloodfield_arikene_the_hopeful_lt: WHERE id in (472044); # #Arikene_the_Hopeful 86
UPDATE npc_types SET loottable_id = :oldbloodfield_assistant_josoth_lt: WHERE id in (472000); # #Assistant_Josoth 85
UPDATE npc_types SET loottable_id = :oldbloodfield_commander_fethul_lt: WHERE id in (472004); # #Commander_Fethul 86
UPDATE npc_types SET loottable_id = :oldbloodfield_commander_prezul_lt: WHERE id in (472051); # #Commander_Prezul 87
UPDATE npc_types SET loottable_id = :oldbloodfield_defender_guland_lt: WHERE id in (472059); # #Defender_Guland 87
UPDATE npc_types SET loottable_id = :oldbloodfield_general_vurig_the_imposing_lt: WHERE id in (472055); # #General_Vurig_the_Imposing 86
UPDATE npc_types SET loottable_id = :oldbloodfield_herald_argoth_lt: WHERE id in (472002); # #Herald_Argoth 85
UPDATE npc_types SET loottable_id = :oldbloodfield_high_noble_backim_lt: WHERE id in (472045); # #High_Noble_Backim 87
UPDATE npc_types SET loottable_id = :oldbloodfield_karsor_the_mad_lt: WHERE id in (472018); # #Karsor_the_Mad 86
UPDATE npc_types SET loottable_id = :oldbloodfield_koarus_the_vigilant_lt: WHERE id in (472040); # #Koarus_the_Vigilant 86
UPDATE npc_types SET loottable_id = :oldbloodfield_laahrin_the_swift_lt: WHERE id in (472001); # #Laahrin_the_Swift 86
UPDATE npc_types SET loottable_id = :oldbloodfield_nahsulen_the_tactician_lt: WHERE id in (472022); # #Nahsulen_the_Tactician 86
UPDATE npc_types SET loottable_id = :oldbloodfield_noble_arisan_lt: WHERE id in (472047); # #Noble_Arisan 87
UPDATE npc_types SET loottable_id = :oldbloodfield_noble_heldru_lt: WHERE id in (472053); # #Noble_Heldru 87
UPDATE npc_types SET loottable_id = :oldbloodfield_noble_mikuv_the_rational_lt: WHERE id in (472056); # #Noble_Mikuv_the_Rational 85
UPDATE npc_types SET loottable_id = :oldbloodfield_noble_ramel_the_strategist_lt: WHERE id in (472057); # #Noble_Ramel_the_Strategist 85
UPDATE npc_types SET loottable_id = :oldbloodfield_noble_yemall_the_arcane_lt: WHERE id in (472039); # #Noble_Yemall_the_Arcane 85
UPDATE npc_types SET loottable_id = :oldbloodfield_noble_zamin_lt: WHERE id in (472046); # #Noble_Zamin 87
UPDATE npc_types SET loottable_id = :oldbloodfield_rarof_the_negotiator_lt: WHERE id in (472020); # #Rarof_the_Negotiator 86
UPDATE npc_types SET loottable_id = :oldbloodfield_selidos_the_patient_lt: WHERE id in (472042); # #Selidos_the_Patient 86
UPDATE npc_types SET loottable_id = :oldbloodfield_tahrak_the_unstable_lt: WHERE id in (472019); # #Tahrak_the_Unstable 86
UPDATE npc_types SET loottable_id = :oldbloodfield_tekrik_the_determined_lt: WHERE id in (472003); # #Tekrik_the_Determined 86
UPDATE npc_types SET loottable_id = :oldbloodfield_xirisst_lt: WHERE id in (472024); # #Xirisst 87
UPDATE npc_types SET loottable_id = :oldbloodfield_an_ikaav_castigator_lt: WHERE id in (472043); # an_ikaav_castigator 86
UPDATE npc_types SET loottable_id = :oldbloodfield_an_ikaav_deathbeckoner_lt: WHERE id in (472028, 472031); # an_ikaav_deathbeckoner 85
UPDATE npc_types SET loottable_id = :oldbloodfield_an_ikaav_despiser_lt: WHERE id in (472017, 472025, 472033); # an_ikaav_despiser 86
UPDATE npc_types SET loottable_id = :oldbloodfield_an_ukun_fleshhound_lt: WHERE id in (472009, 472027, 472029); # an_ukun_fleshhound 86
UPDATE npc_types SET loottable_id = :oldbloodfield_an_ukun_guard_lt: WHERE id in (472058); # an_ukun_guard 86
UPDATE npc_types SET loottable_id = :oldbloodfield_a_captured_dragorn_lt: WHERE id in (472060); # a_captured_Dragorn 70
UPDATE npc_types SET loottable_id = :oldbloodfield_a_cask_of_battle_elixir_lt: WHERE id in (472038); # a_cask_of_Battle_Elixir 65
UPDATE npc_types SET loottable_id = :oldbloodfield_a_dragorn_adjunct_lt: WHERE id in (472006); # a_dragorn_adjunct 85
UPDATE npc_types SET loottable_id = :oldbloodfield_a_dragorn_citizen_lt: WHERE id in (472052); # a_Dragorn_citizen 85
UPDATE npc_types SET loottable_id = :oldbloodfield_a_dragorn_councilman_lt: WHERE id in (472048); # a_dragorn_councilman 85
UPDATE npc_types SET loottable_id = :oldbloodfield_a_dragorn_courier_lt: WHERE id in (472041); # a_dragorn_courier 86
UPDATE npc_types SET loottable_id = :oldbloodfield_a_dragorn_diplomat_lt: WHERE id in (472050); # a_Dragorn_diplomat 85
UPDATE npc_types SET loottable_id = :oldbloodfield_a_dragorn_high_guard_lt: WHERE id in (472049); # a_Dragorn_high_guard 85
UPDATE npc_types SET loottable_id = :oldbloodfield_a_dragorn_knight_lt: WHERE id in (472008); # a_dragorn_knight 85
UPDATE npc_types SET loottable_id = :oldbloodfield_a_dragorn_muramite_lt: WHERE id in (472030, 472032, 472037); # a_Dragorn_muramite 86
UPDATE npc_types SET loottable_id = :oldbloodfield_a_dragorn_warrior_lt: WHERE id in (472007); # a_dragorn_warrior 85
UPDATE npc_types SET loottable_id = :oldbloodfield_a_kyv_lt: WHERE id in (472010, 472012); # a_kyv 86
UPDATE npc_types SET loottable_id = :oldbloodfield_a_kyv_heartpiercer_lt: WHERE id in (472014, 472016); # a_kyv_heartpiercer 86
UPDATE npc_types SET loottable_id = :oldbloodfield_a_kyv_limbcutter_lt: WHERE id in (472035); # a_kyv_limbcutter 86
UPDATE npc_types SET loottable_id = :oldbloodfield_a_muramite_weapon_rack_lt: WHERE id in (472034); # a_Muramite_weapon_rack 65
UPDATE npc_types SET loottable_id = :oldbloodfield_a_noc_darklurch_lt: WHERE id in (472011, 472023); # a_noc_darklurch 85
UPDATE npc_types SET loottable_id = :oldbloodfield_a_noc_flashblade_lt: WHERE id in (472013, 472026); # a_noc_flashblade 86
UPDATE npc_types SET loottable_id = :oldbloodfield_a_noc_fleshletter_lt: WHERE id in (472015); # a_noc_fleshletter 85
UPDATE npc_types SET loottable_id = :oldbloodfield_fsp-general-noeffect_lt: WHERE id in (472036); # FSP-General-NoEffect 1
UPDATE npc_types SET loottable_id = :oldbloodfield_obf_aura_lt: WHERE id in (472054); # OBF_Aura 50
