UPDATE npc_types SET loottable_id = :olddranik_acolyte_grindrik_lt: WHERE id in (474013); # #Acolyte_Grindrik 87
UPDATE npc_types SET loottable_id = :olddranik_acolyte_torsk_lt: WHERE id in (474053); # #Acolyte_Torsk 87
UPDATE npc_types SET loottable_id = :olddranik_barowsar_lt: WHERE id in (474083); # #Barowsar 87
UPDATE npc_types SET loottable_id = :olddranik_battlemaster_denik_lt: WHERE id in (474082); # #Battlemaster_Denik 87
UPDATE npc_types SET loottable_id = :olddranik_bolno_the_peon_lt: WHERE id in (474052); # #Bolno_the_Peon 87
UPDATE npc_types SET loottable_id = :olddranik_bolodakan_lt: WHERE id in (474096); # #Bolodakan 87
UPDATE npc_types SET loottable_id = :olddranik_caller_donivin_lt: WHERE id in (474020); # #Caller_Donivin 87
UPDATE npc_types SET loottable_id = :olddranik_captain_gherish_lt: WHERE id in (474064); # #Captain_Gherish 87
UPDATE npc_types SET loottable_id = :olddranik_citykeeper_nardic_the_proud_lt: WHERE id in (474012); # #Citykeeper_Nardic_the_Proud 87
UPDATE npc_types SET loottable_id = :olddranik_clergyman_rexith_lt: WHERE id in (474069); # #Clergyman_Rexith 87
UPDATE npc_types SET loottable_id = :olddranik_daignal_the_revered_lt: WHERE id in (474101); # #Daignal_the_Revered 87
UPDATE npc_types SET loottable_id = :olddranik_diad_lt: WHERE id in (474072); # #Diad 87
UPDATE npc_types SET loottable_id = :olddranik_drarakon_lt: WHERE id in (474091); # #Drarakon 87
UPDATE npc_types SET loottable_id = :olddranik_droongar_lt: WHERE id in (474057); # #Droongar 87
UPDATE npc_types SET loottable_id = :olddranik_drunt_lt: WHERE id in (474048); # #Drunt 87
UPDATE npc_types SET loottable_id = :olddranik_durhosk_lt: WHERE id in (474018); # #Durhosk 87
UPDATE npc_types SET loottable_id = :olddranik_ertalon_lt: WHERE id in (474066); # #Ertalon 87
UPDATE npc_types SET loottable_id = :olddranik_general_azerug_the_honorable_lt: WHERE id in (474016); # #General_Azerug_the_Honorable 88
UPDATE npc_types SET loottable_id = :olddranik_girztal_the_attendant_lt: WHERE id in (474106); # #Girztal_the_Attendant 87
UPDATE npc_types SET loottable_id = :olddranik_givrund_the_devoted_lt: WHERE id in (474011); # #Givrund_the_Devoted 87
UPDATE npc_types SET loottable_id = :olddranik_gorvoroth_lt: WHERE id in (474087); # #Gorvoroth 87
UPDATE npc_types SET loottable_id = :olddranik_grand_historian_gersh_lt: WHERE id in (474099); # #Grand_Historian_Gersh 87
UPDATE npc_types SET loottable_id = :olddranik_grand_historian_rygua_lt: WHERE id in (474100); # #Grand_Historian_Rygua 87
UPDATE npc_types SET loottable_id = :olddranik_grathnok_gilforgan_lt: WHERE id in (474021); # #Grathnok_Gilforgan 87
UPDATE npc_types SET loottable_id = :olddranik_grinbar_lt: WHERE id in (474008); # #Grinbar 87
UPDATE npc_types SET loottable_id = :olddranik_grithyank_avlonnon_lt: WHERE id in (474005); # #Grithyank_Avlonnon 87
UPDATE npc_types SET loottable_id = :olddranik_guardian_etrias_lt: WHERE id in (474070); # #Guardian_Etrias 87
UPDATE npc_types SET loottable_id = :olddranik_guardian_naven_lt: WHERE id in (474071); # #Guardian_Naven 87
UPDATE npc_types SET loottable_id = :olddranik_guardsman_quilm_lt: WHERE id in (474067); # #Guardsman_Quilm 87
UPDATE npc_types SET loottable_id = :olddranik_high_priest_wersin_lt: WHERE id in (474093); # #High_Priest_Wersin 87
UPDATE npc_types SET loottable_id = :olddranik_hudar_trittan_lt: WHERE id in (474062); # #Hudar_Trittan 87
UPDATE npc_types SET loottable_id = :olddranik_inventor_krang_lt: WHERE id in (474034); # #Inventor_Krang 87
UPDATE npc_types SET loottable_id = :olddranik_jarekiv_lt: WHERE id in (474063); # #Jarekiv 87
UPDATE npc_types SET loottable_id = :olddranik_jayruk_the_hunter_lt: WHERE id in (474015); # #Jayruk_the_Hunter 87
UPDATE npc_types SET loottable_id = :olddranik_jekisia_lt: WHERE id in (474060); # #Jekisia 87
UPDATE npc_types SET loottable_id = :olddranik_jurrock_lt: WHERE id in (474049); # #Jurrock 87
UPDATE npc_types SET loottable_id = :olddranik_kirostall_lt: WHERE id in (474103); # #Kirostall 87
UPDATE npc_types SET loottable_id = :olddranik_korshawn_lt: WHERE id in (474074); # #Korshawn 87
UPDATE npc_types SET loottable_id = :olddranik_ladislev_the_architect_lt: WHERE id in (474097); # #Ladislev_the_Architect 87
UPDATE npc_types SET loottable_id = :olddranik_lannal_lt: WHERE id in (474061); # #Lannal 87
UPDATE npc_types SET loottable_id = :olddranik_lenarsk_lt: WHERE id in (474088); # #Lenarsk 87
UPDATE npc_types SET loottable_id = :olddranik_lieutenant_lihad_lt: WHERE id in (474047); # #Lieutenant_Lihad 87
UPDATE npc_types SET loottable_id = :olddranik_lirah_lt: WHERE id in (474075); # #Lirah 87
UPDATE npc_types SET loottable_id = :olddranik_loyal_servant_ziym_lt: WHERE id in (474105); # #Loyal_Servant_Ziym 87
UPDATE npc_types SET loottable_id = :olddranik_makyah_the_fierce_lt: WHERE id in (474050); # #Makyah_the_Fierce 87
UPDATE npc_types SET loottable_id = :olddranik_marshal_histent_lt: WHERE id in (474094); # #Marshal_Histent 87
UPDATE npc_types SET loottable_id = :olddranik_menlo_lt: WHERE id in (474065); # #Menlo 87
UPDATE npc_types SET loottable_id = :olddranik_mikuv_lt: WHERE id in (474078); # #Mikuv 87
UPDATE npc_types SET loottable_id = :olddranik_nalipat_lt: WHERE id in (474098); # #Nalipat 87
UPDATE npc_types SET loottable_id = :olddranik_nerask_lt: WHERE id in (474079); # #Nerask 87
UPDATE npc_types SET loottable_id = :olddranik_peon_salnar_lt: WHERE id in (474045); # #Peon_Salnar 87
UPDATE npc_types SET loottable_id = :olddranik_reinad_scalebreath_lt: WHERE id in (474107); # #Reinad_Scalebreath 87
UPDATE npc_types SET loottable_id = :olddranik_retind_oaln_lt: WHERE id in (474058); # #Retind_Oaln 87
UPDATE npc_types SET loottable_id = :olddranik_rowgar_lt: WHERE id in (474038); # #Rowgar 87
UPDATE npc_types SET loottable_id = :olddranik_sandak_lt: WHERE id in (474086); # #Sandak 87
UPDATE npc_types SET loottable_id = :olddranik_scion_balion_lt: WHERE id in (474051); # #Scion_Balion 87
UPDATE npc_types SET loottable_id = :olddranik_sentinel_siofet_lt: WHERE id in (474009); # #Sentinel_Siofet 87
UPDATE npc_types SET loottable_id = :olddranik_shzalk_lt: WHERE id in (474115); # #Shzalk 89
UPDATE npc_types SET loottable_id = :olddranik_sverins_fireskin_lt: WHERE id in (474090); # #Sverins_Fireskin 87
UPDATE npc_types SET loottable_id = :olddranik_tibor_lt: WHERE id in (474017); # #Tibor 87
UPDATE npc_types SET loottable_id = :olddranik_tiorpat_tornwing_lt: WHERE id in (474010); # #Tiorpat_Tornwing 87
UPDATE npc_types SET loottable_id = :olddranik_toiler_opanin_lt: WHERE id in (474068); # #Toiler_Opanin 87
UPDATE npc_types SET loottable_id = :olddranik_trainer_cyrum_lt: WHERE id in (474046); # #Trainer_Cyrum 87
UPDATE npc_types SET loottable_id = :olddranik_trainer_dysarth_lt: WHERE id in (474043); # #Trainer_Dysarth 87
UPDATE npc_types SET loottable_id = :olddranik_trelak_lt: WHERE id in (474084); # #Trelak 87
UPDATE npc_types SET loottable_id = :olddranik_tyian_rianda_lt: WHERE id in (474033); # #Tyian_Rianda 87
UPDATE npc_types SET loottable_id = :olddranik_ungorn_lt: WHERE id in (474102); # #Ungorn 87
UPDATE npc_types SET loottable_id = :olddranik_urjek_the_unsteady_lt: WHERE id in (474014); # #Urjek_the_Unsteady 87
UPDATE npc_types SET loottable_id = :olddranik_verow_lt: WHERE id in (474092); # #Verow 87
UPDATE npc_types SET loottable_id = :olddranik_veshlin_the_defamed_lt: WHERE id in (474004); # #Veshlin_the_Defamed 87
UPDATE npc_types SET loottable_id = :olddranik_vorkiev_lt: WHERE id in (474085); # #Vorkiev 87
UPDATE npc_types SET loottable_id = :olddranik_vorskahn_lt: WHERE id in (474007); # #Vorskahn 87
UPDATE npc_types SET loottable_id = :olddranik_vrago_lt: WHERE id in (474006); # #Vrago 87
UPDATE npc_types SET loottable_id = :olddranik_yarln_lt: WHERE id in (474059); # #Yarln 87
UPDATE npc_types SET loottable_id = :olddranik_yemall_the_arcane_lt: WHERE id in (474036); # #Yemall_the_Arcane 87
UPDATE npc_types SET loottable_id = :olddranik_yernom_lt: WHERE id in (474073); # #Yernom 87
UPDATE npc_types SET loottable_id = :olddranik_zakariv_lt: WHERE id in (474037); # #Zakariv 87
UPDATE npc_types SET loottable_id = :olddranik_ziven_lt: WHERE id in (474019); # #Ziven 87
UPDATE npc_types SET loottable_id = :olddranik_an_ikaav_castigator_lt: WHERE id in (474112, 474039, 474056); # an_ikaav_castigator 85
UPDATE npc_types SET loottable_id = :olddranik_an_ikaav_deathbeckoner_lt: WHERE id in (474119, 474121, 474026); # an_ikaav_deathbeckoner 85
UPDATE npc_types SET loottable_id = :olddranik_an_ikaav_despiser_lt: WHERE id in (474116, 474044, 474108); # an_ikaav_despiser 85
UPDATE npc_types SET loottable_id = :olddranik_an_ukun_fleshhound_lt: WHERE id in (474114, 474025, 474110); # an_ukun_fleshhound 85
UPDATE npc_types SET loottable_id = :olddranik_a_dragorn_guardian_lt: WHERE id in (474000, 474001, 474002, 474003, 474022, 474030, 474031, 474032, 474041, 474055, 474076, 474077, 474080, 474081, 474089, 474095, 474104); # a_Dragorn_guardian 85
UPDATE npc_types SET loottable_id = :olddranik_a_dragorn_lookout_lt: WHERE id in (474027, 474028); # a_Dragorn_lookout 84
UPDATE npc_types SET loottable_id = :olddranik_a_dragorn_thug_lt: WHERE id in (474023); # a_Dragorn_thug 87
UPDATE npc_types SET loottable_id = :olddranik_a_kyv_lt: WHERE id in (474029); # a_kyv 84
UPDATE npc_types SET loottable_id = :olddranik_a_kyv_heartpiercer_lt: WHERE id in (474117, 474040, 474054); # a_kyv_heartpiercer 86
UPDATE npc_types SET loottable_id = :olddranik_a_noc_darklurch_lt: WHERE id in (474118, 474024, 474109); # a_noc_darklurch 86
UPDATE npc_types SET loottable_id = :olddranik_a_noc_flashblade_lt: WHERE id in (474113, 474120, 474111); # a_noc_flashblade 85
UPDATE npc_types SET loottable_id = :olddranik_a_noc_fleshletter_lt: WHERE id in (474042); # a_noc_fleshletter 84
UPDATE npc_types SET loottable_id = :olddranik_a_test_subject_lt: WHERE id in (474035); # a_test_subject 85
