# INSERT INTO loottable_entries(probability, loottable_id, lootdrop_id, drop_limit, mindrop) VALUES (100, :todo_lt:, :todo_ld:, 1, 1);
(1, :oldfieldofbone_a_sebilisian_tracker_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_a_sebilisian_messenger_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_a_giant_tree_boa_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_a_sebilisian_ironfist_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_a_sebilisian_patrol_leader_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_an_escaped_sarnak_oracle_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_a_sebilisian_battlemaster_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_a_sarnak_conscript_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_an_escaped_sarnak_footman_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_a_sebilisian_scaleblade_lt:, :fine_steel_ld:),
(1, :oldfieldofbone_a_sebilisian_bonetrooper_lt:, :fine_steel_ld:),
