INSERT INTO loottable(name) VALUES('oldfieldofbone_assistant_josic'); # :oldfieldofbone_assistant_josic_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_commander_koth'); # :oldfieldofbone_commander_koth_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_emperor_ganak'); # :oldfieldofbone_emperor_ganak_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_gorenaire'); # :oldfieldofbone_gorenaire_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_imperial_advisor_resylar'); # :oldfieldofbone_imperial_advisor_resylar_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_imperial_advisor_sestak'); # :oldfieldofbone_imperial_advisor_sestak_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_imperial_guardian_hesalyt'); # :oldfieldofbone_imperial_guardian_hesalyt_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_imperial_guardian_mekta'); # :oldfieldofbone_imperial_guardian_mekta_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_jaleddar'); # :oldfieldofbone_jaleddar_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_phara_dar'); # :oldfieldofbone_phara_dar_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_severilous'); # :oldfieldofbone_severilous_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_shade_of_tharoff'); # :oldfieldofbone_shade_of_tharoff_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_slact_the_frozen_hand'); # :oldfieldofbone_slact_the_frozen_hand_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_talendor'); # :oldfieldofbone_talendor_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_trakanon'); # :oldfieldofbone_trakanon_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_tynoc,_herald_of_scale'); # :oldfieldofbone_tynoc,_herald_of_scale_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_emerald_champion'); # :oldfieldofbone_an_emerald_champion_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_emerald_dragon_corpse'); # :oldfieldofbone_an_emerald_dragon_corpse_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_emerald_skirmisher'); # :oldfieldofbone_an_emerald_skirmisher_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_escaped_sarnak_footman'); # :oldfieldofbone_an_escaped_sarnak_footman_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_escaped_sarnak_oracle'); # :oldfieldofbone_an_escaped_sarnak_oracle_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_icy_champion'); # :oldfieldofbone_an_icy_champion_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_icy_guardian'); # :oldfieldofbone_an_icy_guardian_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_icy_skirmisher'); # :oldfieldofbone_an_icy_skirmisher_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_iksar_alchemist'); # :oldfieldofbone_an_iksar_alchemist_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_iksar_master'); # :oldfieldofbone_an_iksar_master_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_obsidian_champion'); # :oldfieldofbone_an_obsidian_champion_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_an_obsidian_skirmisher'); # :oldfieldofbone_an_obsidian_skirmisher_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_burynai_explorer'); # :oldfieldofbone_a_burynai_explorer_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_chokidai_tracker'); # :oldfieldofbone_a_chokidai_tracker_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_fiery_guardian'); # :oldfieldofbone_a_fiery_guardian_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_fiery_skirmisher'); # :oldfieldofbone_a_fiery_skirmisher_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_giant_tree_boa'); # :oldfieldofbone_a_giant_tree_boa_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_grey_dragon_corpse'); # :oldfieldofbone_a_grey_dragon_corpse_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_large_blackbird'); # :oldfieldofbone_a_large_blackbird_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_racnar_ripper'); # :oldfieldofbone_a_racnar_ripper_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_racnar_tracker'); # :oldfieldofbone_a_racnar_tracker_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sarnak_conscript'); # :oldfieldofbone_a_sarnak_conscript_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_scaled_wolf'); # :oldfieldofbone_a_scaled_wolf_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_scaled_wolf_hunter'); # :oldfieldofbone_a_scaled_wolf_hunter_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_scaled_wolf_stalker'); # :oldfieldofbone_a_scaled_wolf_stalker_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_scorpion'); # :oldfieldofbone_a_scorpion_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_searing_champion'); # :oldfieldofbone_a_searing_champion_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_archer'); # :oldfieldofbone_a_sebilisian_archer_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_battlemaster'); # :oldfieldofbone_a_sebilisian_battlemaster_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_bloodclaw'); # :oldfieldofbone_a_sebilisian_bloodclaw_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_bonecaster'); # :oldfieldofbone_a_sebilisian_bonecaster_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_bonemaster'); # :oldfieldofbone_a_sebilisian_bonemaster_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_bonetrooper'); # :oldfieldofbone_a_sebilisian_bonetrooper_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_commander'); # :oldfieldofbone_a_sebilisian_commander_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_crusader'); # :oldfieldofbone_a_sebilisian_crusader_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_emissary'); # :oldfieldofbone_a_sebilisian_emissary_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_guardian'); # :oldfieldofbone_a_sebilisian_guardian_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_haruspex'); # :oldfieldofbone_a_sebilisian_haruspex_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_hierophant'); # :oldfieldofbone_a_sebilisian_hierophant_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_hunter'); # :oldfieldofbone_a_sebilisian_hunter_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_ironfist'); # :oldfieldofbone_a_sebilisian_ironfist_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_lich'); # :oldfieldofbone_a_sebilisian_lich_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_messenger'); # :oldfieldofbone_a_sebilisian_messenger_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_patrol_leader'); # :oldfieldofbone_a_sebilisian_patrol_leader_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_scaleblade'); # :oldfieldofbone_a_sebilisian_scaleblade_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_tracker'); # :oldfieldofbone_a_sebilisian_tracker_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sebilisian_trooper'); # :oldfieldofbone_a_sebilisian_trooper_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sokokar'); # :oldfieldofbone_a_sokokar_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sokokar_broodling'); # :oldfieldofbone_a_sokokar_broodling_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_a_sokokar_hatchling'); # :oldfieldofbone_a_sokokar_hatchling_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_billy'); # :oldfieldofbone_billy_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_chucko'); # :oldfieldofbone_chucko_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_fsp-general-noeffect'); # :oldfieldofbone_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_krizleks_corpse'); # :oldfieldofbone_krizleks_corpse_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_remains_of_master_marthor'); # :oldfieldofbone_remains_of_master_marthor_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone_thedude'); # :oldfieldofbone_thedude_lt:
INSERT INTO loottable(name) VALUES('oldfieldofbone__'); # :oldfieldofbone___lt:
