INSERT INTO loottable(name) VALUES('oldkaesoraa_an_imperial_scourge'); # :oldkaesoraa_an_imperial_scourge_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_an_imperial_sentry'); # :oldkaesoraa_an_imperial_sentry_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_corrupt_defiler'); # :oldkaesoraa_a_corrupt_defiler_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_corrupt_heretic'); # :oldkaesoraa_a_corrupt_heretic_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_corrupt_warlock'); # :oldkaesoraa_a_corrupt_warlock_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_cryptic_diviner'); # :oldkaesoraa_a_cryptic_diviner_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_cryptic_prophet'); # :oldkaesoraa_a_cryptic_prophet_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_cryptic_soothsayer'); # :oldkaesoraa_a_cryptic_soothsayer_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_dark_ritualist'); # :oldkaesoraa_a_dark_ritualist_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_hateful_reaver'); # :oldkaesoraa_a_hateful_reaver_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_hateful_revenant'); # :oldkaesoraa_a_hateful_revenant_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_librarian'); # :oldkaesoraa_a_librarian_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_stonefist_cenobite'); # :oldkaesoraa_a_stonefist_cenobite_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_stonefist_disciple'); # :oldkaesoraa_a_stonefist_disciple_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_stonefist_master'); # :oldkaesoraa_a_stonefist_master_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_stone_guardian'); # :oldkaesoraa_a_stone_guardian_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_stone_sentinel'); # :oldkaesoraa_a_stone_sentinel_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_vault_custodian'); # :oldkaesoraa_a_vault_custodian_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_vault_protector'); # :oldkaesoraa_a_vault_protector_lt:
INSERT INTO loottable(name) VALUES('oldkaesoraa_a_vault_sentry'); # :oldkaesoraa_a_vault_sentry_lt:
