INSERT INTO loottable(name) VALUES('precipiceofwar_an_ikaav_castigator'); # :precipiceofwar_an_ikaav_castigator_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_an_ikaav_deathbeckoner'); # :precipiceofwar_an_ikaav_deathbeckoner_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_an_ikaav_despiser'); # :precipiceofwar_an_ikaav_despiser_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_an_ukun_fleshhound'); # :precipiceofwar_an_ukun_fleshhound_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_gelidran_encryodant'); # :precipiceofwar_a_gelidran_encryodant_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_gelidran_frostblade'); # :precipiceofwar_a_gelidran_frostblade_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_gelidran_icecaster'); # :precipiceofwar_a_gelidran_icecaster_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_kyv_eviscerator'); # :precipiceofwar_a_kyv_eviscerator_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_kyv_heartpiercer'); # :precipiceofwar_a_kyv_heartpiercer_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_noc_bloodsentinel'); # :precipiceofwar_a_noc_bloodsentinel_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_noc_darklurch'); # :precipiceofwar_a_noc_darklurch_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_noc_flashblade'); # :precipiceofwar_a_noc_flashblade_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_pyrilen_flamestriker'); # :precipiceofwar_a_pyrilen_flamestriker_lt:
INSERT INTO loottable(name) VALUES('precipiceofwar_a_pyrilen_infernate'); # :precipiceofwar_a_pyrilen_infernate_lt:
