INSERT INTO loottable(name) VALUES('commonlands_derin_mausrel'); # :commonlands_derin_mausrel_lt:
INSERT INTO loottable(name) VALUES('commonlands_almon_juliao'); # :commonlands_almon_juliao_lt:
INSERT INTO loottable(name) VALUES('commonlands_altunic_jartin'); # :commonlands_altunic_jartin_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_bixie'); # :commonlands_a_bixie_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_black_bear'); # :commonlands_a_black_bear_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_black_wolf'); # :commonlands_a_black_wolf_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_broken_claw_bandit'); # :commonlands_a_broken_claw_bandit_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_darkweed_snake'); # :commonlands_a_darkweed_snake_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_dervish_cutthroat'); # :commonlands_a_dervish_cutthroat_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_ghoul'); # :commonlands_a_ghoul_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_giant_rattlesnake'); # :commonlands_a_giant_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_giant_spider'); # :commonlands_a_giant_spider_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_griffin'); # :commonlands_a_griffin_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_hill_giant'); # :commonlands_a_hill_giant_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_kodiak'); # :commonlands_a_kodiak_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_large_piranha'); # :commonlands_a_large_piranha_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_large_rattlesnake'); # :commonlands_a_large_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_lesser_mummy'); # :commonlands_a_lesser_mummy_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_nightfall_giant'); # :commonlands_a_nightfall_giant_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_plains_cat'); # :commonlands_a_plains_cat_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_puma'); # :commonlands_a_puma_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_rattlesnake'); # :commonlands_a_rattlesnake_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_sand_scarab_hatchling'); # :commonlands_a_sand_scarab_hatchling_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_shadowed_man'); # :commonlands_a_shadowed_man_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_shadow_wolf'); # :commonlands_a_shadow_wolf_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_shady_swashbuckler'); # :commonlands_a_shady_swashbuckler_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_skeleton'); # :commonlands_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_spiderling'); # :commonlands_a_spiderling_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_wandering_zombie'); # :commonlands_a_wandering_zombie_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_willowisp'); # :commonlands_a_willowisp_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_young_kodiak'); # :commonlands_a_young_kodiak_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_young_puma'); # :commonlands_a_young_puma_lt:
INSERT INTO loottable(name) VALUES('commonlands_a_zombie'); # :commonlands_a_zombie_lt:
INSERT INTO loottable(name) VALUES('commonlands_badlen_gellentine'); # :commonlands_badlen_gellentine_lt:
INSERT INTO loottable(name) VALUES('commonlands_badoo_zumlar'); # :commonlands_badoo_zumlar_lt:
INSERT INTO loottable(name) VALUES('commonlands_barstre_songweaver'); # :commonlands_barstre_songweaver_lt:
INSERT INTO loottable(name) VALUES('commonlands_bealya_tanilsuia'); # :commonlands_bealya_tanilsuia_lt:
INSERT INTO loottable(name) VALUES('commonlands_brizzenoth_scyth'); # :commonlands_brizzenoth_scyth_lt:
INSERT INTO loottable(name) VALUES('commonlands_bubar'); # :commonlands_bubar_lt:
INSERT INTO loottable(name) VALUES('commonlands_calemia_slith'); # :commonlands_calemia_slith_lt:
INSERT INTO loottable(name) VALUES('commonlands_cedric_bramblethorn'); # :commonlands_cedric_bramblethorn_lt:
INSERT INTO loottable(name) VALUES('commonlands_cei_sunjumper'); # :commonlands_cei_sunjumper_lt:
INSERT INTO loottable(name) VALUES('commonlands_celni_pawfoot'); # :commonlands_celni_pawfoot_lt:
INSERT INTO loottable(name) VALUES('commonlands_chaenz_abella'); # :commonlands_chaenz_abella_lt:
INSERT INTO loottable(name) VALUES('commonlands_dena_loommistress'); # :commonlands_dena_loommistress_lt:
INSERT INTO loottable(name) VALUES('commonlands_dooruden_fallstine'); # :commonlands_dooruden_fallstine_lt:
INSERT INTO loottable(name) VALUES('commonlands_druanna_vorana'); # :commonlands_druanna_vorana_lt:
INSERT INTO loottable(name) VALUES('commonlands_elin_lightblade'); # :commonlands_elin_lightblade_lt:
INSERT INTO loottable(name) VALUES('commonlands_entock_malso'); # :commonlands_entock_malso_lt:
INSERT INTO loottable(name) VALUES('commonlands_farrengen_mithfinder'); # :commonlands_farrengen_mithfinder_lt:
INSERT INTO loottable(name) VALUES('commonlands_fellentaya_sentrak'); # :commonlands_fellentaya_sentrak_lt:
INSERT INTO loottable(name) VALUES('commonlands_gamanan_drugo'); # :commonlands_gamanan_drugo_lt:
INSERT INTO loottable(name) VALUES('commonlands_gantran_leafwell'); # :commonlands_gantran_leafwell_lt:
INSERT INTO loottable(name) VALUES('commonlands_germe_threadspinner'); # :commonlands_germe_threadspinner_lt:
INSERT INTO loottable(name) VALUES('commonlands_getallan_drakay'); # :commonlands_getallan_drakay_lt:
INSERT INTO loottable(name) VALUES('commonlands_greemi_draygoon'); # :commonlands_greemi_draygoon_lt:
INSERT INTO loottable(name) VALUES('commonlands_grishna_vriensa'); # :commonlands_grishna_vriensa_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_colin'); # :commonlands_guard_colin_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_deisnak'); # :commonlands_guard_deisnak_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_eridals'); # :commonlands_guard_eridals_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_fefslan'); # :commonlands_guard_fefslan_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_gnoosals'); # :commonlands_guard_gnoosals_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_reskin'); # :commonlands_guard_reskin_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_teridsan'); # :commonlands_guard_teridsan_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_tolus'); # :commonlands_guard_tolus_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_valon'); # :commonlands_guard_valon_lt:
INSERT INTO loottable(name) VALUES('commonlands_guard_walorinags'); # :commonlands_guard_walorinags_lt:
INSERT INTO loottable(name) VALUES('commonlands_high_chief_diedridans'); # :commonlands_high_chief_diedridans_lt:
INSERT INTO loottable(name) VALUES('commonlands_high_chief_fosloas'); # :commonlands_high_chief_fosloas_lt:
INSERT INTO loottable(name) VALUES('commonlands_high_chief_kellerus'); # :commonlands_high_chief_kellerus_lt:
INSERT INTO loottable(name) VALUES('commonlands_initiate_firansad'); # :commonlands_initiate_firansad_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_blaise'); # :commonlands_innkeep_blaise_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_calen'); # :commonlands_innkeep_calen_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_dolman'); # :commonlands_innkeep_dolman_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_elora'); # :commonlands_innkeep_elora_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_fenia'); # :commonlands_innkeep_fenia_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_harold'); # :commonlands_innkeep_harold_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_juna'); # :commonlands_innkeep_juna_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_leo'); # :commonlands_innkeep_leo_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_olissa'); # :commonlands_innkeep_olissa_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_redthorn'); # :commonlands_innkeep_redthorn_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_roster'); # :commonlands_innkeep_roster_lt:
INSERT INTO loottable(name) VALUES('commonlands_innkeep_seke'); # :commonlands_innkeep_seke_lt:
INSERT INTO loottable(name) VALUES('commonlands_jahsohn_aksot'); # :commonlands_jahsohn_aksot_lt:
INSERT INTO loottable(name) VALUES('commonlands_jelda_needlefinger'); # :commonlands_jelda_needlefinger_lt:
INSERT INTO loottable(name) VALUES('commonlands_joryd_longarms'); # :commonlands_joryd_longarms_lt:
INSERT INTO loottable(name) VALUES('commonlands_katha_firespinner'); # :commonlands_katha_firespinner_lt:
INSERT INTO loottable(name) VALUES('commonlands_kathi_norman'); # :commonlands_kathi_norman_lt:
INSERT INTO loottable(name) VALUES('commonlands_kayci_strahtin'); # :commonlands_kayci_strahtin_lt:
INSERT INTO loottable(name) VALUES('commonlands_kehn_kohski'); # :commonlands_kehn_kohski_lt:
INSERT INTO loottable(name) VALUES('commonlands_khaite_ranna'); # :commonlands_khaite_ranna_lt:
INSERT INTO loottable(name) VALUES('commonlands_kizdean_gix'); # :commonlands_kizdean_gix_lt:
INSERT INTO loottable(name) VALUES('commonlands_lisill_sithmoor'); # :commonlands_lisill_sithmoor_lt:
INSERT INTO loottable(name) VALUES('commonlands_loric_weaver'); # :commonlands_loric_weaver_lt:
INSERT INTO loottable(name) VALUES('commonlands_luarnn_gibbizt'); # :commonlands_luarnn_gibbizt_lt:
INSERT INTO loottable(name) VALUES('commonlands_lyth_spellstar'); # :commonlands_lyth_spellstar_lt:
INSERT INTO loottable(name) VALUES('commonlands_magus_zeir'); # :commonlands_magus_zeir_lt:
INSERT INTO loottable(name) VALUES('commonlands_maula_fishcatcher'); # :commonlands_maula_fishcatcher_lt:
INSERT INTO loottable(name) VALUES('commonlands_merra_clayfinger'); # :commonlands_merra_clayfinger_lt:
INSERT INTO loottable(name) VALUES('commonlands_metha_wintersong'); # :commonlands_metha_wintersong_lt:
INSERT INTO loottable(name) VALUES('commonlands_modren_fishcatcher'); # :commonlands_modren_fishcatcher_lt:
INSERT INTO loottable(name) VALUES('commonlands_mojax_hikspin'); # :commonlands_mojax_hikspin_lt:
INSERT INTO loottable(name) VALUES('commonlands_nalla'); # :commonlands_nalla_lt:
INSERT INTO loottable(name) VALUES('commonlands_niatra_glimtaf'); # :commonlands_niatra_glimtaf_lt:
INSERT INTO loottable(name) VALUES('commonlands_noresa_sparkle'); # :commonlands_noresa_sparkle_lt:
INSERT INTO loottable(name) VALUES('commonlands_olin_helni'); # :commonlands_olin_helni_lt:
INSERT INTO loottable(name) VALUES('commonlands_opal_woodchopper'); # :commonlands_opal_woodchopper_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_apprentice'); # :commonlands_orc_apprentice_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_centurion'); # :commonlands_orc_centurion_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_legionnaire'); # :commonlands_orc_legionnaire_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_one_spawn'); # :commonlands_orc_one_spawn_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_oracle'); # :commonlands_orc_oracle_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_pawn'); # :commonlands_orc_pawn_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_three_spawn'); # :commonlands_orc_three_spawn_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_two_spawn'); # :commonlands_orc_two_spawn_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_ut_spawn'); # :commonlands_orc_ut_spawn_lt:
INSERT INTO loottable(name) VALUES('commonlands_orc_weaponsmith'); # :commonlands_orc_weaponsmith_lt:
INSERT INTO loottable(name) VALUES('commonlands_palik_agrolm'); # :commonlands_palik_agrolm_lt:
INSERT INTO loottable(name) VALUES('commonlands_pardor_the_blessed'); # :commonlands_pardor_the_blessed_lt:
INSERT INTO loottable(name) VALUES('commonlands_parthar'); # :commonlands_parthar_lt:
INSERT INTO loottable(name) VALUES('commonlands_parus_the_strong'); # :commonlands_parus_the_strong_lt:
INSERT INTO loottable(name) VALUES('commonlands_periac_windfell'); # :commonlands_periac_windfell_lt:
INSERT INTO loottable(name) VALUES('commonlands_peron_threadspinner'); # :commonlands_peron_threadspinner_lt:
INSERT INTO loottable(name) VALUES('commonlands_ponila_quickfingers'); # :commonlands_ponila_quickfingers_lt:
INSERT INTO loottable(name) VALUES('commonlands_ranon_strongarm'); # :commonlands_ranon_strongarm_lt:
INSERT INTO loottable(name) VALUES('commonlands_ranvigoz_tonsmith'); # :commonlands_ranvigoz_tonsmith_lt:
INSERT INTO loottable(name) VALUES('commonlands_rinna_lightshadow'); # :commonlands_rinna_lightshadow_lt:
INSERT INTO loottable(name) VALUES('commonlands_romya'); # :commonlands_romya_lt:
INSERT INTO loottable(name) VALUES('commonlands_ruby_boxcrafter'); # :commonlands_ruby_boxcrafter_lt:
INSERT INTO loottable(name) VALUES('commonlands_rushka_deklamoor'); # :commonlands_rushka_deklamoor_lt:
INSERT INTO loottable(name) VALUES('commonlands_selendia_geogo'); # :commonlands_selendia_geogo_lt:
INSERT INTO loottable(name) VALUES('commonlands_sergeant_ragus'); # :commonlands_sergeant_ragus_lt:
INSERT INTO loottable(name) VALUES('commonlands_sergeant_slate'); # :commonlands_sergeant_slate_lt:
INSERT INTO loottable(name) VALUES('commonlands_shadow_treebright'); # :commonlands_shadow_treebright_lt:
INSERT INTO loottable(name) VALUES('commonlands_simon_aldicott'); # :commonlands_simon_aldicott_lt:
INSERT INTO loottable(name) VALUES('commonlands_skipynn_stoneheart'); # :commonlands_skipynn_stoneheart_lt:
INSERT INTO loottable(name) VALUES('commonlands_skuprelauncheventtrigger'); # :commonlands_skuprelauncheventtrigger_lt:
INSERT INTO loottable(name) VALUES('commonlands_slea_pinewhisper'); # :commonlands_slea_pinewhisper_lt:
INSERT INTO loottable(name) VALUES('commonlands_sorsha_barrowfriend'); # :commonlands_sorsha_barrowfriend_lt:
INSERT INTO loottable(name) VALUES('commonlands_soulbinder_jubbl'); # :commonlands_soulbinder_jubbl_lt:
INSERT INTO loottable(name) VALUES('commonlands_staranna_eisley'); # :commonlands_staranna_eisley_lt:
INSERT INTO loottable(name) VALUES('commonlands_tallik_jaggedfire'); # :commonlands_tallik_jaggedfire_lt:
INSERT INTO loottable(name) VALUES('commonlands_timtok_tonsmith'); # :commonlands_timtok_tonsmith_lt:
INSERT INTO loottable(name) VALUES('commonlands_uyennli_vdrimw'); # :commonlands_uyennli_vdrimw_lt:
INSERT INTO loottable(name) VALUES('commonlands_uzmanya_zsiksta'); # :commonlands_uzmanya_zsiksta_lt:
INSERT INTO loottable(name) VALUES('commonlands_voris_flatblade'); # :commonlands_voris_flatblade_lt:
INSERT INTO loottable(name) VALUES('commonlands_vuli_greenwhisper'); # :commonlands_vuli_greenwhisper_lt:
INSERT INTO loottable(name) VALUES('commonlands_wallin_slyfoot'); # :commonlands_wallin_slyfoot_lt:
INSERT INTO loottable(name) VALUES('commonlands_wilno_lilin'); # :commonlands_wilno_lilin_lt:
INSERT INTO loottable(name) VALUES('commonlands_xernic_gutner'); # :commonlands_xernic_gutner_lt:
INSERT INTO loottable(name) VALUES('commonlands__'); # :commonlands___lt:
