INSERT INTO loottable(name) VALUES('direwind_anderak'); # :direwind_anderak_lt:
INSERT INTO loottable(name) VALUES('direwind_arakeen,_eater_of_the_dead'); # :direwind_arakeen,_eater_of_the_dead_lt:
INSERT INTO loottable(name) VALUES('direwind_archmage_varren'); # :direwind_archmage_varren_lt:
INSERT INTO loottable(name) VALUES('direwind_blademaster_zerralok'); # :direwind_blademaster_zerralok_lt:
INSERT INTO loottable(name) VALUES('direwind_bollbaru_the_witch'); # :direwind_bollbaru_the_witch_lt:
INSERT INTO loottable(name) VALUES('direwind_captain_orzhok'); # :direwind_captain_orzhok_lt:
INSERT INTO loottable(name) VALUES('direwind_carrionmancer_marrowrot'); # :direwind_carrionmancer_marrowrot_lt:
INSERT INTO loottable(name) VALUES('direwind_creeping_death'); # :direwind_creeping_death_lt:
INSERT INTO loottable(name) VALUES('direwind_darkenfin'); # :direwind_darkenfin_lt:
INSERT INTO loottable(name) VALUES('direwind_deathrattle'); # :direwind_deathrattle_lt:
INSERT INTO loottable(name) VALUES('direwind_deathshed'); # :direwind_deathshed_lt:
INSERT INTO loottable(name) VALUES('direwind_denlord_ezak'); # :direwind_denlord_ezak_lt:
INSERT INTO loottable(name) VALUES('direwind_gatekeeper_kor'); # :direwind_gatekeeper_kor_lt:
INSERT INTO loottable(name) VALUES('direwind_ghostfeather'); # :direwind_ghostfeather_lt:
INSERT INTO loottable(name) VALUES('direwind_hammerfist_the_champion'); # :direwind_hammerfist_the_champion_lt:
INSERT INTO loottable(name) VALUES('direwind_ironpaw,_kodas_mate'); # :direwind_ironpaw,_kodas_mate_lt:
INSERT INTO loottable(name) VALUES('direwind_kendra_the_archer'); # :direwind_kendra_the_archer_lt:
INSERT INTO loottable(name) VALUES('direwind_koda'); # :direwind_koda_lt:
INSERT INTO loottable(name) VALUES('direwind_moldmaster_gangii'); # :direwind_moldmaster_gangii_lt:
INSERT INTO loottable(name) VALUES('direwind_pyre_lord_narseekin'); # :direwind_pyre_lord_narseekin_lt:
INSERT INTO loottable(name) VALUES('direwind_renagarhn_the_exile'); # :direwind_renagarhn_the_exile_lt:
INSERT INTO loottable(name) VALUES('direwind_scout_keshik'); # :direwind_scout_keshik_lt:
INSERT INTO loottable(name) VALUES('direwind_scout_zryan'); # :direwind_scout_zryan_lt:
INSERT INTO loottable(name) VALUES('direwind_severan_the_direwind_caller'); # :direwind_severan_the_direwind_caller_lt:
INSERT INTO loottable(name) VALUES('direwind_shadowpaw'); # :direwind_shadowpaw_lt:
INSERT INTO loottable(name) VALUES('direwind_son_of_severan'); # :direwind_son_of_severan_lt:
INSERT INTO loottable(name) VALUES('direwind_the_blight_pyre'); # :direwind_the_blight_pyre_lt:
INSERT INTO loottable(name) VALUES('direwind_vahna,_dryad_of_direwind'); # :direwind_vahna,_dryad_of_direwind_lt:
INSERT INTO loottable(name) VALUES('direwind_vinelord_molder'); # :direwind_vinelord_molder_lt:
INSERT INTO loottable(name) VALUES('direwind_an_outpost_guardian'); # :direwind_an_outpost_guardian_lt:
INSERT INTO loottable(name) VALUES('direwind_axxanderans_animated_remains'); # :direwind_axxanderans_animated_remains_lt:
INSERT INTO loottable(name) VALUES('direwind_a_black_legion_archer'); # :direwind_a_black_legion_archer_lt:
INSERT INTO loottable(name) VALUES('direwind_a_black_legion_battlemage'); # :direwind_a_black_legion_battlemage_lt:
INSERT INTO loottable(name) VALUES('direwind_a_black_legion_berserker'); # :direwind_a_black_legion_berserker_lt:
INSERT INTO loottable(name) VALUES('direwind_a_black_legion_chaplain'); # :direwind_a_black_legion_chaplain_lt:
INSERT INTO loottable(name) VALUES('direwind_a_black_legion_mercenary'); # :direwind_a_black_legion_mercenary_lt:
INSERT INTO loottable(name) VALUES('direwind_a_black_legion_sergeant'); # :direwind_a_black_legion_sergeant_lt:
INSERT INTO loottable(name) VALUES('direwind_a_black_legion_warrior'); # :direwind_a_black_legion_warrior_lt:
INSERT INTO loottable(name) VALUES('direwind_a_bonestitch_golem'); # :direwind_a_bonestitch_golem_lt:
INSERT INTO loottable(name) VALUES('direwind_a_carrion_pile'); # :direwind_a_carrion_pile_lt:
INSERT INTO loottable(name) VALUES('direwind_a_clan_direwind_carrionmancer'); # :direwind_a_clan_direwind_carrionmancer_lt:
INSERT INTO loottable(name) VALUES('direwind_a_clan_direwind_dreadknight'); # :direwind_a_clan_direwind_dreadknight_lt:
INSERT INTO loottable(name) VALUES('direwind_a_clan_direwind_initiate'); # :direwind_a_clan_direwind_initiate_lt:
INSERT INTO loottable(name) VALUES('direwind_a_clan_direwind_plague_bearer'); # :direwind_a_clan_direwind_plague_bearer_lt:
INSERT INTO loottable(name) VALUES('direwind_a_clan_direwind_ratcaller'); # :direwind_a_clan_direwind_ratcaller_lt:
INSERT INTO loottable(name) VALUES('direwind_a_clan_direwind_ratkin'); # :direwind_a_clan_direwind_ratkin_lt:
INSERT INTO loottable(name) VALUES('direwind_a_clan_direwind_warlock'); # :direwind_a_clan_direwind_warlock_lt:
INSERT INTO loottable(name) VALUES('direwind_a_darkroot_carrion_gatherer'); # :direwind_a_darkroot_carrion_gatherer_lt:
INSERT INTO loottable(name) VALUES('direwind_a_darkroot_gardener'); # :direwind_a_darkroot_gardener_lt:
INSERT INTO loottable(name) VALUES('direwind_a_darkroot_moldling'); # :direwind_a_darkroot_moldling_lt:
INSERT INTO loottable(name) VALUES('direwind_a_darkroot_orchid'); # :direwind_a_darkroot_orchid_lt:
INSERT INTO loottable(name) VALUES('direwind_a_darkroot_shaman'); # :direwind_a_darkroot_shaman_lt:
INSERT INTO loottable(name) VALUES('direwind_a_darkroot_tender'); # :direwind_a_darkroot_tender_lt:
INSERT INTO loottable(name) VALUES('direwind_a_darkroot_vineherd'); # :direwind_a_darkroot_vineherd_lt:
INSERT INTO loottable(name) VALUES('direwind_a_darkroot_vinesnarl'); # :direwind_a_darkroot_vinesnarl_lt:
INSERT INTO loottable(name) VALUES('direwind_a_darkroot_warrior'); # :direwind_a_darkroot_warrior_lt:
INSERT INTO loottable(name) VALUES('direwind_a_diseased_griffon'); # :direwind_a_diseased_griffon_lt:
INSERT INTO loottable(name) VALUES('direwind_a_diseased_grizzly'); # :direwind_a_diseased_grizzly_lt:
INSERT INTO loottable(name) VALUES('direwind_a_diseased_wolf'); # :direwind_a_diseased_wolf_lt:
INSERT INTO loottable(name) VALUES('direwind_a_fleshstitch_golem'); # :direwind_a_fleshstitch_golem_lt:
INSERT INTO loottable(name) VALUES('direwind_a_gray_legion_cleric'); # :direwind_a_gray_legion_cleric_lt:
INSERT INTO loottable(name) VALUES('direwind_a_gray_legion_conscript'); # :direwind_a_gray_legion_conscript_lt:
INSERT INTO loottable(name) VALUES('direwind_a_gray_legion_mage'); # :direwind_a_gray_legion_mage_lt:
INSERT INTO loottable(name) VALUES('direwind_a_gray_legion_sergeant'); # :direwind_a_gray_legion_sergeant_lt:
INSERT INTO loottable(name) VALUES('direwind_a_gray_legion_soldier'); # :direwind_a_gray_legion_soldier_lt:
INSERT INTO loottable(name) VALUES('direwind_a_grizzly_matron'); # :direwind_a_grizzly_matron_lt:
INSERT INTO loottable(name) VALUES('direwind_a_manasheen_grove'); # :direwind_a_manasheen_grove_lt:
INSERT INTO loottable(name) VALUES('direwind_a_mindspore_grove'); # :direwind_a_mindspore_grove_lt:
INSERT INTO loottable(name) VALUES('direwind_a_mountain_griffon'); # :direwind_a_mountain_griffon_lt:
INSERT INTO loottable(name) VALUES('direwind_a_mountain_grizzly'); # :direwind_a_mountain_grizzly_lt:
INSERT INTO loottable(name) VALUES('direwind_a_nesting_griffon'); # :direwind_a_nesting_griffon_lt:
INSERT INTO loottable(name) VALUES('direwind_a_pack_hunter'); # :direwind_a_pack_hunter_lt:
INSERT INTO loottable(name) VALUES('direwind_a_pack_huntress'); # :direwind_a_pack_huntress_lt:
INSERT INTO loottable(name) VALUES('direwind_a_plagueborne_ooze'); # :direwind_a_plagueborne_ooze_lt:
INSERT INTO loottable(name) VALUES('direwind_a_plaguespore_grove'); # :direwind_a_plaguespore_grove_lt:
INSERT INTO loottable(name) VALUES('direwind_a_quickspore_grove'); # :direwind_a_quickspore_grove_lt:
INSERT INTO loottable(name) VALUES('direwind_a_rabid_wolf'); # :direwind_a_rabid_wolf_lt:
INSERT INTO loottable(name) VALUES('direwind_a_summoned_skeleton'); # :direwind_a_summoned_skeleton_lt:
INSERT INTO loottable(name) VALUES('direwind_a_supply_crate'); # :direwind_a_supply_crate_lt:
INSERT INTO loottable(name) VALUES('direwind_a_trained_griffon'); # :direwind_a_trained_griffon_lt:
INSERT INTO loottable(name) VALUES('direwind_blight_pyre_golem'); # :direwind_blight_pyre_golem_lt:
INSERT INTO loottable(name) VALUES('direwind_captain_orenu_urulump'); # :direwind_captain_orenu_urulump_lt:
INSERT INTO loottable(name) VALUES('direwind_direwind_current'); # :direwind_direwind_current_lt:
INSERT INTO loottable(name) VALUES('direwind_diseased_bear_corpse'); # :direwind_diseased_bear_corpse_lt:
INSERT INTO loottable(name) VALUES('direwind_diseased_griffon_corpse'); # :direwind_diseased_griffon_corpse_lt:
INSERT INTO loottable(name) VALUES('direwind_diseased_wolf_corpse'); # :direwind_diseased_wolf_corpse_lt:
INSERT INTO loottable(name) VALUES('direwind_guardian_of_the_gate'); # :direwind_guardian_of_the_gate_lt:
INSERT INTO loottable(name) VALUES('direwind_jenray,_envoy_of_ro'); # :direwind_jenray,_envoy_of_ro_lt:
INSERT INTO loottable(name) VALUES('direwind_kluno_orenbrew'); # :direwind_kluno_orenbrew_lt:
INSERT INTO loottable(name) VALUES('direwind_maven_bellstone'); # :direwind_maven_bellstone_lt:
INSERT INTO loottable(name) VALUES('direwind_outcast_erralock'); # :direwind_outcast_erralock_lt:
INSERT INTO loottable(name) VALUES('direwind_outcast_sayrus'); # :direwind_outcast_sayrus_lt:
INSERT INTO loottable(name) VALUES('direwind_roots_of_the_black_oak'); # :direwind_roots_of_the_black_oak_lt:
INSERT INTO loottable(name) VALUES('direwind_scribe_nurel_uralu'); # :direwind_scribe_nurel_uralu_lt:
INSERT INTO loottable(name) VALUES('direwind_the_blightwind_totem'); # :direwind_the_blightwind_totem_lt:
INSERT INTO loottable(name) VALUES('direwind_the_deathwind_totem'); # :direwind_the_deathwind_totem_lt:
INSERT INTO loottable(name) VALUES('direwind_the_hatewind_totem'); # :direwind_the_hatewind_totem_lt:
INSERT INTO loottable(name) VALUES('direwind_the_stormwind_totem'); # :direwind_the_stormwind_totem_lt:
INSERT INTO loottable(name) VALUES('direwind_tienen_the_wanderer'); # :direwind_tienen_the_wanderer_lt:
INSERT INTO loottable(name) VALUES('direwind_wintersting_the_black_oak'); # :direwind_wintersting_the_black_oak_lt:
INSERT INTO loottable(name) VALUES('direwind_zhubis_the_griffon_tamer'); # :direwind_zhubis_the_griffon_tamer_lt:
INSERT INTO loottable(name) VALUES('direwind__'); # :direwind___lt:
