INSERT INTO loottable(name) VALUES('frostcrypt_barvig_bloodaxe'); # :frostcrypt_barvig_bloodaxe_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_captain_hectov'); # :frostcrypt_captain_hectov_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_firbulg,_tactician_of_ice'); # :frostcrypt_firbulg,_tactician_of_ice_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_havik_the_faithful'); # :frostcrypt_havik_the_faithful_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_icecrack'); # :frostcrypt_icecrack_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_lorekeeper_thoren_goldentongue'); # :frostcrypt_lorekeeper_thoren_goldentongue_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_an_ice_golem'); # :frostcrypt_an_ice_golem_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_blighted_icecaller'); # :frostcrypt_a_blighted_icecaller_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_block_of_ice'); # :frostcrypt_a_block_of_ice_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_corrupted_remains'); # :frostcrypt_a_corrupted_remains_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_crumbling_ascetic'); # :frostcrypt_a_crumbling_ascetic_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_fallen_krithgor_warrior'); # :frostcrypt_a_fallen_krithgor_warrior_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_moldering_corpse'); # :frostcrypt_a_moldering_corpse_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_mummified_spiritist'); # :frostcrypt_a_mummified_spiritist_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_restrained_icemass'); # :frostcrypt_a_restrained_icemass_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_rotting_krithgor_soldier'); # :frostcrypt_a_rotting_krithgor_soldier_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_royal_advisor'); # :frostcrypt_a_royal_advisor_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_royal_guardian'); # :frostcrypt_a_royal_guardian_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_shade_of_zek'); # :frostcrypt_a_shade_of_zek_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_shadowblade_of_zek'); # :frostcrypt_a_shadowblade_of_zek_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_shadowcaller_of_zek'); # :frostcrypt_a_shadowcaller_of_zek_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_shadoweaver_of_zek'); # :frostcrypt_a_shadoweaver_of_zek_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_shadow_priest_of_zek'); # :frostcrypt_a_shadow_priest_of_zek_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_soldier_of_zek'); # :frostcrypt_a_soldier_of_zek_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_a_spirit_of_zek'); # :frostcrypt_a_spirit_of_zek_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_spirit_of_aethmir'); # :frostcrypt_spirit_of_aethmir_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_spirit_of_kalmaer'); # :frostcrypt_spirit_of_kalmaer_lt:
INSERT INTO loottable(name) VALUES('frostcrypt_spirit_of_thontik'); # :frostcrypt_spirit_of_thontik_lt:
