INSERT INTO loottable(name) VALUES('steppes_'); # :steppes__lt:
INSERT INTO loottable(name) VALUES('steppes_captain_gul'); # :steppes_captain_gul_lt:
INSERT INTO loottable(name) VALUES('steppes_cartographer_wylard'); # :steppes_cartographer_wylard_lt:
INSERT INTO loottable(name) VALUES('steppes_commander_drenkith_zontak'); # :steppes_commander_drenkith_zontak_lt:
INSERT INTO loottable(name) VALUES('steppes_cordagan_boulderfist'); # :steppes_cordagan_boulderfist_lt:
INSERT INTO loottable(name) VALUES('steppes_cragnaw'); # :steppes_cragnaw_lt:
INSERT INTO loottable(name) VALUES('steppes_erdna_the_sleeping_giant'); # :steppes_erdna_the_sleeping_giant_lt:
INSERT INTO loottable(name) VALUES('steppes_felena_bellstone'); # :steppes_felena_bellstone_lt:
INSERT INTO loottable(name) VALUES('steppes_hesmire_farflight'); # :steppes_hesmire_farflight_lt:
INSERT INTO loottable(name) VALUES('steppes_hunter_borty'); # :steppes_hunter_borty_lt:
INSERT INTO loottable(name) VALUES('steppes_moldren_the_wise'); # :steppes_moldren_the_wise_lt:
INSERT INTO loottable(name) VALUES('steppes_orumot_uluntar'); # :steppes_orumot_uluntar_lt:
INSERT INTO loottable(name) VALUES('steppes_portal_of_war'); # :steppes_portal_of_war_lt:
INSERT INTO loottable(name) VALUES('steppes_priest_ulkag'); # :steppes_priest_ulkag_lt:
INSERT INTO loottable(name) VALUES('steppes_stonemight_chieftain_swiftear'); # :steppes_stonemight_chieftain_swiftear_lt:
INSERT INTO loottable(name) VALUES('steppes_toegnasher'); # :steppes_toegnasher_lt:
INSERT INTO loottable(name) VALUES('steppes_wilped_the_withered'); # :steppes_wilped_the_withered_lt:
INSERT INTO loottable(name) VALUES('steppes_an_ancient_chest'); # :steppes_an_ancient_chest_lt:
INSERT INTO loottable(name) VALUES('steppes_an_earthen_elemental'); # :steppes_an_earthen_elemental_lt:
INSERT INTO loottable(name) VALUES('steppes_a_bear_cub'); # :steppes_a_bear_cub_lt:
INSERT INTO loottable(name) VALUES('steppes_a_brown_bear'); # :steppes_a_brown_bear_lt:
INSERT INTO loottable(name) VALUES('steppes_a_burly_hill_giant'); # :steppes_a_burly_hill_giant_lt:
INSERT INTO loottable(name) VALUES('steppes_a_crowned_mamba'); # :steppes_a_crowned_mamba_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_archer'); # :steppes_a_darkfell_archer_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_captain'); # :steppes_a_darkfell_captain_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_elder'); # :steppes_a_darkfell_elder_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_gnoll'); # :steppes_a_darkfell_gnoll_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_hunter'); # :steppes_a_darkfell_hunter_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_huntmaster'); # :steppes_a_darkfell_huntmaster_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_militant'); # :steppes_a_darkfell_militant_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_scavenger'); # :steppes_a_darkfell_scavenger_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_shaman'); # :steppes_a_darkfell_shaman_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_sharpshooter'); # :steppes_a_darkfell_sharpshooter_lt:
INSERT INTO loottable(name) VALUES('steppes_a_darkfell_warrior'); # :steppes_a_darkfell_warrior_lt:
INSERT INTO loottable(name) VALUES('steppes_a_dire_wolf'); # :steppes_a_dire_wolf_lt:
INSERT INTO loottable(name) VALUES('steppes_a_glade_rattler'); # :steppes_a_glade_rattler_lt:
INSERT INTO loottable(name) VALUES('steppes_a_grovewalker'); # :steppes_a_grovewalker_lt:
INSERT INTO loottable(name) VALUES('steppes_a_guardian_of_the_grove'); # :steppes_a_guardian_of_the_grove_lt:
INSERT INTO loottable(name) VALUES('steppes_a_hill_giant'); # :steppes_a_hill_giant_lt:
INSERT INTO loottable(name) VALUES('steppes_a_massive_elemental'); # :steppes_a_massive_elemental_lt:
INSERT INTO loottable(name) VALUES('steppes_a_mature_wasp_spider'); # :steppes_a_mature_wasp_spider_lt:
INSERT INTO loottable(name) VALUES('steppes_a_steppes_leopard'); # :steppes_a_steppes_leopard_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_elder'); # :steppes_a_stonemight_elder_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_goblin'); # :steppes_a_stonemight_goblin_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_hunter'); # :steppes_a_stonemight_hunter_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_marauder'); # :steppes_a_stonemight_marauder_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_raider'); # :steppes_a_stonemight_raider_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_shaman'); # :steppes_a_stonemight_shaman_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_stonebinder'); # :steppes_a_stonemight_stonebinder_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_tracker'); # :steppes_a_stonemight_tracker_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_veteran'); # :steppes_a_stonemight_veteran_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stonemight_warrior'); # :steppes_a_stonemight_warrior_lt:
INSERT INTO loottable(name) VALUES('steppes_a_stone_viper'); # :steppes_a_stone_viper_lt:
INSERT INTO loottable(name) VALUES('steppes_a_timber_lizard'); # :steppes_a_timber_lizard_lt:
INSERT INTO loottable(name) VALUES('steppes_a_wasp_spider'); # :steppes_a_wasp_spider_lt:
INSERT INTO loottable(name) VALUES('steppes_a_wolf'); # :steppes_a_wolf_lt:
INSERT INTO loottable(name) VALUES('steppes_a_worn_jug'); # :steppes_a_worn_jug_lt:
INSERT INTO loottable(name) VALUES('steppes_a_young_wasp_spider'); # :steppes_a_young_wasp_spider_lt:
INSERT INTO loottable(name) VALUES('steppes_bordan_the_cursed'); # :steppes_bordan_the_cursed_lt:
INSERT INTO loottable(name) VALUES('steppes_captain_vonsolu'); # :steppes_captain_vonsolu_lt:
INSERT INTO loottable(name) VALUES('steppes_elder_nezzen_trutak'); # :steppes_elder_nezzen_trutak_lt:
INSERT INTO loottable(name) VALUES('steppes_emelia_daeren'); # :steppes_emelia_daeren_lt:
INSERT INTO loottable(name) VALUES('steppes_friend_of_cordagan'); # :steppes_friend_of_cordagan_lt:
INSERT INTO loottable(name) VALUES('steppes_hemmet,_master_sureshot'); # :steppes_hemmet,_master_sureshot_lt:
INSERT INTO loottable(name) VALUES('steppes_igantug'); # :steppes_igantug_lt:
INSERT INTO loottable(name) VALUES('steppes_portal_of_war'); # :steppes_portal_of_war_lt:
INSERT INTO loottable(name) VALUES('steppes_rang_kelliam'); # :steppes_rang_kelliam_lt:
INSERT INTO loottable(name) VALUES('steppes_yavia'); # :steppes_yavia_lt:
INSERT INTO loottable(name) VALUES('steppes__'); # :steppes___lt:
