INSERT INTO loottable(name) VALUES('toxxulia_aglthin_dasmore'); # :toxxulia_aglthin_dasmore_lt:
INSERT INTO loottable(name) VALUES('toxxulia_phaeril_nightshire'); # :toxxulia_phaeril_nightshire_lt:
INSERT INTO loottable(name) VALUES('toxxulia_abandoned_heretic_pet'); # :toxxulia_abandoned_heretic_pet_lt:
INSERT INTO loottable(name) VALUES('toxxulia_allix'); # :toxxulia_allix_lt:
INSERT INTO loottable(name) VALUES('toxxulia_an_erudin_emissary'); # :toxxulia_an_erudin_emissary_lt:
INSERT INTO loottable(name) VALUES('toxxulia_an_infected_rat'); # :toxxulia_an_infected_rat_lt:
INSERT INTO loottable(name) VALUES('toxxulia_assistant_tos'); # :toxxulia_assistant_tos_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_banished_kerran'); # :toxxulia_a_banished_kerran_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_boat'); # :toxxulia_a_boat_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_briar_snake'); # :toxxulia_a_briar_snake_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_catfisher'); # :toxxulia_a_catfisher_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_decaying_skeleton'); # :toxxulia_a_decaying_skeleton_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_faded_banner'); # :toxxulia_a_faded_banner_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_fire_beetle'); # :toxxulia_a_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_fish'); # :toxxulia_a_fish_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_giant_briar_snake'); # :toxxulia_a_giant_briar_snake_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_giant_fire_beetle'); # :toxxulia_a_giant_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_giant_thistle_snake'); # :toxxulia_a_giant_thistle_snake_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_giant_widow'); # :toxxulia_a_giant_widow_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_gorilla_guard'); # :toxxulia_a_gorilla_guard_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_gorilla_protector'); # :toxxulia_a_gorilla_protector_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_ademzada'); # :toxxulia_a_kerran_ademzada_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_ademzada_shaman'); # :toxxulia_a_kerran_ademzada_shaman_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_ademzadaamir'); # :toxxulia_a_kerran_ademzadaamir_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_ahmad_shaman'); # :toxxulia_a_kerran_ahmad_shaman_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_amira_guardian'); # :toxxulia_a_kerran_amira_guardian_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_amira_priestess'); # :toxxulia_a_kerran_amira_priestess_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_awrat'); # :toxxulia_a_kerran_awrat_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_ghazi'); # :toxxulia_a_kerran_ghazi_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_ghazi_shaman'); # :toxxulia_a_kerran_ghazi_shaman_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_ghaziamir'); # :toxxulia_a_kerran_ghaziamir_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_ghulam'); # :toxxulia_a_kerran_ghulam_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_gorilla'); # :toxxulia_a_kerran_gorilla_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_ispusar'); # :toxxulia_a_kerran_ispusar_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_mamluk'); # :toxxulia_a_kerran_mamluk_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_mujahed'); # :toxxulia_a_kerran_mujahed_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_pasdar'); # :toxxulia_a_kerran_pasdar_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_pazdar'); # :toxxulia_a_kerran_pazdar_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_pazdar_shaman'); # :toxxulia_a_kerran_pazdar_shaman_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_pazhal'); # :toxxulia_a_kerran_pazhal_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_puma'); # :toxxulia_a_kerran_puma_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_sharr_apprentice'); # :toxxulia_a_kerran_sharr_apprentice_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerran_amir'); # :toxxulia_a_kerran_amir_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kerra_lion'); # :toxxulia_a_kerra_lion_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kobold_caster'); # :toxxulia_a_kobold_caster_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kobold_prisoner'); # :toxxulia_a_kobold_prisoner_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kobold_runt'); # :toxxulia_a_kobold_runt_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kobold_scout'); # :toxxulia_a_kobold_scout_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kobold_sentry'); # :toxxulia_a_kobold_sentry_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kobold_shaman'); # :toxxulia_a_kobold_shaman_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_kobold_watcher'); # :toxxulia_a_kobold_watcher_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_large_briar_snake'); # :toxxulia_a_large_briar_snake_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_large_fire_beetle'); # :toxxulia_a_large_fire_beetle_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_large_thistle_snake'); # :toxxulia_a_large_thistle_snake_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_large_widow'); # :toxxulia_a_large_widow_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_large_wood_spider'); # :toxxulia_a_large_wood_spider_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_moss_snake'); # :toxxulia_a_moss_snake_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_mystic_voice'); # :toxxulia_a_mystic_voice_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_patrolling_tiger'); # :toxxulia_a_patrolling_tiger_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_piranha'); # :toxxulia_a_piranha_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_pixie'); # :toxxulia_a_pixie_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_skeleton'); # :toxxulia_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_skunk'); # :toxxulia_a_skunk_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_spiderling'); # :toxxulia_a_spiderling_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_thistle_snake'); # :toxxulia_a_thistle_snake_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_venomous_spikefish'); # :toxxulia_a_venomous_spikefish_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_widow_hatchling'); # :toxxulia_a_widow_hatchling_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_wild_tiger'); # :toxxulia_a_wild_tiger_lt:
INSERT INTO loottable(name) VALUES('toxxulia_a_willowisp'); # :toxxulia_a_willowisp_lt:
INSERT INTO loottable(name) VALUES('toxxulia_cyria_lorewhisper'); # :toxxulia_cyria_lorewhisper_lt:
INSERT INTO loottable(name) VALUES('toxxulia_dovon_traical'); # :toxxulia_dovon_traical_lt:
INSERT INTO loottable(name) VALUES('toxxulia_dozing_ghulam'); # :toxxulia_dozing_ghulam_lt:
INSERT INTO loottable(name) VALUES('toxxulia_drunken_ghulam'); # :toxxulia_drunken_ghulam_lt:
INSERT INTO loottable(name) VALUES('toxxulia_elial_brook'); # :toxxulia_elial_brook_lt:
INSERT INTO loottable(name) VALUES('toxxulia_emil_parsini'); # :toxxulia_emil_parsini_lt:
INSERT INTO loottable(name) VALUES('toxxulia_erfer_longclaw'); # :toxxulia_erfer_longclaw_lt:
INSERT INTO loottable(name) VALUES('toxxulia_errrak_thickshank'); # :toxxulia_errrak_thickshank_lt:
INSERT INTO loottable(name) VALUES('toxxulia_falthrik_lothoro'); # :toxxulia_falthrik_lothoro_lt:
INSERT INTO loottable(name) VALUES('toxxulia_feren'); # :toxxulia_feren_lt:
INSERT INTO loottable(name) VALUES('toxxulia_feskr_drinkmaker'); # :toxxulia_feskr_drinkmaker_lt:
INSERT INTO loottable(name) VALUES('toxxulia_fittorin_bladespur'); # :toxxulia_fittorin_bladespur_lt:
INSERT INTO loottable(name) VALUES('toxxulia_friedalla_dawncrest'); # :toxxulia_friedalla_dawncrest_lt:
INSERT INTO loottable(name) VALUES('toxxulia_graalf_sharpclaw'); # :toxxulia_graalf_sharpclaw_lt:
INSERT INTO loottable(name) VALUES('toxxulia_iffrir_soulcaller'); # :toxxulia_iffrir_soulcaller_lt:
INSERT INTO loottable(name) VALUES('toxxulia_ilanics_skeleton'); # :toxxulia_ilanics_skeleton_lt:
INSERT INTO loottable(name) VALUES('toxxulia_ilisiv_gantrau'); # :toxxulia_ilisiv_gantrau_lt:
INSERT INTO loottable(name) VALUES('toxxulia_islan_hetston'); # :toxxulia_islan_hetston_lt:
INSERT INTO loottable(name) VALUES('toxxulia_jalen_goldsinger'); # :toxxulia_jalen_goldsinger_lt:
INSERT INTO loottable(name) VALUES('toxxulia_jo_jo'); # :toxxulia_jo_jo_lt:
INSERT INTO loottable(name) VALUES('toxxulia_kellkoan_rishta'); # :toxxulia_kellkoan_rishta_lt:
INSERT INTO loottable(name) VALUES('toxxulia_kerran_tiger_spahi'); # :toxxulia_kerran_tiger_spahi_lt:
INSERT INTO loottable(name) VALUES('toxxulia_kerran_tseq'); # :toxxulia_kerran_tseq_lt:
INSERT INTO loottable(name) VALUES('toxxulia_knarthenne_skurl'); # :toxxulia_knarthenne_skurl_lt:
INSERT INTO loottable(name) VALUES('toxxulia_lanivon_baxer'); # :toxxulia_lanivon_baxer_lt:
INSERT INTO loottable(name) VALUES('toxxulia_lord_gongo'); # :toxxulia_lord_gongo_lt:
INSERT INTO loottable(name) VALUES('toxxulia_marl_kastane'); # :toxxulia_marl_kastane_lt:
INSERT INTO loottable(name) VALUES('toxxulia_martyn_firechaser'); # :toxxulia_martyn_firechaser_lt:
INSERT INTO loottable(name) VALUES('toxxulia_maugarim'); # :toxxulia_maugarim_lt:
INSERT INTO loottable(name) VALUES('toxxulia_melixis'); # :toxxulia_melixis_lt:
INSERT INTO loottable(name) VALUES('toxxulia_nexus_scion'); # :toxxulia_nexus_scion_lt:
INSERT INTO loottable(name) VALUES('toxxulia_norrath_scion'); # :toxxulia_norrath_scion_lt:
INSERT INTO loottable(name) VALUES('toxxulia_poacher_dell'); # :toxxulia_poacher_dell_lt:
INSERT INTO loottable(name) VALUES('toxxulia_poacher_hill'); # :toxxulia_poacher_hill_lt:
INSERT INTO loottable(name) VALUES('toxxulia_quana_rainsparkle'); # :toxxulia_quana_rainsparkle_lt:
INSERT INTO loottable(name) VALUES('toxxulia_raarrk'); # :toxxulia_raarrk_lt:
INSERT INTO loottable(name) VALUES('toxxulia_reeking_skunk'); # :toxxulia_reeking_skunk_lt:
INSERT INTO loottable(name) VALUES('toxxulia_ricandrow_starbourne'); # :toxxulia_ricandrow_starbourne_lt:
INSERT INTO loottable(name) VALUES('toxxulia_roary_fishpouncer'); # :toxxulia_roary_fishpouncer_lt:
INSERT INTO loottable(name) VALUES('toxxulia_rungupp'); # :toxxulia_rungupp_lt:
INSERT INTO loottable(name) VALUES('toxxulia_sanidella_syllvic'); # :toxxulia_sanidella_syllvic_lt:
INSERT INTO loottable(name) VALUES('toxxulia_sentinel_creot'); # :toxxulia_sentinel_creot_lt:
INSERT INTO loottable(name) VALUES('toxxulia_sentinel_drom'); # :toxxulia_sentinel_drom_lt:
INSERT INTO loottable(name) VALUES('toxxulia_sentinel_flavius'); # :toxxulia_sentinel_flavius_lt:
INSERT INTO loottable(name) VALUES('toxxulia_shazda_asad'); # :toxxulia_shazda_asad_lt:
INSERT INTO loottable(name) VALUES('toxxulia_shintar_vinlail'); # :toxxulia_shintar_vinlail_lt:
INSERT INTO loottable(name) VALUES('toxxulia_spikefish'); # :toxxulia_spikefish_lt:
INSERT INTO loottable(name) VALUES('toxxulia_stylla_parsini'); # :toxxulia_stylla_parsini_lt:
INSERT INTO loottable(name) VALUES('toxxulia_telanku_trailrunner'); # :toxxulia_telanku_trailrunner_lt:
INSERT INTO loottable(name) VALUES('toxxulia_terago_omath'); # :toxxulia_terago_omath_lt:
INSERT INTO loottable(name) VALUES('toxxulia_thalith_mamluk'); # :toxxulia_thalith_mamluk_lt:
INSERT INTO loottable(name) VALUES('toxxulia_the_norrath_spires'); # :toxxulia_the_norrath_spires_lt:
INSERT INTO loottable(name) VALUES('toxxulia_tran_lilspin'); # :toxxulia_tran_lilspin_lt:
INSERT INTO loottable(name) VALUES('toxxulia_urkath_greyface'); # :toxxulia_urkath_greyface_lt:
INSERT INTO loottable(name) VALUES('toxxulia_verogone_wayfinder'); # :toxxulia_verogone_wayfinder_lt:
INSERT INTO loottable(name) VALUES('toxxulia_wharf_rat'); # :toxxulia_wharf_rat_lt:
INSERT INTO loottable(name) VALUES('toxxulia_win_karnam'); # :toxxulia_win_karnam_lt:
INSERT INTO loottable(name) VALUES('toxxulia_wislen_mamluk'); # :toxxulia_wislen_mamluk_lt:
INSERT INTO loottable(name) VALUES('toxxulia_xylania_rainsparkle'); # :toxxulia_xylania_rainsparkle_lt:
