INSERT INTO loottable(name) VALUES('valdeholm_animal_tender_bealon'); # :valdeholm_animal_tender_bealon_lt:
INSERT INTO loottable(name) VALUES('valdeholm_fergarin_bardon_i'); # :valdeholm_fergarin_bardon_i_lt:
INSERT INTO loottable(name) VALUES('valdeholm_gatewatch_urgwit'); # :valdeholm_gatewatch_urgwit_lt:
INSERT INTO loottable(name) VALUES('valdeholm_kellet,_royal_guard_captain'); # :valdeholm_kellet,_royal_guard_captain_lt:
INSERT INTO loottable(name) VALUES('valdeholm_master_smith_goil'); # :valdeholm_master_smith_goil_lt:
INSERT INTO loottable(name) VALUES('valdeholm_royal_cryptguard_zerakt'); # :valdeholm_royal_cryptguard_zerakt_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_hunter_grethmar'); # :valdeholm_wraithguard_hunter_grethmar_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_sergeant_thavin'); # :valdeholm_wraithguard_sergeant_thavin_lt:
INSERT INTO loottable(name) VALUES('valdeholm_an_apprentice_metalworker'); # :valdeholm_an_apprentice_metalworker_lt:
INSERT INTO loottable(name) VALUES('valdeholm_an_armorer'); # :valdeholm_an_armorer_lt:
INSERT INTO loottable(name) VALUES('valdeholm_an_axe_of_the_ancients'); # :valdeholm_an_axe_of_the_ancients_lt:
INSERT INTO loottable(name) VALUES('valdeholm_an_elite_guard'); # :valdeholm_an_elite_guard_lt:
INSERT INTO loottable(name) VALUES('valdeholm_an_icemason'); # :valdeholm_an_icemason_lt:
INSERT INTO loottable(name) VALUES('valdeholm_an_ice_tiger'); # :valdeholm_an_ice_tiger_lt:
INSERT INTO loottable(name) VALUES('valdeholm_an_ice_tiger_cub'); # :valdeholm_an_ice_tiger_cub_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_butcher'); # :valdeholm_a_butcher_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_citizen_of_valdeholm'); # :valdeholm_a_citizen_of_valdeholm_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_dire_wolf'); # :valdeholm_a_dire_wolf_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_dire_wolf_pup'); # :valdeholm_a_dire_wolf_pup_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_flateye_ooze'); # :valdeholm_a_flateye_ooze_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_guard_captain'); # :valdeholm_a_guard_captain_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_hunter'); # :valdeholm_a_hunter_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_krithgor_noble'); # :valdeholm_a_krithgor_noble_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_krithgor_patriarch'); # :valdeholm_a_krithgor_patriarch_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_lakeskater'); # :valdeholm_a_lakeskater_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_lorekeeper'); # :valdeholm_a_lorekeeper_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_lorekeeper_of_ages'); # :valdeholm_a_lorekeeper_of_ages_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_lorekeeper_of_arts'); # :valdeholm_a_lorekeeper_of_arts_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_lorekeeper_of_crypts'); # :valdeholm_a_lorekeeper_of_crypts_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_lorekeeper_of_ritual'); # :valdeholm_a_lorekeeper_of_ritual_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_lorekeeper_of_war'); # :valdeholm_a_lorekeeper_of_war_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_loremaster_of_ages'); # :valdeholm_a_loremaster_of_ages_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_loremaster_of_arts'); # :valdeholm_a_loremaster_of_arts_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_loremaster_of_crypts'); # :valdeholm_a_loremaster_of_crypts_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_loremaster_of_ritual'); # :valdeholm_a_loremaster_of_ritual_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_loremaster_of_war'); # :valdeholm_a_loremaster_of_war_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_mammoth_calf'); # :valdeholm_a_mammoth_calf_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_master_at_arms'); # :valdeholm_a_master_at_arms_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_master_tracker'); # :valdeholm_a_master_tracker_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_mature_lakeskater'); # :valdeholm_a_mature_lakeskater_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_metalworker'); # :valdeholm_a_metalworker_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_pit-trained_tiger'); # :valdeholm_a_pit-trained_tiger_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_pitwolf'); # :valdeholm_a_pitwolf_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_royal_guardsman'); # :valdeholm_a_royal_guardsman_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_sergeant'); # :valdeholm_a_sergeant_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_smith'); # :valdeholm_a_smith_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_stonemason'); # :valdeholm_a_stonemason_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_valdeholm_citizen'); # :valdeholm_a_valdeholm_citizen_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_veteran'); # :valdeholm_a_veteran_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_veteran_captain'); # :valdeholm_a_veteran_captain_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_warwolf'); # :valdeholm_a_warwolf_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_weaponsmith'); # :valdeholm_a_weaponsmith_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_wraithguard_captain'); # :valdeholm_a_wraithguard_captain_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_wraithguard_elite'); # :valdeholm_a_wraithguard_elite_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_wraithguard_homeguard'); # :valdeholm_a_wraithguard_homeguard_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_wraithguard_lorekeeper'); # :valdeholm_a_wraithguard_lorekeeper_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_wraithguard_lorekeeper_of_ages'); # :valdeholm_a_wraithguard_lorekeeper_of_ages_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_wraithguard_lorekeeper_of_arts'); # :valdeholm_a_wraithguard_lorekeeper_of_arts_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_wraithguard_loremaster_of_arts'); # :valdeholm_a_wraithguard_loremaster_of_arts_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_wraithguard_master_at_arms'); # :valdeholm_a_wraithguard_master_at_arms_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_wraithguard_veteran'); # :valdeholm_a_wraithguard_veteran_lt:
INSERT INTO loottable(name) VALUES('valdeholm_a_young_lakeskater'); # :valdeholm_a_young_lakeskater_lt:
INSERT INTO loottable(name) VALUES('valdeholm_black_market_sphere'); # :valdeholm_black_market_sphere_lt:
INSERT INTO loottable(name) VALUES('valdeholm_commander_haesgrin'); # :valdeholm_commander_haesgrin_lt:
INSERT INTO loottable(name) VALUES('valdeholm_derein'); # :valdeholm_derein_lt:
INSERT INTO loottable(name) VALUES('valdeholm_forge_fire'); # :valdeholm_forge_fire_lt:
INSERT INTO loottable(name) VALUES('valdeholm_fsp-general-noeffect'); # :valdeholm_fsp-general-noeffect_lt:
INSERT INTO loottable(name) VALUES('valdeholm_gothar'); # :valdeholm_gothar_lt:
INSERT INTO loottable(name) VALUES('valdeholm_seathir'); # :valdeholm_seathir_lt:
INSERT INTO loottable(name) VALUES('valdeholm_shade_scrying_crystal'); # :valdeholm_shade_scrying_crystal_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_heimgul'); # :valdeholm_wraithguard_heimgul_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_lodigar'); # :valdeholm_wraithguard_lodigar_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_lorekeeper_fenegar'); # :valdeholm_wraithguard_lorekeeper_fenegar_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_lorekeeper_malgar'); # :valdeholm_wraithguard_lorekeeper_malgar_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_loremaster_of_crypts'); # :valdeholm_wraithguard_loremaster_of_crypts_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_loremaster_of_ritual'); # :valdeholm_wraithguard_loremaster_of_ritual_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_sergeant_aerik'); # :valdeholm_wraithguard_sergeant_aerik_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_thentil_strongarm'); # :valdeholm_wraithguard_thentil_strongarm_lt:
INSERT INTO loottable(name) VALUES('valdeholm_wraithguard_warden_hrosigar'); # :valdeholm_wraithguard_warden_hrosigar_lt:
INSERT INTO loottable(name) VALUES('valdeholm__'); # :valdeholm___lt:
