INSERT INTO loottable(name) VALUES('anguish_anishy'); # :anguish_anishy_lt:
INSERT INTO loottable(name) VALUES('anguish_arch_magus_vangl'); # :anguish_arch_magus_vangl_lt:
INSERT INTO loottable(name) VALUES('anguish_a_lightning_warrior_commander'); # :anguish_a_lightning_warrior_commander_lt:
INSERT INTO loottable(name) VALUES('anguish_garishi'); # :anguish_garishi_lt:
INSERT INTO loottable(name) VALUES('anguish_oshimai_spirit_of_the_high_air'); # :anguish_oshimai_spirit_of_the_high_air_lt:
INSERT INTO loottable(name) VALUES('anguish_overlord_mata_muram'); # :anguish_overlord_mata_muram_lt:
INSERT INTO loottable(name) VALUES('anguish_piraand'); # :anguish_piraand_lt:
INSERT INTO loottable(name) VALUES('anguish_vyishe'); # :anguish_vyishe_lt:
INSERT INTO loottable(name) VALUES('anguish_yuisaha'); # :anguish_yuisaha_lt:
INSERT INTO loottable(name) VALUES('anguish_administrator_charial'); # :anguish_administrator_charial_lt:
INSERT INTO loottable(name) VALUES('anguish_an_aneuk_augur'); # :anguish_an_aneuk_augur_lt:
INSERT INTO loottable(name) VALUES('anguish_an_aneuk_deacon'); # :anguish_an_aneuk_deacon_lt:
INSERT INTO loottable(name) VALUES('anguish_an_elite_guard'); # :anguish_an_elite_guard_lt:
INSERT INTO loottable(name) VALUES('anguish_an_enthralled_golem'); # :anguish_an_enthralled_golem_lt:
INSERT INTO loottable(name) VALUES('anguish_an_ikaav_bone_render'); # :anguish_an_ikaav_bone_render_lt:
INSERT INTO loottable(name) VALUES('anguish_an_ikaav_flesh_render'); # :anguish_an_ikaav_flesh_render_lt:
INSERT INTO loottable(name) VALUES('anguish_an_ikaav_mind_render'); # :anguish_an_ikaav_mind_render_lt:
INSERT INTO loottable(name) VALUES('anguish_an_ukun_scent_hound'); # :anguish_an_ukun_scent_hound_lt:
INSERT INTO loottable(name) VALUES('anguish_arch_magus_vangl'); # :anguish_arch_magus_vangl_lt:
INSERT INTO loottable(name) VALUES('anguish_arisisi'); # :anguish_arisisi_lt:
INSERT INTO loottable(name) VALUES('anguish_a_discordling_mender'); # :anguish_a_discordling_mender_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_adjunct'); # :anguish_a_dragorn_adjunct_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_attendant'); # :anguish_a_dragorn_attendant_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_bone_breath'); # :anguish_a_dragorn_bone_breath_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_custodian'); # :anguish_a_dragorn_custodian_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_overseer'); # :anguish_a_dragorn_overseer_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_rampart'); # :anguish_a_dragorn_rampart_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_sentinel'); # :anguish_a_dragorn_sentinel_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_sentry'); # :anguish_a_dragorn_sentry_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_steward'); # :anguish_a_dragorn_steward_lt:
INSERT INTO loottable(name) VALUES('anguish_a_dragorn_vehemenant'); # :anguish_a_dragorn_vehemenant_lt:
INSERT INTO loottable(name) VALUES('anguish_a_girplan_mason'); # :anguish_a_girplan_mason_lt:
INSERT INTO loottable(name) VALUES('anguish_a_languished_convert'); # :anguish_a_languished_convert_lt:
INSERT INTO loottable(name) VALUES('anguish_a_lightning_warrior_diode'); # :anguish_a_lightning_warrior_diode_lt:
INSERT INTO loottable(name) VALUES('anguish_a_lightning_warrior_ohm_knight'); # :anguish_a_lightning_warrior_ohm_knight_lt:
INSERT INTO loottable(name) VALUES('anguish_a_lightning_warrior_static_fist'); # :anguish_a_lightning_warrior_static_fist_lt:
INSERT INTO loottable(name) VALUES('anguish_a_lightning_warrior_stormer'); # :anguish_a_lightning_warrior_stormer_lt:
INSERT INTO loottable(name) VALUES('anguish_a_seasoned_guard'); # :anguish_a_seasoned_guard_lt:
INSERT INTO loottable(name) VALUES('anguish_a_subjugated_golem'); # :anguish_a_subjugated_golem_lt:
INSERT INTO loottable(name) VALUES('anguish_a_transmuted_golem'); # :anguish_a_transmuted_golem_lt:
INSERT INTO loottable(name) VALUES('anguish_a_veteran_guard'); # :anguish_a_veteran_guard_lt:
INSERT INTO loottable(name) VALUES('anguish_a_weathered_guard'); # :anguish_a_weathered_guard_lt:
INSERT INTO loottable(name) VALUES('anguish_coerced_lieutenant'); # :anguish_coerced_lieutenant_lt:
INSERT INTO loottable(name) VALUES('anguish_damlin_lingering_charge'); # :anguish_damlin_lingering_charge_lt:
INSERT INTO loottable(name) VALUES('anguish_first_lieutenant_minas'); # :anguish_first_lieutenant_minas_lt:
INSERT INTO loottable(name) VALUES('anguish_frenzied_lasher'); # :anguish_frenzied_lasher_lt:
INSERT INTO loottable(name) VALUES('anguish_frenzied_pit_fiend'); # :anguish_frenzied_pit_fiend_lt:
INSERT INTO loottable(name) VALUES('anguish_grenlok_the_converter'); # :anguish_grenlok_the_converter_lt:
INSERT INTO loottable(name) VALUES('anguish_iilaria'); # :anguish_iilaria_lt:
INSERT INTO loottable(name) VALUES('anguish_janzio'); # :anguish_janzio_lt:
INSERT INTO loottable(name) VALUES('anguish_jelvan'); # :anguish_jelvan_lt:
INSERT INTO loottable(name) VALUES('anguish_jelvans_keepsake'); # :anguish_jelvans_keepsake_lt:
INSERT INTO loottable(name) VALUES('anguish_keldovan_the_harrier'); # :anguish_keldovan_the_harrier_lt:
INSERT INTO loottable(name) VALUES('anguish_laveng'); # :anguish_laveng_lt:
INSERT INTO loottable(name) VALUES('anguish_novara'); # :anguish_novara_lt:
INSERT INTO loottable(name) VALUES('anguish_ofanso'); # :anguish_ofanso_lt:
INSERT INTO loottable(name) VALUES('anguish_orb_of_discordant_energy'); # :anguish_orb_of_discordant_energy_lt:
INSERT INTO loottable(name) VALUES('anguish_ornate_chest'); # :anguish_ornate_chest_lt:
INSERT INTO loottable(name) VALUES('anguish_overlord_mata_muram'); # :anguish_overlord_mata_muram_lt:
INSERT INTO loottable(name) VALUES('anguish_raging_pit_hound'); # :anguish_raging_pit_hound_lt:
INSERT INTO loottable(name) VALUES('anguish_shalvo'); # :anguish_shalvo_lt:
INSERT INTO loottable(name) VALUES('anguish_tanthi_the_tormentor'); # :anguish_tanthi_the_tormentor_lt:
INSERT INTO loottable(name) VALUES('anguish_tantho_the_tormentor'); # :anguish_tantho_the_tormentor_lt:
INSERT INTO loottable(name) VALUES('anguish_tanthu_the_tormentor'); # :anguish_tanthu_the_tormentor_lt:
INSERT INTO loottable(name) VALUES('anguish_ture'); # :anguish_ture_lt:
INSERT INTO loottable(name) VALUES('anguish_uchti'); # :anguish_uchti_lt:
INSERT INTO loottable(name) VALUES('anguish_vangls_focus'); # :anguish_vangls_focus_lt:
INSERT INTO loottable(name) VALUES('anguish_vilria_the_keeper'); # :anguish_vilria_the_keeper_lt:
INSERT INTO loottable(name) VALUES('anguish_vonaahsa'); # :anguish_vonaahsa_lt:
INSERT INTO loottable(name) VALUES('anguish_warden_hanvar'); # :anguish_warden_hanvar_lt:
INSERT INTO loottable(name) VALUES('anguish_yhinra'); # :anguish_yhinra_lt:
INSERT INTO loottable(name) VALUES('anguish_zone_status'); # :anguish_zone_status_lt:
