UPDATE npc_types SET loottable_id = :bloodfields_an_eager_student_lt: WHERE id in (301068); # #an_eager_student 68
UPDATE npc_types SET loottable_id = :bloodfields_an_enslaved_earthmover_lt: WHERE id in (301067); # #an_enslaved_earthmover 68
UPDATE npc_types SET loottable_id = :bloodfields_a_burnmuzle_feran_lt: WHERE id in (301072); # #a_burnmuzle_feran 65
UPDATE npc_types SET loottable_id = :bloodfields_a_mindburrow_feran_lt: WHERE id in (301071); # #a_mindburrow_feran 65
UPDATE npc_types SET loottable_id = :bloodfields_a_noc_slaveguard_lt: WHERE id in (301052); # #a_noc_slaveguard 58
UPDATE npc_types SET loottable_id = :bloodfields_a_reclusive_girplan_lt: WHERE id in (301073, 301074, 301075, 301076, 301033); # #a_reclusive_girplan 62
UPDATE npc_types SET loottable_id = :bloodfields_a_savage_feran_lt: WHERE id in (301070); # #a_savage_feran 65
UPDATE npc_types SET loottable_id = :bloodfields_caller_donivin_lt: WHERE id in (301024); # #Caller_Donivin 70
UPDATE npc_types SET loottable_id = :bloodfields_captain_gherish_lt: WHERE id in (301050); # #Captain_Gherish 58
UPDATE npc_types SET loottable_id = :bloodfields_clergyman_rexith_lt: WHERE id in (301006); # #Clergyman_Rexith 62
UPDATE npc_types SET loottable_id = :bloodfields_discordling_dark_animist_lt: WHERE id in (301069); # #Discordling_Dark_Animist 73
UPDATE npc_types SET loottable_id = :bloodfields_elite_dragorn_jekisia_lt: WHERE id in (301032); # #Elite_Dragorn_Jekisia 70
UPDATE npc_types SET loottable_id = :bloodfields_gazz_the_gargantuan_lt: WHERE id in (301062); # #Gazz_the_Gargantuan 75
UPDATE npc_types SET loottable_id = :bloodfields_golem_supplier_lt: WHERE id in (301060); # #Golem_Supplier 58
UPDATE npc_types SET loottable_id = :bloodfields_grinbik_the_fertile_lt: WHERE id in (301066); # #Grinbik_the_Fertile 70
UPDATE npc_types SET loottable_id = :bloodfields_high_priest_wersin_lt: WHERE id in (301054); # #High_Priest_Wersin 62
UPDATE npc_types SET loottable_id = :bloodfields_ikaav_dominator_lt: WHERE id in (301057); # #Ikaav_Dominator 58
UPDATE npc_types SET loottable_id = :bloodfields_ikaav_slumberer_lt: WHERE id in (301053); # #Ikaav_Slumberer 62
UPDATE npc_types SET loottable_id = :bloodfields_ikaav_sorceress_lt: WHERE id in (301081); # #Ikaav_Sorceress 62
UPDATE npc_types SET loottable_id = :bloodfields_keetra_the_lost_lt: WHERE id in (301078); # #Keetra_the_Lost 65
UPDATE npc_types SET loottable_id = :bloodfields_kragsmash_lt: WHERE id in (301035); # #Kragsmash 75
UPDATE npc_types SET loottable_id = :bloodfields_lieutenant_lihad_lt: WHERE id in (301061); # #Lieutenant_Lihad 62
UPDATE npc_types SET loottable_id = :bloodfields_marshal_histent_lt: WHERE id in (301065); # #Marshal_Histent 73
UPDATE npc_types SET loottable_id = :bloodfields_myrhee_the_flighty_lt: WHERE id in (301077); # #Myrhee_the_Flighty 75
UPDATE npc_types SET loottable_id = :bloodfields_noc_deathstalker_lt: WHERE id in (301051); # #Noc_Deathstalker 62
UPDATE npc_types SET loottable_id = :bloodfields_rolthee_roundbelly_lt: WHERE id in (301079); # #Rolthee_Roundbelly 75
UPDATE npc_types SET loottable_id = :bloodfields_the_domineering_ukun_lt: WHERE id in (301047); # #The_Domineering_Ukun 62
UPDATE npc_types SET loottable_id = :bloodfields_the_heavy_burdened_golem_lt: WHERE id in (301058); # #The_Heavy_Burdened_Golem 62
UPDATE npc_types SET loottable_id = :bloodfields_tormented_scout_lt: WHERE id in (301037); # #Tormented_Scout 65
UPDATE npc_types SET loottable_id = :bloodfields_ukun_hatemonger_lt: WHERE id in (301059); # #Ukun_Hatemonger 58
UPDATE npc_types SET loottable_id = :bloodfields_an_ikaav_castigator_lt: WHERE id in (301003); # an_ikaav_castigator 54
UPDATE npc_types SET loottable_id = :bloodfields_an_ikaav_chimeran_lt: WHERE id in (301022); # an_ikaav_chimeran 54
UPDATE npc_types SET loottable_id = :bloodfields_an_ikaav_deathbeckoner_lt: WHERE id in (301008); # an_ikaav_deathbeckoner 54
UPDATE npc_types SET loottable_id = :bloodfields_an_ikaav_despiser_lt: WHERE id in (301018); # an_ikaav_despiser 54
UPDATE npc_types SET loottable_id = :bloodfields_an_ikaav_miragenist_lt: WHERE id in (301015); # an_ikaav_miragenist 54
UPDATE npc_types SET loottable_id = :bloodfields_an_ukun_fleshhound_lt: WHERE id in (301009); # an_ukun_fleshhound 51
UPDATE npc_types SET loottable_id = :bloodfields_an_ukun_slaughterhound_lt: WHERE id in (301016, 301019, 301044, 301045, 301049); # an_ukun_slaughterhound 61
UPDATE npc_types SET loottable_id = :bloodfields_a_baleful_stoneworker_lt: WHERE id in (301023); # a_baleful_stoneworker 56
UPDATE npc_types SET loottable_id = :bloodfields_a_chest_lt: WHERE id in (301040); # a_chest 65
UPDATE npc_types SET loottable_id = :bloodfields_a_dragorn_adjunct_lt: WHERE id in (301005); # a_dragorn_adjunct 58
UPDATE npc_types SET loottable_id = :bloodfields_a_dragorn_box_lt: WHERE id in (301082); # a_dragorn_box 65
UPDATE npc_types SET loottable_id = :bloodfields_a_dragorn_commoner_lt: WHERE id in (301001, 301007); # a_dragorn_commoner 53
UPDATE npc_types SET loottable_id = :bloodfields_a_dragorn_flunky_lt: WHERE id in (301080); # A_Dragorn_flunky 60
UPDATE npc_types SET loottable_id = :bloodfields_a_dragorn_knight_lt: WHERE id in (301014); # a_dragorn_knight 58
UPDATE npc_types SET loottable_id = :bloodfields_a_dragorn_peon_lt: WHERE id in (301000, 301041); # a_dragorn_peon 53
UPDATE npc_types SET loottable_id = :bloodfields_a_dragorn_warrior_lt: WHERE id in (301002); # a_dragorn_warrior 58
UPDATE npc_types SET loottable_id = :bloodfields_a_noc_darklurch_lt: WHERE id in (301004, 301011); # a_noc_darklurch 56
UPDATE npc_types SET loottable_id = :bloodfields_a_noc_flashblade_lt: WHERE id in (301013); # a_noc_flashblade 56
UPDATE npc_types SET loottable_id = :bloodfields_a_noc_fleshletter_lt: WHERE id in (301010); # a_noc_fleshletter 51
UPDATE npc_types SET loottable_id = :bloodfields_a_noc_havocblade_lt: WHERE id in (301020); # a_noc_havocblade 56
UPDATE npc_types SET loottable_id = :bloodfields_a_slumbering_beast_lt: WHERE id in (301034); # a_slumbering_beast 75
UPDATE npc_types SET loottable_id = :bloodfields_a_subjugated_stoneworker_lt: WHERE id in (301056, 301021, 301026, 301046, 301048, 301055); # a_subjugated_stoneworker 60
UPDATE npc_types SET loottable_id = :bloodfields_a_twisted_stoneworker_lt: WHERE id in (301012); # a_twisted_stoneworker 56
UPDATE npc_types SET loottable_id = :bloodfields_barowsar_lt: WHERE id in (301028); # Barowsar 60
UPDATE npc_types SET loottable_id = :bloodfields_cryssa_lt: WHERE id in (301025); # Cryssa 70
UPDATE npc_types SET loottable_id = :bloodfields_girplan_devourer_lt: WHERE id in (301063); # Girplan_Devourer 70
UPDATE npc_types SET loottable_id = :bloodfields_girplan_slasher_lt: WHERE id in (301027); # Girplan_Slasher 65
UPDATE npc_types SET loottable_id = :bloodfields_guardian_of_kaavi_lt: WHERE id in (301017); # Guardian_of_Kaavi 68
UPDATE npc_types SET loottable_id = :bloodfields_ikaav_dreamweaver_lt: WHERE id in (301031); # Ikaav_Dreamweaver 70
UPDATE npc_types SET loottable_id = :bloodfields_lenarsk_lt: WHERE id in (301029); # Lenarsk 70
UPDATE npc_types SET loottable_id = :bloodfields_marshall_trap_lt: WHERE id in (301064); # marshall_trap 1
UPDATE npc_types SET loottable_id = :bloodfields_sentry_of_kaavi_lt: WHERE id in (301043); # Sentry_of_Kaavi 64
UPDATE npc_types SET loottable_id = :bloodfields_speed_of_body_lt: WHERE id in (301039); # speed_of_body 68
UPDATE npc_types SET loottable_id = :bloodfields_strength_of_body_lt: WHERE id in (301038); # strength_of_body 68
UPDATE npc_types SET loottable_id = :bloodfields_tarvash_scriller_lt: WHERE id in (301036); # Tarvash_Scriller 55
UPDATE npc_types SET loottable_id = :bloodfields_the_keeper_lt: WHERE id in (301030); # The_Keeper 75
UPDATE npc_types SET loottable_id = :bloodfields_war_caller_kaavi_lt: WHERE id in (301042); # War_Caller_Kaavi 70
