UPDATE npc_types SET loottable_id = :causeway_alkron_wyrmsong_lt: WHERE id in (303034); # #Alkron_Wyrmsong 70
UPDATE npc_types SET loottable_id = :causeway_an_aggressive_murkglider_lt: WHERE id in (303119); # #an_aggressive_murkglider 64
UPDATE npc_types SET loottable_id = :causeway_a_bazu_crusher_lt: WHERE id in (303126); # #a_bazu_crusher 65
UPDATE npc_types SET loottable_id = :causeway_a_fecund_murkglider_lt: WHERE id in (303082); # #a_fecund_murkglider 62
UPDATE npc_types SET loottable_id = :causeway_a_feran_packleader_lt: WHERE id in (303090); # #a_feran_packleader 64
UPDATE npc_types SET loottable_id = :causeway_a_ukun_packmaster_lt: WHERE id in (303118); # #a_ukun_packmaster 62
UPDATE npc_types SET loottable_id = :causeway_bazu_scavenger_lt: WHERE id in (303002); # #Bazu_Scavenger 68
UPDATE npc_types SET loottable_id = :causeway_bazu_terror_lt: WHERE id in (303092); # #Bazu_Terror 70
UPDATE npc_types SET loottable_id = :causeway_bone_cracker_lt: WHERE id in (303079); # #Bone_Cracker 70
UPDATE npc_types SET loottable_id = :causeway_discordling_dark_animist_lt: WHERE id in (303094); # #Discordling_Dark_Animist 65
UPDATE npc_types SET loottable_id = :causeway_drarakon_the_mad_lt: WHERE id in (303009); # #Drarakon_the_Mad 71
UPDATE npc_types SET loottable_id = :causeway_event_spawner_lt: WHERE id in (303064); # #Event_Spawner 65
UPDATE npc_types SET loottable_id = :causeway_first_placeholder_lt: WHERE id in (303067); # #First_Placeholder 65
UPDATE npc_types SET loottable_id = :causeway_grinbar_the_ancient_lt: WHERE id in (303107); # #Grinbar_the_Ancient 68
UPDATE npc_types SET loottable_id = :causeway_guardian_etrias_lt: WHERE id in (303111); # #Guardian_Etrias 66
UPDATE npc_types SET loottable_id = :causeway_guardian_naven_lt: WHERE id in (303112); # #Guardian_Naven 66
UPDATE npc_types SET loottable_id = :causeway_jillaa_oogblat_lt: WHERE id in (303085); # #Jillaa_Oogblat 65
UPDATE npc_types SET loottable_id = :causeway_kupiop_iku_lt: WHERE id in (303060); # #Kupiop_Iku 65
UPDATE npc_types SET loottable_id = :causeway_lannal_the_beast_tamer_lt: WHERE id in (303062); # #Lannal_the_Beast_Tamer 65
UPDATE npc_types SET loottable_id = :causeway_misdirection_lt: WHERE id in (303061); # #Misdirection 65
UPDATE npc_types SET loottable_id = :causeway_murkglider_school_leader_lt: WHERE id in (303116); # #Murkglider_School_Leader 68
UPDATE npc_types SET loottable_id = :causeway_oshiruk_lt: WHERE id in (303125); # #Oshiruk 85
UPDATE npc_types SET loottable_id = :causeway_ridgerunner_drunt_lt: WHERE id in (303003); # #Ridgerunner_Drunt 62
UPDATE npc_types SET loottable_id = :causeway_rng_trap_lt: WHERE id in (303133); # #rng_trap 1
UPDATE npc_types SET loottable_id = :causeway_second_placeholder_lt: WHERE id in (303066); # #Second_Placeholder 65
UPDATE npc_types SET loottable_id = :causeway_siflu_lt: WHERE id in (303091); # #Siflu 63
UPDATE npc_types SET loottable_id = :causeway_slavedriver_menlo_lt: WHERE id in (303115); # #Slavedriver_Menlo 70
UPDATE npc_types SET loottable_id = :causeway_stone_thrower_lt: WHERE id in (303087); # #Stone_Thrower 71
UPDATE npc_types SET loottable_id = :causeway_tarlang_lt: WHERE id in (303083); # #Tarlang 73
UPDATE npc_types SET loottable_id = :causeway_warr_trap_lt: WHERE id in (303132); # #warr_trap 1
UPDATE npc_types SET loottable_id = :causeway_withering_murkglider_lt: WHERE id in (303078); # #Withering_Murkglider 80
UPDATE npc_types SET loottable_id = :causeway_you_hear_lt: WHERE id in (303065); # #You_hear 65
UPDATE npc_types SET loottable_id = :causeway_ziegel_one-eye_lt: WHERE id in (303144); # #Ziegel_One-eye 1
UPDATE npc_types SET loottable_id = :causeway_ziegel_one-eye,_bazu_tamer_lt: WHERE id in (303139); # #Ziegel_One-eye,_Bazu_Tamer 72
UPDATE npc_types SET loottable_id = :causeway_alpha_feran_lt: WHERE id in (303074); # Alpha_Feran 69
UPDATE npc_types SET loottable_id = :causeway_an_aneuk_overseer_lt: WHERE id in (303008); # an_aneuk_overseer 60
UPDATE npc_types SET loottable_id = :causeway_an_ikaav_overseer_lt: WHERE id in (303020); # an_ikaav_overseer 61
UPDATE npc_types SET loottable_id = :causeway_an_ukun_bloodbeast_lt: WHERE id in (303014); # an_ukun_bloodbeast 59
UPDATE npc_types SET loottable_id = :causeway_an_ukun_deathhowler_lt: WHERE id in (303005); # an_ukun_deathhowler 61
UPDATE npc_types SET loottable_id = :causeway_a_battle-scarred_bazu_lt: WHERE id in (303036); # a_battle-scarred_bazu 65
UPDATE npc_types SET loottable_id = :causeway_a_bazu_crusher_lt: WHERE id in (303093); # a_bazu_crusher 65
UPDATE npc_types SET loottable_id = :causeway_a_beast_controller_lt: WHERE id in (303142); # a_beast_controller 65
UPDATE npc_types SET loottable_id = :causeway_a_beast_handler_lt: WHERE id in (303141); # a_beast_handler 63
UPDATE npc_types SET loottable_id = :causeway_a_beast_master_lt: WHERE id in (303143); # a_beast_master 66
UPDATE npc_types SET loottable_id = :causeway_a_chained_bazu_lt: WHERE id in (303077); # a_chained_bazu 66
UPDATE npc_types SET loottable_id = :causeway_a_chest_lt: WHERE id in (303120, 303084); # a_chest 65
UPDATE npc_types SET loottable_id = :causeway_a_deranged_feran_lt: WHERE id in (303135); # a_deranged_feran 67
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_arch_prelate_lt: WHERE id in (303017); # a_dragorn_arch_prelate 65
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_armsman_lt: WHERE id in (303012, 303033); # a_dragorn_armsman 61
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_battleleader_lt: WHERE id in (303138); # a_dragorn_battleleader 68
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_elite_armsman_lt: WHERE id in (303010); # a_dragorn_elite_armsman 65
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_elite_guard_lt: WHERE id in (303011); # a_dragorn_elite_guard 61
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_guard_lt: WHERE id in (303022); # a_dragorn_guard 59
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_officer_lt: WHERE id in (303038); # a_dragorn_officer 65
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_prelate_lt: WHERE id in (303054, 303055); # a_dragorn_prelate 61
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_refugee_lt: WHERE id in (303030, 303031, 303032, 303046); # a_dragorn_refugee 66
UPDATE npc_types SET loottable_id = :causeway_a_dragorn_researcher_lt: WHERE id in (303108, 303013, 303015, 303056, 303057); # a_dragorn_researcher 61
UPDATE npc_types SET loottable_id = :causeway_a_feran_lt: WHERE id in (303037); # a_feran 61
UPDATE npc_types SET loottable_id = :causeway_a_feran_bull_lt: WHERE id in (303137); # a_feran_bull 65
UPDATE npc_types SET loottable_id = :causeway_a_gargantuan_bazu_lt: WHERE id in (303063); # a_gargantuan_bazu 69
UPDATE npc_types SET loottable_id = :causeway_a_kyv_heartstriker_lt: WHERE id in (303001); # a_kyv_heartstriker 59
UPDATE npc_types SET loottable_id = :causeway_a_massive_bazu_lt: WHERE id in (303136); # a_massive_bazu 68
UPDATE npc_types SET loottable_id = :causeway_a_mountain_bazu_lt: WHERE id in (303024); # a_mountain_bazu 63
UPDATE npc_types SET loottable_id = :causeway_a_murkglider_lt: WHERE id in (303000, 303004, 303006, 303007, 303026, 303051); # a_murkglider 61
UPDATE npc_types SET loottable_id = :causeway_a_murkglider_deathgrime_lt: WHERE id in (303035, 303040, 303044, 303045); # a_murkglider_deathgrime 65
UPDATE npc_types SET loottable_id = :causeway_a_murkglider_soother_lt: WHERE id in (303117, 303058, 303059, 303095); # a_murkglider_soother 61
UPDATE npc_types SET loottable_id = :causeway_a_murkglider_soulhunter_lt: WHERE id in (303029); # a_murkglider_soulhunter 61
UPDATE npc_types SET loottable_id = :causeway_a_murkglider_soulstalker_lt: WHERE id in (303019, 303041, 303042, 303052); # a_murkglider_soulstalker 64
UPDATE npc_types SET loottable_id = :causeway_a_murkglider_spiritsipper_lt: WHERE id in (303039, 303043, 303053, 303086); # a_murkglider_spiritsipper 66
UPDATE npc_types SET loottable_id = :causeway_a_murkglider_stalker_lt: WHERE id in (303016, 303025, 303088); # a_murkglider_stalker 61
UPDATE npc_types SET loottable_id = :causeway_a_murkglider_stinger_lt: WHERE id in (303027, 303028, 303047); # a_murkglider_stinger 64
UPDATE npc_types SET loottable_id = :causeway_a_noc_sprayblood_lt: WHERE id in (303021); # a_noc_sprayblood 59
UPDATE npc_types SET loottable_id = :causeway_a_parasitic_murkglider_lt: WHERE id in (303121); # A_parasitic_murkglider 65
UPDATE npc_types SET loottable_id = :causeway_a_poisonous_murkglider_lt: WHERE id in (303134); # a_poisonous_murkglider 67
UPDATE npc_types SET loottable_id = :causeway_a_rampaging_bazu_lt: WHERE id in (303140); # a_rampaging_bazu 68
UPDATE npc_types SET loottable_id = :causeway_a_stalking_feran_lt: WHERE id in (303018); # a_stalking_feran 65
UPDATE npc_types SET loottable_id = :causeway_bazu_hulk_lt: WHERE id in (303106); # Bazu_Hulk 72
UPDATE npc_types SET loottable_id = :causeway_bazu_smasher_lt: WHERE id in (303081); # Bazu_Smasher 78
UPDATE npc_types SET loottable_id = :causeway_elemental_essence_breeze_lt: WHERE id in (303103); # Elemental_Essence_Breeze 63
UPDATE npc_types SET loottable_id = :causeway_elemental_essence_current_lt: WHERE id in (303105); # Elemental_Essence_Current 68
UPDATE npc_types SET loottable_id = :causeway_elemental_essence_gust_lt: WHERE id in (303102); # Elemental_Essence_Gust 65
UPDATE npc_types SET loottable_id = :causeway_elemental_essence_of_air_lt: WHERE id in (303100); # Elemental_Essence_of_Air 70
UPDATE npc_types SET loottable_id = :causeway_elemental_essence_wind_lt: WHERE id in (303104); # Elemental_Essence_Wind 63
UPDATE npc_types SET loottable_id = :causeway_elemental_essence_zephyr_lt: WHERE id in (303101); # Elemental_Essence_Zephyr 68
UPDATE npc_types SET loottable_id = :causeway_essence_of_kreljnok_lt: WHERE id in (303129); # Essence_of_Kreljnok 75
UPDATE npc_types SET loottable_id = :causeway_feran_attendant_lt: WHERE id in (303109, 303071, 303096); # feran_attendant 67
UPDATE npc_types SET loottable_id = :causeway_feran_defender_lt: WHERE id in (303110, 303072, 303073); # feran_defender 67
UPDATE npc_types SET loottable_id = :causeway_gorvoroth_lt: WHERE id in (303080); # Gorvoroth 70
UPDATE npc_types SET loottable_id = :causeway_korbuk_brimblade_lt: WHERE id in (303128); # Korbuk_Brimblade 72
UPDATE npc_types SET loottable_id = :causeway_kreljnoks_power_lt: WHERE id in (303131); # Kreljnok`s_Power 73
UPDATE npc_types SET loottable_id = :causeway_kreljnoks_rage_lt: WHERE id in (303130); # Kreljnok`s_Rage 73
UPDATE npc_types SET loottable_id = :causeway_murkglider_drone_lt: WHERE id in (303114); # murkglider_drone 64
UPDATE npc_types SET loottable_id = :causeway_murkglider_nursemaid_lt: WHERE id in (303113); # murkglider_nursemaid 64
UPDATE npc_types SET loottable_id = :causeway_murkglider_school_leader_lt: WHERE id in (303127); # Murkglider_School_Leader 68
UPDATE npc_types SET loottable_id = :causeway_nerask_lt: WHERE id in (303069); # Nerask 70
UPDATE npc_types SET loottable_id = :causeway_pixt_arreand_bodybender_lt: WHERE id in (303122); # Pixt_Arreand_Bodybender 63
UPDATE npc_types SET loottable_id = :causeway_pixt_trent_lt: WHERE id in (303123); # Pixt_Trent 63
UPDATE npc_types SET loottable_id = :causeway_ridgerunner_droongar_lt: WHERE id in (303124); # Ridgerunner_Droongar 64
UPDATE npc_types SET loottable_id = :causeway_tamed_bazu_herder_lt: WHERE id in (303023); # tamed_bazu_herder 61
UPDATE npc_types SET loottable_id = :causeway_tarlang_lt: WHERE id in (303070); # Tarlang 64
UPDATE npc_types SET loottable_id = :causeway_vorkiev_lt: WHERE id in (303068); # Vorkiev 65
UPDATE npc_types SET loottable_id = :causeway___lt: WHERE id in (303048, 303049, 303050, 303098, 303099); # _ 62
