INSERT INTO loottable(name) VALUES('dranikhollowsb_an_ukun_deathhound'); # :dranikhollowsb_an_ukun_deathhound_lt:
INSERT INTO loottable(name) VALUES('dranikhollowsb_an_ukun_fleshhound'); # :dranikhollowsb_an_ukun_fleshhound_lt:
INSERT INTO loottable(name) VALUES('dranikhollowsb_a_dragorn_commoner'); # :dranikhollowsb_a_dragorn_commoner_lt:
INSERT INTO loottable(name) VALUES('dranikhollowsb_a_dragorn_peon'); # :dranikhollowsb_a_dragorn_peon_lt:
INSERT INTO loottable(name) VALUES('dranikhollowsb_a_kyv_bloodhunter'); # :dranikhollowsb_a_kyv_bloodhunter_lt:
INSERT INTO loottable(name) VALUES('dranikhollowsb_a_kyv_heartpiercer'); # :dranikhollowsb_a_kyv_heartpiercer_lt:
INSERT INTO loottable(name) VALUES('dranikhollowsb_a_noc_darklurch'); # :dranikhollowsb_a_noc_darklurch_lt:
INSERT INTO loottable(name) VALUES('dranikhollowsb_a_noc_flashblade'); # :dranikhollowsb_a_noc_flashblade_lt:
INSERT INTO loottable(name) VALUES('dranikhollowsb_kyv_bowkeeper'); # :dranikhollowsb_kyv_bowkeeper_lt:
INSERT INTO loottable(name) VALUES('dranikhollowsb_ukun_fleshrender'); # :dranikhollowsb_ukun_fleshrender_lt:
