INSERT INTO loottable(name) VALUES('draniksewersb_nightfang_glider'); # :draniksewersb_nightfang_glider_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_silania_janaid'); # :draniksewersb_silania_janaid_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_an_elite_ikaav_bonekindler'); # :draniksewersb_an_elite_ikaav_bonekindler_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_an_elite_ikaav_contemptress'); # :draniksewersb_an_elite_ikaav_contemptress_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_an_elite_ikaav_thoughtfouler'); # :draniksewersb_an_elite_ikaav_thoughtfouler_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_an_elite_noc_cadavor'); # :draniksewersb_an_elite_noc_cadavor_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_an_elite_noc_sprayblood'); # :draniksewersb_an_elite_noc_sprayblood_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_an_elite_ukun_bloodbeast'); # :draniksewersb_an_elite_ukun_bloodbeast_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_an_elite_ukun_deathhowler'); # :draniksewersb_an_elite_ukun_deathhowler_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_an_enthralled_stoneworker'); # :draniksewersb_an_enthralled_stoneworker_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_an_offal_eating_rat'); # :draniksewersb_an_offal_eating_rat_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_discordling_crafter'); # :draniksewersb_a_discordling_crafter_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_discordling_patron'); # :draniksewersb_a_discordling_patron_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_dragorn_curate'); # :draniksewersb_a_dragorn_curate_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_dragorn_prelate'); # :draniksewersb_a_dragorn_prelate_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_dragorn_slave'); # :draniksewersb_a_dragorn_slave_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_dragorn_steward'); # :draniksewersb_a_dragorn_steward_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_girplan_rebuilder'); # :draniksewersb_a_girplan_rebuilder_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_girplan_stonelifter'); # :draniksewersb_a_girplan_stonelifter_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_murkglider_stalker'); # :draniksewersb_a_murkglider_stalker_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_murkglider_stinger'); # :draniksewersb_a_murkglider_stinger_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_rabble_dwelling_varmint'); # :draniksewersb_a_rabble_dwelling_varmint_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_screeching_siltglider'); # :draniksewersb_a_screeching_siltglider_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_shrieking_siltglider'); # :draniksewersb_a_shrieking_siltglider_lt:
INSERT INTO loottable(name) VALUES('draniksewersb_a_twisted_stoneworker'); # :draniksewersb_a_twisted_stoneworker_lt:
