INSERT INTO loottable(name) VALUES('draniksscar_druid_trap'); # :draniksscar_druid_trap_lt:
INSERT INTO loottable(name) VALUES('draniksscar_elder_murkglider_devourer'); # :draniksscar_elder_murkglider_devourer_lt:
INSERT INTO loottable(name) VALUES('draniksscar_ertalon_the_thrall'); # :draniksscar_ertalon_the_thrall_lt:
INSERT INTO loottable(name) VALUES('draniksscar_fang'); # :draniksscar_fang_lt:
INSERT INTO loottable(name) VALUES('draniksscar_girplan_spiritleech'); # :draniksscar_girplan_spiritleech_lt:
INSERT INTO loottable(name) VALUES('draniksscar_girztal_the_attendant'); # :draniksscar_girztal_the_attendant_lt:
INSERT INTO loottable(name) VALUES('draniksscar_grathnok_gilforgan'); # :draniksscar_grathnok_gilforgan_lt:
INSERT INTO loottable(name) VALUES('draniksscar_karsor_the_mad'); # :draniksscar_karsor_the_mad_lt:
INSERT INTO loottable(name) VALUES('draniksscar_kiltarn_the_sharp'); # :draniksscar_kiltarn_the_sharp_lt:
INSERT INTO loottable(name) VALUES('draniksscar_kirspos_the_cruel'); # :draniksscar_kirspos_the_cruel_lt:
INSERT INTO loottable(name) VALUES('draniksscar_kyv_bowmaster'); # :draniksscar_kyv_bowmaster_lt:
INSERT INTO loottable(name) VALUES('draniksscar_kyv_darkscout'); # :draniksscar_kyv_darkscout_lt:
INSERT INTO loottable(name) VALUES('draniksscar_mature_murkglider_devourer'); # :draniksscar_mature_murkglider_devourer_lt:
INSERT INTO loottable(name) VALUES('draniksscar_murkglider_hiveguard'); # :draniksscar_murkglider_hiveguard_lt:
INSERT INTO loottable(name) VALUES('draniksscar_murkglider_man_o_war'); # :draniksscar_murkglider_man_o_war_lt:
INSERT INTO loottable(name) VALUES('draniksscar_murkglider_marroweater'); # :draniksscar_murkglider_marroweater_lt:
INSERT INTO loottable(name) VALUES('draniksscar_newborn_murkglider_devourer'); # :draniksscar_newborn_murkglider_devourer_lt:
INSERT INTO loottable(name) VALUES('draniksscar_noc_bloodtusk'); # :draniksscar_noc_bloodtusk_lt:
INSERT INTO loottable(name) VALUES('draniksscar_noc_razortusk'); # :draniksscar_noc_razortusk_lt:
INSERT INTO loottable(name) VALUES('draniksscar_scaleback'); # :draniksscar_scaleback_lt:
INSERT INTO loottable(name) VALUES('draniksscar_ukun_gutfeaster'); # :draniksscar_ukun_gutfeaster_lt:
INSERT INTO loottable(name) VALUES('draniksscar_ukun_slavehunter'); # :draniksscar_ukun_slavehunter_lt:
INSERT INTO loottable(name) VALUES('draniksscar_yerika_sisslak'); # :draniksscar_yerika_sisslak_lt:
INSERT INTO loottable(name) VALUES('draniksscar_young_murkglider_devourer'); # :draniksscar_young_murkglider_devourer_lt:
INSERT INTO loottable(name) VALUES('draniksscar_an_ukun'); # :draniksscar_an_ukun_lt:
INSERT INTO loottable(name) VALUES('draniksscar_an_ukun_deathhound'); # :draniksscar_an_ukun_deathhound_lt:
INSERT INTO loottable(name) VALUES('draniksscar_an_ukun_fleshhound'); # :draniksscar_an_ukun_fleshhound_lt:
INSERT INTO loottable(name) VALUES('draniksscar_an_ukun_slaughterhound'); # :draniksscar_an_ukun_slaughterhound_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_blightscourge_rat'); # :draniksscar_a_blightscourge_rat_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_darkscourge_rat'); # :draniksscar_a_darkscourge_rat_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_dragorn_commoner'); # :draniksscar_a_dragorn_commoner_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_dragorn_peon'); # :draniksscar_a_dragorn_peon_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_filthy_rat'); # :draniksscar_a_filthy_rat_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_girplan_spiritminion'); # :draniksscar_a_girplan_spiritminion_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_greater_fringed_bat'); # :draniksscar_a_greater_fringed_bat_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_greater_noctulis_bat'); # :draniksscar_a_greater_noctulis_bat_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_kyv'); # :draniksscar_a_kyv_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_kyv_bloodhunter'); # :draniksscar_a_kyv_bloodhunter_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_kyv_heartpiercer'); # :draniksscar_a_kyv_heartpiercer_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_lesser_fringed_bat'); # :draniksscar_a_lesser_fringed_bat_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_lesser_noctulis_bat'); # :draniksscar_a_lesser_noctulis_bat_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_murkglider'); # :draniksscar_a_murkglider_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_murkglider_blighter'); # :draniksscar_a_murkglider_blighter_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_murkglider_lingerer'); # :draniksscar_a_murkglider_lingerer_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_murkglider_skulker'); # :draniksscar_a_murkglider_skulker_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_murkglider_slinker'); # :draniksscar_a_murkglider_slinker_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_murkglider_souldrifter'); # :draniksscar_a_murkglider_souldrifter_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_murkglider_wanderer'); # :draniksscar_a_murkglider_wanderer_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_noc'); # :draniksscar_a_noc_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_noc_darklurch'); # :draniksscar_a_noc_darklurch_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_noc_havocblade'); # :draniksscar_a_noc_havocblade_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_noc_sharpblade'); # :draniksscar_a_noc_sharpblade_lt:
INSERT INTO loottable(name) VALUES('draniksscar_a_plaguescourge_rat'); # :draniksscar_a_plaguescourge_rat_lt:
INSERT INTO loottable(name) VALUES('draniksscar_blackfall_borer'); # :draniksscar_blackfall_borer_lt:
INSERT INTO loottable(name) VALUES('draniksscar_bolodakan'); # :draniksscar_bolodakan_lt:
INSERT INTO loottable(name) VALUES('draniksscar_elder_priest_of_discord'); # :draniksscar_elder_priest_of_discord_lt:
INSERT INTO loottable(name) VALUES('draniksscar_grand_historian_gersh'); # :draniksscar_grand_historian_gersh_lt:
INSERT INTO loottable(name) VALUES('draniksscar_iilivina'); # :draniksscar_iilivina_lt:
INSERT INTO loottable(name) VALUES('draniksscar_kirostall'); # :draniksscar_kirostall_lt:
INSERT INTO loottable(name) VALUES('draniksscar_korbuk_brimblade'); # :draniksscar_korbuk_brimblade_lt:
INSERT INTO loottable(name) VALUES('draniksscar_kyv_headhunter'); # :draniksscar_kyv_headhunter_lt:
INSERT INTO loottable(name) VALUES('draniksscar_priest_of_discord'); # :draniksscar_priest_of_discord_lt:
INSERT INTO loottable(name) VALUES('draniksscar_shorvock'); # :draniksscar_shorvock_lt:
INSERT INTO loottable(name) VALUES('draniksscar_tibor'); # :draniksscar_tibor_lt:
INSERT INTO loottable(name) VALUES('draniksscar_tranlinor_the_maimed'); # :draniksscar_tranlinor_the_maimed_lt:
INSERT INTO loottable(name) VALUES('draniksscar_ukun_boneretriever'); # :draniksscar_ukun_boneretriever_lt:
INSERT INTO loottable(name) VALUES('draniksscar_vorskahn'); # :draniksscar_vorskahn_lt:
