INSERT INTO loottable(name) VALUES('dranikcatacombsa_dragorn_marshal_greshka'); # :dranikcatacombsa_dragorn_marshal_greshka_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_high_enchantress_zychia'); # :dranikcatacombsa_high_enchantress_zychia_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_shade_of_redis_linrok'); # :dranikcatacombsa_shade_of_redis_linrok_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_ikaav_bonekindler'); # :dranikcatacombsa_an_elite_ikaav_bonekindler_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_ikaav_fleshflare'); # :dranikcatacombsa_an_elite_ikaav_fleshflare_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_ikaav_odiumate'); # :dranikcatacombsa_an_elite_ikaav_odiumate_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_ikaav_thoughtfouler'); # :dranikcatacombsa_an_elite_ikaav_thoughtfouler_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_noc'); # :dranikcatacombsa_an_elite_noc_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_noc_cadavor'); # :dranikcatacombsa_an_elite_noc_cadavor_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_noc_sprayblood'); # :dranikcatacombsa_an_elite_noc_sprayblood_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_ukun'); # :dranikcatacombsa_an_elite_ukun_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_ukun_bloodbeast'); # :dranikcatacombsa_an_elite_ukun_bloodbeast_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_elite_ukun_bloodhowler'); # :dranikcatacombsa_an_elite_ukun_bloodhowler_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_an_enshrined_bat'); # :dranikcatacombsa_an_enshrined_bat_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_baleful_stoneworker'); # :dranikcatacombsa_a_baleful_stoneworker_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_crypt-robbing_rat'); # :dranikcatacombsa_a_crypt-robbing_rat_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_dragorn_armsman'); # :dranikcatacombsa_a_dragorn_armsman_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_dragorn_curate'); # :dranikcatacombsa_a_dragorn_curate_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_dragorn_laborer'); # :dranikcatacombsa_a_dragorn_laborer_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_dragorn_prelate'); # :dranikcatacombsa_a_dragorn_prelate_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_dragorn_slave'); # :dranikcatacombsa_a_dragorn_slave_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_dragorn_steward'); # :dranikcatacombsa_a_dragorn_steward_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_murkglider_soother'); # :dranikcatacombsa_a_murkglider_soother_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_murkglider_stinger'); # :dranikcatacombsa_a_murkglider_stinger_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_murkglider_striker'); # :dranikcatacombsa_a_murkglider_striker_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_noc_scout'); # :dranikcatacombsa_a_noc_scout_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_scavenging_rat'); # :dranikcatacombsa_a_scavenging_rat_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_sepulcher_bat'); # :dranikcatacombsa_a_sepulcher_bat_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_sepulcher_rat'); # :dranikcatacombsa_a_sepulcher_rat_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_shrieking_bloodfang'); # :dranikcatacombsa_a_shrieking_bloodfang_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_subjugated_stoneworker'); # :dranikcatacombsa_a_subjugated_stoneworker_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_a_twisted_stoneworker'); # :dranikcatacombsa_a_twisted_stoneworker_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_elite_overlord_vijaz'); # :dranikcatacombsa_elite_overlord_vijaz_lt:
INSERT INTO loottable(name) VALUES('dranikcatacombsa_ikaav_mind_distorter'); # :dranikcatacombsa_ikaav_mind_distorter_lt:
