UPDATE npc_types SET loottable_id = :riftseekers_balancer_relik_lt: WHERE id in (334073); # #Balancer_Relik 73
UPDATE npc_types SET loottable_id = :riftseekers_burnscar_lt: WHERE id in (334101); # #Burnscar 60
UPDATE npc_types SET loottable_id = :riftseekers_chailak_lt: WHERE id in (334014); # #Chailak 75
UPDATE npc_types SET loottable_id = :riftseekers_channeler_pyren_lt: WHERE id in (334121); # #Channeler_Pyren 75
UPDATE npc_types SET loottable_id = :riftseekers_cinder_lt: WHERE id in (334099); # #Cinder 60
UPDATE npc_types SET loottable_id = :riftseekers_coal_lt: WHERE id in (334100); # #Coal 60
UPDATE npc_types SET loottable_id = :riftseekers_companion_prefect_lt: WHERE id in (334106); # #Companion_Prefect 74
UPDATE npc_types SET loottable_id = :riftseekers_craftmaster_tieranu_lt: WHERE id in (334087); # #Craftmaster_Tieranu 80
UPDATE npc_types SET loottable_id = :riftseekers_discordling_gemkeeper_lt: WHERE id in (334066); # #Discordling_Gemkeeper 75
UPDATE npc_types SET loottable_id = :riftseekers_discordling_shardmender_lt: WHERE id in (334083); # #Discordling_Shardmender 74
UPDATE npc_types SET loottable_id = :riftseekers_elite_aneuk_miseryfiend_lt: WHERE id in (334104); # #Elite_Aneuk_Miseryfiend 74
UPDATE npc_types SET loottable_id = :riftseekers_familiar_venomtail_lt: WHERE id in (334093); # #Familiar_Venomtail 75
UPDATE npc_types SET loottable_id = :riftseekers_feratha_lt: WHERE id in (334102); # #Feratha 75
UPDATE npc_types SET loottable_id = :riftseekers_flamegore_lt: WHERE id in (334089); # #Flamegore 70
UPDATE npc_types SET loottable_id = :riftseekers_flametop_lt: WHERE id in (334098); # #Flametop 60
UPDATE npc_types SET loottable_id = :riftseekers_flareup_lt: WHERE id in (334097); # #Flareup 60
UPDATE npc_types SET loottable_id = :riftseekers_frostkeeper_rybah_lt: WHERE id in (334067); # #Frostkeeper_Rybah 74
UPDATE npc_types SET loottable_id = :riftseekers_gelidran_conjurer_lt: WHERE id in (334088); # #Gelidran_Conjurer 75
UPDATE npc_types SET loottable_id = :riftseekers_gelidran_frostformer_lt: WHERE id in (334076); # #Gelidran_Frostformer 75
UPDATE npc_types SET loottable_id = :riftseekers_gelidran_icekeeper_lt: WHERE id in (334105); # #Gelidran_Icekeeper 75
UPDATE npc_types SET loottable_id = :riftseekers_girplan_shardtender_lt: WHERE id in (334103); # #Girplan_Shardtender 74
UPDATE npc_types SET loottable_id = :riftseekers_girplan_stonesinger_lt: WHERE id in (334020); # #Girplan_Stonesinger 75
UPDATE npc_types SET loottable_id = :riftseekers_hotspot_lt: WHERE id in (334091); # #Hotspot 70
UPDATE npc_types SET loottable_id = :riftseekers_king_gelaqua_lt: WHERE id in (334041); # #King_Gelaqua 80
UPDATE npc_types SET loottable_id = :riftseekers_mistwalker_lt: WHERE id in (334108); # #Mistwalker 75
UPDATE npc_types SET loottable_id = :riftseekers_princess_kira_lt: WHERE id in (334046); # #Princess_Kira 75
UPDATE npc_types SET loottable_id = :riftseekers_princess_lana_lt: WHERE id in (334044); # #Princess_Lana 75
UPDATE npc_types SET loottable_id = :riftseekers_princess_puja_lt: WHERE id in (334043); # #Princess_Puja 75
UPDATE npc_types SET loottable_id = :riftseekers_princess_quellon_lt: WHERE id in (334045); # #Princess_Quellon 75
UPDATE npc_types SET loottable_id = :riftseekers_princess_yelnia_lt: WHERE id in (334047); # #Princess_Yelnia 75
UPDATE npc_types SET loottable_id = :riftseekers_princess_zulaqua_lt: WHERE id in (334048); # #Princess_Zulaqua 75
UPDATE npc_types SET loottable_id = :riftseekers_prince_allin_lt: WHERE id in (334036); # #Prince_Allin 75
UPDATE npc_types SET loottable_id = :riftseekers_prince_britalic_lt: WHERE id in (334037); # #Prince_Britalic 75
UPDATE npc_types SET loottable_id = :riftseekers_prince_cynin_lt: WHERE id in (334039); # #Prince_Cynin 75
UPDATE npc_types SET loottable_id = :riftseekers_prince_ilsin_lt: WHERE id in (334040); # #Prince_Ilsin 75
UPDATE npc_types SET loottable_id = :riftseekers_prince_kiranus_lt: WHERE id in (334035); # #Prince_Kiranus 75
UPDATE npc_types SET loottable_id = :riftseekers_prince_scyllus_lt: WHERE id in (334038); # #Prince_Scyllus 75
UPDATE npc_types SET loottable_id = :riftseekers_pyrilen_researcher_lt: WHERE id in (334070); # #Pyrilen_Researcher 75
UPDATE npc_types SET loottable_id = :riftseekers_pyrilen_riftseeker_lt: WHERE id in (334069); # #Pyrilen_Riftseeker 75
UPDATE npc_types SET loottable_id = :riftseekers_pyrilen_summoner_lt: WHERE id in (334002); # #Pyrilen_Summoner 75
UPDATE npc_types SET loottable_id = :riftseekers_queen_pyrilonis_lt: WHERE id in (334049); # #Queen_Pyrilonis 80
UPDATE npc_types SET loottable_id = :riftseekers_ruiner_isaka_lt: WHERE id in (334007); # #Ruiner_Isaka 74
UPDATE npc_types SET loottable_id = :riftseekers_shadowstalker_lt: WHERE id in (334096); # #Shadowstalker 74
UPDATE npc_types SET loottable_id = :riftseekers_sizzle_lt: WHERE id in (334090); # #Sizzle 70
UPDATE npc_types SET loottable_id = :riftseekers_an_aneuk_darkdiviner_lt: WHERE id in (334084); # an_aneuk_darkdiviner 71
UPDATE npc_types SET loottable_id = :riftseekers_an_aneuk_fleshthreader_lt: WHERE id in (334081); # an_aneuk_fleshthreader 71
UPDATE npc_types SET loottable_id = :riftseekers_an_aneuk_painwringer_lt: WHERE id in (334009); # an_aneuk_painwringer 71
UPDATE npc_types SET loottable_id = :riftseekers_an_icy_orb_lt: WHERE id in (334095); # an_icy_orb 75
UPDATE npc_types SET loottable_id = :riftseekers_an_ikaav_detainer_lt: WHERE id in (334068); # an_ikaav_detainer 71
UPDATE npc_types SET loottable_id = :riftseekers_an_ikaav_neuromancer_lt: WHERE id in (334078, 334079); # an_ikaav_neuromancer 72
UPDATE npc_types SET loottable_id = :riftseekers_an_ikaav_ruiner_lt: WHERE id in (334060); # an_ikaav_ruiner 71
UPDATE npc_types SET loottable_id = :riftseekers_a_chest_lt: WHERE id in (334092); # a_chest 65
UPDATE npc_types SET loottable_id = :riftseekers_a_commanded_chimera_lt: WHERE id in (334013, 334071); # a_commanded_chimera 71
UPDATE npc_types SET loottable_id = :riftseekers_a_commanded_feran_lt: WHERE id in (334021, 334057); # a_commanded_feran 72
UPDATE npc_types SET loottable_id = :riftseekers_a_companion_chimera_lt: WHERE id in (334012, 334015); # a_companion_chimera 71
UPDATE npc_types SET loottable_id = :riftseekers_a_companion_feran_lt: WHERE id in (334022, 334061); # a_companion_feran 72
UPDATE npc_types SET loottable_id = :riftseekers_a_crystalline_portal_lt: WHERE id in (334111, 334112, 334113, 334114, 334115, 334116, 334117, 334118, 334119, 334120, 334034, 334042); # a_crystalline_portal 70
UPDATE npc_types SET loottable_id = :riftseekers_a_discordling_architect_lt: WHERE id in (334058, 334064); # a_discordling_architect 71
UPDATE npc_types SET loottable_id = :riftseekers_a_discordling_surveyor_lt: WHERE id in (334056, 334063); # a_discordling_surveyor 71
UPDATE npc_types SET loottable_id = :riftseekers_a_dragorn_battlemaster_lt: WHERE id in (334033); # a_Dragorn_Battlemaster 70
UPDATE npc_types SET loottable_id = :riftseekers_a_ferocious_chimera_lt: WHERE id in (334050); # a_ferocious_chimera 70
UPDATE npc_types SET loottable_id = :riftseekers_a_ferocious_feran_lt: WHERE id in (334051); # a_ferocious_feran 70
UPDATE npc_types SET loottable_id = :riftseekers_a_fire_construct_lt: WHERE id in (334086); # a_fire_construct 75
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidin_crystal_lt: WHERE id in (334110); # a_gelidin_crystal 75
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_deathfreeze_lt: WHERE id in (334031); # a_gelidran_deathfreeze 71
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_flamefreeze_lt: WHERE id in (334016); # a_gelidran_flamefreeze 71
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_frostblade_lt: WHERE id in (334018, 334023); # a_gelidran_frostblade 71
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_frostmaster_lt: WHERE id in (334074); # a_gelidran_frostmaster 72
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_guard_lt: WHERE id in (334030); # a_gelidran_guard 72
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_hailbringer_lt: WHERE id in (334080); # a_gelidran_hailbringer 72
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_icedagger_lt: WHERE id in (334017, 334077); # a_gelidran_icedagger 71
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_icemender_lt: WHERE id in (334025); # a_gelidran_icemender 72
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_iceshadow_lt: WHERE id in (334019, 334024); # a_gelidran_iceshadow 71
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_iceskin_lt: WHERE id in (334026, 334029); # a_gelidran_iceskin 72
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_icespinnder_lt: WHERE id in (334028); # a_gelidran_icespinnder 71
UPDATE npc_types SET loottable_id = :riftseekers_a_gelidran_researcher_lt: WHERE id in (334052); # a_gelidran_researcher 72
UPDATE npc_types SET loottable_id = :riftseekers_a_girplan_geomancer_lt: WHERE id in (334059, 334075); # a_girplan_geomancer 71
UPDATE npc_types SET loottable_id = :riftseekers_a_girplan_stonecrafter_lt: WHERE id in (334062, 334065); # a_girplan_stonecrafter 72
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_cinderhealer_lt: WHERE id in (334032); # a_pyrilen_cinderhealer 71
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_fireblade_lt: WHERE id in (334003, 334005); # a_pyrilen_fireblade 72
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_firecharmer_lt: WHERE id in (334010); # a_pyrilen_firecharmer 71
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_firedancer_lt: WHERE id in (334082); # a_pyrilen_firedancer 72
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_flamedouser_lt: WHERE id in (334054); # a_pyrilen_flamedouser 72
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_flamemistress_lt: WHERE id in (334055); # a_pyrilen_flamemistress 71
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_flameshard_lt: WHERE id in (334004, 334027); # a_pyrilen_flameshard 71
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_guard_lt: WHERE id in (334000); # a_pyrilen_guard 72
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_sirenscorcher_lt: WHERE id in (334072); # a_pyrilen_sirenscorcher 72
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_slayfire_lt: WHERE id in (334008, 334011); # a_pyrilen_slayfire 72
UPDATE npc_types SET loottable_id = :riftseekers_a_pyrilen_spinesinge_lt: WHERE id in (334001, 334006); # a_pyrilen_spinesinge 72
UPDATE npc_types SET loottable_id = :riftseekers_a_raging_chimera_lt: WHERE id in (334085); # a_raging_chimera 72
UPDATE npc_types SET loottable_id = :riftseekers_a_snarling_feran_lt: WHERE id in (334094); # a_snarling_feran 72
UPDATE npc_types SET loottable_id = :riftseekers_cyrec_the_arcane_lt: WHERE id in (334109); # Cyrec_the_Arcane 74
UPDATE npc_types SET loottable_id = :riftseekers_pyronicassault_lt: WHERE id in (334107); # PyronicAssault 71
UPDATE npc_types SET loottable_id = :riftseekers_taromani_lt: WHERE id in (334053); # Taromani 80
