INSERT INTO loottable(name) VALUES('cobaltscar_azureake'); # :cobaltscar_azureake_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_bulthar_herdleader'); # :cobaltscar_a_bulthar_herdleader_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_makulazs_warder'); # :cobaltscar_makulazs_warder_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_yvolcarn'); # :cobaltscar_yvolcarn_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_an_othmir_pup'); # :cobaltscar_an_othmir_pup_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_an_othmir_shaman'); # :cobaltscar_an_othmir_shaman_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_an_othmir_warrior'); # :cobaltscar_an_othmir_warrior_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_an_outcast_siren'); # :cobaltscar_an_outcast_siren_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_bulthar'); # :cobaltscar_a_bulthar_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_cobalt_drake'); # :cobaltscar_a_cobalt_drake_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_cobalt_trigger'); # :cobaltscar_a_cobalt_trigger_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_coldwater_barracuda'); # :cobaltscar_a_coldwater_barracuda_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_haunted_seachest'); # :cobaltscar_a_haunted_seachest_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_shark'); # :cobaltscar_a_shark_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_shellfish_collector'); # :cobaltscar_a_shellfish_collector_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_siren_enchantress'); # :cobaltscar_a_siren_enchantress_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_siren_enticer'); # :cobaltscar_a_siren_enticer_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_siren_seductress'); # :cobaltscar_a_siren_seductress_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_a_wyvern'); # :cobaltscar_a_wyvern_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_bloogy_shellcracker'); # :cobaltscar_bloogy_shellcracker_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_blumblum_swigwater'); # :cobaltscar_blumblum_swigwater_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_bungre_crawcrusher'); # :cobaltscar_bungre_crawcrusher_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_cedrick'); # :cobaltscar_cedrick_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_chief_kalan'); # :cobaltscar_chief_kalan_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_darting_shark'); # :cobaltscar_darting_shark_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_feeder_shark'); # :cobaltscar_feeder_shark_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_gekn'); # :cobaltscar_gekn_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_gnashing_killer_shark'); # :cobaltscar_gnashing_killer_shark_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_high_priest_margle'); # :cobaltscar_high_priest_margle_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_jabantik'); # :cobaltscar_jabantik_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_jabarn'); # :cobaltscar_jabarn_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_kelorekdar'); # :cobaltscar_kelorekdar_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_kenn'); # :cobaltscar_kenn_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_lasarn'); # :cobaltscar_lasarn_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_qarrgy_scallopgobbler'); # :cobaltscar_qarrgy_scallopgobbler_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_tiknonmanin'); # :cobaltscar_tiknonmanin_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_vabaner'); # :cobaltscar_vabaner_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_vobanab'); # :cobaltscar_vobanab_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_yoppa_greenthumb'); # :cobaltscar_yoppa_greenthumb_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_zarn'); # :cobaltscar_zarn_lt:
INSERT INTO loottable(name) VALUES('cobaltscar_zartik'); # :cobaltscar_zartik_lt:
