INSERT INTO loottable(name) VALUES('eastwastes_an_egg_hunter'); # :eastwastes_an_egg_hunter_lt:
INSERT INTO loottable(name) VALUES('eastwastes_an_egg_stealing_bunny'); # :eastwastes_an_egg_stealing_bunny_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_bunny_hawk'); # :eastwastes_a_bunny_hawk_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rabbit_flesh_eater'); # :eastwastes_a_rabbit_flesh_eater_lt:
INSERT INTO loottable(name) VALUES('eastwastes_bunny_napping_rygorr'); # :eastwastes_bunny_napping_rygorr_lt:
INSERT INTO loottable(name) VALUES('eastwastes_captain_berradin'); # :eastwastes_captain_berradin_lt:
INSERT INTO loottable(name) VALUES('eastwastes_chief_rygorr'); # :eastwastes_chief_rygorr_lt:
INSERT INTO loottable(name) VALUES('eastwastes_garadain_glacierbane'); # :eastwastes_garadain_glacierbane_lt:
INSERT INTO loottable(name) VALUES('eastwastes_garadain_glacierbane_'); # :eastwastes_garadain_glacierbane__lt:
INSERT INTO loottable(name) VALUES('eastwastes_peffin_ambersnow'); # :eastwastes_peffin_ambersnow_lt:
INSERT INTO loottable(name) VALUES('eastwastes_ulthork_raider'); # :eastwastes_ulthork_raider_lt:
INSERT INTO loottable(name) VALUES('eastwastes_warr_trap'); # :eastwastes_warr_trap_lt:
INSERT INTO loottable(name) VALUES('eastwastes_you_stumble'); # :eastwastes_you_stumble_lt:
INSERT INTO loottable(name) VALUES('eastwastes_an_elder_snow_griffin'); # :eastwastes_an_elder_snow_griffin_lt:
INSERT INTO loottable(name) VALUES('eastwastes_an_injured_warrior'); # :eastwastes_an_injured_warrior_lt:
INSERT INTO loottable(name) VALUES('eastwastes_an_ogre_mercenary'); # :eastwastes_an_ogre_mercenary_lt:
INSERT INTO loottable(name) VALUES('eastwastes_an_oracle_of_rygorr'); # :eastwastes_an_oracle_of_rygorr_lt:
INSERT INTO loottable(name) VALUES('eastwastes_an_ulthork_hunter'); # :eastwastes_an_ulthork_hunter_lt:
INSERT INTO loottable(name) VALUES('eastwastes_an_ulthork_man_o_war'); # :eastwastes_an_ulthork_man_o_war_lt:
INSERT INTO loottable(name) VALUES('eastwastes_an_ulthork_warrior'); # :eastwastes_an_ulthork_warrior_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_blacksmith_of_rygorr'); # :eastwastes_a_blacksmith_of_rygorr_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_blizzard_dervish'); # :eastwastes_a_blizzard_dervish_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_coldain_cook'); # :eastwastes_a_coldain_cook_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_coldain_hunter'); # :eastwastes_a_coldain_hunter_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_coldain_lookout'); # :eastwastes_a_coldain_lookout_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_coldain_missionary'); # :eastwastes_a_coldain_missionary_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_coldain_skinner'); # :eastwastes_a_coldain_skinner_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_coldain_warrior'); # :eastwastes_a_coldain_warrior_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_dire_wolf'); # :eastwastes_a_dire_wolf_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_frost_giant'); # :eastwastes_a_frost_giant_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_frost_giant_captain'); # :eastwastes_a_frost_giant_captain_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_frost_giant_savage'); # :eastwastes_a_frost_giant_savage_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_frost_giant_scout'); # :eastwastes_a_frost_giant_scout_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_injured_warrior'); # :eastwastes_a_injured_warrior_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_kromrif_prison_guard'); # :eastwastes_a_kromrif_prison_guard_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_legendary_velious_dragon'); # :eastwastes_a_legendary_velious_dragon_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_manticore'); # :eastwastes_a_manticore_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_centurion'); # :eastwastes_a_rygorr_centurion_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_clan_scout'); # :eastwastes_a_rygorr_clan_scout_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_snow_trooper'); # :eastwastes_a_rygorr_snow_trooper_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_avenger'); # :eastwastes_a_rygorr_avenger_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_centurion'); # :eastwastes_a_rygorr_centurion_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_clan_lookout'); # :eastwastes_a_rygorr_clan_lookout_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_clan_scout'); # :eastwastes_a_rygorr_clan_scout_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_invader'); # :eastwastes_a_rygorr_invader_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_legionaire'); # :eastwastes_a_rygorr_legionaire_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_messenger'); # :eastwastes_a_rygorr_messenger_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_minstrel'); # :eastwastes_a_rygorr_minstrel_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_oracle'); # :eastwastes_a_rygorr_oracle_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_rygorr_prison_guard'); # :eastwastes_a_rygorr_prison_guard_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_savage_dire_wolf'); # :eastwastes_a_savage_dire_wolf_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_snow_bunny'); # :eastwastes_a_snow_bunny_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_snow_cougar'); # :eastwastes_a_snow_cougar_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_snow_dervish'); # :eastwastes_a_snow_dervish_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_snow_griffin'); # :eastwastes_a_snow_griffin_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_tundra_kodiak'); # :eastwastes_a_tundra_kodiak_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_tundra_mammoth'); # :eastwastes_a_tundra_mammoth_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_walrus'); # :eastwastes_a_walrus_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_wooly_mammoth'); # :eastwastes_a_wooly_mammoth_lt:
INSERT INTO loottable(name) VALUES('eastwastes_a_wooly_rhino'); # :eastwastes_a_wooly_rhino_lt:
INSERT INTO loottable(name) VALUES('eastwastes_bodyguard_marganel'); # :eastwastes_bodyguard_marganel_lt:
INSERT INTO loottable(name) VALUES('eastwastes_bodyguard_nergan'); # :eastwastes_bodyguard_nergan_lt:
INSERT INTO loottable(name) VALUES('eastwastes_bodyguard_persevil'); # :eastwastes_bodyguard_persevil_lt:
INSERT INTO loottable(name) VALUES('eastwastes_bodyguard_stoneberg'); # :eastwastes_bodyguard_stoneberg_lt:
INSERT INTO loottable(name) VALUES('eastwastes_boridain_glacierbane'); # :eastwastes_boridain_glacierbane_lt:
INSERT INTO loottable(name) VALUES('eastwastes_captain_berradin'); # :eastwastes_captain_berradin_lt:
INSERT INTO loottable(name) VALUES('eastwastes_captain_ulmog'); # :eastwastes_captain_ulmog_lt:
INSERT INTO loottable(name) VALUES('eastwastes_chief_rygorr'); # :eastwastes_chief_rygorr_lt:
INSERT INTO loottable(name) VALUES('eastwastes_coldain_icechipper'); # :eastwastes_coldain_icechipper_lt:
INSERT INTO loottable(name) VALUES('eastwastes_commander_bahreck'); # :eastwastes_commander_bahreck_lt:
INSERT INTO loottable(name) VALUES('eastwastes_corbin_blackwell'); # :eastwastes_corbin_blackwell_lt:
INSERT INTO loottable(name) VALUES('eastwastes_deaen_greyforge'); # :eastwastes_deaen_greyforge_lt:
INSERT INTO loottable(name) VALUES('eastwastes_disturbed_wurm'); # :eastwastes_disturbed_wurm_lt:
INSERT INTO loottable(name) VALUES('eastwastes_dobbin_crossaxe'); # :eastwastes_dobbin_crossaxe_lt:
INSERT INTO loottable(name) VALUES('eastwastes_ekelng_thunderstone'); # :eastwastes_ekelng_thunderstone_lt:
INSERT INTO loottable(name) VALUES('eastwastes_elder_snow_griffin'); # :eastwastes_elder_snow_griffin_lt:
INSERT INTO loottable(name) VALUES('eastwastes_ewph'); # :eastwastes_ewph_lt:
INSERT INTO loottable(name) VALUES('eastwastes_firbrand_the_black'); # :eastwastes_firbrand_the_black_lt:
INSERT INTO loottable(name) VALUES('eastwastes_fjloaren_icebane'); # :eastwastes_fjloaren_icebane_lt:
INSERT INTO loottable(name) VALUES('eastwastes_garadain_glacierbane'); # :eastwastes_garadain_glacierbane_lt:
INSERT INTO loottable(name) VALUES('eastwastes_garath_the_trader'); # :eastwastes_garath_the_trader_lt:
INSERT INTO loottable(name) VALUES('eastwastes_garfunkle'); # :eastwastes_garfunkle_lt:
INSERT INTO loottable(name) VALUES('eastwastes_ghrek_squatnot'); # :eastwastes_ghrek_squatnot_lt:
INSERT INTO loottable(name) VALUES('eastwastes_gloradin_coldheart'); # :eastwastes_gloradin_coldheart_lt:
INSERT INTO loottable(name) VALUES('eastwastes_icefang'); # :eastwastes_icefang_lt:
INSERT INTO loottable(name) VALUES('eastwastes_interrogator_of_rygorr'); # :eastwastes_interrogator_of_rygorr_lt:
INSERT INTO loottable(name) VALUES('eastwastes_kassel'); # :eastwastes_kassel_lt:
INSERT INTO loottable(name) VALUES('eastwastes_korrigain'); # :eastwastes_korrigain_lt:
INSERT INTO loottable(name) VALUES('eastwastes_kromriff_guardsman'); # :eastwastes_kromriff_guardsman_lt:
INSERT INTO loottable(name) VALUES('eastwastes_kromrif_commander'); # :eastwastes_kromrif_commander_lt:
INSERT INTO loottable(name) VALUES('eastwastes_kromrif_death_squad'); # :eastwastes_kromrif_death_squad_lt:
INSERT INTO loottable(name) VALUES('eastwastes_kromrif_elite'); # :eastwastes_kromrif_elite_lt:
INSERT INTO loottable(name) VALUES('eastwastes_kromrif_guard'); # :eastwastes_kromrif_guard_lt:
INSERT INTO loottable(name) VALUES('eastwastes_kromrif_prison_guard'); # :eastwastes_kromrif_prison_guard_lt:
INSERT INTO loottable(name) VALUES('eastwastes_kromrif_soldier'); # :eastwastes_kromrif_soldier_lt:
INSERT INTO loottable(name) VALUES('eastwastes_larnik_the_recluse'); # :eastwastes_larnik_the_recluse_lt:
INSERT INTO loottable(name) VALUES('eastwastes_loremaster_derrin'); # :eastwastes_loremaster_derrin_lt:
INSERT INTO loottable(name) VALUES('eastwastes_mystic_of_rygorr'); # :eastwastes_mystic_of_rygorr_lt:
INSERT INTO loottable(name) VALUES('eastwastes_nelef_the_trader'); # :eastwastes_nelef_the_trader_lt:
INSERT INTO loottable(name) VALUES('eastwastes_nubert'); # :eastwastes_nubert_lt:
INSERT INTO loottable(name) VALUES('eastwastes_oracle_of_rygorr'); # :eastwastes_oracle_of_rygorr_lt:
INSERT INTO loottable(name) VALUES('eastwastes_paladin_of_brell'); # :eastwastes_paladin_of_brell_lt:
INSERT INTO loottable(name) VALUES('eastwastes_peffin_ambersnow'); # :eastwastes_peffin_ambersnow_lt:
INSERT INTO loottable(name) VALUES('eastwastes_poxbreath_yellowfang'); # :eastwastes_poxbreath_yellowfang_lt:
INSERT INTO loottable(name) VALUES('eastwastes_priest_of_brell'); # :eastwastes_priest_of_brell_lt:
INSERT INTO loottable(name) VALUES('eastwastes_rabid_tundra_kodiak'); # :eastwastes_rabid_tundra_kodiak_lt:
INSERT INTO loottable(name) VALUES('eastwastes_ringeightcoord'); # :eastwastes_ringeightcoord_lt:
INSERT INTO loottable(name) VALUES('eastwastes_ringfivecoord'); # :eastwastes_ringfivecoord_lt:
INSERT INTO loottable(name) VALUES('eastwastes_ringfourcoord'); # :eastwastes_ringfourcoord_lt:
INSERT INTO loottable(name) VALUES('eastwastes_ringsixcoord'); # :eastwastes_ringsixcoord_lt:
INSERT INTO loottable(name) VALUES('eastwastes_rodrick_tardok'); # :eastwastes_rodrick_tardok_lt:
INSERT INTO loottable(name) VALUES('eastwastes_royal_archer'); # :eastwastes_royal_archer_lt:
INSERT INTO loottable(name) VALUES('eastwastes_royal_guard_of_the_dain'); # :eastwastes_royal_guard_of_the_dain_lt:
INSERT INTO loottable(name) VALUES('eastwastes_royal_wolven_guard'); # :eastwastes_royal_wolven_guard_lt:
INSERT INTO loottable(name) VALUES('eastwastes_rygorr_basher'); # :eastwastes_rygorr_basher_lt:
INSERT INTO loottable(name) VALUES('eastwastes_rygorr_elite'); # :eastwastes_rygorr_elite_lt:
INSERT INTO loottable(name) VALUES('eastwastes_rygorr_elite_guard'); # :eastwastes_rygorr_elite_guard_lt:
INSERT INTO loottable(name) VALUES('eastwastes_rygorr_emissary'); # :eastwastes_rygorr_emissary_lt:
INSERT INTO loottable(name) VALUES('eastwastes_scarbrow_gahruk'); # :eastwastes_scarbrow_gahruk_lt:
INSERT INTO loottable(name) VALUES('eastwastes_shhbarconv'); # :eastwastes_shhbarconv_lt:
INSERT INTO loottable(name) VALUES('eastwastes_tain_hammerfrost'); # :eastwastes_tain_hammerfrost_lt:
INSERT INTO loottable(name) VALUES('eastwastes_tanik_greskil'); # :eastwastes_tanik_greskil_lt:
INSERT INTO loottable(name) VALUES('eastwastes_the_fabled_snow_bunny'); # :eastwastes_the_fabled_snow_bunny_lt:
INSERT INTO loottable(name) VALUES('eastwastes_warden_bruke'); # :eastwastes_warden_bruke_lt:
INSERT INTO loottable(name) VALUES('eastwastes_you'); # :eastwastes_you_lt:
INSERT INTO loottable(name) VALUES('eastwastes_your'); # :eastwastes_your_lt:
INSERT INTO loottable(name) VALUES('eastwastes_you_have'); # :eastwastes_you_have_lt:
