(:frozenshadow_a_lesser_ice_shade_lt:, :rusty_ld:, 1),
(:frozenshadow_librarian_lt:, :fine_steel_ld:, 1),
(:frozenshadow_librarian_lt:, :rawhide_small_ld:, 1),
(:frozenshadow_librarian_lt:, :bronze_weapon_ld:, 1),
(:frozenshadow_a_lesser_ice_shade_lt:, :bronze_weapon_ld:, 1),
