INSERT INTO loottable(name) VALUES('frozenshadow_advisor_svartmane'); # :frozenshadow_advisor_svartmane_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_amontehepna'); # :frozenshadow_amontehepna_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_angry_chef'); # :frozenshadow_an_angry_chef_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_angry_librarian'); # :frozenshadow_an_angry_librarian_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_enraged_relative'); # :frozenshadow_an_enraged_relative_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_enraged_shadow_beast'); # :frozenshadow_an_enraged_shadow_beast_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_enraged_vampire'); # :frozenshadow_an_enraged_vampire_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_ice_shade'); # :frozenshadow_an_ice_shade_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_undead_usher'); # :frozenshadow_an_undead_usher_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_ghostly_student'); # :frozenshadow_a_ghostly_student_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_large_undead_gnoll'); # :frozenshadow_a_large_undead_gnoll_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadowbone'); # :frozenshadow_a_shadowbone_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadow_beast_cook'); # :frozenshadow_a_shadow_beast_cook_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadow_beast_guard'); # :frozenshadow_a_shadow_beast_guard_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shrouded_bat'); # :frozenshadow_a_shrouded_bat_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_skeleton_sleeper'); # :frozenshadow_a_skeleton_sleeper_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_cara_omica'); # :frozenshadow_cara_omica_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_eugie'); # :frozenshadow_eugie_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_incoherent_spirit'); # :frozenshadow_incoherent_spirit_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_maggot_infested_flesh'); # :frozenshadow_maggot_infested_flesh_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_narmak_berreka'); # :frozenshadow_narmak_berreka_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_the_fabled_cara_omica'); # :frozenshadow_the_fabled_cara_omica_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_the_fabled_head_usher'); # :frozenshadow_the_fabled_head_usher_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_the_fabled_incoherent_spirit'); # :frozenshadow_the_fabled_incoherent_spirit_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_the_fabled_maggot_infested_flesh'); # :frozenshadow_the_fabled_maggot_infested_flesh_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_the_fabled_narmak_berreka'); # :frozenshadow_the_fabled_narmak_berreka_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_the_fabled_priest_majes_medory'); # :frozenshadow_the_fabled_priest_majes_medory_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_the_fabled_tserrina_syltor'); # :frozenshadow_the_fabled_tserrina_syltor_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_the_fabled_zorglim_the_dead'); # :frozenshadow_the_fabled_zorglim_the_dead_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_the_head_usher'); # :frozenshadow_the_head_usher_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_tserrina_syltor'); # :frozenshadow_tserrina_syltor_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_uanarcel'); # :frozenshadow_uanarcel_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_vhalsera'); # :frozenshadow_vhalsera_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_voknya'); # :frozenshadow_voknya_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_xalgoti'); # :frozenshadow_xalgoti_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_zorglim_the_dead'); # :frozenshadow_zorglim_the_dead_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_ancient_mummy'); # :frozenshadow_an_ancient_mummy_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_armored_shadow'); # :frozenshadow_an_armored_shadow_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_emerald_familiar'); # :frozenshadow_an_emerald_familiar_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_enraged_vampire'); # :frozenshadow_an_enraged_vampire_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_ice_shade'); # :frozenshadow_an_ice_shade_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_icy_shade'); # :frozenshadow_an_icy_shade_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_undead_bridesmaid'); # :frozenshadow_an_undead_bridesmaid_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_undead_dancer'); # :frozenshadow_an_undead_dancer_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_an_undead_musician'); # :frozenshadow_an_undead_musician_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_blood_familiar'); # :frozenshadow_a_blood_familiar_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_crystallized_shadow_guard'); # :frozenshadow_a_crystallized_shadow_guard_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_disabled_trap'); # :frozenshadow_a_disabled_trap_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_distant_voice'); # :frozenshadow_a_distant_voice_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_fading_shadow_guard'); # :frozenshadow_a_fading_shadow_guard_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_frost_familiar'); # :frozenshadow_a_frost_familiar_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_ghostly_scholar'); # :frozenshadow_a_ghostly_scholar_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_ghostly_student'); # :frozenshadow_a_ghostly_student_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_ghostly_teacher'); # :frozenshadow_a_ghostly_teacher_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_golem_usher'); # :frozenshadow_a_golem_usher_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_haunting_voice'); # :frozenshadow_a_haunting_voice_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_lesser_ice_shade'); # :frozenshadow_a_lesser_ice_shade_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shaded_torch'); # :frozenshadow_a_shaded_torch_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadow'); # :frozenshadow_a_shadow_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadowbone'); # :frozenshadow_a_shadowbone_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadowed_banner'); # :frozenshadow_a_shadowed_banner_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadow_beast'); # :frozenshadow_a_shadow_beast_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadow_beast_cook'); # :frozenshadow_a_shadow_beast_cook_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadow_beast_guard'); # :frozenshadow_a_shadow_beast_guard_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadow_beast_necromancer'); # :frozenshadow_a_shadow_beast_necromancer_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadow_beast_servant'); # :frozenshadow_a_shadow_beast_servant_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shadow_familiar'); # :frozenshadow_a_shadow_familiar_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_shrouded_bat'); # :frozenshadow_a_shrouded_bat_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_skeletal_hand'); # :frozenshadow_a_skeletal_hand_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_skeleton_sleeper'); # :frozenshadow_a_skeleton_sleeper_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_statue'); # :frozenshadow_a_statue_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_zombie_butler'); # :frozenshadow_a_zombie_butler_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_a_zombie_maid'); # :frozenshadow_a_zombie_maid_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_daman'); # :frozenshadow_daman_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_dark_huntress'); # :frozenshadow_dark_huntress_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_eugie'); # :frozenshadow_eugie_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_incoherent_spirit'); # :frozenshadow_incoherent_spirit_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_isopca'); # :frozenshadow_isopca_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_kabaner'); # :frozenshadow_kabaner_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_lerty'); # :frozenshadow_lerty_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_librarian'); # :frozenshadow_librarian_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_librarian_assistant'); # :frozenshadow_librarian_assistant_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_lucid_spirit_of_abrams'); # :frozenshadow_lucid_spirit_of_abrams_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_mirror_reflection'); # :frozenshadow_mirror_reflection_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_nosja'); # :frozenshadow_nosja_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_oozing_flesh'); # :frozenshadow_oozing_flesh_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_otdd'); # :frozenshadow_otdd_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_pelpa'); # :frozenshadow_pelpa_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_priest_majes_medory'); # :frozenshadow_priest_majes_medory_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_tihgren'); # :frozenshadow_tihgren_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_uenlarc'); # :frozenshadow_uenlarc_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_varjie'); # :frozenshadow_varjie_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_vyakna'); # :frozenshadow_vyakna_lt:
INSERT INTO loottable(name) VALUES('frozenshadow_you_'); # :frozenshadow_you__lt:
