UPDATE npc_types SET loottable_id = :greatdivide_an_angry_shardwurm_lt: WHERE id in (118164); # #an_angry_shardwurm 40
UPDATE npc_types SET loottable_id = :greatdivide_coldain_war_wolf_lt: WHERE id in (118103); # #Coldain_War_Wolf 35
UPDATE npc_types SET loottable_id = :greatdivide_drakkel_blood_wolf_lt: WHERE id in (118122); # #Drakkel_Blood_Wolf 37
UPDATE npc_types SET loottable_id = :greatdivide_fergul_frostsky_lt: WHERE id in (118207); # #Fergul_Frostsky 40
UPDATE npc_types SET loottable_id = :greatdivide_gorul_longshanks_lt: WHERE id in (118117); # #Gorul_Longshanks 47
UPDATE npc_types SET loottable_id = :greatdivide_gralk_dwarfkiller_lt: WHERE id in (118208); # #Gralk_Dwarfkiller 40
UPDATE npc_types SET loottable_id = :greatdivide_icetooth_lt: WHERE id in (118119); # #Icetooth 38
UPDATE npc_types SET loottable_id = :greatdivide_murdrick_tardok_lt: WHERE id in (118061); # #Murdrick_Tardok 50
UPDATE npc_types SET loottable_id = :greatdivide_narandi_the_wretched_lt: WHERE id in (118145); # #Narandi_the_Wretched 65
UPDATE npc_types SET loottable_id = :greatdivide_relaypoint_lt: WHERE id in (118147); # #Relaypoint 1
UPDATE npc_types SET loottable_id = :greatdivide_shardtooth_lt: WHERE id in (118107); # #Shardtooth 42
UPDATE npc_types SET loottable_id = :greatdivide_the_fabled_blizzent_lt: WHERE id in (118200); # #The_Fabled_Blizzent 55
UPDATE npc_types SET loottable_id = :greatdivide_the_fabled_gorul_longshanks_lt: WHERE id in (118201); # #The_Fabled_Gorul_Longshanks 55
UPDATE npc_types SET loottable_id = :greatdivide_the_fabled_icetooth_lt: WHERE id in (118202); # #The_Fabled_Icetooth 55
UPDATE npc_types SET loottable_id = :greatdivide_the_fabled_shardtooth_lt: WHERE id in (118203); # #The_Fabled_Shardtooth 50
UPDATE npc_types SET loottable_id = :greatdivide_the_fabled_shardwurm_broodmother_lt: WHERE id in (118204); # #The_Fabled_shardwurm_broodmother 60
UPDATE npc_types SET loottable_id = :greatdivide_the_fabled_shardwurm_matriarch_lt: WHERE id in (118205); # #The_Fabled_shardwurm_matriarch 55
UPDATE npc_types SET loottable_id = :greatdivide_war_god_lt: WHERE id in (118142); # #War_God 1
UPDATE npc_types SET loottable_id = :greatdivide_war_slave_lt: WHERE id in (118159); # #War_Slave 1
UPDATE npc_types SET loottable_id = :greatdivide_yaka_razorhoof_lt: WHERE id in (118109); # #Yaka_Razorhoof 36
UPDATE npc_types SET loottable_id = :greatdivide_an_ancient_shardwurm_lt: WHERE id in (118018, 118035, 118037, 118038, 118095, 118099, 118118); # an_ancient_shardwurm 37
UPDATE npc_types SET loottable_id = :greatdivide_an_elder_shardwurm_lt: WHERE id in (118019, 118020, 118021, 118043, 118044, 118105, 118111); # an_elder_shardwurm 36
UPDATE npc_types SET loottable_id = :greatdivide_an_expedition_guard_lt: WHERE id in (118070); # an_expedition_guard 50
UPDATE npc_types SET loottable_id = :greatdivide_awaitkromwin_lt: WHERE id in (118124); # AwaitKromWin 1
UPDATE npc_types SET loottable_id = :greatdivide_a_coldain_miner_lt: WHERE id in (118068); # a_coldain_miner 35
UPDATE npc_types SET loottable_id = :greatdivide_a_coldain_tracking_wolf_lt: WHERE id in (118059, 118063, 118064, 118101, 118113, 118115); # a_coldain_tracking_wolf 29
UPDATE npc_types SET loottable_id = :greatdivide_a_coldain_wolfmaster_lt: WHERE id in (118022, 118057, 118062, 118071, 118093, 118098, 118114); # a_coldain_wolfmaster 30
UPDATE npc_types SET loottable_id = :greatdivide_a_crystaline_shardwurm_lt: WHERE id in (118051); # a_crystaline_shardwurm 40
UPDATE npc_types SET loottable_id = :greatdivide_a_drakkel_dire_wolf_lt: WHERE id in (118016, 118055, 118092, 118100, 118112, 118002, 118006, 118014); # a_drakkel_dire_wolf 32
UPDATE npc_types SET loottable_id = :greatdivide_a_feral_cave_kodiak_lt: WHERE id in (118046, 118049, 118010); # a_feral_cave_kodiak 31
UPDATE npc_types SET loottable_id = :greatdivide_a_ferocious_cave_kodiak_lt: WHERE id in (118031, 118042, 118045); # a_ferocious_cave_kodiak 34
UPDATE npc_types SET loottable_id = :greatdivide_a_frost_giant_berserker_lt: WHERE id in (118056, 118009, 118013); # a_frost_giant_berserker 39
UPDATE npc_types SET loottable_id = :greatdivide_a_frost_giant_elite_lt: WHERE id in (118050, 118060, 118012); # a_frost_giant_elite 44
UPDATE npc_types SET loottable_id = :greatdivide_a_frost_giant_scout_lt: WHERE id in (118001, 118007, 118015); # a_frost_giant_scout 36
UPDATE npc_types SET loottable_id = :greatdivide_a_furious_tizmak_warrior_lt: WHERE id in (118017, 118023, 118024); # a_furious_tizmak_warrior 31
UPDATE npc_types SET loottable_id = :greatdivide_a_guardian_shardwurm_lt: WHERE id in (118036); # a_guardian_shardwurm 38
UPDATE npc_types SET loottable_id = :greatdivide_a_mystic_voice_lt: WHERE id in (118165); # A_Mystic_Voice 50
UPDATE npc_types SET loottable_id = :greatdivide_a_savage_cave_kodiak_lt: WHERE id in (118032, 118047, 118048); # a_savage_cave_kodiak 32
UPDATE npc_types SET loottable_id = :greatdivide_a_tizmak_augur_lt: WHERE id in (118029, 118034, 118004); # a_tizmak_augur 29
UPDATE npc_types SET loottable_id = :greatdivide_a_tizmak_champion_lt: WHERE id in (118003, 118005, 118008); # a_tizmak_champion 29
UPDATE npc_types SET loottable_id = :greatdivide_a_tizmak_shaman_lt: WHERE id in (118085, 118089, 118094); # a_tizmak_shaman 27
UPDATE npc_types SET loottable_id = :greatdivide_a_tizmak_spiritcaller_lt: WHERE id in (118028, 118030, 118108); # a_tizmak_spiritcaller 31
UPDATE npc_types SET loottable_id = :greatdivide_a_tizmak_warrior_lt: WHERE id in (118025, 118033, 118000); # a_tizmak_warrior 27
UPDATE npc_types SET loottable_id = :greatdivide_a_tower_guard_lt: WHERE id in (118083, 118084); # a_tower_guard 55
UPDATE npc_types SET loottable_id = :greatdivide_a_velium_miner_lt: WHERE id in (118069); # a_velium_miner 35
UPDATE npc_types SET loottable_id = :greatdivide_a_young_shardwurm_lt: WHERE id in (118039, 118041, 118052, 118053, 118054, 118096, 118097, 118102, 118116); # a_young_shardwurm 33
UPDATE npc_types SET loottable_id = :greatdivide_bekerak_coldbones_lt: WHERE id in (118011); # Bekerak_Coldbones 35
UPDATE npc_types SET loottable_id = :greatdivide_blizzent_lt: WHERE id in (118110); # Blizzent 45
UPDATE npc_types SET loottable_id = :greatdivide_bloodmaw_lt: WHERE id in (118027); # Bloodmaw 20
UPDATE npc_types SET loottable_id = :greatdivide_bloody_gnome_captive_lt: WHERE id in (118026); # bloody_gnome_captive 1
UPDATE npc_types SET loottable_id = :greatdivide_captain_stonefist_lt: WHERE id in (118082); # Captain_Stonefist 65
UPDATE npc_types SET loottable_id = :greatdivide_churn_the_axeman_lt: WHERE id in (118169); # Churn_the_Axeman 45
UPDATE npc_types SET loottable_id = :greatdivide_clock_lt: WHERE id in (118127); # Clock 1
UPDATE npc_types SET loottable_id = :greatdivide_coldainwin_lt: WHERE id in (118146); # ColdainWin 1
UPDATE npc_types SET loottable_id = :greatdivide_coldain_smuggler_lt: WHERE id in (118106); # Coldain_Smuggler 40
UPDATE npc_types SET loottable_id = :greatdivide_corbin_blackwell_lt: WHERE id in (118171); # Corbin_Blackwell 41
UPDATE npc_types SET loottable_id = :greatdivide_davin_fatfist_lt: WHERE id in (118077); # Davin_Fatfist 50
UPDATE npc_types SET loottable_id = :greatdivide_dialogueman_lt: WHERE id in (118121); # Dialogueman 1
UPDATE npc_types SET loottable_id = :greatdivide_die_lt: WHERE id in (118133); # die 1
UPDATE npc_types SET loottable_id = :greatdivide_dobbin_crossaxe_lt: WHERE id in (118170); # Dobbin_Crossaxe 42
UPDATE npc_types SET loottable_id = :greatdivide_extraxbows_lt: WHERE id in (118125); # ExtraXbows 1
UPDATE npc_types SET loottable_id = :greatdivide_fall_out_lt: WHERE id in (118144); # Fall_Out 1
UPDATE npc_types SET loottable_id = :greatdivide_fergul_frostsky_lt: WHERE id in (118090); # Fergul_Frostsky 40
UPDATE npc_types SET loottable_id = :greatdivide_fgsowngd_lt: WHERE id in (118163); # FGsOwnGD 1
UPDATE npc_types SET loottable_id = :greatdivide_fomgrut_borkel_lt: WHERE id in (118072); # Fomgrut_Borkel 50
UPDATE npc_types SET loottable_id = :greatdivide_garadain_glacierbane_lt: WHERE id in (118168); # Garadain_Glacierbane 42
UPDATE npc_types SET loottable_id = :greatdivide_gavon_morant_lt: WHERE id in (118206); # Gavon_Morant 65
UPDATE npc_types SET loottable_id = :greatdivide_gerton_dumkin_lt: WHERE id in (118076); # Gerton_Dumkin 50
UPDATE npc_types SET loottable_id = :greatdivide_gnomish_captive_lt: WHERE id in (118154); # gnomish_captive 1
UPDATE npc_types SET loottable_id = :greatdivide_gnomish_deserter_lt: WHERE id in (118078); # gnomish_deserter 60
UPDATE npc_types SET loottable_id = :greatdivide_gralk_dwarfkiller_lt: WHERE id in (118091); # Gralk_Dwarfkiller 40
UPDATE npc_types SET loottable_id = :greatdivide_guard_korik_lt: WHERE id in (118081); # Guard_Korik 55
UPDATE npc_types SET loottable_id = :greatdivide_guard_krag_lt: WHERE id in (118080); # Guard_Krag 55
UPDATE npc_types SET loottable_id = :greatdivide_herga_ratgur_lt: WHERE id in (118074); # Herga_Ratgur 50
UPDATE npc_types SET loottable_id = :greatdivide_high_priest_maltan_lt: WHERE id in (118211); # High_Priest_Maltan 68
UPDATE npc_types SET loottable_id = :greatdivide_high_priest_of_zek_lt: WHERE id in (118132); # High_Priest_of_Zek 58
UPDATE npc_types SET loottable_id = :greatdivide_invischurn_lt: WHERE id in (118143); # InvisChurn 1
UPDATE npc_types SET loottable_id = :greatdivide_invisdob_lt: WHERE id in (118148); # InvisDob 1
UPDATE npc_types SET loottable_id = :greatdivide_invisgar_lt: WHERE id in (118128); # InvisGar 1
UPDATE npc_types SET loottable_id = :greatdivide_inviskar_lt: WHERE id in (118162); # InvisKar 1
UPDATE npc_types SET loottable_id = :greatdivide_invisman_fuse_lt: WHERE id in (118123); # Invisman_Fuse 1
UPDATE npc_types SET loottable_id = :greatdivide_kardakor_lt: WHERE id in (118087); # Kardakor 60
UPDATE npc_types SET loottable_id = :greatdivide_kargin_the_archer_lt: WHERE id in (118172); # Kargin_the_Archer 45
UPDATE npc_types SET loottable_id = :greatdivide_korf_brokenhammer_lt: WHERE id in (118066); # Korf_Brokenhammer 55
UPDATE npc_types SET loottable_id = :greatdivide_kromrif_captain_lt: WHERE id in (118130); # Kromrif_Captain 52
UPDATE npc_types SET loottable_id = :greatdivide_kromrif_general_lt: WHERE id in (118120); # Kromrif_General 56
UPDATE npc_types SET loottable_id = :greatdivide_kromrif_high_priest_lt: WHERE id in (118210); # Kromrif_High_Priest 60
UPDATE npc_types SET loottable_id = :greatdivide_kromrif_priest_lt: WHERE id in (118209); # Kromrif_Priest 53
UPDATE npc_types SET loottable_id = :greatdivide_kromrif_recruit_lt: WHERE id in (118160); # Kromrif_Recruit 48
UPDATE npc_types SET loottable_id = :greatdivide_kromrif_spearman_lt: WHERE id in (118138); # Kromrif_Spearman 52
UPDATE npc_types SET loottable_id = :greatdivide_kromrif_veteran_lt: WHERE id in (118156); # Kromrif_Veteran 58
UPDATE npc_types SET loottable_id = :greatdivide_kromrif_warlord_lt: WHERE id in (118158); # Kromrif_Warlord 60
UPDATE npc_types SET loottable_id = :greatdivide_kromrif_warrior_lt: WHERE id in (118150); # Kromrif_Warrior 53
UPDATE npc_types SET loottable_id = :greatdivide_laima_ratgur_lt: WHERE id in (118073); # Laima_Ratgur 50
UPDATE npc_types SET loottable_id = :greatdivide_lapker_geynion_lt: WHERE id in (118075); # Lapker_Geynion 50
UPDATE npc_types SET loottable_id = :greatdivide_miner_animator_lt: WHERE id in (118136); # miner_animator 1
UPDATE npc_types SET loottable_id = :greatdivide_narandi_the_wretched_lt: WHERE id in (118126); # Narandi_the_Wretched 1
UPDATE npc_types SET loottable_id = :greatdivide_nexus_scion_lt: WHERE id in (118086); # Nexus_Scion 66
UPDATE npc_types SET loottable_id = :greatdivide_priest_of_zek_lt: WHERE id in (118155); # Priest_of_Zek 53
UPDATE npc_types SET loottable_id = :greatdivide_relik_lt: WHERE id in (118065); # Relik 40
UPDATE npc_types SET loottable_id = :greatdivide_ringtenmaster_lt: WHERE id in (118173); # ringtenmaster 80
UPDATE npc_types SET loottable_id = :greatdivide_ringtenphaseone_lt: WHERE id in (118174); # ringtenphaseone 80
UPDATE npc_types SET loottable_id = :greatdivide_ringtenphasethree_lt: WHERE id in (118176); # ringtenphasethree 80
UPDATE npc_types SET loottable_id = :greatdivide_ringtenphasetwo_lt: WHERE id in (118175); # ringtenphasetwo 80
UPDATE npc_types SET loottable_id = :greatdivide_royal_archer_lt: WHERE id in (118141); # Royal_Archer 36
UPDATE npc_types SET loottable_id = :greatdivide_royal_axeman_lt: WHERE id in (118129, 118152, 118153, 118161); # Royal_Axeman 42
UPDATE npc_types SET loottable_id = :greatdivide_royal_cleric_lt: WHERE id in (118135, 118151); # Royal_Cleric 43
UPDATE npc_types SET loottable_id = :greatdivide_royal_soldier_lt: WHERE id in (118131, 118134, 118140, 118149); # royal_soldier 42
UPDATE npc_types SET loottable_id = :greatdivide_seneschal_aldikar_lt: WHERE id in (118166); # Seneschal_Aldikar 65
UPDATE npc_types SET loottable_id = :greatdivide_sentry_badain_lt: WHERE id in (118067); # Sentry_Badain 55
UPDATE npc_types SET loottable_id = :greatdivide_shardwurm_broodmother_lt: WHERE id in (118040); # shardwurm_broodmother 50
UPDATE npc_types SET loottable_id = :greatdivide_shardwurm_matriarch_lt: WHERE id in (118104); # shardwurm_matriarch 45
UPDATE npc_types SET loottable_id = :greatdivide_taskmaster_abyott_lt: WHERE id in (118088); # Taskmaster_Abyott 62
UPDATE npc_types SET loottable_id = :greatdivide_velious_spires_lt: WHERE id in (118058); # Velious_Spires 50
UPDATE npc_types SET loottable_id = :greatdivide_vluudeen_lt: WHERE id in (118157); # Vluudeen 49
UPDATE npc_types SET loottable_id = :greatdivide_vores_the_hunter_lt: WHERE id in (118079); # Vores_the_Hunter 60
UPDATE npc_types SET loottable_id = :greatdivide_war_lt: WHERE id in (118137); # War 1
UPDATE npc_types SET loottable_id = :greatdivide_waveone_lt: WHERE id in (118139); # WaveOne 1
UPDATE npc_types SET loottable_id = :greatdivide_zrelik_the_scout_lt: WHERE id in (118167); # Zrelik_the_Scout 45
