INSERT INTO loottable(name) VALUES('sirens_mistress_of_the_darkwater'); # :sirens_mistress_of_the_darkwater_lt:
INSERT INTO loottable(name) VALUES('sirens_an_enthralled_ulthork'); # :sirens_an_enthralled_ulthork_lt:
INSERT INTO loottable(name) VALUES('sirens_a_deadly_siren'); # :sirens_a_deadly_siren_lt:
INSERT INTO loottable(name) VALUES('sirens_a_massive_manatee'); # :sirens_a_massive_manatee_lt:
INSERT INTO loottable(name) VALUES('sirens_a_rampaging_ulthork'); # :sirens_a_rampaging_ulthork_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_coercer'); # :sirens_a_siren_coercer_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_seductress'); # :sirens_a_siren_seductress_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_sorceress'); # :sirens_a_siren_sorceress_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_temptress'); # :sirens_a_siren_temptress_lt:
INSERT INTO loottable(name) VALUES('sirens_faleniel_of_darkwater'); # :sirens_faleniel_of_darkwater_lt:
INSERT INTO loottable(name) VALUES('sirens_helsia_mindreaver'); # :sirens_helsia_mindreaver_lt:
INSERT INTO loottable(name) VALUES('sirens_high_priestess_sercema'); # :sirens_high_priestess_sercema_lt:
INSERT INTO loottable(name) VALUES('sirens_mistress_latazura'); # :sirens_mistress_latazura_lt:
INSERT INTO loottable(name) VALUES('sirens_mistress_of_the_darkwater'); # :sirens_mistress_of_the_darkwater_lt:
INSERT INTO loottable(name) VALUES('sirens_shimmering_sea_spirit'); # :sirens_shimmering_sea_spirit_lt:
INSERT INTO loottable(name) VALUES('sirens_ulth_the_enraged'); # :sirens_ulth_the_enraged_lt:
INSERT INTO loottable(name) VALUES('sirens_ailing_walrus'); # :sirens_ailing_walrus_lt:
INSERT INTO loottable(name) VALUES('sirens_an_alluring_siren'); # :sirens_an_alluring_siren_lt:
INSERT INTO loottable(name) VALUES('sirens_an_enthralled_bulthar'); # :sirens_an_enthralled_bulthar_lt:
INSERT INTO loottable(name) VALUES('sirens_an_enthralled_molkor'); # :sirens_an_enthralled_molkor_lt:
INSERT INTO loottable(name) VALUES('sirens_an_icy_servant'); # :sirens_an_icy_servant_lt:
INSERT INTO loottable(name) VALUES('sirens_a_coldspine_seahorse'); # :sirens_a_coldspine_seahorse_lt:
INSERT INTO loottable(name) VALUES('sirens_a_massive_walrus'); # :sirens_a_massive_walrus_lt:
INSERT INTO loottable(name) VALUES('sirens_a_neriad_maiden'); # :sirens_a_neriad_maiden_lt:
INSERT INTO loottable(name) VALUES('sirens_a_neriad_mistress'); # :sirens_a_neriad_mistress_lt:
INSERT INTO loottable(name) VALUES('sirens_a_neriad_sea_princess'); # :sirens_a_neriad_sea_princess_lt:
INSERT INTO loottable(name) VALUES('sirens_a_neriad_weaver'); # :sirens_a_neriad_weaver_lt:
INSERT INTO loottable(name) VALUES('sirens_a_servant_manatee'); # :sirens_a_servant_manatee_lt:
INSERT INTO loottable(name) VALUES('sirens_a_servant_sea_elephant'); # :sirens_a_servant_sea_elephant_lt:
INSERT INTO loottable(name) VALUES('sirens_a_servant_walrus'); # :sirens_a_servant_walrus_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_beguiler'); # :sirens_a_siren_beguiler_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_enchantress'); # :sirens_a_siren_enchantress_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_enticer'); # :sirens_a_siren_enticer_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_myrmidon'); # :sirens_a_siren_myrmidon_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_priestess'); # :sirens_a_siren_priestess_lt:
INSERT INTO loottable(name) VALUES('sirens_a_siren_templar'); # :sirens_a_siren_templar_lt:
INSERT INTO loottable(name) VALUES('sirens_a_swordfish'); # :sirens_a_swordfish_lt:
INSERT INTO loottable(name) VALUES('sirens_a_twitching_swordfish'); # :sirens_a_twitching_swordfish_lt:
INSERT INTO loottable(name) VALUES('sirens_a_walrus_servant'); # :sirens_a_walrus_servant_lt:
INSERT INTO loottable(name) VALUES('sirens_a_watery_servant'); # :sirens_a_watery_servant_lt:
INSERT INTO loottable(name) VALUES('sirens_elna_kelpweaver'); # :sirens_elna_kelpweaver_lt:
INSERT INTO loottable(name) VALUES('sirens_fellspine'); # :sirens_fellspine_lt:
INSERT INTO loottable(name) VALUES('sirens_high_priestess_sercema'); # :sirens_high_priestess_sercema_lt:
INSERT INTO loottable(name) VALUES('sirens_ravaging_tsunami_elemental'); # :sirens_ravaging_tsunami_elemental_lt:
INSERT INTO loottable(name) VALUES('sirens_the_behemoth'); # :sirens_the_behemoth_lt:
INSERT INTO loottable(name) VALUES('sirens_wygrish'); # :sirens_wygrish_lt:
