INSERT INTO loottable(name) VALUES('sleeper_a_foreboding_sentry'); # :sleeper_a_foreboding_sentry_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_foreboding_sentry1'); # :sleeper_a_foreboding_sentry1_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_foreboding_sentry2'); # :sleeper_a_foreboding_sentry2_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_foreboding_sentry3'); # :sleeper_a_foreboding_sentry3_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_foreboding_sentry4'); # :sleeper_a_foreboding_sentry4_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_foreboding_sentry5'); # :sleeper_a_foreboding_sentry5_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_foreboding_sentry6'); # :sleeper_a_foreboding_sentry6_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_foreboding_sentry7'); # :sleeper_a_foreboding_sentry7_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_foreboding_sentry8'); # :sleeper_a_foreboding_sentry8_lt:
INSERT INTO loottable(name) VALUES('sleeper_bittles_the_lost'); # :sleeper_bittles_the_lost_lt:
INSERT INTO loottable(name) VALUES('sleeper_drakeen_apprentice'); # :sleeper_drakeen_apprentice_lt:
INSERT INTO loottable(name) VALUES('sleeper_drakeen_protector'); # :sleeper_drakeen_protector_lt:
INSERT INTO loottable(name) VALUES('sleeper_ferrin_qnyil'); # :sleeper_ferrin_qnyil_lt:
INSERT INTO loottable(name) VALUES('sleeper_hraashna_the_warder'); # :sleeper_hraashna_the_warder_lt:
INSERT INTO loottable(name) VALUES('sleeper_jobana_duata'); # :sleeper_jobana_duata_lt:
INSERT INTO loottable(name) VALUES('sleeper_jonas_levlellen'); # :sleeper_jonas_levlellen_lt:
INSERT INTO loottable(name) VALUES('sleeper_kal_tven'); # :sleeper_kal_tven_lt:
INSERT INTO loottable(name) VALUES('sleeper_kerafyrm'); # :sleeper_kerafyrm_lt:
INSERT INTO loottable(name) VALUES('sleeper_kerafyrm_'); # :sleeper_kerafyrm__lt:
INSERT INTO loottable(name) VALUES('sleeper_kildrukaun_the_ancient'); # :sleeper_kildrukaun_the_ancient_lt:
INSERT INTO loottable(name) VALUES('sleeper_master_of_the_guard'); # :sleeper_master_of_the_guard_lt:
INSERT INTO loottable(name) VALUES('sleeper_nanzata_the_warder'); # :sleeper_nanzata_the_warder_lt:
INSERT INTO loottable(name) VALUES('sleeper_remmen_the_short'); # :sleeper_remmen_the_short_lt:
INSERT INTO loottable(name) VALUES('sleeper_sorren_dentral'); # :sleeper_sorren_dentral_lt:
INSERT INTO loottable(name) VALUES('sleeper_the_final_arbiter'); # :sleeper_the_final_arbiter_lt:
INSERT INTO loottable(name) VALUES('sleeper_the_progenitor'); # :sleeper_the_progenitor_lt:
INSERT INTO loottable(name) VALUES('sleeper_the_sleeper'); # :sleeper_the_sleeper_lt:
INSERT INTO loottable(name) VALUES('sleeper_tjudawos_the_ancient'); # :sleeper_tjudawos_the_ancient_lt:
INSERT INTO loottable(name) VALUES('sleeper_tukaarak_the_warder'); # :sleeper_tukaarak_the_warder_lt:
INSERT INTO loottable(name) VALUES('sleeper_ventani_the_warder'); # :sleeper_ventani_the_warder_lt:
INSERT INTO loottable(name) VALUES('sleeper_vyskudra_the_ancient'); # :sleeper_vyskudra_the_ancient_lt:
INSERT INTO loottable(name) VALUES('sleeper_zeixshi-kar_the_ancient'); # :sleeper_zeixshi-kar_the_ancient_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_aged_caretaker'); # :sleeper_an_aged_caretaker_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_ancient_advocator'); # :sleeper_an_ancient_advocator_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_ancient_caretaker'); # :sleeper_an_ancient_caretaker_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_ancient_drakeen'); # :sleeper_an_ancient_drakeen_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_ancient_drakonine'); # :sleeper_an_ancient_drakonine_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_ancient_sentry'); # :sleeper_an_ancient_sentry_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_arcane_wyvern'); # :sleeper_an_arcane_wyvern_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_intrepid_drakeen'); # :sleeper_an_intrepid_drakeen_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_iridescent_caretaker'); # :sleeper_an_iridescent_caretaker_lt:
INSERT INTO loottable(name) VALUES('sleeper_an_opalescent_sentry'); # :sleeper_an_opalescent_sentry_lt:
INSERT INTO loottable(name) VALUES('sleeper_area15starter'); # :sleeper_area15starter_lt:
INSERT INTO loottable(name) VALUES('sleeper_area18mob1dead'); # :sleeper_area18mob1dead_lt:
INSERT INTO loottable(name) VALUES('sleeper_area18mob2dead'); # :sleeper_area18mob2dead_lt:
INSERT INTO loottable(name) VALUES('sleeper_area18mob3dead'); # :sleeper_area18mob3dead_lt:
INSERT INTO loottable(name) VALUES('sleeper_area18starter'); # :sleeper_area18starter_lt:
INSERT INTO loottable(name) VALUES('sleeper_area4spawner'); # :sleeper_area4spawner_lt:
INSERT INTO loottable(name) VALUES('sleeper_area8mob10dead'); # :sleeper_area8mob10dead_lt:
INSERT INTO loottable(name) VALUES('sleeper_area8mob1dead'); # :sleeper_area8mob1dead_lt:
INSERT INTO loottable(name) VALUES('sleeper_area8mob2dead'); # :sleeper_area8mob2dead_lt:
INSERT INTO loottable(name) VALUES('sleeper_area8mob5dead'); # :sleeper_area8mob5dead_lt:
INSERT INTO loottable(name) VALUES('sleeper_area8mob6dead'); # :sleeper_area8mob6dead_lt:
INSERT INTO loottable(name) VALUES('sleeper_area8starter'); # :sleeper_area8starter_lt:
INSERT INTO loottable(name) VALUES('sleeper_as_you'); # :sleeper_as_you_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_colloquial_antagonist'); # :sleeper_a_colloquial_antagonist_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_debris_covered_guardian'); # :sleeper_a_debris_covered_guardian_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_drakeen_collaborator'); # :sleeper_a_drakeen_collaborator_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_drakeen_sentinel'); # :sleeper_a_drakeen_sentinel_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_drakonine_antagonist'); # :sleeper_a_drakonine_antagonist_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_drakonine_flurrier'); # :sleeper_a_drakonine_flurrier_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_drakonine_lair_keeper'); # :sleeper_a_drakonine_lair_keeper_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_drakonine_opportunist'); # :sleeper_a_drakonine_opportunist_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_flailing_phantom'); # :sleeper_a_flailing_phantom_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_lair_protector'); # :sleeper_a_lair_protector_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_newly_created_sentry'); # :sleeper_a_newly_created_sentry_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_prismatic_keeper'); # :sleeper_a_prismatic_keeper_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_prismatic_priest'); # :sleeper_a_prismatic_priest_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_prismatic_sentry'); # :sleeper_a_prismatic_sentry_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_prismatic_servitor'); # :sleeper_a_prismatic_servitor_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_scholarly_wyvern'); # :sleeper_a_scholarly_wyvern_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_scorn_spectre'); # :sleeper_a_scorn_spectre_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_screeching_banshee'); # :sleeper_a_screeching_banshee_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_tireless_servitor'); # :sleeper_a_tireless_servitor_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_vigilant_custodian'); # :sleeper_a_vigilant_custodian_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_wardstone'); # :sleeper_a_wardstone_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_warning'); # :sleeper_a_warning_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_warren_protector'); # :sleeper_a_warren_protector_lt:
INSERT INTO loottable(name) VALUES('sleeper_a_watchful_custodian'); # :sleeper_a_watchful_custodian_lt:
INSERT INTO loottable(name) VALUES('sleeper_drakeen_controller'); # :sleeper_drakeen_controller_lt:
INSERT INTO loottable(name) VALUES('sleeper_drakonine_caretaker'); # :sleeper_drakonine_caretaker_lt:
INSERT INTO loottable(name) VALUES('sleeper_drakonine_defender'); # :sleeper_drakonine_defender_lt:
INSERT INTO loottable(name) VALUES('sleeper_drakonine_guardian'); # :sleeper_drakonine_guardian_lt:
INSERT INTO loottable(name) VALUES('sleeper_forbidding_gargoyle'); # :sleeper_forbidding_gargoyle_lt:
INSERT INTO loottable(name) VALUES('sleeper_furious_phantasm'); # :sleeper_furious_phantasm_lt:
INSERT INTO loottable(name) VALUES('sleeper_milas_anrev'); # :sleeper_milas_anrev_lt:
INSERT INTO loottable(name) VALUES('sleeper_paldar_bladesoul'); # :sleeper_paldar_bladesoul_lt:
INSERT INTO loottable(name) VALUES('sleeper_paldar_the_demented'); # :sleeper_paldar_the_demented_lt:
INSERT INTO loottable(name) VALUES('sleeper_sinister_gargoyle'); # :sleeper_sinister_gargoyle_lt:
INSERT INTO loottable(name) VALUES('sleeper_staticshoutone'); # :sleeper_staticshoutone_lt:
INSERT INTO loottable(name) VALUES('sleeper_staticshouttwo'); # :sleeper_staticshouttwo_lt:
INSERT INTO loottable(name) VALUES('sleeper_the_overseer'); # :sleeper_the_overseer_lt:
INSERT INTO loottable(name) VALUES('sleeper_ulessa_bladesoul'); # :sleeper_ulessa_bladesoul_lt:
INSERT INTO loottable(name) VALUES('sleeper_ulessa_the_insane'); # :sleeper_ulessa_the_insane_lt:
INSERT INTO loottable(name) VALUES('sleeper_wyvern_fanatic'); # :sleeper_wyvern_fanatic_lt:
