UPDATE npc_types SET loottable_id = :templeveeshan_aaryonar_lt: WHERE id in (124010); # #Aaryonar 66
UPDATE npc_types SET loottable_id = :templeveeshan_a_glowing_orb_lt: WHERE id in (124125); # #A_Glowing_Orb 55
UPDATE npc_types SET loottable_id = :templeveeshan_casalen_lt: WHERE id in (124040); # #Casalen 60
UPDATE npc_types SET loottable_id = :templeveeshan_cekenar_lt: WHERE id in (124071); # #Cekenar 66
UPDATE npc_types SET loottable_id = :templeveeshan_cyndor_lightningfang_lt: WHERE id in (124018); # #Cyndor_Lightningfang 65
UPDATE npc_types SET loottable_id = :templeveeshan_dozekar_the_cursed_lt: WHERE id in (124037); # #Dozekar_the_Cursed 66
UPDATE npc_types SET loottable_id = :templeveeshan_eashen_of_the_sky_lt: WHERE id in (124004); # #Eashen_of_the_Sky 66
UPDATE npc_types SET loottable_id = :templeveeshan_essedera_lt: WHERE id in (124038); # #Essedera 60
UPDATE npc_types SET loottable_id = :templeveeshan_feshlak_chkone_lt: WHERE id in (124120); # #Feshlak_ChkOne 50
UPDATE npc_types SET loottable_id = :templeveeshan_gozzrem_lt: WHERE id in (124105); # #Gozzrem 66
UPDATE npc_types SET loottable_id = :templeveeshan_grozzmel_lt: WHERE id in (124031); # #Grozzmel 60
UPDATE npc_types SET loottable_id = :templeveeshan_ikatiar_the_venom_lt: WHERE id in (124001); # #Ikatiar_the_Venom 66
UPDATE npc_types SET loottable_id = :templeveeshan_jorlleag_lt: WHERE id in (124072); # #Jorlleag 66
UPDATE npc_types SET loottable_id = :templeveeshan_kalkar_of_the_maelstrom_lt: WHERE id in (124106); # #Kalkar_of_the_Maelstrom 65
UPDATE npc_types SET loottable_id = :templeveeshan_krigara_lt: WHERE id in (124035); # #Krigara 60
UPDATE npc_types SET loottable_id = :templeveeshan_lady_mirenilla_lt: WHERE id in (124077); # #Lady_Mirenilla 66
UPDATE npc_types SET loottable_id = :templeveeshan_lady_nevederia_lt: WHERE id in (124076); # #Lady_Nevederia 66
UPDATE npc_types SET loottable_id = :templeveeshan_lendiniara_the_keeper_lt: WHERE id in (124020); # #Lendiniara_the_Keeper 66
UPDATE npc_types SET loottable_id = :templeveeshan_lepethida_lt: WHERE id in (124036); # #Lepethida 60
UPDATE npc_types SET loottable_id = :templeveeshan_lord_feshlak_lt: WHERE id in (124008); # #Lord_Feshlak 66
UPDATE npc_types SET loottable_id = :templeveeshan_lord_koidoken_lt: WHERE id in (124103); # #Lord_Koi`Doken 66
UPDATE npc_types SET loottable_id = :templeveeshan_lord_kreizenn_lt: WHERE id in (124074); # #Lord_Kreizenn 66
UPDATE npc_types SET loottable_id = :templeveeshan_lord_vyemm_lt: WHERE id in (124017); # #Lord_Vyemm 66
UPDATE npc_types SET loottable_id = :templeveeshan_malteor_flamecaller_lt: WHERE id in (124009); # #Malteor_Flamecaller 65
UPDATE npc_types SET loottable_id = :templeveeshan_midayor_lt: WHERE id in (124030); # #Midayor 60
UPDATE npc_types SET loottable_id = :templeveeshan_quellod_earthspirit_lt: WHERE id in (124006); # #Quellod_Earthspirit 65
UPDATE npc_types SET loottable_id = :templeveeshan_sevalak_lt: WHERE id in (124075); # #Sevalak 66
UPDATE npc_types SET loottable_id = :templeveeshan_tavekalem_lt: WHERE id in (124039); # #Tavekalem 60
UPDATE npc_types SET loottable_id = :templeveeshan_telkorenar_lt: WHERE id in (124104); # #Telkorenar 66
UPDATE npc_types SET loottable_id = :templeveeshan_thylex_of_veeshan_lt: WHERE id in (124000); # #Thylex_of_Veeshan 10
UPDATE npc_types SET loottable_id = :templeveeshan_vulak_trigger_lt: WHERE id in (124156); # #Vulak_Trigger 90
UPDATE npc_types SET loottable_id = :templeveeshan_vulakaerr_lt: WHERE id in (124155); # #Vulak`Aerr 70
UPDATE npc_types SET loottable_id = :templeveeshan_vyldin_flamereaver_lt: WHERE id in (124107); # #Vyldin_Flamereaver 65
UPDATE npc_types SET loottable_id = :templeveeshan_ymmeln_lt: WHERE id in (124034); # #Ymmeln 60
UPDATE npc_types SET loottable_id = :templeveeshan_yrrindor_emerald_claw_lt: WHERE id in (124007); # #Yrrindor_Emerald_Claw 65
UPDATE npc_types SET loottable_id = :templeveeshan_zemm_lt: WHERE id in (124078); # #Zemm 66
UPDATE npc_types SET loottable_id = :templeveeshan_zlexak_lt: WHERE id in (124073); # #Zlexak 66
UPDATE npc_types SET loottable_id = :templeveeshan_ajorek_the_crimson_fang_lt: WHERE id in (124088); # Ajorek_the_Crimson_Fang 63
UPDATE npc_types SET loottable_id = :templeveeshan_an_acolyte_of_veeshan_lt: WHERE id in (124114, 124141, 124149); # an_acolyte_of_Veeshan 62
UPDATE npc_types SET loottable_id = :templeveeshan_an_ancient_frost_guardian_lt: WHERE id in (124070); # an_ancient_frost_guardian 64
UPDATE npc_types SET loottable_id = :templeveeshan_an_ancient_guardian_lt: WHERE id in (124081); # an_ancient_guardian 60
UPDATE npc_types SET loottable_id = :templeveeshan_an_ancient_guardian_wurm_lt: WHERE id in (124019); # an_ancient_guardian_wurm 62
UPDATE npc_types SET loottable_id = :templeveeshan_an_ancient_ice_wurm_defender_lt: WHERE id in (124047); # an_ancient_ice_wurm_defender 62
UPDATE npc_types SET loottable_id = :templeveeshan_an_ancient_shard_wyvern_lt: WHERE id in (124085, 124102); # an_ancient_shard_wyvern 64
UPDATE npc_types SET loottable_id = :templeveeshan_an_ancient_sky_drake_lt: WHERE id in (124055); # an_ancient_sky_drake 62
UPDATE npc_types SET loottable_id = :templeveeshan_an_ancient_tigerclaw_racnar_lt: WHERE id in (124026); # an_ancient_tigerclaw_racnar 63
UPDATE npc_types SET loottable_id = :templeveeshan_an_ancient_wyvern_lt: WHERE id in (124108); # an_ancient_wyvern 64
UPDATE npc_types SET loottable_id = :templeveeshan_an_ebon_wing_hatchling_lt: WHERE id in (124042); # an_ebon_wing_hatchling 45
UPDATE npc_types SET loottable_id = :templeveeshan_an_elder_crimson_drake_lt: WHERE id in (124067); # an_elder_crimson_drake 62
UPDATE npc_types SET loottable_id = :templeveeshan_an_elder_onyx_drake_lt: WHERE id in (124053); # an_elder_onyx_drake 62
UPDATE npc_types SET loottable_id = :templeveeshan_an_elder_racnar_lt: WHERE id in (124068); # an_elder_racnar 63
UPDATE npc_types SET loottable_id = :templeveeshan_an_elder_shard_wyvern_lt: WHERE id in (124028); # an_elder_shard_wyvern 61
UPDATE npc_types SET loottable_id = :templeveeshan_an_elder_temple_defender_lt: WHERE id in (124022, 124099); # an_elder_temple_defender 60
UPDATE npc_types SET loottable_id = :templeveeshan_an_elder_wyvern_lt: WHERE id in (124058); # an_elder_wyvern 61
UPDATE npc_types SET loottable_id = :templeveeshan_an_emerald_defender_lt: WHERE id in (124050); # An_Emerald_Defender 65
UPDATE npc_types SET loottable_id = :templeveeshan_an_emerald_eye_hatchling_lt: WHERE id in (124043); # an_emerald_eye_hatchling 45
UPDATE npc_types SET loottable_id = :templeveeshan_an_emerald_sky_defender_lt: WHERE id in (124046, 124061); # an_emerald_sky_defender 60
UPDATE npc_types SET loottable_id = :templeveeshan_an_emerald_watcher_lt: WHERE id in (124110); # an_emerald_watcher 60
UPDATE npc_types SET loottable_id = :templeveeshan_an_onyx_defender_lt: WHERE id in (124052); # An_Onyx_Defender 65
UPDATE npc_types SET loottable_id = :templeveeshan_an_onyx_hatchling_lt: WHERE id in (124152); # an_onyx_hatchling 55
UPDATE npc_types SET loottable_id = :templeveeshan_an_onyx_sky_drake_lt: WHERE id in (124059, 124062); # an_onyx_sky_drake 60
UPDATE npc_types SET loottable_id = :templeveeshan_an_onyx_warden_lt: WHERE id in (124112); # an_onyx_warden 62
UPDATE npc_types SET loottable_id = :templeveeshan_arreken_skyward_lt: WHERE id in (124063); # Arreken_Skyward 62
UPDATE npc_types SET loottable_id = :templeveeshan_as_you_pass_lt: WHERE id in (124148); # As_you_pass 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_burning_guardian_lt: WHERE id in (124032); # a_burning_guardian 64
UPDATE npc_types SET loottable_id = :templeveeshan_a_cerulean_guardian_lt: WHERE id in (124097); # a_cerulean_guardian 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_cerulean_hatchling_lt: WHERE id in (124146); # a_cerulean_hatchling 55
UPDATE npc_types SET loottable_id = :templeveeshan_a_cerulean_sky_gazer_lt: WHERE id in (124044, 124109); # a_cerulean_sky_gazer 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_crimson_claw_hatchling_lt: WHERE id in (124041); # a_crimson_claw_hatchling 45
UPDATE npc_types SET loottable_id = :templeveeshan_a_crimson_hatchling_lt: WHERE id in (124124); # a_crimson_hatchling 55
UPDATE npc_types SET loottable_id = :templeveeshan_a_deafening_roar_lt: WHERE id in (124135); # A_deafening_roar 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_feeling_lt: WHERE id in (124140); # A_feeling 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_fiery_drake_lt: WHERE id in (124066); # a_fiery_drake 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_fiery_guardian_lt: WHERE id in (124065); # a_fiery_guardian 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_fiery_temple_guardian_lt: WHERE id in (124023); # a_fiery_temple_guardian 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_fiery_watcher_lt: WHERE id in (124024, 124064, 124082); # a_fiery_watcher 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_glimmering_drake_lt: WHERE id in (124002, 124083); # a_glimmering_drake 64
UPDATE npc_types SET loottable_id = :templeveeshan_a_glimmering_emerald_drake_lt: WHERE id in (124111); # a_glimmering_emerald_drake 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_glimmer_drake_lt: WHERE id in (124048); # a_glimmer_drake 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_greater_malevolent_drake_lt: WHERE id in (124029); # a_greater_malevolent_drake 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_greater_sky_drake_lt: WHERE id in (124069); # a_greater_sky_drake 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_guardian_spirit_lt: WHERE id in (124021, 124080, 124157); # a_guardian_spirit 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_jade_warden_lt: WHERE id in (124115); # a_jade_warden 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_lava_dancer_lt: WHERE id in (124049, 124084); # a_lava_dancer 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_lava_defender_lt: WHERE id in (124079); # A_Lava_Defender 65
UPDATE npc_types SET loottable_id = :templeveeshan_a_malevolent_drake_lt: WHERE id in (124027); # a_malevolent_drake 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_molten_warden_lt: WHERE id in (124126); # a_molten_warden 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_pearl_destroyer_lt: WHERE id in (124136); # a_pearl_destroyer 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_racnar_lt: WHERE id in (124101); # a_racnar 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_raging_wind_lt: WHERE id in (124153); # A_raging_wind 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_raging_wyvern_lt: WHERE id in (124095); # a_raging_wyvern 61
UPDATE npc_types SET loottable_id = :templeveeshan_a_sense_of_awe_lt: WHERE id in (124119, 124151); # A_sense_of_awe 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_shard_wyvern_hatchling_lt: WHERE id in (124033); # a_shard_wyvern_hatchling 45
UPDATE npc_types SET loottable_id = :templeveeshan_a_shimmering_green_drake_lt: WHERE id in (124054); # a_shimmering_green_drake 62
UPDATE npc_types SET loottable_id = :templeveeshan_a_shimmer_drake_lt: WHERE id in (124098, 124100); # a_shimmer_drake 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_skyseeker_hatchling_lt: WHERE id in (124045); # a_skyseeker_hatchling 45
UPDATE npc_types SET loottable_id = :templeveeshan_a_sky_defender_lt: WHERE id in (124051); # A_Sky_Defender 65
UPDATE npc_types SET loottable_id = :templeveeshan_a_tigerclaw_racnar_lt: WHERE id in (124025); # a_tigerclaw_racnar 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_vehement_wyvern_lt: WHERE id in (124096); # a_vehement_wyvern 66
UPDATE npc_types SET loottable_id = :templeveeshan_a_vortex_of_mana_lt: WHERE id in (124144); # A_vortex_of_mana 60
UPDATE npc_types SET loottable_id = :templeveeshan_a_wyvern_hatchling_lt: WHERE id in (124060); # a_wyvern_hatchling 45
UPDATE npc_types SET loottable_id = :templeveeshan_beldion_icewind_lt: WHERE id in (124147); # Beldion_Icewind 65
UPDATE npc_types SET loottable_id = :templeveeshan_belijor_the_emerald_eye_lt: WHERE id in (124057); # Belijor_the_Emerald_Eye 63
UPDATE npc_types SET loottable_id = :templeveeshan_bryrym_lt: WHERE id in (124005); # Bryrym 60
UPDATE npc_types SET loottable_id = :templeveeshan_carxvean_lt: WHERE id in (124094); # Carx`Vean 60
UPDATE npc_types SET loottable_id = :templeveeshan_dagarn_the_destroyer_lt: WHERE id in (124011); # Dagarn_the_Destroyer 70
UPDATE npc_types SET loottable_id = :templeveeshan_empty_egg_shells_lt: WHERE id in (124117); # Empty_egg_shells 60
UPDATE npc_types SET loottable_id = :templeveeshan_gravloren_lt: WHERE id in (124091); # Gra`Vloren 60
UPDATE npc_types SET loottable_id = :templeveeshan_hsrek_lt: WHERE id in (124014); # Hsrek 60
UPDATE npc_types SET loottable_id = :templeveeshan_infusion_lt: WHERE id in (124154); # Infusion 50
UPDATE npc_types SET loottable_id = :templeveeshan_kalvunar_lt: WHERE id in (124016); # Kal`Vunar 60
UPDATE npc_types SET loottable_id = :templeveeshan_kedrak_lt: WHERE id in (124093); # Kedrak 60
UPDATE npc_types SET loottable_id = :templeveeshan_lurian_lt: WHERE id in (124013); # Lurian 60
UPDATE npc_types SET loottable_id = :templeveeshan_mazrien_lt: WHERE id in (124090); # Mazrien 60
UPDATE npc_types SET loottable_id = :templeveeshan_meldikor_the_windchaser_lt: WHERE id in (124086); # Meldikor_the_Windchaser 60
UPDATE npc_types SET loottable_id = :templeveeshan_nelaarn_the_ebon_claw_lt: WHERE id in (124089); # Nelaarn_the_Ebon_Claw 63
UPDATE npc_types SET loottable_id = :templeveeshan_nirtan_lt: WHERE id in (124012); # Nir`Tan 60
UPDATE npc_types SET loottable_id = :templeveeshan_something_seems_lt: WHERE id in (124150); # Something_seems 60
UPDATE npc_types SET loottable_id = :templeveeshan_spawn_master_lt: WHERE id in (124142); # Spawn_Master 50
UPDATE npc_types SET loottable_id = :templeveeshan_theldek_the_stinger_lt: WHERE id in (124087); # Theldek_the_Stinger 59
UPDATE npc_types SET loottable_id = :templeveeshan_the_sound_of_lt: WHERE id in (124130); # The_sound_of 60
UPDATE npc_types SET loottable_id = :templeveeshan_vukuz_lt: WHERE id in (124015); # Vukuz 60
UPDATE npc_types SET loottable_id = :templeveeshan_welwnas_lt: WHERE id in (124092); # Wel`Wnas 60
UPDATE npc_types SET loottable_id = :templeveeshan_yendilor_the_cerulean_wing_lt: WHERE id in (124056); # Yendilor_the_Cerulean_Wing 60
UPDATE npc_types SET loottable_id = :templeveeshan_zyerek_onyxblood_lt: WHERE id in (124003); # Zyerek_Onyxblood 65
