INSERT INTO loottable(name) VALUES('thurgadinb_councilor_juliah_lockheart'); # :thurgadinb_councilor_juliah_lockheart_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_dain_frostreaver_iv'); # :thurgadinb_dain_frostreaver_iv_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_daytrigger'); # :thurgadinb_daytrigger_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_nighttrigger'); # :thurgadinb_nighttrigger_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_an_avalanche_golem'); # :thurgadinb_an_avalanche_golem_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_an_icewell_sentinel'); # :thurgadinb_an_icewell_sentinel_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_an_icewell_sentry'); # :thurgadinb_an_icewell_sentry_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_a_coldain_skeleton'); # :thurgadinb_a_coldain_skeleton_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_a_frost_spike'); # :thurgadinb_a_frost_spike_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_bouncy'); # :thurgadinb_bouncy_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_chamberlain_krystorf'); # :thurgadinb_chamberlain_krystorf_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_coldain_outcast'); # :thurgadinb_coldain_outcast_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_amberfeld'); # :thurgadinb_councilor_amberfeld_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_coldember'); # :thurgadinb_councilor_coldember_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_darakor'); # :thurgadinb_councilor_darakor_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_darkfrost'); # :thurgadinb_councilor_darkfrost_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_deynekn'); # :thurgadinb_councilor_deynekn_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_dirkins'); # :thurgadinb_councilor_dirkins_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_glacierbane'); # :thurgadinb_councilor_glacierbane_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_icelok'); # :thurgadinb_councilor_icelok_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_icepike'); # :thurgadinb_councilor_icepike_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_juliah_lockheart'); # :thurgadinb_councilor_juliah_lockheart_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_thubins'); # :thurgadinb_councilor_thubins_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_councilor_wintershade'); # :thurgadinb_councilor_wintershade_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_frosticube'); # :thurgadinb_frosticube_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_frosty_mug'); # :thurgadinb_frosty_mug_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_ghost'); # :thurgadinb_ghost_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_glucose'); # :thurgadinb_glucose_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_grand_huntsman_darral'); # :thurgadinb_grand_huntsman_darral_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_grizznot'); # :thurgadinb_grizznot_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_loremaster_solstrin'); # :thurgadinb_loremaster_solstrin_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_onethree'); # :thurgadinb_onethree_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_royal_armorer_slade'); # :thurgadinb_royal_armorer_slade_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_royal_guardsman_braxis'); # :thurgadinb_royal_guardsman_braxis_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_royal_guardsman_hauten'); # :thurgadinb_royal_guardsman_hauten_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_royal_guardsman_horix'); # :thurgadinb_royal_guardsman_horix_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_royal_guardsman_nial'); # :thurgadinb_royal_guardsman_nial_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_royal_guardsman_raxine'); # :thurgadinb_royal_guardsman_raxine_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_royal_guardsman_rhion'); # :thurgadinb_royal_guardsman_rhion_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_royal_scribe_kaavin'); # :thurgadinb_royal_scribe_kaavin_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_seneschal_aldikar'); # :thurgadinb_seneschal_aldikar_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_sentinel_anderin'); # :thurgadinb_sentinel_anderin_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_sentinel_fridmar'); # :thurgadinb_sentinel_fridmar_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_sentinel_paxin'); # :thurgadinb_sentinel_paxin_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_sentinel_saedis'); # :thurgadinb_sentinel_saedis_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_sentinel_sheila'); # :thurgadinb_sentinel_sheila_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_sentry_ellison'); # :thurgadinb_sentry_ellison_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_servant_girl'); # :thurgadinb_servant_girl_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_staff_sergeant_bayard'); # :thurgadinb_staff_sergeant_bayard_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_watcher_devin'); # :thurgadinb_watcher_devin_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_watcher_scots'); # :thurgadinb_watcher_scots_lt:
INSERT INTO loottable(name) VALUES('thurgadinb_watcher_sprin'); # :thurgadinb_watcher_sprin_lt:
