INSERT INTO loottable(name) VALUES('velketor_bledrek'); # :velketor_bledrek_lt:
INSERT INTO loottable(name) VALUES('velketor_errkak_icepaw'); # :velketor_errkak_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_failed_experiment'); # :velketor_failed_experiment_lt:
INSERT INTO loottable(name) VALUES('velketor_gregendek_icepaw'); # :velketor_gregendek_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_jelek_icepaw'); # :velketor_jelek_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_kalik_icepaw'); # :velketor_kalik_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_kerdelb'); # :velketor_kerdelb_lt:
INSERT INTO loottable(name) VALUES('velketor_laryk_icepaw'); # :velketor_laryk_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_marlek_icepaw'); # :velketor_marlek_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_meljemor'); # :velketor_meljemor_lt:
INSERT INTO loottable(name) VALUES('velketor_rowwek_icepaw'); # :velketor_rowwek_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_tpos_icepaw'); # :velketor_tpos_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_ular_icepaw'); # :velketor_ular_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_velketors_experiment'); # :velketor_velketors_experiment_lt:
INSERT INTO loottable(name) VALUES('velketor_venar_icepaw'); # :velketor_venar_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_aedispellph'); # :velketor_aedispellph_lt:
INSERT INTO loottable(name) VALUES('velketor_aerainph'); # :velketor_aerainph_lt:
INSERT INTO loottable(name) VALUES('velketor_an_icepaw_champion'); # :velketor_an_icepaw_champion_lt:
INSERT INTO loottable(name) VALUES('velketor_an_icepaw_cleric'); # :velketor_an_icepaw_cleric_lt:
INSERT INTO loottable(name) VALUES('velketor_an_icepaw_kobold'); # :velketor_an_icepaw_kobold_lt:
INSERT INTO loottable(name) VALUES('velketor_an_icepaw_kobold_priest'); # :velketor_an_icepaw_kobold_priest_lt:
INSERT INTO loottable(name) VALUES('velketor_an_icepaw_kobold_warrior'); # :velketor_an_icepaw_kobold_warrior_lt:
INSERT INTO loottable(name) VALUES('velketor_an_icepaw_prophet'); # :velketor_an_icepaw_prophet_lt:
INSERT INTO loottable(name) VALUES('velketor_an_ice_paw_sorcerer'); # :velketor_an_ice_paw_sorcerer_lt:
INSERT INTO loottable(name) VALUES('velketor_an_icy_watcher'); # :velketor_an_icy_watcher_lt:
INSERT INTO loottable(name) VALUES('velketor_a_blizzard_hunter'); # :velketor_a_blizzard_hunter_lt:
INSERT INTO loottable(name) VALUES('velketor_a_blizzard_spider'); # :velketor_a_blizzard_spider_lt:
INSERT INTO loottable(name) VALUES('velketor_a_chill'); # :velketor_a_chill_lt:
INSERT INTO loottable(name) VALUES('velketor_a_cold_shade'); # :velketor_a_cold_shade_lt:
INSERT INTO loottable(name) VALUES('velketor_a_cold_spectre'); # :velketor_a_cold_spectre_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystaline_sentinel'); # :velketor_a_crystaline_sentinel_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystalline_devourer'); # :velketor_a_crystalline_devourer_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystalline_gargoyle'); # :velketor_a_crystalline_gargoyle_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystalline_hunter'); # :velketor_a_crystalline_hunter_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystalline_sentinel'); # :velketor_a_crystalline_sentinel_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystalline_shard'); # :velketor_a_crystalline_shard_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystalline_statue'); # :velketor_a_crystalline_statue_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystalline_watcher'); # :velketor_a_crystalline_watcher_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystal_destroyer'); # :velketor_a_crystal_destroyer_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystal_gargoyle'); # :velketor_a_crystal_gargoyle_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystal_guardian'); # :velketor_a_crystal_guardian_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystal_sentinel'); # :velketor_a_crystal_sentinel_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystal_shard'); # :velketor_a_crystal_shard_lt:
INSERT INTO loottable(name) VALUES('velketor_a_crystal_statue'); # :velketor_a_crystal_statue_lt:
INSERT INTO loottable(name) VALUES('velketor_a_deadly_blizzard_hunter'); # :velketor_a_deadly_blizzard_hunter_lt:
INSERT INTO loottable(name) VALUES('velketor_a_fierce_blizzard_hunter'); # :velketor_a_fierce_blizzard_hunter_lt:
INSERT INTO loottable(name) VALUES('velketor_a_frenzied_velium_broodling'); # :velketor_a_frenzied_velium_broodling_lt:
INSERT INTO loottable(name) VALUES('velketor_a_frenzied_velium_stalker'); # :velketor_a_frenzied_velium_stalker_lt:
INSERT INTO loottable(name) VALUES('velketor_a_frost_spectre'); # :velketor_a_frost_spectre_lt:
INSERT INTO loottable(name) VALUES('velketor_a_glimmering_orb'); # :velketor_a_glimmering_orb_lt:
INSERT INTO loottable(name) VALUES('velketor_a_hissing'); # :velketor_a_hissing_lt:
INSERT INTO loottable(name) VALUES('velketor_a_large_crystal_shard'); # :velketor_a_large_crystal_shard_lt:
INSERT INTO loottable(name) VALUES('velketor_a_shard_spectre'); # :velketor_a_shard_spectre_lt:
INSERT INTO loottable(name) VALUES('velketor_a_shard_spider'); # :velketor_a_shard_spider_lt:
INSERT INTO loottable(name) VALUES('velketor_a_shimmering_orb'); # :velketor_a_shimmering_orb_lt:
INSERT INTO loottable(name) VALUES('velketor_a_stalagtite'); # :velketor_a_stalagtite_lt:
INSERT INTO loottable(name) VALUES('velketor_a_tentacle'); # :velketor_a_tentacle_lt:
INSERT INTO loottable(name) VALUES('velketor_a_velium_broodling'); # :velketor_a_velium_broodling_lt:
INSERT INTO loottable(name) VALUES('velketor_a_velium_hunter'); # :velketor_a_velium_hunter_lt:
INSERT INTO loottable(name) VALUES('velketor_a_velium_stalker'); # :velketor_a_velium_stalker_lt:
INSERT INTO loottable(name) VALUES('velketor_bjoron_axefall'); # :velketor_bjoron_axefall_lt:
INSERT INTO loottable(name) VALUES('velketor_bled'); # :velketor_bled_lt:
INSERT INTO loottable(name) VALUES('velketor_brumen_firehammer'); # :velketor_brumen_firehammer_lt:
INSERT INTO loottable(name) VALUES('velketor_bryma_loftaxe'); # :velketor_bryma_loftaxe_lt:
INSERT INTO loottable(name) VALUES('velketor_crystal_eyes'); # :velketor_crystal_eyes_lt:
INSERT INTO loottable(name) VALUES('velketor_crystal_fang'); # :velketor_crystal_fang_lt:
INSERT INTO loottable(name) VALUES('velketor_crystal_guardian'); # :velketor_crystal_guardian_lt:
INSERT INTO loottable(name) VALUES('velketor_dlemin_whiteforge'); # :velketor_dlemin_whiteforge_lt:
INSERT INTO loottable(name) VALUES('velketor_drella_stonegrinder'); # :velketor_drella_stonegrinder_lt:
INSERT INTO loottable(name) VALUES('velketor_eight'); # :velketor_eight_lt:
INSERT INTO loottable(name) VALUES('velketor_five'); # :velketor_five_lt:
INSERT INTO loottable(name) VALUES('velketor_four'); # :velketor_four_lt:
INSERT INTO loottable(name) VALUES('velketor_frekka_alebringer'); # :velketor_frekka_alebringer_lt:
INSERT INTO loottable(name) VALUES('velketor_from_no_where'); # :velketor_from_no_where_lt:
INSERT INTO loottable(name) VALUES('velketor_ice'); # :velketor_ice_lt:
INSERT INTO loottable(name) VALUES('velketor_icepaw_kobold'); # :velketor_icepaw_kobold_lt:
INSERT INTO loottable(name) VALUES('velketor_icy_guardian'); # :velketor_icy_guardian_lt:
INSERT INTO loottable(name) VALUES('velketor_kerd'); # :velketor_kerd_lt:
INSERT INTO loottable(name) VALUES('velketor_khelkar_icepaw'); # :velketor_khelkar_icepaw_lt:
INSERT INTO loottable(name) VALUES('velketor_khlem_alestone'); # :velketor_khlem_alestone_lt:
INSERT INTO loottable(name) VALUES('velketor_lord_doljonijiarnimorinar'); # :velketor_lord_doljonijiarnimorinar_lt:
INSERT INTO loottable(name) VALUES('velketor_nine'); # :velketor_nine_lt:
INSERT INTO loottable(name) VALUES('velketor_one'); # :velketor_one_lt:
INSERT INTO loottable(name) VALUES('velketor_rijoely'); # :velketor_rijoely_lt:
INSERT INTO loottable(name) VALUES('velketor_seven'); # :velketor_seven_lt:
INSERT INTO loottable(name) VALUES('velketor_six'); # :velketor_six_lt:
INSERT INTO loottable(name) VALUES('velketor_something_seems'); # :velketor_something_seems_lt:
INSERT INTO loottable(name) VALUES('velketor_ten'); # :velketor_ten_lt:
INSERT INTO loottable(name) VALUES('velketor_terrorspawner'); # :velketor_terrorspawner_lt:
INSERT INTO loottable(name) VALUES('velketor_the_brood_master'); # :velketor_the_brood_master_lt:
INSERT INTO loottable(name) VALUES('velketor_the_brood_mother'); # :velketor_the_brood_mother_lt:
INSERT INTO loottable(name) VALUES('velketor_the_hair'); # :velketor_the_hair_lt:
INSERT INTO loottable(name) VALUES('velketor_the_walls'); # :velketor_the_walls_lt:
INSERT INTO loottable(name) VALUES('velketor_three'); # :velketor_three_lt:
INSERT INTO loottable(name) VALUES('velketor_tijoely'); # :velketor_tijoely_lt:
INSERT INTO loottable(name) VALUES('velketor_two'); # :velketor_two_lt:
INSERT INTO loottable(name) VALUES('velketor_velketor_the_sorcerer'); # :velketor_velketor_the_sorcerer_lt:
INSERT INTO loottable(name) VALUES('velketor_you_are'); # :velketor_you_are_lt:
