UPDATE npc_types SET loottable_id = :westwastes_amcilla_lt: WHERE id in (120061); # #Amcilla 53
UPDATE npc_types SET loottable_id = :westwastes_a_banished_efreeti_lt: WHERE id in (120129); # #a_banished_efreeti 65
UPDATE npc_types SET loottable_id = :westwastes_a_kromzek_captain_lt: WHERE id in (120115); # #a_Kromzek_Captain 58
UPDATE npc_types SET loottable_id = :westwastes_cargalia_lt: WHERE id in (120065); # #Cargalia 57
UPDATE npc_types SET loottable_id = :westwastes_diddugu_lt: WHERE id in (120128); # #Diddugu 65
UPDATE npc_types SET loottable_id = :westwastes_icehackle_lt: WHERE id in (120102); # #Icehackle 61
UPDATE npc_types SET loottable_id = :westwastes_mraaka_lt: WHERE id in (120064); # #Mraaka 66
UPDATE npc_types SET loottable_id = :westwastes_nintal_lt: WHERE id in (120041); # #Nintal 54
UPDATE npc_types SET loottable_id = :westwastes_scout_charisa_lt: WHERE id in (120000); # #Scout_Charisa 55
UPDATE npc_types SET loottable_id = :westwastes_scout_pirri_lt: WHERE id in (120112); # #Scout_Pirri 75
UPDATE npc_types SET loottable_id = :westwastes_strong_horn_lt: WHERE id in (120099); # #Strong_Horn 65
UPDATE npc_types SET loottable_id = :westwastes_tantor_lt: WHERE id in (120048); # #Tantor 66
UPDATE npc_types SET loottable_id = :westwastes_travala_lt: WHERE id in (120063); # #Travala 66
UPDATE npc_types SET loottable_id = :westwastes_tsiraka_lt: WHERE id in (120089); # #Tsiraka 66
UPDATE npc_types SET loottable_id = :westwastes_vohnkare_lt: WHERE id in (120130); # #Vohnkare 57
UPDATE npc_types SET loottable_id = :westwastes_von_lt: WHERE id in (120046); # #Von 57
UPDATE npc_types SET loottable_id = :westwastes_yal_lt: WHERE id in (120085); # #Yal 52
UPDATE npc_types SET loottable_id = :westwastes_zil_sapara_lt: WHERE id in (120093); # #Zil_Sapara 60
UPDATE npc_types SET loottable_id = :westwastes_an_elder_wyvern_lt: WHERE id in (120103, 120036); # an_elder_wyvern 52
UPDATE npc_types SET loottable_id = :westwastes_an_ice_burrower_lt: WHERE id in (120010); # an_ice_burrower 61
UPDATE npc_types SET loottable_id = :westwastes_atpaev_lt: WHERE id in (120122); # Atpaev 51
UPDATE npc_types SET loottable_id = :westwastes_ayillish_lt: WHERE id in (120015); # Ayillish 57
UPDATE npc_types SET loottable_id = :westwastes_a_brontotherium_lt: WHERE id in (120009, 120026); # a_brontotherium 46
UPDATE npc_types SET loottable_id = :westwastes_a_burrowing_wyvern_lt: WHERE id in (120038); # a_burrowing_wyvern 52
UPDATE npc_types SET loottable_id = :westwastes_a_cragwyrm_lt: WHERE id in (120070, 120013, 120023, 120032, 120033); # a_cragwyrm 51
UPDATE npc_types SET loottable_id = :westwastes_a_drake_lt: WHERE id in (120074, 120075, 120095, 120096, 120109); # a_drake 45
UPDATE npc_types SET loottable_id = :westwastes_a_drake_outcast_lt: WHERE id in (120092, 120104); # a_drake_outcast 46
UPDATE npc_types SET loottable_id = :westwastes_a_glacier_mastodon_lt: WHERE id in (120080, 120098, 120101, 120011, 120020); # a_glacier_mastodon 49
UPDATE npc_types SET loottable_id = :westwastes_a_gravid_drake_lt: WHERE id in (120012, 120022, 120027, 120034, 120051); # a_gravid_drake 46
UPDATE npc_types SET loottable_id = :westwastes_a_kromzek_warrior_lt: WHERE id in (120121); # a_Kromzek_warrior 54
UPDATE npc_types SET loottable_id = :westwastes_a_lindwyrm_lt: WHERE id in (120118); # a_lindwyrm 51
UPDATE npc_types SET loottable_id = :westwastes_a_lost_tomekeeper_lt: WHERE id in (120131); # a_Lost_Tomekeeper 65
UPDATE npc_types SET loottable_id = :westwastes_a_neuralgic_huntress_lt: WHERE id in (120136); # a_neuralgic_huntress 66
UPDATE npc_types SET loottable_id = :westwastes_a_rogue_dire_wolf_lt: WHERE id in (120082, 120097); # a_rogue_dire_wolf 48
UPDATE npc_types SET loottable_id = :westwastes_a_scar_guardian_lt: WHERE id in (120049, 120054); # a_Scar_Guardian 51
UPDATE npc_types SET loottable_id = :westwastes_a_sentinels_voice_lt: WHERE id in (120116); # A_sentinel`s_voice 1
UPDATE npc_types SET loottable_id = :westwastes_a_shipwrecked_pirate_lt: WHERE id in (120067); # a_shipwrecked_pirate 50
UPDATE npc_types SET loottable_id = :westwastes_a_slain_dragon_lt: WHERE id in (120077, 120078); # a_slain_dragon 1
UPDATE npc_types SET loottable_id = :westwastes_a_velious_drake_lt: WHERE id in (120047); # a_Velious_Drake 45
UPDATE npc_types SET loottable_id = :westwastes_a_velium_hound_lt: WHERE id in (120002); # a_velium_hound 47
UPDATE npc_types SET loottable_id = :westwastes_a_wayward_wyvern_lt: WHERE id in (120127); # a_wayward_wyvern 70
UPDATE npc_types SET loottable_id = :westwastes_a_wyvern_lt: WHERE id in (120037, 120039, 120040); # a_wyvern 50
UPDATE npc_types SET loottable_id = :westwastes_a_wyvern_hunter_lt: WHERE id in (120058, 120059, 120060); # a_wyvern_hunter 50
UPDATE npc_types SET loottable_id = :westwastes_a_wyvern_huntress_lt: WHERE id in (120090, 120091, 120045); # a_wyvern_huntress 52
UPDATE npc_types SET loottable_id = :westwastes_bratavar_lt: WHERE id in (120004); # Bratavar 53
UPDATE npc_types SET loottable_id = :westwastes_breezeboot_swordrattler_lt: WHERE id in (120069); # Breezeboot_Swordrattler 61
UPDATE npc_types SET loottable_id = :westwastes_bronif_snowchipper_lt: WHERE id in (120119); # Bronif_Snowchipper 56
UPDATE npc_types SET loottable_id = :westwastes_bufa_lt: WHERE id in (120088); # Bufa 54
UPDATE npc_types SET loottable_id = :westwastes_chief_engineer_tocs_lt: WHERE id in (120068); # Chief_Engineer_Tocs 55
UPDATE npc_types SET loottable_id = :westwastes_crial_lt: WHERE id in (120100); # Crial 54
UPDATE npc_types SET loottable_id = :westwastes_del_sapara_lt: WHERE id in (120125); # Del_Sapara 60
UPDATE npc_types SET loottable_id = :westwastes_derasinal_lt: WHERE id in (120014); # Derasinal 57
UPDATE npc_types SET loottable_id = :westwastes_disciple_of_moon_lt: WHERE id in (120138); # Disciple_of_Moon 70
UPDATE npc_types SET loottable_id = :westwastes_disciple_of_moon_trap_lt: WHERE id in (120137); # disciple_of_moon_trap 1
UPDATE npc_types SET loottable_id = :westwastes_draazak_lt: WHERE id in (120019); # Draazak 58
UPDATE npc_types SET loottable_id = :westwastes_entariz_lt: WHERE id in (120018); # Entariz 57
UPDATE npc_types SET loottable_id = :westwastes_esorpa_of_the_ring_lt: WHERE id in (120086); # Esorpa_of_the_Ring 53
UPDATE npc_types SET loottable_id = :westwastes_gafala_lt: WHERE id in (120024); # Gafala 52
UPDATE npc_types SET loottable_id = :westwastes_gangel_lt: WHERE id in (120120); # Gangel 51
UPDATE npc_types SET loottable_id = :westwastes_glati_lt: WHERE id in (120007); # Glati 54
UPDATE npc_types SET loottable_id = :westwastes_grenth_drakebane_lt: WHERE id in (120030); # Grenth_Drakebane 55
UPDATE npc_types SET loottable_id = :westwastes_guardian_kozzalym_lt: WHERE id in (120035); # Guardian_Kozzalym 55
UPDATE npc_types SET loottable_id = :westwastes_harla_dar_lt: WHERE id in (120057); # Harla_Dar 66
UPDATE npc_types SET loottable_id = :westwastes_hechaeva_lt: WHERE id in (120043); # Hechaeva 54
UPDATE npc_types SET loottable_id = :westwastes_honvar_lt: WHERE id in (120053); # Honvar 52
UPDATE npc_types SET loottable_id = :westwastes_ionat_lt: WHERE id in (120017); # Ionat 56
UPDATE npc_types SET loottable_id = :westwastes_jen_sapara_lt: WHERE id in (120056); # Jen_Sapara 62
UPDATE npc_types SET loottable_id = :westwastes_jerigozia_lt: WHERE id in (120134); # Jerigozia 58
UPDATE npc_types SET loottable_id = :westwastes_julius_oresko_lt: WHERE id in (120031); # Julius_Oresko 55
UPDATE npc_types SET loottable_id = :westwastes_karkona_lt: WHERE id in (120016); # Karkona 57
UPDATE npc_types SET loottable_id = :westwastes_kar_sapara_lt: WHERE id in (120055); # Kar_Sapara 60
UPDATE npc_types SET loottable_id = :westwastes_klandicar_lt: WHERE id in (120084); # Klandicar 70
UPDATE npc_types SET loottable_id = :westwastes_linbrak_lt: WHERE id in (120106); # Linbrak 53
UPDATE npc_types SET loottable_id = :westwastes_makala_lt: WHERE id in (120108); # Makala 51
UPDATE npc_types SET loottable_id = :westwastes_makil_rargon_lt: WHERE id in (120079); # Makil_Rargon 50
UPDATE npc_types SET loottable_id = :westwastes_mav_sapara_lt: WHERE id in (120111); # Mav_Sapara 60
UPDATE npc_types SET loottable_id = :westwastes_mazi_lt: WHERE id in (120073); # Mazi 54
UPDATE npc_types SET loottable_id = :westwastes_melalafen_lt: WHERE id in (120126); # Melalafen 65
UPDATE npc_types SET loottable_id = :westwastes_myga_lt: WHERE id in (120087); # Myga 52
UPDATE npc_types SET loottable_id = :westwastes_neordla_lt: WHERE id in (120114); # Neordla 57
UPDATE npc_types SET loottable_id = :westwastes_onava_lt: WHERE id in (120107); # Onava 54
UPDATE npc_types SET loottable_id = :westwastes_pantrilla_lt: WHERE id in (120006); # Pantrilla 53
UPDATE npc_types SET loottable_id = :westwastes_quoza_lt: WHERE id in (120123); # Quoza 54
UPDATE npc_types SET loottable_id = :westwastes_rak_sapara_lt: WHERE id in (120105); # Rak_Sapara 59
UPDATE npc_types SET loottable_id = :westwastes_rontar_okarn_lt: WHERE id in (120028); # Rontar_O`Karn 55
UPDATE npc_types SET loottable_id = :westwastes_sadeem_oujva_lt: WHERE id in (120029); # Sadeem_Oujva 55
UPDATE npc_types SET loottable_id = :westwastes_scout_pirri_lt: WHERE id in (120132); # Scout_Pirri 75
UPDATE npc_types SET loottable_id = :westwastes_shardwing_courier_lt: WHERE id in (120052); # Shardwing_Courier 50
UPDATE npc_types SET loottable_id = :westwastes_sir_elmonious_falmont_lt: WHERE id in (120133); # Sir_Elmonious_Falmont 70
UPDATE npc_types SET loottable_id = :westwastes_sivar_lt: WHERE id in (120113); # Sivar 53
UPDATE npc_types SET loottable_id = :westwastes_sontalak_lt: WHERE id in (120005); # Sontalak 70
UPDATE npc_types SET loottable_id = :westwastes_the_dragon_sage_lt: WHERE id in (120066); # The_Dragon_Sage 60
UPDATE npc_types SET loottable_id = :westwastes_tranala_lt: WHERE id in (120076); # Tranala 66
UPDATE npc_types SET loottable_id = :westwastes_uiliak_lt: WHERE id in (120117); # Uiliak 53
UPDATE npc_types SET loottable_id = :westwastes_veredenia_lt: WHERE id in (120135); # Veredenia 55
UPDATE npc_types SET loottable_id = :westwastes_vitaela_lt: WHERE id in (120042); # Vitaela 53
UPDATE npc_types SET loottable_id = :westwastes_vraptin_lt: WHERE id in (120008); # Vraptin 53
UPDATE npc_types SET loottable_id = :westwastes_yeldema_lt: WHERE id in (120025); # Yeldema 52
UPDATE npc_types SET loottable_id = :westwastes_you_lt: WHERE id in (120110); # You 60
