INSERT INTO loottable(name) VALUES('westwastes_amcilla'); # :westwastes_amcilla_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_banished_efreeti'); # :westwastes_a_banished_efreeti_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_kromzek_captain'); # :westwastes_a_kromzek_captain_lt:
INSERT INTO loottable(name) VALUES('westwastes_cargalia'); # :westwastes_cargalia_lt:
INSERT INTO loottable(name) VALUES('westwastes_diddugu'); # :westwastes_diddugu_lt:
INSERT INTO loottable(name) VALUES('westwastes_icehackle'); # :westwastes_icehackle_lt:
INSERT INTO loottable(name) VALUES('westwastes_mraaka'); # :westwastes_mraaka_lt:
INSERT INTO loottable(name) VALUES('westwastes_nintal'); # :westwastes_nintal_lt:
INSERT INTO loottable(name) VALUES('westwastes_scout_charisa'); # :westwastes_scout_charisa_lt:
INSERT INTO loottable(name) VALUES('westwastes_scout_pirri'); # :westwastes_scout_pirri_lt:
INSERT INTO loottable(name) VALUES('westwastes_strong_horn'); # :westwastes_strong_horn_lt:
INSERT INTO loottable(name) VALUES('westwastes_tantor'); # :westwastes_tantor_lt:
INSERT INTO loottable(name) VALUES('westwastes_travala'); # :westwastes_travala_lt:
INSERT INTO loottable(name) VALUES('westwastes_tsiraka'); # :westwastes_tsiraka_lt:
INSERT INTO loottable(name) VALUES('westwastes_vohnkare'); # :westwastes_vohnkare_lt:
INSERT INTO loottable(name) VALUES('westwastes_von'); # :westwastes_von_lt:
INSERT INTO loottable(name) VALUES('westwastes_yal'); # :westwastes_yal_lt:
INSERT INTO loottable(name) VALUES('westwastes_zil_sapara'); # :westwastes_zil_sapara_lt:
INSERT INTO loottable(name) VALUES('westwastes_an_elder_wyvern'); # :westwastes_an_elder_wyvern_lt:
INSERT INTO loottable(name) VALUES('westwastes_an_ice_burrower'); # :westwastes_an_ice_burrower_lt:
INSERT INTO loottable(name) VALUES('westwastes_atpaev'); # :westwastes_atpaev_lt:
INSERT INTO loottable(name) VALUES('westwastes_ayillish'); # :westwastes_ayillish_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_brontotherium'); # :westwastes_a_brontotherium_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_burrowing_wyvern'); # :westwastes_a_burrowing_wyvern_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_cragwyrm'); # :westwastes_a_cragwyrm_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_drake'); # :westwastes_a_drake_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_drake_outcast'); # :westwastes_a_drake_outcast_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_glacier_mastodon'); # :westwastes_a_glacier_mastodon_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_gravid_drake'); # :westwastes_a_gravid_drake_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_kromzek_warrior'); # :westwastes_a_kromzek_warrior_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_lindwyrm'); # :westwastes_a_lindwyrm_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_lost_tomekeeper'); # :westwastes_a_lost_tomekeeper_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_neuralgic_huntress'); # :westwastes_a_neuralgic_huntress_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_rogue_dire_wolf'); # :westwastes_a_rogue_dire_wolf_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_scar_guardian'); # :westwastes_a_scar_guardian_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_sentinels_voice'); # :westwastes_a_sentinels_voice_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_shipwrecked_pirate'); # :westwastes_a_shipwrecked_pirate_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_slain_dragon'); # :westwastes_a_slain_dragon_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_velious_drake'); # :westwastes_a_velious_drake_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_velium_hound'); # :westwastes_a_velium_hound_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_wayward_wyvern'); # :westwastes_a_wayward_wyvern_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_wyvern'); # :westwastes_a_wyvern_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_wyvern_hunter'); # :westwastes_a_wyvern_hunter_lt:
INSERT INTO loottable(name) VALUES('westwastes_a_wyvern_huntress'); # :westwastes_a_wyvern_huntress_lt:
INSERT INTO loottable(name) VALUES('westwastes_bratavar'); # :westwastes_bratavar_lt:
INSERT INTO loottable(name) VALUES('westwastes_breezeboot_swordrattler'); # :westwastes_breezeboot_swordrattler_lt:
INSERT INTO loottable(name) VALUES('westwastes_bronif_snowchipper'); # :westwastes_bronif_snowchipper_lt:
INSERT INTO loottable(name) VALUES('westwastes_bufa'); # :westwastes_bufa_lt:
INSERT INTO loottable(name) VALUES('westwastes_chief_engineer_tocs'); # :westwastes_chief_engineer_tocs_lt:
INSERT INTO loottable(name) VALUES('westwastes_crial'); # :westwastes_crial_lt:
INSERT INTO loottable(name) VALUES('westwastes_del_sapara'); # :westwastes_del_sapara_lt:
INSERT INTO loottable(name) VALUES('westwastes_derasinal'); # :westwastes_derasinal_lt:
INSERT INTO loottable(name) VALUES('westwastes_disciple_of_moon'); # :westwastes_disciple_of_moon_lt:
INSERT INTO loottable(name) VALUES('westwastes_disciple_of_moon_trap'); # :westwastes_disciple_of_moon_trap_lt:
INSERT INTO loottable(name) VALUES('westwastes_draazak'); # :westwastes_draazak_lt:
INSERT INTO loottable(name) VALUES('westwastes_entariz'); # :westwastes_entariz_lt:
INSERT INTO loottable(name) VALUES('westwastes_esorpa_of_the_ring'); # :westwastes_esorpa_of_the_ring_lt:
INSERT INTO loottable(name) VALUES('westwastes_gafala'); # :westwastes_gafala_lt:
INSERT INTO loottable(name) VALUES('westwastes_gangel'); # :westwastes_gangel_lt:
INSERT INTO loottable(name) VALUES('westwastes_glati'); # :westwastes_glati_lt:
INSERT INTO loottable(name) VALUES('westwastes_grenth_drakebane'); # :westwastes_grenth_drakebane_lt:
INSERT INTO loottable(name) VALUES('westwastes_guardian_kozzalym'); # :westwastes_guardian_kozzalym_lt:
INSERT INTO loottable(name) VALUES('westwastes_harla_dar'); # :westwastes_harla_dar_lt:
INSERT INTO loottable(name) VALUES('westwastes_hechaeva'); # :westwastes_hechaeva_lt:
INSERT INTO loottable(name) VALUES('westwastes_honvar'); # :westwastes_honvar_lt:
INSERT INTO loottable(name) VALUES('westwastes_ionat'); # :westwastes_ionat_lt:
INSERT INTO loottable(name) VALUES('westwastes_jen_sapara'); # :westwastes_jen_sapara_lt:
INSERT INTO loottable(name) VALUES('westwastes_jerigozia'); # :westwastes_jerigozia_lt:
INSERT INTO loottable(name) VALUES('westwastes_julius_oresko'); # :westwastes_julius_oresko_lt:
INSERT INTO loottable(name) VALUES('westwastes_karkona'); # :westwastes_karkona_lt:
INSERT INTO loottable(name) VALUES('westwastes_kar_sapara'); # :westwastes_kar_sapara_lt:
INSERT INTO loottable(name) VALUES('westwastes_klandicar'); # :westwastes_klandicar_lt:
INSERT INTO loottable(name) VALUES('westwastes_linbrak'); # :westwastes_linbrak_lt:
INSERT INTO loottable(name) VALUES('westwastes_makala'); # :westwastes_makala_lt:
INSERT INTO loottable(name) VALUES('westwastes_makil_rargon'); # :westwastes_makil_rargon_lt:
INSERT INTO loottable(name) VALUES('westwastes_mav_sapara'); # :westwastes_mav_sapara_lt:
INSERT INTO loottable(name) VALUES('westwastes_mazi'); # :westwastes_mazi_lt:
INSERT INTO loottable(name) VALUES('westwastes_melalafen'); # :westwastes_melalafen_lt:
INSERT INTO loottable(name) VALUES('westwastes_myga'); # :westwastes_myga_lt:
INSERT INTO loottable(name) VALUES('westwastes_neordla'); # :westwastes_neordla_lt:
INSERT INTO loottable(name) VALUES('westwastes_onava'); # :westwastes_onava_lt:
INSERT INTO loottable(name) VALUES('westwastes_pantrilla'); # :westwastes_pantrilla_lt:
INSERT INTO loottable(name) VALUES('westwastes_quoza'); # :westwastes_quoza_lt:
INSERT INTO loottable(name) VALUES('westwastes_rak_sapara'); # :westwastes_rak_sapara_lt:
INSERT INTO loottable(name) VALUES('westwastes_rontar_okarn'); # :westwastes_rontar_okarn_lt:
INSERT INTO loottable(name) VALUES('westwastes_sadeem_oujva'); # :westwastes_sadeem_oujva_lt:
INSERT INTO loottable(name) VALUES('westwastes_scout_pirri'); # :westwastes_scout_pirri_lt:
INSERT INTO loottable(name) VALUES('westwastes_shardwing_courier'); # :westwastes_shardwing_courier_lt:
INSERT INTO loottable(name) VALUES('westwastes_sir_elmonious_falmont'); # :westwastes_sir_elmonious_falmont_lt:
INSERT INTO loottable(name) VALUES('westwastes_sivar'); # :westwastes_sivar_lt:
INSERT INTO loottable(name) VALUES('westwastes_sontalak'); # :westwastes_sontalak_lt:
INSERT INTO loottable(name) VALUES('westwastes_the_dragon_sage'); # :westwastes_the_dragon_sage_lt:
INSERT INTO loottable(name) VALUES('westwastes_tranala'); # :westwastes_tranala_lt:
INSERT INTO loottable(name) VALUES('westwastes_uiliak'); # :westwastes_uiliak_lt:
INSERT INTO loottable(name) VALUES('westwastes_veredenia'); # :westwastes_veredenia_lt:
INSERT INTO loottable(name) VALUES('westwastes_vitaela'); # :westwastes_vitaela_lt:
INSERT INTO loottable(name) VALUES('westwastes_vraptin'); # :westwastes_vraptin_lt:
INSERT INTO loottable(name) VALUES('westwastes_yeldema'); # :westwastes_yeldema_lt:
INSERT INTO loottable(name) VALUES('westwastes_you'); # :westwastes_you_lt:
