INSERT INTO loottable(name) VALUES('atiiki_'); # :atiiki__lt:
INSERT INTO loottable(name) VALUES('atiiki_hand_of_dezthazkekol'); # :atiiki_hand_of_dezthazkekol_lt:
INSERT INTO loottable(name) VALUES('atiiki_noble_mhrat'); # :atiiki_noble_mhrat_lt:
INSERT INTO loottable(name) VALUES('atiiki_noble_phren'); # :atiiki_noble_phren_lt:
INSERT INTO loottable(name) VALUES('atiiki_noble_sivrn'); # :atiiki_noble_sivrn_lt:
INSERT INTO loottable(name) VALUES('atiiki_phobolyten'); # :atiiki_phobolyten_lt:
INSERT INTO loottable(name) VALUES('atiiki_rockstorm'); # :atiiki_rockstorm_lt:
INSERT INTO loottable(name) VALUES('atiiki_akarahotuten'); # :atiiki_akarahotuten_lt:
INSERT INTO loottable(name) VALUES('atiiki_an_efreeti_enthraller'); # :atiiki_an_efreeti_enthraller_lt:
INSERT INTO loottable(name) VALUES('atiiki_an_efreeti_lord'); # :atiiki_an_efreeti_lord_lt:
INSERT INTO loottable(name) VALUES('atiiki_an_efreeti_sorceror'); # :atiiki_an_efreeti_sorceror_lt:
INSERT INTO loottable(name) VALUES('atiiki_azia'); # :atiiki_azia_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_crag_ravager'); # :atiiki_a_crag_ravager_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_decaying_mummy'); # :atiiki_a_decaying_mummy_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_frenzied_gorilla'); # :atiiki_a_frenzied_gorilla_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_glowing_scarab'); # :atiiki_a_glowing_scarab_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_large_scorpion'); # :atiiki_a_large_scorpion_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_photoplasm'); # :atiiki_a_photoplasm_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_pristine_scarab'); # :atiiki_a_pristine_scarab_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_rhinoback_beetle'); # :atiiki_a_rhinoback_beetle_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_scatterback_scarab'); # :atiiki_a_scatterback_scarab_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_turtle'); # :atiiki_a_turtle_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_whirling_dervish'); # :atiiki_a_whirling_dervish_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_winged_conjurer'); # :atiiki_a_winged_conjurer_lt:
INSERT INTO loottable(name) VALUES('atiiki_a_winged_evoker'); # :atiiki_a_winged_evoker_lt:
INSERT INTO loottable(name) VALUES('atiiki_beza'); # :atiiki_beza_lt:
INSERT INTO loottable(name) VALUES('atiiki_caza'); # :atiiki_caza_lt:
INSERT INTO loottable(name) VALUES('atiiki_dena'); # :atiiki_dena_lt:
INSERT INTO loottable(name) VALUES('atiiki_dezthazkekol'); # :atiiki_dezthazkekol_lt:
INSERT INTO loottable(name) VALUES('atiiki_earthen_sentinel'); # :atiiki_earthen_sentinel_lt:
INSERT INTO loottable(name) VALUES('atiiki_ena'); # :atiiki_ena_lt:
INSERT INTO loottable(name) VALUES('atiiki_fana'); # :atiiki_fana_lt:
INSERT INTO loottable(name) VALUES('atiiki_geza'); # :atiiki_geza_lt:
INSERT INTO loottable(name) VALUES('atiiki_gigias'); # :atiiki_gigias_lt:
INSERT INTO loottable(name) VALUES('atiiki_heda'); # :atiiki_heda_lt:
INSERT INTO loottable(name) VALUES('atiiki_izah'); # :atiiki_izah_lt:
INSERT INTO loottable(name) VALUES('atiiki_jaka'); # :atiiki_jaka_lt:
INSERT INTO loottable(name) VALUES('atiiki_kala'); # :atiiki_kala_lt:
INSERT INTO loottable(name) VALUES('atiiki_kikinkoutepmozha'); # :atiiki_kikinkoutepmozha_lt:
INSERT INTO loottable(name) VALUES('atiiki_lathik'); # :atiiki_lathik_lt:
INSERT INTO loottable(name) VALUES('atiiki_lena'); # :atiiki_lena_lt:
INSERT INTO loottable(name) VALUES('atiiki_mahatototarit'); # :atiiki_mahatototarit_lt:
INSERT INTO loottable(name) VALUES('atiiki_meda'); # :atiiki_meda_lt:
INSERT INTO loottable(name) VALUES('atiiki_medious'); # :atiiki_medious_lt:
INSERT INTO loottable(name) VALUES('atiiki_neza'); # :atiiki_neza_lt:
INSERT INTO loottable(name) VALUES('atiiki_osinzuhazhfet'); # :atiiki_osinzuhazhfet_lt:
INSERT INTO loottable(name) VALUES('atiiki_ozah'); # :atiiki_ozah_lt:
INSERT INTO loottable(name) VALUES('atiiki_queltizenzumotif'); # :atiiki_queltizenzumotif_lt:
INSERT INTO loottable(name) VALUES('atiiki_rock_sentinel'); # :atiiki_rock_sentinel_lt:
INSERT INTO loottable(name) VALUES('atiiki_rohtrepoten'); # :atiiki_rohtrepoten_lt:
INSERT INTO loottable(name) VALUES('atiiki_sand_sentinel'); # :atiiki_sand_sentinel_lt:
INSERT INTO loottable(name) VALUES('atiiki_shelfezmaken'); # :atiiki_shelfezmaken_lt:
INSERT INTO loottable(name) VALUES('atiiki_simulat'); # :atiiki_simulat_lt:
INSERT INTO loottable(name) VALUES('atiiki_tekelfotonan'); # :atiiki_tekelfotonan_lt:
INSERT INTO loottable(name) VALUES('atiiki_tiniz'); # :atiiki_tiniz_lt:
INSERT INTO loottable(name) VALUES('atiiki_vizhizshazid'); # :atiiki_vizhizshazid_lt:
INSERT INTO loottable(name) VALUES('atiiki_xanxionusus'); # :atiiki_xanxionusus_lt:
INSERT INTO loottable(name) VALUES('atiiki_yinihortinkah'); # :atiiki_yinihortinkah_lt:
INSERT INTO loottable(name) VALUES('atiiki__'); # :atiiki___lt:
