(:kattacastrum_a_vestigia_sentinel_lt:, :fine_steel_ld:, 1),
(:kattacastrum_praecantor_jumais_lt:, :fine_steel_ld:, 1),
(:kattacastrum_praecantor_jumais_lt:, :human_parts_ld:, 1),
(:kattacastrum_a_vestigia_sentinel_lt:, :human_parts_ld:, 1),
(:kattacastrum_praecantor_jumais_lt:, :human_blood_ld:, 1),
(:kattacastrum_a_vestigia_sentinel_lt:, :human_blood_ld:, 1),
(:kattacastrum_a_darkmud_slave_lt:, :iron_oxide_ld:, 1),
(:kattacastrum_a_darkmud_keeper_lt:, :iron_oxide_ld:, 1),
