UPDATE npc_types SET loottable_id = :kattacastrum__lt: WHERE id in (416073); #  75
UPDATE npc_types SET loottable_id = :kattacastrum_alchemist_hesia_lt: WHERE id in (416003); # #Alchemist_Hesia 75
UPDATE npc_types SET loottable_id = :kattacastrum_arcanist_thalian_lt: WHERE id in (416025); # #Arcanist_Thalian 75
UPDATE npc_types SET loottable_id = :kattacastrum_arcanist_variszh_lt: WHERE id in (416144); # #Arcanist_Variszh 75
UPDATE npc_types SET loottable_id = :kattacastrum_chief_librarian_lars_lt: WHERE id in (416093); # #Chief_Librarian_Lars 75
UPDATE npc_types SET loottable_id = :kattacastrum_commander_zzarishazum_lt: WHERE id in (416167); # #Commander_Zzarishazum 78
UPDATE npc_types SET loottable_id = :kattacastrum_guard_captain_parvus_lt: WHERE id in (416035); # #Guard_Captain_Parvus 75
UPDATE npc_types SET loottable_id = :kattacastrum_portalmaster_temuratis_lt: WHERE id in (416141); # #Portalmaster_Temuratis 70
UPDATE npc_types SET loottable_id = :kattacastrum_spiritflame_of_the_drowned_lt: WHERE id in (416138); # #Spiritflame_of_the_Drowned 80
UPDATE npc_types SET loottable_id = :kattacastrum_structural_engineer_dewas_lt: WHERE id in (416033); # #Structural_Engineer_Dewas 80
UPDATE npc_types SET loottable_id = :kattacastrum_an_amalgam_of_the_drowned_lt: WHERE id in (416142, 416149, 416158); # an_amalgam_of_the_drowned 76
UPDATE npc_types SET loottable_id = :kattacastrum_an_animated_agent_of_zhisza_lt: WHERE id in (416124, 416148, 416163); # an_animated_agent_of_Zhisza 75
UPDATE npc_types SET loottable_id = :kattacastrum_an_animated_servant_of_zhisza_lt: WHERE id in (416126, 416128, 416130); # an_animated_servant_of_Zhisza 75
UPDATE npc_types SET loottable_id = :kattacastrum_an_elite_acolyte_lt: WHERE id in (416110, 416113, 416164); # an_elite_acolyte 77
UPDATE npc_types SET loottable_id = :kattacastrum_an_elite_arcanist_lt: WHERE id in (416083, 416108); # an_elite_arcanist 79
UPDATE npc_types SET loottable_id = :kattacastrum_an_elite_nightfang_lt: WHERE id in (416106, 416112, 416161); # an_elite_nightfang 79
UPDATE npc_types SET loottable_id = :kattacastrum_an_elite_revenant_lt: WHERE id in (416114); # an_elite_revenant 78
UPDATE npc_types SET loottable_id = :kattacastrum_an_elite_spiritward_lt: WHERE id in (416115, 416153, 416166); # an_elite_spiritward 77
UPDATE npc_types SET loottable_id = :kattacastrum_an_elite_tormentor_lt: WHERE id in (416165); # an_elite_tormentor 75
UPDATE npc_types SET loottable_id = :kattacastrum_an_essence_of_the_deep_lt: WHERE id in (416052, 416087, 416150); # an_essence_of_the_deep 75
UPDATE npc_types SET loottable_id = :kattacastrum_arcanist_tivalin_lt: WHERE id in (416016); # Arcanist_Tivalin 80
UPDATE npc_types SET loottable_id = :kattacastrum_archarcanist_kirstmycl_lt: WHERE id in (416062); # Archarcanist_Kirstmycl 75
UPDATE npc_types SET loottable_id = :kattacastrum_archarcanist_pintanus_lt: WHERE id in (416024); # Archarcanist_Pintanus 70
UPDATE npc_types SET loottable_id = :kattacastrum_associate_researcher_maladoks_lt: WHERE id in (416015); # Associate_Researcher_Maladoks 70
UPDATE npc_types SET loottable_id = :kattacastrum_associate_researcher_plik_lt: WHERE id in (416011); # Associate_Researcher_Plik 70
UPDATE npc_types SET loottable_id = :kattacastrum_a_castrum_praetoria_lt: WHERE id in (416022, 416046); # a_Castrum_praetoria 1
UPDATE npc_types SET loottable_id = :kattacastrum_a_castrum_praetorian_lt: WHERE id in (416018); # a_Castrum_praetorian 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_combine_praecantor_lt: WHERE id in (416012, 416020); # a_Combine_praecantor 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_combine_theurgus_lt: WHERE id in (416029); # a_Combine_theurgus 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_construct_of_the_drowned_lt: WHERE id in (416092, 416096, 416136); # a_construct_of_the_drowned 73
UPDATE npc_types SET loottable_id = :kattacastrum_a_darkmud_keeper_lt: WHERE id in (416139, 416151, 416152); # a_darkmud_keeper 74
UPDATE npc_types SET loottable_id = :kattacastrum_a_darkmud_slave_lt: WHERE id in (416045, 416051, 416075); # a_darkmud_slave 74
UPDATE npc_types SET loottable_id = :kattacastrum_a_fear_funnel_lt: WHERE id in (416145, 416154, 416156); # a_fear_funnel 76
UPDATE npc_types SET loottable_id = :kattacastrum_a_fire_whisperer_lt: WHERE id in (416088, 416157, 416159); # a_fire_whisperer 76
UPDATE npc_types SET loottable_id = :kattacastrum_a_flame_whisperer_lt: WHERE id in (416077, 416085, 416094); # a_flame_whisperer 74
UPDATE npc_types SET loottable_id = :kattacastrum_a_frenzied_whirlpool_lt: WHERE id in (416119, 416169); # a_frenzied_whirlpool 74
UPDATE npc_types SET loottable_id = :kattacastrum_a_fright_funnel_lt: WHERE id in (416065, 416067, 416123); # a_fright_funnel 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_haggler_lt: WHERE id in (416048); # a_haggler 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_librarii_legionnaire_lt: WHERE id in (416072, 416086); # a_Librarii_legionnaire 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_prayermaker_of_zhisza_lt: WHERE id in (416120, 416125, 416129); # a_prayermaker_of_Zhisza 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_scruffy_beggar_lt: WHERE id in (416037); # a_scruffy_beggar 70
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_alchemist_lt: WHERE id in (416170, 416171); # a_Shissar_alchemist 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_arbiter_lt: WHERE id in (416074, 416082, 416105); # a_Shissar_arbiter 74
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_firetongue_lt: WHERE id in (416099, 416101, 416109); # a_Shissar_firetongue 74
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_herb_tender_lt: WHERE id in (416162, 416168); # a_Shissar_herb_tender 73
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_revenant_lt: WHERE id in (416080, 416118, 416122); # a_Shissar_revenant 73
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_shadowslither_lt: WHERE id in (416098, 416104, 416143); # a_Shissar_shadowslither 74
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_spiritbinder_lt: WHERE id in (416089, 416095); # a_Shissar_spiritbinder 74
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_taskmaster_lt: WHERE id in (416111, 416155, 416160); # a_Shissar_taskmaster 77
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_templar_lt: WHERE id in (416090, 416107, 416131); # a_Shissar_templar 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_terrorfang_lt: WHERE id in (416079, 416091, 416117); # a_Shissar_terrorfang 73
UPDATE npc_types SET loottable_id = :kattacastrum_a_shissar_wraithmaker_lt: WHERE id in (416100, 416127, 416132); # a_Shissar_wraithmaker 77
UPDATE npc_types SET loottable_id = :kattacastrum_a_spiritcore_of_zhisza_lt: WHERE id in (416133, 416146, 416147); # a_spiritcore_of_Zhisza 74
UPDATE npc_types SET loottable_id = :kattacastrum_a_supplier_lt: WHERE id in (416040, 416058); # a_supplier 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_tatty_beggar_lt: WHERE id in (416043); # a_tatty_beggar 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_vestigia_sentinel_lt: WHERE id in (416135, 416137); # a_Vestigia_sentinel 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_vortex_of_the_deep_lt: WHERE id in (416056, 416081, 416084); # a_vortex_of_the_deep 75
UPDATE npc_types SET loottable_id = :kattacastrum_a_wayward_whirlpool_eddy_lt: WHERE id in (416097, 416102, 416121); # a_wayward_whirlpool_eddy 75
UPDATE npc_types SET loottable_id = :kattacastrum_flora_venloe_lt: WHERE id in (416055); # Flora_Venloe 70
UPDATE npc_types SET loottable_id = :kattacastrum_fsp-general-noeffect_lt: WHERE id in (416063); # FSP-General-NoEffect 1
UPDATE npc_types SET loottable_id = :kattacastrum_head_attendant_haestus_lt: WHERE id in (416005); # Head_Attendant_Haestus 80
UPDATE npc_types SET loottable_id = :kattacastrum_head_mage_antius_lt: WHERE id in (416021); # Head_Mage_Antius 75
UPDATE npc_types SET loottable_id = :kattacastrum_historian_divinicus_lt: WHERE id in (416019); # Historian_Divinicus 75
UPDATE npc_types SET loottable_id = :kattacastrum_lifekeeper_of_the_beloved_lt: WHERE id in (416009); # Lifekeeper_of_the_Beloved 75
UPDATE npc_types SET loottable_id = :kattacastrum_lucius_lt: WHERE id in (416026); # Lucius 99
UPDATE npc_types SET loottable_id = :kattacastrum_master_archimetus_lt: WHERE id in (416054); # Master_Archimetus 75
UPDATE npc_types SET loottable_id = :kattacastrum_master_cappello_lt: WHERE id in (416070); # Master_Cappello 75
UPDATE npc_types SET loottable_id = :kattacastrum_master_dammara_lt: WHERE id in (416060); # Master_Dammara 75
UPDATE npc_types SET loottable_id = :kattacastrum_master_ellestellian_lt: WHERE id in (416044); # Master_Ellestellian 75
UPDATE npc_types SET loottable_id = :kattacastrum_master_gulliastus_lt: WHERE id in (416064); # Master_Gulliastus 75
UPDATE npc_types SET loottable_id = :kattacastrum_master_nemetis_lt: WHERE id in (416053); # Master_Nemetis 75
UPDATE npc_types SET loottable_id = :kattacastrum_master_patales_lt: WHERE id in (416036); # Master_Patales 75
UPDATE npc_types SET loottable_id = :kattacastrum_master_pokk_lt: WHERE id in (416039); # Master_Pokk 75
UPDATE npc_types SET loottable_id = :kattacastrum_master_renalto_lt: WHERE id in (416042); # Master_Renalto 75
UPDATE npc_types SET loottable_id = :kattacastrum_master_ulyssus_lt: WHERE id in (416038); # Master_Ulyssus 75
UPDATE npc_types SET loottable_id = :kattacastrum_orator_niluna_lt: WHERE id in (416116); # Orator_Niluna 75
UPDATE npc_types SET loottable_id = :kattacastrum_pius_loravia_lt: WHERE id in (416027); # Pius_Loravia 75
UPDATE npc_types SET loottable_id = :kattacastrum_praecantor_jumais_lt: WHERE id in (416031); # Praecantor_Jumais 75
UPDATE npc_types SET loottable_id = :kattacastrum_praecantor_tunderon_lt: WHERE id in (416030); # Praecantor_Tunderon 75
UPDATE npc_types SET loottable_id = :kattacastrum_prime_researcher_elnot_waymun_lt: WHERE id in (416006); # Prime_Researcher_Elnot_Waymun 75
UPDATE npc_types SET loottable_id = :kattacastrum_researcher_chlearpa_lt: WHERE id in (416017); # Researcher_Chlearpa 75
UPDATE npc_types SET loottable_id = :kattacastrum_scribe_oastalides_lt: WHERE id in (416013); # Scribe_Oastalides 75
UPDATE npc_types SET loottable_id = :kattacastrum_seer_ichamedes_lt: WHERE id in (416004); # Seer_Ichamedes 75
UPDATE npc_types SET loottable_id = :kattacastrum_sergeant_zetren_lt: WHERE id in (416034); # Sergeant_Zetren 1
UPDATE npc_types SET loottable_id = :kattacastrum_simus_the_doomsayer_lt: WHERE id in (416000); # Simus_the_Doomsayer 75
UPDATE npc_types SET loottable_id = :kattacastrum_sorcerer_hearah_lt: WHERE id in (416014); # Sorcerer_Hearah 75
UPDATE npc_types SET loottable_id = :kattacastrum_sorcerer_xycl_lt: WHERE id in (416010); # Sorcerer_Xycl 80
UPDATE npc_types SET loottable_id = :kattacastrum_sorcerer_yurius_lt: WHERE id in (416001); # Sorcerer_Yurius 75
UPDATE npc_types SET loottable_id = :kattacastrum_tactician_sodut_lt: WHERE id in (416032); # Tactician_Sodut 80
UPDATE npc_types SET loottable_id = :kattacastrum_the_town_crier_lt: WHERE id in (416069); # The_Town_Crier 75
UPDATE npc_types SET loottable_id = :kattacastrum_titus_lt: WHERE id in (416028); # Titus 99
UPDATE npc_types SET loottable_id = :kattacastrum_torrence_ire_lt: WHERE id in (416023); # Torrence_Ire 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_avatticus_lt: WHERE id in (416078); # Trader_Avatticus 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_bartus_lt: WHERE id in (416068); # Trader_Bartus 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_dammides_lt: WHERE id in (416071); # Trader_Dammides 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_difius_lt: WHERE id in (416050); # Trader_Difius 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_gulleus_lt: WHERE id in (416061); # Trader_Gulleus 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_hyalunes_lt: WHERE id in (416041); # Trader_Hyalunes 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_leanian_lt: WHERE id in (416059); # Trader_Leanian 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_markus_lt: WHERE id in (416057); # Trader_Markus 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_othena_lt: WHERE id in (416066); # Trader_Othena 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_thallynus_lt: WHERE id in (416049); # Trader_Thallynus 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_vallarines_lt: WHERE id in (416047); # Trader_Vallarines 75
UPDATE npc_types SET loottable_id = :kattacastrum_trader_varrina_lt: WHERE id in (416076); # Trader_Varrina 75
UPDATE npc_types SET loottable_id = :kattacastrum_tsaph_katta_lt: WHERE id in (416008); # Tsaph_Katta 75
UPDATE npc_types SET loottable_id = :kattacastrum_tuzart_relenfold_lt: WHERE id in (416002); # Tuzart_Relenfold 1
UPDATE npc_types SET loottable_id = :kattacastrum_vizier_zio_lt: WHERE id in (416140); # Vizier_Zio 75
UPDATE npc_types SET loottable_id = :kattacastrum___lt: WHERE id in (416007, 416103, 416134); # _ 75
