(:maidensgrave_a_cursed_pirate_lt:, :skeleton_parts_ld:, 1),
(:maidensgrave_a_tortured_sailor_lt:, :skeleton_parts_ld:, 1),
(:maidensgrave_a_cursed_pirate_lt:, :bone_chips_ld:, 1),
(:maidensgrave_a_tortured_sailor_lt:, :bone_chips_ld:, 1),
(:maidensgrave_a_siren_spitfire_lt:, :scale_ore_ld:, 1),
(:maidensgrave_a_cursed_pirate_lt:, :scale_ore_ld:, 1),
