INSERT INTO loottable(name) VALUES('redfeather_gurada_the_sea_singer'); # :redfeather_gurada_the_sea_singer_lt:
INSERT INTO loottable(name) VALUES('redfeather_king_peleke'); # :redfeather_king_peleke_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_feral_puma'); # :redfeather_a_feral_puma_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_rabid_basilisk'); # :redfeather_a_rabid_basilisk_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_regrua_aggressor'); # :redfeather_a_regrua_aggressor_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_regrua_diviner'); # :redfeather_a_regrua_diviner_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_regrua_seaskimmer'); # :redfeather_a_regrua_seaskimmer_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_savage_raptor'); # :redfeather_a_savage_raptor_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_stormscape_kingsguard'); # :redfeather_a_stormscape_kingsguard_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_stormscape_rook'); # :redfeather_a_stormscape_rook_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_stormscape_skyknight'); # :redfeather_a_stormscape_skyknight_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_stormscape_skymage'); # :redfeather_a_stormscape_skymage_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_stormscape_skypriest'); # :redfeather_a_stormscape_skypriest_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_stormscape_soothsayer'); # :redfeather_a_stormscape_soothsayer_lt:
INSERT INTO loottable(name) VALUES('redfeather_a_stormscape_spellbinder'); # :redfeather_a_stormscape_spellbinder_lt:
INSERT INTO loottable(name) VALUES('redfeather_stormscape_crusader'); # :redfeather_stormscape_crusader_lt:
INSERT INTO loottable(name) VALUES('redfeather_stormscape_high_priest'); # :redfeather_stormscape_high_priest_lt:
INSERT INTO loottable(name) VALUES('redfeather_stormscape_warder'); # :redfeather_stormscape_warder_lt:
INSERT INTO loottable(name) VALUES('redfeather__'); # :redfeather___lt:
