UPDATE npc_types SET loottable_id = :thalassius_muckdiver_lt: WHERE id in (417009); # #Muckdiver 75
UPDATE npc_types SET loottable_id = :thalassius_phyrael_mollotus_lt: WHERE id in (417036); # #Phyrael_Mollotus 74
UPDATE npc_types SET loottable_id = :thalassius_rockcrusher_lt: WHERE id in (417003); # #Rockcrusher 75
UPDATE npc_types SET loottable_id = :thalassius_wavecrasher_lt: WHERE id in (417029); # #Wavecrasher 73
UPDATE npc_types SET loottable_id = :thalassius_an_elemental_construct_lt: WHERE id in (417022); # an_elemental_construct 73
UPDATE npc_types SET loottable_id = :thalassius_an_elemental_watershaper_lt: WHERE id in (417030); # an_elemental_watershaper 73
UPDATE npc_types SET loottable_id = :thalassius_an_experimental_kedge_arcanist_lt: WHERE id in (417026); # an_experimental_Kedge_arcanist 76
UPDATE npc_types SET loottable_id = :thalassius_an_experimental_kedge_champion_lt: WHERE id in (417023); # an_experimental_Kedge_champion 76
UPDATE npc_types SET loottable_id = :thalassius_an_experimental_kedge_overseer_lt: WHERE id in (417028); # an_experimental_Kedge_overseer 76
UPDATE npc_types SET loottable_id = :thalassius_a_brutal_turtle_lt: WHERE id in (417007); # a_brutal_turtle 72
UPDATE npc_types SET loottable_id = :thalassius_a_construct_of_surf_lt: WHERE id in (417019); # a_construct_of_surf 73
UPDATE npc_types SET loottable_id = :thalassius_a_construct_of_water_lt: WHERE id in (417021); # a_construct_of_water 73
UPDATE npc_types SET loottable_id = :thalassius_a_convergence_of_tide_lt: WHERE id in (417032); # a_convergence_of_tide 73
UPDATE npc_types SET loottable_id = :thalassius_a_convergence_of_waves_lt: WHERE id in (417014); # a_convergence_of_waves 73
UPDATE npc_types SET loottable_id = :thalassius_a_hraquis_grunt_lt: WHERE id in (417005); # a_Hraquis_grunt 72
UPDATE npc_types SET loottable_id = :thalassius_a_hraquis_seer_lt: WHERE id in (417025, 417027, 417033, 417000, 417002, 417015, 417016, 417017, 417020); # a_Hraquis_seer 72
UPDATE npc_types SET loottable_id = :thalassius_a_kedge_defender_lt: WHERE id in (417013); # a_Kedge_defender 74
UPDATE npc_types SET loottable_id = :thalassius_a_kedge_oracle_lt: WHERE id in (417011); # a_Kedge_oracle 74
UPDATE npc_types SET loottable_id = :thalassius_a_kedge_watermancer_lt: WHERE id in (417035, 417012); # a_Kedge_Watermancer 74
UPDATE npc_types SET loottable_id = :thalassius_a_puddle_of_water_lt: WHERE id in (417024, 417008); # a_puddle_of_water 74
UPDATE npc_types SET loottable_id = :thalassius_a_regrua_aggressor_lt: WHERE id in (417006); # a_Regrua_aggressor 72
UPDATE npc_types SET loottable_id = :thalassius_a_regrua_naturewalker_lt: WHERE id in (417004); # a_Regrua_naturewalker 72
UPDATE npc_types SET loottable_id = :thalassius_a_sea_dervish_lt: WHERE id in (417031, 417034); # a_sea_dervish 73
UPDATE npc_types SET loottable_id = :thalassius_a_sea_dredger_lt: WHERE id in (417001); # a_sea_dredger 72
UPDATE npc_types SET loottable_id = :thalassius_a_sea_mephit_defender_lt: WHERE id in (417018); # a_sea_mephit_defender 74
UPDATE npc_types SET loottable_id = :thalassius_a_sea_mephit_evoker_lt: WHERE id in (417010); # a_sea_mephit_evoker 74
