INSERT INTO loottable(name) VALUES('thalassius_muckdiver'); # :thalassius_muckdiver_lt:
INSERT INTO loottable(name) VALUES('thalassius_phyrael_mollotus'); # :thalassius_phyrael_mollotus_lt:
INSERT INTO loottable(name) VALUES('thalassius_rockcrusher'); # :thalassius_rockcrusher_lt:
INSERT INTO loottable(name) VALUES('thalassius_wavecrasher'); # :thalassius_wavecrasher_lt:
INSERT INTO loottable(name) VALUES('thalassius_an_elemental_construct'); # :thalassius_an_elemental_construct_lt:
INSERT INTO loottable(name) VALUES('thalassius_an_elemental_watershaper'); # :thalassius_an_elemental_watershaper_lt:
INSERT INTO loottable(name) VALUES('thalassius_an_experimental_kedge_arcanist'); # :thalassius_an_experimental_kedge_arcanist_lt:
INSERT INTO loottable(name) VALUES('thalassius_an_experimental_kedge_champion'); # :thalassius_an_experimental_kedge_champion_lt:
INSERT INTO loottable(name) VALUES('thalassius_an_experimental_kedge_overseer'); # :thalassius_an_experimental_kedge_overseer_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_brutal_turtle'); # :thalassius_a_brutal_turtle_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_construct_of_surf'); # :thalassius_a_construct_of_surf_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_construct_of_water'); # :thalassius_a_construct_of_water_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_convergence_of_tide'); # :thalassius_a_convergence_of_tide_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_convergence_of_waves'); # :thalassius_a_convergence_of_waves_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_hraquis_grunt'); # :thalassius_a_hraquis_grunt_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_hraquis_seer'); # :thalassius_a_hraquis_seer_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_kedge_defender'); # :thalassius_a_kedge_defender_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_kedge_oracle'); # :thalassius_a_kedge_oracle_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_kedge_watermancer'); # :thalassius_a_kedge_watermancer_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_puddle_of_water'); # :thalassius_a_puddle_of_water_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_regrua_aggressor'); # :thalassius_a_regrua_aggressor_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_regrua_naturewalker'); # :thalassius_a_regrua_naturewalker_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_sea_dervish'); # :thalassius_a_sea_dervish_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_sea_dredger'); # :thalassius_a_sea_dredger_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_sea_mephit_defender'); # :thalassius_a_sea_mephit_defender_lt:
INSERT INTO loottable(name) VALUES('thalassius_a_sea_mephit_evoker'); # :thalassius_a_sea_mephit_evoker_lt:
