INSERT INTO loottable(name) VALUES('barindu_abena_taifa'); # :barindu_abena_taifa_lt:
INSERT INTO loottable(name) VALUES('barindu_aneuk_overseer'); # :barindu_aneuk_overseer_lt:
INSERT INTO loottable(name) VALUES('barindu_apprentice_udranda'); # :barindu_apprentice_udranda_lt:
INSERT INTO loottable(name) VALUES('barindu_a_controlled_earth_churner'); # :barindu_a_controlled_earth_churner_lt:
INSERT INTO loottable(name) VALUES('barindu_chiaka_lerato'); # :barindu_chiaka_lerato_lt:
INSERT INTO loottable(name) VALUES('barindu_colossus_of_war'); # :barindu_colossus_of_war_lt:
INSERT INTO loottable(name) VALUES('barindu_construct_of_war'); # :barindu_construct_of_war_lt:
INSERT INTO loottable(name) VALUES('barindu_frenzied_noc_corpsethrasher'); # :barindu_frenzied_noc_corpsethrasher_lt:
INSERT INTO loottable(name) VALUES('barindu_gamesh'); # :barindu_gamesh_lt:
INSERT INTO loottable(name) VALUES('barindu_high_priest_diru_riwirn'); # :barindu_high_priest_diru_riwirn_lt:
INSERT INTO loottable(name) VALUES('barindu_ikaav_ixvet_pox'); # :barindu_ikaav_ixvet_pox_lt:
INSERT INTO loottable(name) VALUES('barindu_jomaj_kaiijin'); # :barindu_jomaj_kaiijin_lt:
INSERT INTO loottable(name) VALUES('barindu_kunimi_falade'); # :barindu_kunimi_falade_lt:
INSERT INTO loottable(name) VALUES('barindu_kyv_rux_vhedt'); # :barindu_kyv_rux_vhedt_lt:
INSERT INTO loottable(name) VALUES('barindu_mastruq_utk_hykat'); # :barindu_mastruq_utk_hykat_lt:
INSERT INTO loottable(name) VALUES('barindu_njanu_dinari'); # :barindu_njanu_dinari_lt:
INSERT INTO loottable(name) VALUES('barindu_proteri_amari'); # :barindu_proteri_amari_lt:
INSERT INTO loottable(name) VALUES('barindu_rasnil_sanusel'); # :barindu_rasnil_sanusel_lt:
INSERT INTO loottable(name) VALUES('barindu_ratuk_kjyt_gykk'); # :barindu_ratuk_kjyt_gykk_lt:
INSERT INTO loottable(name) VALUES('barindu_taiandao'); # :barindu_taiandao_lt:
INSERT INTO loottable(name) VALUES('barindu_talwins_remains'); # :barindu_talwins_remains_lt:
INSERT INTO loottable(name) VALUES('barindu_vasha_firaji'); # :barindu_vasha_firaji_lt:
INSERT INTO loottable(name) VALUES('barindu_viarglug'); # :barindu_viarglug_lt:
INSERT INTO loottable(name) VALUES('barindu_zoner'); # :barindu_zoner_lt:
INSERT INTO loottable(name) VALUES('barindu_zoner_vxed_tipt'); # :barindu_zoner_vxed_tipt_lt:
INSERT INTO loottable(name) VALUES('barindu_aneuk_controller'); # :barindu_aneuk_controller_lt:
INSERT INTO loottable(name) VALUES('barindu_an_aneuk_glyphcaller'); # :barindu_an_aneuk_glyphcaller_lt:
INSERT INTO loottable(name) VALUES('barindu_an_aneuk_incantor'); # :barindu_an_aneuk_incantor_lt:
INSERT INTO loottable(name) VALUES('barindu_an_ukun_bloodbeast'); # :barindu_an_ukun_bloodbeast_lt:
INSERT INTO loottable(name) VALUES('barindu_an_ukun_fleshhound'); # :barindu_an_ukun_fleshhound_lt:
INSERT INTO loottable(name) VALUES('barindu_a_chest'); # :barindu_a_chest_lt:
INSERT INTO loottable(name) VALUES('barindu_a_clay_laborer'); # :barindu_a_clay_laborer_lt:
INSERT INTO loottable(name) VALUES('barindu_a_conquered_guardian'); # :barindu_a_conquered_guardian_lt:
INSERT INTO loottable(name) VALUES('barindu_a_dominated_guardian'); # :barindu_a_dominated_guardian_lt:
INSERT INTO loottable(name) VALUES('barindu_a_golem_stoneshifter'); # :barindu_a_golem_stoneshifter_lt:
INSERT INTO loottable(name) VALUES('barindu_a_harindi_craftsman'); # :barindu_a_harindi_craftsman_lt:
INSERT INTO loottable(name) VALUES('barindu_a_kyv_eyecollector'); # :barindu_a_kyv_eyecollector_lt:
INSERT INTO loottable(name) VALUES('barindu_a_kyv_heartpiercer'); # :barindu_a_kyv_heartpiercer_lt:
INSERT INTO loottable(name) VALUES('barindu_a_kyv_runner'); # :barindu_a_kyv_runner_lt:
INSERT INTO loottable(name) VALUES('barindu_a_mastruq_eviscerator'); # :barindu_a_mastruq_eviscerator_lt:
INSERT INTO loottable(name) VALUES('barindu_a_mastruq_spiritbrute'); # :barindu_a_mastruq_spiritbrute_lt:
INSERT INTO loottable(name) VALUES('barindu_a_mastruq_warfiend'); # :barindu_a_mastruq_warfiend_lt:
INSERT INTO loottable(name) VALUES('barindu_a_mastruq_warmedic'); # :barindu_a_mastruq_warmedic_lt:
INSERT INTO loottable(name) VALUES('barindu_a_noc_bloodluster'); # :barindu_a_noc_bloodluster_lt:
INSERT INTO loottable(name) VALUES('barindu_a_noc_darklurch'); # :barindu_a_noc_darklurch_lt:
INSERT INTO loottable(name) VALUES('barindu_a_noc_fleshfeaster'); # :barindu_a_noc_fleshfeaster_lt:
INSERT INTO loottable(name) VALUES('barindu_a_ratuk_decapitator'); # :barindu_a_ratuk_decapitator_lt:
INSERT INTO loottable(name) VALUES('barindu_a_ratuk_screambringer'); # :barindu_a_ratuk_screambringer_lt:
INSERT INTO loottable(name) VALUES('barindu_a_sandstone_laborer'); # :barindu_a_sandstone_laborer_lt:
INSERT INTO loottable(name) VALUES('barindu_a_stoneshifter'); # :barindu_a_stoneshifter_lt:
INSERT INTO loottable(name) VALUES('barindu_a_yunjo_cultivator'); # :barindu_a_yunjo_cultivator_lt:
INSERT INTO loottable(name) VALUES('barindu_a_yunjo_harvester'); # :barindu_a_yunjo_harvester_lt:
INSERT INTO loottable(name) VALUES('barindu_a_yunjo_laborer'); # :barindu_a_yunjo_laborer_lt:
INSERT INTO loottable(name) VALUES('barindu_construct_of_war'); # :barindu_construct_of_war_lt:
INSERT INTO loottable(name) VALUES('barindu_harvester_dramudi'); # :barindu_harvester_dramudi_lt:
INSERT INTO loottable(name) VALUES('barindu_ikaav_ixvet_pox'); # :barindu_ikaav_ixvet_pox_lt:
INSERT INTO loottable(name) VALUES('barindu_overseer_oltix'); # :barindu_overseer_oltix_lt:
INSERT INTO loottable(name) VALUES('barindu_scribe_gurru'); # :barindu_scribe_gurru_lt:
INSERT INTO loottable(name) VALUES('barindu_talwins_remains'); # :barindu_talwins_remains_lt:
INSERT INTO loottable(name) VALUES('barindu_viarglug'); # :barindu_viarglug_lt:
