INSERT INTO loottable(name) VALUES('ferubi_body_elemental'); # :ferubi_body_elemental_lt:
INSERT INTO loottable(name) VALUES('ferubi_mage_trap'); # :ferubi_mage_trap_lt:
INSERT INTO loottable(name) VALUES('ferubi_pxet_vzanki_kzan'); # :ferubi_pxet_vzanki_kzan_lt:
INSERT INTO loottable(name) VALUES('ferubi_rav_hunter'); # :ferubi_rav_hunter_lt:
INSERT INTO loottable(name) VALUES('ferubi_rav_pizak'); # :ferubi_rav_pizak_lt:
INSERT INTO loottable(name) VALUES('ferubi_rav_ptvin'); # :ferubi_rav_ptvin_lt:
INSERT INTO loottable(name) VALUES('ferubi_smith_rondo'); # :ferubi_smith_rondo_lt:
INSERT INTO loottable(name) VALUES('ferubi_smiths_spectral_memory'); # :ferubi_smiths_spectral_memory_lt:
INSERT INTO loottable(name) VALUES('ferubi_an_aneuk_bone_binder'); # :ferubi_an_aneuk_bone_binder_lt:
INSERT INTO loottable(name) VALUES('ferubi_an_aneuk_darkarchon'); # :ferubi_an_aneuk_darkarchon_lt:
INSERT INTO loottable(name) VALUES('ferubi_an_aneuk_seer'); # :ferubi_an_aneuk_seer_lt:
INSERT INTO loottable(name) VALUES('ferubi_an_aneuk_spiritskin'); # :ferubi_an_aneuk_spiritskin_lt:
INSERT INTO loottable(name) VALUES('ferubi_an_ukun_bloodbeast'); # :ferubi_an_ukun_bloodbeast_lt:
INSERT INTO loottable(name) VALUES('ferubi_an_ukun_boneretriever'); # :ferubi_an_ukun_boneretriever_lt:
INSERT INTO loottable(name) VALUES('ferubi_an_ukun_fleshound'); # :ferubi_an_ukun_fleshound_lt:
INSERT INTO loottable(name) VALUES('ferubi_an_ukun_marrowbeast'); # :ferubi_an_ukun_marrowbeast_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_corrupted_turepta'); # :ferubi_a_corrupted_turepta_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_kyv_eyecollector'); # :ferubi_a_kyv_eyecollector_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_kyv_heartpiercer'); # :ferubi_a_kyv_heartpiercer_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_kyv_shadowhunter'); # :ferubi_a_kyv_shadowhunter_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_kyv_stalker'); # :ferubi_a_kyv_stalker_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_mastruq_battlemaster'); # :ferubi_a_mastruq_battlemaster_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_mastruq_bloodluster'); # :ferubi_a_mastruq_bloodluster_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_mastruq_fiend'); # :ferubi_a_mastruq_fiend_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_mastruq_surgeon'); # :ferubi_a_mastruq_surgeon_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_mastruq_warfiend'); # :ferubi_a_mastruq_warfiend_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_mastruq_weaver'); # :ferubi_a_mastruq_weaver_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_noc_bloodluster'); # :ferubi_a_noc_bloodluster_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_noc_cadavor'); # :ferubi_a_noc_cadavor_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_noc_darklurch'); # :ferubi_a_noc_darklurch_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_ratuk_bonebreaker'); # :ferubi_a_ratuk_bonebreaker_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_ratuk_decapitator'); # :ferubi_a_ratuk_decapitator_lt:
INSERT INTO loottable(name) VALUES('ferubi_a_ratuk_screambringer'); # :ferubi_a_ratuk_screambringer_lt:
INSERT INTO loottable(name) VALUES('ferubi_event_spawner'); # :ferubi_event_spawner_lt:
INSERT INTO loottable(name) VALUES('ferubi_hexxt_gkon'); # :ferubi_hexxt_gkon_lt:
INSERT INTO loottable(name) VALUES('ferubi_hexxt_nvak_tkan'); # :ferubi_hexxt_nvak_tkan_lt:
INSERT INTO loottable(name) VALUES('ferubi_hexxt_pzik_shziaak'); # :ferubi_hexxt_pzik_shziaak_lt:
INSERT INTO loottable(name) VALUES('ferubi_masters_apprentice'); # :ferubi_masters_apprentice_lt:
INSERT INTO loottable(name) VALUES('ferubi_packmaster_skoiat_pizak'); # :ferubi_packmaster_skoiat_pizak_lt:
INSERT INTO loottable(name) VALUES('ferubi_pixtt_votal'); # :ferubi_pixtt_votal_lt:
INSERT INTO loottable(name) VALUES('ferubi_pixtt_votal_'); # :ferubi_pixtt_votal__lt:
INSERT INTO loottable(name) VALUES('ferubi_pxet_elite_blademaster'); # :ferubi_pxet_elite_blademaster_lt:
INSERT INTO loottable(name) VALUES('ferubi_pxet_elite_brawler'); # :ferubi_pxet_elite_brawler_lt:
INSERT INTO loottable(name) VALUES('ferubi_pxet_elite_hammermaster'); # :ferubi_pxet_elite_hammermaster_lt:
INSERT INTO loottable(name) VALUES('ferubi_pxet_elite_spearmaster'); # :ferubi_pxet_elite_spearmaster_lt:
INSERT INTO loottable(name) VALUES('ferubi_pxet_vzanki_kzan'); # :ferubi_pxet_vzanki_kzan_lt:
INSERT INTO loottable(name) VALUES('ferubi_shade_of_reiya_the_pained'); # :ferubi_shade_of_reiya_the_pained_lt:
INSERT INTO loottable(name) VALUES('ferubi_smith_rondo'); # :ferubi_smith_rondo_lt:
INSERT INTO loottable(name) VALUES('ferubi_speargroup'); # :ferubi_speargroup_lt:
INSERT INTO loottable(name) VALUES('ferubi_weapon_master_vtiink_vzaan'); # :ferubi_weapon_master_vtiink_vzaan_lt:
INSERT INTO loottable(name) VALUES('ferubi_zunmuram_votal'); # :ferubi_zunmuram_votal_lt:
