(:fhalls_a_squeaking_rat_lt:, :rat_ears_ld:, 1),
(:fhalls_a_squeaking_rat_lt:, :piece_of_rat_fur_ld:, 1),
(:fhalls_a_squeaking_rat_lt:, :rat_whiskers_ld:, 1),
(:fhalls_a_swooping_bat_lt:, :scale_ore_ld:, 1),
(:fhalls_a_swooping_bat_lt:, :giant_bat_wing_ld:, 1),
