INSERT INTO loottable(name) VALUES('ikkinz_guardian_of_glorification'); # :ikkinz_guardian_of_glorification_lt:
INSERT INTO loottable(name) VALUES('ikkinz_transcendent_acolyte'); # :ikkinz_transcendent_acolyte_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_adherent'); # :ikkinz_altar_adherent_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_adherent_'); # :ikkinz_altar_adherent__lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_adherent__'); # :ikkinz_altar_adherent___lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_adherent___'); # :ikkinz_altar_adherent____lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_adherent____'); # :ikkinz_altar_adherent_____lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_construct'); # :ikkinz_altar_construct_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_monument'); # :ikkinz_altar_monument_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_sentry'); # :ikkinz_altar_sentry_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_sustainer'); # :ikkinz_altar_sustainer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_warden'); # :ikkinz_altar_warden_lt:
INSERT INTO loottable(name) VALUES('ikkinz_crumbling_monolith'); # :ikkinz_crumbling_monolith_lt:
INSERT INTO loottable(name) VALUES('ikkinz_crumbling_monument'); # :ikkinz_crumbling_monument_lt:
INSERT INTO loottable(name) VALUES('ikkinz_curate_firetender'); # :ikkinz_curate_firetender_lt:
INSERT INTO loottable(name) VALUES('ikkinz_defender_of_righteousness'); # :ikkinz_defender_of_righteousness_lt:
INSERT INTO loottable(name) VALUES('ikkinz_flesh_hunter'); # :ikkinz_flesh_hunter_lt:
INSERT INTO loottable(name) VALUES('ikkinz_glorified_bolsterer'); # :ikkinz_glorified_bolsterer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_guardian_of_glorification'); # :ikkinz_guardian_of_glorification_lt:
INSERT INTO loottable(name) VALUES('ikkinz_guardian_of_glorification_'); # :ikkinz_guardian_of_glorification__lt:
INSERT INTO loottable(name) VALUES('ikkinz_guardian_of_transcendence'); # :ikkinz_guardian_of_transcendence_lt:
INSERT INTO loottable(name) VALUES('ikkinz_keeper_of_the_altar'); # :ikkinz_keeper_of_the_altar_lt:
INSERT INTO loottable(name) VALUES('ikkinz_lesser_altar_construct'); # :ikkinz_lesser_altar_construct_lt:
INSERT INTO loottable(name) VALUES('ikkinz_malevolent_priest'); # :ikkinz_malevolent_priest_lt:
INSERT INTO loottable(name) VALUES('ikkinz_malevolent_priest_'); # :ikkinz_malevolent_priest__lt:
INSERT INTO loottable(name) VALUES('ikkinz_oracle_of_the_altar'); # :ikkinz_oracle_of_the_altar_lt:
INSERT INTO loottable(name) VALUES('ikkinz_phantasmal_priest'); # :ikkinz_phantasmal_priest_lt:
INSERT INTO loottable(name) VALUES('ikkinz_phantasmal_priest_guardian'); # :ikkinz_phantasmal_priest_guardian_lt:
INSERT INTO loottable(name) VALUES('ikkinz_priest_of_righteousness'); # :ikkinz_priest_of_righteousness_lt:
INSERT INTO loottable(name) VALUES('ikkinz_spirit_of_tunik_tamuik'); # :ikkinz_spirit_of_tunik_tamuik_lt:
INSERT INTO loottable(name) VALUES('ikkinz_stalwart_caretaker'); # :ikkinz_stalwart_caretaker_lt:
INSERT INTO loottable(name) VALUES('ikkinz_transcendent_acolyte'); # :ikkinz_transcendent_acolyte_lt:
INSERT INTO loottable(name) VALUES('ikkinz_transcendent_acolyte_'); # :ikkinz_transcendent_acolyte__lt:
INSERT INTO loottable(name) VALUES('ikkinz_trigger_ikkinz_1'); # :ikkinz_trigger_ikkinz_1_lt:
INSERT INTO loottable(name) VALUES('ikkinz_trigger_ikkinz_2'); # :ikkinz_trigger_ikkinz_2_lt:
INSERT INTO loottable(name) VALUES('ikkinz_trigger_ikkinz_3'); # :ikkinz_trigger_ikkinz_3_lt:
INSERT INTO loottable(name) VALUES('ikkinz_trigger_ikkinz_4'); # :ikkinz_trigger_ikkinz_4_lt:
INSERT INTO loottable(name) VALUES('ikkinz_trigger_ikkinz_5'); # :ikkinz_trigger_ikkinz_5_lt:
INSERT INTO loottable(name) VALUES('ikkinz_visionary_of_glory'); # :ikkinz_visionary_of_glory_lt:
INSERT INTO loottable(name) VALUES('ikkinz_visionary_of_glory_'); # :ikkinz_visionary_of_glory__lt:
INSERT INTO loottable(name) VALUES('ikkinz_vrex_xalkak_nixki'); # :ikkinz_vrex_xalkak_nixki_lt:
INSERT INTO loottable(name) VALUES('ikkinz_vrex_xalkaks_sentinel'); # :ikkinz_vrex_xalkaks_sentinel_lt:
INSERT INTO loottable(name) VALUES('ikkinz_vrex_xalkaks_sentinel_'); # :ikkinz_vrex_xalkaks_sentinel__lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_assailant'); # :ikkinz_altar_assailant_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_monument'); # :ikkinz_altar_monument_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_overseer'); # :ikkinz_altar_overseer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_sentry'); # :ikkinz_altar_sentry_lt:
INSERT INTO loottable(name) VALUES('ikkinz_altar_warden'); # :ikkinz_altar_warden_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_abandoned_recusant'); # :ikkinz_an_abandoned_recusant_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_aneuk_darkdiviner'); # :ikkinz_an_aneuk_darkdiviner_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_aneuk_fleshthreader'); # :ikkinz_an_aneuk_fleshthreader_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_enslaved_radical'); # :ikkinz_an_enslaved_radical_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_enslaved_spiritcrusher'); # :ikkinz_an_enslaved_spiritcrusher_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_enthralled_listener'); # :ikkinz_an_enthralled_listener_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ikaav_binder'); # :ikkinz_an_ikaav_binder_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ikaav_captor'); # :ikkinz_an_ikaav_captor_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ikaav_detainer'); # :ikkinz_an_ikaav_detainer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_infernal_deserter'); # :ikkinz_an_infernal_deserter_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ixt_blightbringer'); # :ikkinz_an_ixt_blightbringer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ixt_eradicator'); # :ikkinz_an_ixt_eradicator_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ixt_impulsor'); # :ikkinz_an_ixt_impulsor_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ixt_persecutor'); # :ikkinz_an_ixt_persecutor_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ixt_slaveherder'); # :ikkinz_an_ixt_slaveherder_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ixt_steelslayer'); # :ikkinz_an_ixt_steelslayer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_outcast_defector'); # :ikkinz_an_outcast_defector_lt:
INSERT INTO loottable(name) VALUES('ikkinz_an_ukun_boneretriever'); # :ikkinz_an_ukun_boneretriever_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_broken_trialmaster'); # :ikkinz_a_broken_trialmaster_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_choked_hymnist'); # :ikkinz_a_choked_hymnist_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_commanded_guardian'); # :ikkinz_a_commanded_guardian_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_compulsed_umbrabasher'); # :ikkinz_a_compulsed_umbrabasher_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_constrained_aggressor'); # :ikkinz_a_constrained_aggressor_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_desolate_fanatic'); # :ikkinz_a_desolate_fanatic_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_destitute_malcontent'); # :ikkinz_a_destitute_malcontent_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_destitute_spirit'); # :ikkinz_a_destitute_spirit_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_kyv_eyegorger'); # :ikkinz_a_kyv_eyegorger_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_kyv_sightstalker'); # :ikkinz_a_kyv_sightstalker_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_mastruq_battlebrute'); # :ikkinz_a_mastruq_battlebrute_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_mastruq_spiritscourge'); # :ikkinz_a_mastruq_spiritscourge_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_noc_bloodluster'); # :ikkinz_a_noc_bloodluster_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_pile_of_bones'); # :ikkinz_a_pile_of_bones_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_ratuk_rabidfury'); # :ikkinz_a_ratuk_rabidfury_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_silenced_ritesdrummer'); # :ikkinz_a_silenced_ritesdrummer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_tortured_prayerlord'); # :ikkinz_a_tortured_prayerlord_lt:
INSERT INTO loottable(name) VALUES('ikkinz_a_whipped_deathchanter'); # :ikkinz_a_whipped_deathchanter_lt:
INSERT INTO loottable(name) VALUES('ikkinz_constrained_servitor'); # :ikkinz_constrained_servitor_lt:
INSERT INTO loottable(name) VALUES('ikkinz_controlled_spirithunter'); # :ikkinz_controlled_spirithunter_lt:
INSERT INTO loottable(name) VALUES('ikkinz_cruel_illusion'); # :ikkinz_cruel_illusion_lt:
INSERT INTO loottable(name) VALUES('ikkinz_crumbling_monolith'); # :ikkinz_crumbling_monolith_lt:
INSERT INTO loottable(name) VALUES('ikkinz_crumbling_monument'); # :ikkinz_crumbling_monument_lt:
INSERT INTO loottable(name) VALUES('ikkinz_custodian_of_righteousness'); # :ikkinz_custodian_of_righteousness_lt:
INSERT INTO loottable(name) VALUES('ikkinz_defender_of_righteousness'); # :ikkinz_defender_of_righteousness_lt:
INSERT INTO loottable(name) VALUES('ikkinz_diabolic_destroyer'); # :ikkinz_diabolic_destroyer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_dire_illusion'); # :ikkinz_dire_illusion_lt:
INSERT INTO loottable(name) VALUES('ikkinz_doorman'); # :ikkinz_doorman_lt:
INSERT INTO loottable(name) VALUES('ikkinz_flesh_hunter'); # :ikkinz_flesh_hunter_lt:
INSERT INTO loottable(name) VALUES('ikkinz_flesh_hunter_'); # :ikkinz_flesh_hunter__lt:
INSERT INTO loottable(name) VALUES('ikkinz_glorified_bolsterer'); # :ikkinz_glorified_bolsterer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_guardian_of_glorification'); # :ikkinz_guardian_of_glorification_lt:
INSERT INTO loottable(name) VALUES('ikkinz_guardian_of_righteousness'); # :ikkinz_guardian_of_righteousness_lt:
INSERT INTO loottable(name) VALUES('ikkinz_guardian_of_transcendence'); # :ikkinz_guardian_of_transcendence_lt:
INSERT INTO loottable(name) VALUES('ikkinz_hexxt_markmaker'); # :ikkinz_hexxt_markmaker_lt:
INSERT INTO loottable(name) VALUES('ikkinz_hexxt_sightsliverer'); # :ikkinz_hexxt_sightsliverer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_lockout_ikkinz'); # :ikkinz_lockout_ikkinz_lt:
INSERT INTO loottable(name) VALUES('ikkinz_malevolent_priest'); # :ikkinz_malevolent_priest_lt:
INSERT INTO loottable(name) VALUES('ikkinz_phantasmal_priest_guardian'); # :ikkinz_phantasmal_priest_guardian_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_airstrangler'); # :ikkinz_pixtt_airstrangler_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_annihilator'); # :ikkinz_pixtt_annihilator_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_annuller'); # :ikkinz_pixtt_annuller_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_assault_ward'); # :ikkinz_pixtt_assault_ward_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_condemner'); # :ikkinz_pixtt_condemner_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_decimator'); # :ikkinz_pixtt_decimator_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_nervehammer'); # :ikkinz_pixtt_nervehammer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_neuromancer'); # :ikkinz_pixtt_neuromancer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_slaughterer'); # :ikkinz_pixtt_slaughterer_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_slaughtereress'); # :ikkinz_pixtt_slaughtereress_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_tyrannist'); # :ikkinz_pixtt_tyrannist_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_venomblade'); # :ikkinz_pixtt_venomblade_lt:
INSERT INTO loottable(name) VALUES('ikkinz_pixtt_willbreaker'); # :ikkinz_pixtt_willbreaker_lt:
INSERT INTO loottable(name) VALUES('ikkinz_priest_of_righteousness'); # :ikkinz_priest_of_righteousness_lt:
INSERT INTO loottable(name) VALUES('ikkinz_rav_interceptor'); # :ikkinz_rav_interceptor_lt:
INSERT INTO loottable(name) VALUES('ikkinz_sentinel_of_glorification'); # :ikkinz_sentinel_of_glorification_lt:
INSERT INTO loottable(name) VALUES('ikkinz_spirit_of_tunik_tamuik'); # :ikkinz_spirit_of_tunik_tamuik_lt:
INSERT INTO loottable(name) VALUES('ikkinz_subjugated_vrex_caller'); # :ikkinz_subjugated_vrex_caller_lt:
INSERT INTO loottable(name) VALUES('ikkinz_transcendent_acolyte'); # :ikkinz_transcendent_acolyte_lt:
INSERT INTO loottable(name) VALUES('ikkinz_transcendent_acolyte_'); # :ikkinz_transcendent_acolyte__lt:
INSERT INTO loottable(name) VALUES('ikkinz_visionary_of_glory'); # :ikkinz_visionary_of_glory_lt:
INSERT INTO loottable(name) VALUES('ikkinz_vrex_xalkaks_marauder'); # :ikkinz_vrex_xalkaks_marauder_lt:
INSERT INTO loottable(name) VALUES('ikkinz_vrex_xalkaks_sentinel'); # :ikkinz_vrex_xalkaks_sentinel_lt:
INSERT INTO loottable(name) VALUES('ikkinz_vrex_xalkaks_sentinel_'); # :ikkinz_vrex_xalkaks_sentinel__lt:
