INSERT INTO loottable(name) VALUES('sncrematory_a_ghostly_essence'); # :sncrematory_a_ghostly_essence_lt:
INSERT INTO loottable(name) VALUES('sncrematory_cryxtetl'); # :sncrematory_cryxtetl_lt:
INSERT INTO loottable(name) VALUES('sncrematory_diseased_larva'); # :sncrematory_diseased_larva_lt:
INSERT INTO loottable(name) VALUES('sncrematory_gzifa_the_pure_one'); # :sncrematory_gzifa_the_pure_one_lt:
INSERT INTO loottable(name) VALUES('sncrematory_gzifa_trigger'); # :sncrematory_gzifa_trigger_lt:
INSERT INTO loottable(name) VALUES('sncrematory_mabiki'); # :sncrematory_mabiki_lt:
INSERT INTO loottable(name) VALUES('sncrematory_ngozi'); # :sncrematory_ngozi_lt:
INSERT INTO loottable(name) VALUES('sncrematory_sewage_slime'); # :sncrematory_sewage_slime_lt:
INSERT INTO loottable(name) VALUES('sncrematory_sewer_trigger'); # :sncrematory_sewer_trigger_lt:
INSERT INTO loottable(name) VALUES('sncrematory_slime_devourer'); # :sncrematory_slime_devourer_lt:
INSERT INTO loottable(name) VALUES('sncrematory_talakoi'); # :sncrematory_talakoi_lt:
INSERT INTO loottable(name) VALUES('sncrematory_yogundi'); # :sncrematory_yogundi_lt:
INSERT INTO loottable(name) VALUES('sncrematory_an_acid_larva'); # :sncrematory_an_acid_larva_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_decaying_slimesnipper'); # :sncrematory_a_decaying_slimesnipper_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_grimy_turepta'); # :sncrematory_a_grimy_turepta_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_muck-covered_fly'); # :sncrematory_a_muck-covered_fly_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_nihil_arcanists_spirit'); # :sncrematory_a_nihil_arcanists_spirit_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_nihil_geomancers_spirit'); # :sncrematory_a_nihil_geomancers_spirit_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_nihil_priests_spirit'); # :sncrematory_a_nihil_priests_spirit_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_nihil_workers_spirit'); # :sncrematory_a_nihil_workers_spirit_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_sewer_gnat'); # :sncrematory_a_sewer_gnat_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_slimelurking_stonemite'); # :sncrematory_a_slimelurking_stonemite_lt:
INSERT INTO loottable(name) VALUES('sncrematory_a_sludge_lurker'); # :sncrematory_a_sludge_lurker_lt:
INSERT INTO loottable(name) VALUES('sncrematory__'); # :sncrematory___lt:
