INSERT INTO loottable(name) VALUES('tacvi_absors_remains'); # :tacvi_absors_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_balance_of_defense'); # :tacvi_balance_of_defense_lt:
INSERT INTO loottable(name) VALUES('tacvi_balance_of_fury'); # :tacvi_balance_of_fury_lt:
INSERT INTO loottable(name) VALUES('tacvi_balance_of_rage'); # :tacvi_balance_of_rage_lt:
INSERT INTO loottable(name) VALUES('tacvi_balance_of_speed'); # :tacvi_balance_of_speed_lt:
INSERT INTO loottable(name) VALUES('tacvi_frizzniks_remains'); # :tacvi_frizzniks_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_kaikachis_remains'); # :tacvi_kaikachis_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_lyndrohs_remains'); # :tacvi_lyndrohs_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_maddocs_remains'); # :tacvi_maddocs_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_prathuns_remains'); # :tacvi_prathuns_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_rasheres_remains'); # :tacvi_rasheres_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_rytans_remains'); # :tacvi_rytans_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_sesnil_yisnon'); # :tacvi_sesnil_yisnon_lt:
INSERT INTO loottable(name) VALUES('tacvi_silius_remains'); # :tacvi_silius_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_tunatmuram_cuu_vauax'); # :tacvi_tunatmuram_cuu_vauax_lt:
INSERT INTO loottable(name) VALUES('tacvi_vahlaras_remains'); # :tacvi_vahlaras_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_valtrons_remains'); # :tacvi_valtrons_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_wijdans_remains'); # :tacvi_wijdans_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_xenaidas_remains'); # :tacvi_xenaidas_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_zajeers_remains'); # :tacvi_zajeers_remains_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_elite_mastruq_berserker'); # :tacvi_an_elite_mastruq_berserker_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_elite_mastruq_crusher'); # :tacvi_an_elite_mastruq_crusher_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_elite_mastruq_destroyer'); # :tacvi_an_elite_mastruq_destroyer_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_ikaav_hatchling'); # :tacvi_an_ikaav_hatchling_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_ukun_biledrinker'); # :tacvi_an_ukun_biledrinker_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_ukun_juxtapincer'); # :tacvi_an_ukun_juxtapincer_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_ukun_lifebleeder'); # :tacvi_an_ukun_lifebleeder_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_ukun_manasipper'); # :tacvi_an_ukun_manasipper_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_ukun_ragehound'); # :tacvi_an_ukun_ragehound_lt:
INSERT INTO loottable(name) VALUES('tacvi_an_unstable_construct'); # :tacvi_an_unstable_construct_lt:
INSERT INTO loottable(name) VALUES('tacvi_a_corrupted_construct'); # :tacvi_a_corrupted_construct_lt:
INSERT INTO loottable(name) VALUES('tacvi_husk_of_pixtt_kretv_krakxt'); # :tacvi_husk_of_pixtt_kretv_krakxt_lt:
INSERT INTO loottable(name) VALUES('tacvi_living_phylactery'); # :tacvi_living_phylactery_lt:
INSERT INTO loottable(name) VALUES('tacvi_pixtt_kretv_krakxt'); # :tacvi_pixtt_kretv_krakxt_lt:
INSERT INTO loottable(name) VALUES('tacvi_pixtt_riel_tavas'); # :tacvi_pixtt_riel_tavas_lt:
INSERT INTO loottable(name) VALUES('tacvi_pixtt_xxeric_kex'); # :tacvi_pixtt_xxeric_kex_lt:
INSERT INTO loottable(name) VALUES('tacvi_reflection_of_kretv_krakxt'); # :tacvi_reflection_of_kretv_krakxt_lt:
INSERT INTO loottable(name) VALUES('tacvi_zone_status'); # :tacvi_zone_status_lt:
INSERT INTO loottable(name) VALUES('tacvi_zunmuram_kvxe_pirik'); # :tacvi_zunmuram_kvxe_pirik_lt:
INSERT INTO loottable(name) VALUES('tacvi_zunmuram_mordl_delt'); # :tacvi_zunmuram_mordl_delt_lt:
INSERT INTO loottable(name) VALUES('tacvi_zunmuram_shaldn_boc'); # :tacvi_zunmuram_shaldn_boc_lt:
INSERT INTO loottable(name) VALUES('tacvi_zunmuram_yihst_vor'); # :tacvi_zunmuram_yihst_vor_lt:
INSERT INTO loottable(name) VALUES('tacvi__'); # :tacvi___lt:
