INSERT INTO loottable(name) VALUES('txevu_ancient_cragbeast_matriarch'); # :txevu_ancient_cragbeast_matriarch_lt:
INSERT INTO loottable(name) VALUES('txevu_aneuk_nyrt_ymosa'); # :txevu_aneuk_nyrt_ymosa_lt:
INSERT INTO loottable(name) VALUES('txevu_aneuk_rilst_uskst'); # :txevu_aneuk_rilst_uskst_lt:
INSERT INTO loottable(name) VALUES('txevu_a_stonemite_corpseburrower'); # :txevu_a_stonemite_corpseburrower_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_absorption'); # :txevu_bearer_of_absorption_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_anger'); # :txevu_bearer_of_anger_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_haste'); # :txevu_bearer_of_haste_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_intensification'); # :txevu_bearer_of_intensification_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_mending'); # :txevu_bearer_of_mending_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_nascency'); # :txevu_bearer_of_nascency_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_projection'); # :txevu_bearer_of_projection_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_quickening'); # :txevu_bearer_of_quickening_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_rage'); # :txevu_bearer_of_rage_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_reflection'); # :txevu_bearer_of_reflection_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_resistance'); # :txevu_bearer_of_resistance_lt:
INSERT INTO loottable(name) VALUES('txevu_bearer_of_shielding'); # :txevu_bearer_of_shielding_lt:
INSERT INTO loottable(name) VALUES('txevu_high_priest_nkosi_bakari'); # :txevu_high_priest_nkosi_bakari_lt:
INSERT INTO loottable(name) VALUES('txevu_ikaav_nysf_lleiv'); # :txevu_ikaav_nysf_lleiv_lt:
INSERT INTO loottable(name) VALUES('txevu_inquisitor_chiak_tansk'); # :txevu_inquisitor_chiak_tansk_lt:
INSERT INTO loottable(name) VALUES('txevu_inquisitor_lliev_kinth'); # :txevu_inquisitor_lliev_kinth_lt:
INSERT INTO loottable(name) VALUES('txevu_ixt_hsek_syat'); # :txevu_ixt_hsek_syat_lt:
INSERT INTO loottable(name) VALUES('txevu_ixt_kial_ivesi'); # :txevu_ixt_kial_ivesi_lt:
INSERT INTO loottable(name) VALUES('txevu_ixt_quall_nalnn'); # :txevu_ixt_quall_nalnn_lt:
INSERT INTO loottable(name) VALUES('txevu_mastruq_champion'); # :txevu_mastruq_champion_lt:
INSERT INTO loottable(name) VALUES('txevu_priest_trigger'); # :txevu_priest_trigger_lt:
INSERT INTO loottable(name) VALUES('txevu_the_runt'); # :txevu_the_runt_lt:
INSERT INTO loottable(name) VALUES('txevu_ukun_bloodfeaster'); # :txevu_ukun_bloodfeaster_lt:
INSERT INTO loottable(name) VALUES('txevu_vrex_invoker_akello'); # :txevu_vrex_invoker_akello_lt:
INSERT INTO loottable(name) VALUES('txevu_vrex_invoker_jahzara'); # :txevu_vrex_invoker_jahzara_lt:
INSERT INTO loottable(name) VALUES('txevu_vrex_invoker_kashka'); # :txevu_vrex_invoker_kashka_lt:
INSERT INTO loottable(name) VALUES('txevu_vrex_invoker_malik'); # :txevu_vrex_invoker_malik_lt:
INSERT INTO loottable(name) VALUES('txevu_vrex_invoker_raziya'); # :txevu_vrex_invoker_raziya_lt:
INSERT INTO loottable(name) VALUES('txevu_vrex_stonemaster_hateq'); # :txevu_vrex_stonemaster_hateq_lt:
INSERT INTO loottable(name) VALUES('txevu_vrex_stonemaster_lorasa'); # :txevu_vrex_stonemaster_lorasa_lt:
INSERT INTO loottable(name) VALUES('txevu_vrex_stonemaster_veset'); # :txevu_vrex_stonemaster_veset_lt:
INSERT INTO loottable(name) VALUES('txevu_zunmuram_tkarish_zyk'); # :txevu_zunmuram_tkarish_zyk_lt:
INSERT INTO loottable(name) VALUES('txevu_an_ancient_hynid_scavenger'); # :txevu_an_ancient_hynid_scavenger_lt:
INSERT INTO loottable(name) VALUES('txevu_an_aneuk_darkdiviner'); # :txevu_an_aneuk_darkdiviner_lt:
INSERT INTO loottable(name) VALUES('txevu_an_aneuk_fleshthreader'); # :txevu_an_aneuk_fleshthreader_lt:
INSERT INTO loottable(name) VALUES('txevu_an_aneuk_nervehammer'); # :txevu_an_aneuk_nervehammer_lt:
INSERT INTO loottable(name) VALUES('txevu_an_apprentice_diviner'); # :txevu_an_apprentice_diviner_lt:
INSERT INTO loottable(name) VALUES('txevu_an_apprentice_firebrand'); # :txevu_an_apprentice_firebrand_lt:
INSERT INTO loottable(name) VALUES('txevu_an_apprentice_incantor'); # :txevu_an_apprentice_incantor_lt:
INSERT INTO loottable(name) VALUES('txevu_an_apprentice_willbender'); # :txevu_an_apprentice_willbender_lt:
INSERT INTO loottable(name) VALUES('txevu_an_enslaved_destroyer'); # :txevu_an_enslaved_destroyer_lt:
INSERT INTO loottable(name) VALUES('txevu_an_enthralled_deathbringer'); # :txevu_an_enthralled_deathbringer_lt:
INSERT INTO loottable(name) VALUES('txevu_an_ikaav_binder'); # :txevu_an_ikaav_binder_lt:
INSERT INTO loottable(name) VALUES('txevu_an_ikaav_binder_'); # :txevu_an_ikaav_binder__lt:
INSERT INTO loottable(name) VALUES('txevu_an_ikaav_detainer'); # :txevu_an_ikaav_detainer_lt:
INSERT INTO loottable(name) VALUES('txevu_an_ikaav_ruiner'); # :txevu_an_ikaav_ruiner_lt:
INSERT INTO loottable(name) VALUES('txevu_an_ikaav_willbreaker'); # :txevu_an_ikaav_willbreaker_lt:
INSERT INTO loottable(name) VALUES('txevu_an_ukun_deathfang'); # :txevu_an_ukun_deathfang_lt:
INSERT INTO loottable(name) VALUES('txevu_an_ukun_mauler'); # :txevu_an_ukun_mauler_lt:
INSERT INTO loottable(name) VALUES('txevu_arena'); # :txevu_arena_lt:
INSERT INTO loottable(name) VALUES('txevu_a_cragbeast_hatchling'); # :txevu_a_cragbeast_hatchling_lt:
INSERT INTO loottable(name) VALUES('txevu_a_decaying_corpse'); # :txevu_a_decaying_corpse_lt:
INSERT INTO loottable(name) VALUES('txevu_a_fervid_revenant'); # :txevu_a_fervid_revenant_lt:
INSERT INTO loottable(name) VALUES('txevu_a_jailer'); # :txevu_a_jailer_lt:
INSERT INTO loottable(name) VALUES('txevu_a_kyv_hunter'); # :txevu_a_kyv_hunter_lt:
INSERT INTO loottable(name) VALUES('txevu_a_mastruq_battlebrute'); # :txevu_a_mastruq_battlebrute_lt:
INSERT INTO loottable(name) VALUES('txevu_a_mastruq_battlebrute_'); # :txevu_a_mastruq_battlebrute__lt:
INSERT INTO loottable(name) VALUES('txevu_a_mastruq_chaosslayer'); # :txevu_a_mastruq_chaosslayer_lt:
INSERT INTO loottable(name) VALUES('txevu_a_mastruq_gladiator'); # :txevu_a_mastruq_gladiator_lt:
INSERT INTO loottable(name) VALUES('txevu_a_noc_bloodluster'); # :txevu_a_noc_bloodluster_lt:
INSERT INTO loottable(name) VALUES('txevu_a_noc_brawler'); # :txevu_a_noc_brawler_lt:
INSERT INTO loottable(name) VALUES('txevu_a_ravenous_corpsefeeder'); # :txevu_a_ravenous_corpsefeeder_lt:
INSERT INTO loottable(name) VALUES('txevu_a_ratuk_bruiser'); # :txevu_a_ratuk_bruiser_lt:
INSERT INTO loottable(name) VALUES('txevu_a_ratuk_rabidfury'); # :txevu_a_ratuk_rabidfury_lt:
INSERT INTO loottable(name) VALUES('txevu_a_vengeful_apparition'); # :txevu_a_vengeful_apparition_lt:
INSERT INTO loottable(name) VALUES('txevu_champ_event'); # :txevu_champ_event_lt:
INSERT INTO loottable(name) VALUES('txevu_feaster'); # :txevu_feaster_lt:
INSERT INTO loottable(name) VALUES('txevu_hamari_nedu'); # :txevu_hamari_nedu_lt:
INSERT INTO loottable(name) VALUES('txevu_ikaav_ritualist'); # :txevu_ikaav_ritualist_lt:
INSERT INTO loottable(name) VALUES('txevu_mastruq_beast_warden'); # :txevu_mastruq_beast_warden_lt:
INSERT INTO loottable(name) VALUES('txevu_onyx_rockchanter'); # :txevu_onyx_rockchanter_lt:
INSERT INTO loottable(name) VALUES('txevu_onyx_sentinel'); # :txevu_onyx_sentinel_lt:
INSERT INTO loottable(name) VALUES('txevu_restless_wraith'); # :txevu_restless_wraith_lt:
INSERT INTO loottable(name) VALUES('txevu_shade_of_a_vrex_invoker'); # :txevu_shade_of_a_vrex_invoker_lt:
INSERT INTO loottable(name) VALUES('txevu_shade_of_a_vrex_invoker_'); # :txevu_shade_of_a_vrex_invoker__lt:
INSERT INTO loottable(name) VALUES('txevu_shade_of_a_vrex_invoker__'); # :txevu_shade_of_a_vrex_invoker___lt:
INSERT INTO loottable(name) VALUES('txevu_shade_of_a_vrex_invoker___'); # :txevu_shade_of_a_vrex_invoker____lt:
INSERT INTO loottable(name) VALUES('txevu_shade_of_a_vrex_invoker____'); # :txevu_shade_of_a_vrex_invoker_____lt:
INSERT INTO loottable(name) VALUES('txevu_the_sound'); # :txevu_the_sound_lt:
INSERT INTO loottable(name) VALUES('txevu_tiv_prayer_chanter'); # :txevu_tiv_prayer_chanter_lt:
INSERT INTO loottable(name) VALUES('txevu_zmtz_dummy'); # :txevu_zmtz_dummy_lt:
INSERT INTO loottable(name) VALUES('txevu__'); # :txevu___lt:
