INSERT INTO loottable(name) VALUES('uqua_an_avenging_spirit'); # :uqua_an_avenging_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_an_infuriated_spirit'); # :uqua_an_infuriated_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_aura_of_destruction'); # :uqua_aura_of_destruction_lt:
INSERT INTO loottable(name) VALUES('uqua_a_bubble'); # :uqua_a_bubble_lt:
INSERT INTO loottable(name) VALUES('uqua_a_coercing_spirit'); # :uqua_a_coercing_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_a_destructive_channeler'); # :uqua_a_destructive_channeler_lt:
INSERT INTO loottable(name) VALUES('uqua_a_destructive_channeler_'); # :uqua_a_destructive_channeler__lt:
INSERT INTO loottable(name) VALUES('uqua_a_disciple_of_destruction'); # :uqua_a_disciple_of_destruction_lt:
INSERT INTO loottable(name) VALUES('uqua_a_disciple_of_fury'); # :uqua_a_disciple_of_fury_lt:
INSERT INTO loottable(name) VALUES('uqua_a_disciple_of_rage'); # :uqua_a_disciple_of_rage_lt:
INSERT INTO loottable(name) VALUES('uqua_a_fury_behemoth'); # :uqua_a_fury_behemoth_lt:
INSERT INTO loottable(name) VALUES('uqua_a_malevolent_spirit'); # :uqua_a_malevolent_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_a_rage_behemoth'); # :uqua_a_rage_behemoth_lt:
INSERT INTO loottable(name) VALUES('uqua_a_slighted_spirit'); # :uqua_a_slighted_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_a_spiteful_spirit'); # :uqua_a_spiteful_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_anchorite'); # :uqua_a_trusik_anchorite_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_ascetic'); # :uqua_a_trusik_ascetic_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_ritualist'); # :uqua_a_trusik_ritualist_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_stalker'); # :uqua_a_trusik_stalker_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_summoner'); # :uqua_a_trusik_summoner_lt:
INSERT INTO loottable(name) VALUES('uqua_a_vengeful_spirit'); # :uqua_a_vengeful_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_a_vindictive_spirit'); # :uqua_a_vindictive_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_devastating_construct'); # :uqua_devastating_construct_lt:
INSERT INTO loottable(name) VALUES('uqua_floating_foam'); # :uqua_floating_foam_lt:
INSERT INTO loottable(name) VALUES('uqua_gas_chamber_1'); # :uqua_gas_chamber_1_lt:
INSERT INTO loottable(name) VALUES('uqua_gas_chamber_2'); # :uqua_gas_chamber_2_lt:
INSERT INTO loottable(name) VALUES('uqua_guardian_of_destruction'); # :uqua_guardian_of_destruction_lt:
INSERT INTO loottable(name) VALUES('uqua_guardian_of_destruction_'); # :uqua_guardian_of_destruction__lt:
INSERT INTO loottable(name) VALUES('uqua_main_spawner'); # :uqua_main_spawner_lt:
INSERT INTO loottable(name) VALUES('uqua_preshna_the_lost'); # :uqua_preshna_the_lost_lt:
INSERT INTO loottable(name) VALUES('uqua_specter_of_barxt'); # :uqua_specter_of_barxt_lt:
INSERT INTO loottable(name) VALUES('uqua_specter_of_fury'); # :uqua_specter_of_fury_lt:
INSERT INTO loottable(name) VALUES('uqua_specter_of_rage'); # :uqua_specter_of_rage_lt:
INSERT INTO loottable(name) VALUES('uqua_tqiv_araxt_the_enraged'); # :uqua_tqiv_araxt_the_enraged_lt:
INSERT INTO loottable(name) VALUES('uqua_tqiv_qukret_the_furious'); # :uqua_tqiv_qukret_the_furious_lt:
INSERT INTO loottable(name) VALUES('uqua_trap_uqua_1'); # :uqua_trap_uqua_1_lt:
INSERT INTO loottable(name) VALUES('uqua_trap_uqua_2'); # :uqua_trap_uqua_2_lt:
INSERT INTO loottable(name) VALUES('uqua_trap_uqua_3'); # :uqua_trap_uqua_3_lt:
INSERT INTO loottable(name) VALUES('uqua_trap_uqua_4'); # :uqua_trap_uqua_4_lt:
INSERT INTO loottable(name) VALUES('uqua_trap_uqua_5'); # :uqua_trap_uqua_5_lt:
INSERT INTO loottable(name) VALUES('uqua_trap_uqua_6'); # :uqua_trap_uqua_6_lt:
INSERT INTO loottable(name) VALUES('uqua_trap_uqua_7'); # :uqua_trap_uqua_7_lt:
INSERT INTO loottable(name) VALUES('uqua_trap_uqua_8'); # :uqua_trap_uqua_8_lt:
INSERT INTO loottable(name) VALUES('uqua_vrex_barxt_qurat'); # :uqua_vrex_barxt_qurat_lt:
INSERT INTO loottable(name) VALUES('uqua_an_anchorite_of_destruction'); # :uqua_an_anchorite_of_destruction_lt:
INSERT INTO loottable(name) VALUES('uqua_a_coercing_spirit'); # :uqua_a_coercing_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_a_construct_of_fury'); # :uqua_a_construct_of_fury_lt:
INSERT INTO loottable(name) VALUES('uqua_a_construct_of_rage'); # :uqua_a_construct_of_rage_lt:
INSERT INTO loottable(name) VALUES('uqua_a_disciple_of_destruction'); # :uqua_a_disciple_of_destruction_lt:
INSERT INTO loottable(name) VALUES('uqua_a_fury_behemoth'); # :uqua_a_fury_behemoth_lt:
INSERT INTO loottable(name) VALUES('uqua_a_malevolent_spirit'); # :uqua_a_malevolent_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_a_rage_behemoth'); # :uqua_a_rage_behemoth_lt:
INSERT INTO loottable(name) VALUES('uqua_a_slighted_spirit'); # :uqua_a_slighted_spirit_lt:
INSERT INTO loottable(name) VALUES('uqua_a_spectral_guide'); # :uqua_a_spectral_guide_lt:
INSERT INTO loottable(name) VALUES('uqua_a_spirit_guardian'); # :uqua_a_spirit_guardian_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_anchorite'); # :uqua_a_trusik_anchorite_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_ascetic'); # :uqua_a_trusik_ascetic_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_ritualist'); # :uqua_a_trusik_ritualist_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_spiritmaster'); # :uqua_a_trusik_spiritmaster_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_stalker'); # :uqua_a_trusik_stalker_lt:
INSERT INTO loottable(name) VALUES('uqua_a_trusik_summoner'); # :uqua_a_trusik_summoner_lt:
INSERT INTO loottable(name) VALUES('uqua_guardian_of_destruction'); # :uqua_guardian_of_destruction_lt:
INSERT INTO loottable(name) VALUES('uqua_lockout_uqua'); # :uqua_lockout_uqua_lt:
INSERT INTO loottable(name) VALUES('uqua_spectral_trushar_worshipper'); # :uqua_spectral_trushar_worshipper_lt:
INSERT INTO loottable(name) VALUES('uqua_summoning_altar'); # :uqua_summoning_altar_lt:
INSERT INTO loottable(name) VALUES('uqua_tqiv_araxt_the_enraged'); # :uqua_tqiv_araxt_the_enraged_lt:
INSERT INTO loottable(name) VALUES('uqua_tqiv_qukret_the_furious'); # :uqua_tqiv_qukret_the_furious_lt:
INSERT INTO loottable(name) VALUES('uqua_vrex_barxt_qurat'); # :uqua_vrex_barxt_qurat_lt:
