INSERT INTO loottable(name) VALUES('burningwood_a_crippled_wurm'); # :burningwood_a_crippled_wurm_lt:
INSERT INTO loottable(name) VALUES('burningwood_gorgul_paclock'); # :burningwood_gorgul_paclock_lt:
INSERT INTO loottable(name) VALUES('burningwood_spawn_condition'); # :burningwood_spawn_condition_lt:
INSERT INTO loottable(name) VALUES('burningwood_an_ash_hornet'); # :burningwood_an_ash_hornet_lt:
INSERT INTO loottable(name) VALUES('burningwood_an_ember_hornet'); # :burningwood_an_ember_hornet_lt:
INSERT INTO loottable(name) VALUES('burningwood_asmodin_jrudac'); # :burningwood_asmodin_jrudac_lt:
INSERT INTO loottable(name) VALUES('burningwood_atheling_plague'); # :burningwood_atheling_plague_lt:
INSERT INTO loottable(name) VALUES('burningwood_azdalin'); # :burningwood_azdalin_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_cinder_hornet'); # :burningwood_a_cinder_hornet_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_forest_giant_ancient'); # :burningwood_a_forest_giant_ancient_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_forest_giant_arbor'); # :burningwood_a_forest_giant_arbor_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_forest_giant_verdant'); # :burningwood_a_forest_giant_verdant_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_loyal_follower'); # :burningwood_a_loyal_follower_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_moldering_gorilla'); # :burningwood_a_moldering_gorilla_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_sarnak_avenger'); # :burningwood_a_sarnak_avenger_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_sarnak_champion'); # :burningwood_a_sarnak_champion_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_sarnak_enthusiast'); # :burningwood_a_sarnak_enthusiast_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_sarnak_extremist'); # :burningwood_a_sarnak_extremist_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_sarnak_imitator'); # :burningwood_a_sarnak_imitator_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_sarnak_knight'); # :burningwood_a_sarnak_knight_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_sarnak_zealot'); # :burningwood_a_sarnak_zealot_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_scoriae_hornet'); # :burningwood_a_scoriae_hornet_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_tatterback_ape'); # :burningwood_a_tatterback_ape_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_tatterback_gorilla'); # :burningwood_a_tatterback_gorilla_lt:
INSERT INTO loottable(name) VALUES('burningwood_a_tottering_gorilla'); # :burningwood_a_tottering_gorilla_lt:
INSERT INTO loottable(name) VALUES('burningwood_carpenter_grundo'); # :burningwood_carpenter_grundo_lt:
INSERT INTO loottable(name) VALUES('burningwood_clerk_doval'); # :burningwood_clerk_doval_lt:
INSERT INTO loottable(name) VALUES('burningwood_entalon'); # :burningwood_entalon_lt:
INSERT INTO loottable(name) VALUES('burningwood_greater_barbed_skeleton'); # :burningwood_greater_barbed_skeleton_lt:
INSERT INTO loottable(name) VALUES('burningwood_greater_plague_skeleton'); # :burningwood_greater_plague_skeleton_lt:
INSERT INTO loottable(name) VALUES('burningwood_greater_war_boned_skeleton'); # :burningwood_greater_war_boned_skeleton_lt:
INSERT INTO loottable(name) VALUES('burningwood_gullerback'); # :burningwood_gullerback_lt:
INSERT INTO loottable(name) VALUES('burningwood_gylton'); # :burningwood_gylton_lt:
INSERT INTO loottable(name) VALUES('burningwood_ixiblat_fer'); # :burningwood_ixiblat_fer_lt:
INSERT INTO loottable(name) VALUES('burningwood_korasal_klyseer'); # :burningwood_korasal_klyseer_lt:
INSERT INTO loottable(name) VALUES('burningwood_naxot_deepwater'); # :burningwood_naxot_deepwater_lt:
INSERT INTO loottable(name) VALUES('burningwood_nezekezena'); # :burningwood_nezekezena_lt:
INSERT INTO loottable(name) VALUES('burningwood_phurzikon'); # :burningwood_phurzikon_lt:
INSERT INTO loottable(name) VALUES('burningwood_plaguebone_skeleton'); # :burningwood_plaguebone_skeleton_lt:
INSERT INTO loottable(name) VALUES('burningwood_skel_inv_spawn'); # :burningwood_skel_inv_spawn_lt:
INSERT INTO loottable(name) VALUES('burningwood_slixin_klex'); # :burningwood_slixin_klex_lt:
INSERT INTO loottable(name) VALUES('burningwood_telin_darkforest'); # :burningwood_telin_darkforest_lt:
INSERT INTO loottable(name) VALUES('burningwood_wurm'); # :burningwood_wurm_lt:
