INSERT INTO loottable(name) VALUES('chardok_echo_of_chardok'); # :chardok_echo_of_chardok_lt:
INSERT INTO loottable(name) VALUES('chardok_historian_silren_dizok'); # :chardok_historian_silren_dizok_lt:
INSERT INTO loottable(name) VALUES('chardok_interrogator_gimok'); # :chardok_interrogator_gimok_lt:
INSERT INTO loottable(name) VALUES('chardok_korocust'); # :chardok_korocust_lt:
INSERT INTO loottable(name) VALUES('chardok_tani_cogswin'); # :chardok_tani_cogswin_lt:
INSERT INTO loottable(name) VALUES('chardok_the_fabled_prince_selrach_dizok'); # :chardok_the_fabled_prince_selrach_dizok_lt:
INSERT INTO loottable(name) VALUES('chardok_ancient_guardian'); # :chardok_ancient_guardian_lt:
INSERT INTO loottable(name) VALUES('chardok_an_accused_traitor'); # :chardok_an_accused_traitor_lt:
INSERT INTO loottable(name) VALUES('chardok_an_ancient_guardian'); # :chardok_an_ancient_guardian_lt:
INSERT INTO loottable(name) VALUES('chardok_an_angry_slave'); # :chardok_an_angry_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_an_apprentice_herbalist'); # :chardok_an_apprentice_herbalist_lt:
INSERT INTO loottable(name) VALUES('chardok_an_apprentice_kennelmaster'); # :chardok_an_apprentice_kennelmaster_lt:
INSERT INTO loottable(name) VALUES('chardok_an_apprentice_lorekeeper'); # :chardok_an_apprentice_lorekeeper_lt:
INSERT INTO loottable(name) VALUES('chardok_an_enraged_slave'); # :chardok_an_enraged_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_an_enslaved_iksar_miner'); # :chardok_an_enslaved_iksar_miner_lt:
INSERT INTO loottable(name) VALUES('chardok_an_escaped_slave'); # :chardok_an_escaped_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_an_iksar_betrayer'); # :chardok_an_iksar_betrayer_lt:
INSERT INTO loottable(name) VALUES('chardok_an_iksar_collaborator'); # :chardok_an_iksar_collaborator_lt:
INSERT INTO loottable(name) VALUES('chardok_an_iksar_trustee'); # :chardok_an_iksar_trustee_lt:
INSERT INTO loottable(name) VALUES('chardok_an_imperial_advisor'); # :chardok_an_imperial_advisor_lt:
INSERT INTO loottable(name) VALUES('chardok_an_imperial_construct'); # :chardok_an_imperial_construct_lt:
INSERT INTO loottable(name) VALUES('chardok_an_imperial_courier'); # :chardok_an_imperial_courier_lt:
INSERT INTO loottable(name) VALUES('chardok_an_imperial_defender'); # :chardok_an_imperial_defender_lt:
INSERT INTO loottable(name) VALUES('chardok_an_imperial_gravemaster'); # :chardok_an_imperial_gravemaster_lt:
INSERT INTO loottable(name) VALUES('chardok_an_imperial_inspector'); # :chardok_an_imperial_inspector_lt:
INSERT INTO loottable(name) VALUES('chardok_an_imperial_interrogator'); # :chardok_an_imperial_interrogator_lt:
INSERT INTO loottable(name) VALUES('chardok_an_imperial_officer'); # :chardok_an_imperial_officer_lt:
INSERT INTO loottable(name) VALUES('chardok_an_imperial_wardog'); # :chardok_an_imperial_wardog_lt:
INSERT INTO loottable(name) VALUES('chardok_an_insane_slave'); # :chardok_an_insane_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_an_off_duty_accountant'); # :chardok_an_off_duty_accountant_lt:
INSERT INTO loottable(name) VALUES('chardok_an_off_duty_overseer'); # :chardok_an_off_duty_overseer_lt:
INSERT INTO loottable(name) VALUES('chardok_an_off_duty_pitboss'); # :chardok_an_off_duty_pitboss_lt:
INSERT INTO loottable(name) VALUES('chardok_an_off_duty_researcher'); # :chardok_an_off_duty_researcher_lt:
INSERT INTO loottable(name) VALUES('chardok_an_off_duty_scribe'); # :chardok_an_off_duty_scribe_lt:
INSERT INTO loottable(name) VALUES('chardok_an_off_duty_slavemaster'); # :chardok_an_off_duty_slavemaster_lt:
INSERT INTO loottable(name) VALUES('chardok_an_unhappy_slave'); # :chardok_an_unhappy_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_arch_inspector_nibizi'); # :chardok_arch_inspector_nibizi_lt:
INSERT INTO loottable(name) VALUES('chardok_a_alchemists_acolyte'); # :chardok_a_alchemists_acolyte_lt:
INSERT INTO loottable(name) VALUES('chardok_a_block_foreman'); # :chardok_a_block_foreman_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chardoki_golem'); # :chardok_a_chardoki_golem_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_bloodhound'); # :chardok_a_chokidai_bloodhound_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_bonesnapper'); # :chardok_a_chokidai_bonesnapper_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_fleshripper'); # :chardok_a_chokidai_fleshripper_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_growler'); # :chardok_a_chokidai_growler_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_herbsniffer'); # :chardok_a_chokidai_herbsniffer_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_lasher'); # :chardok_a_chokidai_lasher_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_mangler'); # :chardok_a_chokidai_mangler_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_mauler'); # :chardok_a_chokidai_mauler_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_pitfighter'); # :chardok_a_chokidai_pitfighter_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_rootdigger'); # :chardok_a_chokidai_rootdigger_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_sniffer'); # :chardok_a_chokidai_sniffer_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_sunderfiend'); # :chardok_a_chokidai_sunderfiend_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_tearer'); # :chardok_a_chokidai_tearer_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_terror'); # :chardok_a_chokidai_terror_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_wardog'); # :chardok_a_chokidai_wardog_lt:
INSERT INTO loottable(name) VALUES('chardok_a_chokidai_whelp'); # :chardok_a_chokidai_whelp_lt:
INSERT INTO loottable(name) VALUES('chardok_a_confused_slave'); # :chardok_a_confused_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_crystal_shard_golem'); # :chardok_a_crystal_shard_golem_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dirty_slave'); # :chardok_a_dirty_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_herbalist'); # :chardok_a_dizok_herbalist_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_observer'); # :chardok_a_dizok_observer_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_researcher'); # :chardok_a_dizok_researcher_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_sergeant'); # :chardok_a_dizok_sergeant_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_aruspex'); # :chardok_a_dizok_aruspex_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_captain'); # :chardok_a_dizok_captain_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_channeler'); # :chardok_a_dizok_channeler_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_conscript'); # :chardok_a_dizok_conscript_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_cryptmaster'); # :chardok_a_dizok_cryptmaster_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_dragoon'); # :chardok_a_dizok_dragoon_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_evoker'); # :chardok_a_dizok_evoker_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_follower'); # :chardok_a_dizok_follower_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_gravebinder'); # :chardok_a_dizok_gravebinder_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_guardian'); # :chardok_a_dizok_guardian_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_herbalist'); # :chardok_a_dizok_herbalist_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_invoker'); # :chardok_a_dizok_invoker_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_jannisary'); # :chardok_a_dizok_jannisary_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_legionnaire'); # :chardok_a_dizok_legionnaire_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_librarian'); # :chardok_a_dizok_librarian_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_myrmidon'); # :chardok_a_dizok_myrmidon_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_partisan'); # :chardok_a_dizok_partisan_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_recruit'); # :chardok_a_dizok_recruit_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_revealer'); # :chardok_a_dizok_revealer_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_sage'); # :chardok_a_dizok_sage_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_seer'); # :chardok_a_dizok_seer_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_sergeant'); # :chardok_a_dizok_sergeant_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_soldier'); # :chardok_a_dizok_soldier_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_underling'); # :chardok_a_dizok_underling_lt:
INSERT INTO loottable(name) VALUES('chardok_a_dizok_warlord'); # :chardok_a_dizok_warlord_lt:
INSERT INTO loottable(name) VALUES('chardok_a_droopy_slave'); # :chardok_a_droopy_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_greater_guardian'); # :chardok_a_greater_guardian_lt:
INSERT INTO loottable(name) VALUES('chardok_a_gruff_slave'); # :chardok_a_gruff_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_grumpy_slave'); # :chardok_a_grumpy_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_lesser_guardian'); # :chardok_a_lesser_guardian_lt:
INSERT INTO loottable(name) VALUES('chardok_a_miserable_slave'); # :chardok_a_miserable_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_mix'); # :chardok_a_mix_lt:
INSERT INTO loottable(name) VALUES('chardok_a_muddy_slave'); # :chardok_a_muddy_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_reanimated_berserker'); # :chardok_a_reanimated_berserker_lt:
INSERT INTO loottable(name) VALUES('chardok_a_reanimated_champion'); # :chardok_a_reanimated_champion_lt:
INSERT INTO loottable(name) VALUES('chardok_a_reanimated_conscript'); # :chardok_a_reanimated_conscript_lt:
INSERT INTO loottable(name) VALUES('chardok_a_reanimated_dragoon'); # :chardok_a_reanimated_dragoon_lt:
INSERT INTO loottable(name) VALUES('chardok_a_reanimated_partisan'); # :chardok_a_reanimated_partisan_lt:
INSERT INTO loottable(name) VALUES('chardok_a_royal_library_guard'); # :chardok_a_royal_library_guard_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sad_ratman_slave'); # :chardok_a_sad_ratman_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sad_slave'); # :chardok_a_sad_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_aruspex'); # :chardok_a_sarnak_aruspex_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_aruspice'); # :chardok_a_sarnak_aruspice_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_dog_handler'); # :chardok_a_sarnak_dog_handler_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_foreman'); # :chardok_a_sarnak_foreman_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_herb_collector'); # :chardok_a_sarnak_herb_collector_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_janissary'); # :chardok_a_sarnak_janissary_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_manager'); # :chardok_a_sarnak_manager_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_myrmidon'); # :chardok_a_sarnak_myrmidon_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_overseer'); # :chardok_a_sarnak_overseer_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_physician'); # :chardok_a_sarnak_physician_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_pitboss'); # :chardok_a_sarnak_pitboss_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_slavedriver'); # :chardok_a_sarnak_slavedriver_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_slavemaster'); # :chardok_a_sarnak_slavemaster_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_templar'); # :chardok_a_sarnak_templar_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_underboss'); # :chardok_a_sarnak_underboss_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sarnak_whipcracker'); # :chardok_a_sarnak_whipcracker_lt:
INSERT INTO loottable(name) VALUES('chardok_a_scarred_overseer'); # :chardok_a_scarred_overseer_lt:
INSERT INTO loottable(name) VALUES('chardok_a_security_advisor'); # :chardok_a_security_advisor_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_bloodomen'); # :chardok_a_shaidin_bloodomen_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_bonecollector'); # :chardok_a_shaidin_bonecollector_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_conscript'); # :chardok_a_shaidin_conscript_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_follower'); # :chardok_a_shaidin_follower_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_hemlock'); # :chardok_a_shaidin_hemlock_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_jannisary'); # :chardok_a_shaidin_jannisary_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_myrmidon'); # :chardok_a_shaidin_myrmidon_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_nightfear'); # :chardok_a_shaidin_nightfear_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_partisan'); # :chardok_a_shaidin_partisan_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_savant'); # :chardok_a_shaidin_savant_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_soldier'); # :chardok_a_shaidin_soldier_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_soultrapper'); # :chardok_a_shaidin_soultrapper_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shaidin_warlord'); # :chardok_a_shaidin_warlord_lt:
INSERT INTO loottable(name) VALUES('chardok_a_shivering_slave'); # :chardok_a_shivering_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_skinny_slave'); # :chardok_a_skinny_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_slaveblock_guard'); # :chardok_a_slaveblock_guard_lt:
INSERT INTO loottable(name) VALUES('chardok_a_smelly_slave'); # :chardok_a_smelly_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_soggy_slave'); # :chardok_a_soggy_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_sullen_slave'); # :chardok_a_sullen_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_terrified_slave'); # :chardok_a_terrified_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_tired_slave'); # :chardok_a_tired_slave_lt:
INSERT INTO loottable(name) VALUES('chardok_a_tortured_iksar_miner'); # :chardok_a_tortured_iksar_miner_lt:
INSERT INTO loottable(name) VALUES('chardok_a_treasury_guard'); # :chardok_a_treasury_guard_lt:
INSERT INTO loottable(name) VALUES('chardok_a_veteran_drillmaster'); # :chardok_a_veteran_drillmaster_lt:
INSERT INTO loottable(name) VALUES('chardok_a_veteran_overseer'); # :chardok_a_veteran_overseer_lt:
INSERT INTO loottable(name) VALUES('chardok_a_veteran_underboss'); # :chardok_a_veteran_underboss_lt:
INSERT INTO loottable(name) VALUES('chardok_a_wizened_herb_collector'); # :chardok_a_wizened_herb_collector_lt:
INSERT INTO loottable(name) VALUES('chardok_battle_master_skatu'); # :chardok_battle_master_skatu_lt:
INSERT INTO loottable(name) VALUES('chardok_captain_diouz'); # :chardok_captain_diouz_lt:
INSERT INTO loottable(name) VALUES('chardok_clanging_sounds'); # :chardok_clanging_sounds_lt:
INSERT INTO loottable(name) VALUES('chardok_councilman_buzdarloan_iii'); # :chardok_councilman_buzdarloan_iii_lt:
INSERT INTO loottable(name) VALUES('chardok_councilman_caroeth_iii'); # :chardok_councilman_caroeth_iii_lt:
INSERT INTO loottable(name) VALUES('chardok_councilman_garkerok_iii'); # :chardok_councilman_garkerok_iii_lt:
INSERT INTO loottable(name) VALUES('chardok_councilman_gwalnax_iii'); # :chardok_councilman_gwalnax_iii_lt:
INSERT INTO loottable(name) VALUES('chardok_councilman_laanari_iii'); # :chardok_councilman_laanari_iii_lt:
INSERT INTO loottable(name) VALUES('chardok_councilman_neyir_iii'); # :chardok_councilman_neyir_iii_lt:
INSERT INTO loottable(name) VALUES('chardok_councilman_ysabrial_iii'); # :chardok_councilman_ysabrial_iii_lt:
INSERT INTO loottable(name) VALUES('chardok_deathfang'); # :chardok_deathfang_lt:
INSERT INTO loottable(name) VALUES('chardok_dizok_elite_guard'); # :chardok_dizok_elite_guard_lt:
INSERT INTO loottable(name) VALUES('chardok_dizok_royal_guard'); # :chardok_dizok_royal_guard_lt:
INSERT INTO loottable(name) VALUES('chardok_drill_master_dihroul'); # :chardok_drill_master_dihroul_lt:
INSERT INTO loottable(name) VALUES('chardok_foreman_kulul'); # :chardok_foreman_kulul_lt:
INSERT INTO loottable(name) VALUES('chardok_foreman_mirtakk'); # :chardok_foreman_mirtakk_lt:
INSERT INTO loottable(name) VALUES('chardok_grand_advisor_zumuul'); # :chardok_grand_advisor_zumuul_lt:
INSERT INTO loottable(name) VALUES('chardok_grand_herbalist_makha'); # :chardok_grand_herbalist_makha_lt:
INSERT INTO loottable(name) VALUES('chardok_grand_lorekeeper_kino_shaidin'); # :chardok_grand_lorekeeper_kino_shaidin_lt:
INSERT INTO loottable(name) VALUES('chardok_grave_master_zolun'); # :chardok_grave_master_zolun_lt:
INSERT INTO loottable(name) VALUES('chardok_haggle_baron_drydn'); # :chardok_haggle_baron_drydn_lt:
INSERT INTO loottable(name) VALUES('chardok_herald_telcha'); # :chardok_herald_telcha_lt:
INSERT INTO loottable(name) VALUES('chardok_judicator_of_dizok'); # :chardok_judicator_of_dizok_lt:
INSERT INTO loottable(name) VALUES('chardok_kennel_master_alele'); # :chardok_kennel_master_alele_lt:
INSERT INTO loottable(name) VALUES('chardok_korucusts_courier'); # :chardok_korucusts_courier_lt:
INSERT INTO loottable(name) VALUES('chardok_loremaster_pizatak'); # :chardok_loremaster_pizatak_lt:
INSERT INTO loottable(name) VALUES('chardok_niblek'); # :chardok_niblek_lt:
INSERT INTO loottable(name) VALUES('chardok_observer_aqtouz'); # :chardok_observer_aqtouz_lt:
INSERT INTO loottable(name) VALUES('chardok_overking_bathezid'); # :chardok_overking_bathezid_lt:
INSERT INTO loottable(name) VALUES('chardok_overseer_dalguur'); # :chardok_overseer_dalguur_lt:
INSERT INTO loottable(name) VALUES('chardok_prince_selrach_dizok'); # :chardok_prince_selrach_dizok_lt:
INSERT INTO loottable(name) VALUES('chardok_queen_velazul_dizok'); # :chardok_queen_velazul_dizok_lt:
INSERT INTO loottable(name) VALUES('chardok_sarnak_collective_auditor'); # :chardok_sarnak_collective_auditor_lt:
INSERT INTO loottable(name) VALUES('chardok_sorcerer_of_dizok'); # :chardok_sorcerer_of_dizok_lt:
INSERT INTO loottable(name) VALUES('chardok_the_bridge'); # :chardok_the_bridge_lt:
INSERT INTO loottable(name) VALUES('chardok_the_bridge_keeper'); # :chardok_the_bridge_keeper_lt:
INSERT INTO loottable(name) VALUES('chardok_the_clang'); # :chardok_the_clang_lt:
INSERT INTO loottable(name) VALUES('chardok_the_cries'); # :chardok_the_cries_lt:
INSERT INTO loottable(name) VALUES('chardok_the_earth'); # :chardok_the_earth_lt:
INSERT INTO loottable(name) VALUES('chardok_the_musty'); # :chardok_the_musty_lt:
INSERT INTO loottable(name) VALUES('chardok_the_sounds'); # :chardok_the_sounds_lt:
INSERT INTO loottable(name) VALUES('chardok_the_stench'); # :chardok_the_stench_lt:
INSERT INTO loottable(name) VALUES('chardok_the_thick'); # :chardok_the_thick_lt:
INSERT INTO loottable(name) VALUES('chardok_underboss_myliki'); # :chardok_underboss_myliki_lt:
INSERT INTO loottable(name) VALUES('chardok_vault_master_shuzo'); # :chardok_vault_master_shuzo_lt:
INSERT INTO loottable(name) VALUES('chardok_watch_captain_hirroul'); # :chardok_watch_captain_hirroul_lt:
INSERT INTO loottable(name) VALUES('chardok_watch_sergeant_rizoul'); # :chardok_watch_sergeant_rizoul_lt:
INSERT INTO loottable(name) VALUES('chardok_wraith_of_a_dizok_hero'); # :chardok_wraith_of_a_dizok_hero_lt:
INSERT INTO loottable(name) VALUES('chardok_your_feet_splash'); # :chardok_your_feet_splash_lt:
INSERT INTO loottable(name) VALUES('chardok_your_mind'); # :chardok_your_mind_lt:
INSERT INTO loottable(name) VALUES('chardok_your_shin'); # :chardok_your_shin_lt:
INSERT INTO loottable(name) VALUES('chardok_you_hear'); # :chardok_you_hear_lt:
INSERT INTO loottable(name) VALUES('chardok_you_notice'); # :chardok_you_notice_lt:
INSERT INTO loottable(name) VALUES('chardok_you_seem'); # :chardok_you_seem_lt:
