INSERT INTO loottable(name) VALUES('dreadlands_brother_balatin'); # :dreadlands_brother_balatin_lt:
INSERT INTO loottable(name) VALUES('dreadlands_chaos_elemental'); # :dreadlands_chaos_elemental_lt:
INSERT INTO loottable(name) VALUES('dreadlands_mage_trap'); # :dreadlands_mage_trap_lt:
INSERT INTO loottable(name) VALUES('dreadlands_the_fabled_gorenaire'); # :dreadlands_the_fabled_gorenaire_lt:
INSERT INTO loottable(name) VALUES('dreadlands_the_fabled_rotting_skeleton'); # :dreadlands_the_fabled_rotting_skeleton_lt:
INSERT INTO loottable(name) VALUES('dreadlands_time_torn_acolyte'); # :dreadlands_time_torn_acolyte_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drachnid_recluse'); # :dreadlands_a_drachnid_recluse_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drachnid_silkmistress'); # :dreadlands_a_drachnid_silkmistress_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drachnid_silkstrander'); # :dreadlands_a_drachnid_silkstrander_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drachnid_webmaster'); # :dreadlands_a_drachnid_webmaster_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drachnid_webstrander'); # :dreadlands_a_drachnid_webstrander_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drachnid_widow'); # :dreadlands_a_drachnid_widow_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_dread_widow'); # :dreadlands_a_dread_widow_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drolvarg_gnasher'); # :dreadlands_a_drolvarg_gnasher_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drolvarg_growler'); # :dreadlands_a_drolvarg_growler_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drolvarg_rager'); # :dreadlands_a_drolvarg_rager_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_drolvarg_snarler'); # :dreadlands_a_drolvarg_snarler_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_glacier_yeti'); # :dreadlands_a_glacier_yeti_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_loyal_follower'); # :dreadlands_a_loyal_follower_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_mountain_giant_brae'); # :dreadlands_a_mountain_giant_brae_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_mountain_giant_craig'); # :dreadlands_a_mountain_giant_craig_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_mountain_giant_patriarch'); # :dreadlands_a_mountain_giant_patriarch_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_mountain_giant_steep'); # :dreadlands_a_mountain_giant_steep_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_mystic_voice'); # :dreadlands_a_mystic_voice_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_petrifier_cockatrice'); # :dreadlands_a_petrifier_cockatrice_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_plaguebone_thief'); # :dreadlands_a_plaguebone_thief_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_ravishing_drolvarg'); # :dreadlands_a_ravishing_drolvarg_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_stonegazer_cockatrice'); # :dreadlands_a_stonegazer_cockatrice_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_stoneleer_cockatrice'); # :dreadlands_a_stoneleer_cockatrice_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_tundra_yeti'); # :dreadlands_a_tundra_yeti_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_voracious_brute'); # :dreadlands_a_voracious_brute_lt:
INSERT INTO loottable(name) VALUES('dreadlands_a_wulfware_lonewolf'); # :dreadlands_a_wulfware_lonewolf_lt:
INSERT INTO loottable(name) VALUES('dreadlands_baldric_slezaf'); # :dreadlands_baldric_slezaf_lt:
INSERT INTO loottable(name) VALUES('dreadlands_brother_balatin'); # :dreadlands_brother_balatin_lt:
INSERT INTO loottable(name) VALUES('dreadlands_gem_cutter_skeleton'); # :dreadlands_gem_cutter_skeleton_lt:
INSERT INTO loottable(name) VALUES('dreadlands_gorenaire'); # :dreadlands_gorenaire_lt:
INSERT INTO loottable(name) VALUES('dreadlands_greater_plaguebone'); # :dreadlands_greater_plaguebone_lt:
INSERT INTO loottable(name) VALUES('dreadlands_greater_spurbone'); # :dreadlands_greater_spurbone_lt:
INSERT INTO loottable(name) VALUES('dreadlands_klok_ftshai'); # :dreadlands_klok_ftshai_lt:
INSERT INTO loottable(name) VALUES('dreadlands_kunark_spires'); # :dreadlands_kunark_spires_lt:
INSERT INTO loottable(name) VALUES('dreadlands_mountain_giant_brae'); # :dreadlands_mountain_giant_brae_lt:
INSERT INTO loottable(name) VALUES('dreadlands_mountain_giant_craig'); # :dreadlands_mountain_giant_craig_lt:
INSERT INTO loottable(name) VALUES('dreadlands_nexus_scion'); # :dreadlands_nexus_scion_lt:
INSERT INTO loottable(name) VALUES('dreadlands_plaguebone_skeleton'); # :dreadlands_plaguebone_skeleton_lt:
INSERT INTO loottable(name) VALUES('dreadlands_remnant_spirit'); # :dreadlands_remnant_spirit_lt:
INSERT INTO loottable(name) VALUES('dreadlands_rotting_skeleton'); # :dreadlands_rotting_skeleton_lt:
INSERT INTO loottable(name) VALUES('dreadlands_sionie_the_sage'); # :dreadlands_sionie_the_sage_lt:
INSERT INTO loottable(name) VALUES('dreadlands_the_norrath_spires'); # :dreadlands_the_norrath_spires_lt:
INSERT INTO loottable(name) VALUES('dreadlands_time_terror'); # :dreadlands_time_terror_lt:
INSERT INTO loottable(name) VALUES('dreadlands_veltar'); # :dreadlands_veltar_lt:
