INSERT INTO loottable(name) VALUES('kaesora_an_iksar_spectre'); # :kaesora_an_iksar_spectre_lt:
INSERT INTO loottable(name) VALUES('kaesora_a_corrupt_spiritualist'); # :kaesora_a_corrupt_spiritualist_lt:
INSERT INTO loottable(name) VALUES('kaesora_a_freed_soul'); # :kaesora_a_freed_soul_lt:
INSERT INTO loottable(name) VALUES('kaesora_a_tome_keeper'); # :kaesora_a_tome_keeper_lt:
INSERT INTO loottable(name) VALUES('kaesora_briarweb_spider'); # :kaesora_briarweb_spider_lt:
INSERT INTO loottable(name) VALUES('kaesora_bristleweb_spider'); # :kaesora_bristleweb_spider_lt:
INSERT INTO loottable(name) VALUES('kaesora_enraged_ravener'); # :kaesora_enraged_ravener_lt:
INSERT INTO loottable(name) VALUES('kaesora_enraged_spectral_librarian'); # :kaesora_enraged_spectral_librarian_lt:
INSERT INTO loottable(name) VALUES('kaesora_failed_crypt_raider'); # :kaesora_failed_crypt_raider_lt:
INSERT INTO loottable(name) VALUES('kaesora_famished_ravener'); # :kaesora_famished_ravener_lt:
INSERT INTO loottable(name) VALUES('kaesora_frenzied_strathbone'); # :kaesora_frenzied_strathbone_lt:
INSERT INTO loottable(name) VALUES('kaesora_gorged_ravener'); # :kaesora_gorged_ravener_lt:
INSERT INTO loottable(name) VALUES('kaesora_guardian_of_xalgoz'); # :kaesora_guardian_of_xalgoz_lt:
INSERT INTO loottable(name) VALUES('kaesora_hungered_ravener'); # :kaesora_hungered_ravener_lt:
INSERT INTO loottable(name) VALUES('kaesora_minion_of_xalgoz'); # :kaesora_minion_of_xalgoz_lt:
INSERT INTO loottable(name) VALUES('kaesora_ravener'); # :kaesora_ravener_lt:
INSERT INTO loottable(name) VALUES('kaesora_reaver_of_xalgoz'); # :kaesora_reaver_of_xalgoz_lt:
INSERT INTO loottable(name) VALUES('kaesora_skeletal_guardian'); # :kaesora_skeletal_guardian_lt:
INSERT INTO loottable(name) VALUES('kaesora_skeletal_minion'); # :kaesora_skeletal_minion_lt:
INSERT INTO loottable(name) VALUES('kaesora_skeletal_warder'); # :kaesora_skeletal_warder_lt:
INSERT INTO loottable(name) VALUES('kaesora_spectral_guardian'); # :kaesora_spectral_guardian_lt:
INSERT INTO loottable(name) VALUES('kaesora_spectral_librarian'); # :kaesora_spectral_librarian_lt:
INSERT INTO loottable(name) VALUES('kaesora_strathbone_healer'); # :kaesora_strathbone_healer_lt:
INSERT INTO loottable(name) VALUES('kaesora_strathbone_runelord'); # :kaesora_strathbone_runelord_lt:
INSERT INTO loottable(name) VALUES('kaesora_strathbone_spider'); # :kaesora_strathbone_spider_lt:
INSERT INTO loottable(name) VALUES('kaesora_tortured_librarian'); # :kaesora_tortured_librarian_lt:
INSERT INTO loottable(name) VALUES('kaesora_warder_of_xalgoz'); # :kaesora_warder_of_xalgoz_lt:
INSERT INTO loottable(name) VALUES('kaesora_xalgoz'); # :kaesora_xalgoz_lt:
