UPDATE npc_types SET loottable_id = :overthere_an_undead_marine_lt: WHERE id in (93303); # #an_undead_marine 50
UPDATE npc_types SET loottable_id = :overthere_a_corrupted_koalindl_lt: WHERE id in (93306); # #A_Corrupted_Koalindl 60
UPDATE npc_types SET loottable_id = :overthere_daytrigger_lt: WHERE id in (93304); # #daytrigger 99
UPDATE npc_types SET loottable_id = :overthere_high_priest_ixar_lt: WHERE id in (93186); # #High_Priest_I`Xar 40
UPDATE npc_types SET loottable_id = :overthere_irionu_bastun_lt: WHERE id in (93302); # #Irionu_Bastun 65
UPDATE npc_types SET loottable_id = :overthere_nighttrigger_lt: WHERE id in (93305); # #nighttrigger 99
UPDATE npc_types SET loottable_id = :overthere_translocator_breya_lt: WHERE id in (93157); # #Translocator_Breya 1
UPDATE npc_types SET loottable_id = :overthere_yiln_darksly_lt: WHERE id in (93153); # #Yiln_Darksly 45
UPDATE npc_types SET loottable_id = :overthere___6_lt: WHERE id in (93300); # #_#_6 60
UPDATE npc_types SET loottable_id = :overthere_admiral_tylix_lt: WHERE id in (93159); # Admiral_Tylix 59
UPDATE npc_types SET loottable_id = :overthere_alchemist_granika_lt: WHERE id in (93075); # Alchemist_Granika 25
UPDATE npc_types SET loottable_id = :overthere_an_undead_foreman_lt: WHERE id in (93082); # an_undead_foreman 50
UPDATE npc_types SET loottable_id = :overthere_an_undead_herald_lt: WHERE id in (93115, 93175); # an_undead_herald 32
UPDATE npc_types SET loottable_id = :overthere_an_undead_marine_lt: WHERE id in (93126); # an_undead_marine 50
UPDATE npc_types SET loottable_id = :overthere_astral_projection_lt: WHERE id in (93154); # Astral_Projection 50
UPDATE npc_types SET loottable_id = :overthere_a_barbed_succulent_lt: WHERE id in (93073, 93161, 93162); # a_barbed_succulent 19
UPDATE npc_types SET loottable_id = :overthere_a_bristly_succulent_lt: WHERE id in (93092, 93098, 93102); # a_bristly_succulent 12
UPDATE npc_types SET loottable_id = :overthere_a_cliff_golem_lt: WHERE id in (93077); # a_cliff_golem 58
UPDATE npc_types SET loottable_id = :overthere_a_glowing_cliff_golem_lt: WHERE id in (93190); # a_glowing_cliff_golem 55
UPDATE npc_types SET loottable_id = :overthere_a_kunark_rhino_lt: WHERE id in (93007, 93015, 93021, 93031, 93033, 93048, 93072, 93163); # a_kunark_rhino 35
UPDATE npc_types SET loottable_id = :overthere_a_prickly_succulent_lt: WHERE id in (93046, 93067, 93070); # a_prickly_succulent 15
UPDATE npc_types SET loottable_id = :overthere_a_sabertooth_cat_lt: WHERE id in (93099, 93101, 93103); # a_sabertooth_cat 10
UPDATE npc_types SET loottable_id = :overthere_a_sabertooth_tiger_lt: WHERE id in (93049, 93165); # a_sabertooth_tiger 18
UPDATE npc_types SET loottable_id = :overthere_a_sabertooth_tigress_lt: WHERE id in (93055, 93064, 93069); # a_sabertooth_tigress 16
UPDATE npc_types SET loottable_id = :overthere_a_sarnak_berzerker_lt: WHERE id in (93001, 93003, 93080, 93081, 93158, 93171, 93183); # a_Sarnak_berzerker 30
UPDATE npc_types SET loottable_id = :overthere_a_sarnak_conscript_lt: WHERE id in (93041); # a_Sarnak_conscript 20
UPDATE npc_types SET loottable_id = :overthere_a_sarnak_enthusiast_lt: WHERE id in (93038, 93047, 93170, 93178); # a_Sarnak_enthusiast 34
UPDATE npc_types SET loottable_id = :overthere_a_sarnak_flunkie_lt: WHERE id in (93042, 93044, 93079); # a_Sarnak_flunkie 15
UPDATE npc_types SET loottable_id = :overthere_a_sarnak_knight_lt: WHERE id in (93022, 93023, 93027, 93050, 93052); # a_Sarnak_knight 34
UPDATE npc_types SET loottable_id = :overthere_a_sarnak_messenger_lt: WHERE id in (93058); # a_sarnak_messenger 38
UPDATE npc_types SET loottable_id = :overthere_a_sarnak_partisan_lt: WHERE id in (93008, 93011, 93051, 93057, 93108); # a_Sarnak_partisan 33
UPDATE npc_types SET loottable_id = :overthere_a_sarnak_youth_lt: WHERE id in (93100, 93106, 93107); # a_Sarnak_youth 10
UPDATE npc_types SET loottable_id = :overthere_a_scorpikis_lt: WHERE id in (93020, 93024, 93035, 93037, 93039); # a_scorpikis 36
UPDATE npc_types SET loottable_id = :overthere_a_scorpikis_scrounger_lt: WHERE id in (93097, 93174, 93180, 93181); # a_scorpikis_scrounger 34
UPDATE npc_types SET loottable_id = :overthere_a_skeleton_worker_lt: WHERE id in (93184, 93078, 93140, 93172, 93182); # a_skeleton_worker 33
UPDATE npc_types SET loottable_id = :overthere_a_spiked_succulent_lt: WHERE id in (93004, 93006, 93019, 93030, 93034); # a_spiked_succulent 33
UPDATE npc_types SET loottable_id = :overthere_a_stonegazer_cockatrice_lt: WHERE id in (93005, 93009, 93018, 93068, 93164); # a_stonegazer_cockatrice 35
UPDATE npc_types SET loottable_id = :overthere_a_stoneglint_cockatrice_lt: WHERE id in (93060, 93062, 93065); # a_stoneglint_cockatrice 20
UPDATE npc_types SET loottable_id = :overthere_a_stoneleer_cockatrice_lt: WHERE id in (93013, 93026, 93028, 93053, 93076); # a_stoneleer_cockatrice 29
UPDATE npc_types SET loottable_id = :overthere_a_stonepeep_cockatrice_lt: WHERE id in (93054, 93063, 93071); # a_stonepeep_cockatrice 16
UPDATE npc_types SET loottable_id = :overthere_a_thorny_succulent_lt: WHERE id in (93000, 93012, 93014, 93017, 93045); # a_thorny_succulent 31
UPDATE npc_types SET loottable_id = :overthere_bloated_belly_lt: WHERE id in (93176); # Bloated_Belly 50
UPDATE npc_types SET loottable_id = :overthere_brinaa_darkpact_lt: WHERE id in (93114); # Brinaa_Darkpact 49
UPDATE npc_types SET loottable_id = :overthere_bukuku_wolffeetz_lt: WHERE id in (93111); # Bukuku_Wolffeetz 49
UPDATE npc_types SET loottable_id = :overthere_captain_rottgrime_lt: WHERE id in (93085); # Captain_Rottgrime 55
UPDATE npc_types SET loottable_id = :overthere_child_of_charasis_lt: WHERE id in (93189); # child_of_Charasis 49
UPDATE npc_types SET loottable_id = :overthere_corundium_lt: WHERE id in (93145); # Corundium 50
UPDATE npc_types SET loottable_id = :overthere_dom_kperl_lt: WHERE id in (93148); # Dom_K`Perl 30
UPDATE npc_types SET loottable_id = :overthere_dragoon_barber_wselo_lt: WHERE id in (93124); # Dragoon_Barber_W`Selo 50
UPDATE npc_types SET loottable_id = :overthere_dragoon_tvem_lt: WHERE id in (93088); # Dragoon_T`Vem 50
UPDATE npc_types SET loottable_id = :overthere_dragoon_tvex_lt: WHERE id in (93084); # Dragoon_T`Vex 50
UPDATE npc_types SET loottable_id = :overthere_dragoon_vlask_lt: WHERE id in (93125); # Dragoon_V`Lask 50
UPDATE npc_types SET loottable_id = :overthere_dragoon_vresh_lt: WHERE id in (93086); # Dragoon_V`Resh 50
UPDATE npc_types SET loottable_id = :overthere_drixiv_arcut_lt: WHERE id in (93091); # Drixiv_Arcut 50
UPDATE npc_types SET loottable_id = :overthere_dyth_xteria_lt: WHERE id in (93116); # Dyth_X`Teria 61
UPDATE npc_types SET loottable_id = :overthere_finlay_kitoran_lt: WHERE id in (93119); # Finlay_Kitoran 40
UPDATE npc_types SET loottable_id = :overthere_galdon_vok_nir_lt: WHERE id in (93147); # Galdon_Vok_Nir 15
UPDATE npc_types SET loottable_id = :overthere_general_vdeers_lt: WHERE id in (93087); # General_V`Deers 58
UPDATE npc_types SET loottable_id = :overthere_gogu_the_smasher_lt: WHERE id in (93155); # Gogu_the_Smasher 61
UPDATE npc_types SET loottable_id = :overthere_grubmar_hartblak_lt: WHERE id in (93117); # Grubmar_Hartblak 40
UPDATE npc_types SET loottable_id = :overthere_impaler_tzilug_lt: WHERE id in (93149); # Impaler_Tzilug 50
UPDATE npc_types SET loottable_id = :overthere_inem_rker_lt: WHERE id in (93301); # Inem_R`ker 65
UPDATE npc_types SET loottable_id = :overthere_iron_guardian_lt: WHERE id in (93141); # Iron_Guardian 50
UPDATE npc_types SET loottable_id = :overthere_iron_sentinel_lt: WHERE id in (93089); # Iron_Sentinel 50
UPDATE npc_types SET loottable_id = :overthere_ixpacan_lt: WHERE id in (93185); # Ixpacan 61
UPDATE npc_types SET loottable_id = :overthere_kelsi_qgrinol_lt: WHERE id in (93118); # Kelsi_Q`Grinol 40
UPDATE npc_types SET loottable_id = :overthere_klok_grshai_lt: WHERE id in (93146); # Klok_G`rshai 40
UPDATE npc_types SET loottable_id = :overthere_kuglaz_grot_lt: WHERE id in (93122); # Kuglaz_Grot 40
UPDATE npc_types SET loottable_id = :overthere_kurron_ni_lt: WHERE id in (93083); # Kurron_Ni 54
UPDATE npc_types SET loottable_id = :overthere_lissa_tborn_lt: WHERE id in (93123); # Lissa_T`Born 40
UPDATE npc_types SET loottable_id = :overthere_modani_quloni_lt: WHERE id in (93150); # Modani_Qu`Loni 55
UPDATE npc_types SET loottable_id = :overthere_nekexin_virulence_lt: WHERE id in (93043); # Nekexin_Virulence 60
UPDATE npc_types SET loottable_id = :overthere_osvima_kmatim_lt: WHERE id in (93104); # Osvima_K`Matim 35
UPDATE npc_types SET loottable_id = :overthere_pungub_brawlum_lt: WHERE id in (93105); # Pungub_Brawlum 35
UPDATE npc_types SET loottable_id = :overthere_sabretooth_tiger_lt: WHERE id in (93025, 93032, 93036, 93059, 93160); # sabretooth_tiger 39
UPDATE npc_types SET loottable_id = :overthere_sabretooth_tigress_lt: WHERE id in (93002, 93010, 93029, 93040, 93061); # sabretooth_tigress 31
UPDATE npc_types SET loottable_id = :overthere_scorpikis_guardian_lt: WHERE id in (93094, 93095, 93096, 93173, 93179); # Scorpikis_Guardian 43
UPDATE npc_types SET loottable_id = :overthere_siladdarae_nriese_lt: WHERE id in (93109); # Siladdarae_N`Riese 49
UPDATE npc_types SET loottable_id = :overthere_slicia_jsinge_lt: WHERE id in (93110); # Slicia_J`Singe 49
UPDATE npc_types SET loottable_id = :overthere_soulbinder_kardin_lt: WHERE id in (93156); # Soulbinder_Kardin 65
UPDATE npc_types SET loottable_id = :overthere_stishovite_lt: WHERE id in (93142); # Stishovite 50
UPDATE npc_types SET loottable_id = :overthere_tektite_lt: WHERE id in (93143); # Tektite 50
UPDATE npc_types SET loottable_id = :overthere_the_sounds_lt: WHERE id in (93187); # The_sounds 60
UPDATE npc_types SET loottable_id = :overthere_tin_banker_assistant_lt: WHERE id in (93151); # Tin_Banker_Assistant 40
UPDATE npc_types SET loottable_id = :overthere_tin_banker_i_lt: WHERE id in (93128); # Tin_Banker_I 40
UPDATE npc_types SET loottable_id = :overthere_tin_banker_ii_lt: WHERE id in (93127); # Tin_Banker_II 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_i_lt: WHERE id in (93139); # Tin_Merchant_I 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_ii_lt: WHERE id in (93138); # Tin_Merchant_II 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_iii_lt: WHERE id in (93137); # Tin_Merchant_III 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_iv_lt: WHERE id in (93136); # Tin_Merchant_IV 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_ix_lt: WHERE id in (93131); # Tin_Merchant_IX 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_v_lt: WHERE id in (93135); # Tin_Merchant_V 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_vi_lt: WHERE id in (93134); # Tin_Merchant_VI 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_vii_lt: WHERE id in (93133); # Tin_Merchant_VII 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_viii_lt: WHERE id in (93132); # Tin_Merchant_VIII 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_x_lt: WHERE id in (93130); # Tin_Merchant_X 40
UPDATE npc_types SET loottable_id = :overthere_tin_merchant_xi_lt: WHERE id in (93129); # Tin_Merchant_XI 40
UPDATE npc_types SET loottable_id = :overthere_tourmaline_lt: WHERE id in (93144); # Tourmaline 50
UPDATE npc_types SET loottable_id = :overthere_tyrin_flinz_lt: WHERE id in (93120); # Tyrin_F`Linz 40
UPDATE npc_types SET loottable_id = :overthere_uggrig_skullchomper_lt: WHERE id in (93152); # Uggrig_Skullchomper 61
UPDATE npc_types SET loottable_id = :overthere_utandar_rizndown_lt: WHERE id in (93112); # Utandar_Rizndown 40
UPDATE npc_types SET loottable_id = :overthere_vaean_the_night_lt: WHERE id in (93113); # Vaean_the_Night 49
UPDATE npc_types SET loottable_id = :overthere_varg_stonebelly_lt: WHERE id in (93188); # Varg_Stonebelly 99
UPDATE npc_types SET loottable_id = :overthere_vaxxim_tquoren_lt: WHERE id in (93093); # Vaxxim_T`Quoren 35
UPDATE npc_types SET loottable_id = :overthere_vizra_lnizlon_lt: WHERE id in (93121); # Vizra_L`Nizlon 40
UPDATE npc_types SET loottable_id = :overthere_xlixinar_arcut_lt: WHERE id in (93090); # Xlixinar_Arcut 50
UPDATE npc_types SET loottable_id = :overthere_zorash_lt: WHERE id in (93169); # Zorash 37
