INSERT INTO loottable(name) VALUES('overthere_an_undead_marine'); # :overthere_an_undead_marine_lt:
INSERT INTO loottable(name) VALUES('overthere_a_corrupted_koalindl'); # :overthere_a_corrupted_koalindl_lt:
INSERT INTO loottable(name) VALUES('overthere_daytrigger'); # :overthere_daytrigger_lt:
INSERT INTO loottable(name) VALUES('overthere_high_priest_ixar'); # :overthere_high_priest_ixar_lt:
INSERT INTO loottable(name) VALUES('overthere_irionu_bastun'); # :overthere_irionu_bastun_lt:
INSERT INTO loottable(name) VALUES('overthere_nighttrigger'); # :overthere_nighttrigger_lt:
INSERT INTO loottable(name) VALUES('overthere_translocator_breya'); # :overthere_translocator_breya_lt:
INSERT INTO loottable(name) VALUES('overthere_yiln_darksly'); # :overthere_yiln_darksly_lt:
INSERT INTO loottable(name) VALUES('overthere___6'); # :overthere___6_lt:
INSERT INTO loottable(name) VALUES('overthere_admiral_tylix'); # :overthere_admiral_tylix_lt:
INSERT INTO loottable(name) VALUES('overthere_alchemist_granika'); # :overthere_alchemist_granika_lt:
INSERT INTO loottable(name) VALUES('overthere_an_undead_foreman'); # :overthere_an_undead_foreman_lt:
INSERT INTO loottable(name) VALUES('overthere_an_undead_herald'); # :overthere_an_undead_herald_lt:
INSERT INTO loottable(name) VALUES('overthere_an_undead_marine'); # :overthere_an_undead_marine_lt:
INSERT INTO loottable(name) VALUES('overthere_astral_projection'); # :overthere_astral_projection_lt:
INSERT INTO loottable(name) VALUES('overthere_a_barbed_succulent'); # :overthere_a_barbed_succulent_lt:
INSERT INTO loottable(name) VALUES('overthere_a_bristly_succulent'); # :overthere_a_bristly_succulent_lt:
INSERT INTO loottable(name) VALUES('overthere_a_cliff_golem'); # :overthere_a_cliff_golem_lt:
INSERT INTO loottable(name) VALUES('overthere_a_glowing_cliff_golem'); # :overthere_a_glowing_cliff_golem_lt:
INSERT INTO loottable(name) VALUES('overthere_a_kunark_rhino'); # :overthere_a_kunark_rhino_lt:
INSERT INTO loottable(name) VALUES('overthere_a_prickly_succulent'); # :overthere_a_prickly_succulent_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sabertooth_cat'); # :overthere_a_sabertooth_cat_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sabertooth_tiger'); # :overthere_a_sabertooth_tiger_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sabertooth_tigress'); # :overthere_a_sabertooth_tigress_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sarnak_berzerker'); # :overthere_a_sarnak_berzerker_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sarnak_conscript'); # :overthere_a_sarnak_conscript_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sarnak_enthusiast'); # :overthere_a_sarnak_enthusiast_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sarnak_flunkie'); # :overthere_a_sarnak_flunkie_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sarnak_knight'); # :overthere_a_sarnak_knight_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sarnak_messenger'); # :overthere_a_sarnak_messenger_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sarnak_partisan'); # :overthere_a_sarnak_partisan_lt:
INSERT INTO loottable(name) VALUES('overthere_a_sarnak_youth'); # :overthere_a_sarnak_youth_lt:
INSERT INTO loottable(name) VALUES('overthere_a_scorpikis'); # :overthere_a_scorpikis_lt:
INSERT INTO loottable(name) VALUES('overthere_a_scorpikis_scrounger'); # :overthere_a_scorpikis_scrounger_lt:
INSERT INTO loottable(name) VALUES('overthere_a_skeleton_worker'); # :overthere_a_skeleton_worker_lt:
INSERT INTO loottable(name) VALUES('overthere_a_spiked_succulent'); # :overthere_a_spiked_succulent_lt:
INSERT INTO loottable(name) VALUES('overthere_a_stonegazer_cockatrice'); # :overthere_a_stonegazer_cockatrice_lt:
INSERT INTO loottable(name) VALUES('overthere_a_stoneglint_cockatrice'); # :overthere_a_stoneglint_cockatrice_lt:
INSERT INTO loottable(name) VALUES('overthere_a_stoneleer_cockatrice'); # :overthere_a_stoneleer_cockatrice_lt:
INSERT INTO loottable(name) VALUES('overthere_a_stonepeep_cockatrice'); # :overthere_a_stonepeep_cockatrice_lt:
INSERT INTO loottable(name) VALUES('overthere_a_thorny_succulent'); # :overthere_a_thorny_succulent_lt:
INSERT INTO loottable(name) VALUES('overthere_bloated_belly'); # :overthere_bloated_belly_lt:
INSERT INTO loottable(name) VALUES('overthere_brinaa_darkpact'); # :overthere_brinaa_darkpact_lt:
INSERT INTO loottable(name) VALUES('overthere_bukuku_wolffeetz'); # :overthere_bukuku_wolffeetz_lt:
INSERT INTO loottable(name) VALUES('overthere_captain_rottgrime'); # :overthere_captain_rottgrime_lt:
INSERT INTO loottable(name) VALUES('overthere_child_of_charasis'); # :overthere_child_of_charasis_lt:
INSERT INTO loottable(name) VALUES('overthere_corundium'); # :overthere_corundium_lt:
INSERT INTO loottable(name) VALUES('overthere_dom_kperl'); # :overthere_dom_kperl_lt:
INSERT INTO loottable(name) VALUES('overthere_dragoon_barber_wselo'); # :overthere_dragoon_barber_wselo_lt:
INSERT INTO loottable(name) VALUES('overthere_dragoon_tvem'); # :overthere_dragoon_tvem_lt:
INSERT INTO loottable(name) VALUES('overthere_dragoon_tvex'); # :overthere_dragoon_tvex_lt:
INSERT INTO loottable(name) VALUES('overthere_dragoon_vlask'); # :overthere_dragoon_vlask_lt:
INSERT INTO loottable(name) VALUES('overthere_dragoon_vresh'); # :overthere_dragoon_vresh_lt:
INSERT INTO loottable(name) VALUES('overthere_drixiv_arcut'); # :overthere_drixiv_arcut_lt:
INSERT INTO loottable(name) VALUES('overthere_dyth_xteria'); # :overthere_dyth_xteria_lt:
INSERT INTO loottable(name) VALUES('overthere_finlay_kitoran'); # :overthere_finlay_kitoran_lt:
INSERT INTO loottable(name) VALUES('overthere_galdon_vok_nir'); # :overthere_galdon_vok_nir_lt:
INSERT INTO loottable(name) VALUES('overthere_general_vdeers'); # :overthere_general_vdeers_lt:
INSERT INTO loottable(name) VALUES('overthere_gogu_the_smasher'); # :overthere_gogu_the_smasher_lt:
INSERT INTO loottable(name) VALUES('overthere_grubmar_hartblak'); # :overthere_grubmar_hartblak_lt:
INSERT INTO loottable(name) VALUES('overthere_impaler_tzilug'); # :overthere_impaler_tzilug_lt:
INSERT INTO loottable(name) VALUES('overthere_inem_rker'); # :overthere_inem_rker_lt:
INSERT INTO loottable(name) VALUES('overthere_iron_guardian'); # :overthere_iron_guardian_lt:
INSERT INTO loottable(name) VALUES('overthere_iron_sentinel'); # :overthere_iron_sentinel_lt:
INSERT INTO loottable(name) VALUES('overthere_ixpacan'); # :overthere_ixpacan_lt:
INSERT INTO loottable(name) VALUES('overthere_kelsi_qgrinol'); # :overthere_kelsi_qgrinol_lt:
INSERT INTO loottable(name) VALUES('overthere_klok_grshai'); # :overthere_klok_grshai_lt:
INSERT INTO loottable(name) VALUES('overthere_kuglaz_grot'); # :overthere_kuglaz_grot_lt:
INSERT INTO loottable(name) VALUES('overthere_kurron_ni'); # :overthere_kurron_ni_lt:
INSERT INTO loottable(name) VALUES('overthere_lissa_tborn'); # :overthere_lissa_tborn_lt:
INSERT INTO loottable(name) VALUES('overthere_modani_quloni'); # :overthere_modani_quloni_lt:
INSERT INTO loottable(name) VALUES('overthere_nekexin_virulence'); # :overthere_nekexin_virulence_lt:
INSERT INTO loottable(name) VALUES('overthere_osvima_kmatim'); # :overthere_osvima_kmatim_lt:
INSERT INTO loottable(name) VALUES('overthere_pungub_brawlum'); # :overthere_pungub_brawlum_lt:
INSERT INTO loottable(name) VALUES('overthere_sabretooth_tiger'); # :overthere_sabretooth_tiger_lt:
INSERT INTO loottable(name) VALUES('overthere_sabretooth_tigress'); # :overthere_sabretooth_tigress_lt:
INSERT INTO loottable(name) VALUES('overthere_scorpikis_guardian'); # :overthere_scorpikis_guardian_lt:
INSERT INTO loottable(name) VALUES('overthere_siladdarae_nriese'); # :overthere_siladdarae_nriese_lt:
INSERT INTO loottable(name) VALUES('overthere_slicia_jsinge'); # :overthere_slicia_jsinge_lt:
INSERT INTO loottable(name) VALUES('overthere_soulbinder_kardin'); # :overthere_soulbinder_kardin_lt:
INSERT INTO loottable(name) VALUES('overthere_stishovite'); # :overthere_stishovite_lt:
INSERT INTO loottable(name) VALUES('overthere_tektite'); # :overthere_tektite_lt:
INSERT INTO loottable(name) VALUES('overthere_the_sounds'); # :overthere_the_sounds_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_banker_assistant'); # :overthere_tin_banker_assistant_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_banker_i'); # :overthere_tin_banker_i_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_banker_ii'); # :overthere_tin_banker_ii_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_i'); # :overthere_tin_merchant_i_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_ii'); # :overthere_tin_merchant_ii_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_iii'); # :overthere_tin_merchant_iii_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_iv'); # :overthere_tin_merchant_iv_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_ix'); # :overthere_tin_merchant_ix_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_v'); # :overthere_tin_merchant_v_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_vi'); # :overthere_tin_merchant_vi_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_vii'); # :overthere_tin_merchant_vii_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_viii'); # :overthere_tin_merchant_viii_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_x'); # :overthere_tin_merchant_x_lt:
INSERT INTO loottable(name) VALUES('overthere_tin_merchant_xi'); # :overthere_tin_merchant_xi_lt:
INSERT INTO loottable(name) VALUES('overthere_tourmaline'); # :overthere_tourmaline_lt:
INSERT INTO loottable(name) VALUES('overthere_tyrin_flinz'); # :overthere_tyrin_flinz_lt:
INSERT INTO loottable(name) VALUES('overthere_uggrig_skullchomper'); # :overthere_uggrig_skullchomper_lt:
INSERT INTO loottable(name) VALUES('overthere_utandar_rizndown'); # :overthere_utandar_rizndown_lt:
INSERT INTO loottable(name) VALUES('overthere_vaean_the_night'); # :overthere_vaean_the_night_lt:
INSERT INTO loottable(name) VALUES('overthere_varg_stonebelly'); # :overthere_varg_stonebelly_lt:
INSERT INTO loottable(name) VALUES('overthere_vaxxim_tquoren'); # :overthere_vaxxim_tquoren_lt:
INSERT INTO loottable(name) VALUES('overthere_vizra_lnizlon'); # :overthere_vizra_lnizlon_lt:
INSERT INTO loottable(name) VALUES('overthere_xlixinar_arcut'); # :overthere_xlixinar_arcut_lt:
INSERT INTO loottable(name) VALUES('overthere_zorash'); # :overthere_zorash_lt:
