INSERT INTO loottable(name) VALUES('skyfire_an_ancient_wurm'); # :skyfire_an_ancient_wurm_lt:
INSERT INTO loottable(name) VALUES('skyfire_dragon_trigger'); # :skyfire_dragon_trigger_lt:
INSERT INTO loottable(name) VALUES('skyfire_obsidian_wyvern'); # :skyfire_obsidian_wyvern_lt:
INSERT INTO loottable(name) VALUES('skyfire_rithnok_the_tormented'); # :skyfire_rithnok_the_tormented_lt:
INSERT INTO loottable(name) VALUES('skyfire_suled_dars_shade'); # :skyfire_suled_dars_shade_lt:
INSERT INTO loottable(name) VALUES('skyfire_an_elder_wyvern'); # :skyfire_an_elder_wyvern_lt:
INSERT INTO loottable(name) VALUES('skyfire_an_old_wurm'); # :skyfire_an_old_wurm_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_bottomless_devourer'); # :skyfire_a_bottomless_devourer_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_bottomless_feaster'); # :skyfire_a_bottomless_feaster_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_bottomless_gnawer'); # :skyfire_a_bottomless_gnawer_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_chromadrac'); # :skyfire_a_chromadrac_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_guardian_wurm'); # :skyfire_a_guardian_wurm_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_lava_walker'); # :skyfire_a_lava_walker_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_mature_chromadrac'); # :skyfire_a_mature_chromadrac_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_mature_wurm'); # :skyfire_a_mature_wurm_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_mature_wyvern'); # :skyfire_a_mature_wyvern_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_shadow_drake'); # :skyfire_a_shadow_drake_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_skyash_drake'); # :skyfire_a_skyash_drake_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_skycinder_drake'); # :skyfire_a_skycinder_drake_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_skyfire_drake'); # :skyfire_a_skyfire_drake_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_soul_devourer'); # :skyfire_a_soul_devourer_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_wandering_wurm'); # :skyfire_a_wandering_wurm_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_wurm'); # :skyfire_a_wurm_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_wurm_spirit'); # :skyfire_a_wurm_spirit_lt:
INSERT INTO loottable(name) VALUES('skyfire_a_wyvern'); # :skyfire_a_wyvern_lt:
INSERT INTO loottable(name) VALUES('skyfire_black_scar'); # :skyfire_black_scar_lt:
INSERT INTO loottable(name) VALUES('skyfire_dry_sapara'); # :skyfire_dry_sapara_lt:
INSERT INTO loottable(name) VALUES('skyfire_eldrig_the_old'); # :skyfire_eldrig_the_old_lt:
INSERT INTO loottable(name) VALUES('skyfire_enrid_ebonclaw'); # :skyfire_enrid_ebonclaw_lt:
INSERT INTO loottable(name) VALUES('skyfire_faerie_of_dismay'); # :skyfire_faerie_of_dismay_lt:
INSERT INTO loottable(name) VALUES('skyfire_felia_goldenwing'); # :skyfire_felia_goldenwing_lt:
INSERT INTO loottable(name) VALUES('skyfire_guardian_of_felia'); # :skyfire_guardian_of_felia_lt:
INSERT INTO loottable(name) VALUES('skyfire_jennus_lyklobar'); # :skyfire_jennus_lyklobar_lt:
INSERT INTO loottable(name) VALUES('skyfire_servant_of_the_peak'); # :skyfire_servant_of_the_peak_lt:
INSERT INTO loottable(name) VALUES('skyfire_talendor'); # :skyfire_talendor_lt:
INSERT INTO loottable(name) VALUES('skyfire_the_fabled_black_scar'); # :skyfire_the_fabled_black_scar_lt:
INSERT INTO loottable(name) VALUES('skyfire_warder_cecilia'); # :skyfire_warder_cecilia_lt:
INSERT INTO loottable(name) VALUES('skyfire_zordakalicus_ragefire'); # :skyfire_zordakalicus_ragefire_lt:
INSERT INTO loottable(name) VALUES('skyfire_zordak_ragefire'); # :skyfire_zordak_ragefire_lt:
INSERT INTO loottable(name) VALUES('skyfire__a_lava_walker'); # :skyfire__a_lava_walker_lt:
