UPDATE npc_types SET loottable_id = :swampofnohope_a_swamp_dragon_lt: WHERE id in (83249); # #a_swamp_dragon 68
UPDATE npc_types SET loottable_id = :swampofnohope_an_iksar_brigand_lt: WHERE id in (83131, 83153, 83198); # an_Iksar_brigand 13
UPDATE npc_types SET loottable_id = :swampofnohope_an_iksar_footpad_lt: WHERE id in (83142, 83143); # an_Iksar_footpad 6
UPDATE npc_types SET loottable_id = :swampofnohope_an_iksar_manslayer_lt: WHERE id in (83108, 83109); # an_Iksar_manslayer 17
UPDATE npc_types SET loottable_id = :swampofnohope_an_iksar_marauder_lt: WHERE id in (83112, 83128, 83190); # an_Iksar_marauder 16
UPDATE npc_types SET loottable_id = :swampofnohope_an_insatiable_devourer_lt: WHERE id in (83078, 83081, 83082, 83089); # an_insatiable_devourer 25
UPDATE npc_types SET loottable_id = :swampofnohope_an_insatiable_gnawer_lt: WHERE id in (83041, 83103); # an_insatiable_gnawer 18
UPDATE npc_types SET loottable_id = :swampofnohope_an_insatiable_nibbler_lt: WHERE id in (83042, 83045, 83115); # an_insatiable_nibbler 14
UPDATE npc_types SET loottable_id = :swampofnohope_a_black_ravenger_lt: WHERE id in (83154); # A_black_ravenger 55
UPDATE npc_types SET loottable_id = :swampofnohope_a_bloodvein_mosquito_lt: WHERE id in (83117, 83120, 83126); # a_bloodvein_mosquito 13
UPDATE npc_types SET loottable_id = :swampofnohope_a_dancing_flame_lt: WHERE id in (83247); # a_dancing_flame 5
UPDATE npc_types SET loottable_id = :swampofnohope_a_dire_leech_lt: WHERE id in (83248); # a_dire_leech 65
UPDATE npc_types SET loottable_id = :swampofnohope_a_froglok_bounder_lt: WHERE id in (83032, 83137, 83138); # a_froglok_bounder 8
UPDATE npc_types SET loottable_id = :swampofnohope_a_froglok_escort_lt: WHERE id in (83243); # a_froglok_escort 4
UPDATE npc_types SET loottable_id = :swampofnohope_a_froglok_fisher_lt: WHERE id in (83015, 83025, 83048); # a_froglok_fisher 5
UPDATE npc_types SET loottable_id = :swampofnohope_a_froglok_gaz_knight_lt: WHERE id in (83200, 83060); # a_froglok_gaz_knight 17
UPDATE npc_types SET loottable_id = :swampofnohope_a_froglok_outlander_lt: WHERE id in (83208, 83051, 83170); # a_froglok_outlander 19
UPDATE npc_types SET loottable_id = :swampofnohope_a_froglok_repairer_lt: WHERE id in (83011, 83147); # a_froglok_repairer 20
UPDATE npc_types SET loottable_id = :swampofnohope_a_froglok_skipper_lt: WHERE id in (83016, 83036, 83053); # a_froglok_skipper 4
UPDATE npc_types SET loottable_id = :swampofnohope_a_froglok_ton_shaman_lt: WHERE id in (83171); # a_froglok_ton_shaman 18
UPDATE npc_types SET loottable_id = :swampofnohope_a_froglok_ton_warrior_lt: WHERE id in (83210); # a_froglok_ton_warrior 22
UPDATE npc_types SET loottable_id = :swampofnohope_a_giant_marsh_leech_lt: WHERE id in (83028, 83057, 83140); # a_giant_marsh_leech 9
UPDATE npc_types SET loottable_id = :swampofnohope_a_giant_mire_leech_lt: WHERE id in (83125, 83129); # a_giant_mire_leech 15
UPDATE npc_types SET loottable_id = :swampofnohope_a_giant_morass_leech_lt: WHERE id in (83096); # a_giant_morass_leech 22
UPDATE npc_types SET loottable_id = :swampofnohope_a_giant_mosquito_lt: WHERE id in (83133, 83136, 83141); # a_giant_mosquito 8
UPDATE npc_types SET loottable_id = :swampofnohope_a_giant_swamp_leech_lt: WHERE id in (83017, 83029, 83040); # a_giant_swamp_leech 3
UPDATE npc_types SET loottable_id = :swampofnohope_a_huge_lt: WHERE id in (83230); # A_huge 1
UPDATE npc_types SET loottable_id = :swampofnohope_a_large_mosquito_lt: WHERE id in (83050); # a_large_mosquito 3
UPDATE npc_types SET loottable_id = :swampofnohope_a_legendary_froglok_ghoul_lt: WHERE id in (83246); # A_Legendary_Froglok_Ghoul 72
UPDATE npc_types SET loottable_id = :swampofnohope_a_marsh_leech_lt: WHERE id in (83039, 83135); # a_marsh_leech 6
UPDATE npc_types SET loottable_id = :swampofnohope_a_mire_leech_lt: WHERE id in (83021, 83034, 83116); # a_mire_leech 11
UPDATE npc_types SET loottable_id = :swampofnohope_a_morass_leech_lt: WHERE id in (83019, 83022, 83035); # a_morass_leech 18
UPDATE npc_types SET loottable_id = :swampofnohope_a_mosquito_lt: WHERE id in (83018); # a_mosquito 1
UPDATE npc_types SET loottable_id = :swampofnohope_a_scourgewing_mosquito_lt: WHERE id in (83080, 83086); # a_scourgewing_mosquito 22
UPDATE npc_types SET loottable_id = :swampofnohope_a_skeleton_lt: WHERE id in (83212, 83037, 83192); # a_skeleton 5
UPDATE npc_types SET loottable_id = :swampofnohope_a_swamp_leech_lt: WHERE id in (83000); # a_swamp_leech 1
UPDATE npc_types SET loottable_id = :swampofnohope_blackbone_lt: WHERE id in (83222); # Blackbone 24
UPDATE npc_types SET loottable_id = :swampofnohope_blackwing_lt: WHERE id in (83235); # Blackwing 26
UPDATE npc_types SET loottable_id = :swampofnohope_bloodgorge_lt: WHERE id in (83193); # Bloodgorge 25
UPDATE npc_types SET loottable_id = :swampofnohope_bloodvein_lt: WHERE id in (83229); # Bloodvein 25
UPDATE npc_types SET loottable_id = :swampofnohope_bulsgor_lt: WHERE id in (83238); # Bulsgor 26
UPDATE npc_types SET loottable_id = :swampofnohope_captain_nedar_lt: WHERE id in (83214); # Captain_Nedar 50
UPDATE npc_types SET loottable_id = :swampofnohope_charbone_skeleton_lt: WHERE id in (83202, 83163); # charbone_skeleton 26
UPDATE npc_types SET loottable_id = :swampofnohope_crusader_litia_lt: WHERE id in (83059); # Crusader_Litia 50
UPDATE npc_types SET loottable_id = :swampofnohope_crusader_savot_lt: WHERE id in (83058); # Crusader_Savot 50
UPDATE npc_types SET loottable_id = :swampofnohope_deadeye_lt: WHERE id in (83223); # Deadeye 26
UPDATE npc_types SET loottable_id = :swampofnohope_decaying_skeleton_lt: WHERE id in (83020); # decaying_skeleton 1
UPDATE npc_types SET loottable_id = :swampofnohope_dreesix_ghoultongue_lt: WHERE id in (83217); # Dreesix_Ghoultongue 25
UPDATE npc_types SET loottable_id = :swampofnohope_dugroz_lt: WHERE id in (83149); # Dugroz 30
UPDATE npc_types SET loottable_id = :swampofnohope_ebon_bloodrose_lt: WHERE id in (83195); # Ebon_Bloodrose 23
UPDATE npc_types SET loottable_id = :swampofnohope_escaped_froglok_slave_lt: WHERE id in (83241, 83242); # escaped_froglok_slave 4
UPDATE npc_types SET loottable_id = :swampofnohope_fakraa_the_forsaken_lt: WHERE id in (83075); # Fakraa_the_Forsaken 25
UPDATE npc_types SET loottable_id = :swampofnohope_fangor_lt: WHERE id in (83239); # Fangor 25
UPDATE npc_types SET loottable_id = :swampofnohope_flighty_violet_wisp_lt: WHERE id in (83245); # Flighty_Violet_Wisp 70
UPDATE npc_types SET loottable_id = :swampofnohope_footman_moglok_lt: WHERE id in (83068, 83172); # Footman_Moglok 12
UPDATE npc_types SET loottable_id = :swampofnohope_frayk_lt: WHERE id in (83236); # Frayk 25
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_berserker_lt: WHERE id in (83216); # Froglok_berserker 25
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_escort_lt: WHERE id in (83204); # Froglok_Escort 5
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_gaz_knight_lt: WHERE id in (83008, 83009, 83079, 83100, 83146); # froglok_gaz_knight 20
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_gaz_shaman_lt: WHERE id in (83001, 83004, 83107); # froglok_gaz_shaman 15
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_gaz_warder_lt: WHERE id in (83185); # froglok_gaz_warder 19
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_gaz_warrior_lt: WHERE id in (83002, 83007, 83054); # froglok_gaz_warrior 17
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_impaler_lt: WHERE id in (83224); # Froglok_Impaler 25
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_krup_guard_lt: WHERE id in (83213); # froglok_krup_guard 22
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_raider_lt: WHERE id in (83046, 83055, 83056); # froglok_raider 11
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_shin_shaman_lt: WHERE id in (83005, 83094, 83144, 83145, 83148); # froglok_shin_shaman 21
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_ton_shaman_lt: WHERE id in (83101, 83105, 83106); # froglok_ton_shaman 17
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_ton_warrior_lt: WHERE id in (83006, 83044, 83095, 83183); # froglok_ton_warrior 24
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_tuk_knight_lt: WHERE id in (83003, 83010, 83104); # froglok_tuk_knight 15
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_tuk_shaman_lt: WHERE id in (83121); # froglok_tuk_shaman 11
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_tuk_warder_lt: WHERE id in (83012, 83013, 83184); # froglok_tuk_warder 15
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_tuk_warrior_lt: WHERE id in (83043, 83124); # froglok_tuk_warrior 12
UPDATE npc_types SET loottable_id = :swampofnohope_froglok_vis_shaman_lt: WHERE id in (83098); # froglok_vis_shaman 23
UPDATE npc_types SET loottable_id = :swampofnohope_giant_bloodvein_mosquito_lt: WHERE id in (83205); # giant_bloodvein_mosquito 22
UPDATE npc_types SET loottable_id = :swampofnohope_greater_scalebone_lt: WHERE id in (83119, 83152, 83186); # greater_scalebone 15
UPDATE npc_types SET loottable_id = :swampofnohope_greater_skeleton_lt: WHERE id in (83123, 83127, 83130); # greater_skeleton 13
UPDATE npc_types SET loottable_id = :swampofnohope_grik_the_exile_lt: WHERE id in (83221); # Grik_the_Exile 45
UPDATE npc_types SET loottable_id = :swampofnohope_grik_the_exiled_lt: WHERE id in (83156); # Grik_the_Exiled 45
UPDATE npc_types SET loottable_id = :swampofnohope_grimewurm_lt: WHERE id in (83206); # Grimewurm 22
UPDATE npc_types SET loottable_id = :swampofnohope_grizshnok_lt: WHERE id in (83233); # Grizshnok 22
UPDATE npc_types SET loottable_id = :swampofnohope_heartblood_fern_lt: WHERE id in (83220); # Heartblood_Fern 24
UPDATE npc_types SET loottable_id = :swampofnohope_icebone_skeleton_lt: WHERE id in (83076, 83090, 83151); # icebone_skeleton 24
UPDATE npc_types SET loottable_id = :swampofnohope_ichorspike_lt: WHERE id in (83228); # Ichorspike 23
UPDATE npc_types SET loottable_id = :swampofnohope_iksar_exile_lt: WHERE id in (83077); # Iksar_exile 23
UPDATE npc_types SET loottable_id = :swampofnohope_iksar_pariah_lt: WHERE id in (83087, 83092, 83097, 83176); # Iksar_pariah 23
UPDATE npc_types SET loottable_id = :swampofnohope_kaggy_krup_lt: WHERE id in (83073); # Kaggy_Krup 55
UPDATE npc_types SET loottable_id = :swampofnohope_klok_bygle_lt: WHERE id in (83069); # Klok_Bygle 30
UPDATE npc_types SET loottable_id = :swampofnohope_klok_gokrok_lt: WHERE id in (83070); # Klok_Gokrok 30
UPDATE npc_types SET loottable_id = :swampofnohope_klok_migo_lt: WHERE id in (83071); # Klok_Migo 30
UPDATE npc_types SET loottable_id = :swampofnohope_klok_roshin_lt: WHERE id in (83072); # Klok_Roshin 30
UPDATE npc_types SET loottable_id = :swampofnohope_large_bloodvein_mosquito_lt: WHERE id in (83102); # large_bloodvein_mosquito 15
UPDATE npc_types SET loottable_id = :swampofnohope_lesser_charbone_skeleton_lt: WHERE id in (83027, 83113); # lesser_charbone_skeleton 19
UPDATE npc_types SET loottable_id = :swampofnohope_lesser_icebone_skeleton_lt: WHERE id in (83038, 83114); # lesser_icebone_skeleton 18
UPDATE npc_types SET loottable_id = :swampofnohope_man_eating_creeper_lt: WHERE id in (83099, 83111); # man_eating_creeper 14
UPDATE npc_types SET loottable_id = :swampofnohope_man_eating_fern_lt: WHERE id in (83026, 83118, 83122); # man_eating_fern 10
UPDATE npc_types SET loottable_id = :swampofnohope_man_eating_plant_lt: WHERE id in (83024, 83110); # man_eating_plant 20
UPDATE npc_types SET loottable_id = :swampofnohope_man_eating_shrub_lt: WHERE id in (83049, 83132); # man_eating_shrub 6
UPDATE npc_types SET loottable_id = :swampofnohope_man_eating_vine_lt: WHERE id in (83047, 83084, 83088); # man_eating_vine 25
UPDATE npc_types SET loottable_id = :swampofnohope_mystic_dovan_lt: WHERE id in (83014); # Mystic_Dovan 35
UPDATE npc_types SET loottable_id = :swampofnohope_old_hangman_lt: WHERE id in (83240); # Old_Hangman 22
UPDATE npc_types SET loottable_id = :swampofnohope_scalebone_skeleton_lt: WHERE id in (83023, 83134, 83139); # scalebone_skeleton 9
UPDATE npc_types SET loottable_id = :swampofnohope_scout_eyru_lt: WHERE id in (83231); # Scout_Eyru 15
UPDATE npc_types SET loottable_id = :swampofnohope_skeleton_lt: WHERE id in (83031, 83033, 83052); # skeleton 4
UPDATE npc_types SET loottable_id = :swampofnohope_skurza_slicekutt_lt: WHERE id in (83250); # Skurza_Slicekutt 66
UPDATE npc_types SET loottable_id = :swampofnohope_soblohg_lt: WHERE id in (83226); # Soblohg 25
UPDATE npc_types SET loottable_id = :swampofnohope_ssessthrass_lt: WHERE id in (83074); # Ssessthrass 55
UPDATE npc_types SET loottable_id = :swampofnohope_the_spirit_of_sorrow_lt: WHERE id in (83244); # The_Spirit_of_Sorrow 55
UPDATE npc_types SET loottable_id = :swampofnohope_torgis_lt: WHERE id in (83227); # Torgis 24
UPDATE npc_types SET loottable_id = :swampofnohope_trooper_fodcod_lt: WHERE id in (83061); # Trooper_Fodcod 50
UPDATE npc_types SET loottable_id = :swampofnohope_trooper_harkee_lt: WHERE id in (83065); # Trooper_Harkee 50
UPDATE npc_types SET loottable_id = :swampofnohope_trooper_inkin_lt: WHERE id in (83063); # Trooper_Inkin 50
UPDATE npc_types SET loottable_id = :swampofnohope_trooper_keat_lt: WHERE id in (83064); # Trooper_Keat 50
UPDATE npc_types SET loottable_id = :swampofnohope_trooper_lorgen_lt: WHERE id in (83066); # Trooper_Lorgen 50
UPDATE npc_types SET loottable_id = :swampofnohope_trooper_nilzik_lt: WHERE id in (83062); # Trooper_Nilzik 50
UPDATE npc_types SET loottable_id = :swampofnohope_two_tails_lt: WHERE id in (83232); # Two_Tails 25
UPDATE npc_types SET loottable_id = :swampofnohope_ulump_pujluk_lt: WHERE id in (83030); # Ulump_Pujluk 55
UPDATE npc_types SET loottable_id = :swampofnohope_venomous_lamprey_lt: WHERE id in (83083, 83093); # venomous_lamprey 26
UPDATE npc_types SET loottable_id = :swampofnohope_venomwing_lt: WHERE id in (83219); # Venomwing 25
UPDATE npc_types SET loottable_id = :swampofnohope_warlord_hikyg_lt: WHERE id in (83067); # Warlord_Hikyg 51
UPDATE npc_types SET loottable_id = :swampofnohope_war_boned_skeleton_lt: WHERE id in (83085, 83091, 83150); # war_boned_skeleton 21
UPDATE npc_types SET loottable_id = :swampofnohope_weeping_mantrap_lt: WHERE id in (83237); # Weeping_Mantrap 25
UPDATE npc_types SET loottable_id = :swampofnohope___lt: WHERE id in (83155); # _ 1
