INSERT INTO loottable(name) VALUES('swampofnohope_a_swamp_dragon'); # :swampofnohope_a_swamp_dragon_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_an_iksar_brigand'); # :swampofnohope_an_iksar_brigand_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_an_iksar_footpad'); # :swampofnohope_an_iksar_footpad_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_an_iksar_manslayer'); # :swampofnohope_an_iksar_manslayer_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_an_iksar_marauder'); # :swampofnohope_an_iksar_marauder_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_an_insatiable_devourer'); # :swampofnohope_an_insatiable_devourer_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_an_insatiable_gnawer'); # :swampofnohope_an_insatiable_gnawer_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_an_insatiable_nibbler'); # :swampofnohope_an_insatiable_nibbler_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_black_ravenger'); # :swampofnohope_a_black_ravenger_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_bloodvein_mosquito'); # :swampofnohope_a_bloodvein_mosquito_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_dancing_flame'); # :swampofnohope_a_dancing_flame_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_dire_leech'); # :swampofnohope_a_dire_leech_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_froglok_bounder'); # :swampofnohope_a_froglok_bounder_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_froglok_escort'); # :swampofnohope_a_froglok_escort_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_froglok_fisher'); # :swampofnohope_a_froglok_fisher_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_froglok_gaz_knight'); # :swampofnohope_a_froglok_gaz_knight_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_froglok_outlander'); # :swampofnohope_a_froglok_outlander_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_froglok_repairer'); # :swampofnohope_a_froglok_repairer_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_froglok_skipper'); # :swampofnohope_a_froglok_skipper_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_froglok_ton_shaman'); # :swampofnohope_a_froglok_ton_shaman_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_froglok_ton_warrior'); # :swampofnohope_a_froglok_ton_warrior_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_giant_marsh_leech'); # :swampofnohope_a_giant_marsh_leech_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_giant_mire_leech'); # :swampofnohope_a_giant_mire_leech_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_giant_morass_leech'); # :swampofnohope_a_giant_morass_leech_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_giant_mosquito'); # :swampofnohope_a_giant_mosquito_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_giant_swamp_leech'); # :swampofnohope_a_giant_swamp_leech_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_huge'); # :swampofnohope_a_huge_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_large_mosquito'); # :swampofnohope_a_large_mosquito_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_legendary_froglok_ghoul'); # :swampofnohope_a_legendary_froglok_ghoul_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_marsh_leech'); # :swampofnohope_a_marsh_leech_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_mire_leech'); # :swampofnohope_a_mire_leech_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_morass_leech'); # :swampofnohope_a_morass_leech_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_mosquito'); # :swampofnohope_a_mosquito_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_scourgewing_mosquito'); # :swampofnohope_a_scourgewing_mosquito_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_skeleton'); # :swampofnohope_a_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_a_swamp_leech'); # :swampofnohope_a_swamp_leech_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_blackbone'); # :swampofnohope_blackbone_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_blackwing'); # :swampofnohope_blackwing_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_bloodgorge'); # :swampofnohope_bloodgorge_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_bloodvein'); # :swampofnohope_bloodvein_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_bulsgor'); # :swampofnohope_bulsgor_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_captain_nedar'); # :swampofnohope_captain_nedar_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_charbone_skeleton'); # :swampofnohope_charbone_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_crusader_litia'); # :swampofnohope_crusader_litia_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_crusader_savot'); # :swampofnohope_crusader_savot_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_deadeye'); # :swampofnohope_deadeye_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_decaying_skeleton'); # :swampofnohope_decaying_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_dreesix_ghoultongue'); # :swampofnohope_dreesix_ghoultongue_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_dugroz'); # :swampofnohope_dugroz_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_ebon_bloodrose'); # :swampofnohope_ebon_bloodrose_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_escaped_froglok_slave'); # :swampofnohope_escaped_froglok_slave_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_fakraa_the_forsaken'); # :swampofnohope_fakraa_the_forsaken_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_fangor'); # :swampofnohope_fangor_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_flighty_violet_wisp'); # :swampofnohope_flighty_violet_wisp_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_footman_moglok'); # :swampofnohope_footman_moglok_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_frayk'); # :swampofnohope_frayk_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_berserker'); # :swampofnohope_froglok_berserker_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_escort'); # :swampofnohope_froglok_escort_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_gaz_knight'); # :swampofnohope_froglok_gaz_knight_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_gaz_shaman'); # :swampofnohope_froglok_gaz_shaman_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_gaz_warder'); # :swampofnohope_froglok_gaz_warder_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_gaz_warrior'); # :swampofnohope_froglok_gaz_warrior_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_impaler'); # :swampofnohope_froglok_impaler_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_krup_guard'); # :swampofnohope_froglok_krup_guard_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_raider'); # :swampofnohope_froglok_raider_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_shin_shaman'); # :swampofnohope_froglok_shin_shaman_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_ton_shaman'); # :swampofnohope_froglok_ton_shaman_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_ton_warrior'); # :swampofnohope_froglok_ton_warrior_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_tuk_knight'); # :swampofnohope_froglok_tuk_knight_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_tuk_shaman'); # :swampofnohope_froglok_tuk_shaman_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_tuk_warder'); # :swampofnohope_froglok_tuk_warder_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_tuk_warrior'); # :swampofnohope_froglok_tuk_warrior_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_froglok_vis_shaman'); # :swampofnohope_froglok_vis_shaman_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_giant_bloodvein_mosquito'); # :swampofnohope_giant_bloodvein_mosquito_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_greater_scalebone'); # :swampofnohope_greater_scalebone_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_greater_skeleton'); # :swampofnohope_greater_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_grik_the_exile'); # :swampofnohope_grik_the_exile_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_grik_the_exiled'); # :swampofnohope_grik_the_exiled_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_grimewurm'); # :swampofnohope_grimewurm_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_grizshnok'); # :swampofnohope_grizshnok_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_heartblood_fern'); # :swampofnohope_heartblood_fern_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_icebone_skeleton'); # :swampofnohope_icebone_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_ichorspike'); # :swampofnohope_ichorspike_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_iksar_exile'); # :swampofnohope_iksar_exile_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_iksar_pariah'); # :swampofnohope_iksar_pariah_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_kaggy_krup'); # :swampofnohope_kaggy_krup_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_klok_bygle'); # :swampofnohope_klok_bygle_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_klok_gokrok'); # :swampofnohope_klok_gokrok_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_klok_migo'); # :swampofnohope_klok_migo_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_klok_roshin'); # :swampofnohope_klok_roshin_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_large_bloodvein_mosquito'); # :swampofnohope_large_bloodvein_mosquito_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_lesser_charbone_skeleton'); # :swampofnohope_lesser_charbone_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_lesser_icebone_skeleton'); # :swampofnohope_lesser_icebone_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_man_eating_creeper'); # :swampofnohope_man_eating_creeper_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_man_eating_fern'); # :swampofnohope_man_eating_fern_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_man_eating_plant'); # :swampofnohope_man_eating_plant_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_man_eating_shrub'); # :swampofnohope_man_eating_shrub_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_man_eating_vine'); # :swampofnohope_man_eating_vine_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_mystic_dovan'); # :swampofnohope_mystic_dovan_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_old_hangman'); # :swampofnohope_old_hangman_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_scalebone_skeleton'); # :swampofnohope_scalebone_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_scout_eyru'); # :swampofnohope_scout_eyru_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_skeleton'); # :swampofnohope_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_skurza_slicekutt'); # :swampofnohope_skurza_slicekutt_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_soblohg'); # :swampofnohope_soblohg_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_ssessthrass'); # :swampofnohope_ssessthrass_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_the_spirit_of_sorrow'); # :swampofnohope_the_spirit_of_sorrow_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_torgis'); # :swampofnohope_torgis_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_trooper_fodcod'); # :swampofnohope_trooper_fodcod_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_trooper_harkee'); # :swampofnohope_trooper_harkee_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_trooper_inkin'); # :swampofnohope_trooper_inkin_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_trooper_keat'); # :swampofnohope_trooper_keat_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_trooper_lorgen'); # :swampofnohope_trooper_lorgen_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_trooper_nilzik'); # :swampofnohope_trooper_nilzik_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_two_tails'); # :swampofnohope_two_tails_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_ulump_pujluk'); # :swampofnohope_ulump_pujluk_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_venomous_lamprey'); # :swampofnohope_venomous_lamprey_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_venomwing'); # :swampofnohope_venomwing_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_warlord_hikyg'); # :swampofnohope_warlord_hikyg_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_war_boned_skeleton'); # :swampofnohope_war_boned_skeleton_lt:
INSERT INTO loottable(name) VALUES('swampofnohope_weeping_mantrap'); # :swampofnohope_weeping_mantrap_lt:
INSERT INTO loottable(name) VALUES('swampofnohope__'); # :swampofnohope___lt:
