UPDATE npc_types SET loottable_id = :timorous_a_spiroc_roostmaster_lt: WHERE id in (96353); # #a_spiroc_roostmaster 41
UPDATE npc_types SET loottable_id = :timorous_barrel_barge_lt: WHERE id in (96316); # #Barrel_Barge 50
UPDATE npc_types SET loottable_id = :timorous_faydedar_lt: WHERE id in (96073); # #Faydedar 55
UPDATE npc_types SET loottable_id = :timorous_gefaari_drokaz_lt: WHERE id in (96368); # #Gefaari_Drokaz 80
UPDATE npc_types SET loottable_id = :timorous_maidens_voyage_lt: WHERE id in (96301); # #Maidens_Voyage 50
UPDATE npc_types SET loottable_id = :timorous_olok_oneeye_lt: WHERE id in (96354); # #Olok_One`eye 53
UPDATE npc_types SET loottable_id = :timorous_translocator_deela_lt: WHERE id in (96071); # #Translocator_Deela 1
UPDATE npc_types SET loottable_id = :timorous_translocator_jorbin_lt: WHERE id in (96070); # #Translocator_Jorbin 1
UPDATE npc_types SET loottable_id = :timorous_zordaks_minion_lt: WHERE id in (96369); # #Zordak`s_Minion 70
UPDATE npc_types SET loottable_id = :timorous___lt: WHERE id in (96300); # #_# 60
UPDATE npc_types SET loottable_id = :timorous___4_lt: WHERE id in (96314); # #_#_4 60
UPDATE npc_types SET loottable_id = :timorous__8__lt: WHERE id in (96315); # #_8_ 60
UPDATE npc_types SET loottable_id = :timorous_alrik_farsight_lt: WHERE id in (96032); # Alrik_Farsight 50
UPDATE npc_types SET loottable_id = :timorous_an_elven_overseer_lt: WHERE id in (96068); # an_Elven_Overseer 24
UPDATE npc_types SET loottable_id = :timorous_an_elven_ranger_lt: WHERE id in (96037, 96064); # an_elven_ranger 17
UPDATE npc_types SET loottable_id = :timorous_an_elven_scout_lt: WHERE id in (96038, 96063, 96067); # an_elven_scout 15
UPDATE npc_types SET loottable_id = :timorous_an_elven_war_scout_lt: WHERE id in (96062, 96065); # an_elven_war_scout 21
UPDATE npc_types SET loottable_id = :timorous_an_iksar_master_lt: WHERE id in (96002); # an_Iksar_master 61
UPDATE npc_types SET loottable_id = :timorous_an_ogre_raider_lt: WHERE id in (96005, 96363, 96364, 96365, 96366); # an_Ogre_Raider 16
UPDATE npc_types SET loottable_id = :timorous_avatar_of_water_lt: WHERE id in (96086); # Avatar_of_Water 60
UPDATE npc_types SET loottable_id = :timorous_a_bandit_lt: WHERE id in (96048, 96049); # a_bandit 15
UPDATE npc_types SET loottable_id = :timorous_a_bandit_leader_lt: WHERE id in (96047); # a_bandit_leader 18
UPDATE npc_types SET loottable_id = :timorous_a_dancing_skeleton_lt: WHERE id in (96088); # a_dancing_skeleton 29
UPDATE npc_types SET loottable_id = :timorous_a_fallen_deckhand_lt: WHERE id in (96323); # a_fallen_deckhand 21
UPDATE npc_types SET loottable_id = :timorous_a_fallen_iksar_lt: WHERE id in (96050, 96051, 96052, 96053, 96054); # a_fallen_Iksar 13
UPDATE npc_types SET loottable_id = :timorous_a_golra_lt: WHERE id in (96023, 96024, 96025, 96027, 96029); # a_golra 27
UPDATE npc_types SET loottable_id = :timorous_a_gunthak_pirate_lt: WHERE id in (96355); # a_gunthak_pirate 49
UPDATE npc_types SET loottable_id = :timorous_a_gunthak_swabby_lt: WHERE id in (96356); # a_gunthak_swabby 48
UPDATE npc_types SET loottable_id = :timorous_a_hulking_golra_lt: WHERE id in (96026, 96028); # a_hulking_golra 34
UPDATE npc_types SET loottable_id = :timorous_a_pebble_lt: WHERE id in (96084); # a_pebble 1
UPDATE npc_types SET loottable_id = :timorous_a_raptor_lt: WHERE id in (96009, 96019, 96020, 96022); # a_Raptor 41
UPDATE npc_types SET loottable_id = :timorous_a_spiroc_harvester_lt: WHERE id in (96324); # a_Spiroc_Harvester 55
UPDATE npc_types SET loottable_id = :timorous_a_spiroc_lightbringer_lt: WHERE id in (96081); # a_Spiroc_Lightbringer 50
UPDATE npc_types SET loottable_id = :timorous_a_spiroc_lightfoot_lt: WHERE id in (96008, 96013, 96017); # a_Spiroc_Lightfoot 37
UPDATE npc_types SET loottable_id = :timorous_a_spiroc_proven_lt: WHERE id in (96011, 96014, 96016); # a_Spiroc_Proven 41
UPDATE npc_types SET loottable_id = :timorous_a_spiroc_warrior_lt: WHERE id in (96030, 96055); # a_Spiroc_Warrior 43
UPDATE npc_types SET loottable_id = :timorous_a_spiroc_watcher_lt: WHERE id in (96007, 96012, 96015); # a_Spiroc_Watcher 38
UPDATE npc_types SET loottable_id = :timorous_a_streamer_lt: WHERE id in (96039); # a_streamer 14
UPDATE npc_types SET loottable_id = :timorous_a_streamer01_lt: WHERE id in (96040); # a_streamer01 13
UPDATE npc_types SET loottable_id = :timorous_a_streamer02_lt: WHERE id in (96041); # a_streamer02 10
UPDATE npc_types SET loottable_id = :timorous_a_streamer03_lt: WHERE id in (96042); # a_streamer03 13
UPDATE npc_types SET loottable_id = :timorous_a_streamer04_lt: WHERE id in (96043); # a_streamer04 11
UPDATE npc_types SET loottable_id = :timorous_a_streamer05_lt: WHERE id in (96044); # a_streamer05 10
UPDATE npc_types SET loottable_id = :timorous_a_streamer06_lt: WHERE id in (96045); # a_streamer06 12
UPDATE npc_types SET loottable_id = :timorous_a_streamer07_lt: WHERE id in (96046); # a_streamer07 14
UPDATE npc_types SET loottable_id = :timorous_a_vicious_raptor_lt: WHERE id in (96010, 96021); # a_Vicious_Raptor 45
UPDATE npc_types SET loottable_id = :timorous_bloated_belly_lt: WHERE id in (96317); # Bloated_Belly 50
UPDATE npc_types SET loottable_id = :timorous_cursed_traveler_lt: WHERE id in (96056); # Cursed_Traveler 1
UPDATE npc_types SET loottable_id = :timorous_dinus_lt: WHERE id in (96076); # Dinus 47
UPDATE npc_types SET loottable_id = :timorous_dolgin_codslayer_lt: WHERE id in (96018); # Dolgin_Codslayer 10
UPDATE npc_types SET loottable_id = :timorous_draz_nurakk_lt: WHERE id in (96321); # Draz_Nurakk 55
UPDATE npc_types SET loottable_id = :timorous_draz_nurakks_image_lt: WHERE id in (96322); # Draz_Nurakks_Image 55
UPDATE npc_types SET loottable_id = :timorous_drendico_metalbones_lt: WHERE id in (96034); # Drendico_Metalbones 56
UPDATE npc_types SET loottable_id = :timorous_farstara_dio_lt: WHERE id in (96357); # Farstara_Dio 50
UPDATE npc_types SET loottable_id = :timorous_faydedar_lt: WHERE id in (96089); # Faydedar 55
UPDATE npc_types SET loottable_id = :timorous_fire_gator_lt: WHERE id in (96057, 96058, 96059, 96060, 96061); # Fire_Gator 26
UPDATE npc_types SET loottable_id = :timorous_glairb_stonebelly_lt: WHERE id in (96079); # Glairb_Stonebelly 99
UPDATE npc_types SET loottable_id = :timorous_grandmaster_rinmark_lt: WHERE id in (96318); # Grandmaster_Rinmark 61
UPDATE npc_types SET loottable_id = :timorous_halara_lt: WHERE id in (96077); # Halara 40
UPDATE npc_types SET loottable_id = :timorous_island_shuttle_lt: WHERE id in (96075); # Island_Shuttle 50
UPDATE npc_types SET loottable_id = :timorous_izatri_lt: WHERE id in (96352); # Izatri 61
UPDATE npc_types SET loottable_id = :timorous_jhassad_oceanson_lt: WHERE id in (96074); # Jhassad_Oceanson 50
UPDATE npc_types SET loottable_id = :timorous_kellewin_stillwater_lt: WHERE id in (96358); # Kellewin_Stillwater 50
UPDATE npc_types SET loottable_id = :timorous_lheao_lt: WHERE id in (96001); # Lheao 50
UPDATE npc_types SET loottable_id = :timorous_master_rinmark_lt: WHERE id in (96319); # Master_Rinmark 50
UPDATE npc_types SET loottable_id = :timorous_micus_vloren_lt: WHERE id in (96069); # Micus_Vloren 35
UPDATE npc_types SET loottable_id = :timorous_natasha_whitewater_lt: WHERE id in (96080); # Natasha_Whitewater 40
UPDATE npc_types SET loottable_id = :timorous_oasis_lt: WHERE id in (96085); # Oasis 15
UPDATE npc_types SET loottable_id = :timorous_ogre_wise_one_lt: WHERE id in (96000, 96003); # Ogre_Wise_One 18
UPDATE npc_types SET loottable_id = :timorous_omat_vastsea_lt: WHERE id in (96033); # Omat_Vastsea 60
UPDATE npc_types SET loottable_id = :timorous_perican_fallhammer_lt: WHERE id in (96359); # Perican_Fallhammer 50
UPDATE npc_types SET loottable_id = :timorous_portik_grolam_lt: WHERE id in (96036); # Portik_Grolam 35
UPDATE npc_types SET loottable_id = :timorous_quest_master_deedil_lt: WHERE id in (96083); # Quest_Master_Deedil 60
UPDATE npc_types SET loottable_id = :timorous_raider_watchman_lt: WHERE id in (96006, 96031); # Raider_Watchman 19
UPDATE npc_types SET loottable_id = :timorous_rinmark_lt: WHERE id in (96320); # Rinmark 42
UPDATE npc_types SET loottable_id = :timorous_salco_dagor_lt: WHERE id in (96360); # Salco_Dagor 50
UPDATE npc_types SET loottable_id = :timorous_scout_sihmoj_lt: WHERE id in (96078); # Scout_Sihmoj 15
UPDATE npc_types SET loottable_id = :timorous_sellcondru_dusaan_lt: WHERE id in (96361); # Sellcondru_Dusaan 50
UPDATE npc_types SET loottable_id = :timorous_seloris_windweaver_lt: WHERE id in (96066); # Seloris_Windweaver 25
UPDATE npc_types SET loottable_id = :timorous_silithis_sisnta_lt: WHERE id in (96362); # Silithis_Sisnta 66
UPDATE npc_types SET loottable_id = :timorous_the_fabled_oowomp_lt: WHERE id in (96351); # The_Fabled_Oowomp 40
UPDATE npc_types SET loottable_id = :timorous_the_fabled_ugrak_da_raider_lt: WHERE id in (96350); # The_Fabled_Ugrak_da_Raider 30
UPDATE npc_types SET loottable_id = :timorous_the_great_oowomp_lt: WHERE id in (96004); # The_Great_Oowomp 34
UPDATE npc_types SET loottable_id = :timorous_thousands_of_lt: WHERE id in (96072); # Thousands_of 1
UPDATE npc_types SET loottable_id = :timorous_ugrak_da_raider_lt: WHERE id in (96087); # Ugrak_da_Raider 24
UPDATE npc_types SET loottable_id = :timorous_utte_the_virtuous_lt: WHERE id in (96367); # Utte_the_Virtuous 70
UPDATE npc_types SET loottable_id = :timorous_xiblin_fizzlebik_lt: WHERE id in (96035); # Xiblin_Fizzlebik 30
UPDATE npc_types SET loottable_id = :timorous__1_lt: WHERE id in (96302); # _1 60
UPDATE npc_types SET loottable_id = :timorous__10_lt: WHERE id in (96311); # _10 60
UPDATE npc_types SET loottable_id = :timorous__11_lt: WHERE id in (96312); # _11 60
UPDATE npc_types SET loottable_id = :timorous__12_lt: WHERE id in (96313); # _12 60
UPDATE npc_types SET loottable_id = :timorous__2_lt: WHERE id in (96303); # _2 60
UPDATE npc_types SET loottable_id = :timorous__3_lt: WHERE id in (96304); # _3 60
UPDATE npc_types SET loottable_id = :timorous__4_lt: WHERE id in (96305); # _4 60
UPDATE npc_types SET loottable_id = :timorous__5_lt: WHERE id in (96306); # _5 60
UPDATE npc_types SET loottable_id = :timorous__6_lt: WHERE id in (96307); # _6 60
UPDATE npc_types SET loottable_id = :timorous__7_lt: WHERE id in (96308); # _7 60
UPDATE npc_types SET loottable_id = :timorous__8_lt: WHERE id in (96309); # _8 60
UPDATE npc_types SET loottable_id = :timorous__9_lt: WHERE id in (96310); # _9 60
