INSERT INTO loottable(name) VALUES('timorous_a_spiroc_roostmaster'); # :timorous_a_spiroc_roostmaster_lt:
INSERT INTO loottable(name) VALUES('timorous_barrel_barge'); # :timorous_barrel_barge_lt:
INSERT INTO loottable(name) VALUES('timorous_faydedar'); # :timorous_faydedar_lt:
INSERT INTO loottable(name) VALUES('timorous_gefaari_drokaz'); # :timorous_gefaari_drokaz_lt:
INSERT INTO loottable(name) VALUES('timorous_maidens_voyage'); # :timorous_maidens_voyage_lt:
INSERT INTO loottable(name) VALUES('timorous_olok_oneeye'); # :timorous_olok_oneeye_lt:
INSERT INTO loottable(name) VALUES('timorous_translocator_deela'); # :timorous_translocator_deela_lt:
INSERT INTO loottable(name) VALUES('timorous_translocator_jorbin'); # :timorous_translocator_jorbin_lt:
INSERT INTO loottable(name) VALUES('timorous_zordaks_minion'); # :timorous_zordaks_minion_lt:
INSERT INTO loottable(name) VALUES('timorous__'); # :timorous___lt:
INSERT INTO loottable(name) VALUES('timorous___4'); # :timorous___4_lt:
INSERT INTO loottable(name) VALUES('timorous__8_'); # :timorous__8__lt:
INSERT INTO loottable(name) VALUES('timorous_alrik_farsight'); # :timorous_alrik_farsight_lt:
INSERT INTO loottable(name) VALUES('timorous_an_elven_overseer'); # :timorous_an_elven_overseer_lt:
INSERT INTO loottable(name) VALUES('timorous_an_elven_ranger'); # :timorous_an_elven_ranger_lt:
INSERT INTO loottable(name) VALUES('timorous_an_elven_scout'); # :timorous_an_elven_scout_lt:
INSERT INTO loottable(name) VALUES('timorous_an_elven_war_scout'); # :timorous_an_elven_war_scout_lt:
INSERT INTO loottable(name) VALUES('timorous_an_iksar_master'); # :timorous_an_iksar_master_lt:
INSERT INTO loottable(name) VALUES('timorous_an_ogre_raider'); # :timorous_an_ogre_raider_lt:
INSERT INTO loottable(name) VALUES('timorous_avatar_of_water'); # :timorous_avatar_of_water_lt:
INSERT INTO loottable(name) VALUES('timorous_a_bandit'); # :timorous_a_bandit_lt:
INSERT INTO loottable(name) VALUES('timorous_a_bandit_leader'); # :timorous_a_bandit_leader_lt:
INSERT INTO loottable(name) VALUES('timorous_a_dancing_skeleton'); # :timorous_a_dancing_skeleton_lt:
INSERT INTO loottable(name) VALUES('timorous_a_fallen_deckhand'); # :timorous_a_fallen_deckhand_lt:
INSERT INTO loottable(name) VALUES('timorous_a_fallen_iksar'); # :timorous_a_fallen_iksar_lt:
INSERT INTO loottable(name) VALUES('timorous_a_golra'); # :timorous_a_golra_lt:
INSERT INTO loottable(name) VALUES('timorous_a_gunthak_pirate'); # :timorous_a_gunthak_pirate_lt:
INSERT INTO loottable(name) VALUES('timorous_a_gunthak_swabby'); # :timorous_a_gunthak_swabby_lt:
INSERT INTO loottable(name) VALUES('timorous_a_hulking_golra'); # :timorous_a_hulking_golra_lt:
INSERT INTO loottable(name) VALUES('timorous_a_pebble'); # :timorous_a_pebble_lt:
INSERT INTO loottable(name) VALUES('timorous_a_raptor'); # :timorous_a_raptor_lt:
INSERT INTO loottable(name) VALUES('timorous_a_spiroc_harvester'); # :timorous_a_spiroc_harvester_lt:
INSERT INTO loottable(name) VALUES('timorous_a_spiroc_lightbringer'); # :timorous_a_spiroc_lightbringer_lt:
INSERT INTO loottable(name) VALUES('timorous_a_spiroc_lightfoot'); # :timorous_a_spiroc_lightfoot_lt:
INSERT INTO loottable(name) VALUES('timorous_a_spiroc_proven'); # :timorous_a_spiroc_proven_lt:
INSERT INTO loottable(name) VALUES('timorous_a_spiroc_warrior'); # :timorous_a_spiroc_warrior_lt:
INSERT INTO loottable(name) VALUES('timorous_a_spiroc_watcher'); # :timorous_a_spiroc_watcher_lt:
INSERT INTO loottable(name) VALUES('timorous_a_streamer'); # :timorous_a_streamer_lt:
INSERT INTO loottable(name) VALUES('timorous_a_streamer01'); # :timorous_a_streamer01_lt:
INSERT INTO loottable(name) VALUES('timorous_a_streamer02'); # :timorous_a_streamer02_lt:
INSERT INTO loottable(name) VALUES('timorous_a_streamer03'); # :timorous_a_streamer03_lt:
INSERT INTO loottable(name) VALUES('timorous_a_streamer04'); # :timorous_a_streamer04_lt:
INSERT INTO loottable(name) VALUES('timorous_a_streamer05'); # :timorous_a_streamer05_lt:
INSERT INTO loottable(name) VALUES('timorous_a_streamer06'); # :timorous_a_streamer06_lt:
INSERT INTO loottable(name) VALUES('timorous_a_streamer07'); # :timorous_a_streamer07_lt:
INSERT INTO loottable(name) VALUES('timorous_a_vicious_raptor'); # :timorous_a_vicious_raptor_lt:
INSERT INTO loottable(name) VALUES('timorous_bloated_belly'); # :timorous_bloated_belly_lt:
INSERT INTO loottable(name) VALUES('timorous_cursed_traveler'); # :timorous_cursed_traveler_lt:
INSERT INTO loottable(name) VALUES('timorous_dinus'); # :timorous_dinus_lt:
INSERT INTO loottable(name) VALUES('timorous_dolgin_codslayer'); # :timorous_dolgin_codslayer_lt:
INSERT INTO loottable(name) VALUES('timorous_draz_nurakk'); # :timorous_draz_nurakk_lt:
INSERT INTO loottable(name) VALUES('timorous_draz_nurakks_image'); # :timorous_draz_nurakks_image_lt:
INSERT INTO loottable(name) VALUES('timorous_drendico_metalbones'); # :timorous_drendico_metalbones_lt:
INSERT INTO loottable(name) VALUES('timorous_farstara_dio'); # :timorous_farstara_dio_lt:
INSERT INTO loottable(name) VALUES('timorous_faydedar'); # :timorous_faydedar_lt:
INSERT INTO loottable(name) VALUES('timorous_fire_gator'); # :timorous_fire_gator_lt:
INSERT INTO loottable(name) VALUES('timorous_glairb_stonebelly'); # :timorous_glairb_stonebelly_lt:
INSERT INTO loottable(name) VALUES('timorous_grandmaster_rinmark'); # :timorous_grandmaster_rinmark_lt:
INSERT INTO loottable(name) VALUES('timorous_halara'); # :timorous_halara_lt:
INSERT INTO loottable(name) VALUES('timorous_island_shuttle'); # :timorous_island_shuttle_lt:
INSERT INTO loottable(name) VALUES('timorous_izatri'); # :timorous_izatri_lt:
INSERT INTO loottable(name) VALUES('timorous_jhassad_oceanson'); # :timorous_jhassad_oceanson_lt:
INSERT INTO loottable(name) VALUES('timorous_kellewin_stillwater'); # :timorous_kellewin_stillwater_lt:
INSERT INTO loottable(name) VALUES('timorous_lheao'); # :timorous_lheao_lt:
INSERT INTO loottable(name) VALUES('timorous_master_rinmark'); # :timorous_master_rinmark_lt:
INSERT INTO loottable(name) VALUES('timorous_micus_vloren'); # :timorous_micus_vloren_lt:
INSERT INTO loottable(name) VALUES('timorous_natasha_whitewater'); # :timorous_natasha_whitewater_lt:
INSERT INTO loottable(name) VALUES('timorous_oasis'); # :timorous_oasis_lt:
INSERT INTO loottable(name) VALUES('timorous_ogre_wise_one'); # :timorous_ogre_wise_one_lt:
INSERT INTO loottable(name) VALUES('timorous_omat_vastsea'); # :timorous_omat_vastsea_lt:
INSERT INTO loottable(name) VALUES('timorous_perican_fallhammer'); # :timorous_perican_fallhammer_lt:
INSERT INTO loottable(name) VALUES('timorous_portik_grolam'); # :timorous_portik_grolam_lt:
INSERT INTO loottable(name) VALUES('timorous_quest_master_deedil'); # :timorous_quest_master_deedil_lt:
INSERT INTO loottable(name) VALUES('timorous_raider_watchman'); # :timorous_raider_watchman_lt:
INSERT INTO loottable(name) VALUES('timorous_rinmark'); # :timorous_rinmark_lt:
INSERT INTO loottable(name) VALUES('timorous_salco_dagor'); # :timorous_salco_dagor_lt:
INSERT INTO loottable(name) VALUES('timorous_scout_sihmoj'); # :timorous_scout_sihmoj_lt:
INSERT INTO loottable(name) VALUES('timorous_sellcondru_dusaan'); # :timorous_sellcondru_dusaan_lt:
INSERT INTO loottable(name) VALUES('timorous_seloris_windweaver'); # :timorous_seloris_windweaver_lt:
INSERT INTO loottable(name) VALUES('timorous_silithis_sisnta'); # :timorous_silithis_sisnta_lt:
INSERT INTO loottable(name) VALUES('timorous_the_fabled_oowomp'); # :timorous_the_fabled_oowomp_lt:
INSERT INTO loottable(name) VALUES('timorous_the_fabled_ugrak_da_raider'); # :timorous_the_fabled_ugrak_da_raider_lt:
INSERT INTO loottable(name) VALUES('timorous_the_great_oowomp'); # :timorous_the_great_oowomp_lt:
INSERT INTO loottable(name) VALUES('timorous_thousands_of'); # :timorous_thousands_of_lt:
INSERT INTO loottable(name) VALUES('timorous_ugrak_da_raider'); # :timorous_ugrak_da_raider_lt:
INSERT INTO loottable(name) VALUES('timorous_utte_the_virtuous'); # :timorous_utte_the_virtuous_lt:
INSERT INTO loottable(name) VALUES('timorous_xiblin_fizzlebik'); # :timorous_xiblin_fizzlebik_lt:
INSERT INTO loottable(name) VALUES('timorous__1'); # :timorous__1_lt:
INSERT INTO loottable(name) VALUES('timorous__10'); # :timorous__10_lt:
INSERT INTO loottable(name) VALUES('timorous__11'); # :timorous__11_lt:
INSERT INTO loottable(name) VALUES('timorous__12'); # :timorous__12_lt:
INSERT INTO loottable(name) VALUES('timorous__2'); # :timorous__2_lt:
INSERT INTO loottable(name) VALUES('timorous__3'); # :timorous__3_lt:
INSERT INTO loottable(name) VALUES('timorous__4'); # :timorous__4_lt:
INSERT INTO loottable(name) VALUES('timorous__5'); # :timorous__5_lt:
INSERT INTO loottable(name) VALUES('timorous__6'); # :timorous__6_lt:
INSERT INTO loottable(name) VALUES('timorous__7'); # :timorous__7_lt:
INSERT INTO loottable(name) VALUES('timorous__8'); # :timorous__8_lt:
INSERT INTO loottable(name) VALUES('timorous__9'); # :timorous__9_lt:
