# INSERT INTO loottable_entries(probability, loottable_id, lootdrop_id, drop_limit, mindrop) VALUES (100, :todo_lt:, :todo_ld:, 1, 1);
(1, :trakanon_froglok_tsu_shaman_lt:, :fine_steel_ld:),
(1, :trakanon_froglok_tal_shaman_lt:, :fine_steel_ld:),
(1, :trakanon_froglok_urd_shaman_lt:, :fine_steel_ld:),
(1, :trakanon_froglok_wan_knight_lt:, :fine_steel_ld:),
(1, :trakanon_froglok_vis_knight_lt:, :fine_steel_ld:),
(1, :trakanon_froglok_yun_shaman_lt:, :fine_steel_ld:),
(1, :trakanon_ranvigoz_tonsmith_lt:, :fine_steel_ld:),
(1, :trakanon_froglok_shin_warrior_lt:, :fine_steel_ld:),
(1, :trakanon_froglok_shin_knight_lt:, :fine_steel_ld:),
