UPDATE npc_types SET loottable_id = :warslikswood_an_injured_traveller_lt: WHERE id in (79130); # #an_injured_traveller 50
UPDATE npc_types SET loottable_id = :warslikswood_raving_goblinmaster_lt: WHERE id in (79126); # #Raving_Goblinmaster 60
UPDATE npc_types SET loottable_id = :warslikswood_an_iksar_bandit_lt: WHERE id in (79107, 79108, 79064); # an_Iksar_bandit 9
UPDATE npc_types SET loottable_id = :warslikswood_an_iksar_brigand_lt: WHERE id in (79110, 79111, 79004); # an_Iksar_brigand 11
UPDATE npc_types SET loottable_id = :warslikswood_an_iksar_footpad_lt: WHERE id in (79105, 79059, 79062); # an_Iksar_footpad 6
UPDATE npc_types SET loottable_id = :warslikswood_an_iksar_knight_lt: WHERE id in (79112); # an_Iksar_knight 21
UPDATE npc_types SET loottable_id = :warslikswood_an_iksar_manslayer_lt: WHERE id in (79063, 79079, 79080); # an_Iksar_manslayer 18
UPDATE npc_types SET loottable_id = :warslikswood_an_iksar_marauder_lt: WHERE id in (79055, 79068, 79069); # an_Iksar_marauder 16
UPDATE npc_types SET loottable_id = :warslikswood_a_forest_giant_lt: WHERE id in (79113); # a_forest_giant 20
UPDATE npc_types SET loottable_id = :warslikswood_a_forest_giant_evergreen_lt: WHERE id in (79022, 79024, 79040); # a_forest_giant_evergreen 26
UPDATE npc_types SET loottable_id = :warslikswood_a_forest_giant_greenwood_lt: WHERE id in (79002, 79023, 79026, 79039, 79043); # a_forest_giant_greenwood 19
UPDATE npc_types SET loottable_id = :warslikswood_a_forest_giant_sapling_lt: WHERE id in (79003, 79025, 79049); # a_forest_giant_sapling 17
UPDATE npc_types SET loottable_id = :warslikswood_a_frantic_goblin_lt: WHERE id in (79129); # a_frantic_goblin 40
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_agressor_lt: WHERE id in (79010, 79017, 79019); # a_goblin_agressor 19
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_battlemaster_lt: WHERE id in (79005, 79008, 79013); # a_goblin_battlemaster 15
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_bloodtracer_lt: WHERE id in (79007, 79031, 79052); # a_goblin_bloodtracer 18
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_bonecaster_lt: WHERE id in (79104, 79067, 79071); # a_goblin_bonecaster 11
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_hextracer_lt: WHERE id in (79070, 79074); # a_goblin_hextracer 8
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_hunter_lt: WHERE id in (79038, 79065); # a_goblin_hunter 8
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_outrider_lt: WHERE id in (79061); # a_goblin_outrider 5
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_pit_fighter_lt: WHERE id in (79016); # a_goblin_pit_fighter 16
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_scout_lt: WHERE id in (79020, 79035, 79047); # a_goblin_scout 4
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_skirmisher_lt: WHERE id in (79076, 79077, 79102); # a_goblin_skirmisher 12
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_soothsayer_lt: WHERE id in (79009, 79044, 79051); # a_goblin_soothsayer 20
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_thief_lt: WHERE id in (79114); # a_goblin_thief 4
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_warrior_lt: WHERE id in (79014, 79018, 79054); # a_goblin_warrior 20
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_watcher_lt: WHERE id in (79057, 79060, 79072); # a_goblin_watcher 4
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_whelp_lt: WHERE id in (79029); # a_goblin_whelp 1
UPDATE npc_types SET loottable_id = :warslikswood_a_goblin_witchdoctor_lt: WHERE id in (79006, 79011, 79012); # a_goblin_witchdoctor 15
UPDATE npc_types SET loottable_id = :warslikswood_a_pygmy_skulking_brute_lt: WHERE id in (79099, 79100, 79101); # a_pygmy_skulking_brute 18
UPDATE npc_types SET loottable_id = :warslikswood_a_rogue_shaman_lt: WHERE id in (79117); # a_rogue_shaman 9
UPDATE npc_types SET loottable_id = :warslikswood_a_scaled_wolf_cub_lt: WHERE id in (79106, 79000, 79041); # a_scaled_wolf_cub 4
UPDATE npc_types SET loottable_id = :warslikswood_a_scaled_wolf_elder_lt: WHERE id in (79119); # a_scaled_wolf_elder 22
UPDATE npc_types SET loottable_id = :warslikswood_a_scaled_wolf_pup_lt: WHERE id in (79037); # a_scaled_wolf_pup 1
UPDATE npc_types SET loottable_id = :warslikswood_a_shady_goblin_lt: WHERE id in (79056); # a_shady_goblin 40
UPDATE npc_types SET loottable_id = :warslikswood_a_skulking_brute_lt: WHERE id in (79032, 79033, 79034, 79036); # a_skulking_brute 22
UPDATE npc_types SET loottable_id = :warslikswood_a_skulking_brutling_lt: WHERE id in (79075, 79103); # a_skulking_brutling 13
UPDATE npc_types SET loottable_id = :warslikswood_a_skulking_runtling_lt: WHERE id in (79058, 79073); # a_skulking_runtling 9
UPDATE npc_types SET loottable_id = :warslikswood_captain_gideen_lt: WHERE id in (79083); # Captain_Gideen 50
UPDATE npc_types SET loottable_id = :warslikswood_crusader_eaxl_lt: WHERE id in (79082); # Crusader_Eaxl 50
UPDATE npc_types SET loottable_id = :warslikswood_crusader_myxl_lt: WHERE id in (79081); # Crusader_Myxl 50
UPDATE npc_types SET loottable_id = :warslikswood_daynight_lt: WHERE id in (79131); # daynight 1
UPDATE npc_types SET loottable_id = :warslikswood_decaying_skeleton_lt: WHERE id in (79001); # decaying_skeleton 1
UPDATE npc_types SET loottable_id = :warslikswood_drakigone_bruann_lt: WHERE id in (79156); # Drakigone_Bruann 50
UPDATE npc_types SET loottable_id = :warslikswood_ferocious_goblin_lt: WHERE id in (79128); # Ferocious_Goblin 45
UPDATE npc_types SET loottable_id = :warslikswood_gellrazz_scalerunner_lt: WHERE id in (79155); # Gellrazz_Scalerunner 50
UPDATE npc_types SET loottable_id = :warslikswood_goblin_spirit_caller_lt: WHERE id in (79045, 79046, 79066); # goblin_spirit_caller 22
UPDATE npc_types SET loottable_id = :warslikswood_grachnist_the_destroyer_lt: WHERE id in (79015); # Grachnist_the_Destroyer 32
UPDATE npc_types SET loottable_id = :warslikswood_hunter_kerkzyz_lt: WHERE id in (79120); # Hunter_Kerkzyz 50
UPDATE npc_types SET loottable_id = :warslikswood_hunter_rethzan_lt: WHERE id in (79124); # Hunter_Rethzan 50
UPDATE npc_types SET loottable_id = :warslikswood_hunter_veryix_lt: WHERE id in (79118); # Hunter_Veryix 50
UPDATE npc_types SET loottable_id = :warslikswood_hunter_yovoz_lt: WHERE id in (79121); # Hunter_Yovoz 50
UPDATE npc_types SET loottable_id = :warslikswood_iksar_bandit_lord_lt: WHERE id in (79116); # Iksar_Bandit_Lord 31
UPDATE npc_types SET loottable_id = :warslikswood_iksar_exile_lt: WHERE id in (79027, 79030, 79053); # Iksar_exile 25
UPDATE npc_types SET loottable_id = :warslikswood_iksar_pariah_lt: WHERE id in (79109, 79028, 79050); # Iksar_pariah 21
UPDATE npc_types SET loottable_id = :warslikswood_juikull_slizz_lt: WHERE id in (79151); # Juikull_Slizz 50
UPDATE npc_types SET loottable_id = :warslikswood_karrenabell_joonan_lt: WHERE id in (79152); # Karrenabell_Joonan 50
UPDATE npc_types SET loottable_id = :warslikswood_klok_gragin_lt: WHERE id in (79093); # Klok_Gragin 30
UPDATE npc_types SET loottable_id = :warslikswood_klok_kogrin_lt: WHERE id in (79094); # Klok_Kogrin 30
UPDATE npc_types SET loottable_id = :warslikswood_klok_nogolin_lt: WHERE id in (79097); # Klok_Nogolin 30
UPDATE npc_types SET loottable_id = :warslikswood_klok_rogalin_lt: WHERE id in (79095); # Klok_Rogalin 30
UPDATE npc_types SET loottable_id = :warslikswood_klok_ryre_lt: WHERE id in (79096); # Klok_Ryre 30
UPDATE npc_types SET loottable_id = :warslikswood_lurking_hopeful_lt: WHERE id in (79115); # Lurking_Hopeful 65
UPDATE npc_types SET loottable_id = :warslikswood_pit_fighter_dob_lt: WHERE id in (79125); # Pit_Fighter_Dob 33
UPDATE npc_types SET loottable_id = :warslikswood_raving_goblinmaster_lt: WHERE id in (79127); # Raving_Goblinmaster 60
UPDATE npc_types SET loottable_id = :warslikswood_silliv_host_lt: WHERE id in (79153); # Silliv_`Host 11
UPDATE npc_types SET loottable_id = :warslikswood_skeleton_lt: WHERE id in (79021, 79042, 79048); # skeleton 4
UPDATE npc_types SET loottable_id = :warslikswood_ssolet_dnaas_lt: WHERE id in (79098); # Ssolet_Dnaas 50
UPDATE npc_types SET loottable_id = :warslikswood_templar_nekzok_lt: WHERE id in (79123); # Templar_Nekzok 50
UPDATE npc_types SET loottable_id = :warslikswood_templar_trankoz_lt: WHERE id in (79122); # Templar_Trankoz 50
UPDATE npc_types SET loottable_id = :warslikswood_the_fabled_iksar_bandit_lord_lt: WHERE id in (79150); # The_Fabled_Iksar_Bandit_Lord 35
UPDATE npc_types SET loottable_id = :warslikswood_trooper_agash_lt: WHERE id in (79084); # Trooper_Agash 50
UPDATE npc_types SET loottable_id = :warslikswood_trooper_gepwyz_lt: WHERE id in (79087); # Trooper_Gepwyz 50
UPDATE npc_types SET loottable_id = :warslikswood_trooper_kroniz_lt: WHERE id in (79092); # Trooper_Kroniz 50
UPDATE npc_types SET loottable_id = :warslikswood_trooper_lunmiz_lt: WHERE id in (79085); # Trooper_Lunmiz 50
UPDATE npc_types SET loottable_id = :warslikswood_trooper_melzok_lt: WHERE id in (79089); # Trooper_Melzok 50
UPDATE npc_types SET loottable_id = :warslikswood_trooper_olon_lt: WHERE id in (79086); # Trooper_Olon 50
UPDATE npc_types SET loottable_id = :warslikswood_trooper_roklon_lt: WHERE id in (79090); # Trooper_Roklon 50
UPDATE npc_types SET loottable_id = :warslikswood_trooper_syldon_lt: WHERE id in (79088); # Trooper_Syldon 50
UPDATE npc_types SET loottable_id = :warslikswood_trooper_walrun_lt: WHERE id in (79091); # Trooper_Walrun 50
UPDATE npc_types SET loottable_id = :warslikswood_warlord_vyzer_lt: WHERE id in (79078); # Warlord_Vyzer 51
UPDATE npc_types SET loottable_id = :warslikswood_xarezia_drushiv_lt: WHERE id in (79154); # Xarezia_Dru`Shiv 50
