INSERT INTO loottable(name) VALUES('stillmoona_akihiro'); # :stillmoona_akihiro_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_silent_hunter'); # :stillmoona_a_silent_hunter_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_spirit_keeper'); # :stillmoona_a_spirit_keeper_lt:
INSERT INTO loottable(name) VALUES('stillmoona_hervash_the_foreman'); # :stillmoona_hervash_the_foreman_lt:
INSERT INTO loottable(name) VALUES('stillmoona_hong_lei'); # :stillmoona_hong_lei_lt:
INSERT INTO loottable(name) VALUES('stillmoona_jadewing'); # :stillmoona_jadewing_lt:
INSERT INTO loottable(name) VALUES('stillmoona_osashi'); # :stillmoona_osashi_lt:
INSERT INTO loottable(name) VALUES('stillmoona_shogurei,_guardian_of_the_sands'); # :stillmoona_shogurei,_guardian_of_the_sands_lt:
INSERT INTO loottable(name) VALUES('stillmoona_stoneskin'); # :stillmoona_stoneskin_lt:
INSERT INTO loottable(name) VALUES('stillmoona_sung_li'); # :stillmoona_sung_li_lt:
INSERT INTO loottable(name) VALUES('stillmoona_temple_foreman_korsav'); # :stillmoona_temple_foreman_korsav_lt:
INSERT INTO loottable(name) VALUES('stillmoona_the_keeper_of_strength'); # :stillmoona_the_keeper_of_strength_lt:
INSERT INTO loottable(name) VALUES('stillmoona_the_keeper_of_wisdom'); # :stillmoona_the_keeper_of_wisdom_lt:
INSERT INTO loottable(name) VALUES('stillmoona_an_ancestral_guardian'); # :stillmoona_an_ancestral_guardian_lt:
INSERT INTO loottable(name) VALUES('stillmoona_an_ancient_protector'); # :stillmoona_an_ancient_protector_lt:
INSERT INTO loottable(name) VALUES('stillmoona_an_ancient_stillmoon_guardian'); # :stillmoona_an_ancient_stillmoon_guardian_lt:
INSERT INTO loottable(name) VALUES('stillmoona_an_animated_statue'); # :stillmoona_an_animated_statue_lt:
INSERT INTO loottable(name) VALUES('stillmoona_an_infected_puma'); # :stillmoona_an_infected_puma_lt:
INSERT INTO loottable(name) VALUES('stillmoona_an_intricately_carved_chest'); # :stillmoona_an_intricately_carved_chest_lt:
INSERT INTO loottable(name) VALUES('stillmoona_an_iron_sentinel'); # :stillmoona_an_iron_sentinel_lt:
INSERT INTO loottable(name) VALUES('stillmoona_an_iron_warder'); # :stillmoona_an_iron_warder_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_clay_sentinel'); # :stillmoona_a_clay_sentinel_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_drakescale_protector'); # :stillmoona_a_drakescale_protector_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_drake_conspirator'); # :stillmoona_a_drake_conspirator_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_drake_usurper'); # :stillmoona_a_drake_usurper_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_goblin_guard'); # :stillmoona_a_goblin_guard_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_goblin_pet'); # :stillmoona_a_goblin_pet_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_goblin_poison_master'); # :stillmoona_a_goblin_poison_master_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_goblin_tea_tender'); # :stillmoona_a_goblin_tea_tender_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_goblin_warlord'); # :stillmoona_a_goblin_warlord_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_goblin_worker'); # :stillmoona_a_goblin_worker_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_poison_assistant'); # :stillmoona_a_poison_assistant_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_basalt_mage'); # :stillmoona_a_stillmoon_basalt_mage_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_champion'); # :stillmoona_a_stillmoon_champion_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_charmer'); # :stillmoona_a_stillmoon_charmer_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_defender'); # :stillmoona_a_stillmoon_defender_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_dirt_tender'); # :stillmoona_a_stillmoon_dirt_tender_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_drake'); # :stillmoona_a_stillmoon_drake_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_forest_warden'); # :stillmoona_a_stillmoon_forest_warden_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_goblin'); # :stillmoona_a_stillmoon_goblin_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_granite_keeper'); # :stillmoona_a_stillmoon_granite_keeper_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_gravel_warden'); # :stillmoona_a_stillmoon_gravel_warden_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_harmony'); # :stillmoona_a_stillmoon_harmony_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_harmony_wing'); # :stillmoona_a_stillmoon_harmony_wing_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_instigator'); # :stillmoona_a_stillmoon_instigator_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_keeper'); # :stillmoona_a_stillmoon_keeper_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_koi_master'); # :stillmoona_a_stillmoon_koi_master_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_laborer'); # :stillmoona_a_stillmoon_laborer_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_librarian'); # :stillmoona_a_stillmoon_librarian_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_lorekeeper'); # :stillmoona_a_stillmoon_lorekeeper_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_loremaster'); # :stillmoona_a_stillmoon_loremaster_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_magus'); # :stillmoona_a_stillmoon_magus_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_marauder'); # :stillmoona_a_stillmoon_marauder_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_mystic'); # :stillmoona_a_stillmoon_mystic_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_novice'); # :stillmoona_a_stillmoon_novice_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_protector'); # :stillmoona_a_stillmoon_protector_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_scoundrel'); # :stillmoona_a_stillmoon_scoundrel_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_seer'); # :stillmoona_a_stillmoon_seer_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_servant'); # :stillmoona_a_stillmoon_servant_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_shaman'); # :stillmoona_a_stillmoon_shaman_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_sorcerer'); # :stillmoona_a_stillmoon_sorcerer_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_stonecaster'); # :stillmoona_a_stillmoon_stonecaster_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_stone_caster'); # :stillmoona_a_stillmoon_stone_caster_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_stone_wing'); # :stillmoona_a_stillmoon_stone_wing_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_teacher'); # :stillmoona_a_stillmoon_teacher_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_templar'); # :stillmoona_a_stillmoon_templar_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_treasure_chest'); # :stillmoona_a_stillmoon_treasure_chest_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_wakemaker'); # :stillmoona_a_stillmoon_wakemaker_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_warlord'); # :stillmoona_a_stillmoon_warlord_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_watcher'); # :stillmoona_a_stillmoon_watcher_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_water_mage'); # :stillmoona_a_stillmoon_water_mage_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_water_servant'); # :stillmoona_a_stillmoon_water_servant_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_waverusher'); # :stillmoona_a_stillmoon_waverusher_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stillmoon_witchdoctor'); # :stillmoona_a_stillmoon_witchdoctor_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stone_guardian'); # :stillmoona_a_stone_guardian_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_stone_statue'); # :stillmoona_a_stone_statue_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_sturdy_chest'); # :stillmoona_a_sturdy_chest_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_swirl_of_sand'); # :stillmoona_a_swirl_of_sand_lt:
INSERT INTO loottable(name) VALUES('stillmoona_a_weather-beaten_chest'); # :stillmoona_a_weather-beaten_chest_lt:
INSERT INTO loottable(name) VALUES('stillmoona_bathouse_manager_hakvar'); # :stillmoona_bathouse_manager_hakvar_lt:
INSERT INTO loottable(name) VALUES('stillmoona_dark_reign_assistant'); # :stillmoona_dark_reign_assistant_lt:
INSERT INTO loottable(name) VALUES('stillmoona_dark_reign_contact'); # :stillmoona_dark_reign_contact_lt:
INSERT INTO loottable(name) VALUES('stillmoona_decrepit_guard'); # :stillmoona_decrepit_guard_lt:
INSERT INTO loottable(name) VALUES('stillmoona_elusive_kirin'); # :stillmoona_elusive_kirin_lt:
INSERT INTO loottable(name) VALUES('stillmoona_goblin_bath_attendant'); # :stillmoona_goblin_bath_attendant_lt:
INSERT INTO loottable(name) VALUES('stillmoona_goblin_laborer'); # :stillmoona_goblin_laborer_lt:
INSERT INTO loottable(name) VALUES('stillmoona_guard_musashi'); # :stillmoona_guard_musashi_lt:
INSERT INTO loottable(name) VALUES('stillmoona_guard_nobunaga'); # :stillmoona_guard_nobunaga_lt:
INSERT INTO loottable(name) VALUES('stillmoona_jorvash_the_usurper'); # :stillmoona_jorvash_the_usurper_lt:
INSERT INTO loottable(name) VALUES('stillmoona_nethran'); # :stillmoona_nethran_lt:
INSERT INTO loottable(name) VALUES('stillmoona_norrath's_keeper_contact'); # :stillmoona_norrath's_keeper_contact_lt:
INSERT INTO loottable(name) VALUES('stillmoona_scroll_thief'); # :stillmoona_scroll_thief_lt:
INSERT INTO loottable(name) VALUES('stillmoona_scroll_thief_underling'); # :stillmoona_scroll_thief_underling_lt:
INSERT INTO loottable(name) VALUES('stillmoona_shogurei,_guardian_of_the_sands'); # :stillmoona_shogurei,_guardian_of_the_sands_lt:
INSERT INTO loottable(name) VALUES('stillmoona_stillmoon_courtyard_gardener'); # :stillmoona_stillmoon_courtyard_gardener_lt:
INSERT INTO loottable(name) VALUES('stillmoona_stillmoon_forest_keeper'); # :stillmoona_stillmoon_forest_keeper_lt:
INSERT INTO loottable(name) VALUES('stillmoona_stillmoon_henchman'); # :stillmoona_stillmoon_henchman_lt:
INSERT INTO loottable(name) VALUES('stillmoona_stillmoon_plan_keeper'); # :stillmoona_stillmoon_plan_keeper_lt:
INSERT INTO loottable(name) VALUES('stillmoona_stillmoon_tea_master'); # :stillmoona_stillmoon_tea_master_lt:
INSERT INTO loottable(name) VALUES('stillmoona_tunk_the_fluid'); # :stillmoona_tunk_the_fluid_lt:
INSERT INTO loottable(name) VALUES('stillmoona_unusual_footprints'); # :stillmoona_unusual_footprints_lt:
INSERT INTO loottable(name) VALUES('stillmoona_wei_chung'); # :stillmoona_wei_chung_lt:
INSERT INTO loottable(name) VALUES('stillmoona_wei_zhang'); # :stillmoona_wei_zhang_lt:
INSERT INTO loottable(name) VALUES('stillmoona_wong_li'); # :stillmoona_wong_li_lt:
INSERT INTO loottable(name) VALUES('stillmoona__'); # :stillmoona___lt:
