INSERT INTO loottable(name) VALUES('acrylia_an_evolved_burrower'); # :acrylia_an_evolved_burrower_lt:
INSERT INTO loottable(name) VALUES('acrylia_as'); # :acrylia_as_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_summoned_burrower'); # :acrylia_a_summoned_burrower_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_summoned_crawler'); # :acrylia_a_summoned_crawler_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_summoned_hatchling'); # :acrylia_a_summoned_hatchling_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_summoned_larva'); # :acrylia_a_summoned_larva_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_summoned_pupa'); # :acrylia_a_summoned_pupa_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_summoned_worm'); # :acrylia_a_summoned_worm_lt:
INSERT INTO loottable(name) VALUES('acrylia_evinvis'); # :acrylia_evinvis_lt:
INSERT INTO loottable(name) VALUES('acrylia_gurmarl_the_chieftain'); # :acrylia_gurmarl_the_chieftain_lt:
INSERT INTO loottable(name) VALUES('acrylia_raidman'); # :acrylia_raidman_lt:
INSERT INTO loottable(name) VALUES('acrylia_the_fabled_khati_sha_the_twisted'); # :acrylia_the_fabled_khati_sha_the_twisted_lt:
INSERT INTO loottable(name) VALUES('acrylia_the_fabled_ward_of_death'); # :acrylia_the_fabled_ward_of_death_lt:
INSERT INTO loottable(name) VALUES('acrylia_the_fabled_ward_of_life'); # :acrylia_the_fabled_ward_of_life_lt:
INSERT INTO loottable(name) VALUES('acrylia_the_grimling_archmage'); # :acrylia_the_grimling_archmage_lt:
INSERT INTO loottable(name) VALUES('acrylia_ward_of_death'); # :acrylia_ward_of_death_lt:
INSERT INTO loottable(name) VALUES('acrylia_ward_of_life'); # :acrylia_ward_of_life_lt:
INSERT INTO loottable(name) VALUES('acrylia_animman'); # :acrylia_animman_lt:
INSERT INTO loottable(name) VALUES('acrylia_antispawnman'); # :acrylia_antispawnman_lt:
INSERT INTO loottable(name) VALUES('acrylia_an_elite_grimling_deathguard'); # :acrylia_an_elite_grimling_deathguard_lt:
INSERT INTO loottable(name) VALUES('acrylia_an_enslaved_shiknar'); # :acrylia_an_enslaved_shiknar_lt:
INSERT INTO loottable(name) VALUES('acrylia_an_undead_warden'); # :acrylia_an_undead_warden_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_diseased_grimling'); # :acrylia_a_diseased_grimling_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_fallen_vah_shir_hero'); # :acrylia_a_fallen_vah_shir_hero_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_furious_apprentice'); # :acrylia_a_furious_apprentice_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_apprentice'); # :acrylia_a_grimling_apprentice_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_arcanist'); # :acrylia_a_grimling_arcanist_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_bloodguard'); # :acrylia_a_grimling_bloodguard_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_bloodpriest'); # :acrylia_a_grimling_bloodpriest_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_cadaverist'); # :acrylia_a_grimling_cadaverist_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_deathbringer'); # :acrylia_a_grimling_deathbringer_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_deathguard'); # :acrylia_a_grimling_deathguard_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_deathpriest'); # :acrylia_a_grimling_deathpriest_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_deathspeaker'); # :acrylia_a_grimling_deathspeaker_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_dreamspinner'); # :acrylia_a_grimling_dreamspinner_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_elite_guard'); # :acrylia_a_grimling_elite_guard_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_fire_eater'); # :acrylia_a_grimling_fire_eater_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_hero'); # :acrylia_a_grimling_hero_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_high_priest'); # :acrylia_a_grimling_high_priest_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_manacrafter'); # :acrylia_a_grimling_manacrafter_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_manaseeker'); # :acrylia_a_grimling_manaseeker_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_prison_guard'); # :acrylia_a_grimling_prison_guard_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_ritualist'); # :acrylia_a_grimling_ritualist_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_skullcracker'); # :acrylia_a_grimling_skullcracker_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_soulsoother'); # :acrylia_a_grimling_soulsoother_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_spiritslaver'); # :acrylia_a_grimling_spiritslaver_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_summoner'); # :acrylia_a_grimling_summoner_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_grimling_warder'); # :acrylia_a_grimling_warder_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_growl'); # :acrylia_a_growl_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_mutated_chrysalis'); # :acrylia_a_mutated_chrysalis_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_pit_trap'); # :acrylia_a_pit_trap_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_possessed_battlelord'); # :acrylia_a_possessed_battlelord_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_possessed_battlemaster'); # :acrylia_a_possessed_battlemaster_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_possessed_corpse'); # :acrylia_a_possessed_corpse_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_possessed_priest'); # :acrylia_a_possessed_priest_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_possessed_warmonger'); # :acrylia_a_possessed_warmonger_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_runed_grimling'); # :acrylia_a_runed_grimling_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_sacrifice'); # :acrylia_a_sacrifice_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_sanctum_bloodguard'); # :acrylia_a_sanctum_bloodguard_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_sanctum_corpsemaster'); # :acrylia_a_sanctum_corpsemaster_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_sanctum_deathpriest'); # :acrylia_a_sanctum_deathpriest_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_sanctum_spiritslaver'); # :acrylia_a_sanctum_spiritslaver_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_savage_shiknar'); # :acrylia_a_savage_shiknar_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_skeletal_enforcer'); # :acrylia_a_skeletal_enforcer_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_skeletal_minion'); # :acrylia_a_skeletal_minion_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_smudged_grimling'); # :acrylia_a_smudged_grimling_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_spell_jammer'); # :acrylia_a_spell_jammer_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_spiritual_arcanist'); # :acrylia_a_spiritual_arcanist_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_spirit_caller'); # :acrylia_a_spirit_caller_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_spirit_guard'); # :acrylia_a_spirit_guard_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_spirit_healer'); # :acrylia_a_spirit_healer_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_spirit_speaker'); # :acrylia_a_spirit_speaker_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_war_painted_skullcracker'); # :acrylia_a_war_painted_skullcracker_lt:
INSERT INTO loottable(name) VALUES('acrylia_a_wormbait_minnow'); # :acrylia_a_wormbait_minnow_lt:
INSERT INTO loottable(name) VALUES('acrylia_combatman'); # :acrylia_combatman_lt:
INSERT INTO loottable(name) VALUES('acrylia_defiled_minion'); # :acrylia_defiled_minion_lt:
INSERT INTO loottable(name) VALUES('acrylia_foreman_gworknop'); # :acrylia_foreman_gworknop_lt:
INSERT INTO loottable(name) VALUES('acrylia_gatturg_deadface'); # :acrylia_gatturg_deadface_lt:
INSERT INTO loottable(name) VALUES('acrylia_gruj_warfist'); # :acrylia_gruj_warfist_lt:
INSERT INTO loottable(name) VALUES('acrylia_invis'); # :acrylia_invis_lt:
INSERT INTO loottable(name) VALUES('acrylia_khati_sha_the_twisted'); # :acrylia_khati_sha_the_twisted_lt:
INSERT INTO loottable(name) VALUES('acrylia_reanimated_prisoner'); # :acrylia_reanimated_prisoner_lt:
INSERT INTO loottable(name) VALUES('acrylia_shackle'); # :acrylia_shackle_lt:
INSERT INTO loottable(name) VALUES('acrylia_spiritist_andro_shimi'); # :acrylia_spiritist_andro_shimi_lt:
INSERT INTO loottable(name) VALUES('acrylia_spiritist_kama_resan'); # :acrylia_spiritist_kama_resan_lt:
INSERT INTO loottable(name) VALUES('acrylia_tashakhi'); # :acrylia_tashakhi_lt:
INSERT INTO loottable(name) VALUES('acrylia_the_grimling_archmage'); # :acrylia_the_grimling_archmage_lt:
INSERT INTO loottable(name) VALUES('acrylia_the_sacrificial_cauldron'); # :acrylia_the_sacrificial_cauldron_lt:
INSERT INTO loottable(name) VALUES('acrylia_the_vile_statue'); # :acrylia_the_vile_statue_lt:
INSERT INTO loottable(name) VALUES('acrylia_trondol_shir'); # :acrylia_trondol_shir_lt:
INSERT INTO loottable(name) VALUES('acrylia_vhalek_shah'); # :acrylia_vhalek_shah_lt:
INSERT INTO loottable(name) VALUES('acrylia_wdtrpmn'); # :acrylia_wdtrpmn_lt:
