UPDATE npc_types SET loottable_id = :echo_adelin_crow_lt: WHERE id in (153030); # #Adelin_Crow 27
UPDATE npc_types SET loottable_id = :echo_crinthia_signseer_lt: WHERE id in (153033); # #Crinthia_Signseer 28
UPDATE npc_types SET loottable_id = :echo_dack_tiktopper_lt: WHERE id in (153042); # #Dack_Tiktopper 28
UPDATE npc_types SET loottable_id = :echo_fireclaw_lt: WHERE id in (153005); # #Fireclaw 40
UPDATE npc_types SET loottable_id = :echo_marin_pointear_lt: WHERE id in (153012); # #Marin_Pointear 28
UPDATE npc_types SET loottable_id = :echo_murph_cobblestone_lt: WHERE id in (153130); # #Murph_Cobblestone 26
UPDATE npc_types SET loottable_id = :echo_torin_truestring_lt: WHERE id in (153044); # #Torin_Truestring 23
UPDATE npc_types SET loottable_id = :echo_trillcor_lt: WHERE id in (153145); # #Trillcor 39
UPDATE npc_types SET loottable_id = :echo_xilniov_lt: WHERE id in (153142); # #Xilniov 52
UPDATE npc_types SET loottable_id = :echo_amscray_the_historian_lt: WHERE id in (153046); # Amscray_the_Historian 35
UPDATE npc_types SET loottable_id = :echo_an_archer_lt: WHERE id in (153047); # an_archer 45
UPDATE npc_types SET loottable_id = :echo_an_assassin_protector_lt: WHERE id in (153094, 153144); # an_assassin_protector 51
UPDATE npc_types SET loottable_id = :echo_an_outcast_mutant_lt: WHERE id in (153131, 153025, 153029, 153032, 153040); # an_outcast_mutant 25
UPDATE npc_types SET loottable_id = :echo_an_undead_slave_lt: WHERE id in (153118, 153119, 153133); # an_undead_slave 39
UPDATE npc_types SET loottable_id = :echo_an_underbulk_lt: WHERE id in (153000, 153008, 153010, 153013); # an_underbulk 36
UPDATE npc_types SET loottable_id = :echo_arisen_soldier_lt: WHERE id in (153089, 153090, 153092); # arisen_soldier 47
UPDATE npc_types SET loottable_id = :echo_asther_lt: WHERE id in (153038); # Asther 25
UPDATE npc_types SET loottable_id = :echo_a_bogling_lt: WHERE id in (153128, 153129, 153018, 153019, 153026); # a_bogling 28
UPDATE npc_types SET loottable_id = :echo_a_bogling_cultist_lt: WHERE id in (153015); # a_bogling_cultist 33
UPDATE npc_types SET loottable_id = :echo_a_bogling_scout_lt: WHERE id in (153116, 153137, 153007, 153009, 153020); # a_bogling_scout 21
UPDATE npc_types SET loottable_id = :echo_a_bogling_warrior_lt: WHERE id in (153135, 153016, 153017); # a_bogling_warrior 30
UPDATE npc_types SET loottable_id = :echo_a_festering_mushroom_lt: WHERE id in (153041); # a_festering_mushroom 21
UPDATE npc_types SET loottable_id = :echo_a_fungal_fiend_lt: WHERE id in (153115, 153117, 153003, 153004, 153006); # a_fungal_fiend 36
UPDATE npc_types SET loottable_id = :echo_a_haven_defender_lt: WHERE id in (153035); # a_Haven_Defender 40
UPDATE npc_types SET loottable_id = :echo_a_needlite_lt: WHERE id in (153121, 153123, 153125, 153001, 153002); # a_needlite 23
UPDATE npc_types SET loottable_id = :echo_a_saprophyte_spawn_lt: WHERE id in (153049); # a_saprophyte_spawn 27
UPDATE npc_types SET loottable_id = :echo_a_scound_lt: WHERE id in (153076); # a_scound 45
UPDATE npc_types SET loottable_id = :echo_a_stonegrabber_lt: WHERE id in (153122, 153124, 153126, 153132, 153011); # a_stonegrabber 37
UPDATE npc_types SET loottable_id = :echo_a_wormspore_lt: WHERE id in (153147); # a_wormspore 36
UPDATE npc_types SET loottable_id = :echo_blademaster_kelsitch_lt: WHERE id in (153103); # Blademaster_Kelsitch 45
UPDATE npc_types SET loottable_id = :echo_bowmaster_staniel_lt: WHERE id in (153107); # Bowmaster_Staniel 45
UPDATE npc_types SET loottable_id = :echo_cerinos_blackfinger_lt: WHERE id in (153113); # Cerinos_Blackfinger 37
UPDATE npc_types SET loottable_id = :echo_chief_groplin_lt: WHERE id in (153138); # Chief_Groplin 30
UPDATE npc_types SET loottable_id = :echo_court_jester_lt: WHERE id in (153031); # Court_Jester 40
UPDATE npc_types SET loottable_id = :echo_court_sage_lt: WHERE id in (153055); # Court_Sage 40
UPDATE npc_types SET loottable_id = :echo_crates_the_philosopher_lt: WHERE id in (153073); # Crates_the_Philosopher 35
UPDATE npc_types SET loottable_id = :echo_crazy_pete_lt: WHERE id in (153043); # Crazy_Pete 24
UPDATE npc_types SET loottable_id = :echo_crewman_pete_lt: WHERE id in (153134, 153072); # Crewman_Pete 31
UPDATE npc_types SET loottable_id = :echo_crew_chief_doyle_lt: WHERE id in (153061); # Crew_Chief_Doyle 35
UPDATE npc_types SET loottable_id = :echo_crew_chief_grinn_lt: WHERE id in (153070); # Crew_Chief_Grinn 35
UPDATE npc_types SET loottable_id = :echo_crew_chief_tarin_lt: WHERE id in (153071); # Crew_Chief_Tarin 35
UPDATE npc_types SET loottable_id = :echo_darian_the_preacher_lt: WHERE id in (153036); # Darian_the_Preacher 25
UPDATE npc_types SET loottable_id = :echo_defender_antorin_lt: WHERE id in (153112); # Defender_Antorin 30
UPDATE npc_types SET loottable_id = :echo_defender_birk_lt: WHERE id in (153060); # Defender_Birk 35
UPDATE npc_types SET loottable_id = :echo_defender_oram_lt: WHERE id in (153077); # Defender_Oram 30
UPDATE npc_types SET loottable_id = :echo_defender_pauls_lt: WHERE id in (153111); # Defender_Pauls 30
UPDATE npc_types SET loottable_id = :echo_defender_siltan_lt: WHERE id in (153110); # Defender_Siltan 30
UPDATE npc_types SET loottable_id = :echo_defender_siman_lt: WHERE id in (153058); # Defender_Siman 35
UPDATE npc_types SET loottable_id = :echo_defender_stavros_lt: WHERE id in (153054); # Defender_Stavros 30
UPDATE npc_types SET loottable_id = :echo_defender_urik_lt: WHERE id in (153053); # Defender_Urik 30
UPDATE npc_types SET loottable_id = :echo_drible_telakeri_lt: WHERE id in (153080); # Drible_Telakeri 55
UPDATE npc_types SET loottable_id = :echo_duke_norfin_lt: WHERE id in (153101); # Duke_Norfin 61
UPDATE npc_types SET loottable_id = :echo_engineer_palin_lt: WHERE id in (153050); # Engineer_Palin 31
UPDATE npc_types SET loottable_id = :echo_falos_ginranes_lt: WHERE id in (153087); # Falos_Ginranes 30
UPDATE npc_types SET loottable_id = :echo_garer_lt: WHERE id in (153139); # Garer 39
UPDATE npc_types SET loottable_id = :echo_general_jared_blaystich_lt: WHERE id in (153095); # General_Jared_Blaystich 55
UPDATE npc_types SET loottable_id = :echo_gip_gallows_lt: WHERE id in (153045); # Gip_Gallows 24
UPDATE npc_types SET loottable_id = :echo_guard_alfast_lt: WHERE id in (153027); # Guard_Alfast 38
UPDATE npc_types SET loottable_id = :echo_guard_cyren_lt: WHERE id in (153023); # Guard_Cyren 38
UPDATE npc_types SET loottable_id = :echo_guard_mirick_lt: WHERE id in (153028); # Guard_Mirick 38
UPDATE npc_types SET loottable_id = :echo_guard_tork_lt: WHERE id in (153024); # Guard_Tork 38
UPDATE npc_types SET loottable_id = :echo_guildmaster_grobin_lt: WHERE id in (153057); # Guildmaster_Grobin 37
UPDATE npc_types SET loottable_id = :echo_harold_the_herald_lt: WHERE id in (153034); # Harold_the_Herald 37
UPDATE npc_types SET loottable_id = :echo_horoal_deathdealer_lt: WHERE id in (153088); # Horoal_Deathdealer 30
UPDATE npc_types SET loottable_id = :echo_jake_the_shoveler_lt: WHERE id in (153062); # Jake_the_Shoveler 32
UPDATE npc_types SET loottable_id = :echo_kacheoa_dariwlan_lt: WHERE id in (153081); # Kacheoa_Dariwlan 55
UPDATE npc_types SET loottable_id = :echo_king_gomklin_of_below_lt: WHERE id in (153022); # King_Gomklin_of_Below 45
UPDATE npc_types SET loottable_id = :echo_king_grery_of_above_lt: WHERE id in (153021); # King_Grery_of_Above 45
UPDATE npc_types SET loottable_id = :echo_konekn_lt: WHERE id in (153140); # Konekn 31
UPDATE npc_types SET loottable_id = :echo_lieutenant_arathur_lt: WHERE id in (153120); # Lieutenant_Arathur 35
UPDATE npc_types SET loottable_id = :echo_lineol_teropalig_lt: WHERE id in (153079); # Lineol_Teropalig 61
UPDATE npc_types SET loottable_id = :echo_marshall_galeron_lt: WHERE id in (153102); # Marshall_Galeron 61
UPDATE npc_types SET loottable_id = :echo_master_assasin_prasor_lt: WHERE id in (153141); # Master_Assasin_Prasor 61
UPDATE npc_types SET loottable_id = :echo_master_assassin_prasor_lt: WHERE id in (153100); # Master_Assassin_Prasor 61
UPDATE npc_types SET loottable_id = :echo_master_celerik_lt: WHERE id in (153098); # Master_Celerik 61
UPDATE npc_types SET loottable_id = :echo_master_nochtar_lt: WHERE id in (153099); # Master_Nochtar 61
UPDATE npc_types SET loottable_id = :echo_master_wirgus_lt: WHERE id in (153096); # Master_Wirgus 61
UPDATE npc_types SET loottable_id = :echo_master_yurian_lt: WHERE id in (153097); # Master_Yurian 61
UPDATE npc_types SET loottable_id = :echo_miner_buritch_lt: WHERE id in (153067); # Miner_Buritch 30
UPDATE npc_types SET loottable_id = :echo_miner_corin_lt: WHERE id in (153064); # Miner_Corin 30
UPDATE npc_types SET loottable_id = :echo_miner_daven_lt: WHERE id in (153078); # Miner_Daven 30
UPDATE npc_types SET loottable_id = :echo_miner_dirkins_lt: WHERE id in (153059); # Miner_Dirkins 32
UPDATE npc_types SET loottable_id = :echo_miner_neville_lt: WHERE id in (153069); # Miner_Neville 30
UPDATE npc_types SET loottable_id = :echo_miner_perrin_lt: WHERE id in (153063); # Miner_Perrin 30
UPDATE npc_types SET loottable_id = :echo_miner_skorn_lt: WHERE id in (153065); # Miner_Skorn 30
UPDATE npc_types SET loottable_id = :echo_miner_tager_lt: WHERE id in (153068); # Miner_Tager 30
UPDATE npc_types SET loottable_id = :echo_miner_zelitz_lt: WHERE id in (153066); # Miner_Zelitz 30
UPDATE npc_types SET loottable_id = :echo_nightmaster_kelador_lt: WHERE id in (153091); # Nightmaster_Kelador 61
UPDATE npc_types SET loottable_id = :echo_olowakn_telrok_lt: WHERE id in (153085); # Olowakn_Telrok 55
UPDATE npc_types SET loottable_id = :echo_pelinor_the_arms_merchant_lt: WHERE id in (153106); # Pelinor_the_Arms_Merchant 45
UPDATE npc_types SET loottable_id = :echo_polyona_lt: WHERE id in (153052); # Polyona 40
UPDATE npc_types SET loottable_id = :echo_priestess_tarafol_lt: WHERE id in (153039); # Priestess_Tarafol 30
UPDATE npc_types SET loottable_id = :echo_pugidlar_vermot_lt: WHERE id in (153084); # Pugidlar_Vermot 55
UPDATE npc_types SET loottable_id = :echo_rasl_lerosac_lt: WHERE id in (153082); # Rasl_Lerosac 55
UPDATE npc_types SET loottable_id = :echo_ronald_the_shoveler_lt: WHERE id in (153048); # Ronald_the_Shoveler 32
UPDATE npc_types SET loottable_id = :echo_roy_lt: WHERE id in (153037); # Roy 32
UPDATE npc_types SET loottable_id = :echo_royal_guardian_of_above_lt: WHERE id in (153051); # Royal_Guardian_of_Above 40
UPDATE npc_types SET loottable_id = :echo_royal_guardian_of_below_lt: WHERE id in (153056); # Royal_Guardian_of_Below 40
UPDATE npc_types SET loottable_id = :echo_saerlsam_monrols_lt: WHERE id in (153086); # Saerlsam_Monrols 55
UPDATE npc_types SET loottable_id = :echo_scound_dralin_lt: WHERE id in (153074); # Scound_Dralin 45
UPDATE npc_types SET loottable_id = :echo_scound_trevor_lt: WHERE id in (153075); # Scound_Trevor 45
UPDATE npc_types SET loottable_id = :echo_solsain_paslinor_lt: WHERE id in (153083); # Solsain_Paslinor 55
UPDATE npc_types SET loottable_id = :echo_spawner_lt: WHERE id in (153146); # Spawner 1
UPDATE npc_types SET loottable_id = :echo_taskmaster_torkazh_lt: WHERE id in (153127); # Taskmaster_Torkazh 42
UPDATE npc_types SET loottable_id = :echo_the_fabled_general_jared_blaystich_lt: WHERE id in (153148); # The_Fabled_General_Jared_Blaystich 70
UPDATE npc_types SET loottable_id = :echo_the_fabled_needlite_queen_lt: WHERE id in (153149); # The_Fabled_Needlite_Queen 40
UPDATE npc_types SET loottable_id = :echo_the_great_saprophyte_lt: WHERE id in (153014); # The_Great_Saprophyte 35
UPDATE npc_types SET loottable_id = :echo_the_needlite_queen_lt: WHERE id in (153136); # The_Needlite_Queen 28
UPDATE npc_types SET loottable_id = :echo_trace_the_tinker_lt: WHERE id in (153114); # Trace_the_Tinker 35
UPDATE npc_types SET loottable_id = :echo_trademaster_korvesh_lt: WHERE id in (153093); # Trademaster_Korvesh 45
UPDATE npc_types SET loottable_id = :echo_trainee_barkis_lt: WHERE id in (153104); # Trainee_Barkis 40
UPDATE npc_types SET loottable_id = :echo_trainee_durvich_lt: WHERE id in (153105); # Trainee_Durvich 40
UPDATE npc_types SET loottable_id = :echo_trainee_kelwyn_lt: WHERE id in (153109); # Trainee_Kelwyn 40
UPDATE npc_types SET loottable_id = :echo_trainee_robert_lt: WHERE id in (153108); # Trainee_Robert 40
UPDATE npc_types SET loottable_id = :echo_zaber_lt: WHERE id in (153143); # Zaber 36
