INSERT INTO loottable(name) VALUES('fungusgrove_caller_groo'); # :fungusgrove_caller_groo_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_caller_murkin'); # :fungusgrove_caller_murkin_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_caller_torgal'); # :fungusgrove_caller_torgal_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_chakiza'); # :fungusgrove_chakiza_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_chakno'); # :fungusgrove_chakno_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_draz_nurakk'); # :fungusgrove_draz_nurakk_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_draz_nurakks_warder'); # :fungusgrove_draz_nurakks_warder_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_katcha'); # :fungusgrove_katcha_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_takacha'); # :fungusgrove_takacha_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_tiako'); # :fungusgrove_tiako_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_tuchako'); # :fungusgrove_tuchako_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_an_underbulk'); # :fungusgrove_an_underbulk_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_bandit_lookout'); # :fungusgrove_a_bandit_lookout_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_chakta_fungusbeast'); # :fungusgrove_a_chakta_fungusbeast_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_chakta_fungusfiend'); # :fungusgrove_a_chakta_fungusfiend_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_chakta_fungus_healer'); # :fungusgrove_a_chakta_fungus_healer_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_chakta_fungus_priest'); # :fungusgrove_a_chakta_fungus_priest_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_deep_cavern_lotus'); # :fungusgrove_a_deep_cavern_lotus_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_domestic_beetle'); # :fungusgrove_a_domestic_beetle_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_domestic_underbulk'); # :fungusgrove_a_domestic_underbulk_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_mutant_dreg'); # :fungusgrove_a_mutant_dreg_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_shadel_bandit'); # :fungusgrove_a_shadel_bandit_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_shiknar_forager'); # :fungusgrove_a_shiknar_forager_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_shiknar_hatchling'); # :fungusgrove_a_shiknar_hatchling_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_shiknar_nurse'); # :fungusgrove_a_shiknar_nurse_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_sleeping_tarmok'); # :fungusgrove_a_sleeping_tarmok_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_small_mushroom'); # :fungusgrove_a_small_mushroom_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_small_underbulk'); # :fungusgrove_a_small_underbulk_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_tarmok_beetle_herder'); # :fungusgrove_a_tarmok_beetle_herder_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_tarmok_defender'); # :fungusgrove_a_tarmok_defender_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_tarmok_lookout'); # :fungusgrove_a_tarmok_lookout_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_tarmok_protector'); # :fungusgrove_a_tarmok_protector_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_tarmok_tribesman'); # :fungusgrove_a_tarmok_tribesman_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_a_underbulk_hatchling'); # :fungusgrove_a_underbulk_hatchling_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_batin_sweery'); # :fungusgrove_batin_sweery_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_cen_snoworb'); # :fungusgrove_cen_snoworb_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_draz_nurakk'); # :fungusgrove_draz_nurakk_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_east_atk_man_one'); # :fungusgrove_east_atk_man_one_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_east_atk_man_three'); # :fungusgrove_east_atk_man_three_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_east_atk_man_two'); # :fungusgrove_east_atk_man_two_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_east_death_ear'); # :fungusgrove_east_death_ear_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_east_raid_manager'); # :fungusgrove_east_raid_manager_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_ebben_quickblade'); # :fungusgrove_ebben_quickblade_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_esti_elvenblood'); # :fungusgrove_esti_elvenblood_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fabi_arnett'); # :fungusgrove_fabi_arnett_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgeastraidmankiller'); # :fungusgrove_fgeastraidmankiller_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgnorthraidmankiller'); # :fungusgrove_fgnorthraidmankiller_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgsouthraidmankiller'); # :fungusgrove_fgsouthraidmankiller_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgueastattackcaller'); # :fungusgrove_fgueastattackcaller_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgueastcallerspawner'); # :fungusgrove_fgueastcallerspawner_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgunorthattackcaller'); # :fungusgrove_fgunorthattackcaller_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgunorthcallerspawner'); # :fungusgrove_fgunorthcallerspawner_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgushouter'); # :fungusgrove_fgushouter_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgusouthattackcaller'); # :fungusgrove_fgusouthattackcaller_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_fgusouthcallerspawner'); # :fungusgrove_fgusouthcallerspawner_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_basso'); # :fungusgrove_guard_basso_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_camil'); # :fungusgrove_guard_camil_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_dortof'); # :fungusgrove_guard_dortof_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_fornar'); # :fungusgrove_guard_fornar_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_jontroy'); # :fungusgrove_guard_jontroy_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_kartim'); # :fungusgrove_guard_kartim_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_kirste'); # :fungusgrove_guard_kirste_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_marmo'); # :fungusgrove_guard_marmo_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_megnon'); # :fungusgrove_guard_megnon_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_rento'); # :fungusgrove_guard_rento_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_rhoy'); # :fungusgrove_guard_rhoy_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_sinda'); # :fungusgrove_guard_sinda_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_smet'); # :fungusgrove_guard_smet_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_guard_varuf'); # :fungusgrove_guard_varuf_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_jasan_fiar'); # :fungusgrove_jasan_fiar_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_jolly_arval'); # :fungusgrove_jolly_arval_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_lupot_nukla'); # :fungusgrove_lupot_nukla_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_martin_woelt'); # :fungusgrove_martin_woelt_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_missy_mcelle'); # :fungusgrove_missy_mcelle_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_narvak_smugreed'); # :fungusgrove_narvak_smugreed_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_north_atk_man_one'); # :fungusgrove_north_atk_man_one_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_north_atk_man_three'); # :fungusgrove_north_atk_man_three_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_north_atk_man_two'); # :fungusgrove_north_atk_man_two_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_north_death_ear'); # :fungusgrove_north_death_ear_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_north_raid_manager'); # :fungusgrove_north_raid_manager_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_orlaba'); # :fungusgrove_orlaba_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_priest_kakthak'); # :fungusgrove_priest_kakthak_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_rebecca_cabbageleaf'); # :fungusgrove_rebecca_cabbageleaf_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_rictor_asmot'); # :fungusgrove_rictor_asmot_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_rolktim_cogtop'); # :fungusgrove_rolktim_cogtop_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_samfort_ruggen'); # :fungusgrove_samfort_ruggen_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_sartor'); # :fungusgrove_sartor_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_scout_halmia'); # :fungusgrove_scout_halmia_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_several'); # :fungusgrove_several_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_shiknar_herdmaster'); # :fungusgrove_shiknar_herdmaster_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_shiknar_royal_advisor'); # :fungusgrove_shiknar_royal_advisor_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_shiknar_royal_guard'); # :fungusgrove_shiknar_royal_guard_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_shiknar_soldier'); # :fungusgrove_shiknar_soldier_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_shiknar_warrior'); # :fungusgrove_shiknar_warrior_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_shiknar_worker'); # :fungusgrove_shiknar_worker_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_shuddering_fungus'); # :fungusgrove_shuddering_fungus_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_sir_karzad'); # :fungusgrove_sir_karzad_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_south_atk_man_one'); # :fungusgrove_south_atk_man_one_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_south_atk_man_three'); # :fungusgrove_south_atk_man_three_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_south_atk_man_two'); # :fungusgrove_south_atk_man_two_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_south_death_ear'); # :fungusgrove_south_death_ear_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_south_raid_manager'); # :fungusgrove_south_raid_manager_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_thar_anton'); # :fungusgrove_thar_anton_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_thom_the_fish'); # :fungusgrove_thom_the_fish_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_thorgi_mullet'); # :fungusgrove_thorgi_mullet_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_trader_snugrut'); # :fungusgrove_trader_snugrut_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_tziik_underbulk'); # :fungusgrove_tziik_underbulk_lt:
INSERT INTO loottable(name) VALUES('fungusgrove_warlord_tkkiktthik'); # :fungusgrove_warlord_tkkiktthik_lt:
