INSERT INTO loottable(name) VALUES('grimling_arcanist_ukigit'); # :grimling_arcanist_ukigit_lt:
INSERT INTO loottable(name) VALUES('grimling_avisiris'); # :grimling_avisiris_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_warblood'); # :grimling_a_grimling_warblood_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_warfiend'); # :grimling_a_grimling_warfiend_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_warmaster'); # :grimling_a_grimling_warmaster_lt:
INSERT INTO loottable(name) VALUES('grimling_a_spawner'); # :grimling_a_spawner_lt:
INSERT INTO loottable(name) VALUES('grimling_chazzems_warder'); # :grimling_chazzems_warder_lt:
INSERT INTO loottable(name) VALUES('grimling_grimling_colonel'); # :grimling_grimling_colonel_lt:
INSERT INTO loottable(name) VALUES('grimling_grimling_counter'); # :grimling_grimling_counter_lt:
INSERT INTO loottable(name) VALUES('grimling_grimling_general'); # :grimling_grimling_general_lt:
INSERT INTO loottable(name) VALUES('grimling_raidman'); # :grimling_raidman_lt:
INSERT INTO loottable(name) VALUES('grimling_raidman45x'); # :grimling_raidman45x_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5l'); # :grimling_timer5l_lt:
INSERT INTO loottable(name) VALUES('grimling_agent_tiesh'); # :grimling_agent_tiesh_lt:
INSERT INTO loottable(name) VALUES('grimling_antispawnman'); # :grimling_antispawnman_lt:
INSERT INTO loottable(name) VALUES('grimling_an_exiled_priest'); # :grimling_an_exiled_priest_lt:
INSERT INTO loottable(name) VALUES('grimling_an_imprisoned_grimling'); # :grimling_an_imprisoned_grimling_lt:
INSERT INTO loottable(name) VALUES('grimling_an_outcast_shaman'); # :grimling_an_outcast_shaman_lt:
INSERT INTO loottable(name) VALUES('grimling_an_owlbear_bloodspiller'); # :grimling_an_owlbear_bloodspiller_lt:
INSERT INTO loottable(name) VALUES('grimling_an_owlbear_grappler'); # :grimling_an_owlbear_grappler_lt:
INSERT INTO loottable(name) VALUES('grimling_an_owlbear_razorbeak'); # :grimling_an_owlbear_razorbeak_lt:
INSERT INTO loottable(name) VALUES('grimling_arcanist_ukigit'); # :grimling_arcanist_ukigit_lt:
INSERT INTO loottable(name) VALUES('grimling_a_bandit'); # :grimling_a_bandit_lt:
INSERT INTO loottable(name) VALUES('grimling_a_beaming_grimling'); # :grimling_a_beaming_grimling_lt:
INSERT INTO loottable(name) VALUES('grimling_a_coin_courier'); # :grimling_a_coin_courier_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_blacksoul'); # :grimling_a_grimling_blacksoul_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_bloodguard'); # :grimling_a_grimling_bloodguard_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_bloodreaver'); # :grimling_a_grimling_bloodreaver_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_bonecracker'); # :grimling_a_grimling_bonecracker_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_cadaverist'); # :grimling_a_grimling_cadaverist_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_corpsecaller'); # :grimling_a_grimling_corpsecaller_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_dartspitter'); # :grimling_a_grimling_dartspitter_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_deathbringer'); # :grimling_a_grimling_deathbringer_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_dedicant'); # :grimling_a_grimling_dedicant_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_dreamspinner'); # :grimling_a_grimling_dreamspinner_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_elder_guard'); # :grimling_a_grimling_elder_guard_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_fighter'); # :grimling_a_grimling_fighter_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_fleshsoother'); # :grimling_a_grimling_fleshsoother_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_grunt'); # :grimling_a_grimling_grunt_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_gruntling'); # :grimling_a_grimling_gruntling_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_guard'); # :grimling_a_grimling_guard_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_guardian'); # :grimling_a_grimling_guardian_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_herbalist'); # :grimling_a_grimling_herbalist_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_manacrafter'); # :grimling_a_grimling_manacrafter_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_manawielder'); # :grimling_a_grimling_manawielder_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_marauder'); # :grimling_a_grimling_marauder_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_metalworker'); # :grimling_a_grimling_metalworker_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_miner'); # :grimling_a_grimling_miner_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_nightknife'); # :grimling_a_grimling_nightknife_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_painsoother'); # :grimling_a_grimling_painsoother_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_pickpocket'); # :grimling_a_grimling_pickpocket_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_prophet'); # :grimling_a_grimling_prophet_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_protector'); # :grimling_a_grimling_protector_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_scout'); # :grimling_a_grimling_scout_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_sentry'); # :grimling_a_grimling_sentry_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_skirmisher'); # :grimling_a_grimling_skirmisher_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_skullcracker'); # :grimling_a_grimling_skullcracker_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_skullsplitter'); # :grimling_a_grimling_skullsplitter_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_sorceress'); # :grimling_a_grimling_sorceress_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_soulsoother'); # :grimling_a_grimling_soulsoother_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_soulstealer'); # :grimling_a_grimling_soulstealer_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_spinetapper'); # :grimling_a_grimling_spinetapper_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_spiritcaller'); # :grimling_a_grimling_spiritcaller_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_spiritchanter'); # :grimling_a_grimling_spiritchanter_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_spiritslaver'); # :grimling_a_grimling_spiritslaver_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_twistblade'); # :grimling_a_grimling_twistblade_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_veteran'); # :grimling_a_grimling_veteran_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_warblood'); # :grimling_a_grimling_warblood_lt:
INSERT INTO loottable(name) VALUES('grimling_a_grimling_warrior'); # :grimling_a_grimling_warrior_lt:
INSERT INTO loottable(name) VALUES('grimling_a_legendary_grimling_twin'); # :grimling_a_legendary_grimling_twin_lt:
INSERT INTO loottable(name) VALUES('grimling_a_possessed_grimling'); # :grimling_a_possessed_grimling_lt:
INSERT INTO loottable(name) VALUES('grimling_a_raspy_grimling'); # :grimling_a_raspy_grimling_lt:
INSERT INTO loottable(name) VALUES('grimling_a_reanimated_grimling'); # :grimling_a_reanimated_grimling_lt:
INSERT INTO loottable(name) VALUES('grimling_a_rockhopper_scavenger'); # :grimling_a_rockhopper_scavenger_lt:
INSERT INTO loottable(name) VALUES('grimling_a_sonic_battlehound'); # :grimling_a_sonic_battlehound_lt:
INSERT INTO loottable(name) VALUES('grimling_a_sonic_mangler'); # :grimling_a_sonic_mangler_lt:
INSERT INTO loottable(name) VALUES('grimling_a_sonic_stalker'); # :grimling_a_sonic_stalker_lt:
INSERT INTO loottable(name) VALUES('grimling_a_thief'); # :grimling_a_thief_lt:
INSERT INTO loottable(name) VALUES('grimling_a_thug'); # :grimling_a_thug_lt:
INSERT INTO loottable(name) VALUES('grimling_a_vah_shir_healer'); # :grimling_a_vah_shir_healer_lt:
INSERT INTO loottable(name) VALUES('grimling_a_vah_shir_officer'); # :grimling_a_vah_shir_officer_lt:
INSERT INTO loottable(name) VALUES('grimling_a_vah_shir_soldier'); # :grimling_a_vah_shir_soldier_lt:
INSERT INTO loottable(name) VALUES('grimling_a_vah_shir_trooper'); # :grimling_a_vah_shir_trooper_lt:
INSERT INTO loottable(name) VALUES('grimling_a_watchwolf'); # :grimling_a_watchwolf_lt:
INSERT INTO loottable(name) VALUES('grimling_banker_hanarah'); # :grimling_banker_hanarah_lt:
INSERT INTO loottable(name) VALUES('grimling_bookkeeper_leaha'); # :grimling_bookkeeper_leaha_lt:
INSERT INTO loottable(name) VALUES('grimling_campeighttrack'); # :grimling_campeighttrack_lt:
INSERT INTO loottable(name) VALUES('grimling_campfivetrack'); # :grimling_campfivetrack_lt:
INSERT INTO loottable(name) VALUES('grimling_campfourtrack'); # :grimling_campfourtrack_lt:
INSERT INTO loottable(name) VALUES('grimling_campninetrack'); # :grimling_campninetrack_lt:
INSERT INTO loottable(name) VALUES('grimling_camponetrack'); # :grimling_camponetrack_lt:
INSERT INTO loottable(name) VALUES('grimling_campseventrack'); # :grimling_campseventrack_lt:
INSERT INTO loottable(name) VALUES('grimling_campsixtrack'); # :grimling_campsixtrack_lt:
INSERT INTO loottable(name) VALUES('grimling_camptentrack'); # :grimling_camptentrack_lt:
INSERT INTO loottable(name) VALUES('grimling_campthreetrack'); # :grimling_campthreetrack_lt:
INSERT INTO loottable(name) VALUES('grimling_camptwotrack'); # :grimling_camptwotrack_lt:
INSERT INTO loottable(name) VALUES('grimling_captain_darznel'); # :grimling_captain_darznel_lt:
INSERT INTO loottable(name) VALUES('grimling_captain_necin'); # :grimling_captain_necin_lt:
INSERT INTO loottable(name) VALUES('grimling_delayspawnman'); # :grimling_delayspawnman_lt:
INSERT INTO loottable(name) VALUES('grimling_flagman'); # :grimling_flagman_lt:
INSERT INTO loottable(name) VALUES('grimling_general_staginar'); # :grimling_general_staginar_lt:
INSERT INTO loottable(name) VALUES('grimling_governoreight'); # :grimling_governoreight_lt:
INSERT INTO loottable(name) VALUES('grimling_governorfive'); # :grimling_governorfive_lt:
INSERT INTO loottable(name) VALUES('grimling_governorfour'); # :grimling_governorfour_lt:
INSERT INTO loottable(name) VALUES('grimling_governormines'); # :grimling_governormines_lt:
INSERT INTO loottable(name) VALUES('grimling_governornine'); # :grimling_governornine_lt:
INSERT INTO loottable(name) VALUES('grimling_governorone'); # :grimling_governorone_lt:
INSERT INTO loottable(name) VALUES('grimling_governoroutpost'); # :grimling_governoroutpost_lt:
INSERT INTO loottable(name) VALUES('grimling_governorseven'); # :grimling_governorseven_lt:
INSERT INTO loottable(name) VALUES('grimling_governorsix'); # :grimling_governorsix_lt:
INSERT INTO loottable(name) VALUES('grimling_governorten'); # :grimling_governorten_lt:
INSERT INTO loottable(name) VALUES('grimling_governorthree'); # :grimling_governorthree_lt:
INSERT INTO loottable(name) VALUES('grimling_governortwo'); # :grimling_governortwo_lt:
INSERT INTO loottable(name) VALUES('grimling_int10a'); # :grimling_int10a_lt:
INSERT INTO loottable(name) VALUES('grimling_int10b'); # :grimling_int10b_lt:
INSERT INTO loottable(name) VALUES('grimling_int10c'); # :grimling_int10c_lt:
INSERT INTO loottable(name) VALUES('grimling_int10d'); # :grimling_int10d_lt:
INSERT INTO loottable(name) VALUES('grimling_int11a'); # :grimling_int11a_lt:
INSERT INTO loottable(name) VALUES('grimling_int11b'); # :grimling_int11b_lt:
INSERT INTO loottable(name) VALUES('grimling_int11c'); # :grimling_int11c_lt:
INSERT INTO loottable(name) VALUES('grimling_int11d'); # :grimling_int11d_lt:
INSERT INTO loottable(name) VALUES('grimling_int11e'); # :grimling_int11e_lt:
INSERT INTO loottable(name) VALUES('grimling_int12a'); # :grimling_int12a_lt:
INSERT INTO loottable(name) VALUES('grimling_int12b'); # :grimling_int12b_lt:
INSERT INTO loottable(name) VALUES('grimling_int12c'); # :grimling_int12c_lt:
INSERT INTO loottable(name) VALUES('grimling_int12d'); # :grimling_int12d_lt:
INSERT INTO loottable(name) VALUES('grimling_int12e'); # :grimling_int12e_lt:
INSERT INTO loottable(name) VALUES('grimling_int1a'); # :grimling_int1a_lt:
INSERT INTO loottable(name) VALUES('grimling_int1b'); # :grimling_int1b_lt:
INSERT INTO loottable(name) VALUES('grimling_int1c'); # :grimling_int1c_lt:
INSERT INTO loottable(name) VALUES('grimling_int1d'); # :grimling_int1d_lt:
INSERT INTO loottable(name) VALUES('grimling_int1e'); # :grimling_int1e_lt:
INSERT INTO loottable(name) VALUES('grimling_int2a'); # :grimling_int2a_lt:
INSERT INTO loottable(name) VALUES('grimling_int2b'); # :grimling_int2b_lt:
INSERT INTO loottable(name) VALUES('grimling_int2c'); # :grimling_int2c_lt:
INSERT INTO loottable(name) VALUES('grimling_int2d'); # :grimling_int2d_lt:
INSERT INTO loottable(name) VALUES('grimling_int3a'); # :grimling_int3a_lt:
INSERT INTO loottable(name) VALUES('grimling_int3b'); # :grimling_int3b_lt:
INSERT INTO loottable(name) VALUES('grimling_int3c'); # :grimling_int3c_lt:
INSERT INTO loottable(name) VALUES('grimling_int3d'); # :grimling_int3d_lt:
INSERT INTO loottable(name) VALUES('grimling_int3e'); # :grimling_int3e_lt:
INSERT INTO loottable(name) VALUES('grimling_int4a'); # :grimling_int4a_lt:
INSERT INTO loottable(name) VALUES('grimling_int4b'); # :grimling_int4b_lt:
INSERT INTO loottable(name) VALUES('grimling_int4c'); # :grimling_int4c_lt:
INSERT INTO loottable(name) VALUES('grimling_int4d'); # :grimling_int4d_lt:
INSERT INTO loottable(name) VALUES('grimling_int4e'); # :grimling_int4e_lt:
INSERT INTO loottable(name) VALUES('grimling_int5a'); # :grimling_int5a_lt:
INSERT INTO loottable(name) VALUES('grimling_int5b'); # :grimling_int5b_lt:
INSERT INTO loottable(name) VALUES('grimling_int5c'); # :grimling_int5c_lt:
INSERT INTO loottable(name) VALUES('grimling_int5d'); # :grimling_int5d_lt:
INSERT INTO loottable(name) VALUES('grimling_int5e'); # :grimling_int5e_lt:
INSERT INTO loottable(name) VALUES('grimling_int6a'); # :grimling_int6a_lt:
INSERT INTO loottable(name) VALUES('grimling_int6b'); # :grimling_int6b_lt:
INSERT INTO loottable(name) VALUES('grimling_int6c'); # :grimling_int6c_lt:
INSERT INTO loottable(name) VALUES('grimling_int6d'); # :grimling_int6d_lt:
INSERT INTO loottable(name) VALUES('grimling_int6e'); # :grimling_int6e_lt:
INSERT INTO loottable(name) VALUES('grimling_int7a'); # :grimling_int7a_lt:
INSERT INTO loottable(name) VALUES('grimling_int7b'); # :grimling_int7b_lt:
INSERT INTO loottable(name) VALUES('grimling_int7c'); # :grimling_int7c_lt:
INSERT INTO loottable(name) VALUES('grimling_int7d'); # :grimling_int7d_lt:
INSERT INTO loottable(name) VALUES('grimling_int7e'); # :grimling_int7e_lt:
INSERT INTO loottable(name) VALUES('grimling_int8a'); # :grimling_int8a_lt:
INSERT INTO loottable(name) VALUES('grimling_int8b'); # :grimling_int8b_lt:
INSERT INTO loottable(name) VALUES('grimling_int8c'); # :grimling_int8c_lt:
INSERT INTO loottable(name) VALUES('grimling_int8d'); # :grimling_int8d_lt:
INSERT INTO loottable(name) VALUES('grimling_int9a'); # :grimling_int9a_lt:
INSERT INTO loottable(name) VALUES('grimling_int9b'); # :grimling_int9b_lt:
INSERT INTO loottable(name) VALUES('grimling_int9c'); # :grimling_int9c_lt:
INSERT INTO loottable(name) VALUES('grimling_int9d'); # :grimling_int9d_lt:
INSERT INTO loottable(name) VALUES('grimling_int9e'); # :grimling_int9e_lt:
INSERT INTO loottable(name) VALUES('grimling_lieutenant_venris'); # :grimling_lieutenant_venris_lt:
INSERT INTO loottable(name) VALUES('grimling_major_ehmdish'); # :grimling_major_ehmdish_lt:
INSERT INTO loottable(name) VALUES('grimling_merchant_hamarr'); # :grimling_merchant_hamarr_lt:
INSERT INTO loottable(name) VALUES('grimling_overseer_gizgargank'); # :grimling_overseer_gizgargank_lt:
INSERT INTO loottable(name) VALUES('grimling_overseer_gnerpokkel'); # :grimling_overseer_gnerpokkel_lt:
INSERT INTO loottable(name) VALUES('grimling_popmaint'); # :grimling_popmaint_lt:
INSERT INTO loottable(name) VALUES('grimling_prophet_grikplag'); # :grimling_prophet_grikplag_lt:
INSERT INTO loottable(name) VALUES('grimling_prospector_keykis'); # :grimling_prospector_keykis_lt:
INSERT INTO loottable(name) VALUES('grimling_rakshasa_karwoaro'); # :grimling_rakshasa_karwoaro_lt:
INSERT INTO loottable(name) VALUES('grimling_royal_khala_dun'); # :grimling_royal_khala_dun_lt:
INSERT INTO loottable(name) VALUES('grimling_scout_danarin'); # :grimling_scout_danarin_lt:
INSERT INTO loottable(name) VALUES('grimling_scout_derrin'); # :grimling_scout_derrin_lt:
INSERT INTO loottable(name) VALUES('grimling_scout_gergil'); # :grimling_scout_gergil_lt:
INSERT INTO loottable(name) VALUES('grimling_scout_husman'); # :grimling_scout_husman_lt:
INSERT INTO loottable(name) VALUES('grimling_sergeant_cursah'); # :grimling_sergeant_cursah_lt:
INSERT INTO loottable(name) VALUES('grimling_sergeant_tidwah'); # :grimling_sergeant_tidwah_lt:
INSERT INTO loottable(name) VALUES('grimling_shopkeeper_chirrin'); # :grimling_shopkeeper_chirrin_lt:
INSERT INTO loottable(name) VALUES('grimling_slaveeight'); # :grimling_slaveeight_lt:
INSERT INTO loottable(name) VALUES('grimling_slaveeighteen'); # :grimling_slaveeighteen_lt:
INSERT INTO loottable(name) VALUES('grimling_slaveeleven'); # :grimling_slaveeleven_lt:
INSERT INTO loottable(name) VALUES('grimling_slavefifteen'); # :grimling_slavefifteen_lt:
INSERT INTO loottable(name) VALUES('grimling_slavefive'); # :grimling_slavefive_lt:
INSERT INTO loottable(name) VALUES('grimling_slaveforty'); # :grimling_slaveforty_lt:
INSERT INTO loottable(name) VALUES('grimling_slavefour'); # :grimling_slavefour_lt:
INSERT INTO loottable(name) VALUES('grimling_slavefourteen'); # :grimling_slavefourteen_lt:
INSERT INTO loottable(name) VALUES('grimling_slavenine'); # :grimling_slavenine_lt:
INSERT INTO loottable(name) VALUES('grimling_slavenineteen'); # :grimling_slavenineteen_lt:
INSERT INTO loottable(name) VALUES('grimling_slaveone'); # :grimling_slaveone_lt:
INSERT INTO loottable(name) VALUES('grimling_slaveseven'); # :grimling_slaveseven_lt:
INSERT INTO loottable(name) VALUES('grimling_slaveseventeen'); # :grimling_slaveseventeen_lt:
INSERT INTO loottable(name) VALUES('grimling_slavesix'); # :grimling_slavesix_lt:
INSERT INTO loottable(name) VALUES('grimling_slavesixteen'); # :grimling_slavesixteen_lt:
INSERT INTO loottable(name) VALUES('grimling_slaveten'); # :grimling_slaveten_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirteen'); # :grimling_slavethirteen_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirty'); # :grimling_slavethirty_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirtyeight'); # :grimling_slavethirtyeight_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirtyfive'); # :grimling_slavethirtyfive_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirtyfour'); # :grimling_slavethirtyfour_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirtynine'); # :grimling_slavethirtynine_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirtyone'); # :grimling_slavethirtyone_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirtyseven'); # :grimling_slavethirtyseven_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirtysix'); # :grimling_slavethirtysix_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirtythree'); # :grimling_slavethirtythree_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethirtytwo'); # :grimling_slavethirtytwo_lt:
INSERT INTO loottable(name) VALUES('grimling_slavethree'); # :grimling_slavethree_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwelve'); # :grimling_slavetwelve_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwenty'); # :grimling_slavetwenty_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwentyeight'); # :grimling_slavetwentyeight_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwentyfive'); # :grimling_slavetwentyfive_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwentyfour'); # :grimling_slavetwentyfour_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwentynine'); # :grimling_slavetwentynine_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwentyone'); # :grimling_slavetwentyone_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwentyseven'); # :grimling_slavetwentyseven_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwentysix'); # :grimling_slavetwentysix_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwentythree'); # :grimling_slavetwentythree_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwentytwo'); # :grimling_slavetwentytwo_lt:
INSERT INTO loottable(name) VALUES('grimling_slavetwo'); # :grimling_slavetwo_lt:
INSERT INTO loottable(name) VALUES('grimling_sorceress_gnildaria'); # :grimling_sorceress_gnildaria_lt:
INSERT INTO loottable(name) VALUES('grimling_spiritist_darah'); # :grimling_spiritist_darah_lt:
INSERT INTO loottable(name) VALUES('grimling_spiritist_roleko'); # :grimling_spiritist_roleko_lt:
INSERT INTO loottable(name) VALUES('grimling_spiritmaster_ugreth'); # :grimling_spiritmaster_ugreth_lt:
INSERT INTO loottable(name) VALUES('grimling_spymaster_gephes'); # :grimling_spymaster_gephes_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5a'); # :grimling_timer5a_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5b'); # :grimling_timer5b_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5c'); # :grimling_timer5c_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5e'); # :grimling_timer5e_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5f'); # :grimling_timer5f_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5g'); # :grimling_timer5g_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5h'); # :grimling_timer5h_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5i'); # :grimling_timer5i_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5j'); # :grimling_timer5j_lt:
INSERT INTO loottable(name) VALUES('grimling_timer5k'); # :grimling_timer5k_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6a'); # :grimling_timer6a_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6b'); # :grimling_timer6b_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6c'); # :grimling_timer6c_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6d'); # :grimling_timer6d_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6e'); # :grimling_timer6e_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6f'); # :grimling_timer6f_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6g'); # :grimling_timer6g_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6h'); # :grimling_timer6h_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6i'); # :grimling_timer6i_lt:
INSERT INTO loottable(name) VALUES('grimling_timer6j'); # :grimling_timer6j_lt:
INSERT INTO loottable(name) VALUES('grimling_timerd'); # :grimling_timerd_lt:
INSERT INTO loottable(name) VALUES('grimling_timerl'); # :grimling_timerl_lt:
INSERT INTO loottable(name) VALUES('grimling_timerm'); # :grimling_timerm_lt:
INSERT INTO loottable(name) VALUES('grimling_veteran_cullin'); # :grimling_veteran_cullin_lt:
INSERT INTO loottable(name) VALUES('grimling_veteran_darznel'); # :grimling_veteran_darznel_lt:
INSERT INTO loottable(name) VALUES('grimling_veteran_vadrel'); # :grimling_veteran_vadrel_lt:
