INSERT INTO loottable(name) VALUES('katta_arbogast'); # :katta_arbogast_lt:
INSERT INTO loottable(name) VALUES('katta_autarkic_lord_sfarosh'); # :katta_autarkic_lord_sfarosh_lt:
INSERT INTO loottable(name) VALUES('katta_a_coterie_servant'); # :katta_a_coterie_servant_lt:
INSERT INTO loottable(name) VALUES('katta_a_coterie__servant'); # :katta_a_coterie__servant_lt:
INSERT INTO loottable(name) VALUES('katta_a_dust_bunny'); # :katta_a_dust_bunny_lt:
INSERT INTO loottable(name) VALUES('katta_a_tortured_abomination'); # :katta_a_tortured_abomination_lt:
INSERT INTO loottable(name) VALUES('katta_condor'); # :katta_condor_lt:
INSERT INTO loottable(name) VALUES('katta_eeaxizal'); # :katta_eeaxizal_lt:
INSERT INTO loottable(name) VALUES('katta_gerplazix'); # :katta_gerplazix_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_jak_masric'); # :katta_incantator_jak_masric_lt:
INSERT INTO loottable(name) VALUES('katta_invis_spectre_trigger'); # :katta_invis_spectre_trigger_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire'); # :katta_legionnaire_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_claudius'); # :katta_legionnaire_claudius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_claudius_'); # :katta_legionnaire_claudius__lt:
INSERT INTO loottable(name) VALUES('katta_magus_conlegium_trigger'); # :katta_magus_conlegium_trigger_lt:
INSERT INTO loottable(name) VALUES('katta_miller'); # :katta_miller_lt:
INSERT INTO loottable(name) VALUES('katta_nathyn_illuminious'); # :katta_nathyn_illuminious_lt:
INSERT INTO loottable(name) VALUES('katta_praecantor_selis_dawneyes'); # :katta_praecantor_selis_dawneyes_lt:
INSERT INTO loottable(name) VALUES('katta_rett_jimmins'); # :katta_rett_jimmins_lt:
INSERT INTO loottable(name) VALUES('katta_ryazziax'); # :katta_ryazziax_lt:
INSERT INTO loottable(name) VALUES('katta_sasha_aliquin'); # :katta_sasha_aliquin_lt:
INSERT INTO loottable(name) VALUES('katta_theurgus_ajeea_polaja'); # :katta_theurgus_ajeea_polaja_lt:
INSERT INTO loottable(name) VALUES('katta_tvan_gurrish'); # :katta_tvan_gurrish_lt:
INSERT INTO loottable(name) VALUES('katta_vahn'); # :katta_vahn_lt:
INSERT INTO loottable(name) VALUES('katta_vamp_infiltrator_ph'); # :katta_vamp_infiltrator_ph_lt:
INSERT INTO loottable(name) VALUES('katta_xaxxizilliaz'); # :katta_xaxxizilliaz_lt:
INSERT INTO loottable(name) VALUES('katta_xylezroz'); # :katta_xylezroz_lt:
INSERT INTO loottable(name) VALUES('katta_zyriazil'); # :katta_zyriazil_lt:
INSERT INTO loottable(name) VALUES('katta_aerin_kvekn'); # :katta_aerin_kvekn_lt:
INSERT INTO loottable(name) VALUES('katta_aliara_galestra'); # :katta_aliara_galestra_lt:
INSERT INTO loottable(name) VALUES('katta_an_autarkic_umbrage_shade'); # :katta_an_autarkic_umbrage_shade_lt:
INSERT INTO loottable(name) VALUES('katta_an_imprisoned_shade'); # :katta_an_imprisoned_shade_lt:
INSERT INTO loottable(name) VALUES('katta_an_invis_spawner'); # :katta_an_invis_spawner_lt:
INSERT INTO loottable(name) VALUES('katta_arabella_augustleaf'); # :katta_arabella_augustleaf_lt:
INSERT INTO loottable(name) VALUES('katta_arbogast'); # :katta_arbogast_lt:
INSERT INTO loottable(name) VALUES('katta_arialestra_dionicas'); # :katta_arialestra_dionicas_lt:
INSERT INTO loottable(name) VALUES('katta_ashen_remains'); # :katta_ashen_remains_lt:
INSERT INTO loottable(name) VALUES('katta_autarkic_lord_sfarosh'); # :katta_autarkic_lord_sfarosh_lt:
INSERT INTO loottable(name) VALUES('katta_avir_sterbla'); # :katta_avir_sterbla_lt:
INSERT INTO loottable(name) VALUES('katta_a_bell'); # :katta_a_bell_lt:
INSERT INTO loottable(name) VALUES('katta_a_coterie_assassin'); # :katta_a_coterie_assassin_lt:
INSERT INTO loottable(name) VALUES('katta_a_gargoyle_custodus'); # :katta_a_gargoyle_custodus_lt:
INSERT INTO loottable(name) VALUES('katta_a_ghastly_apparition'); # :katta_a_ghastly_apparition_lt:
INSERT INTO loottable(name) VALUES('katta_a_ghost_spawner'); # :katta_a_ghost_spawner_lt:
INSERT INTO loottable(name) VALUES('katta_a_glyph_covered_corpse'); # :katta_a_glyph_covered_corpse_lt:
INSERT INTO loottable(name) VALUES('katta_a_guard_sonic_wolf'); # :katta_a_guard_sonic_wolf_lt:
INSERT INTO loottable(name) VALUES('katta_a_locked_chest'); # :katta_a_locked_chest_lt:
INSERT INTO loottable(name) VALUES('katta_a_magus_protectorate'); # :katta_a_magus_protectorate_lt:
INSERT INTO loottable(name) VALUES('katta_a_molded_skeleton'); # :katta_a_molded_skeleton_lt:
INSERT INTO loottable(name) VALUES('katta_a_mouse'); # :katta_a_mouse_lt:
INSERT INTO loottable(name) VALUES('katta_a_muddy_corpse'); # :katta_a_muddy_corpse_lt:
INSERT INTO loottable(name) VALUES('katta_a_reanimated_corpse'); # :katta_a_reanimated_corpse_lt:
INSERT INTO loottable(name) VALUES('katta_a_reanimated_vah_shir'); # :katta_a_reanimated_vah_shir_lt:
INSERT INTO loottable(name) VALUES('katta_a_vah_shir_courier'); # :katta_a_vah_shir_courier_lt:
INSERT INTO loottable(name) VALUES('katta_a_wetfang_minnow'); # :katta_a_wetfang_minnow_lt:
INSERT INTO loottable(name) VALUES('katta_a__coterie_servant'); # :katta_a__coterie_servant_lt:
INSERT INTO loottable(name) VALUES('katta_beacon'); # :katta_beacon_lt:
INSERT INTO loottable(name) VALUES('katta_bella_helsin'); # :katta_bella_helsin_lt:
INSERT INTO loottable(name) VALUES('katta_bell_two'); # :katta_bell_two_lt:
INSERT INTO loottable(name) VALUES('katta_berda_granitefist'); # :katta_berda_granitefist_lt:
INSERT INTO loottable(name) VALUES('katta_berk_thurstone'); # :katta_berk_thurstone_lt:
INSERT INTO loottable(name) VALUES('katta_blaylok_geerlok'); # :katta_blaylok_geerlok_lt:
INSERT INTO loottable(name) VALUES('katta_bole_bricktop'); # :katta_bole_bricktop_lt:
INSERT INTO loottable(name) VALUES('katta_borean_soggybeard'); # :katta_borean_soggybeard_lt:
INSERT INTO loottable(name) VALUES('katta_broote_malicus'); # :katta_broote_malicus_lt:
INSERT INTO loottable(name) VALUES('katta_celris_shadetracker'); # :katta_celris_shadetracker_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_allanus'); # :katta_centurion_allanus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_altinus'); # :katta_centurion_altinus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_balk'); # :katta_centurion_balk_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_bartilous'); # :katta_centurion_bartilous_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_bevor'); # :katta_centurion_bevor_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_brutus'); # :katta_centurion_brutus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_ceraticles'); # :katta_centurion_ceraticles_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_cevikor'); # :katta_centurion_cevikor_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_cradolus'); # :katta_centurion_cradolus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_crullick'); # :katta_centurion_crullick_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_dalaction'); # :katta_centurion_dalaction_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_domicus'); # :katta_centurion_domicus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_donactalis'); # :katta_centurion_donactalis_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_ebben'); # :katta_centurion_ebben_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_elnerius'); # :katta_centurion_elnerius_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_engrov'); # :katta_centurion_engrov_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_garicalious'); # :katta_centurion_garicalious_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_gersetor'); # :katta_centurion_gersetor_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_goran'); # :katta_centurion_goran_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_hephas'); # :katta_centurion_hephas_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_hunigon'); # :katta_centurion_hunigon_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_jeracus'); # :katta_centurion_jeracus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_jerek'); # :katta_centurion_jerek_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_korigon'); # :katta_centurion_korigon_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_kroldus'); # :katta_centurion_kroldus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_kromdus'); # :katta_centurion_kromdus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_macivian'); # :katta_centurion_macivian_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_manik'); # :katta_centurion_manik_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_markalis'); # :katta_centurion_markalis_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_maverus'); # :katta_centurion_maverus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_mesoptilus'); # :katta_centurion_mesoptilus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_narser'); # :katta_centurion_narser_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_nezzer'); # :katta_centurion_nezzer_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_pallak'); # :katta_centurion_pallak_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_pythondius'); # :katta_centurion_pythondius_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_queniton'); # :katta_centurion_queniton_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_ralton'); # :katta_centurion_ralton_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_rancoves'); # :katta_centurion_rancoves_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_regorator'); # :katta_centurion_regorator_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_relicor'); # :katta_centurion_relicor_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_renardio'); # :katta_centurion_renardio_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_rutleo'); # :katta_centurion_rutleo_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_samsun'); # :katta_centurion_samsun_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_shanigus'); # :katta_centurion_shanigus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_sorialus'); # :katta_centurion_sorialus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_talekor'); # :katta_centurion_talekor_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_valaric'); # :katta_centurion_valaric_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_valisus'); # :katta_centurion_valisus_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_venctivo'); # :katta_centurion_venctivo_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_vengor'); # :katta_centurion_vengor_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_vericol'); # :katta_centurion_vericol_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_veridious'); # :katta_centurion_veridious_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_xavier'); # :katta_centurion_xavier_lt:
INSERT INTO loottable(name) VALUES('katta_centurion_zeratillion'); # :katta_centurion_zeratillion_lt:
INSERT INTO loottable(name) VALUES('katta_clavius_masric'); # :katta_clavius_masric_lt:
INSERT INTO loottable(name) VALUES('katta_corporal_donfeld'); # :katta_corporal_donfeld_lt:
INSERT INTO loottable(name) VALUES('katta_corporal_kent'); # :katta_corporal_kent_lt:
INSERT INTO loottable(name) VALUES('katta_danika_farcloud'); # :katta_danika_farcloud_lt:
INSERT INTO loottable(name) VALUES('katta_dersino'); # :katta_dersino_lt:
INSERT INTO loottable(name) VALUES('katta_dianna_dilsm'); # :katta_dianna_dilsm_lt:
INSERT INTO loottable(name) VALUES('katta_did'); # :katta_did_lt:
INSERT INTO loottable(name) VALUES('katta_dralin_kvekn'); # :katta_dralin_kvekn_lt:
INSERT INTO loottable(name) VALUES('katta_drenic_garrison'); # :katta_drenic_garrison_lt:
INSERT INTO loottable(name) VALUES('katta_elnerick_augustleaf'); # :katta_elnerick_augustleaf_lt:
INSERT INTO loottable(name) VALUES('katta_erikal_wolfeye'); # :katta_erikal_wolfeye_lt:
INSERT INTO loottable(name) VALUES('katta_erixok_twildbik'); # :katta_erixok_twildbik_lt:
INSERT INTO loottable(name) VALUES('katta_evonna_songslinger'); # :katta_evonna_songslinger_lt:
INSERT INTO loottable(name) VALUES('katta_fallar_grolden'); # :katta_fallar_grolden_lt:
INSERT INTO loottable(name) VALUES('katta_gaerok_rednose'); # :katta_gaerok_rednose_lt:
INSERT INTO loottable(name) VALUES('katta_galren_fuzzytoes'); # :katta_galren_fuzzytoes_lt:
INSERT INTO loottable(name) VALUES('katta_georgette_dawneyes'); # :katta_georgette_dawneyes_lt:
INSERT INTO loottable(name) VALUES('katta_geran_starshiner'); # :katta_geran_starshiner_lt:
INSERT INTO loottable(name) VALUES('katta_gertrude_twiblik'); # :katta_gertrude_twiblik_lt:
INSERT INTO loottable(name) VALUES('katta_glixx_tobbnokcog'); # :katta_glixx_tobbnokcog_lt:
INSERT INTO loottable(name) VALUES('katta_gosek_jerabi'); # :katta_gosek_jerabi_lt:
INSERT INTO loottable(name) VALUES('katta_granic_malicus'); # :katta_granic_malicus_lt:
INSERT INTO loottable(name) VALUES('katta_greta_teralin'); # :katta_greta_teralin_lt:
INSERT INTO loottable(name) VALUES('katta_guard_lennon'); # :katta_guard_lennon_lt:
INSERT INTO loottable(name) VALUES('katta_guard_zimmer'); # :katta_guard_zimmer_lt:
INSERT INTO loottable(name) VALUES('katta_gundal_bronzebrow'); # :katta_gundal_bronzebrow_lt:
INSERT INTO loottable(name) VALUES('katta_harvin_talbson'); # :katta_harvin_talbson_lt:
INSERT INTO loottable(name) VALUES('katta_helga_furrunner'); # :katta_helga_furrunner_lt:
INSERT INTO loottable(name) VALUES('katta_helinya_limerick'); # :katta_helinya_limerick_lt:
INSERT INTO loottable(name) VALUES('katta_heracus_helsin'); # :katta_heracus_helsin_lt:
INSERT INTO loottable(name) VALUES('katta_holin_aeridia'); # :katta_holin_aeridia_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_elza_dilsm'); # :katta_incantator_elza_dilsm_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_gedy_helsin'); # :katta_incantator_gedy_helsin_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_hue_teralin'); # :katta_incantator_hue_teralin_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_jak_masric'); # :katta_incantator_jak_masric_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_jeena_talbson'); # :katta_incantator_jeena_talbson_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_teak_firetree'); # :katta_incantator_teak_firetree_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_toby_lidspin'); # :katta_incantator_toby_lidspin_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_waek_kerrol'); # :katta_incantator_waek_kerrol_lt:
INSERT INTO loottable(name) VALUES('katta_incantator_yaln_dilsm'); # :katta_incantator_yaln_dilsm_lt:
INSERT INTO loottable(name) VALUES('katta_jacob_rutledge'); # :katta_jacob_rutledge_lt:
INSERT INTO loottable(name) VALUES('katta_jarin_lorean'); # :katta_jarin_lorean_lt:
INSERT INTO loottable(name) VALUES('katta_kalin_abanjabi'); # :katta_kalin_abanjabi_lt:
INSERT INTO loottable(name) VALUES('katta_kellari_autumnfall'); # :katta_kellari_autumnfall_lt:
INSERT INTO loottable(name) VALUES('katta_keylara_abanjabi'); # :katta_keylara_abanjabi_lt:
INSERT INTO loottable(name) VALUES('katta_kitty_barleou'); # :katta_kitty_barleou_lt:
INSERT INTO loottable(name) VALUES('katta_klandar_bronzebrow'); # :katta_klandar_bronzebrow_lt:
INSERT INTO loottable(name) VALUES('katta_kroldar_strongarm'); # :katta_kroldar_strongarm_lt:
INSERT INTO loottable(name) VALUES('katta_lathinquestpopper'); # :katta_lathinquestpopper_lt:
INSERT INTO loottable(name) VALUES('katta_lathin_firetree'); # :katta_lathin_firetree_lt:
INSERT INTO loottable(name) VALUES('katta_lcea_katta'); # :katta_lcea_katta_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_abedeb'); # :katta_legionnaire_abedeb_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_agorix'); # :katta_legionnaire_agorix_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_akixok'); # :katta_legionnaire_akixok_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_alivarius'); # :katta_legionnaire_alivarius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_apollonius'); # :katta_legionnaire_apollonius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_aponius'); # :katta_legionnaire_aponius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_apthorus'); # :katta_legionnaire_apthorus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_ardion'); # :katta_legionnaire_ardion_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_arices'); # :katta_legionnaire_arices_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_artemidorus'); # :katta_legionnaire_artemidorus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_atlakices'); # :katta_legionnaire_atlakices_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_avoretes'); # :katta_legionnaire_avoretes_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_axlox'); # :katta_legionnaire_axlox_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_banictus'); # :katta_legionnaire_banictus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_baolk'); # :katta_legionnaire_baolk_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_belisarius'); # :katta_legionnaire_belisarius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_berblug'); # :katta_legionnaire_berblug_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_berplugle'); # :katta_legionnaire_berplugle_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_blokgrim'); # :katta_legionnaire_blokgrim_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_bonosus'); # :katta_legionnaire_bonosus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_broble'); # :katta_legionnaire_broble_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_bromidus'); # :katta_legionnaire_bromidus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_brugnar'); # :katta_legionnaire_brugnar_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_buntop'); # :katta_legionnaire_buntop_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_byronius'); # :katta_legionnaire_byronius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_carinalio'); # :katta_legionnaire_carinalio_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_carsius'); # :katta_legionnaire_carsius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_catonius'); # :katta_legionnaire_catonius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_catullus'); # :katta_legionnaire_catullus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_claudius'); # :katta_legionnaire_claudius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_cobnoggin'); # :katta_legionnaire_cobnoggin_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_cogniker'); # :katta_legionnaire_cogniker_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_cosmus'); # :katta_legionnaire_cosmus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_cresces'); # :katta_legionnaire_cresces_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_dannicus'); # :katta_legionnaire_dannicus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_decmitius'); # :katta_legionnaire_decmitius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_devorialius'); # :katta_legionnaire_devorialius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_diodotus'); # :katta_legionnaire_diodotus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_domrib'); # :katta_legionnaire_domrib_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_doralycus'); # :katta_legionnaire_doralycus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_doreses'); # :katta_legionnaire_doreses_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_dromides'); # :katta_legionnaire_dromides_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_eldopop'); # :katta_legionnaire_eldopop_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_erallic'); # :katta_legionnaire_erallic_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_ericos'); # :katta_legionnaire_ericos_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_flavio'); # :katta_legionnaire_flavio_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_flobbin'); # :katta_legionnaire_flobbin_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_garrok'); # :katta_legionnaire_garrok_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_gilldonicus'); # :katta_legionnaire_gilldonicus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_giovesanes'); # :katta_legionnaire_giovesanes_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_glycon'); # :katta_legionnaire_glycon_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_gorbthar'); # :katta_legionnaire_gorbthar_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_gumpbar'); # :katta_legionnaire_gumpbar_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_hadolar'); # :katta_legionnaire_hadolar_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_hectavio'); # :katta_legionnaire_hectavio_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_heraticus'); # :katta_legionnaire_heraticus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_heratio'); # :katta_legionnaire_heratio_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_hesicalic'); # :katta_legionnaire_hesicalic_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_hesychius'); # :katta_legionnaire_hesychius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_hicesius'); # :katta_legionnaire_hicesius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_hoblle'); # :katta_legionnaire_hoblle_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_holiged'); # :katta_legionnaire_holiged_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_holisus'); # :katta_legionnaire_holisus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_holug'); # :katta_legionnaire_holug_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_hugby'); # :katta_legionnaire_hugby_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_ioces'); # :katta_legionnaire_ioces_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_iustario'); # :katta_legionnaire_iustario_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_iysando'); # :katta_legionnaire_iysando_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_jaypario'); # :katta_legionnaire_jaypario_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_kapericus'); # :katta_legionnaire_kapericus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_klicbang'); # :katta_legionnaire_klicbang_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_koaltok'); # :katta_legionnaire_koaltok_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_korael'); # :katta_legionnaire_korael_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_leemnix'); # :katta_legionnaire_leemnix_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_logoxop'); # :katta_legionnaire_logoxop_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_loxscog'); # :katta_legionnaire_loxscog_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_malicio'); # :katta_legionnaire_malicio_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_micon'); # :katta_legionnaire_micon_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_miconius'); # :katta_legionnaire_miconius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_mixltik'); # :katta_legionnaire_mixltik_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_mordib'); # :katta_legionnaire_mordib_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_nalicario'); # :katta_legionnaire_nalicario_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_neville'); # :katta_legionnaire_neville_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_nicimious'); # :katta_legionnaire_nicimious_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_nimlox'); # :katta_legionnaire_nimlox_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_oridion'); # :katta_legionnaire_oridion_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_orloxip'); # :katta_legionnaire_orloxip_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_orodilius'); # :katta_legionnaire_orodilius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_orosius'); # :katta_legionnaire_orosius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_ozzmik'); # :katta_legionnaire_ozzmik_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_parethro'); # :katta_legionnaire_parethro_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_paryanos'); # :katta_legionnaire_paryanos_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_peralisor'); # :katta_legionnaire_peralisor_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_perealos'); # :katta_legionnaire_perealos_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_pernicious'); # :katta_legionnaire_pernicious_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_perticon'); # :katta_legionnaire_perticon_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_piscius'); # :katta_legionnaire_piscius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_plixltob'); # :katta_legionnaire_plixltob_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_plocamus'); # :katta_legionnaire_plocamus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_poggle'); # :katta_legionnaire_poggle_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_poliedes'); # :katta_legionnaire_poliedes_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_potalius'); # :katta_legionnaire_potalius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_proddleb'); # :katta_legionnaire_proddleb_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_pudentius'); # :katta_legionnaire_pudentius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_pythion'); # :katta_legionnaire_pythion_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_qalliceus'); # :katta_legionnaire_qalliceus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_quavictus'); # :katta_legionnaire_quavictus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_quentin'); # :katta_legionnaire_quentin_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_rebices'); # :katta_legionnaire_rebices_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_remigius'); # :katta_legionnaire_remigius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_revones'); # :katta_legionnaire_revones_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_rices'); # :katta_legionnaire_rices_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_roarices'); # :katta_legionnaire_roarices_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_rokgar'); # :katta_legionnaire_rokgar_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_rolificus'); # :katta_legionnaire_rolificus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_romaric'); # :katta_legionnaire_romaric_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_rothgan'); # :katta_legionnaire_rothgan_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_rothgivus'); # :katta_legionnaire_rothgivus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_secario'); # :katta_legionnaire_secario_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_sorio'); # :katta_legionnaire_sorio_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_soterides'); # :katta_legionnaire_soterides_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_tarautas'); # :katta_legionnaire_tarautas_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_thorinius'); # :katta_legionnaire_thorinius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_toktix'); # :katta_legionnaire_toktix_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_toralitides'); # :katta_legionnaire_toralitides_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_tribledek'); # :katta_legionnaire_tribledek_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_trikaticus'); # :katta_legionnaire_trikaticus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_tripticus'); # :katta_legionnaire_tripticus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_tweedlib'); # :katta_legionnaire_tweedlib_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_twibleok'); # :katta_legionnaire_twibleok_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_urolic'); # :katta_legionnaire_urolic_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_utilliac'); # :katta_legionnaire_utilliac_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_valesco'); # :katta_legionnaire_valesco_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_vaquiles'); # :katta_legionnaire_vaquiles_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_varioces'); # :katta_legionnaire_varioces_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_vassus'); # :katta_legionnaire_vassus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_veak'); # :katta_legionnaire_veak_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_vendicius'); # :katta_legionnaire_vendicius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_viator'); # :katta_legionnaire_viator_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_vitruvius'); # :katta_legionnaire_vitruvius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_willecius'); # :katta_legionnaire_willecius_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_wundaces'); # :katta_legionnaire_wundaces_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_xaldivious'); # :katta_legionnaire_xaldivious_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_xandilious'); # :katta_legionnaire_xandilious_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_ximbl'); # :katta_legionnaire_ximbl_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_xobok'); # :katta_legionnaire_xobok_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_yabatus'); # :katta_legionnaire_yabatus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_yabbo'); # :katta_legionnaire_yabbo_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_yaelidion'); # :katta_legionnaire_yaelidion_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_yarolok'); # :katta_legionnaire_yarolok_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_yolicus'); # :katta_legionnaire_yolicus_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_zalobnokin'); # :katta_legionnaire_zalobnokin_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_zeboxin'); # :katta_legionnaire_zeboxin_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_zexolicor'); # :katta_legionnaire_zexolicor_lt:
INSERT INTO loottable(name) VALUES('katta_legionnaire_zweeblok'); # :katta_legionnaire_zweeblok_lt:
INSERT INTO loottable(name) VALUES('katta_librarian_ezmerelda'); # :katta_librarian_ezmerelda_lt:
INSERT INTO loottable(name) VALUES('katta_lizsa_barleou'); # :katta_lizsa_barleou_lt:
INSERT INTO loottable(name) VALUES('katta_lyneea_doyle'); # :katta_lyneea_doyle_lt:
INSERT INTO loottable(name) VALUES('katta_mahri_matuya'); # :katta_mahri_matuya_lt:
INSERT INTO loottable(name) VALUES('katta_maralicis_dilsm'); # :katta_maralicis_dilsm_lt:
INSERT INTO loottable(name) VALUES('katta_marda_granitefist'); # :katta_marda_granitefist_lt:
INSERT INTO loottable(name) VALUES('katta_margy_okoyle'); # :katta_margy_okoyle_lt:
INSERT INTO loottable(name) VALUES('katta_maria_whispersong'); # :katta_maria_whispersong_lt:
INSERT INTO loottable(name) VALUES('katta_markil_jurbac'); # :katta_markil_jurbac_lt:
INSERT INTO loottable(name) VALUES('katta_marko_wolfeye'); # :katta_marko_wolfeye_lt:
INSERT INTO loottable(name) VALUES('katta_maryssa_talbson'); # :katta_maryssa_talbson_lt:
INSERT INTO loottable(name) VALUES('katta_mehgyn_garrison'); # :katta_mehgyn_garrison_lt:
INSERT INTO loottable(name) VALUES('katta_melanie_mavroudis'); # :katta_melanie_mavroudis_lt:
INSERT INTO loottable(name) VALUES('katta_melodei_cruzsia'); # :katta_melodei_cruzsia_lt:
INSERT INTO loottable(name) VALUES('katta_mercusius_farcloud'); # :katta_mercusius_farcloud_lt:
INSERT INTO loottable(name) VALUES('katta_mercutius_rutledge'); # :katta_mercutius_rutledge_lt:
INSERT INTO loottable(name) VALUES('katta_miguel_talbson'); # :katta_miguel_talbson_lt:
INSERT INTO loottable(name) VALUES('katta_miller'); # :katta_miller_lt:
INSERT INTO loottable(name) VALUES('katta_monika_helsin'); # :katta_monika_helsin_lt:
INSERT INTO loottable(name) VALUES('katta_morfesh_okoyle'); # :katta_morfesh_okoyle_lt:
INSERT INTO loottable(name) VALUES('katta_nannette_farcloud'); # :katta_nannette_farcloud_lt:
INSERT INTO loottable(name) VALUES('katta_oblivion'); # :katta_oblivion_lt:
INSERT INTO loottable(name) VALUES('katta_olam_polaja'); # :katta_olam_polaja_lt:
INSERT INTO loottable(name) VALUES('katta_phenic_dionicas'); # :katta_phenic_dionicas_lt:
INSERT INTO loottable(name) VALUES('katta_praecantor_dovar_rutledge'); # :katta_praecantor_dovar_rutledge_lt:
INSERT INTO loottable(name) VALUES('katta_praecantor_lisa_kerrol'); # :katta_praecantor_lisa_kerrol_lt:
INSERT INTO loottable(name) VALUES('katta_praecantor_perph_unja'); # :katta_praecantor_perph_unja_lt:
INSERT INTO loottable(name) VALUES('katta_praecantor_selis_dawneyes'); # :katta_praecantor_selis_dawneyes_lt:
INSERT INTO loottable(name) VALUES('katta_praecantor_tes_dawneyes'); # :katta_praecantor_tes_dawneyes_lt:
INSERT INTO loottable(name) VALUES('katta_praecantor_torin_jurbac'); # :katta_praecantor_torin_jurbac_lt:
INSERT INTO loottable(name) VALUES('katta_praecantor_ury_polaja'); # :katta_praecantor_ury_polaja_lt:
INSERT INTO loottable(name) VALUES('katta_praecantor_vesa_farcloud'); # :katta_praecantor_vesa_farcloud_lt:
INSERT INTO loottable(name) VALUES('katta_private_sentinel_frieza'); # :katta_private_sentinel_frieza_lt:
INSERT INTO loottable(name) VALUES('katta_private_sentinel_tozza'); # :katta_private_sentinel_tozza_lt:
INSERT INTO loottable(name) VALUES('katta_raesha_dawneyes'); # :katta_raesha_dawneyes_lt:
INSERT INTO loottable(name) VALUES('katta_raien_talikar'); # :katta_raien_talikar_lt:
INSERT INTO loottable(name) VALUES('katta_rallena_doyle'); # :katta_rallena_doyle_lt:
INSERT INTO loottable(name) VALUES('katta_rallic_aristos'); # :katta_rallic_aristos_lt:
INSERT INTO loottable(name) VALUES('katta_rebecca_wolfeye'); # :katta_rebecca_wolfeye_lt:
INSERT INTO loottable(name) VALUES('katta_rolanda_unja'); # :katta_rolanda_unja_lt:
INSERT INTO loottable(name) VALUES('katta_ronocinv'); # :katta_ronocinv_lt:
INSERT INTO loottable(name) VALUES('katta_roshawna_rhorer'); # :katta_roshawna_rhorer_lt:
INSERT INTO loottable(name) VALUES('katta_rowle_shieldson'); # :katta_rowle_shieldson_lt:
INSERT INTO loottable(name) VALUES('katta_salic_whispersong'); # :katta_salic_whispersong_lt:
INSERT INTO loottable(name) VALUES('katta_saumeem_unja'); # :katta_saumeem_unja_lt:
INSERT INTO loottable(name) VALUES('katta_sellar_mulletune'); # :katta_sellar_mulletune_lt:
INSERT INTO loottable(name) VALUES('katta_sentinel_berdra'); # :katta_sentinel_berdra_lt:
INSERT INTO loottable(name) VALUES('katta_sentinel_fellysa'); # :katta_sentinel_fellysa_lt:
INSERT INTO loottable(name) VALUES('katta_sentinel_helga'); # :katta_sentinel_helga_lt:
INSERT INTO loottable(name) VALUES('katta_sentinel_kerrigan'); # :katta_sentinel_kerrigan_lt:
INSERT INTO loottable(name) VALUES('katta_sentinel_kerry'); # :katta_sentinel_kerry_lt:
INSERT INTO loottable(name) VALUES('katta_sentinel_majandra'); # :katta_sentinel_majandra_lt:
INSERT INTO loottable(name) VALUES('katta_sentinel_mellisy'); # :katta_sentinel_mellisy_lt:
INSERT INTO loottable(name) VALUES('katta_sentinel_yora'); # :katta_sentinel_yora_lt:
INSERT INTO loottable(name) VALUES('katta_shadeeventclock'); # :katta_shadeeventclock_lt:
INSERT INTO loottable(name) VALUES('katta_shara_aristos'); # :katta_shara_aristos_lt:
INSERT INTO loottable(name) VALUES('katta_sharra_okoyle'); # :katta_sharra_okoyle_lt:
INSERT INTO loottable(name) VALUES('katta_shay_aristos'); # :katta_shay_aristos_lt:
INSERT INTO loottable(name) VALUES('katta_shoeon_malicus'); # :katta_shoeon_malicus_lt:
INSERT INTO loottable(name) VALUES('katta_something'); # :katta_something_lt:
INSERT INTO loottable(name) VALUES('katta_sparrow_shadetracker'); # :katta_sparrow_shadetracker_lt:
INSERT INTO loottable(name) VALUES('katta_strange'); # :katta_strange_lt:
INSERT INTO loottable(name) VALUES('katta_suidualc'); # :katta_suidualc_lt:
INSERT INTO loottable(name) VALUES('katta_tack_shieldson'); # :katta_tack_shieldson_lt:
INSERT INTO loottable(name) VALUES('katta_talika_polajian'); # :katta_talika_polajian_lt:
INSERT INTO loottable(name) VALUES('katta_teepa_berrytoe'); # :katta_teepa_berrytoe_lt:
INSERT INTO loottable(name) VALUES('katta_terasol'); # :katta_terasol_lt:
INSERT INTO loottable(name) VALUES('katta_theurgus_ajeea_polaja'); # :katta_theurgus_ajeea_polaja_lt:
INSERT INTO loottable(name) VALUES('katta_theurgus_bella_geerlok'); # :katta_theurgus_bella_geerlok_lt:
INSERT INTO loottable(name) VALUES('katta_theurgus_dala_abanjabi'); # :katta_theurgus_dala_abanjabi_lt:
INSERT INTO loottable(name) VALUES('katta_theurgus_meg_teralin'); # :katta_theurgus_meg_teralin_lt:
INSERT INTO loottable(name) VALUES('katta_theurgus_olius_matuya'); # :katta_theurgus_olius_matuya_lt:
INSERT INTO loottable(name) VALUES('katta_theurgus_ravy_helsin'); # :katta_theurgus_ravy_helsin_lt:
INSERT INTO loottable(name) VALUES('katta_theurgus_talsen_farsky'); # :katta_theurgus_talsen_farsky_lt:
INSERT INTO loottable(name) VALUES('katta_theurgus_zral_aristos'); # :katta_theurgus_zral_aristos_lt:
INSERT INTO loottable(name) VALUES('katta_the_ground'); # :katta_the_ground_lt:
INSERT INTO loottable(name) VALUES('katta_the_smell'); # :katta_the_smell_lt:
INSERT INTO loottable(name) VALUES('katta_the_study'); # :katta_the_study_lt:
INSERT INTO loottable(name) VALUES('katta_tilbok_furrunner'); # :katta_tilbok_furrunner_lt:
INSERT INTO loottable(name) VALUES('katta_tobala_honeyjar'); # :katta_tobala_honeyjar_lt:
INSERT INTO loottable(name) VALUES('katta_toktonn_geerlok'); # :katta_toktonn_geerlok_lt:
INSERT INTO loottable(name) VALUES('katta_triblix_tikbok'); # :katta_triblix_tikbok_lt:
INSERT INTO loottable(name) VALUES('katta_trigger'); # :katta_trigger_lt:
INSERT INTO loottable(name) VALUES('katta_tsuia_matuya'); # :katta_tsuia_matuya_lt:
INSERT INTO loottable(name) VALUES('katta_vanessa_rutledge'); # :katta_vanessa_rutledge_lt:
INSERT INTO loottable(name) VALUES('katta_wendel_starshiner'); # :katta_wendel_starshiner_lt:
INSERT INTO loottable(name) VALUES('katta_wendlock_twiblik'); # :katta_wendlock_twiblik_lt:
INSERT INTO loottable(name) VALUES('katta_yaeorat'); # :katta_yaeorat_lt:
INSERT INTO loottable(name) VALUES('katta_yalnin_kvekn'); # :katta_yalnin_kvekn_lt:
INSERT INTO loottable(name) VALUES('katta_yanni_talbson'); # :katta_yanni_talbson_lt:
INSERT INTO loottable(name) VALUES('katta_yavik_teralin'); # :katta_yavik_teralin_lt:
INSERT INTO loottable(name) VALUES('katta_yazmin_farsky'); # :katta_yazmin_farsky_lt:
INSERT INTO loottable(name) VALUES('katta_yolanda_honeyjar'); # :katta_yolanda_honeyjar_lt:
INSERT INTO loottable(name) VALUES('katta_your_foot'); # :katta_your_foot_lt:
INSERT INTO loottable(name) VALUES('katta_you_hear'); # :katta_you_hear_lt:
INSERT INTO loottable(name) VALUES('katta_you_kick'); # :katta_you_kick_lt:
INSERT INTO loottable(name) VALUES('katta_you_step'); # :katta_you_step_lt:
INSERT INTO loottable(name) VALUES('katta_yurddle_the_caretaker'); # :katta_yurddle_the_caretaker_lt:
INSERT INTO loottable(name) VALUES('katta_zweeblok_tiktokin'); # :katta_zweeblok_tiktokin_lt:
INSERT INTO loottable(name) VALUES('katta_zyleea_geerlok'); # :katta_zyleea_geerlok_lt:
