INSERT INTO loottable(name) VALUES('mseru_an_ancient_zelniak'); # :mseru_an_ancient_zelniak_lt:
INSERT INTO loottable(name) VALUES('mseru_a_giant_lightcrawler'); # :mseru_a_giant_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('mseru_legionnaire_marais'); # :mseru_legionnaire_marais_lt:
INSERT INTO loottable(name) VALUES('mseru_queen_kvaknak'); # :mseru_queen_kvaknak_lt:
INSERT INTO loottable(name) VALUES('mseru_a_crumbling_stonegrabber'); # :mseru_a_crumbling_stonegrabber_lt:
INSERT INTO loottable(name) VALUES('mseru_a_greyhopper'); # :mseru_a_greyhopper_lt:
INSERT INTO loottable(name) VALUES('mseru_a_hand_of_seru'); # :mseru_a_hand_of_seru_lt:
INSERT INTO loottable(name) VALUES('mseru_a_lightcrawler'); # :mseru_a_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('mseru_a_massive_lightcrawler'); # :mseru_a_massive_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('mseru_a_recuso'); # :mseru_a_recuso_lt:
INSERT INTO loottable(name) VALUES('mseru_a_recuso_hunter'); # :mseru_a_recuso_hunter_lt:
INSERT INTO loottable(name) VALUES('mseru_a_recuso_smuggler'); # :mseru_a_recuso_smuggler_lt:
INSERT INTO loottable(name) VALUES('mseru_a_rhino_beetle'); # :mseru_a_rhino_beetle_lt:
INSERT INTO loottable(name) VALUES('mseru_a_rhino_beetle_hatchling'); # :mseru_a_rhino_beetle_hatchling_lt:
INSERT INTO loottable(name) VALUES('mseru_a_stonegrabber'); # :mseru_a_stonegrabber_lt:
INSERT INTO loottable(name) VALUES('mseru_a_weathered_stonegrabber'); # :mseru_a_weathered_stonegrabber_lt:
INSERT INTO loottable(name) VALUES('mseru_a_zelniak_render'); # :mseru_a_zelniak_render_lt:
INSERT INTO loottable(name) VALUES('mseru_a_zelniak_ripper'); # :mseru_a_zelniak_ripper_lt:
INSERT INTO loottable(name) VALUES('mseru_a_zelniak_shredder'); # :mseru_a_zelniak_shredder_lt:
INSERT INTO loottable(name) VALUES('mseru_a_zelniak_tearer'); # :mseru_a_zelniak_tearer_lt:
INSERT INTO loottable(name) VALUES('mseru_gerak_jelin'); # :mseru_gerak_jelin_lt:
INSERT INTO loottable(name) VALUES('mseru_nikfir'); # :mseru_nikfir_lt:
INSERT INTO loottable(name) VALUES('mseru_reothe'); # :mseru_reothe_lt:
INSERT INTO loottable(name) VALUES('mseru_siaram'); # :mseru_siaram_lt:
