(:paludal_noppta_mottun_lt:, :rusty_ld:, 1),
(:paludal_diojb_waksom_lt:, :rusty_ld:, 1),
(:paludal_farlol_duriclo_lt:, :rusty_ld:, 1),
(:paludal_daesorak_steelknuckle_lt:, :rusty_ld:, 1),
(:paludal_overslo_herlsal_lt:, :rusty_ld:, 1),
