INSERT INTO loottable(name) VALUES('scarlet_disciple_of_sun'); # :scarlet_disciple_of_sun_lt:
INSERT INTO loottable(name) VALUES('scarlet_event_starter'); # :scarlet_event_starter_lt:
INSERT INTO loottable(name) VALUES('scarlet_killer_vine'); # :scarlet_killer_vine_lt:
INSERT INTO loottable(name) VALUES('scarlet_kraen_flameweaver'); # :scarlet_kraen_flameweaver_lt:
INSERT INTO loottable(name) VALUES('scarlet_sectoid'); # :scarlet_sectoid_lt:
INSERT INTO loottable(name) VALUES('scarlet_sunlord_wedazi'); # :scarlet_sunlord_wedazi_lt:
INSERT INTO loottable(name) VALUES('scarlet_ambush_trap_trigger'); # :scarlet_ambush_trap_trigger_lt:
INSERT INTO loottable(name) VALUES('scarlet_an_aggressive_rockhopper'); # :scarlet_an_aggressive_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_an_agile_bloodtribe_warrior'); # :scarlet_an_agile_bloodtribe_warrior_lt:
INSERT INTO loottable(name) VALUES('scarlet_an_ancient_sunflower'); # :scarlet_an_ancient_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_an_ancient_sun_revenant'); # :scarlet_an_ancient_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_an_enraptured_fire_warrior'); # :scarlet_an_enraptured_fire_warrior_lt:
INSERT INTO loottable(name) VALUES('scarlet_an_etched_sun_revenant'); # :scarlet_an_etched_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_an_imposing_cheetah'); # :scarlet_an_imposing_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_an_opposed_cheetah'); # :scarlet_an_opposed_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bespectled_grol_baku'); # :scarlet_a_bespectled_grol_baku_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_chanter'); # :scarlet_a_bloodtribe_chanter_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_firetalker'); # :scarlet_a_bloodtribe_firetalker_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_gem_collector'); # :scarlet_a_bloodtribe_gem_collector_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_hopeful'); # :scarlet_a_bloodtribe_hopeful_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_lightwarrior'); # :scarlet_a_bloodtribe_lightwarrior_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_lorekeeper'); # :scarlet_a_bloodtribe_lorekeeper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_martialist'); # :scarlet_a_bloodtribe_martialist_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_ornamentalist'); # :scarlet_a_bloodtribe_ornamentalist_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_protector'); # :scarlet_a_bloodtribe_protector_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_runekeeper'); # :scarlet_a_bloodtribe_runekeeper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_shaman'); # :scarlet_a_bloodtribe_shaman_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_sunworshipper'); # :scarlet_a_bloodtribe_sunworshipper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_warrior'); # :scarlet_a_bloodtribe_warrior_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_bloodtribe_waterkeeper'); # :scarlet_a_bloodtribe_waterkeeper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_braided_sunflower'); # :scarlet_a_braided_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_composed_cheetah'); # :scarlet_a_composed_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_courageous_tro_jeg_invader'); # :scarlet_a_courageous_tro_jeg_invader_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_cursed_sun_revenant'); # :scarlet_a_cursed_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_darkened_sunflower'); # :scarlet_a_darkened_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_darkened_sun_revenant'); # :scarlet_a_darkened_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_darkeyed_sunflower'); # :scarlet_a_darkeyed_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_darkhued_sunflower'); # :scarlet_a_darkhued_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_dark_rockhopper'); # :scarlet_a_dark_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_dull_lightcrawler'); # :scarlet_a_dull_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_ferocious_rockhopper'); # :scarlet_a_ferocious_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_fiery_sun_revenant'); # :scarlet_a_fiery_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_fiery_tro_jeg_invader'); # :scarlet_a_fiery_tro_jeg_invader_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_fire_blossom'); # :scarlet_a_fire_blossom_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_five_toed_tro_jeg_bane'); # :scarlet_a_five_toed_tro_jeg_bane_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_flaming_cheetah'); # :scarlet_a_flaming_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_flowery_cheetah'); # :scarlet_a_flowery_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_frantic_lightcrawler'); # :scarlet_a_frantic_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_frenzied_rockhopper'); # :scarlet_a_frenzied_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_furious_rockhopper'); # :scarlet_a_furious_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_gallant_cheetah'); # :scarlet_a_gallant_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_gigantic_sunflower'); # :scarlet_a_gigantic_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_greater_grol_baku'); # :scarlet_a_greater_grol_baku_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_greedy_bloodtribe_hunter'); # :scarlet_a_greedy_bloodtribe_hunter_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grim_lightcrawler'); # :scarlet_a_grim_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_benefactor'); # :scarlet_a_grol_baku_benefactor_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_bodyguard'); # :scarlet_a_grol_baku_bodyguard_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_defender'); # :scarlet_a_grol_baku_defender_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_engraver'); # :scarlet_a_grol_baku_engraver_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_gemkeeper'); # :scarlet_a_grol_baku_gemkeeper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_geomancer'); # :scarlet_a_grol_baku_geomancer_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_guard'); # :scarlet_a_grol_baku_guard_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_historian'); # :scarlet_a_grol_baku_historian_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_keeper'); # :scarlet_a_grol_baku_keeper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_raider'); # :scarlet_a_grol_baku_raider_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_retainer'); # :scarlet_a_grol_baku_retainer_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_rock_collector'); # :scarlet_a_grol_baku_rock_collector_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_runemaster'); # :scarlet_a_grol_baku_runemaster_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_sculptor'); # :scarlet_a_grol_baku_sculptor_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_seer'); # :scarlet_a_grol_baku_seer_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_sentinel'); # :scarlet_a_grol_baku_sentinel_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_sentry'); # :scarlet_a_grol_baku_sentry_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_shaman'); # :scarlet_a_grol_baku_shaman_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_grol_baku_warder'); # :scarlet_a_grol_baku_warder_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_hardened_grol_baku_sentry'); # :scarlet_a_hardened_grol_baku_sentry_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_hardy_rockhopper'); # :scarlet_a_hardy_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_hearty_sun_revenant'); # :scarlet_a_hearty_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_lightcrawler'); # :scarlet_a_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_lightcrawler_drone'); # :scarlet_a_lightcrawler_drone_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_light_cheetah'); # :scarlet_a_light_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_lively_lightcrawler'); # :scarlet_a_lively_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_malign_lightcrawler'); # :scarlet_a_malign_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_masterful_cheetah'); # :scarlet_a_masterful_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_methodical_cheetah'); # :scarlet_a_methodical_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_mighty_bloodtribe_hunter'); # :scarlet_a_mighty_bloodtribe_hunter_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_mighty_rockhopper'); # :scarlet_a_mighty_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_natural_cheetah'); # :scarlet_a_natural_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_panther_cheetah'); # :scarlet_a_panther_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_pious_sun_revenant'); # :scarlet_a_pious_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_potent_rockhopper'); # :scarlet_a_potent_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_prismatic_lightcrawler'); # :scarlet_a_prismatic_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_prognostic_cheetah'); # :scarlet_a_prognostic_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_raging_rockhopper'); # :scarlet_a_raging_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_raging_sun_revenant'); # :scarlet_a_raging_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_rational_sun_revenant'); # :scarlet_a_rational_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_repulsive_lightcrawler'); # :scarlet_a_repulsive_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_rough_cheetah'); # :scarlet_a_rough_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_savage_lightcrawler'); # :scarlet_a_savage_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_savage_rockhopper'); # :scarlet_a_savage_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_scarlet_cheetah'); # :scarlet_a_scarlet_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_scarlet_rockhopper'); # :scarlet_a_scarlet_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_silvery_sunflower'); # :scarlet_a_silvery_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_sluggish_sunflower'); # :scarlet_a_sluggish_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_stealthy_cheetah'); # :scarlet_a_stealthy_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_stone_cheetah'); # :scarlet_a_stone_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_sunflower'); # :scarlet_a_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_sun_fiend'); # :scarlet_a_sun_fiend_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_sun_reaver'); # :scarlet_a_sun_reaver_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_sun_revenant'); # :scarlet_a_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_sun_revenant_hero'); # :scarlet_a_sun_revenant_hero_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tenacious_lightcrawler'); # :scarlet_a_tenacious_lightcrawler_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_thorny_sunflower'); # :scarlet_a_thorny_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tiger_cheetah'); # :scarlet_a_tiger_cheetah_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tranquil_bloodtribe_hero'); # :scarlet_a_tranquil_bloodtribe_hero_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_augur'); # :scarlet_a_tro_jeg_augur_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_bane'); # :scarlet_a_tro_jeg_bane_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_captor'); # :scarlet_a_tro_jeg_captor_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_carver'); # :scarlet_a_tro_jeg_carver_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_defender'); # :scarlet_a_tro_jeg_defender_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_diviner'); # :scarlet_a_tro_jeg_diviner_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_entertainer'); # :scarlet_a_tro_jeg_entertainer_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_firekeeper'); # :scarlet_a_tro_jeg_firekeeper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_firerider'); # :scarlet_a_tro_jeg_firerider_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_fire_servant'); # :scarlet_a_tro_jeg_fire_servant_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_fire_warder'); # :scarlet_a_tro_jeg_fire_warder_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_fire_worshipper'); # :scarlet_a_tro_jeg_fire_worshipper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_gemcutter'); # :scarlet_a_tro_jeg_gemcutter_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_heathen'); # :scarlet_a_tro_jeg_heathen_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_hooligan'); # :scarlet_a_tro_jeg_hooligan_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_invader'); # :scarlet_a_tro_jeg_invader_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_legionnaire'); # :scarlet_a_tro_jeg_legionnaire_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_rock_collector'); # :scarlet_a_tro_jeg_rock_collector_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_sentinel'); # :scarlet_a_tro_jeg_sentinel_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_sentry'); # :scarlet_a_tro_jeg_sentry_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_shaman'); # :scarlet_a_tro_jeg_shaman_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_soldier'); # :scarlet_a_tro_jeg_soldier_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_spiritward'); # :scarlet_a_tro_jeg_spiritward_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_visionary'); # :scarlet_a_tro_jeg_visionary_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_warrior'); # :scarlet_a_tro_jeg_warrior_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_tro_jeg_watcher'); # :scarlet_a_tro_jeg_watcher_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_archon'); # :scarlet_a_vas_ren_archon_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_bruiser'); # :scarlet_a_vas_ren_bruiser_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_champion'); # :scarlet_a_vas_ren_champion_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_guard'); # :scarlet_a_vas_ren_guard_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_librarian'); # :scarlet_a_vas_ren_librarian_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_nomad'); # :scarlet_a_vas_ren_nomad_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_protector'); # :scarlet_a_vas_ren_protector_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_shaman'); # :scarlet_a_vas_ren_shaman_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_trooper'); # :scarlet_a_vas_ren_trooper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_watermaster'); # :scarlet_a_vas_ren_watermaster_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vas_ren_woodkeeper'); # :scarlet_a_vas_ren_woodkeeper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_vigorous_rockhopper'); # :scarlet_a_vigorous_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_violent_rockhopper'); # :scarlet_a_violent_rockhopper_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_watery_sunflower'); # :scarlet_a_watery_sunflower_lt:
INSERT INTO loottable(name) VALUES('scarlet_a_wooden_sun_revenant'); # :scarlet_a_wooden_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_bloodtribe_agitator'); # :scarlet_bloodtribe_agitator_lt:
INSERT INTO loottable(name) VALUES('scarlet_bloodtribe_ancient'); # :scarlet_bloodtribe_ancient_lt:
INSERT INTO loottable(name) VALUES('scarlet_bloodtribe_bonecollector'); # :scarlet_bloodtribe_bonecollector_lt:
INSERT INTO loottable(name) VALUES('scarlet_bloodtribe_prophet'); # :scarlet_bloodtribe_prophet_lt:
INSERT INTO loottable(name) VALUES('scarlet_bloodtribe_seer'); # :scarlet_bloodtribe_seer_lt:
INSERT INTO loottable(name) VALUES('scarlet_bloodtribe_shaman'); # :scarlet_bloodtribe_shaman_lt:
INSERT INTO loottable(name) VALUES('scarlet_bloodtribe_sneakster'); # :scarlet_bloodtribe_sneakster_lt:
INSERT INTO loottable(name) VALUES('scarlet_bloodtribe_surveryor'); # :scarlet_bloodtribe_surveryor_lt:
INSERT INTO loottable(name) VALUES('scarlet_bloodtribe_wiseman'); # :scarlet_bloodtribe_wiseman_lt:
INSERT INTO loottable(name) VALUES('scarlet_elite_sun_revenant'); # :scarlet_elite_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_emoter_spawner'); # :scarlet_emoter_spawner_lt:
INSERT INTO loottable(name) VALUES('scarlet_high_priest_valon'); # :scarlet_high_priest_valon_lt:
INSERT INTO loottable(name) VALUES('scarlet_invisambtargetable'); # :scarlet_invisambtargetable_lt:
INSERT INTO loottable(name) VALUES('scarlet_jimmic_adle'); # :scarlet_jimmic_adle_lt:
INSERT INTO loottable(name) VALUES('scarlet_knight_of_the_dread_sun'); # :scarlet_knight_of_the_dread_sun_lt:
INSERT INTO loottable(name) VALUES('scarlet_merchantbossspawn'); # :scarlet_merchantbossspawn_lt:
INSERT INTO loottable(name) VALUES('scarlet_newboss'); # :scarlet_newboss_lt:
INSERT INTO loottable(name) VALUES('scarlet_newsubboss'); # :scarlet_newsubboss_lt:
INSERT INTO loottable(name) VALUES('scarlet_newutc'); # :scarlet_newutc_lt:
INSERT INTO loottable(name) VALUES('scarlet_ntbspawner'); # :scarlet_ntbspawner_lt:
INSERT INTO loottable(name) VALUES('scarlet_ntcspawner'); # :scarlet_ntcspawner_lt:
INSERT INTO loottable(name) VALUES('scarlet_possesed_sun_revenant'); # :scarlet_possesed_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_ruinous_sun_revenant'); # :scarlet_ruinous_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('scarlet_sbspawner'); # :scarlet_sbspawner_lt:
INSERT INTO loottable(name) VALUES('scarlet_scarlet_cheetah_gatherer'); # :scarlet_scarlet_cheetah_gatherer_lt:
INSERT INTO loottable(name) VALUES('scarlet_scarlet_cheetah_hunter'); # :scarlet_scarlet_cheetah_hunter_lt:
INSERT INTO loottable(name) VALUES('scarlet_scarlet_cheetah_matriarch'); # :scarlet_scarlet_cheetah_matriarch_lt:
INSERT INTO loottable(name) VALUES('scarlet_subboss_trap_trigger'); # :scarlet_subboss_trap_trigger_lt:
INSERT INTO loottable(name) VALUES('scarlet_sun_revenant_chancellor'); # :scarlet_sun_revenant_chancellor_lt:
INSERT INTO loottable(name) VALUES('scarlet_sun_revenant_desecrator'); # :scarlet_sun_revenant_desecrator_lt:
INSERT INTO loottable(name) VALUES('scarlet_sun_revenant_magistrate'); # :scarlet_sun_revenant_magistrate_lt:
INSERT INTO loottable(name) VALUES('scarlet_sun_revenant_primatus'); # :scarlet_sun_revenant_primatus_lt:
INSERT INTO loottable(name) VALUES('scarlet_sun_revenant_smiter'); # :scarlet_sun_revenant_smiter_lt:
INSERT INTO loottable(name) VALUES('scarlet_sun_revenant_warlock'); # :scarlet_sun_revenant_warlock_lt:
INSERT INTO loottable(name) VALUES('scarlet_the_burning_priest'); # :scarlet_the_burning_priest_lt:
INSERT INTO loottable(name) VALUES('scarlet_the_gem_guardian'); # :scarlet_the_gem_guardian_lt:
