INSERT INTO loottable(name) VALUES('shadowhaven_melina_stalorok'); # :shadowhaven_melina_stalorok_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_palzone'); # :shadowhaven_palzone_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_adept_arnthus'); # :shadowhaven_adept_arnthus_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_adept_delf'); # :shadowhaven_adept_delf_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_adept_paloney'); # :shadowhaven_adept_paloney_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_adept_tirisa'); # :shadowhaven_adept_tirisa_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_adinson_allonode'); # :shadowhaven_adinson_allonode_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_aeksola_faerlonifer'); # :shadowhaven_aeksola_faerlonifer_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_akeral'); # :shadowhaven_akeral_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_albarok'); # :shadowhaven_albarok_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_alexandra'); # :shadowhaven_alexandra_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_alexandriana'); # :shadowhaven_alexandriana_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_aliane_steelknuckle'); # :shadowhaven_aliane_steelknuckle_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_alorienal_takirilso'); # :shadowhaven_alorienal_takirilso_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_alorob_bolrodo'); # :shadowhaven_alorob_bolrodo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_ambassador_balopombo'); # :shadowhaven_ambassador_balopombo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_ambassador_dordak'); # :shadowhaven_ambassador_dordak_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_ambassador_jerlopodix'); # :shadowhaven_ambassador_jerlopodix_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_a_fordel_guard'); # :shadowhaven_a_fordel_guard_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_a_house_watch'); # :shadowhaven_a_house_watch_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_a_pile_of_dirt'); # :shadowhaven_a_pile_of_dirt_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_bailes'); # :shadowhaven_bailes_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_balrolok_haldarano'); # :shadowhaven_balrolok_haldarano_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_banker_heralow'); # :shadowhaven_banker_heralow_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_banker_pansak'); # :shadowhaven_banker_pansak_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_banker_tarson'); # :shadowhaven_banker_tarson_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_bargain_merchant'); # :shadowhaven_bargain_merchant_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_barkeep_prastice'); # :shadowhaven_barkeep_prastice_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_barkeep_veronica'); # :shadowhaven_barkeep_veronica_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_barlotal'); # :shadowhaven_barlotal_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_barmaid_adelina'); # :shadowhaven_barmaid_adelina_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_barotolen'); # :shadowhaven_barotolen_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_bartender_woolf'); # :shadowhaven_bartender_woolf_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_belbie_hildreth'); # :shadowhaven_belbie_hildreth_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_beriol_talorakoir'); # :shadowhaven_beriol_talorakoir_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_bestive_farworth'); # :shadowhaven_bestive_farworth_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_bilkel_biddinight'); # :shadowhaven_bilkel_biddinight_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_billien'); # :shadowhaven_billien_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_bouncer_molas'); # :shadowhaven_bouncer_molas_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_brandon_stormchaser'); # :shadowhaven_brandon_stormchaser_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_bronklad_stoneshaper'); # :shadowhaven_bronklad_stoneshaper_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_callowolf_macfuller'); # :shadowhaven_callowolf_macfuller_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_chadasl_dalsoeam'); # :shadowhaven_chadasl_dalsoeam_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_coglixar_xorlopodil'); # :shadowhaven_coglixar_xorlopodil_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_daekos_ferinsalo'); # :shadowhaven_daekos_ferinsalo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_daleoas_brondaer'); # :shadowhaven_daleoas_brondaer_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_daliea_saeiersa'); # :shadowhaven_daliea_saeiersa_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_daloran_glimmerblade'); # :shadowhaven_daloran_glimmerblade_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_danlin_hildreth'); # :shadowhaven_danlin_hildreth_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_darian_shallowsong'); # :shadowhaven_darian_shallowsong_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_darosn_sajson'); # :shadowhaven_darosn_sajson_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_daveiro_fanormat'); # :shadowhaven_daveiro_fanormat_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_alakurn'); # :shadowhaven_defender_alakurn_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_alein'); # :shadowhaven_defender_alein_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_alerion'); # :shadowhaven_defender_alerion_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_alroklon'); # :shadowhaven_defender_alroklon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_awilanar'); # :shadowhaven_defender_awilanar_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_axedaos'); # :shadowhaven_defender_axedaos_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_beolsona'); # :shadowhaven_defender_beolsona_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_boyrslen'); # :shadowhaven_defender_boyrslen_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_dalivayen'); # :shadowhaven_defender_dalivayen_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_deralian'); # :shadowhaven_defender_deralian_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_derlsin'); # :shadowhaven_defender_derlsin_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_dribsla'); # :shadowhaven_defender_dribsla_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_dutrolian'); # :shadowhaven_defender_dutrolian_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_eowlas'); # :shadowhaven_defender_eowlas_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_eronlo'); # :shadowhaven_defender_eronlo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_erotans'); # :shadowhaven_defender_erotans_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_faeloritar'); # :shadowhaven_defender_faeloritar_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_feorlso'); # :shadowhaven_defender_feorlso_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_filorou'); # :shadowhaven_defender_filorou_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_gerlinson'); # :shadowhaven_defender_gerlinson_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_geslaon'); # :shadowhaven_defender_geslaon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_helodonea'); # :shadowhaven_defender_helodonea_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_hollabac'); # :shadowhaven_defender_hollabac_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_jentlos'); # :shadowhaven_defender_jentlos_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_jerlen'); # :shadowhaven_defender_jerlen_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_joklusarn'); # :shadowhaven_defender_joklusarn_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_jolusnan'); # :shadowhaven_defender_jolusnan_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_justean'); # :shadowhaven_defender_justean_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_kealren'); # :shadowhaven_defender_kealren_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_lenduros'); # :shadowhaven_defender_lenduros_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_leorn'); # :shadowhaven_defender_leorn_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_naetel'); # :shadowhaven_defender_naetel_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_nalout'); # :shadowhaven_defender_nalout_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_natelrns'); # :shadowhaven_defender_natelrns_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_olaof'); # :shadowhaven_defender_olaof_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_paegor'); # :shadowhaven_defender_paegor_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_polosnes'); # :shadowhaven_defender_polosnes_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_qualern'); # :shadowhaven_defender_qualern_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_qulosna'); # :shadowhaven_defender_qulosna_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_raldson'); # :shadowhaven_defender_raldson_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_releiel'); # :shadowhaven_defender_releiel_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_rogalo'); # :shadowhaven_defender_rogalo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_salur'); # :shadowhaven_defender_salur_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_sintion'); # :shadowhaven_defender_sintion_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_taglorns'); # :shadowhaven_defender_taglorns_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_tamalre'); # :shadowhaven_defender_tamalre_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_teerlals'); # :shadowhaven_defender_teerlals_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_walorns'); # :shadowhaven_defender_walorns_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_wemblen'); # :shadowhaven_defender_wemblen_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_werolon'); # :shadowhaven_defender_werolon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_yausnor'); # :shadowhaven_defender_yausnor_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_yerlini'); # :shadowhaven_defender_yerlini_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_yoel'); # :shadowhaven_defender_yoel_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_defender_zaerel'); # :shadowhaven_defender_zaerel_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_desaliar_terfediskian'); # :shadowhaven_desaliar_terfediskian_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_dinoli_fantalicus'); # :shadowhaven_dinoli_fantalicus_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_disciple_chalong'); # :shadowhaven_disciple_chalong_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_disciple_ferilisu'); # :shadowhaven_disciple_ferilisu_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_disciple_keriuso'); # :shadowhaven_disciple_keriuso_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_disciple_peighro'); # :shadowhaven_disciple_peighro_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_disciple_taloerlen'); # :shadowhaven_disciple_taloerlen_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_driena_whistleger'); # :shadowhaven_driena_whistleger_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_drolan'); # :shadowhaven_drolan_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_eairdsidh_macfuller'); # :shadowhaven_eairdsidh_macfuller_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_ealerel_tidebringer'); # :shadowhaven_ealerel_tidebringer_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_easen'); # :shadowhaven_easen_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_eastring_fashing'); # :shadowhaven_eastring_fashing_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_eiles'); # :shadowhaven_eiles_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_engie_farworth'); # :shadowhaven_engie_farworth_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_eriska_malosona'); # :shadowhaven_eriska_malosona_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_eslof_runsalark'); # :shadowhaven_eslof_runsalark_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_eustace_dakes'); # :shadowhaven_eustace_dakes_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_falina_silinilak'); # :shadowhaven_falina_silinilak_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_fantoal_geabaran'); # :shadowhaven_fantoal_geabaran_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_feirus_hollowbranch'); # :shadowhaven_feirus_hollowbranch_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_ferusal'); # :shadowhaven_ferusal_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_fitonas_galaofon'); # :shadowhaven_fitonas_galaofon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_fordel_keeper_faloensar'); # :shadowhaven_fordel_keeper_faloensar_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_fordel_keeper_teridat'); # :shadowhaven_fordel_keeper_teridat_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_frewin_strongpaw'); # :shadowhaven_frewin_strongpaw_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_frinzel_heartstinger'); # :shadowhaven_frinzel_heartstinger_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_galorano_daldirick'); # :shadowhaven_galorano_daldirick_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_galoran_precon'); # :shadowhaven_galoran_precon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_galornas_eaksilwobble'); # :shadowhaven_galornas_eaksilwobble_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_garn_allonode'); # :shadowhaven_garn_allonode_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_garon_battlehand'); # :shadowhaven_garon_battlehand_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_gealian_husnalsn'); # :shadowhaven_gealian_husnalsn_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_gelson'); # :shadowhaven_gelson_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_general_dalinastalarix'); # :shadowhaven_general_dalinastalarix_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_goesl_sealsonich'); # :shadowhaven_goesl_sealsonich_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_gralin_silvertooth'); # :shadowhaven_gralin_silvertooth_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_grandmaster_haloriki'); # :shadowhaven_grandmaster_haloriki_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_granger_kenforth'); # :shadowhaven_granger_kenforth_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_grimthor'); # :shadowhaven_grimthor_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_guardsman_dales'); # :shadowhaven_guardsman_dales_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_guardsman_joroli'); # :shadowhaven_guardsman_joroli_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_hamon'); # :shadowhaven_hamon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_hardam_stonegrinder'); # :shadowhaven_hardam_stonegrinder_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_healian_saroelitan'); # :shadowhaven_healian_saroelitan_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_hejsua_skalkon'); # :shadowhaven_hejsua_skalkon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_henriala_hobialon'); # :shadowhaven_henriala_hobialon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_hereia_gealsina'); # :shadowhaven_hereia_gealsina_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_herol_beaufodal'); # :shadowhaven_herol_beaufodal_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_hintol_balkortak'); # :shadowhaven_hintol_balkortak_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_hobolor_peltskinner'); # :shadowhaven_hobolor_peltskinner_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_horiel_gaeslania'); # :shadowhaven_horiel_gaeslania_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_horsal_bittrosas'); # :shadowhaven_horsal_bittrosas_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_house_watch_dunvel'); # :shadowhaven_house_watch_dunvel_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_incantator_brials'); # :shadowhaven_incantator_brials_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_incantator_firefall'); # :shadowhaven_incantator_firefall_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_incantator_icewand'); # :shadowhaven_incantator_icewand_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_incantator_lizerian'); # :shadowhaven_incantator_lizerian_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_incantator_palaser'); # :shadowhaven_incantator_palaser_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_incantator_saderloa'); # :shadowhaven_incantator_saderloa_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_incantator_salien'); # :shadowhaven_incantator_salien_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_incantator_stevak'); # :shadowhaven_incantator_stevak_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_incantator_verloir'); # :shadowhaven_incantator_verloir_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_innkeeper_morland'); # :shadowhaven_innkeeper_morland_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_innkeep_alviva'); # :shadowhaven_innkeep_alviva_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_innkeep_restoration'); # :shadowhaven_innkeep_restoration_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_innkeep_zara'); # :shadowhaven_innkeep_zara_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_izibat'); # :shadowhaven_izibat_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_jacob_thornblade'); # :shadowhaven_jacob_thornblade_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_jales_gaelshorad'); # :shadowhaven_jales_gaelshorad_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_jiovfer_precon'); # :shadowhaven_jiovfer_precon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_jolan'); # :shadowhaven_jolan_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_jostan_karsnic'); # :shadowhaven_jostan_karsnic_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_junun_rawkins'); # :shadowhaven_junun_rawkins_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_kardon'); # :shadowhaven_kardon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_kassel'); # :shadowhaven_kassel_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_keeper_geologo'); # :shadowhaven_keeper_geologo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_keeper_raldilikis'); # :shadowhaven_keeper_raldilikis_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_keiya_oakwood'); # :shadowhaven_keiya_oakwood_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_kelly_blackhand'); # :shadowhaven_kelly_blackhand_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_kenral_siroisl'); # :shadowhaven_kenral_siroisl_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_kolburn_inglewort'); # :shadowhaven_kolburn_inglewort_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_koren_galund'); # :shadowhaven_koren_galund_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_krizle_geerlok'); # :shadowhaven_krizle_geerlok_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_kytley'); # :shadowhaven_kytley_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lamukas_kaesoanls'); # :shadowhaven_lamukas_kaesoanls_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lander_furthers'); # :shadowhaven_lander_furthers_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lareso_runsalark'); # :shadowhaven_lareso_runsalark_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lemsen_frostherb'); # :shadowhaven_lemsen_frostherb_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lesia_furthers'); # :shadowhaven_lesia_furthers_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lewena'); # :shadowhaven_lewena_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_loensa_esorlinal'); # :shadowhaven_loensa_esorlinal_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_loewnsaz_waldalon'); # :shadowhaven_loewnsaz_waldalon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lolara'); # :shadowhaven_lolara_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_belorop'); # :shadowhaven_lookout_belorop_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_bolombo'); # :shadowhaven_lookout_bolombo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_delron'); # :shadowhaven_lookout_delron_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_eloralon'); # :shadowhaven_lookout_eloralon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_falatalix'); # :shadowhaven_lookout_falatalix_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_gereol'); # :shadowhaven_lookout_gereol_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_girols'); # :shadowhaven_lookout_girols_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_nelorin'); # :shadowhaven_lookout_nelorin_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_reloen'); # :shadowhaven_lookout_reloen_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_sereon'); # :shadowhaven_lookout_sereon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_tageonia'); # :shadowhaven_lookout_tageonia_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_tiblo'); # :shadowhaven_lookout_tiblo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_uhingil'); # :shadowhaven_lookout_uhingil_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_valobolo'); # :shadowhaven_lookout_valobolo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lookout_yereil'); # :shadowhaven_lookout_yereil_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_lynesia_eroaaf'); # :shadowhaven_lynesia_eroaaf_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_mandark_soulhealer'); # :shadowhaven_mandark_soulhealer_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_marchap_biddinight'); # :shadowhaven_marchap_biddinight_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_mark_blotter'); # :shadowhaven_mark_blotter_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_meribeth'); # :shadowhaven_meribeth_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_milasar_husnalsn'); # :shadowhaven_milasar_husnalsn_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_milesent'); # :shadowhaven_milesent_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_mistala_glimmerblade'); # :shadowhaven_mistala_glimmerblade_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_mother_ilisial_fordel'); # :shadowhaven_mother_ilisial_fordel_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_narmase_flecher'); # :shadowhaven_narmase_flecher_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_narsam'); # :shadowhaven_narsam_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_nayda_winterwind'); # :shadowhaven_nayda_winterwind_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_nelm_the_tiny'); # :shadowhaven_nelm_the_tiny_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_nevetra_utagse'); # :shadowhaven_nevetra_utagse_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_nicoela'); # :shadowhaven_nicoela_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_nieson_loterboras'); # :shadowhaven_nieson_loterboras_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_nolram_gorlsan'); # :shadowhaven_nolram_gorlsan_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_nubert'); # :shadowhaven_nubert_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_oxon_essencebinder'); # :shadowhaven_oxon_essencebinder_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_palomidiar_allakhaji'); # :shadowhaven_palomidiar_allakhaji_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_patriarch_lardalon'); # :shadowhaven_patriarch_lardalon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_patrolman_blickorot'); # :shadowhaven_patrolman_blickorot_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_patrolman_walopalo'); # :shadowhaven_patrolman_walopalo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_peacekeeper_dasoel'); # :shadowhaven_peacekeeper_dasoel_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_peacekeeper_deralokor'); # :shadowhaven_peacekeeper_deralokor_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_peacekeeper_sarolorn'); # :shadowhaven_peacekeeper_sarolorn_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_peacekeeper_sildalos'); # :shadowhaven_peacekeeper_sildalos_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_peqi_biato'); # :shadowhaven_peqi_biato_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_piersal_whistleger'); # :shadowhaven_piersal_whistleger_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_pietro_guiccini'); # :shadowhaven_pietro_guiccini_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_pilop_stolarix'); # :shadowhaven_pilop_stolarix_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_plow_jumpinwolf'); # :shadowhaven_plow_jumpinwolf_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_podslan_xasiani'); # :shadowhaven_podslan_xasiani_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_polson_medicinal'); # :shadowhaven_polson_medicinal_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_praeon_wyldefire'); # :shadowhaven_praeon_wyldefire_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_priestess_farinthorn'); # :shadowhaven_priestess_farinthorn_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_priest_jarson'); # :shadowhaven_priest_jarson_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_ralshalod'); # :shadowhaven_ralshalod_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_record_keeper_ajar'); # :shadowhaven_record_keeper_ajar_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_researcher_relreom'); # :shadowhaven_researcher_relreom_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_rianna_birchard'); # :shadowhaven_rianna_birchard_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_rifkin'); # :shadowhaven_rifkin_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_river_mudhands'); # :shadowhaven_river_mudhands_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_robbolo_balashil'); # :shadowhaven_robbolo_balashil_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_robert_blackhand'); # :shadowhaven_robert_blackhand_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_ronlotar_stumpshade'); # :shadowhaven_ronlotar_stumpshade_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_rowl_tanner'); # :shadowhaven_rowl_tanner_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_rusty_blackhand'); # :shadowhaven_rusty_blackhand_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sahrona_sorisnali'); # :shadowhaven_sahrona_sorisnali_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_samotal_sedmians'); # :shadowhaven_samotal_sedmians_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sanderson'); # :shadowhaven_sanderson_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sarith_clawnik'); # :shadowhaven_sarith_clawnik_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sarlos_windwalker'); # :shadowhaven_sarlos_windwalker_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sarron'); # :shadowhaven_sarron_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sedaitam_cournsian'); # :shadowhaven_sedaitam_cournsian_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sesamin_soulhealer'); # :shadowhaven_sesamin_soulhealer_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_shhbarconv'); # :shadowhaven_shhbarconv_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sibyl'); # :shadowhaven_sibyl_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sinasi_daleioa'); # :shadowhaven_sinasi_daleioa_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sir_heaviside'); # :shadowhaven_sir_heaviside_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sir_jarsonic'); # :shadowhaven_sir_jarsonic_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sir_michael'); # :shadowhaven_sir_michael_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sir_oron'); # :shadowhaven_sir_oron_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_skalopar'); # :shadowhaven_skalopar_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_skiliar_hardbrick'); # :shadowhaven_skiliar_hardbrick_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_slosean'); # :shadowhaven_slosean_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_smithy_edcar'); # :shadowhaven_smithy_edcar_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_smithy_firehand'); # :shadowhaven_smithy_firehand_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sneathe'); # :shadowhaven_sneathe_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sol'); # :shadowhaven_sol_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_soulbinder_nansin'); # :shadowhaven_soulbinder_nansin_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_sroj_arrowsmith'); # :shadowhaven_sroj_arrowsmith_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_steaon_alarenier'); # :shadowhaven_steaon_alarenier_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_tabard_redhand'); # :shadowhaven_tabard_redhand_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_tabart_tailforth'); # :shadowhaven_tabart_tailforth_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_talida_furrytoes'); # :shadowhaven_talida_furrytoes_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_tall_joe'); # :shadowhaven_tall_joe_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_talor'); # :shadowhaven_talor_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_tarson_lonewolf'); # :shadowhaven_tarson_lonewolf_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_teriesl_windwalker'); # :shadowhaven_teriesl_windwalker_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_tersie_falsialoen'); # :shadowhaven_tersie_falsialoen_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_therin_asakith'); # :shadowhaven_therin_asakith_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_tiplo_the_gardener'); # :shadowhaven_tiplo_the_gardener_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_tirac_goldbender'); # :shadowhaven_tirac_goldbender_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_toddor_stalorok'); # :shadowhaven_toddor_stalorok_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_townsperson_berolon'); # :shadowhaven_townsperson_berolon_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_townsperson_erinol'); # :shadowhaven_townsperson_erinol_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_townsperson_pirions'); # :shadowhaven_townsperson_pirions_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_townsperson_ranlanos'); # :shadowhaven_townsperson_ranlanos_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_townsperson_sarolix'); # :shadowhaven_townsperson_sarolix_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_trade_commissioner_henry'); # :shadowhaven_trade_commissioner_henry_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_tronso_namistail'); # :shadowhaven_tronso_namistail_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_tsueas_eadajo'); # :shadowhaven_tsueas_eadajo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_verte'); # :shadowhaven_verte_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_vicars'); # :shadowhaven_vicars_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_volan'); # :shadowhaven_volan_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_vuri_pandar'); # :shadowhaven_vuri_pandar_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_waterman'); # :shadowhaven_waterman_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_wawker'); # :shadowhaven_wawker_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_wayke_mudhands'); # :shadowhaven_wayke_mudhands_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_wiglapo'); # :shadowhaven_wiglapo_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_xerisolap_whistleger'); # :shadowhaven_xerisolap_whistleger_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_xerolop_palostilad'); # :shadowhaven_xerolop_palostilad_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_yargin_the_traveler'); # :shadowhaven_yargin_the_traveler_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_yaron'); # :shadowhaven_yaron_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_yeren_ironback'); # :shadowhaven_yeren_ironback_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_zaores'); # :shadowhaven_zaores_lt:
INSERT INTO loottable(name) VALUES('shadowhaven_zimloro_jalobottle'); # :shadowhaven_zimloro_jalobottle_lt:
