(:shadeweaver_a_lesser_shade_lt:, :rusty_ld:, 1),
(:shadeweaver_a_firefall_saurek_lt:, :vah_shir_meat_ld:, 1),
(:shadeweaver_a_lesser_shade_lt:, :skeleton_parts_ld:, 1),
(:shadeweaver_a_skeletal_brigand_lt:, :skeleton_parts_ld:, 1),
(:shadeweaver_a_skeletal_hunter_lt:, :bone_chips_ld:, 1),
(:shadeweaver_a_skeletal_brigand_lt:, :bone_chips_ld:, 1),
(:shadeweaver_a_skeletal_thug_lt:, :bone_chips_ld:, 1),
