INSERT INTO loottable(name) VALUES('sharvahl_a_prisoner'); # :sharvahl_a_prisoner_lt:
INSERT INTO loottable(name) VALUES('sharvahl_chialle'); # :sharvahl_chialle_lt:
INSERT INTO loottable(name) VALUES('sharvahl_delival'); # :sharvahl_delival_lt:
INSERT INTO loottable(name) VALUES('sharvahl_elder_animist_muada'); # :sharvahl_elder_animist_muada_lt:
INSERT INTO loottable(name) VALUES('sharvahl_general_keraj'); # :sharvahl_general_keraj_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_aihjin'); # :sharvahl_khala_dun_aihjin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_bokh'); # :sharvahl_khala_dun_bokh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_jasir'); # :sharvahl_khala_dun_jasir_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_koby'); # :sharvahl_khala_dun_koby_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_fahaar'); # :sharvahl_recruit_fahaar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_omaj'); # :sharvahl_recruit_omaj_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_sihiq'); # :sharvahl_recruit_sihiq_lt:
INSERT INTO loottable(name) VALUES('sharvahl_shainai'); # :sharvahl_shainai_lt:
INSERT INTO loottable(name) VALUES('sharvahl_tailfang'); # :sharvahl_tailfang_lt:
INSERT INTO loottable(name) VALUES('sharvahl_tajie_karaf'); # :sharvahl_tajie_karaf_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_murod_karaf'); # :sharvahl_taruun_murod_karaf_lt:
INSERT INTO loottable(name) VALUES('sharvahl_vuro_padfoot'); # :sharvahl_vuro_padfoot_lt:
INSERT INTO loottable(name) VALUES('sharvahl_ahahd_tolm'); # :sharvahl_ahahd_tolm_lt:
INSERT INTO loottable(name) VALUES('sharvahl_ahjiq_mumir'); # :sharvahl_ahjiq_mumir_lt:
INSERT INTO loottable(name) VALUES('sharvahl_alchemist_hikal'); # :sharvahl_alchemist_hikal_lt:
INSERT INTO loottable(name) VALUES('sharvahl_alchemist_kotahl'); # :sharvahl_alchemist_kotahl_lt:
INSERT INTO loottable(name) VALUES('sharvahl_aljuum_mohim'); # :sharvahl_aljuum_mohim_lt:
INSERT INTO loottable(name) VALUES('sharvahl_amat_iuziq'); # :sharvahl_amat_iuziq_lt:
INSERT INTO loottable(name) VALUES('sharvahl_amgah_siman'); # :sharvahl_amgah_siman_lt:
INSERT INTO loottable(name) VALUES('sharvahl_amyamu'); # :sharvahl_amyamu_lt:
INSERT INTO loottable(name) VALUES('sharvahl_animist_gazin'); # :sharvahl_animist_gazin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_animist_imotmeh'); # :sharvahl_animist_imotmeh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_animist_mahron_sood'); # :sharvahl_animist_mahron_sood_lt:
INSERT INTO loottable(name) VALUES('sharvahl_animist_poren'); # :sharvahl_animist_poren_lt:
INSERT INTO loottable(name) VALUES('sharvahl_animist_simol'); # :sharvahl_animist_simol_lt:
INSERT INTO loottable(name) VALUES('sharvahl_apprentice_davik'); # :sharvahl_apprentice_davik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_apprentice_garr'); # :sharvahl_apprentice_garr_lt:
INSERT INTO loottable(name) VALUES('sharvahl_apprentice_hirata'); # :sharvahl_apprentice_hirata_lt:
INSERT INTO loottable(name) VALUES('sharvahl_apprentice_kafy'); # :sharvahl_apprentice_kafy_lt:
INSERT INTO loottable(name) VALUES('sharvahl_apprentice_omosh'); # :sharvahl_apprentice_omosh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_apprentice_rawkel'); # :sharvahl_apprentice_rawkel_lt:
INSERT INTO loottable(name) VALUES('sharvahl_apprentice_siason'); # :sharvahl_apprentice_siason_lt:
INSERT INTO loottable(name) VALUES('sharvahl_armorer_nimij'); # :sharvahl_armorer_nimij_lt:
INSERT INTO loottable(name) VALUES('sharvahl_armsman_khaigesh'); # :sharvahl_armsman_khaigesh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_arms_historian_qua'); # :sharvahl_arms_historian_qua_lt:
INSERT INTO loottable(name) VALUES('sharvahl_arms_researcher_saulgan'); # :sharvahl_arms_researcher_saulgan_lt:
INSERT INTO loottable(name) VALUES('sharvahl_arrin_murij'); # :sharvahl_arrin_murij_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_caged_rockhopper'); # :sharvahl_a_caged_rockhopper_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_decaying_skeleton'); # :sharvahl_a_decaying_skeleton_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_frostfell_goblin'); # :sharvahl_a_frostfell_goblin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_frost_covered_hopling'); # :sharvahl_a_frost_covered_hopling_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_grimling_prisoner'); # :sharvahl_a_grimling_prisoner_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_grimling_runt'); # :sharvahl_a_grimling_runt_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_grimling_skeleton'); # :sharvahl_a_grimling_skeleton_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_needle_clawed_hopper'); # :sharvahl_a_needle_clawed_hopper_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_prisoner'); # :sharvahl_a_prisoner_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_rhinobeetle_hatchling'); # :sharvahl_a_rhinobeetle_hatchling_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_scorpion'); # :sharvahl_a_scorpion_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_shar_vahl_guard'); # :sharvahl_a_shar_vahl_guard_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_whiptail_scorpion'); # :sharvahl_a_whiptail_scorpion_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_whisperling'); # :sharvahl_a_whisperling_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_xakra_larva'); # :sharvahl_a_xakra_larva_lt:
INSERT INTO loottable(name) VALUES('sharvahl_a_young_rockhopper'); # :sharvahl_a_young_rockhopper_lt:
INSERT INTO loottable(name) VALUES('sharvahl_banker_kjarl'); # :sharvahl_banker_kjarl_lt:
INSERT INTO loottable(name) VALUES('sharvahl_banker_naudi'); # :sharvahl_banker_naudi_lt:
INSERT INTO loottable(name) VALUES('sharvahl_barkeep_babagyn'); # :sharvahl_barkeep_babagyn_lt:
INSERT INTO loottable(name) VALUES('sharvahl_barkeep_nejat'); # :sharvahl_barkeep_nejat_lt:
INSERT INTO loottable(name) VALUES('sharvahl_barkeep_rawlf'); # :sharvahl_barkeep_rawlf_lt:
INSERT INTO loottable(name) VALUES('sharvahl_barracks_guard_myrik'); # :sharvahl_barracks_guard_myrik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_brewer_mikkis'); # :sharvahl_brewer_mikkis_lt:
INSERT INTO loottable(name) VALUES('sharvahl_brewmaster_hizier'); # :sharvahl_brewmaster_hizier_lt:
INSERT INTO loottable(name) VALUES('sharvahl_broker_fahaar'); # :sharvahl_broker_fahaar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_brokh'); # :sharvahl_brokh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_captain_arulk'); # :sharvahl_captain_arulk_lt:
INSERT INTO loottable(name) VALUES('sharvahl_captain_jhulim'); # :sharvahl_captain_jhulim_lt:
INSERT INTO loottable(name) VALUES('sharvahl_carih_namij'); # :sharvahl_carih_namij_lt:
INSERT INTO loottable(name) VALUES('sharvahl_chogar'); # :sharvahl_chogar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_cook_mylis'); # :sharvahl_cook_mylis_lt:
INSERT INTO loottable(name) VALUES('sharvahl_cook_umek'); # :sharvahl_cook_umek_lt:
INSERT INTO loottable(name) VALUES('sharvahl_cook_yalkiin'); # :sharvahl_cook_yalkiin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_danala_valith'); # :sharvahl_danala_valith_lt:
INSERT INTO loottable(name) VALUES('sharvahl_dar_khura_ahmih'); # :sharvahl_dar_khura_ahmih_lt:
INSERT INTO loottable(name) VALUES('sharvahl_dar_khura_aylin'); # :sharvahl_dar_khura_aylin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_dar_khura_hamat'); # :sharvahl_dar_khura_hamat_lt:
INSERT INTO loottable(name) VALUES('sharvahl_dar_khura_hylaar'); # :sharvahl_dar_khura_hylaar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_dar_khura_jeruk'); # :sharvahl_dar_khura_jeruk_lt:
INSERT INTO loottable(name) VALUES('sharvahl_dar_khura_pyjek'); # :sharvahl_dar_khura_pyjek_lt:
INSERT INTO loottable(name) VALUES('sharvahl_dar_khura_shavra'); # :sharvahl_dar_khura_shavra_lt:
INSERT INTO loottable(name) VALUES('sharvahl_delival'); # :sharvahl_delival_lt:
INSERT INTO loottable(name) VALUES('sharvahl_dharr_nadim'); # :sharvahl_dharr_nadim_lt:
INSERT INTO loottable(name) VALUES('sharvahl_dronqam_runghi'); # :sharvahl_dronqam_runghi_lt:
INSERT INTO loottable(name) VALUES('sharvahl_elam_arruk'); # :sharvahl_elam_arruk_lt:
INSERT INTO loottable(name) VALUES('sharvahl_elder_animist_dumul'); # :sharvahl_elder_animist_dumul_lt:
INSERT INTO loottable(name) VALUES('sharvahl_elder_animist_sahdi'); # :sharvahl_elder_animist_sahdi_lt:
INSERT INTO loottable(name) VALUES('sharvahl_elder_hymnist_hortitosh'); # :sharvahl_elder_hymnist_hortitosh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_elder_scout_kyth_lar'); # :sharvahl_elder_scout_kyth_lar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_elder_spiritist_grawleh'); # :sharvahl_elder_spiritist_grawleh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_elder_taruun_ternq'); # :sharvahl_elder_taruun_ternq_lt:
INSERT INTO loottable(name) VALUES('sharvahl_elder_veteran_muhrak'); # :sharvahl_elder_veteran_muhrak_lt:
INSERT INTO loottable(name) VALUES('sharvahl_erat_almar'); # :sharvahl_erat_almar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_fharra_cawfeet'); # :sharvahl_fharra_cawfeet_lt:
INSERT INTO loottable(name) VALUES('sharvahl_firewatch_kigil'); # :sharvahl_firewatch_kigil_lt:
INSERT INTO loottable(name) VALUES('sharvahl_firewatch_ohmila'); # :sharvahl_firewatch_ohmila_lt:
INSERT INTO loottable(name) VALUES('sharvahl_fireworks_engineer_fabdabus'); # :sharvahl_fireworks_engineer_fabdabus_lt:
INSERT INTO loottable(name) VALUES('sharvahl_friaz_ompir'); # :sharvahl_friaz_ompir_lt:
INSERT INTO loottable(name) VALUES('sharvahl_garl'); # :sharvahl_garl_lt:
INSERT INTO loottable(name) VALUES('sharvahl_gawra'); # :sharvahl_gawra_lt:
INSERT INTO loottable(name) VALUES('sharvahl_gendalic'); # :sharvahl_gendalic_lt:
INSERT INTO loottable(name) VALUES('sharvahl_general_avilah'); # :sharvahl_general_avilah_lt:
INSERT INTO loottable(name) VALUES('sharvahl_gherik_alarhun'); # :sharvahl_gherik_alarhun_lt:
INSERT INTO loottable(name) VALUES('sharvahl_golath'); # :sharvahl_golath_lt:
INSERT INTO loottable(name) VALUES('sharvahl_guard_jabbar'); # :sharvahl_guard_jabbar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_hana_sulm'); # :sharvahl_hana_sulm_lt:
INSERT INTO loottable(name) VALUES('sharvahl_harbin_gernawl'); # :sharvahl_harbin_gernawl_lt:
INSERT INTO loottable(name) VALUES('sharvahl_hargar_the_velium_chef'); # :sharvahl_hargar_the_velium_chef_lt:
INSERT INTO loottable(name) VALUES('sharvahl_high_armsman_trukhanah'); # :sharvahl_high_armsman_trukhanah_lt:
INSERT INTO loottable(name) VALUES('sharvahl_high_spiritist_jimuul'); # :sharvahl_high_spiritist_jimuul_lt:
INSERT INTO loottable(name) VALUES('sharvahl_historian_jiira'); # :sharvahl_historian_jiira_lt:
INSERT INTO loottable(name) VALUES('sharvahl_historian_sharar'); # :sharvahl_historian_sharar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_hokar'); # :sharvahl_hokar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_honor_guard_ishouz'); # :sharvahl_honor_guard_ishouz_lt:
INSERT INTO loottable(name) VALUES('sharvahl_honor_guard_siiv'); # :sharvahl_honor_guard_siiv_lt:
INSERT INTO loottable(name) VALUES('sharvahl_hymnist_gawfed'); # :sharvahl_hymnist_gawfed_lt:
INSERT INTO loottable(name) VALUES('sharvahl_instructor_anom'); # :sharvahl_instructor_anom_lt:
INSERT INTO loottable(name) VALUES('sharvahl_instructor_mussin'); # :sharvahl_instructor_mussin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_invisumatwo'); # :sharvahl_invisumatwo_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jaima_seyel'); # :sharvahl_jaima_seyel_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jakhal'); # :sharvahl_jakhal_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jala'); # :sharvahl_jala_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jaleh'); # :sharvahl_jaleh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jalil_talih'); # :sharvahl_jalil_talih_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jangle'); # :sharvahl_jangle_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jharia_talmil'); # :sharvahl_jharia_talmil_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jharin_apprentice_ymina'); # :sharvahl_jharin_apprentice_ymina_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jharin_hajka'); # :sharvahl_jharin_hajka_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jharin_kiliik'); # :sharvahl_jharin_kiliik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jharin_niejan'); # :sharvahl_jharin_niejan_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jharin_ryak'); # :sharvahl_jharin_ryak_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jharin_taani'); # :sharvahl_jharin_taani_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jheral_alezya'); # :sharvahl_jheral_alezya_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jhimis_khadwi'); # :sharvahl_jhimis_khadwi_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jihli_mahej'); # :sharvahl_jihli_mahej_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jihli_namij'); # :sharvahl_jihli_namij_lt:
INSERT INTO loottable(name) VALUES('sharvahl_jolod_amulek'); # :sharvahl_jolod_amulek_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kaam_rahiir'); # :sharvahl_kaam_rahiir_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kafal'); # :sharvahl_kafal_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kagazz'); # :sharvahl_kagazz_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kahala'); # :sharvahl_kahala_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kalila_talih'); # :sharvahl_kalila_talih_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kanaad'); # :sharvahl_kanaad_lt:
INSERT INTO loottable(name) VALUES('sharvahl_katja'); # :sharvahl_katja_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kery_miann'); # :sharvahl_kery_miann_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_alferi'); # :sharvahl_khala_dun_alferi_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_aoera'); # :sharvahl_khala_dun_aoera_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_erelk'); # :sharvahl_khala_dun_erelk_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_faalym'); # :sharvahl_khala_dun_faalym_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_fareed'); # :sharvahl_khala_dun_fareed_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_grerath'); # :sharvahl_khala_dun_grerath_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_gurish'); # :sharvahl_khala_dun_gurish_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_hebijeb'); # :sharvahl_khala_dun_hebijeb_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_jhiniam'); # :sharvahl_khala_dun_jhiniam_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_kerak'); # :sharvahl_khala_dun_kerak_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_kuash'); # :sharvahl_khala_dun_kuash_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_larg'); # :sharvahl_khala_dun_larg_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_maluki'); # :sharvahl_khala_dun_maluki_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_moggs'); # :sharvahl_khala_dun_moggs_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_murglim'); # :sharvahl_khala_dun_murglim_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_quatan'); # :sharvahl_khala_dun_quatan_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_rakata'); # :sharvahl_khala_dun_rakata_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_rorya'); # :sharvahl_khala_dun_rorya_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_sleyhin'); # :sharvahl_khala_dun_sleyhin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_taraku'); # :sharvahl_khala_dun_taraku_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khala_dun_welaar'); # :sharvahl_khala_dun_welaar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khati_sha_guraat'); # :sharvahl_khati_sha_guraat_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khati_sha_jaarin'); # :sharvahl_khati_sha_jaarin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khati_sha_marook'); # :sharvahl_khati_sha_marook_lt:
INSERT INTO loottable(name) VALUES('sharvahl_khati_sha_mylia'); # :sharvahl_khati_sha_mylia_lt:
INSERT INTO loottable(name) VALUES('sharvahl_king_raja_kerrath'); # :sharvahl_king_raja_kerrath_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kogar'); # :sharvahl_kogar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kojik'); # :sharvahl_kojik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_kyala'); # :sharvahl_kyala_lt:
INSERT INTO loottable(name) VALUES('sharvahl_laanas_sejiir'); # :sharvahl_laanas_sejiir_lt:
INSERT INTO loottable(name) VALUES('sharvahl_lajika'); # :sharvahl_lajika_lt:
INSERT INTO loottable(name) VALUES('sharvahl_larken'); # :sharvahl_larken_lt:
INSERT INTO loottable(name) VALUES('sharvahl_librarian_almasa'); # :sharvahl_librarian_almasa_lt:
INSERT INTO loottable(name) VALUES('sharvahl_liorra_sha_kerrath'); # :sharvahl_liorra_sha_kerrath_lt:
INSERT INTO loottable(name) VALUES('sharvahl_lorekeeper_ayriik'); # :sharvahl_lorekeeper_ayriik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_lore_master_rahamin'); # :sharvahl_lore_master_rahamin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_lyjak'); # :sharvahl_lyjak_lt:
INSERT INTO loottable(name) VALUES('sharvahl_maera_kerrath'); # :sharvahl_maera_kerrath_lt:
INSERT INTO loottable(name) VALUES('sharvahl_mahj_hujara'); # :sharvahl_mahj_hujara_lt:
INSERT INTO loottable(name) VALUES('sharvahl_marduk'); # :sharvahl_marduk_lt:
INSERT INTO loottable(name) VALUES('sharvahl_master_barkhem'); # :sharvahl_master_barkhem_lt:
INSERT INTO loottable(name) VALUES('sharvahl_master_taruun_rakutah'); # :sharvahl_master_taruun_rakutah_lt:
INSERT INTO loottable(name) VALUES('sharvahl_melek_haluur'); # :sharvahl_melek_haluur_lt:
INSERT INTO loottable(name) VALUES('sharvahl_merchant_ahlam'); # :sharvahl_merchant_ahlam_lt:
INSERT INTO loottable(name) VALUES('sharvahl_merchant_ayyad'); # :sharvahl_merchant_ayyad_lt:
INSERT INTO loottable(name) VALUES('sharvahl_merchant_gamouz'); # :sharvahl_merchant_gamouz_lt:
INSERT INTO loottable(name) VALUES('sharvahl_messenger_yuashar'); # :sharvahl_messenger_yuashar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_mess_cook_azur'); # :sharvahl_mess_cook_azur_lt:
INSERT INTO loottable(name) VALUES('sharvahl_mess_cook_pyjik'); # :sharvahl_mess_cook_pyjik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_mignah_cahru'); # :sharvahl_mignah_cahru_lt:
INSERT INTO loottable(name) VALUES('sharvahl_minna_helo'); # :sharvahl_minna_helo_lt:
INSERT INTO loottable(name) VALUES('sharvahl_mugdah'); # :sharvahl_mugdah_lt:
INSERT INTO loottable(name) VALUES('sharvahl_mydi_darjik'); # :sharvahl_mydi_darjik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_nayantara_tarana'); # :sharvahl_nayantara_tarana_lt:
INSERT INTO loottable(name) VALUES('sharvahl_nocia'); # :sharvahl_nocia_lt:
INSERT INTO loottable(name) VALUES('sharvahl_noril_galoon'); # :sharvahl_noril_galoon_lt:
INSERT INTO loottable(name) VALUES('sharvahl_nytal_lior'); # :sharvahl_nytal_lior_lt:
INSERT INTO loottable(name) VALUES('sharvahl_palace_guard_niromak'); # :sharvahl_palace_guard_niromak_lt:
INSERT INTO loottable(name) VALUES('sharvahl_palace_guard_talruush'); # :sharvahl_palace_guard_talruush_lt:
INSERT INTO loottable(name) VALUES('sharvahl_palav'); # :sharvahl_palav_lt:
INSERT INTO loottable(name) VALUES('sharvahl_pardak'); # :sharvahl_pardak_lt:
INSERT INTO loottable(name) VALUES('sharvahl_paruh_milin'); # :sharvahl_paruh_milin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_pashir_vollemon'); # :sharvahl_pashir_vollemon_lt:
INSERT INTO loottable(name) VALUES('sharvahl_pathmaster_kharin'); # :sharvahl_pathmaster_kharin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_pit_guard_abdar'); # :sharvahl_pit_guard_abdar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_pit_guard_goqua'); # :sharvahl_pit_guard_goqua_lt:
INSERT INTO loottable(name) VALUES('sharvahl_pit_guard_retaj'); # :sharvahl_pit_guard_retaj_lt:
INSERT INTO loottable(name) VALUES('sharvahl_poekie_raraesh'); # :sharvahl_poekie_raraesh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_priest_of_discord'); # :sharvahl_priest_of_discord_lt:
INSERT INTO loottable(name) VALUES('sharvahl_rajyk'); # :sharvahl_rajyk_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_aliid'); # :sharvahl_recruit_aliid_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_almdur'); # :sharvahl_recruit_almdur_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_diani'); # :sharvahl_recruit_diani_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_erun'); # :sharvahl_recruit_erun_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_huuma'); # :sharvahl_recruit_huuma_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_jiih'); # :sharvahl_recruit_jiih_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_kilyla'); # :sharvahl_recruit_kilyla_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_kuluj'); # :sharvahl_recruit_kuluj_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_miaja'); # :sharvahl_recruit_miaja_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_mogol'); # :sharvahl_recruit_mogol_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_rawik'); # :sharvahl_recruit_rawik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_recruit_ulra'); # :sharvahl_recruit_ulra_lt:
INSERT INTO loottable(name) VALUES('sharvahl_registrar_bindarah'); # :sharvahl_registrar_bindarah_lt:
INSERT INTO loottable(name) VALUES('sharvahl_ritra_icyclaw'); # :sharvahl_ritra_icyclaw_lt:
INSERT INTO loottable(name) VALUES('sharvahl_royal_escort_yalahn'); # :sharvahl_royal_escort_yalahn_lt:
INSERT INTO loottable(name) VALUES('sharvahl_royal_guard_alraj'); # :sharvahl_royal_guard_alraj_lt:
INSERT INTO loottable(name) VALUES('sharvahl_royal_guard_dak'); # :sharvahl_royal_guard_dak_lt:
INSERT INTO loottable(name) VALUES('sharvahl_royal_guard_grosch'); # :sharvahl_royal_guard_grosch_lt:
INSERT INTO loottable(name) VALUES('sharvahl_royal_guard_hahjik'); # :sharvahl_royal_guard_hahjik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_royal_guard_jinjiq'); # :sharvahl_royal_guard_jinjiq_lt:
INSERT INTO loottable(name) VALUES('sharvahl_royal_guard_maras'); # :sharvahl_royal_guard_maras_lt:
INSERT INTO loottable(name) VALUES('sharvahl_royal_guard_maruuk'); # :sharvahl_royal_guard_maruuk_lt:
INSERT INTO loottable(name) VALUES('sharvahl_royal_guard_ragaar'); # :sharvahl_royal_guard_ragaar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_rytan'); # :sharvahl_rytan_lt:
INSERT INTO loottable(name) VALUES('sharvahl_salla'); # :sharvahl_salla_lt:
INSERT INTO loottable(name) VALUES('sharvahl_santug_claugg'); # :sharvahl_santug_claugg_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scout_andur'); # :sharvahl_scout_andur_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scout_faarni'); # :sharvahl_scout_faarni_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scout_irumo'); # :sharvahl_scout_irumo_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scout_lijo'); # :sharvahl_scout_lijo_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_cholsa'); # :sharvahl_scribe_cholsa_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_dav'); # :sharvahl_scribe_dav_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_gefna'); # :sharvahl_scribe_gefna_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_grawl'); # :sharvahl_scribe_grawl_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_imasan'); # :sharvahl_scribe_imasan_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_kaleej'); # :sharvahl_scribe_kaleej_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_lar'); # :sharvahl_scribe_lar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_mojir'); # :sharvahl_scribe_mojir_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_natji'); # :sharvahl_scribe_natji_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_qualia'); # :sharvahl_scribe_qualia_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_shiara'); # :sharvahl_scribe_shiara_lt:
INSERT INTO loottable(name) VALUES('sharvahl_scribe_tolniq'); # :sharvahl_scribe_tolniq_lt:
INSERT INTO loottable(name) VALUES('sharvahl_seer_jafik'); # :sharvahl_seer_jafik_lt:
INSERT INTO loottable(name) VALUES('sharvahl_sergeant_abaar'); # :sharvahl_sergeant_abaar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_sergeant_hujiid'); # :sharvahl_sergeant_hujiid_lt:
INSERT INTO loottable(name) VALUES('sharvahl_shainai'); # :sharvahl_shainai_lt:
INSERT INTO loottable(name) VALUES('sharvahl_shroyer'); # :sharvahl_shroyer_lt:
INSERT INTO loottable(name) VALUES('sharvahl_soroush_koroun'); # :sharvahl_soroush_koroun_lt:
INSERT INTO loottable(name) VALUES('sharvahl_soulbinder_ghula'); # :sharvahl_soulbinder_ghula_lt:
INSERT INTO loottable(name) VALUES('sharvahl_spiritcaller_gaarus'); # :sharvahl_spiritcaller_gaarus_lt:
INSERT INTO loottable(name) VALUES('sharvahl_spiritist_fehril'); # :sharvahl_spiritist_fehril_lt:
INSERT INTO loottable(name) VALUES('sharvahl_spiritist_garig'); # :sharvahl_spiritist_garig_lt:
INSERT INTO loottable(name) VALUES('sharvahl_spiritist_ragnar'); # :sharvahl_spiritist_ragnar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_spiritist_zoliq'); # :sharvahl_spiritist_zoliq_lt:
INSERT INTO loottable(name) VALUES('sharvahl_supply_master_guresh'); # :sharvahl_supply_master_guresh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_supply_sergeant_kerfar'); # :sharvahl_supply_sergeant_kerfar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_arek'); # :sharvahl_taruun_arek_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_arok'); # :sharvahl_taruun_arok_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_falek'); # :sharvahl_taruun_falek_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_galorg'); # :sharvahl_taruun_galorg_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_ahjek'); # :sharvahl_taruun_guardian_ahjek_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_ayam'); # :sharvahl_taruun_guardian_ayam_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_crarla'); # :sharvahl_taruun_guardian_crarla_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_dehram'); # :sharvahl_taruun_guardian_dehram_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_faiiq'); # :sharvahl_taruun_guardian_faiiq_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_gorian'); # :sharvahl_taruun_guardian_gorian_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_graar'); # :sharvahl_taruun_guardian_graar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_haman'); # :sharvahl_taruun_guardian_haman_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_hyar'); # :sharvahl_taruun_guardian_hyar_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_itaral'); # :sharvahl_taruun_guardian_itaral_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_jaamil'); # :sharvahl_taruun_guardian_jaamil_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_jarib'); # :sharvahl_taruun_guardian_jarib_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_jimoul'); # :sharvahl_taruun_guardian_jimoul_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_lilian'); # :sharvahl_taruun_guardian_lilian_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_maliij'); # :sharvahl_taruun_guardian_maliij_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_rawarr'); # :sharvahl_taruun_guardian_rawarr_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guardian_thurad'); # :sharvahl_taruun_guardian_thurad_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_guard_imil'); # :sharvahl_taruun_guard_imil_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_jaur'); # :sharvahl_taruun_jaur_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_jhilia'); # :sharvahl_taruun_jhilia_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_joharr'); # :sharvahl_taruun_joharr_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_olmek'); # :sharvahl_taruun_olmek_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_rolom'); # :sharvahl_taruun_rolom_lt:
INSERT INTO loottable(name) VALUES('sharvahl_taruun_sian'); # :sharvahl_taruun_sian_lt:
INSERT INTO loottable(name) VALUES('sharvahl_tax_collector_khugra'); # :sharvahl_tax_collector_khugra_lt:
INSERT INTO loottable(name) VALUES('sharvahl_the_room'); # :sharvahl_the_room_lt:
INSERT INTO loottable(name) VALUES('sharvahl_toxicologist_tariid'); # :sharvahl_toxicologist_tariid_lt:
INSERT INTO loottable(name) VALUES('sharvahl_trade_historian_hajika'); # :sharvahl_trade_historian_hajika_lt:
INSERT INTO loottable(name) VALUES('sharvahl_trapamyamu'); # :sharvahl_trapamyamu_lt:
INSERT INTO loottable(name) VALUES('sharvahl_uhlma_mareesh'); # :sharvahl_uhlma_mareesh_lt:
INSERT INTO loottable(name) VALUES('sharvahl_ulman_talmil'); # :sharvahl_ulman_talmil_lt:
INSERT INTO loottable(name) VALUES('sharvahl_utilayma'); # :sharvahl_utilayma_lt:
INSERT INTO loottable(name) VALUES('sharvahl_veteran_azamin'); # :sharvahl_veteran_azamin_lt:
INSERT INTO loottable(name) VALUES('sharvahl_vlarha_myticla'); # :sharvahl_vlarha_myticla_lt:
INSERT INTO loottable(name) VALUES('sharvahl_vrasha_piennsa'); # :sharvahl_vrasha_piennsa_lt:
INSERT INTO loottable(name) VALUES('sharvahl_warder_keeper_jyk'); # :sharvahl_warder_keeper_jyk_lt:
INSERT INTO loottable(name) VALUES('sharvahl_weapons_master_rahoul'); # :sharvahl_weapons_master_rahoul_lt:
INSERT INTO loottable(name) VALUES('sharvahl_weapons_master_wygans'); # :sharvahl_weapons_master_wygans_lt:
INSERT INTO loottable(name) VALUES('sharvahl_yhlia_gazeehr'); # :sharvahl_yhlia_gazeehr_lt:
INSERT INTO loottable(name) VALUES('sharvahl__'); # :sharvahl___lt:
