UPDATE npc_types SET loottable_id = :tenebrous_aellana_barleou_lt: WHERE id in (172074); # #Aellana_Barleou 20
UPDATE npc_types SET loottable_id = :tenebrous_an_invis_slayer_lt: WHERE id in (172173); # #an_invis_slayer 1
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_general_lt: WHERE id in (172185); # #a_coterie_general 46
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_insatiate_lt: WHERE id in (172189); # #a_Coterie_insatiate 60
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_warlord_lt: WHERE id in (172167); # #a_cral_ligi_warlord 40
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_warlord_lt: WHERE id in (172083); # #a_grol_baku_warlord 41
UPDATE npc_types SET loottable_id = :tenebrous_a_howl_lt: WHERE id in (172142); # #A_howl 75
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_warlord_lt: WHERE id in (172169); # #a_meeda_hune_warlord 42
UPDATE npc_types SET loottable_id = :tenebrous_bedlavar_lt: WHERE id in (172043); # #Bedlavar 44
UPDATE npc_types SET loottable_id = :tenebrous_coterie_corruptor_lt: WHERE id in (172188); # #Coterie_Corruptor 56
UPDATE npc_types SET loottable_id = :tenebrous_dead_heratius_lt: WHERE id in (172181); # #Dead_Heratius 1
UPDATE npc_types SET loottable_id = :tenebrous_dead_valdanov_lt: WHERE id in (172128); # #Dead_Valdanov 1
UPDATE npc_types SET loottable_id = :tenebrous_disciple_of_focus_lt: WHERE id in (172192); # #Disciple_of_Focus 72
UPDATE npc_types SET loottable_id = :tenebrous_drovalak_lt: WHERE id in (172046); # #Drovalak 44
UPDATE npc_types SET loottable_id = :tenebrous_galinious_lt: WHERE id in (172045); # #Galinious 44
UPDATE npc_types SET loottable_id = :tenebrous_heratius_grolden_lt: WHERE id in (172155); # #Heratius_Grolden 58
UPDATE npc_types SET loottable_id = :tenebrous_heratius_placeholder_lt: WHERE id in (172168); # #heratius_placeholder 1
UPDATE npc_types SET loottable_id = :tenebrous_hoober_lt: WHERE id in (172182); # #Hoober 31
UPDATE npc_types SET loottable_id = :tenebrous_hoobers_pet_lt: WHERE id in (172076, 172087); # #Hoober`s_Pet 30
UPDATE npc_types SET loottable_id = :tenebrous_invisible_trigger_four_lt: WHERE id in (172116); # #invisible_trigger_four 1
UPDATE npc_types SET loottable_id = :tenebrous_invisible_trigger_one_lt: WHERE id in (172129); # #invisible_trigger_one 1
UPDATE npc_types SET loottable_id = :tenebrous_invisible_trigger_three_lt: WHERE id in (172122); # #invisible_trigger_three 1
UPDATE npc_types SET loottable_id = :tenebrous_invisible_trigger_two_lt: WHERE id in (172096); # #invisible_trigger_two 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_eight_lt: WHERE id in (172139); # #invis_johanius_eight 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_eleven_lt: WHERE id in (172127); # #invis_johanius_eleven 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_five_lt: WHERE id in (172119); # #invis_johanius_five 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_four_lt: WHERE id in (172101); # #invis_johanius_four 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_nine_lt: WHERE id in (172152); # #invis_johanius_nine 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_one_lt: WHERE id in (172136); # #invis_johanius_one 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_seven_lt: WHERE id in (172093); # #invis_johanius_seven 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_six_lt: WHERE id in (172104); # #invis_johanius_six 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_ten_lt: WHERE id in (172172); # #invis_johanius_ten 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_three_lt: WHERE id in (172106); # #invis_johanius_three 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_johanius_two_lt: WHERE id in (172137); # #invis_johanius_two 1
UPDATE npc_types SET loottable_id = :tenebrous_johanius_barleou_lt: WHERE id in (172032); # #Johanius_Barleou 24
UPDATE npc_types SET loottable_id = :tenebrous_johanius_barleou_the_slayer_lt: WHERE id in (172166); # #Johanius_Barleou_the_Slayer 24
UPDATE npc_types SET loottable_id = :tenebrous_kerzar_clawtore_lt: WHERE id in (172187); # #Kerzar_Clawtore 46
UPDATE npc_types SET loottable_id = :tenebrous_lyrra_rutledge_lt: WHERE id in (172073); # #Lyrra_Rutledge 20
UPDATE npc_types SET loottable_id = :tenebrous_sir_johanius_barleou_lt: WHERE id in (172111); # #Sir_Johanius_Barleou 24
UPDATE npc_types SET loottable_id = :tenebrous_trigger_kerzar_clawtore_lt: WHERE id in (172186); # #Trigger_Kerzar_Clawtore 46
UPDATE npc_types SET loottable_id = :tenebrous_valdanov_zevfeer_lt: WHERE id in (172184); # #Valdanov_Zevfeer 62
UPDATE npc_types SET loottable_id = :tenebrous_volatilis_monitor_lt: WHERE id in (172180); # #volatilis_monitor 1
UPDATE npc_types SET loottable_id = :tenebrous_an_ancient_darkwing_bat_lt: WHERE id in (172112); # an_ancient_darkwing_bat 38
UPDATE npc_types SET loottable_id = :tenebrous_a_buried_vampyre_lt: WHERE id in (172158); # a_buried_vampyre 1
UPDATE npc_types SET loottable_id = :tenebrous_a_chained_meeda_hune_soldier_lt: WHERE id in (172135); # a_chained_meeda_hune_soldier 40
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_campaigner_lt: WHERE id in (172179); # a_coterie_campaigner 40
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_centurion_lt: WHERE id in (172190, 172004, 172005, 172006, 172007, 172021); # a_coterie_centurion 39
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_cohort_lt: WHERE id in (172107); # a_coterie_cohort 40
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_combatant_lt: WHERE id in (172156); # a_coterie_combatant 40
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_commander_lt: WHERE id in (172125); # a_coterie_commander 39
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_duelist_lt: WHERE id in (172140); # a_coterie_duelist 40
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_fighter_lt: WHERE id in (172097); # a_coterie_fighter 39
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_general_lt: WHERE id in (172001); # a_coterie_general 46
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_guard_lt: WHERE id in (172068); # a_coterie_guard 40
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_legionnaire_lt: WHERE id in (172053, 172054, 172055, 172056, 172026); # a_coterie_legionnaire 37
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_mercenary_lt: WHERE id in (172148); # a_coterie_mercenary 36
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_officer_lt: WHERE id in (172160); # a_coterie_officer 40
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_scout_lt: WHERE id in (172115); # a_coterie_scout 38
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_soldier_lt: WHERE id in (172091); # a_coterie_soldier 37
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_swordsman_lt: WHERE id in (172163); # a_coterie_swordsman 40
UPDATE npc_types SET loottable_id = :tenebrous_a_coterie_trooper_lt: WHERE id in (172102); # a_coterie_trooper 40
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_airmaster_lt: WHERE id in (172118); # a_cral_ligi_airmaster 40
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_ancient_lt: WHERE id in (172170); # a_cral_ligi_ancient 39
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_burglar_lt: WHERE id in (172134); # a_cral_ligi_burglar 39
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_energist_lt: WHERE id in (172153); # a_cral_ligi_energist 38
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_lorekeeper_lt: WHERE id in (172085); # a_cral_ligi_lorekeeper 39
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_mediator_lt: WHERE id in (172165); # a_cral_ligi_mediator 39
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_molder_lt: WHERE id in (172098); # a_cral_ligi_molder 38
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_ringbearer_lt: WHERE id in (172176); # a_cral_ligi_ringbearer 39
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_runner_lt: WHERE id in (172110); # a_cral_ligi_runner 40
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_skinner_lt: WHERE id in (172120); # a_cral_ligi_skinner 39
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_soldier_lt: WHERE id in (172040, 172042, 172072, 172014, 172031); # a_cral_ligi_soldier 35
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_tailor_lt: WHERE id in (172108); # a_cral_ligi_tailor 39
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_torchbearer_lt: WHERE id in (172147); # a_cral_ligi_torchbearer 39
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_weaver_lt: WHERE id in (172095); # a_cral_ligi_weaver 39
UPDATE npc_types SET loottable_id = :tenebrous_a_cral_ligi_writer_lt: WHERE id in (172051); # a_cral_ligi_writer 38
UPDATE npc_types SET loottable_id = :tenebrous_a_darkwing_bat_lt: WHERE id in (172039, 172008, 172009, 172010, 172027); # a_darkwing_bat 32
UPDATE npc_types SET loottable_id = :tenebrous_a_dire_sonic_wolf_lt: WHERE id in (172038, 172011, 172025); # a_dire_sonic_wolf 35
UPDATE npc_types SET loottable_id = :tenebrous_a_fanged_darkwing_bat_lt: WHERE id in (172146); # a_fanged_darkwing_bat 36
UPDATE npc_types SET loottable_id = :tenebrous_a_feral_darkwing_bat_lt: WHERE id in (172171); # a_feral_darkwing_bat 35
UPDATE npc_types SET loottable_id = :tenebrous_a_fierce_darkwing_bat_lt: WHERE id in (172150); # a_fierce_darkwing_bat 38
UPDATE npc_types SET loottable_id = :tenebrous_a_frenzied_darkwing_bat_lt: WHERE id in (172174); # a_frenzied_darkwing_bat 36
UPDATE npc_types SET loottable_id = :tenebrous_a_greater_darkwing_bat_lt: WHERE id in (172000); # a_greater_darkwing_bat 38
UPDATE npc_types SET loottable_id = :tenebrous_a_grey_darkwing_bat_lt: WHERE id in (172143); # a_grey_darkwing_bat 38
UPDATE npc_types SET loottable_id = :tenebrous_a_grimling_foreman_lt: WHERE id in (172082); # a_grimling_foreman 38
UPDATE npc_types SET loottable_id = :tenebrous_a_grimling_geomancer_lt: WHERE id in (172065, 172018, 172028); # a_grimling_geomancer 33
UPDATE npc_types SET loottable_id = :tenebrous_a_grimling_laborer_lt: WHERE id in (172019); # a_grimling_laborer 30
UPDATE npc_types SET loottable_id = :tenebrous_a_grimling_orefinder_lt: WHERE id in (172012, 172013, 172024); # a_grimling_orefinder 32
UPDATE npc_types SET loottable_id = :tenebrous_a_grimling_runner_lt: WHERE id in (172060); # a_grimling_runner 34
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_armsman_lt: WHERE id in (172175); # a_grol_baku_armsman 39
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_chanter_lt: WHERE id in (172084); # a_grol_baku_chanter 37
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_crystalus_lt: WHERE id in (172078); # a_grol_baku_crystalus 39
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_earthmaster_lt: WHERE id in (172069); # a_grol_baku_earthmaster 40
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_embedder_lt: WHERE id in (172138); # a_grol_baku_embedder 37
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_engraver_lt: WHERE id in (172094); # a_grol_baku_engraver 37
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_frightling_lt: WHERE id in (172133); # a_grol_baku_frightling 39
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_greenling_lt: WHERE id in (172049); # a_grol_baku_greenling 37
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_hero_lt: WHERE id in (172022); # a_grol_baku_hero 39
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_miner_lt: WHERE id in (172029); # a_grol_baku_miner 38
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_pyro_lt: WHERE id in (172121); # a_grol_baku_pyro 40
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_ritualist_lt: WHERE id in (172035); # a_grol_baku_ritualist 39
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_seer_lt: WHERE id in (172090); # a_grol_baku_seer 37
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_soldier_lt: WHERE id in (172034, 172037, 172071, 172016, 172030); # a_grol_baku_soldier 37
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_wilder_lt: WHERE id in (172017); # a_grol_baku_wilder 37
UPDATE npc_types SET loottable_id = :tenebrous_a_grol_baku_youth_lt: WHERE id in (172075); # a_grol_baku_youth 37
UPDATE npc_types SET loottable_id = :tenebrous_a_killer_darkwing_bat_lt: WHERE id in (172057); # a_killer_darkwing_bat 38
UPDATE npc_types SET loottable_id = :tenebrous_a_large_darkwing_bat_lt: WHERE id in (172033); # a_large_darkwing_bat 39
UPDATE npc_types SET loottable_id = :tenebrous_a_light_sonic_wolf_lt: WHERE id in (172161); # a_light_sonic_wolf 36
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_airlord_lt: WHERE id in (172123); # a_meeda_hune_airlord 39
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_animalist_lt: WHERE id in (172164); # a_meeda_hune_animalist 40
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_dancer_lt: WHERE id in (172109); # a_meeda_hune_dancer 38
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_dreadlord_lt: WHERE id in (172131); # a_meeda_hune_dreadlord 40
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_hatter_lt: WHERE id in (172126); # a_meeda_hune_hatter 39
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_hero_lt: WHERE id in (172089); # a_meeda_hune_hero 39
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_hopeful_lt: WHERE id in (172154); # a_meeda_hune_hopeful 40
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_justicar_lt: WHERE id in (172113); # a_meeda_hune_justicar 40
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_lordling_lt: WHERE id in (172114); # a_meeda_hune_lordling 39
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_noble_lt: WHERE id in (172100); # a_meeda_hune_noble 40
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_rager_lt: WHERE id in (172105); # a_meeda_hune_rager 38
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_rock_collector_lt: WHERE id in (172145); # a_meeda_hune_rock_collector 38
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_runemaster_lt: WHERE id in (172124); # a_meeda_hune_runemaster 38
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_soldier_lt: WHERE id in (172050, 172070, 172015); # a_meeda_hune_soldier 40
UPDATE npc_types SET loottable_id = :tenebrous_a_meeda_hune_stormbrewer_lt: WHERE id in (172149); # a_meeda_hune_stormbrewer 35
UPDATE npc_types SET loottable_id = :tenebrous_a_nasty_darkwing_bat_lt: WHERE id in (172141); # a_nasty_darkwing_bat 36
UPDATE npc_types SET loottable_id = :tenebrous_a_shadowed_darkwing_bat_lt: WHERE id in (172157); # a_shadowed_darkwing_bat 38
UPDATE npc_types SET loottable_id = :tenebrous_a_tormented_vah_shir_lt: WHERE id in (172117, 172130); # a_tormented_vah_shir 36
UPDATE npc_types SET loottable_id = :tenebrous_a_true_darkwing_bat_lt: WHERE id in (172023); # a_true_darkwing_bat 38
UPDATE npc_types SET loottable_id = :tenebrous_colain_jasior_lt: WHERE id in (172159); # Colain_Jasior 40
UPDATE npc_types SET loottable_id = :tenebrous_courier_balious_lt: WHERE id in (172052, 172079, 172086); # Courier_Balious 38
UPDATE npc_types SET loottable_id = :tenebrous_daksins_lt: WHERE id in (172036); # Daksins 30
UPDATE npc_types SET loottable_id = :tenebrous_emissary_oomgado_lt: WHERE id in (172151); # Emissary_Oomgado 49
UPDATE npc_types SET loottable_id = :tenebrous_felodius_sworddancer_lt: WHERE id in (172058); # Felodius_Sworddancer 55
UPDATE npc_types SET loottable_id = :tenebrous_gorelaz_verilak_lt: WHERE id in (172061); # Gorelaz_Verilak 50
UPDATE npc_types SET loottable_id = :tenebrous_hoober_lt: WHERE id in (172077, 172088); # Hoober 31
UPDATE npc_types SET loottable_id = :tenebrous_invisihoo_lt: WHERE id in (172162); # Invisihoo 1
UPDATE npc_types SET loottable_id = :tenebrous_invis_grave_placeholder_lt: WHERE id in (172103, 172132); # invis_grave_placeholder 1
UPDATE npc_types SET loottable_id = :tenebrous_kerzar_clawtore_lt: WHERE id in (172183); # Kerzar_Clawtore 46
UPDATE npc_types SET loottable_id = :tenebrous_krellices_lt: WHERE id in (172044); # Krellices 44
UPDATE npc_types SET loottable_id = :tenebrous_kristov_otto_lt: WHERE id in (172048); # Kristov_Otto 52
UPDATE npc_types SET loottable_id = :tenebrous_legionnaire_doctalious_lt: WHERE id in (172066, 172081, 172002); # Legionnaire_Doctalious 36
UPDATE npc_types SET loottable_id = :tenebrous_legionnaire_falion_lt: WHERE id in (172064); # Legionnaire_Falion 35
UPDATE npc_types SET loottable_id = :tenebrous_legionnaire_kovenic_lt: WHERE id in (172063, 172092); # Legionnaire_Kovenic 36
UPDATE npc_types SET loottable_id = :tenebrous_legionnaire_spaldres_lt: WHERE id in (172080, 172003); # Legionnaire_Spaldres 35
UPDATE npc_types SET loottable_id = :tenebrous_ore_shipment_lt: WHERE id in (172144, 172177); # ore_shipment 1
UPDATE npc_types SET loottable_id = :tenebrous_renaldok_masric_lt: WHERE id in (172062); # Renaldok_Masric 50
UPDATE npc_types SET loottable_id = :tenebrous_skyshadow_lt: WHERE id in (172178); # Skyshadow 42
UPDATE npc_types SET loottable_id = :tenebrous_trilexior_aeridia_lt: WHERE id in (172067); # Trilexior_Aeridia 50
UPDATE npc_types SET loottable_id = :tenebrous_tymoz_lt: WHERE id in (172047); # Tymoz 44
UPDATE npc_types SET loottable_id = :tenebrous_veynar_aeridia_lt: WHERE id in (172020); # Veynar_Aeridia 44
UPDATE npc_types SET loottable_id = :tenebrous_xenithen_sterbla_lt: WHERE id in (172059); # Xenithen_Sterbla 50
UPDATE npc_types SET loottable_id = :tenebrous_yaroslav_verilak_lt: WHERE id in (172041); # Yaroslav_Verilak 44
