INSERT INTO loottable(name) VALUES('thedeep_a_massive_burrower'); # :thedeep_a_massive_burrower_lt:
INSERT INTO loottable(name) VALUES('thedeep_oldencamp_the_lost'); # :thedeep_oldencamp_the_lost_lt:
INSERT INTO loottable(name) VALUES('thedeep_pingerman'); # :thedeep_pingerman_lt:
INSERT INTO loottable(name) VALUES('thedeep_trapman'); # :thedeep_trapman_lt:
INSERT INTO loottable(name) VALUES('thedeep_ancient_thought_horror_trap'); # :thedeep_ancient_thought_horror_trap_lt:
INSERT INTO loottable(name) VALUES('thedeep_an_ancient_shrieker'); # :thedeep_an_ancient_shrieker_lt:
INSERT INTO loottable(name) VALUES('thedeep_an_ancient_thought_horror'); # :thedeep_an_ancient_thought_horror_lt:
INSERT INTO loottable(name) VALUES('thedeep_an_elder_thought_horror'); # :thedeep_an_elder_thought_horror_lt:
INSERT INTO loottable(name) VALUES('thedeep_an_enthralled_outcast'); # :thedeep_an_enthralled_outcast_lt:
INSERT INTO loottable(name) VALUES('thedeep_an_enthralled_razorfiend'); # :thedeep_an_enthralled_razorfiend_lt:
INSERT INTO loottable(name) VALUES('thedeep_an_enthralled_underbulk'); # :thedeep_an_enthralled_underbulk_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_burrower_parasite'); # :thedeep_a_burrower_parasite_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_core_burrower'); # :thedeep_a_core_burrower_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_deepspore_mushroom'); # :thedeep_a_deepspore_mushroom_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_hideous_thought_leech'); # :thedeep_a_hideous_thought_leech_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_horror_guard'); # :thedeep_a_horror_guard_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_parasite_larva'); # :thedeep_a_parasite_larva_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_rock_burrower'); # :thedeep_a_rock_burrower_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_shrieker'); # :thedeep_a_shrieker_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_spined_rock_burrower'); # :thedeep_a_spined_rock_burrower_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_stone_carver'); # :thedeep_a_stone_carver_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_thought_horror'); # :thedeep_a_thought_horror_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_thought_horror_evoker'); # :thedeep_a_thought_horror_evoker_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_thought_horror_spiriter'); # :thedeep_a_thought_horror_spiriter_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_thought_leech'); # :thedeep_a_thought_leech_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_thought_leech_evoker'); # :thedeep_a_thought_leech_evoker_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_thought_leech_spiriter'); # :thedeep_a_thought_leech_spiriter_lt:
INSERT INTO loottable(name) VALUES('thedeep_a_young_thought_leech'); # :thedeep_a_young_thought_leech_lt:
INSERT INTO loottable(name) VALUES('thedeep_chasm_overseer'); # :thedeep_chasm_overseer_lt:
INSERT INTO loottable(name) VALUES('thedeep_deklean_korgad'); # :thedeep_deklean_korgad_lt:
INSERT INTO loottable(name) VALUES('thedeep_deranged_underbulk'); # :thedeep_deranged_underbulk_lt:
INSERT INTO loottable(name) VALUES('thedeep_eleven'); # :thedeep_eleven_lt:
INSERT INTO loottable(name) VALUES('thedeep_grigor_rojha'); # :thedeep_grigor_rojha_lt:
INSERT INTO loottable(name) VALUES('thedeep_koxiux_the_imperceptible'); # :thedeep_koxiux_the_imperceptible_lt:
INSERT INTO loottable(name) VALUES('thedeep_lhurgoz_the_decayed'); # :thedeep_lhurgoz_the_decayed_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_eight'); # :thedeep_light_spawn_eight_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_eleven'); # :thedeep_light_spawn_eleven_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_five'); # :thedeep_light_spawn_five_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_four'); # :thedeep_light_spawn_four_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_nine'); # :thedeep_light_spawn_nine_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_one'); # :thedeep_light_spawn_one_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_seven'); # :thedeep_light_spawn_seven_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_six'); # :thedeep_light_spawn_six_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_ten'); # :thedeep_light_spawn_ten_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_three'); # :thedeep_light_spawn_three_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_twelve'); # :thedeep_light_spawn_twelve_lt:
INSERT INTO loottable(name) VALUES('thedeep_light_spawn_two'); # :thedeep_light_spawn_two_lt:
INSERT INTO loottable(name) VALUES('thedeep_slavekeeper_xiox'); # :thedeep_slavekeeper_xiox_lt:
INSERT INTO loottable(name) VALUES('thedeep_spore_filled_shrieker'); # :thedeep_spore_filled_shrieker_lt:
INSERT INTO loottable(name) VALUES('thedeep_the'); # :thedeep_the_lt:
INSERT INTO loottable(name) VALUES('thedeep_the_burrower_beast'); # :thedeep_the_burrower_beast_lt:
INSERT INTO loottable(name) VALUES('thedeep_the_giant_burrower'); # :thedeep_the_giant_burrower_lt:
INSERT INTO loottable(name) VALUES('thedeep_thought_horror_corrupter'); # :thedeep_thought_horror_corrupter_lt:
INSERT INTO loottable(name) VALUES('thedeep_thought_horror_overfiend'); # :thedeep_thought_horror_overfiend_lt:
INSERT INTO loottable(name) VALUES('thedeep_twelve'); # :thedeep_twelve_lt:
INSERT INTO loottable(name) VALUES('thedeep_xeximoz'); # :thedeep_xeximoz_lt:
