INSERT INTO loottable(name) VALUES('thegrey_an_ancient_shissar_servitor'); # :thegrey_an_ancient_shissar_servitor_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_shattered_golem'); # :thegrey_a_shattered_golem_lt:
INSERT INTO loottable(name) VALUES('thegrey_boulder'); # :thegrey_boulder_lt:
INSERT INTO loottable(name) VALUES('thegrey_heirophant_grazan'); # :thegrey_heirophant_grazan_lt:
INSERT INTO loottable(name) VALUES('thegrey_revenant_sthzzzizt'); # :thegrey_revenant_sthzzzizt_lt:
INSERT INTO loottable(name) VALUES('thegrey_revenant_zsshta'); # :thegrey_revenant_zsshta_lt:
INSERT INTO loottable(name) VALUES('thegrey_stonehand'); # :thegrey_stonehand_lt:
INSERT INTO loottable(name) VALUES('thegrey_an_airless'); # :thegrey_an_airless_lt:
INSERT INTO loottable(name) VALUES('thegrey_an_eternal_golem'); # :thegrey_an_eternal_golem_lt:
INSERT INTO loottable(name) VALUES('thegrey_an_iksar_slave'); # :thegrey_an_iksar_slave_lt:
INSERT INTO loottable(name) VALUES('thegrey_an_undying_iksar'); # :thegrey_an_undying_iksar_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_boulderling'); # :thegrey_a_boulderling_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_boulder_fiend'); # :thegrey_a_boulder_fiend_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_creature'); # :thegrey_a_creature_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_foreboding'); # :thegrey_a_foreboding_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_forgotten_slave'); # :thegrey_a_forgotten_slave_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_forlorn_slave'); # :thegrey_a_forlorn_slave_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_plain'); # :thegrey_a_plain_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_shimmering_rockfiend'); # :thegrey_a_shimmering_rockfiend_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_shissar_revenant'); # :thegrey_a_shissar_revenant_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_shissar_stalker'); # :thegrey_a_shissar_stalker_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_stone_beast'); # :thegrey_a_stone_beast_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_sun_revenant'); # :thegrey_a_sun_revenant_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_timeless_golem'); # :thegrey_a_timeless_golem_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_tormented_iksar_slave'); # :thegrey_a_tormented_iksar_slave_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_xakra_sei'); # :thegrey_a_xakra_sei_lt:
INSERT INTO loottable(name) VALUES('thegrey_a_xakra_shah'); # :thegrey_a_xakra_shah_lt:
INSERT INTO loottable(name) VALUES('thegrey_crusader_kezzal'); # :thegrey_crusader_kezzal_lt:
INSERT INTO loottable(name) VALUES('thegrey_scout_tovi'); # :thegrey_scout_tovi_lt:
INSERT INTO loottable(name) VALUES('thegrey_the_sand'); # :thegrey_the_sand_lt:
INSERT INTO loottable(name) VALUES('thegrey_the_skin'); # :thegrey_the_skin_lt:
INSERT INTO loottable(name) VALUES('thegrey_trap_ph'); # :thegrey_trap_ph_lt:
INSERT INTO loottable(name) VALUES('thegrey_trembling_earthquake_elemental'); # :thegrey_trembling_earthquake_elemental_lt:
INSERT INTO loottable(name) VALUES('thegrey_your_breath'); # :thegrey_your_breath_lt:
