INSERT INTO loottable(name) VALUES('umbral_a_netherbian_flesheater'); # :umbral_a_netherbian_flesheater_lt:
INSERT INTO loottable(name) VALUES('umbral_a_netherbian_hive_fiend'); # :umbral_a_netherbian_hive_fiend_lt:
INSERT INTO loottable(name) VALUES('umbral_a_netherbian_ravager'); # :umbral_a_netherbian_ravager_lt:
INSERT INTO loottable(name) VALUES('umbral_bile_spew'); # :umbral_bile_spew_lt:
INSERT INTO loottable(name) VALUES('umbral_binkl_dirkwafer'); # :umbral_binkl_dirkwafer_lt:
INSERT INTO loottable(name) VALUES('umbral_bloodwretch'); # :umbral_bloodwretch_lt:
INSERT INTO loottable(name) VALUES('umbral_doomshade'); # :umbral_doomshade_lt:
INSERT INTO loottable(name) VALUES('umbral_festersore'); # :umbral_festersore_lt:
INSERT INTO loottable(name) VALUES('umbral_fleshrot'); # :umbral_fleshrot_lt:
INSERT INTO loottable(name) VALUES('umbral_fyrthek_fior'); # :umbral_fyrthek_fior_lt:
INSERT INTO loottable(name) VALUES('umbral_keymaster'); # :umbral_keymaster_lt:
INSERT INTO loottable(name) VALUES('umbral_netherbian_swarmfiend'); # :umbral_netherbian_swarmfiend_lt:
INSERT INTO loottable(name) VALUES('umbral_rumblecrush'); # :umbral_rumblecrush_lt:
INSERT INTO loottable(name) VALUES('umbral_sylra_fris'); # :umbral_sylra_fris_lt:
INSERT INTO loottable(name) VALUES('umbral_zelnithak'); # :umbral_zelnithak_lt:
INSERT INTO loottable(name) VALUES('umbral_an_ancient_whisperling'); # :umbral_an_ancient_whisperling_lt:
INSERT INTO loottable(name) VALUES('umbral_an_unearthly_wail'); # :umbral_an_unearthly_wail_lt:
INSERT INTO loottable(name) VALUES('umbral_a_chest'); # :umbral_a_chest_lt:
INSERT INTO loottable(name) VALUES('umbral_a_corrupted_elysian_elder'); # :umbral_a_corrupted_elysian_elder_lt:
INSERT INTO loottable(name) VALUES('umbral_a_dark_assassin'); # :umbral_a_dark_assassin_lt:
INSERT INTO loottable(name) VALUES('umbral_a_dark_master'); # :umbral_a_dark_master_lt:
INSERT INTO loottable(name) VALUES('umbral_a_fallen_soldier'); # :umbral_a_fallen_soldier_lt:
INSERT INTO loottable(name) VALUES('umbral_a_fyr_jen_fire_caller'); # :umbral_a_fyr_jen_fire_caller_lt:
INSERT INTO loottable(name) VALUES('umbral_a_fyr_jen_flame_warder'); # :umbral_a_fyr_jen_flame_warder_lt:
INSERT INTO loottable(name) VALUES('umbral_a_fyr_jen_guardian'); # :umbral_a_fyr_jen_guardian_lt:
INSERT INTO loottable(name) VALUES('umbral_a_gantru_moktor'); # :umbral_a_gantru_moktor_lt:
INSERT INTO loottable(name) VALUES('umbral_a_gantru_raldukan'); # :umbral_a_gantru_raldukan_lt:
INSERT INTO loottable(name) VALUES('umbral_a_gantru_shojen'); # :umbral_a_gantru_shojen_lt:
INSERT INTO loottable(name) VALUES('umbral_a_gantru_shojilen'); # :umbral_a_gantru_shojilen_lt:
INSERT INTO loottable(name) VALUES('umbral_a_gargantuan_zelniak'); # :umbral_a_gargantuan_zelniak_lt:
INSERT INTO loottable(name) VALUES('umbral_a_guardian_spirit'); # :umbral_a_guardian_spirit_lt:
INSERT INTO loottable(name) VALUES('umbral_a_massive_stone_guardian'); # :umbral_a_massive_stone_guardian_lt:
INSERT INTO loottable(name) VALUES('umbral_a_netherbian_flesheater'); # :umbral_a_netherbian_flesheater_lt:
INSERT INTO loottable(name) VALUES('umbral_a_netherbian_hive_fiend'); # :umbral_a_netherbian_hive_fiend_lt:
INSERT INTO loottable(name) VALUES('umbral_a_netherbian_infestor'); # :umbral_a_netherbian_infestor_lt:
INSERT INTO loottable(name) VALUES('umbral_a_netherbian_ravager'); # :umbral_a_netherbian_ravager_lt:
INSERT INTO loottable(name) VALUES('umbral_a_netherbian_ravager_'); # :umbral_a_netherbian_ravager__lt:
INSERT INTO loottable(name) VALUES('umbral_a_netherbian_seeker'); # :umbral_a_netherbian_seeker_lt:
INSERT INTO loottable(name) VALUES('umbral_a_shadowy_assassin'); # :umbral_a_shadowy_assassin_lt:
INSERT INTO loottable(name) VALUES('umbral_a_syl_ren_frost_caller'); # :umbral_a_syl_ren_frost_caller_lt:
INSERT INTO loottable(name) VALUES('umbral_a_syl_ren_frost_warder'); # :umbral_a_syl_ren_frost_warder_lt:
INSERT INTO loottable(name) VALUES('umbral_a_syl_ren_guardian'); # :umbral_a_syl_ren_guardian_lt:
INSERT INTO loottable(name) VALUES('umbral_a_tortured_scream'); # :umbral_a_tortured_scream_lt:
INSERT INTO loottable(name) VALUES('umbral_darkmastera'); # :umbral_darkmastera_lt:
INSERT INTO loottable(name) VALUES('umbral_darkmasterb'); # :umbral_darkmasterb_lt:
INSERT INTO loottable(name) VALUES('umbral_darkmasterc'); # :umbral_darkmasterc_lt:
INSERT INTO loottable(name) VALUES('umbral_darkmasterd'); # :umbral_darkmasterd_lt:
INSERT INTO loottable(name) VALUES('umbral_disturbed_elysian_remains'); # :umbral_disturbed_elysian_remains_lt:
INSERT INTO loottable(name) VALUES('umbral_fallen_sergeant'); # :umbral_fallen_sergeant_lt:
INSERT INTO loottable(name) VALUES('umbral_gantru_dralkenr'); # :umbral_gantru_dralkenr_lt:
INSERT INTO loottable(name) VALUES('umbral_netherbian_swarmcaller'); # :umbral_netherbian_swarmcaller_lt:
INSERT INTO loottable(name) VALUES('umbral_netherbian_swarmlord'); # :umbral_netherbian_swarmlord_lt:
INSERT INTO loottable(name) VALUES('umbral_radir_fireshower'); # :umbral_radir_fireshower_lt:
INSERT INTO loottable(name) VALUES('umbral_remains_of_vah_kerrath'); # :umbral_remains_of_vah_kerrath_lt:
INSERT INTO loottable(name) VALUES('umbral_shak_dathor'); # :umbral_shak_dathor_lt:
INSERT INTO loottable(name) VALUES('umbral_shak_dathor_warlord'); # :umbral_shak_dathor_warlord_lt:
INSERT INTO loottable(name) VALUES('umbral_spirit_of_radir'); # :umbral_spirit_of_radir_lt:
INSERT INTO loottable(name) VALUES('umbral_spirit_of_tawro'); # :umbral_spirit_of_tawro_lt:
INSERT INTO loottable(name) VALUES('umbral_swarmcontroller'); # :umbral_swarmcontroller_lt:
INSERT INTO loottable(name) VALUES('umbral_swarmspawna'); # :umbral_swarmspawna_lt:
INSERT INTO loottable(name) VALUES('umbral_swarmspawnb'); # :umbral_swarmspawnb_lt:
INSERT INTO loottable(name) VALUES('umbral_swarmspawnc'); # :umbral_swarmspawnc_lt:
INSERT INTO loottable(name) VALUES('umbral_swarmspawnd'); # :umbral_swarmspawnd_lt:
INSERT INTO loottable(name) VALUES('umbral_tawro_icequake'); # :umbral_tawro_icequake_lt:
INSERT INTO loottable(name) VALUES('umbral_the_earth_rumbles'); # :umbral_the_earth_rumbles_lt:
